[1단계 - 블랙잭 구현] 멍토(김유기) 미션 제출합니다.
woowacourse/java-blackjack pull request #109
Opened 2021-03-04 06:05 UTC by daum7766

안녕하세요. 휴!
이번 미션 잘 부탁합니다. 
인터페이스를 처음 사용해봐서 어색했지만, 페어와 이야기하며 열심히 진행했습니다.

인터페이스를 이용하여 구현했더니 중복되는 부분이 발생했었습니다.
이러한 부분을 해결하기 위해 중간에 추상클래스를 추가하여 공통적인 부분은 추상클래스에서 구현하고 차이가 나는 부분만 구현하도록 했습니다.

좋았던 점 : 인터페이스를 이용하면 반환값과 형태를 미리 정할 수 있어서 상속을 받아 처리할 때 편리함을 느꼈습니다.
또한, 인터페이스를 변수 타입으로 지정하여 활용성 또한 높일 수 있었습니다.

질문 : 
1. Player 인터페이스를 이용하여 User와 Dealer를 구현했는데 User에서만 사용하는 함수가 있는 경우 User 타입을 이용하지 않으면 해당 기능을 사용하지 못하여 각자 타입으로 진행하여 이렇게 진행하는 것이 맞는 건가? 라는 생각이 들었습니다. 이런 경우는 어떻게 진행하나요?

2. 이번에 DTO를 도입하게 되었는데 페어와 이야기를 하면서 나왔던 이야기입니다.
Player DTO에는 이름, 카드 종류, 카드의 총합이 들어있습니다.
처음에 2장씩 뽑았다는 출력을 하기 위해 Player DTO를 보냈는데 여기서는 이름밖에 사용하지 않아서 따로 클래스를 만들어야 하는 거 아니냐? 라는 이야기가 나오게 되었습니다. 이런 경우는 어떻게 진행하는지 궁금합니다.

3. 딜러와 플레이어 각자 출력하는 위치가 있어서 View에 데이터를 전달할 때 Users와 dealer를 나누어 전달하게 되었습니다.
같은 인터페이스로 구현한 것이라 묶어서 보내야 하는 거 아닌가? 라는 이야기가 들었는데 묶게 되면 딜러를 제일 먼저 출력하거나 중의 출력해야 하여 딜러는 찾는 과정이 추가되는 문제가 있어 결국 나누게 되었습니다. 이럴 때 대해서는 어떻게 생각하는지 궁금합니다.

긴 글 읽어주셔서 감사합니다.

2021-03-04 08:26 UTC, daum7766 commented
# 멍토의 학습 프로필
<br>

## TDD - 5

### 내용

- 테스트를 먼저 작성 후 로직을 구현하도록 노력함

  - 테스트를 먼저 작성한 후 에러가 안 나도록 만든다.
  - 강제로 테스트를 통과하도록 설정한다.
  - 테스트 케이스를 추가하여 틀리게 만든 후 로직을 구현한다.

- 로직이 변경된다면 기존 로직을 보존한 채 리팩토링을 진행

  - 기존로직이 에러가 나지 않도록 새로 함수를 만들어 진행한다.
  - 새로운 로직이 완성된 후 기존 로직을 삭제하여 수정

- 이와 같은 진행을 하며 에러가 나지 않고 리팩토링을 진행하는데 쉽다는 점을 느끼게 됨.


### 참고

- 포비의 TDD 강의
- 우아한테크코스 TDD 예제
- Program Programming Programmer - Test Driven Development 책

<br>

## 인터페이스 - 3

### 내용

- 인터페이스를 통해서 만들어야 하는 함수명과 반환 값, 인자를 정하고 시작하는 부분에서 좋았다. 
  - 예시로 브라우저를 떠올릴 수 있었는데 그 당시 인터페이스가 정해져 있지 않아서 각자 다르게 구현된 내용 때문에 개발자들이 힘들어하고 큰 비용이 발생했었습니다. 이후 인터페이스 적용된 후 해당 브라우저에 추가된 특수한 기능이 아니라면 하나만으로 공통적용이 가능한 부분이 좋았습니다.

### 참고

- 우아한테크코스 인터페이스 예제
- https://wikidocs.net/217

<br>

## 추상클래스와 상속 - 3

### 내용

- 중복된 내용을 추상클래스로 끌어올려서 처리함으로써 중복된 내용을 많이 줄일 수 있다.
  - 저희 팀의 경우 인터페이스를 User와 Dealer가 인터페이스를 직접 상속을 받아 구현하면 중복되는 부분이 많이 생겨 중간에 추상클래스를 추가하여 중복코드를 줄였습니다.

### 참고

- 우아한 테크코스 상속 예제

<br>

## 전략패턴 - 3

### 내용

- 처음 설계 당시 딜러의 카드 2장 출력이 오류로 인하여 1개만 보이는 줄 알고 2개로 출력하였으나 알고 보니 블랙잭 규칙에서 딜러는 1장만 보여주는 것이 맞는다는 사실을 알고 수정을 하게 되었다.
- 이것을 수정하기 위하여 여러 가지 방법을 페어와 고민하게 되었으나 전략패턴을 적용하면 쉽게 수정이 가능할 것이라는 생각이 되어 적용하게 됨.
- 전략패턴과 관련된 필드를 추가하고 같은 메소드를 호출하게 되면 전략패턴 메소드를 호출하여 해당 문제를 해결함.

### 참고

- [테코톡 그래의 전략패턴](https://www.youtube.com/watch?v=zGJzEBOELoU)

- https://victorydntmd.tistory.com/292


<br>


## 싱글턴 패턴 - 2

### 내용

- Cards의 경우는 단 하나의 객체만 만들어 모든 위치에서 공유해야 한다고 생각함
- 싱글턴 패턴의 경우 해당 클래스의 객체가 프로그램에 단 하나만 존재하는 것을 보장하기에 적합하다고 생각하여 적용
- 멀티 스레드 환경에서는 적합하지 않은 경우가 있다는 부분을 보았으나 미션에서는 멀티스레드 환경이 아니므로 사용해도 된다고 생각하여 적용
  - 멀티 스레드 환경이라면 그에 따른 해결방법을 적용하면 될 것으로 생각함

### 참고

- https://gmlwjd9405.github.io/2018/07/06/singleton-pattern.html
- Head First Design Patterns - 싱글턴 패턴

2021-03-05 21:21 UTC, Hue9010 requested changes
안녕하세요 멍토! 이번 리뷰를 맡은 휴입니다 😄 
우선 리뷰가 늦었네요. 죄송합니다.😭😭
1단계 미션 잘 구현해주셨네요.👍 
질문에 대한 답변과 피드백 남겼는데 확인해주시고 궁금한건 언제든 질문주세요!(주말 신경 쓰실 필요 없습니다. 😉)

2021-03-06 09:16 UTC, daum7766 commented on src/main/java/blackjack/domain/player/Users.java
> +    public Map<Name, ResultType> getResult(Dealer dealer) {
이건 좀더 공부해보겠습니다!

2021-03-06 09:20 UTC, daum7766 commented on src/main/java/blackjack/domain/player/Dealer.java
> +    }
상태패턴에 대해서 공부해보겠습니다.

2021-03-06 09:21 UTC, daum7766 commented on src/test/java/blackjack/domain/player/UsersTest.java
> +    @DisplayName("Users 생성자 동일 비교 테스트")
여러 바아식의 생성자를 이용하여 같은 결과가 나왔는지 테스트를 하는거였는데 좀더 명칭을 정확하게 수정하겠습니다.

2021-03-06 09:22 UTC, daum7766 commented on src/main/java/blackjack/controller/BlackJackController.java
> +        }
감사합니다.

2021-03-06 09:43 UTC, daum7766 commented on src/main/java/blackjack/domain/player/Users.java
> +            .forEach(name -> users.add(new User(name)));
한번에 처리가 가능하네요! 감사합니다.

2021-03-06 10:01 UTC, daum7766 commented on src/test/java/blackjack/domain/player/NameTest.java
> +    @DisplayName("이름 유효성 검사 - 유효하지 않은 이름")
문자열이 비어있는거는 생각했는데 null에 대해서는 생각못해봤네요!
바로 추가하겠습니다.

2021-03-06 10:30 UTC, daum7766 commented on src/test/java/blackjack/domain/player/UserTest.java
> +    @ValueSource(strings = {"딜러", " jason ", " pobi"})
감사합니다.

2021-03-06 10:31 UTC, daum7766 commented on src/test/java/blackjack/domain/player/UserTest.java
> +    @DisplayName("플레이어는 갖고있는 카드들의 숫자 총 합이 21 이하일 때 선택 가능")
수정 완료했습니다.

2021-03-06 10:31 UTC, daum7766 commented on src/main/java/blackjack/domain/card/Cards.java
> +    }
네 감사합니다!

2021-03-06 12:12 UTC, daum7766 commented on src/main/java/blackjack/domain/player/User.java
> +    }
클린코드에 대해서 공부해보겠습니다. 감사합니다.

2021-03-06 13:20 UTC, daum7766 commented on src/main/java/blackjack/domain/player/Name.java
> +            throw new IllegalArgumentException("공백인 이름은 사용할 수 없습니다.");
넵 추가해보겠습니다.

2021-03-06 13:24 UTC, daum7766 commented on src/main/java/blackjack/domain/player/Player.java
> +    int getValue();
변경 완료했습니다.

2021-03-06 13:33 UTC, daum7766 commented on src/main/java/blackjack/domain/player/User.java
> +    }
적용하고 나니 가독성이 더 좋아진거같습니다!

2021-03-06 13:36 UTC, daum7766 commented on src/main/java/blackjack/view/OutputView.java
> +    }
좋은 의견 감사합니다. 많은 도움이 되었습니다.

2021-03-06 13:57 UTC, daum7766 commented on src/test/java/blackjack/domain/player/DealerTest.java
> +    @DisplayName("카드 합이 17 이상이면 카드를 추가로 받을 수 없다. - 17일 때")
말씀해주신데로 코드를 읽기전까지는 카드를 받거나 못받거나로 판단이 되네요!
바로 수정하겠습니다.

2021-03-06 15:02 UTC, daum7766 commented
휴! 바쁜주말에 봐주셔서 고마워요!
말씀해주신 피드백을 최대한 적용해 보았어요.
궁금했던 내용은 DM으로 물어봐서 많이 해결되었습니다.
제가 잘못 이해하여 반영된 내용이 있다면 피드백 부탁드려요!
감사합니다.

2021-03-06 15:20 UTC, daum7766 commented
휴! 바쁜주말에 봐주셔서 고마워요!
말씀해주신 피드백을 최대한 적용해 보았어요.
궁금했던 내용은 DM으로 물어봐서 많이 해결되었습니다.
제가 잘못 이해하여 반영된 내용이 있다면 피드백 부탁드려요!
감사합니다.

2021-03-07 14:36 UTC, Hue9010 approved these changes
멍토! 빠르게 잘 반영해주셨네요. 👍
몇가지 피드백 남겼는데 확인하시고 궁금한건 언제든 질문 주세요. 😉
이번 단계는 여기서 머지할게요. 피드백은 다음 단계때 반영하면 됩니다!

2021-03-07 14:36 UTC, Hue9010 commented on src/main/java/blackjack/exception/validateException.java
> +    }
생각보다 만드는게 어렵지 않죠? 😉

사실 지금 단계에서는 커스텀 예외를 만들어서 활용할 방법이 적은데 나중에 스프링을 학습하는 시기에는 스프링의 특정 기능을 이용하여 특정 예외 발생시 Response Status Code를 400, 404, 500, 501, 503, ...으로 응답하게 해 줄 수 있답니다. 다른 이점도 있긴하지만 직접적으로 유용하다는 걸 느끼는건 그때 일 걸로 보여요.
IllegalArgumentException이 발생할 때 400으로 응답할 수 도 있지만 그렇게 했을 때 사용자(클라이언트)가 잘못 입력한게 아닌 코드상 실수나 사용된 라이브러리 내에서 발생한 Illegal~도 400으로 응답해보리기 때문에 문제가 됩니다.

그 외에도 Integer.parseInt("some"); 처럼 사용시 발생하는 예외가 RuntimeException인데 메시지 조처 없으면 무슨 문제로 예외가 발생했는이 알려면 코드 위치를 파악해야하고, 메시지가 있어도 NumberFormatException가 발생하는 것보다는 직관적이지 못합니다.

여러모로 지금은 커스텀 예외를 만들어 보는 것만으로도 충분해 보입니다. 😉

2021-03-07 14:36 UTC, Hue9010 commented on src/main/java/blackjack/domain/player/dto/PlayerDTO.java
> +    private final int value;
dto는 value로 남겨두셨는데 의도된 걸까요? 🤔

2021-03-07 14:36 UTC, Hue9010 commented on src/main/java/blackjack/domain/player/Users.java
> +        users.forEach(AbstractPlayer::drawRandomTwoCards);
메서드 참조 👍

2021-03-07 14:36 UTC, Hue9010 commented on src/main/java/blackjack/domain/card/Card.java
> +    private final CardNumber cardNumber;
Enum명은 카드의 모양과 숫자이니까 문제 없지만 변수명은 이미 카드 객체의 shape, number라 card는 불필요해 보입니다.
(판단하기에 따라서는 Enum명의 Card도 제거해도 무방합니다.)

```java
public class Book {
private final String title;


public class Book {
private final String bookTitle;
```
첫번째 것만 봐도 book의 name이 책 제목인 걸 유추할 수 있으실겁니다. 아마 Enum이 CardNumber라서 이걸 따라간 것 같은데 변수명은 이걸 꼭 따라 갈 필요는 없답니다. 😉

지금의 변수명이다 보니
```java
card.getCardNumber()
```
와 같이 사용되고 있죠.

이는
```java
Car car = new Car();
car.runCar();
```
이와 같이 사용되고 있는 것과 마찬가지입니다.
만약
```java
Car a = new Car();
a.runCar();
```
처럼 사용한다면 runCar로 메서드명을 만드는게 유용할 수도 있긴해도...타입으로 알 수도 있고 저런 식으로 코드를 짜지 않을 테니 굳이 그럴 필요 없다고 보네요.

2021-03-07 14:36 UTC, Hue9010 commented on src/main/java/blackjack/domain/player/AbstractPlayer.java
> +    protected AbstractPlayer(String name) {
👍

2021-03-07 14:36 UTC, Hue9010 commented on src/main/java/blackjack/view/OutputView.java
> +        }
이런 작업이 끝난 데이터를 가진 DTO를 만들어 보는 것도 좋을 것 같네요. view에 필요한 데이터를 담아 보내주는거죠.😉

```java
public class GameResultDTO {
    Map<ResultType, Integer> dealerResult;
    Map<Name, ResultType> playerResult;
```
대략 이런 형태로 말이죠. 😉

2021-03-07 14:36 UTC, Hue9010 commented on src/main/java/blackjack/domain/player/User.java
> +    public ResultType getResult(Dealer dealer) {
저도 놓쳤던건데 다른 분들을 보다보니 깨달았는데 😋
지금은 유저가 버스트면 게임에서 지는데 딜러도 버스트면 무승부가 아닐까요?

2021-03-07 14:36 UTC, Hue9010 commented on src/main/java/blackjack/domain/player/User.java
> +    public ResultType getResult(Dealer dealer) {
혹시 몰라 찾아보니 유저가 버스트면 딜러가 버스트인건 상관없는게 맞군요. 😋 

`하지만 카드 숫자의 합이 21을 초과하게 되는 순간 '버스트' 라고 하며 딜러의 결과에 관계없이 플레이어가 패배한다.(설렁 딜러도 버스트가 되어도 무승부가 아닌 플레이어의 패배이다.)`
[블랙잭(카드게임)](https://namu.wiki/w/%EB%B8%94%EB%9E%99%EC%9E%AD(%EC%B9%B4%EB%93%9C%EA%B2%8C%EC%9E%84)#fn-18)
출처가 나무위키지만.. 블랙잭 규칙에 대한 정보라면 충분히 신뢰할만하지 않을까 싶어요. 🙄

2021-03-07 14:36 UTC, merged

2021-03-08 05:06 UTC, daum7766 commented on src/main/java/blackjack/domain/player/User.java
> +    public ResultType getResult(Dealer dealer) {
플레이어가 먼저죽으면 그거는 패배더라구요!

2021-03-08 05:07 UTC, daum7766 commented on src/main/java/blackjack/view/OutputView.java
> +        }
넵! 반영하겠습니다.

2021-03-08 05:07 UTC, daum7766 commented on src/main/java/blackjack/domain/card/Card.java
> +    private final CardNumber cardNumber;
반영하겠습니다!

2021-03-08 05:08 UTC, daum7766 commented on src/main/java/blackjack/domain/player/dto/PlayerDTO.java
> +    private final int value;
바꾸면서 안바꾼거같습니다. ㅜㅠ
꼼꼼하지 못했네요! 변경하겠습니다.