[1단계 - 블랙잭 구현] 욘(김영빈) 미션 제출합니다.
woowacourse/java-blackjack pull request #119
Opened 2021-03-04 08:41 UTC by thisisyoungbin

데이브 안녕하세요! 이번 블랙잭 미션 리뷰를 받게 된 욘입니다!
리뷰를 위해서 귀한 시간내주셔서 감사해요.
이번 미션을 진행하며 에이스 판별과 계산에 대한 부분, 유저와 딜러와의 승무패 여부 계산 등의 부분이 가장 어려웠던 부분 같아요.

유저와 딜러의 공통된 기능이 많아 Participant라는 객체를 만들어 유저와 딜러가 상속을 받도록 구현했습니다.
그리고 Enum을 사용해 카드의 Suit, Value를 구현했고, 참가자들의 상태와 승무패 여부를 가지도록 해봤습니다.

to do로 남겨둔 부분들은 PR 요청 후에도 계속 리팩토링 진행해보겠습니다.
리뷰하실 때 혹시라도 남아있다면 제가 인지하고 있다는 것만 참고해주세요..
저의 성장을 위해 많은 피드백 주시면 감사하겠습니다 !

2021-03-04 09:01 UTC, thisisyoungbin commented
# 학습로그

# [TDD] 단위 기능별 테스트 - 2
## 내용
- 각 도메인 구현 전 테스트를 먼저 작성한다.
- 가능한 모든 부분들에 대해 테스트 주도 개발을 진행하려 했으나 그렇지 못한 부분들이 있어 아쉽다.


# [OOP] 상속과 composition - 4
## 내용
- 추상 클래스인 Participants를 User와 Dealer가 상속받는다.
- UserGameResult는 GameResult를 가지고 GameResult의 메서드를 활용해 중복되는 코드를 최소화한다.


# [OOP] Enum Class 활용 - 3
## 내용
- 카드의 Suit, Value를 Enum 클래스를 활용해 구현한다.
- 참가자들의 승무패 여부를 WinOrLose Enum 클래스를 이용해 구현한다.
- 참가자들이 카드를 더 받을 수 있는지, 블랙잭인지 상태를 알 수 있도록 Status를 Enum 클래스를 이용해 구현한다.


# [JDK] Stream API 활용 - 3
## 내용
- collect, findAny, map 등 다양한 Stream API를 활용해 코드를 작성한다.


# [JDK] 함수형 인터페이스 활용 - 2
## 내용
- BiPredicate를 활용해 딜러와 유저의 점수를 비교한다.
- supplier를 활용해 예외처리한다.

2021-03-06 15:56 UTC, dave915 requested changes
욘 안녕하세요! 리뷰를 맡게된 데이브입니다.
리뷰가 늦어져서 죄송합니다 🙇‍♂️
피드백 몇개 남겼습니다! 
궁금한 점 있다면 언제든지 DM주세요!

2021-03-06 15:56 UTC, dave915 commented on src/main/java/blackjack/domain/card/Value.java
> +    private static List<Value> values = Arrays.stream(Value.values())
```suggestion
    private static final List<Value> values = Arrays.stream(Value.values())
```

2021-03-06 15:56 UTC, dave915 commented on src/main/java/blackjack/domain/user/Hand.java
> +    }
getValue를 호출할때 현재 점수 합을 함께 넘긴다면 Value 객체에서 Ace의 점수를 구분해서 줄 수 있지 않을까요?

2021-03-06 15:56 UTC, dave915 commented on src/main/java/blackjack/controller/BlackjackGameController.java
> +        while (blackjackGame.existCanContinueUser()) {
계속해서 while로 가능한 유저를 찾는것 보단 for를 이용해 차례대로 한번씩만 체크하는게 좋을 것 같아요 ㅎㅎ

2021-03-06 15:56 UTC, dave915 commented on src/main/java/blackjack/controller/BlackjackGameController.java
> +            blackjackGame.getDealer().drawCard(blackjackGame.draw());
blackjackGame로 부터 draw()로 Card를 얻어내 blackjackGame의 내부 상태인 Dealer에게 전달한다는게 어색한 것 같아요 🤔

2021-03-06 15:56 UTC, dave915 commented on src/main/java/blackjack/domain/BlackjackGame.java
> +                , createDealerGameResult());
따로 변수로 빼주는게 가독성이 더 좋을 것 같아요 :) 
```suggestion
        Map<User, UserGameResult> userResults = users.toList().stream()
                .collect(toMap(
                        Function.identity(),
                        this::createGameResult,
                        (exist, newer) -> newer, LinkedHashMap::new));
        return new ScoreBoard(userResults, createDealerGameResult());
```

2021-03-06 15:56 UTC, dave915 commented on src/main/java/blackjack/domain/BlackjackGame.java
> +                , createDealerGameResult());
딜러 및 유저들의 카드 출력과 승패 출력 로직이 합쳐져 있어서 더 복잡해진 것 같아요. 
두 로직을 분리해보면 어떨까요? 

```
딜러 카드: 3다이아몬드, 9클로버, 8다이아몬드 - 결과: 20
pobi카드: 2하트, 8스페이드, A클로버 - 결과: 21
jason카드: 7클로버, K스페이드 - 결과: 17

## 최종 승패
딜러: 1승 1패
pobi: 승 
jason: 패
```

2021-03-06 15:56 UTC, dave915 commented on src/main/java/blackjack/domain/user/Name.java
> +    private static final String DUPLICATE_NAME_ERROR_MSG = "중복된 이름은 존재할 수 없습니다.";
안쓰는 필드 같아요!

2021-03-06 15:56 UTC, dave915 commented on src/main/java/blackjack/domain/user/Status.java
> +    PLAYING(true, i -> 1 < i && i < 21),
21 매직넘버가 있네요.

2021-03-07 09:27 UTC, thisisyoungbin commented on src/main/java/blackjack/controller/BlackjackGameController.java
> +            blackjackGame.getDealer().drawCard(blackjackGame.draw());
유저와 딜러 모두에게 똑같은 방식으로 하고 있어서 수정해봤습니다 !

2021-03-07 09:58 UTC, thisisyoungbin commented on src/main/java/blackjack/domain/user/Hand.java
> +    }
selectValue() 메서드를 만들어서 에이스카드의 Value(11 or 1)를 구분해서 전달하도록 수정해봤습니다 :)

2021-03-07 10:00 UTC, thisisyoungbin commented on src/main/java/blackjack/controller/BlackjackGameController.java
> +        while (blackjackGame.existCanContinueUser()) {
전체 유저들을 탐색하는 불필요한 행동 제거! 를 위해 사용자 마다 카드를 더 받을 수 있는 상태인지 확인하고 물어보도록 수정했습니다 👍

2021-03-08 00:53 UTC, thisisyoungbin commented on src/main/java/blackjack/domain/BlackjackGame.java
> +                , createDealerGameResult());
카드출력과 승패출력을 분리해봤습니다! 근데 거의 컨트롤러에서 읽기 편하게 분리 시킨 느낌이라... 프로덕션 코드에서 수정해볼 부분을 놓치고 있는 것 같은데 힌트 주실 수 있나요?!

2021-03-08 17:26 UTC, dave915 commented on src/main/java/blackjack/domain/user/Status.java
> +    }
Constants 까지 만들필요가 있을까 싶어요 :) 
```suggestion
    PLAYING(true, i -> i < Status.BLACKJACK_SCORE),
    BLACKJACK(false, i -> i == Status.BLACKJACK_SCORE),
    BURST(false, i -> Status.BLACKJACK_SCORE < i),
    STOP(false, i -> false);
    
    public static final String NO_MATCH_CONDITION_ERROR_MSG = "점수 조건에 맞는 Status가 없습니다.";
    public static final int BLACKJACK_SCORE = 21;
```

2021-03-08 17:26 UTC, dave915 commented on src/main/java/blackjack/domain/card/Card.java
> +    }
```
    public int getScore(int score) {
        return value.getScore(score);
    }
```

getScore 를 위 처럼 갖고 가면 selectValue 로직은 Value 내부로 넣을 수 있을 것 같아요 :)

2021-03-08 17:26 UTC, dave915 commented on src/main/java/blackjack/domain/BlackjackGame.java
> +                , createDealerGameResult());
`Map<User, UserGameResult> userResult` 에서 UserGameResult 내부에 유저들의 카드 정보와 승패 정보 둘다 들어가있어서 해당 정보를 만드느라 복잡해 보여요.
`UserGameResult` 내부에 유저의 카드정보를 넣을 필요없이 Participant에서 들고있는 Hand 데이터를 출력시켜줘도 되지않을까요? 
`UserGameResult`는 승,패 정보만 갖고있어도 충분해보여요.

2021-03-08 17:32 UTC, dave915 requested changes
욘! 피드백 반영하신 부분 확인했어요 👍 
코멘트 답변 및 몇가지 코멘트 남겼으니 확인부탁드릴게요.
궁금한점 있다면 언제든 DM주세요!

2021-03-08 17:32 UTC, dave915 commented on src/main/java/blackjack/domain/scoreboard/WinOrLose.java
> +public enum WinOrLose {
이건 꼭 반영하지 않아도 됩니다.
Enum에서 각 상태별 조건 판별하는 Functional Interface를 들고 있으면 이 class가 많이 정리 될수도 있을 것 같아요.

https://dev3m.tistory.com/entry/ENUM-Funcational-Interface%EB%A1%9C-if%EB%AC%B8-%EC%A4%84%EC%9D%B4%EA%B8%B0

2021-03-08 17:32 UTC, dave915 commented on src/main/java/blackjack/domain/scoreboard/WinOrLose.java
> +        }
user 의 score와 dealer의 score 계산이 너무 여러번 일어나지 않나요?

2021-03-09 17:29 UTC, thisisyoungbin commented on src/main/java/blackjack/domain/card/Card.java
> +    }
Value에서 에이스를 1로 사용할지 11로 사용할지 고를 필요 없도록 바꿔봤습니다 ! 캐싱할 때 따로 필터링을 할 필요도 없고, 도메인에 맞게 카카드도 13 종류만 갖고 있어서 관리하기도 편해진 것 같아요..!

2021-03-09 17:30 UTC, thisisyoungbin commented on src/main/java/blackjack/domain/scoreboard/WinOrLose.java
> +        }
피드백 주신대로 BiPredicate를 이용해서 처음에 상태별로 승무패를 구하고, 어디에도 속하지 않는 상태의 경우(유저와 딜러 모두 버스트가 아닌 상태) 점수로 승무패를 구할 수 있게 변경해봤습니다.!

2021-03-09 18:06 UTC, thisisyoungbin commented
데이브 안녕하세요! 또 다시 리뷰를 위해 귀한 시간 내주셔서 감사해요 :)
리팩토링 한 주요 내용은 다음과 같습니다.
***
1. `ScoreBoard`에 있던 `Map<User, UserResult> userResult`가 사실상 유저와 승무패 여부만 관리해도 됐기에 `Map<User, WinOrLose>`를 가지는 `UserGameResult 클래스`로 변경했습니다.


2. `ScoreBoard`를 생성할 때 `Map<User, UserResult>`와 `GameResult(딜러결과)`를 인자로 받아 생성했는데요. 사실 `GameResult`가 딜러의 결과로만 사용되다보니 굳이 `ScoreBoard`내에 있을 필요가 없었고, `DealerGameResult`로 분리해서 관리하도록 수정해봤습니다.


3. 컨트롤러에서 `BlackjackGame`을 최종 출력하는 부분까지 계속 데리고 다녔었는데요. 유저와 딜러의 게임 결과를 반환 받아 최종 출력은 결과들을 통해 실행되도록 수정했습니다.


***
> push 하고 amend commit 하는 실수를 여러번 하는 바람에 강제 푸시를 몇 번 하게 됐네요....

2021-03-11 22:33 UTC, dave915 approved these changes
욘 안녕하세요! 
피드백 반영한 부분 확인했습니다! 
다음단계 진행해주세요 :)

2021-03-11 22:33 UTC, dave915 commented on src/main/java/blackjack/domain/scoreboard/WinOrLose.java
> +                .findFirst().get();
보통 `orElseGet` 또는 `orElseThrow` 로 초기값을 정해주던가 Exception을 던져줘요 😁

2021-03-11 22:33 UTC, dave915 commented on src/main/java/blackjack/domain/scoreboard/WinOrLose.java
> +public enum WinOrLose {
👍

2021-03-11 22:34 UTC, merged