[1단계 - 블랙잭 구현] 파즈(강승윤) 미션 제출합니다.
woowacourse/java-blackjack pull request #129
Opened 2021-03-04 08:59 UTC by Be-poz

안녕하세요 코니, 파즈라고 합니다.  

이번 블랙잭 미션 리뷰 잘 부탁드리겠습니다.  

리팩토링을 큰 시간을 못들여서 미숙한 곳이 많을 것 같습니다. 지적 그리고 제안을 해주시면 좋을 것 같습니다!!  

그리고 이번 미션에서 Controller에서 각 도메인과 메세지를 보내면서 게임의 흐름을 따라갔었는데 이번 미션에서는 페어가 이전에 적용해봤다던 서비스 격의 객체인 Game이라는 것을 통해 흐름을 많이 제어하려고 했습니다. 이 과정에서 ``List<Player> players`` 를 일급컬렉션으로 따로 묶지 않았는데, 해당 객체를 만들고 메세지를 보내줄 그런 로직들을 Game에서 처리하기 때문에 따로 생성하지 않았습니다. 이에 대해서 어떻게 생각하시는지도 여쭤보고 싶습니다.  

좋은 한 주 마무리 되시길 바랄게요 감사합니다!

2021-03-06 05:38 UTC, choihz requested changes
안녕하세요, 파즈! 리뷰어 코니입니다.
1단계를 깔끔하게 잘 구현해 주셨네요 😉 피드백 보시고 궁금한 점이나 의견이 있다면 언제나 코멘트 또는 DM 주세요~

2021-03-06 05:38 UTC, choihz commented on src/main/java/blackjack/domain/participant/Player.java
> +    }
```suggestion
    public Player(String inputName) {
        this.name = new Name(inputName);
    }
```

2021-03-06 05:38 UTC, choihz commented on src/main/java/blackjack/domain/participant/Player.java
> +    }
지금은 각 참여자가 본인의 결과를 가지고 있는데요, 테스트에서만 쓰이고 있는 `GameResult`의 `reverse()` 메서드가 암시하듯 딜러의 결과는 플레이어의 결과와 정반대죠. 그래서 지금 `Player`에서도 플레이어 결과 하나마다 딜러 결과 하나를 추가하는 로직이 반복되고 있고요. `GameResult`가 딜러와 플레이어를 가지고 스스로 결과를 계산하게 해보는 건 어떨까요? 지금의 방법과 비교하여 어떤 장점이 있을까요?

2021-03-06 05:38 UTC, choihz commented on src/main/java/blackjack/view/InputView.java
> +    public static final String NO_REPLY = "n";
접근 제어자 확인해 주세요~

2021-03-06 05:38 UTC, choihz commented on src/test/java/blackjack/domain/card/DeckTest.java
> +    }
무엇을 테스트한 건지 이름을 명시해 주세요~

2021-03-06 05:38 UTC, choihz commented on src/main/java/blackjack/domain/Game.java
> +public class Game {
> 그리고 이번 미션에서 Controller에서 각 도메인과 메세지를 보내면서 게임의 흐름을 따라갔었는데 이번 미션에서는 페어가 이전에 적용해봤다던 서비스 격의 객체인 Game이라는 것을 통해 흐름을 많이 제어하려고 했습니다. 이 과정에서 List<Player> players 를 일급컬렉션으로 따로 묶지 않았는데, 해당 객체를 만들고 메세지를 보내줄 그런 로직들을 Game에서 처리하기 때문에 따로 생성하지 않았습니다. 이에 대해서 어떻게 생각하시는지도 여쭤보고 싶습니다.

지금의 `Game`이 흐름 제어를 하는 것으로 보이지는 않네요. `List<String> playerNames`를 받아 `List<Player> players`를 만들고, 각 참여자들에게 카드를 뽑게 하고 등등 전반적으로는 그냥 일급 컬렉션과 비슷해 보여요 (뭔가 틀렸다는 말은 아닙니다!)
다만 이 객체가 무슨 일을 하는지, 해야 하는지 조금 더 고민해 보시면 좋을 것 같아요.

2021-03-08 06:44 UTC, Be-poz commented on src/main/java/blackjack/domain/Game.java
> +        if (playerNames.size() == 0) {
이렇게도 사용할 수 있군요! 기억해두겠습니다!

2021-03-08 06:45 UTC, Be-poz commented on src/main/java/blackjack/domain/participant/Dealer.java
> +    public static final String DEALER = "딜러";
페어랑 정할 때에 딜러는 변하지 않으니 상수로 두자고 했었는데  Name이라는 객체도 만들었고 딜러라는 이름의 Name을 만들어도 괜찮겠네요!

2021-03-08 06:48 UTC, Be-poz commented on src/main/java/blackjack/controller/Casino.java
> +        closingStage(dealer, players);
따로 리팩토링한 네이밍이었는데 역시 동사를 써야겠네요.. ㅎㅎ

2021-03-08 06:50 UTC, Be-poz commented on src/main/java/blackjack/view/OutputView.java
> +    }
현재 소지한 카드에 대한 정보를 출력하는 것과 마지막에 소지 카드에 대한 정보 출력 후 결과 까지 출력하는 부분에서 중복코드를 잡고싶어서 따로 ``lineFeed()``를 뺐던건데 결과적으로 더 지저분한 코드가 된 것 같아요. 포맷을 따로 두어서 깔끔하게 고쳐보겠습니다.

2021-03-08 06:50 UTC, Be-poz commented on src/main/java/blackjack/controller/Casino.java
> +            OutputView.lineFeed();
이것 또한 맨 첫 답변고치면서 수정해봐야겠네요!

2021-03-08 06:51 UTC, Be-poz commented on src/main/java/blackjack/domain/card/Deck.java
> +    }
52 종류의 카드가 있고 그것을 소모하는 것이 아니라 무한한 카드라고 가정하고 진행했습니다. ``cards.get(0)``을 반환하기 때문에 셔플을 하지않으면 같은 값을 반환하기 때문에 섞어줬습니다. 그냥 index로 진행하게되면 52장이 넘어가는 경우를 따로 처리해야되기 때문에 무한 드로우가 가능하도록 해봤습니다!

2021-03-08 06:52 UTC, Be-poz commented on src/main/java/blackjack/domain/card/GameNumber.java
> +    int value;
Score로 변경했으며, Enum Class 명 또한 변경했습니다.

2021-03-08 06:53 UTC, Be-poz commented on src/main/java/blackjack/domain/card/Shape.java
> +    String name;
앗...

2021-03-08 06:57 UTC, Be-poz commented on src/main/java/blackjack/domain/participant/GameResult.java
> +    }
파라미터로 넘어온 서로 다른 객체여서 이 부분을 getter를 이용해야되는줄 알았는데 아니었네요 ?! 이 부분 처음 알았습니다 ! 완전 충격적이에요... 해당 ``plus()``와 ``reverse()``는 제출 막판에 급하게 방식을 바꾸면서 사용을 더 이상 안했는데 지우는 작업을 못했습니다 ㅜㅜ

2021-03-08 07:00 UTC, Be-poz commented on src/main/java/blackjack/view/InputView.java
> +    public static final String NO_REPLY = "n";
확인 완료!

2021-03-08 07:00 UTC, Be-poz commented on src/test/java/blackjack/domain/card/DeckTest.java
> +    }
넵!

2021-03-08 07:02 UTC, Be-poz commented on src/main/java/blackjack/domain/Game.java
> +public class Game {
저 또한 그렇게 느꼈는데, 한 번 잘 바꿔보겠습니다!

2021-03-08 13:21 UTC, choihz commented on src/main/java/blackjack/domain/participant/GameResult.java
> +    }
앗!!!!!! 이건 제가 잘못 본 게 맞아요 😢 혼란을 드려 죄송합니다.

2021-03-08 14:37 UTC, choihz commented on src/main/java/blackjack/domain/participant/Player.java
> +    }
아니면 `Player`가 `Dealer`와 상태를 비교하여 본인의 결과 객체를 리턴하게 할 수도 있겠죠. `Dealer`는 이 `Player`의 결과 객체를 모아 본인의 결과를 만들 수 있고요. 정보를 알고 있는 객체가 스스로 일하게 하는 것이 좋다는 관점에서 보면 이 방법이 더 좋겠네요!

2021-03-08 14:41 UTC, Be-poz commented on src/main/java/blackjack/domain/participant/Player.java
> +    }
GameResult를 아예 Enum으로 바꾸고 승패 여부의 책임을 부여했습니다.

2021-03-08 15:01 UTC, Be-poz commented
안녕하세요 코니! 파즈입니다. 오늘 대대적인 리팩토링 작업을 진행했습니다... 제가 봐도 코드 진짜 엉망에다가 스스로 부끄러울 정도의 수준이었습니다 ㅜㅜㅜㅜ 구리더라도 돌아가는 코드를 데드라인안에 제출하는게 맞아!! 라고 고집하고 제출하고 피드백 전까지 고치지를 않았었는데... 이제 타협을 좀 봐야될 것 같다고 느꼈습니다 ㅋㅋㅋ  

바뀐 점은 다음과 같습니다.  

1. 메서드 네이밍 동사로 변경

2. GameNumber.class -> CardNumber.class 으로 변경

3. 모든 클래스 접근 제어자 수정

4. OutputView 의 lineFeed 덕지덕지 붙였던 것 수정

5. Players 생성 및 Game 정적팩토리메서드 로직 변경

6. Casino 프로세스 변경

   이 부분은 Game에게 메세지를 보내서 게임이 흘러가도록 많이 변경했습니다. 기본 요구사항 이외의 페어와 약속한 요구사항들을(ex. 플레이어가 카드를 뽑는 턴에 블랙잭, 버스트에 대한 시스템 메세지 출력) 추가하려다 보니 Game 객체를 일급컬렉션처럼 값을 가져오는 용도로 대부분 사용했는데 이 부분들을 싹 고쳐봤습니다.

7. 딜러와 플레이어의 최종 승패에 대한 로직을 고쳤습니다. GameResult라는 Enum을 주축으로 변경했습니다.

8. Dealer도 Name을 사용하도록 수정하면서 이 필드 또한 추상화 시켰습니다.

9. 이에 맞게 테스트 케이스를 모두 고치고 무엇에 대한 테스트인지 ``DisplayName``으로 다 표기했습니다.

이전의 코드가 너무 마음에 안들어서 많이 변경하게 됐습니다! Casino와 Game과의 이동 부분이 제일 많이 바뀐 것 같네요! 피드백 해주셔서 감사합니다~!  

<br/>

## [OOP] 역할 분배 - 5

### 내용

* 승과 패에 대한 정보를 가지고 있는 GameResult에 승, 패 여부를 가리는 책임을 주었다.
* Game에서 현재 진행 중인 게임에 대한 정보를 묻는 메세지를 받을 수 있게끔 했다.
* Players를 만들어서 처음 카드 2장을 세팅할 때 메세지를 보내서 카드를 추가하게끔 하였다.

***

## [JCF] List.isEmpy() -1

### 내용

* ``list.size() == 0``이 아닌 ``list.isEmpty()``를 이용

2021-03-09 12:09 UTC, choihz approved these changes
안녕하세요, 파즈!

피드백을 잘 반영해 주셨네요! 💯 말씀하신 것처럼, 돌아가는 코드를 데드라인 안에 제출하는 것이 사실 가장 중요한 일이랍니다. 1단계 진행하느라 고생 많으셨구요, 2단계에서 만나요~

2021-03-09 12:09 UTC, merged