[1단계 - 블랙잭 구현] 삭정(성정석) 미션 제출합니다.
woowacourse/java-blackjack pull request #130
Opened 2021-03-04 09:00 UTC by sakjung

## 안녕하세요 코니! 1단계 블랙잭 미션 제출합니다.

### 주요 이슈
현재 코드에서는 딜러와 플레이어를 따로 처리해주는 로직이 많습니다. 비록 딜러와 플레이어가 participant라는 객체를 상속받도록 만들었지만 뭔가 다형성을 제대로 활용하지 못한 것 같아 아쉬움이 남네요.
좀 더 상속의 장점을 잘 활용할 수 있는 방법에 관련해서 코니의 인사이트를 받고 싶습니다.

리뷰에 시간 내주셔서 감사합니다!

2021-03-06 08:29 UTC, choihz requested changes
안녕하세요, 삭정! 리뷰어 코니입니다.
1단계를 잘 구현해 주셨네요 👍 피드백 보시고 궁금한 점이나 의견이 있다면 언제나 코멘트 또는 DM 주세요~

2021-03-06 08:29 UTC, choihz commented on src/main/java/blakcjack/domain/outcome/Outcome.java
> +	}
모든 메서드가 `Player`와 `Dealer`를 매개변수로 받아 뭔가를 요구하고 있는데, 그들이 스스로 할 수 있는 일이 아닐까요?

2021-03-06 08:29 UTC, choihz commented on src/main/java/blakcjack/domain/outcome/Outcome.java
> +	final String korean;
```suggestion
	private final String korean;
```

`korean`...? 🙄

2021-03-06 08:29 UTC, choihz commented on src/main/java/blakcjack/domain/participant/Participant.java
> +	}
같은 메서드네요 😳

2021-03-06 08:29 UTC, choihz commented on src/main/java/blakcjack/domain/shufflestrategy/ShuffleStrategy.java
> +}
👍

2021-03-06 08:29 UTC, choihz commented on src/test/java/blakcjack/domain/card/CardTest.java
> +	}
👍

2021-03-06 08:29 UTC, choihz commented on src/test/java/blakcjack/domain/participant/DealerTest.java
> +	@DisplayName("17점 미만이면 통과")
"통과"라는 게 뭘 의미하는 걸까요?

2021-03-06 08:29 UTC, choihz commented on src/main/java/blakcjack/domain/participant/Dealer.java
> +		return Collections.singletonList(getCards().get(FIRST_CARD_POSITION));
```suggestion
		return Collections.singletonList(cards.get(FIRST_CARD_POSITION));
```

2021-03-06 08:29 UTC, choihz commented on src/main/java/blakcjack/domain/card/Card.java
> +	}
`equals()`와 `hashCode()`가 가장 아래 순서가 되도록 수정해 주세요~

```java
class Test {
  상수
  클래스 변수
  인스턴스 변수
  생성자
  팩토리 메서드
  메서드
  기본 메서드 (equals, hashcode, toString...)
}
```

2021-03-06 08:29 UTC, choihz commented on src/main/java/blakcjack/domain/participant/Participant.java
> +	protected final List<Card> cards = new ArrayList<>();
`List<Card>`를 일급 컬렉션으로 만들고 점수 계산의 책임을 부여해도 좋을 것 같아요.

2021-03-06 08:38 UTC, choihz commented on src/test/java/blakcjack/domain/game/BlackjackGameTest.java
> +		assertThatThrownBy(() -> new BlackjackGame(deck, Arrays.asList("pobi", "pobi")))
테스트가 실패하고 있어요~

2021-03-07 06:12 UTC, sakjung commented
## 주요 수정 사항

### 커스템 예외
이번 미션을 통해서 처음 커스텀 예외를 사용해 보았습니다. 리뷰를 통해서 커스텀 예외가 기본 메세지를 가지도록 하라고 하셔서 메세지 상수를 커스텀 예외가 갖고 있도록 한 후 예외 발생지점에서 메세지를 주입해주도록 만들었습니다. 하지만 코니가 의도한 바가 이게 맞는지 잘 모르겠습니다 ㅠ.

### [final 키워드의 기준](https://github.com/woowacourse/java-blackjack/pull/130#discussion_r588848155)
이른 바인딩과 최적화의 개념에 대해서 우연히 알게 되어서 이번 미션에서 한번 극단적으로 최대한 모든 변수에 final 키워드를 붙여보는 시도를 해봤습니다.

코니는 final 키워드를 어떤식으로 사용해야 한다라는 자신만의 코딩 스탠다드가 있는지 궁금합니다. 있다면 어떤 스탠다드를 가지고 있는지 알려주세요 ㅎㅎ.

### [뷰에서 y와 n입력을 판별하기](https://github.com/woowacourse/java-blackjack/pull/130#discussion_r588847903)
코니의 피드백 대로 view에서 boolean으로 바로 리턴 해준다면 컨트롤러에서 불필요하게 y, n에 대해 판별할 로직을 만들 필요가 없어서 더 좋은 방법이라는 생각이 듭니다. 그리고. 입력이 y인지 n인지는 뷰 레이어의 관심사이기 때문에 컨트롤러가 알 필요도 없는 것 같습니다.

### plyaer와 dealer의 책임 증가
코니의 피드백을 통해 리팩토링하면서 player와 dealer가 너무 수동적이라는 것을 깨닫게 되었습니다. 그들이 충분히 수행할 수 있는 역할들인데도 다른 객체들이 그 역할을 대신 하고있는 경우가 많았습니다.

예를들어, outcome에서 결과를 도출하는 게 아니라 dealer와 player들이 알아서 자기들 패를 통해 결과를 산출하는게 더 자연스럽더라구요.

그래서 player와 dealer들이 스스로 할 수 있는 일들은 책임지고 할 수 있도록 리팩토링 해보았습니다

2021-03-08 14:11 UTC, choihz commented on src/test/java/blakcjack/domain/participant/ParticipantsTest.java
> +		Cards dealerExepectedCards = new Cards();
오타가 있어요!

2021-03-08 14:11 UTC, choihz commented on src/main/java/blakcjack/controller/BlackJackController.java
> +		final BlackjackGame blackjackGame = new BlackjackGame(deck, playerNames);
저는 인스턴스 변수 말고 지역 변수나 매개 변수에서는 특별히 필요한 경우가 아니면 `final`을 붙이지 않는데요, 이건 제 스타일일 뿐입니다. 지금은 키워드를 이해하고 본인의 스타일을 만들어 나가는 단계라고 생각하고, 그런 의미에서 "이번 미션에서 한번 극단적으로 최대한 모든 변수에 final 키워드를 붙여보는 시도"를 하신 것은 👍👍💯

2021-03-08 14:11 UTC, choihz approved these changes
안녕하세요 삭정!

그 짧은 새에 정말 많은 고민과 리팩터링을 진행하셨군요 😊 고생 많으셨습니다. 2단계에서 만나요~

2021-03-08 14:11 UTC, merged