[1단계 - 블랙잭 구현] 완태(김태완) 미션 제출합니다.
woowacourse/java-blackjack pull request #133
Opened 2021-03-04 09:03 UTC by wannte

블랙잭 1단계 미션 제출합니다.
1차 완성이 되긴했지만, 계속 수정 진행하겠습니다.

2021-03-06 11:23 UTC, seok-2-o requested changes
안녕하세요. 완태.
어려운 미션 진행하느라 고생이 많으셨어요.

요구사항을 만족하지 못하는 부분이 있어 해당 부분에 코멘트 남겨 놓았어요.
해당부분 확인하고 리펙토링 진행하면 좋을 것 같아요.

진행하면서 어려운 점이나 궁금한점 있으면 편하게 DM 주세요.

2021-03-06 11:23 UTC, seok-2-o commented on src/main/java/blackjack/controller/BlackjackController.java
> +public class BlackjackController {
컨트롤러에서 수행하는 상당수의 로직은 Game안에서도 수행 할 수 있을 것 같은데 어떻게 생각하시나요? 🤔

2021-03-06 11:23 UTC, seok-2-o commented on src/main/java/blackjack/domain/Game.java
> +        if (playerNames.size() == 0) {
```suggestion
        if (playerNames.isEmpty()) {
```

2021-03-06 11:23 UTC, seok-2-o commented on src/main/java/blackjack/domain/card/Deck.java
> +    public static Card draw() {
덱에서 한번 빠진 카드는 다시 사용 될 수 없어요.

지금 구조라면 동일한 문양과 기호를 가진 카드가 중복해서 생성 될 수 있을 것 같아요.

2021-03-06 11:23 UTC, seok-2-o commented on src/main/java/blackjack/domain/participant/Participant.java
> +    private final List<Card> cards = new ArrayList<>();
해당 콜렉션도 객체로 만든다면 어떤 장점이 있을까요? 🤔

2021-03-06 11:23 UTC, seok-2-o commented on src/main/java/utils/StringUtils.java
> +public class StringUtils {
👍

2021-03-06 12:45 UTC, wannte commented on src/main/java/blackjack/domain/card/Deck.java
> +    public static Card draw() {
이 부분에 대해서 페어랑 얘기를 나눴었는데요.
실제 카지노의 블랙잭의 경우에는 카드 덱 여러개를 사용하는 경우도 있다고 해서, 이를 랜덤하게 뽑기로 구현해도 되겠다라 생각했던 것 같아요!.

게임이 덱을 가지고 있는 구조로 설계를 변경하는 게 좋을 것 같네요!:) 가능하면 게임이 52장 x 4 처럼 게임이 몇개의 덱을 가지고 있는지 설정할 수 있으면 더 좋을 것 같아요!

2021-03-06 13:01 UTC, wannte commented on src/main/java/blackjack/domain/participant/Participant.java
> +    private final List<Card> cards = new ArrayList<>();
particiapant클래스가 너무 많은 로직을 가지고 있어서 고민이였는데, 이걸 분리를 안했었네요 ㅎㅎ

2021-03-06 13:04 UTC, wannte commented on src/main/java/blackjack/controller/BlackjackController.java
> +public class BlackjackController {
안녕하세요 미립! 혹시 이 부분은 예시를 하나만 들어주 실 수 있을까요? :cry:

2021-03-09 07:43 UTC, merged

2021-03-09 12:53 UTC, wannte commented on src/main/java/blackjack/domain/Game.java
> +    public void next(boolean willDraw) {
고민해보겠습니다:) ㅎㅎ