[1단계 - 블랙잭 구현] 김김(김기문) 미션 제출합니다.
woowacourse/java-blackjack pull request #136
Opened 2021-03-04 09:06 UTC by tributetothemoon

안녕하세요 코니! 이번에 리뷰를 부탁드리게 된 우아한테크코스 김김입니다.
온라인 상이지만 이렇게나마 만나뵙게되어 반갑습니다. 잘 부탁드립니다 :)

1단계 미션 제출에 마감 기한이 생기면서 페어와 상당히 빠른 속도로 구현을 했는데요, 기한인 오늘 오후부터는 헤어지고 서로 빠른 속도로 리팩토링을 진행했지만, 그럼에도 여전히 부족한 부분이 많은 것 같습니다😢. 2단계를 진행하면서, 코멘트로 남겨주시지 않은 부분도 열심히 리팩토링을 진행하도록 하겠습니다.

이번 미션의 핵심은 상속을 통한 중복 코드 제거였는데요, 이 과정에서 질문이 생겨나 묻고 싶은 것이 있습니다.

이번의 미션에서 상속을 이용한 부분은 유저(플레이어, 딜러)입니다. 딜러와 플레이어는 공통된 부분이 많아 User라는 클래스를 부모 클래스로 상속시켜 중복 코드를 제거하였습니다. 그리고 이 유저들을 담은 Users라는 일급 컬렉션을 만들었는데요, 아무래도 이 Users에 딜러와 플레이어가 모두 들어있다보니, 동적으로 타입을 확인하는 로직이 중간에 많이 가미되었습니다.

>> 예시 ( Users.java )
```
(중략)

 public List<Player> getPlayers() {
        return users.stream()
                .filter(user -> user instanceof Player)
                .map(user -> (Player) user)
                .collect(Collectors.toList());
    }

    public List<User> gerUsers() {
        return Collections.unmodifiableList(this.users);
    }

    public Dealer getDealer() {
        return (Dealer) this.users.stream()
                .filter(user -> user instanceof Dealer)
                .findFirst()
                .orElseThrow(() -> new RuntimeException("딜러가 존재하지 않습니다."));
    }

    public Map<User, ResultType> generateResultsMapAgainstDealer() {
        int dealerScore = getDealer().getScore();
        return users.stream()
                .filter(user -> user instanceof Player)
                .collect(Collectors.toMap(player -> player, player -> ((Player) player).generateResultAgainstDealer(dealerScore)));
    }
```

하지만 이렇게 instanceof 라는 연산자를 사용하니, 정적 타이핑 언어로 설계된 자바의 철학에 역행하고 있는 것은 아닌가 라는 생각이 들었습니다. 이런 식으로 동적으로 타입을 확인하고 캐스팅을 통해 어떠한 동작을 하는 방식을 어떻게 생각하시는지 묻고 싶습니다.

감사합니다 :)

2021-03-06 10:23 UTC, choihz requested changes
안녕하세요, 김김! 리뷰어 코니입니다.
1단계를 잘 구현해 주셨네요 😉 피드백 보시고 궁금한 점이나 의견이 있다면 언제나 코멘트 또는 DM 주세요~

2021-03-06 10:23 UTC, choihz commented on src/main/java/blackjack/domain/user/User.java
> +        }
`score`는 본래 카드의 숫자를 더해 얻어지는 것인데, 지금처럼 `Card.BUST`, `Card.BLACKJACK_SCORE` 등을 이용해 다른 의미까지 부여하면 코드 파악이 어려워지고 실수 가능성이 증가합니다.

2021-03-06 10:23 UTC, choihz commented on src/main/java/blackjack/view/OutputView.java
> +            String temp = checkWinOrLose.get(user).getName();
`temp`.. 🙄

2021-03-06 10:23 UTC, choihz commented on src/test/java/blackjack/domain/user/UsersTest.java
> +        player2 = users.getPlayers().get(1);
```suggestion
        player1 = users.getPlayers().get(0);
        player2 = users.getPlayers().get(1);
```

2021-03-06 10:23 UTC, choihz commented on src/test/java/blackjack/domain/user/UsersTest.java
> +    Card six = new Card(Suit.CLUB, CardNumber.SIX);
테스트 코드에서도 접근 제어자는 신경 써 주세요~

2021-03-08 06:29 UTC, tributetothemoon commented on src/main/java/blackjack/view/OutputView.java
> +            String temp = checkWinOrLose.get(user).getName();
😱 페어에게 대충~ 이런 식으로 어떨까요 하면서 쓰고 지울 예정이었는데 바로 컨펌받고 고칠 생각을 안 했네요...[수정](https://github.com/tributetothemoon/java-blackjack/commit/5a5ac84f35f2ae5bb3f07ef744963919701fc81b)했습니다...

2021-03-08 06:30 UTC, tributetothemoon commented on src/main/java/blackjack/view/OutputView.java
> +    public static void printResult(Map<User, ResultType> checkWinOrLose) {
말씀하신대로 정확한 의도를 전혀 드러내지 못하는 것 같습니다. [수정](https://github.com/tributetothemoon/java-blackjack/commit/5a5ac84f35f2ae5bb3f07ef744963919701fc81b)했습니다.

2021-03-08 06:31 UTC, tributetothemoon commented on src/main/java/blackjack/domain/user/Users.java
> +import blackjack.domain.user.User;
[반영](https://github.com/tributetothemoon/java-blackjack/commit/dbdae3fac8d73b30d538af2a75dab6e5b80fd7d9)하였습니다 :)

2021-03-08 06:35 UTC, tributetothemoon commented on src/main/java/blackjack/controller/BlackJackController.java
> +    }
블랙잭을 잘 알지 못하여 발생한 오류였던 것 같습니다. 블랙잭을 잘 알지 못한 상태로, 예제 출력만 보고 하려다 보니 이것 말고도 이런 저런 문제(딜러는 한 장만 오픈 하는 문제 등)가 발생한 것 같습니다. 만들고자 하는 프로그램에 대해 더 잘 알아보도록 노력하겠습니다.
[수정](https://github.com/tributetothemoon/java-blackjack/commit/c2542b2267c7ee2486087fb6bd20a6331b561e69)하였습니다!

2021-03-08 06:40 UTC, tributetothemoon commented on src/main/java/blackjack/domain/user/Player.java
> +    }
정확한 지적이라고 생각합니다. 지금 보니 왜 이렇게 했는지 부끄럽기만 하네요...[수정](https://github.com/tributetothemoon/java-blackjack/commit/81f2d3e7a26a34cdb622d432d07abf887dc4314d)하였습니다!

2021-03-08 06:42 UTC, tributetothemoon commented on src/main/java/blackjack/domain/user/User.java
> +        return this.cards.stream().anyMatch(card -> card.getScore() == ACE_SCORE);
Cards 일급 컬렉션을 생성하면서 [반영](https://github.com/tributetothemoon/java-blackjack/commit/64a53c3a7e586a58f251ac4be45aaec226c0d1f6)하였습니다 :) 좋은 피드백 감사합니다.

2021-03-08 06:44 UTC, tributetothemoon commented on src/main/java/blackjack/util/StringUtil.java
> +    }
감사합니다...😢 [커밋내역](https://github.com/tributetothemoon/java-blackjack/commit/a967ce7c4ffe9fdab597e5431df4975b0defcb33)

2021-03-08 06:46 UTC, tributetothemoon commented on src/main/java/blackjack/domain/user/User.java
> +        }
좋은 지적입니다. 기한에 쫓겨 1차 리뷰를 빠르게 보내기 위해 score를 이용하여 빠르게 테스트만을 통과하는 코드를 작성했지만, 만들면서도 리뷰 요청 후 1순위로 리팩토링을 해야할 부분이라고 생각하여 곧 바로 리팩토링을 진행하였습니다.
[커밋 내역](https://github.com/tributetothemoon/java-blackjack/commit/d9451e214fb54b07642fb303e55174be4b623780)을 확인하시고, 피드백을 부탁드리겠습니다 🙂👍

2021-03-08 06:50 UTC, tributetothemoon commented on src/test/java/blackjack/domain/user/UsersTest.java
> +        player2 = users.getPlayers().get(1);
[커밋내역](https://github.com/tributetothemoon/java-blackjack/commit/a5d2b8c8f1f98402d2527b16c10a11e4581b991e)👍

2021-03-08 06:51 UTC, tributetothemoon commented on src/test/java/blackjack/domain/user/UsersTest.java
> +    Card six = new Card(Suit.CLUB, CardNumber.SIX);
[커밋내역](https://github.com/tributetothemoon/java-blackjack/commit/a5d2b8c8f1f98402d2527b16c10a11e4581b991e)
😅 유념하겠습니다!

2021-03-09 06:30 UTC, tributetothemoon commented on src/main/java/blackjack/controller/BlackJackController.java
> +        OutputView.printCardsOfUsersWithScore(users);
😱룰을 잘 이해하지 못한 제 불찰입니다. [반영](https://github.com/tributetothemoon/java-blackjack/commit/0e74330b5dead4fa56431ef942e823cbb57f2e42)하였습니다!

2021-03-09 06:39 UTC, tributetothemoon commented on src/main/java/blackjack/domain/user/Users.java
> +    }
코니가 주신 의견에 적극 공감하여 `Players` 클래스를 만들어 [수정](https://github.com/tributetothemoon/java-blackjack/commit/1db2f9de8d9bccda03c655f955d3eab22caec51e)하였습니다. 이제 `Controller`는 `Dealer`와 `Players`에 대한 인스턴스 변수를 가지고, 필요할 때 마다 호출하게 변경하여 필터링 없이 실행될 수 있게 하였습니다. [Users](https://github.com/tributetothemoon/java-blackjack/commit/af5a77d8ecfa3513772025bc55e5e5d2e9bb2101)를 삭제한 것은 아니고, 여전히 딜러를 포함한 모든 유저들의 정보를 필요로 할 때 쓰이고는 있습니다. 하지만, 리팩토링을 하고 나니 역할이 꽤 단촐해 Users라는 클래스를 계속 가지고 가야하는지에 대해서는 여전히 의문입니다. 차라리 `List<User> users`의 형태로 컨트롤러가 가지고 있는게 좋을지 고민해보고 있습니다.

2021-03-09 06:41 UTC, tributetothemoon commented on src/main/java/blackjack/domain/user/Player.java
> +    boolean isStay = false;
만들면서 생각한 로직이 있어 만들었던 메소드였는데, 다 만들고 보니 어느새 조금의 수정만 가하면 필요없는 변수였습니다. 좋은 피드백 감사합니다! [커밋링크](https://github.com/tributetothemoon/java-blackjack/commit/82e6ad70d49bc60b241e4eaf632408b4596a5b49)

2021-03-09 06:42 UTC, tributetothemoon commented on src/main/java/blackjack/domain/card/Card.java
> +        return this.cardNumber.getScore() + this.suit.getName();
😱 심각한 결함을 미처 발견하지 못했었네요... 지적 감사합니다. [수정](https://github.com/tributetothemoon/java-blackjack/commit/1a5a6a1d27f004c79c96cff75d26a1f213d999c7)하였습니다!

2021-03-09 06:47 UTC, tributetothemoon commented
안녕하세요 코니! 정성스런 리뷰에 감사드립니다. 리뷰를 남겨주신 모든 사항에 대해 리팩토링을 진행해보았습니다.
여전히 수정하고 싶은 부분(사용자 입력에 의한 예외 시 종료하지 않고 재입력을 요구, DTO클래스 적용을 통한 View의 의존성 저하 등)이 있지만, 우선은 1단계 머지 및 2단계 진행 등 더 우선시 되어야하는 부분이 있을 것 같아 우선은 코멘트 남겨주신 부분을 모두 수정해본뒤 리뷰 요청을 보냅니다. :)

2021-03-10 15:05 UTC, choihz approved these changes
안녕하세요, 김김!

피드백을 잘 반영해 주셨네요 💯 코멘트를 몇 개 더 남겼는데 확인 부탁드리고, 궁금한 점은 언제든 DM 주세요~ 2단계에서 만나요! 👋

2021-03-10 15:05 UTC, choihz commented on src/main/java/blackjack/domain/card/Cards.java
> +    }
카드에게 직접 에이스냐고 물어볼 수 있지 않을까요? 또한, 에이스라는 것을 점수로밖에 알 수 없나요?

2021-03-10 15:05 UTC, choihz commented on src/test/java/blackjack/domain/card/CardsTest.java
> +    }
1. 메서드 이름에 오타가 있네요~
2. 에이스가 있을 때의 점수 계산 케이스가 다양한데요, JUnit5의 기능을 이용하여 이 여러 가지를 전부 테스트 해보는 건 어떨까요?

2021-03-10 15:05 UTC, choihz commented on src/test/java/blackjack/domain/card/CardsTest.java
> +        assertTrue(cards.isBust());
```suggestion
        cards.hit(king);
        cards.hit(queen);
        cards.hit(two);

        assertTrue(cards.isBust());
```

이렇게 줄바꿈이 들어가면 테스트 코드가 무엇을 검증하는지 한눈에 들어와서 더 좋아요 😉

2021-03-10 15:05 UTC, merged

2021-03-11 04:43 UTC, tributetothemoon commented on src/main/java/blackjack/domain/card/Cards.java
> +    }
👍 자주 boolean 리턴 함수에서 이렇게 의미없는 코드를 쓰는 습관이 있는 것 같습니다. [커밋](https://github.com/tributetothemoon/java-blackjack/commit/80d93cc45db9ba4f0b43b8dbafc8aa5b6b70a016) 감사합니다!

2021-03-11 04:45 UTC, tributetothemoon commented on src/main/java/blackjack/controller/BlackJackController.java
> +    private final Users users;
저는 'BlackJackController 객체가 하나 생성되는 것 = 한 판의 게임이 생성되는 것'으로 간주해서 한번의 게임에 참가하는 주요 인스턴스를 가지고 있도록 하였는데요, 웹 프로그램을 개발할 때를 생각해보면 Controller가 특별히 인스턴스 변수를 가지고 있지는 않았던 것 같습니다.

2021-03-14 03:22 UTC, tributetothemoon commented on src/main/java/blackjack/controller/BlackJackController.java
> +    private final Users users;
도메인 로직과 가능한 상관 없어야하는 컨트롤러가 도메인 객체를 인스턴스 변수로 가지는게 도메인 로직에 깊게 관여한다는 느낌이 들었습니다. [커밋](https://github.com/tributetothemoon/java-blackjack/commit/9d630658ad7a0156cddc4e2031575f6c73129622)을 통해 컨트롤러의 인스턴스 변수를 삭제하고 메소드에 파라미터로 받도록 수정하였습니다!

2021-03-14 03:25 UTC, tributetothemoon commented on src/main/java/blackjack/view/OutputView.java
> +    }
1. [커밋](https://github.com/tributetothemoon/java-blackjack/commit/b37a714a9ba0138196a919108065ced1759b5aac): toString은 주로 로깅, 디버깅 할 때의 용도로 사용한다는 것을 배웠습니다. 뷰 단에서는 getter메소드를 이용해 출력할 수 있도록 변경했습니다. 
2. [커밋](https://github.com/tributetothemoon/java-blackjack/commit/e7c827c1d840ae77c430d614cab3b1c693e3dfac) : 딜러에게 첫 번째 카드만을 받는 메소드를 사용하여 getter를 줄여보았습니다 :)

2021-03-14 03:29 UTC, tributetothemoon commented on src/main/java/blackjack/controller/BlackJackController.java
> +    private void dealingTwoCards(Users users) {
[커밋](https://github.com/tributetothemoon/java-blackjack/commit/8f99dd722c552b4013fc298c72b0fa27e6922e1c)을 통해 가능한 컨트롤러에서 사용하는 메소드의 이름을 추상화해보았습니다. :)

2021-03-14 03:30 UTC, tributetothemoon commented on src/main/java/blackjack/domain/MatchRule.java
> +    SCORE_COMPARISION_DRAW((playerCards, dealerCards) -> playerCards.getScore() == dealerCards.getScore(), ResultType.DRAW);
1. 감사합니다...😭

2021-03-14 03:41 UTC, tributetothemoon commented on src/main/java/blackjack/domain/card/Cards.java
> +    private static final int ELEVEN_SCORE = 11;
[커밋](https://github.com/tributetothemoon/java-blackjack/commit/f4f3b1c23cdffadfcc08358e9ecdd0a00e38e12e): 상수명을 짓는데 의미 없이 부여하지 않도록 노력하겠습니다. 변수명을 짓는 것은 항상 힘든 일이네요 😭

2021-03-14 03:43 UTC, tributetothemoon commented on src/main/java/blackjack/domain/card/Cards.java
> +    }
[커밋](https://github.com/tributetothemoon/java-blackjack/commit/d703613c38ef4c984b6d1e6e657bca8768fcfe2c): 왜 그랬을까 싶은 코드네요😢 바로 수정해보았습니다!

2021-03-14 03:46 UTC, tributetothemoon commented on src/test/java/blackjack/domain/card/CardsTest.java
> +    }
1. 감사합니다...
2. [커밋](https://github.com/tributetothemoon/java-blackjack/commit/12c14e6b93d7e3703218cf2815885cd6ae2408d5): `ParameterizedTest`와 `MethodSource`를 이용하여 원시 자료형이 아닌 인스턴스를 스트림을 통해 전달하여 테스트 할 수 있는 방법을 배웠습니다. 항상 해결하기 힘들었던 부분이라 한참을 돌아가고 있었네요. 테스트 코드에 왜 이리 무심했는지 새삼 반성하게 되는 부분이었습니다. 성장할 수 있도록 좋은 리뷰를 주셔서 정말 감사합니다 🙌🙌🙌🙌🙌

2021-03-14 03:49 UTC, tributetothemoon commented on src/test/java/blackjack/domain/card/CardsTest.java
> +        assertTrue(cards.isBust());
[커밋](https://github.com/tributetothemoon/java-blackjack/commit/30db48acdf7498d8e623d3e1d3e7ffc827c2d9dd): 개행문자를 추가해주는 편이 맞는 것이군요. 감사합니다😉

2021-03-14 05:13 UTC, tributetothemoon commented
# 김김의 학습로그 - 블랙잭 1단계
-----------

# [Java] ToString의 주된 용도 - 3
## 내용
- toString()을 뷰 레이어에서 출력을 위해 사용하는 로직을 작성했으나, 리뷰어님으로부터 이런 방식으로 사용하는 것은 좋지 못한 방법이라는 피드백을 받았다.
- 검색을 통해 알아보니, toString()은 주로 로깅, 디버깅시 객체의 상태를 쉽게 확인하기 위해 사용된다는 것을 알게 되었다. View 레이어에서 출력에 관해서는 getter만을 이용해 뷰 레이어에서 알아서 가공하도록 로직을 구성했다.
## 링크
- [toString()에 대해서](https://dublin-java.tistory.com/46)

------------
# [TDD] MethodSource를 통한 ParameterizedTest 사용
## 내용
- 블랙잭 카드 조합에 따른 다양한 점수 계산법을 테스트해야하는 상황에서, 주로 코드의 복사를 통해 중복 코드를 많이 작성하는 방식으로 테스트했고, 그렇게 했음에도 충분한 경우를 테스트하지 못하고 있었다. 이에 리뷰어님께서는 Junit5의 다양한 기능을 이용하여 테스팅을 진행해볼 것을 권유했다.
- 어떻게 하면 인스턴스를 테스트 메소드에 보내줄 수 있을까 고민하던 중, 우테코 크루 손너잘이 MethodSource의 사용법을 알려주었다.
- 인스턴스를 제공해줄 수 있는 provider 메소드를 정적으로 생성함으로써, 반복적으로 다양한 인자를 받아 테스트해야하는 경우에 대한 테스트 코드를 더 효율적으로 작성할 수 있었다.
## 링크
- [Guide To JUnit 5 Paramererized Tests](https://www.baeldung.com/parameterized-tests-junit-5)

2021-03-14 05:21 UTC, tributetothemoon commented on src/main/java/blackjack/controller/BlackJackController.java
> +    private void drawCardsOfDealerUntilOver16Score() {
사용되는 순서대로 코드를 재정렬하니 프로그램의 흐름을 읽기가 한결 수월해졌고, 협업에 도움이 되겠다는 생각이 들었습니다. 내 코드는 나만 보는 것이 아니라는 생각을 상기하며 코드를 작성할 수 있도록 주의하겠습니다!