[1단계 - 블랙잭 구현] 다니(이다은) 미션 제출합니다.
woowacourse/java-blackjack pull request #139
Opened 2021-03-04 09:08 UTC by da-nyee

안녕하세요 미립! 다니입니다 🙌

블랙잭 구현이 생각보다 더 어려워서 제출이 약간 늦었습니다...!
데드라인에 맞춰서 제출은 미리하지만, 틈틈이 더 수정하겠습니다!
미션을 진행하면서 궁금했던 점이랑 학습 로그는 추후에 작성해서 코멘트 남기겠습니다 👀

바쁘신 와중에 귀중한 시간 내주셔서 감사합니다 ✨

2021-03-04 11:32 UTC, da-nyee commented
# 📚 다니의 학습 로그

2021-03-04 12:29 UTC, da-nyee commented
# 📚 다니의 학습 로그
## [Java] 추상 클래스 vs 인터페이스 - 4
### 내용
- 추상 클래스는 IS-A 관계 + 미완성 설계도, 인터페이스는 HAS-A 관계 + 기본 설계도임
- 추상 클래스는 단일 상속만 가능하고, 인터페이스는 다중 상속도 가능함
- 추상 클래스는 상속 관계를 쭉 타고 올라갔을 때
  - 같은 조상 메소드를 상속하고, 기능까지 완전히 똑같은 기능이 필요할 때 사용함
- 인터페이스는 상속 관계를 쭉 타고 올라갔을 때
  - 다른 조상 클래스를 상속하고, 같은 기능이 필요할 때 사용함

![abstract_class_vs_interface](https://user-images.githubusercontent.com/50176238/109964194-b136e880-7d30-11eb-923e-15fceface4a0.png)

### 링크
- [[JAVA] 추상클래스 VS 인터페이스 왜 사용할까? 차이점, 예제로 확인](https://myjamong.tistory.com/150)

## [Etc] TODO.md 작성 - 3
### 내용
- 기능을 구현하며 기억해야 하는 내용들을 작성함
- 할 일, 완료한 일, 용어 정리로 소주제를 나눠서 정리함

### 링크
- [TODO.md](https://github.com/da-nyee/java-blackjack/blob/step1/docs/TODO.md)

2021-03-05 06:44 UTC, seok-2-o requested changes
안녕하세요 다니! 블랙잭 미션을 함께할 미립입니다.
반갑습니다 🙇 

어려운 미션인대 잘 진행해주셨네요 👍 
다만, 컨트롤러에서 하는일을 대신 해줄 객체를 만들면 더 좋을 것 같다는 생각이 들어요.
해당부분에 대해서 고민해보고 리펙토링 진행해보면 좋을 것 같아요

그 외에도 몇가지 코멘트 남겨 놓았으니 확인해주세요.

미션 진행하면서 저와 의견이 다르거나 궁금한점 어려운점 있으면 편하게 DM 주세요.

이번 미션도 즐겁게 해봐요 🔥

2021-03-05 06:44 UTC, seok-2-o commented on src/main/java/blackjack/controller/BlackjackController.java
> +public class BlackjackController {
컨트롤러에서 하는일이 많네요.

일정부분 책임을 묶어 새로운 객체로 만들 수 없을지 고민해보면 좋을 것 같아요.

2021-03-05 06:44 UTC, seok-2-o commented on src/main/java/blackjack/view/OutputView.java
> +    public static void printResultBoard(Dealer dealer, ResultBoard resultBoard) {
resultBoard 도 dealer 를 가지고 있는데 따로 넣어주는 이유가 있을까요?

2021-03-05 06:44 UTC, seok-2-o commented on src/main/java/blackjack/domain/Deck.java
> +    private static final Deque<Card> DECK = new ArrayDeque<>();
Deque 👍 

`static final` 로 선언하신 이유가 있을까요?

해당 게임이 여러명이 이용할 수 있는 다중 게임이라면 카드 분배과정에서 에러가 발생 할 수 있을 것 같아요.

2021-03-05 06:44 UTC, seok-2-o commented on src/main/java/blackjack/domain/Deck.java
> +    public static Cards popTwo() {
popOne() 을 2번 호출하는 것과
popTwo() 를 이용하는 것에 장 단점이 고민해보면 좋을 것 같아요 🤔

2021-03-05 06:44 UTC, seok-2-o commented on src/main/java/blackjack/domain/Deck.java
> +                .collect(Collectors.toList()));
```suggestion
        return Stream.generate(() -> DECK.pop())
            .limit(1)
            .collect(collectingAndThen(toList(), Cards::new));
```

2021-03-05 06:44 UTC, seok-2-o commented on src/main/java/blackjack/domain/DrawAnswer.java
> +public enum DrawAnswer {
boolean 값을 쓰는것에 비해 어떤 장점이 있나요? 🤔

2021-03-05 06:44 UTC, seok-2-o commented on src/main/java/blackjack/domain/Result.java
> +    }
승자를 구하는 로직을 Result 에서 수행하는 이유가 무엇인가요 ? 🤔 
스스로 할 수 있는 일을 외부에 도움을 받아서 처리한다면 객체 지향이라고 할 수 있을까요?

dealer.compre(player) 의 결과가 Result 인것이 더 자연스럽게 보여요.

2021-03-05 06:44 UTC, seok-2-o commented on src/main/java/blackjack/view/InputView.java
> +    }
👍

2021-03-08 11:47 UTC, da-nyee commented on src/main/java/blackjack/view/OutputView.java
> +    public static void printResultBoard(Dealer dealer, ResultBoard resultBoard) {
resultBoard는 dealer 이름을 가지고 있지 않아서 따로 넣어줬습니다!

2021-03-08 11:50 UTC, da-nyee commented on src/main/java/blackjack/view/OutputView.java
> +    public static void printResultBoard(Dealer dealer, ResultBoard resultBoard) {
resultBoard는 dealer 이름을 가지고 있지 않아서 매개변수로 넣어줬습니다!
dealer를 따로 받지 않고 출력문에 `"딜러"` 이렇게 작성해도 괜찮을까요?

2021-03-08 11:50 UTC, da-nyee commented
안녕하세요 미립! 다니입니다 🏃‍♀️

2021-03-08 11:53 UTC, da-nyee commented on src/main/java/blackjack/domain/DrawAnswer.java
> +public enum DrawAnswer {
만약 `Answer`에 로직이 필요하다면 클래스로 만들어야겠지만, 현재는 불필요하니까 boolean 값으로 쓰는 게 맞는 거 같아요!

2021-03-08 11:54 UTC, da-nyee commented on src/main/java/blackjack/domain/DrawAnswer.java
> +public enum DrawAnswer {
만약 `Answer`에 로직이 필요하면 클래스로 만들어야겠지만, 현재는 불필요하니까 boolean을 쓰는 게 맞는 거 같아요!

2021-03-08 11:56 UTC, da-nyee commented on src/main/java/blackjack/domain/Result.java
> +    }
`Result`를 반환하니까 Result에서 수행하게 작성했는데, 다시 생각해보니까 이건 객체지향이 아닌 거 같아요..!

2021-03-08 11:58 UTC, da-nyee commented on src/main/java/blackjack/controller/BlackjackController.java
> +public class BlackjackController {
[`29225f6`](https://github.com/woowacourse/java-blackjack/pull/139/commits/29225f6b3649ec4a1f7a724c7b25334b7fdfb55d) 수정했습니다!

2021-03-08 11:59 UTC, da-nyee commented on src/main/java/blackjack/domain/Deck.java
> +    private static final Deque<Card> DECK = new ArrayDeque<>();
[`7d7c970`](https://github.com/woowacourse/java-blackjack/pull/139/commits/7d7c9704d31309c61fdcf60b8533bba37a2eb43d) 수정했습니다!

2021-03-08 12:00 UTC, da-nyee commented on src/main/java/blackjack/domain/Deck.java
> +                .collect(Collectors.toList()));
[`4f6455e`](https://github.com/woowacourse/java-blackjack/pull/139/commits/4f6455e09ff71d9ee8c65b5f5f8f21bdb88dd713) 수정했습니다!

2021-03-08 12:00 UTC, da-nyee commented on src/main/java/blackjack/domain/DrawAnswer.java
> +public enum DrawAnswer {
[`6823482`](https://github.com/woowacourse/java-blackjack/pull/139/commits/6823482029de3bce773c781defb2d25b46917410) 수정했습니다!

2021-03-08 12:01 UTC, da-nyee commented on src/main/java/blackjack/domain/Result.java
> +    }
[`f6373de`](https://github.com/woowacourse/java-blackjack/pull/139/commits/f6373de6cf38d5f710a7fd7a64a964635b75b701) 수정했습니다!

2021-03-08 12:10 UTC, da-nyee commented
안녕하세요 미립! 다니입니다 🙌

피드백 남겨주신대로 리팩토링 진행했습니다!
DM 질문에 빠르게 답변해주셔서 다시 한번 감사드립니다 🙇‍♀️

리팩토링을 하다가 궁금한 점이 생겼는데요!

현재는 게임 결과를 구하는 로직이 Player 기준으로 Dealer도 판단해서 결정하게 되어있습니다.
근데, 일반적인 게임은 보통 딜러가 진행하니까 Dealer 기준으로 Player의 결과를 판단하는 게 맞지 않나? 라는 의문이 들었습니다.
리뷰어님의 생각이 궁금해요! 전자의 방식보다 후자의 방식이 더 자연스러울까요?? 아니면 지금처럼 둬도 괜찮을까요?!

이번에도 귀한 시간 내주셔서 감사합니다! 코드 리뷰 잘 부탁드립니다~! 🙏

2021-03-08 12:11 UTC, da-nyee commented
# 📚 다니의 학습 로그

2021-03-08 12:15 UTC, da-nyee commented
# 📚 다니의 학습 로그
## [Java] HashMap vs LinkedHashMap - 3
### 내용
- HashMap과 LinkedHashMap 둘 다 Map의 특징을 지닌다는 공통점이 있음
- HashMap은 데이터의 삽입 순서를 보장하지 않는 반면, LinkedHashMap은 삽입 순서를 보장한다는 차이점이 있음
- HashMap은 AbstractMap 클래스를 구현하는 한편, LinkedHashMap은 HashMap을 구현한다는 차이점도 있음

### 링크
- [[Java] HashMap vs LinkedHashMap](https://da-nyee.github.io/posts/java-hashmap-vs-likedhashmap/)

2021-03-08 13:46 UTC, seok-2-o requested changes
피드백 반영하고 새로운 객체 도출하느라 고생 많으셨어요.
해당 객체를 조금 더 객체답게 고민해볼 수 있는 코멘트 남겨 놓았습니다.
고민해보고 제 의견에 동의한다면 리팩토링 진행해주시고,
동의하지 않는다면 다시 PR 주세요. 바로 머지 할 수 있도록 하겠습니다.

어려운점이나 궁금한점은 편하게 DM 주세요.

2021-03-08 13:46 UTC, seok-2-o commented on src/main/java/blackjack/domain/BlackjackGame.java
> +    }
둘은 생성자를 통해서 생성해주면 어떤 장점이 있을까요?

참고로 이번과정에서 setter 사용은 금지(?) 되어 있습니다.

2021-03-08 13:46 UTC, seok-2-o commented on src/main/java/blackjack/domain/BlackjackGame.java
> +    private final List<User> users = new ArrayList<>();
딜러랑 플레이어즈를 구지 같이 가지고 있어야 할지 의문이에요

2021-03-08 13:46 UTC, seok-2-o commented on src/main/java/blackjack/domain/BlackjackGame.java
> +public class BlackjackGame {
해당 객체를 통해 블랙잭 게임을 완전히 캡슐화 해보는건 어떤가요?
컨트롤러 입장에서는 블랙잭 룰을 몰라도 게임이 진행 될 수 있도록 수정 할 수 있으면 좋을 것 같아요.

제가 컨트롤러를 만들고 다니가 게임 코어 엔진을 만든다고 생각해볼게요.

제가 구현하는 부분은 아래와 같습니다. 
1. 게임을 생성한다.
2. 게임이 종료되었는지 확인한다.
3. 게임이 종료되었지 않았다면 
3.1. 현재 플레이어와 카드를 출력한다.
3.2. 클라이언트에서 전달받은 응답을 게임에게 다시 전달한다.
```
pobi카드: 2하트, 8스페이드
pobi는 한장의 카드를 더 받겠습니까?
```

4. 3번으로 돌아간다.
5. 게임이 종료되었다면 게임의 결과를 출력한다.

2021-03-08 13:46 UTC, seok-2-o commented on src/main/java/blackjack/domain/user/Player.java
> +    }
둘을 분리할 필요가 있었을까요?

2021-03-09 12:49 UTC, da-nyee commented on src/main/java/blackjack/domain/BlackjackGame.java
> +public class BlackjackGame {
캡슐화가 생각보다 감이 잘 안 잡히네요.. 😥
게임 객체를 수정하면서 나름대로 컨트롤러 캡슐화를 진행한 거 같은데, 확신이 안 들어서 질문 드립니다!
[BlackjackController](https://github.com/da-nyee/java-blackjack/blob/step1/src/main/java/blackjack/controller/BlackjackController.java)가 리팩토링한 클래스인데, 제대로 캡슐화를 한 것인가요??
혹시 아직 부족한 점이 있다면 말씀해주세요!! 바로 반영해보겠습니다! 🙇‍♀️

2021-03-09 12:50 UTC, da-nyee commented
안녕하세요 미립! 다니입니다 🙌

추가로 코멘트 남겨주신 것들 반영해봤는데 확인 부탁드립니다!
피드백에서 궁금한 부분은 👀 이모지로 표시해뒀습니다. 이 부분도 확인해주시면 감사하겠습니다! 🙏

2021-03-10 02:55 UTC, seok-2-o commented on src/main/java/blackjack/domain/BlackjackGame.java
> +public class BlackjackGame {
출력을 제외하고 getter 가 사용되는 부분이 하나도 남지 않아야 캡슐화가 잘 진행되었다고 불 수 있을 것 같아요.
위에 제가 설명한걸 코드로 풀면 아래와 같아요(컨트롤러에서 수행되는 로직)
```java

Game game = new Game(players):
OutputView.print(game);
while(game.isEnd()) {
    Player player = game.getCurrentPlayer():
    String res = InputView.ask(player) => 'player.name' 은 한장의 카드를 더 받겠습니까?
    game.next(res) ;
}

OutputView.print(game.getResult());
```

2021-03-10 02:56 UTC, seok-2-o requested changes
피드백 반영 잘해주셨네요 👍 

질문하신 내용에 추가 코멘트 남겨놓았습니다. 해당부분 확인 부탁드려요.

2021-03-10 09:40 UTC, seok-2-o approved these changes
피드백 반영 빠르게 잘 해주셨어요 💯 
소소한 질문하나 더 남겨놓았는데 다음 미션 진행하면서 함께 고민해보면 좋을 것 같아요.

2021-03-10 09:40 UTC, seok-2-o commented on src/main/java/blackjack/domain/BlackjackGame.java
> +    }
게임은 Player 가지고 있는데 외부에서 주입 받을 필요가 있을까요?

2021-03-10 09:40 UTC, merged