[1단계 - 블랙잭 구현] 알리(허진호) 미션 제출합니다.
woowacourse/java-blackjack pull request #150
Opened 2021-03-04 09:47 UTC by jh8579

안녕하세요 알리입니다!

이번 미션에는 고려해야할 조건도 많고 여러가지고 상속과 Dto를 적용하느라 저번 미션에 비해서 갑자기 난이도가 확 올라간 느낌이네요ㅜㅜ
코드 구현을 하면서도 "이게 맞나"라는 생각을 많이 했습니다.
이번 미션을 진행하면서 궁금했던 부분을 질문해보려고 합니다.

### 고민한 부분

#### Controller의 역할

```java
// BlackjackController.java
//
// 기존 코드
private void drawCards(Deck deck, Game game) {
        game.getPlayers().forEach(player -> getAdditionalCard((Player) player, deck));
        OutputView.printDealerDraw(game.askDrawToDealer(deck));
    }

    private void getAdditionalCard(Player player, Deck deck) {
        while (player.isHit()) {
            player.askDraw(InputView.askIfMoreCard(player), deck);
            OutputView.printPlayerCard(player);
        }
    }
```

```java
// BlackjackController.java
//
// 개선 코드
private void drawCardsV2(Game game) {
    while (game.isAnyPlayerHit()) {
        PlayerDto hitPlayerDto = game.getAnyHitPlayerDto();
        game.drawCard(hitPlayerDto, InputView.askIfMoreCardV2(hitPlayerDto));
        OutputView.printPlayerCardV2(hitPlayerDto);
    }
    OutputView.printDealerDraw(game.askDrawToDealer());
}
```
이번 미션에서는 Player의 상태에 따라 사용자의 입력을 동적으로 받아야하는 기능이 있습니다.
Controller에서만 input을 관리하려고 노력하다보니,
기존 코드에서는 플레이어 리스트를 Controller에 가져와서 사용자 입력에 대한 처리를 했습니다.

개선 코드에서는 매번 Game 클래스에 player의 상황을 물어보고,
그때마다 input을 Game 클래스에 넘겨주는 방식으로 변경해봤는데
게이츠님의 생각은 어떤지 궁금합니다!

#### 상속...캐스팅
이번 미션에서 User라는 부모 클래스와 Dealer, Player 두 자식 클래스를 생성했습니다.
그런데 Player만의 메소드가 필요할 때는 어떤 식으로 해결하는지 알고 싶습니다!

감사합니다!

2021-03-07 19:53 UTC, serverwizard requested changes
안녕하세요 알리! 블랙잭 미션을 함께할 (빌) 게이츠입니다.
반갑습니다 🙇

어려운 미션인데 잘 진행해주셨네요 👍
몇 가지 피드백 남겨두었으니 확인해주시고 리펙토링 진행해보면 좋을 것 같아요

미션 진행하면서 저와 의견이 다르거나 궁금한점 어려운점 있으면 편하게 DM 주세요.

이번 미션도 즐겁게 해봐요 🔥

2021-03-07 19:53 UTC, serverwizard commented on src/main/java/blackjack/domain/Game.java
> +        }
현재 해당 메소드가 2가지 일을 하고 있는 것 같은데, 한 가지 일만 하도록 메소드를 분리하는 건 어떨까요?

2021-03-07 19:53 UTC, serverwizard commented on src/main/java/blackjack/domain/card/Deck.java
> +    private final Stack<Card> cards;
카드를 미리 생성해 두고 필요할 때 사용할 수는 없을까요? (캐시 개념)

2021-03-07 19:53 UTC, serverwizard commented on src/main/java/blackjack/domain/user/MatchResult.java
> +        if (player.getStatus() == HandStatus.BUST) {
객체에서 값을 조회해 와서 비교하지말고, 객체에게 메시지를 통해 책임을 위임하는 건 어떨까요?

2021-03-07 19:53 UTC, serverwizard commented on src/test/java/blackjack/domain/DeckTest.java
> +class DeckTest {
단위 테스트 관련해서 참고로 공유 드리는 부분인데요~

단위 테스트 용이성으로 객체지향 설계 품질을 측정할 수도 있어요~
즉, 객체지향 설계의 품질이 좋으면 좋을 수록 단위 테스트 작성이 쉽다고 보면 됩니다.

2021-03-07 19:59 UTC, serverwizard commented
```
개선 코드에서는 매번 Game 클래스에 player의 상황을 물어보고,
그때마다 input을 Game 클래스에 넘겨주는 방식으로 변경해봤는데
게이츠님의 생각은 어떤지 궁금합니다!
```
개인마다 의견이 다를 순 있겠지만, 저는 좋은 접근 법이라고 생각해요~
```
상속...캐스팅
이번 미션에서 User라는 부모 클래스와 Dealer, Player 두 자식 클래스를 생성했습니다.
그런데 Player만의 메소드가 필요할 때는 어떤 식으로 해결하는지 알고 싶습니다!
```
자식에서만 필요한 메소드는 자식에서 선언해서 사용하면 될 것 같아요
자식에서 공통적으로 사용되는 메소드라면 부모 클래스에서 선언해서 사용하구요~

2021-03-08 08:51 UTC, jh8579 commented
### 변경사항
* 모든 카드 덱을 미리 생성해놓고 사용할 때만 셔플하여 사용하도록 변경
* getter를 사용하여 비교하던 로직을 모두 메시지를 보내 책임 위임
* 필요 없는 주석 제거 및 코드 정리

### 고민한 부분
```java
// User 클래스

public boolean isLessScoreThan(User user) {
        return hand.isLessScoreThan(user.getScore());
    }

    public boolean isSameScore(User user) {
        return hand.isSameScore(user.getScore());
    }
``` 
위와 같이 score가 User 내부에 Hand에 위치해서 비교하기 위해 어느 순간에는 getter를 사용해야 하는 부분이 있는데,
이럴 경우에는 score에 대한 책임을 User로 가져와야 할까요?

2021-03-08 09:00 UTC, jh8579 commented
# [JDK] Collectors API groupBy - 1
## 내용
- Collectors API의 groupBy 메소드를 활용하여 출력 시에 Player의 승/무/패 모두 모아 Dealer의 승무패 계산
- 중복된 Collectors 사용을 static import를 사용하여 가독성을 높임
## 링크
- 정리 예정 - https://velog.io/@jh8579/Stream-API
- 참조 - https://recordsoflife.tistory.com/55
```java
public static Map<MatchResult, Long> calculateMathResultCount(List<WinningResultDTO> winningResultDTOs) {
        return winningResultDTOs.stream()
            .map(WinningResultDTO::getResult)
            .collect(groupingBy(Function.identity(), counting()));
    }
```

2021-03-09 07:03 UTC, jh8579 commented
# [객체지향] 방어적 복사 - 2
## 내용
- 원본 객체 수정을 방지하기 위해 List 반환 시에 새로운 리스트를 생성하여 반환
## 링크
- https://velog.io/@jh8579/%EB%B0%A9%EC%96%B4%EC%A0%81-%EB%B3%B5%EC%82%AC%EB%B6%88%EB%B3%80-%EA%B0%9D%EC%B2%B4
```
public List<Card> shuffleCards() {
        List<Card> cards = new ArrayList<>(deck);
        Collections.shuffle(cards);
        return new ArrayList<>(cards);
}
```

2021-03-13 03:07 UTC, serverwizard commented
```
고민한 부분
// User 클래스

public boolean isLessScoreThan(User user) {
        return hand.isLessScoreThan(user.getScore());
    }

    public boolean isSameScore(User user) {
        return hand.isSameScore(user.getScore());
    }
위와 같이 score가 User 내부에 Hand에 위치해서 비교하기 위해 어느 순간에는 getter를 사용해야 하는 부분이 있는데,
이럴 경우에는 score에 대한 책임을 User로 가져와야 할까요?
```

2021-03-13 03:18 UTC, serverwizard approved these changes
안녕하세요 알리
step1 진행하신다고 수고 많으셨습니다! 👏👏
몇 가지 코멘트 남겼어요! 
step2 진행할 때 참고하면 좋을 것 같아요!🙂
오래 기다리게 해서 죄송합니다🙇♂️

2021-03-13 03:18 UTC, serverwizard commented on src/main/java/blackjack/controller/BlackjackController.java
> +    }
BlackjackController부분이 정말 깔끔해졌네요 👍

2021-03-13 03:18 UTC, serverwizard commented on src/main/java/blackjack/domain/Game.java
> +    private final List<User> players;
이를 일급 콜렉션으로 만들어 볼 수도 있겠네요~

2021-03-13 03:18 UTC, serverwizard commented on src/main/java/blackjack/domain/Game.java
> +    public PlayerDto getAnyHitPlayerDto() {
현재 Game 도메인 객체에서 DTO를 의존하고 있는데요.
DTO는 애플리케이션의 외부 요구 사항(UI)을 반영한 것이고, 도메인 객체는 내부 요구 사항(비즈니스 로직)을 반영한 것이라 이를 분리하는 건 어떨까요?
만약, 현재와 같은 구조라면 DTO(UI)가 변경 됐을 때 도메인 객체에도 영향을 줄 수 있을 것 같아요.

2021-03-13 03:18 UTC, serverwizard commented on src/main/java/blackjack/domain/card/Deck.java
> +    private static final List<Card> deck;
상수는 보통 대문자로 변수명을 표현합니다~

2021-03-13 03:18 UTC, serverwizard commented on src/main/java/blackjack/domain/card/Deck.java
> +        return new ArrayList<>(cards);
아래와 같이 불변객체로 리턴할 수도 있을 것 같아요! (추가, 삭제행위가 금지)
```
Collections.unmodifiableList(cards);
```

2021-03-13 03:18 UTC, merged