[2단계 - 블랙잭 구현] 멍토(김유기) 미션 제출합니다.
woowacourse/java-blackjack pull request #177
Opened 2021-03-11 05:38 UTC by daum7766

휴! 안녕하세요

2단계 미션도 잘 부탁해요!

이번 미션은 상태 패턴을 공부하고 적용하느라 많이 늦었어요. ㅜㅠ

이상한 부분이 있다면 피드백 부탁해요!

아래는 하면서 생겼던 질문사항입니다!

1. 테스트코드에서 Card를 자주 쓰게 돼서 Card를 캐싱하게 되었습니다.
테스트를 위한 캐싱은 괜찮을까요? 아니면 큰 상관이 없을까요?

2. 메소드를 만드는데 인자를 4개 이상은 사용하지 말라고 배웠습니다.
이것은 생성자 또한 포함될까요?
(외부로 지원하는 것은 최대 3개, 내부적으로 로직을 추가하기 위해 4개로 증가)

감사합니다!

2021-03-11 08:12 UTC, daum7766 commented
# 멍토의 학습 프로필



## 상태 패턴 - 4

### 내용

- 특정 상태에 따라서 동작하는 방식이 바뀌는 상태 패턴에 대하여 공부
- 카드의 합 상태에 따라 상태를 적용할 수 있었음
- 특정 상태 때만 나오는 행동들만 생각할 수 있어서 작성이 좀 더 쉬웠음
  - 내가 블랙잭이라면 상대방이 블랙잭일 때만 무승부이고 나머지는 승리 등.
- 상태 패턴을 적용함으로써 조건분기를 줄일 수 있어서 가독성이 향상됨

2021-03-11 16:34 UTC, Hue9010 requested changes
멍토! 상태 패턴을 활용하여 추가된 요구사항을 잘 구현해주셨네요 💯 
몇가지 피드백을 남겼는데 확인하시고 궁금한건 언제들 질문주세요!! 😉

2021-03-11 16:34 UTC, Hue9010 commented on src/main/java/blackjack/domain/player/dto/GameResultDTO.java
> +    private final int dealerResult;
단순 결과라기보다는 수익인데 이걸 알수 있는 이름을 사용하는게 좋아보입니다.

2021-03-11 16:34 UTC, Hue9010 commented on src/main/java/blackjack/domain/player/AbstractPlayer.java
> +        return Collections.unmodifiableList(state.cards().getCards());
state의 카드를 가져오는걸 생각해보면 기존에 사용한 전략패턴을 제거하고 딜러 전용의 최초 드로우 받았을 때만 사용할 State를 만들어 줄 수도 있을 것 같아요.

2021-03-11 16:34 UTC, Hue9010 commented on src/main/java/blackjack/domain/card/PlayerCards.java
> +public class PlayerCards {
카드게임에서 주로 사람이 손에 들고 있는 카드는 핸드(Hand)라고 표현해요. 블랙잭 또한 이 용어를 사용하는걸로 알고 있는데 핸드라는 명칭을 사용해주신다면 카드게임에 대한 지식이 있는 사람한테는 PlayerCards가 무엇인지 아는데 도움이 될 것 같아요. 😉

2021-03-11 16:34 UTC, Hue9010 commented on src/main/java/blackjack/domain/player/User.java
> +        super(name, firstCard, secondCard);
> 2. 메소드를 만드는데 인자를 4개 이상은 사용하지 말라고 배웠습니다.
> 이것은 생성자 또한 포함될까요?
> (외부로 지원하는 것은 최대 3개, 내부적으로 로직을 추가하기 위해 4개로 증가)


넵, 생성자도 포함된다고 생각합니다. 보통 생성자에 그렇게 많은 값이 들어온다는 건 필드 값이 많아진다는 건데 하나의 객체가 많은 상태를 관리하는건 쉽지 않습니다. 지금의 유저보다 더 많은 상태를 가진 객체가 상태 관리를 한다고 생각해보죠. 클래스 자체도 비대해지고 신경써야 할 것도 많아 질 겁니다. 그럴 때 List\<Card>에 대한 작업은 PlayerCardss에 위임해서 User의 부담이 줄어 든 것처럼(상태패턴을 적용하기 위해 추가하신 것 같지만 😋) 인자가 많다는건 일부 공통 요소로 새로운 요소를 추상화 시킬 여지가 많습니다.
당장 좋은 예는 안떠오르는데 User에 전화번호, 나이, 닉네임이 추가된다면 기존의 이름을 포함해서 인적사항을 추상화 시킬 수 있을 것 같아요.

그렇게 추상화 시키지 않는다쳐도 두장의 카드를 받는게 아니라 이미 주입 받을 때 부터 PlayerCards를 받아오게 고칠 수도 있을 것 같네요. 😉

[[아이템 2] 생성자에 매개변수가 많다면 빌더를 고려하라](https://walbatrossw.github.io/java/2018/11/10/effective-java-rule-2.html)가 있지만 테크코스 과정 중 롬복 사용은 제한하는 걸로 알고 있고, 빌더 패턴을 직접만드는건 쉽지 않으니 참고만 해주세요.

2021-03-11 16:34 UTC, Hue9010 commented on src/main/java/blackjack/domain/player/AbstractPlayer.java
> +        return Collections.unmodifiableList(state.cards().getCards());
위 제안은 선택적으로 진행해주시면 될 것 같아요. 진행하실지 여부를 알려주면 좋을 것 같아요.
사실 상태 패텬 포함하여 굉장히 잘 추가해주셔서 이 고민을 해보시는 것 외에는 이번 단계는 머지하여 마무리해도 좋을 상태입니다. 👍

2021-03-11 23:59 UTC, daum7766 commented on src/main/java/blackjack/controller/BlackJackController.java
> +public class BlackjackController {
엇!.. 바꿀때 실수가 있었던거 같습니다.
그런데 동작은 정상적으로 됐었네요...
수정하겠습니다.

2021-03-12 00:00 UTC, daum7766 commented on src/main/java/blackjack/domain/card/Card.java
> +    private static final Card[] cards = new Card[cardSize];
좋은 이야기 감사합니다!

2021-03-12 00:00 UTC, daum7766 commented on src/main/java/blackjack/domain/player/dto/GameResultDTO.java
> +    private final int dealerResult;
수익과 관련된 네이밍으로 변경하겠습니다.

2021-03-12 00:01 UTC, daum7766 commented on src/main/java/blackjack/domain/card/PlayerCards.java
> +public class PlayerCards {
바로 변경하겠습니다.

2021-03-12 00:02 UTC, daum7766 commented on src/main/java/blackjack/domain/player/User.java
> +        super(name, firstCard, secondCard);
넵 감사합니다.
적어주신 내용은 추가적으로 공부하도록 하겠습니다!

2021-03-12 00:03 UTC, daum7766 commented on src/main/java/blackjack/domain/player/AbstractPlayer.java
> +        return Collections.unmodifiableList(state.cards().getCards());
상태패턴으로 구현해보도록 하겠습니다.

2021-03-12 04:06 UTC, daum7766 commented
DM으로 고민했던 내용을 이야기하고 의견도 많이 내주셔서 정말 좋은 시간이었습니다!
휴가 말씀해주신데로 네이밍과 클래스명 변경을 했습니다.
컨트롤러 오타도 수정했어요!

마지막으로 전략패턴을 상태패턴으로 적용해 보았습니다.
내부에서 자체적으로 수정하는 로직이 없어서 따로 stateChange함수를 통해 상태를 바꾸도록 했는데
해당방법이 맞는지는 잘 모르겠어요!
휴의 의견 부탁드릴게요!

2021-03-12 13:03 UTC, Hue9010 approved these changes
멍토!! 마지막까지 잘 구현주셨네요. 👍👍
이번 단계는 여기서 머지할게요.
궁금한게 생기면 언제든 질문해주세요. 😉 
(혹시나 제가 빠트린 질문이 있다면 알려주세요!!!!)

이번 과제 진행하면서 고생많으셨습니다.
남은 과정도 화이팅입니다! 😄

2021-03-12 13:04 UTC, merged

2021-03-13 03:52 UTC, daum7766 commented on src/test/java/blackjack/domain/player/UserTest.java
> +        User user = new User(TEST_NAME, twoCard, twoCard);
생성시 카드를 넘겨줘야 하는데 넘겨주지 않아 랜덤한 요소가 포함되어 테스트가 실패할 때가 있어서 수정했습니다!