[2단계 - 블랙잭 구현] 소롱(최솔지) 미션 제출합니다.
woowacourse/java-blackjack pull request #178
Opened 2021-03-11 05:48 UTC by soulgchoi

안녕하세요 재연링!
1단계 후로 다소 늦게 2단계를 겨우 제출합니다.
재연링이 학습을 다 마치고 코드를 짜려하지 말라고 조언해주셨는데, 이번에 잘 지키지 못했어요.
전체에서 어느 부분이 바뀌어야 할까를 먼저 생각하다보니 배팅 금액 받는 것부터 참 어렵더라구요.
그래서 일단 작은 단위는 TDD로 짜고 나머지는 차차 수정해나가려고 합니다..!

피드백 적용한 부분과 질문들은 길어져서 따로 코멘트로 추가하겠습니다.
감사합니다!

2021-03-11 06:35 UTC, soulgchoi commented
1. `split()` 메서드의 limit를 좀 더 공부했습니다! 전에 페어가 쓰는걸 보고 별 생각없이 쓰고 있었는데 정확한 용도를 알게 되니 제 의도대로라면 -1을 빼는 게 맞겠어요.

2. NumberCandidate와 SymbolCadidate를 CardNumber와 CardSymbol로 만들었습니다. 생각해보니 이미 enum으로 만든 것을 또 캐싱할 필요는 없겠더라구요. 어차피 카드들은 CardDeck에서 한 번만 만들고 사용하므로 두 번 불러올 필요가 없다고 생각했습니다.

3. for 문으로 입력 받을 때, 꼭 `Scanner.nextLine()` 입력을 마지막에 더 받아야 할까요? 개행이 들어가서 계속 에러가 발생하는데 다른 해결 방법이 없을지 궁금합니다..

4. dealer와 player의 draw 로직 자체는 크게 차이가 없는데 while을 쓰냐 재귀를 쓰냐로 각각 다르게 오버플로우가 발생하는 문제가 있었습니다. 왜 이런 문제가 생기는지 전혀 모르겠습니다ㅠㅠ

5. 딜러 수익을 구하면서 플레이어 수익을 출력하려니 어려워서 일단 딜러를 나중에 출력하고 있습니다. 결과를 두 번 구하는건 별로 좋지 않은 것 같아서요. 미션 예시대로 출력하면서 효율적으로 할 만한 힌트를 주실 수 있나요?

6. 디미터 패턴은 '모르는 객체의 메서드를 가져오지 마라'가 핵심인 것 같은데, 인스턴스로 가지고 있는 객체의 메소드를 호출하여 결과를 반환하는건 괜찮은가요? 아래 User의 경우라면, userDeck을 모르는 객체가 getScore만 할 수 있게요!

   ```public Double getMoney(double earningRate) {
   // Player
   public Double getMoney(double earningRate) {
       return money.getEarning(earningRate);
   }
   
   // User
   public int getScore() {
       return userDeck.deckScore();
   }
   ```

7. `승패무`를 enum으로 만드는 것까진 좋았는데, bust, blackjack 판별을 user에서 하고있다보니 점수만 가져가서 판단하기가 쉽지 않았어요. 이 부분도 혹시 구조를 개선할만한 조언이 있다면 부탁드리겠습니다.

8. 1단계에서 view에 대한 질문을 했었습니다. 저는 view에는 가장 로우한 데이터를 주는게 좋지 않을까 라고 생각합니다. MVC 패턴의 규칙 중에 '모델이나 컨트롤러를 참조하면 안된다'고 알고 있는데, domain에 접근하는건 그 모델을 알고 있어야 가능한게 아닌가요? 그래서 view에서 get 하는걸 지양하고 있었는데 너무 복잡하고 어려웠어요. 
이 과정에서 따로 BlackjackGame을 만들고 컨트롤러에서 데이터만 뷰에 주려는 시도를 했지만...! 반복문 안에서 어떻게 처리할지 고민하다가 타협을 좀 했습니다. 
사실 지난번에도 get하는건 괜찮다는 피드백을 받았지만 비슷한 시도를 계속 하게 되네요😅

2021-03-12 04:11 UTC, jaeyeonling requested changes
2단계 미션도 잘 해주셨네요 👍 
질문의 답변과 추가적인 피드백 남겨두었으니 확인 부탁드리겠습니다 :)

2021-03-12 04:11 UTC, jaeyeonling commented on src/main/java/blackjack/domain/user/Money.java
> +    private final double money;
```suggestion
    private static final String MIN_MONEY_ERROR = "[ERROR] 배팅 금액은 0원이 될 수 없습니다.";

        private final double money;
```

클래스 변수와 인스턴스 변수 사이에 공백이 존재한다면 가독성이 상승합니다

2021-03-12 04:11 UTC, jaeyeonling commented on src/main/java/blackjack/domain/user/Player.java
> +    }
getMoney라는 네이밍은 Money를 응답해야 할 것 같아요!
또한 get- 라는 네이밍은 getter에서 관례적으로 사용하는 네이밍으로 로직이 존재한다면 get-이 아닌 적절한 네이밍에 대해 고민해보아요

2021-03-18 17:49 UTC, soulgchoi commented
안녕하세요, 재연링!
추가 리팩토링이 늦어도 너무 늦어서 죄송합니다🙇‍♀️
피드백 반영하고 상태 패턴을 사용(하려고 노력)했습니다.

- 피드백 주신 부분들 중에 getter 말고 어떤 값을 가져오는 역할을 하는 메소드들을 어떻게 이름지을지 아직 잘 모르겠습니다. 혹시 재연링이 선호하는 방식이 있다면 조언해주실 수 있을까요?
- 그리고 cardNumber와 cardSymbol을 왜 String으로 받고 있냐고 코멘트 주셨는데, 저도 다시 보니까 그냥 enum을 쓰면 되더라구요. 테스트 할 때 String으로 카드를 만들다보니 이렇게 되었던 것 같습니다. 사실 테스트를 바꿀 엄두가 안나서 부생성자를 만들었다가 전체 다시 수정했습니다. 테스트를 위한 부생성자는 없는 게 맞겠죠?

아래는 특히 더 피드백 받고 싶은 내용입니다!

- 상태 패턴을 적용한다고 했는데 Result를 추가로 판단해야 해서 수익 구하는 로직이 다소 복잡해져서 아쉽습니다. 지금 적절하게 하고 있는 걸까요?
- BlackjackGame을 만들어서 컨트롤러를 쪼갰습니다. 하지만 여전히 컨트롤러에서 하는 일이 많고, BlackjackGame에서 뭔가 가져오지 않으면 처리하기 힘든 부분이 많습니다. 이렇게 계속 get으로 가져오면 나눈 의미가 있나? 싶기도 했구요. 그래서 수익 구하는 부분만 BlackjackGame으로 옮겼는데 이게 더 나을까요? 두 부분 다 커밋을 해둬서 봐주셨으면 합니다.
 [🐕처음 BlackjackGame을 나눈 코드](https://github.com/soulgchoi/java-blackjack/tree/e2b2668d477ed62918e43b267954c644ed283e7b)와 [🐈수익만 BlackjackGame이 하는 코드](https://github.com/soulgchoi/java-blackjack/tree/4f741687f6c15cf896e2b33f327627256999597c)입니다!

이번에도 잘 부탁드립니다🙇‍♀️🙇‍♀️🙇‍♀️ 감사합니다🙇‍♀️🙇‍♀️🙇‍♀️

2021-03-20 11:33 UTC, jaeyeonling approved these changes
피드백 반영 잘 해주셨네요! 💯 
수 많은 피드백 반영하시느라 고생 많으셨어요!!!

2021-03-20 11:33 UTC, jaeyeonling commented on src/main/java/blackjack/domain/card/Card.java
> +    private static final String ACE_NUMBER = "A";
해당 값은 사용하지 않네요 :)

2021-03-20 11:33 UTC, jaeyeonling commented on src/main/java/blackjack/controller/BlackJackController.java
>  public class BlackJackController {
질문의 답변 남겨두겠습니다 :) 

Q1. 피드백 주신 부분들 중에 getter 말고 어떤 값을 가져오는 역할을 하는 메소드들을 어떻게 이름지을지 아직 잘 모르겠습니다. 혹시 재연링이 선호하는 방식이 있다면 조언해주실 수 있을까요?
A1. 단순 데이터를 가져오는 경우 getter와 같은 네이밍을 적용해주셔도 되지만 특별한 역할을 담당한다면 어떠한 역할을 담당하는지를 알 수 있도록 의미를 전달하는 것이 좋습니다

https://github.com/woowacourse/java-blackjack/pull/178#discussion_r592826974 해당 코멘트의 경우 `getCard()`라는 네이밍으로 봤을 때 `Card`를 응답할 것은 느낌을 주어 남긴 피드백이였고!

https://github.com/woowacourse/java-blackjack/pull/178#discussion_r592897463 피드백의 경우 위와 동일하게 `Money`를 응답해야할 것 같은 느낌과 수익을 곱하는 로직을 네이밍으로 알 수 없어 남긴 리뷰였습니다 :)


Q2. 그리고 cardNumber와 cardSymbol을 왜 String으로 받고 있냐고 코멘트 주셨는데, 저도 다시 보니까 그냥 enum을 쓰면 되더라구요. 테스트 할 때 String으로 카드를 만들다보니 이렇게 되었던 것 같습니다. 사실 테스트를 바꿀 엄두가 안나서 부생성자를 만들었다가 전체 다시 수정했습니다. 테스트를 위한 부생성자는 없는 게 맞겠죠?
아래는 특히 더 피드백 받고 싶은 내용입니다!
A2. `테스트만을 위한 부생성자`라는 관점으로 접근했을 때는 없는 것이 맞습니다
하지만 개인적으론 설계에 자연스러운 느낌을 준다면 존재해도 괜찮다고 생각하는데요
해당 프로젝트에 적용할수 있는 간단한 예를 보면 CardNumber.of("A")와 CardNumber.of(11)와 같이 설계 상 자연스러운 형태를 가지고 있다면 존재해도 문제가 없다고 생각해요!


Q3. 상태 패턴을 적용한다고 했는데 Result를 추가로 판단해야 해서 수익 구하는 로직이 다소 복잡해져서 아쉽습니다. 지금 적절하게 하고 있는 걸까요?
A3. 상태 패턴으로 구현하는 것이 쉽지 않으셨을텐데 수익을 구하는 로직 둘 다 깔끔하게 잘 구현해주신 것 같습니다 ㅎㅎ 
지금도 잘 구현해주셨지만 추가적으로 리뷰를 남겨드린다면! Result 등 유틸성으로 사용하고 있는 클래스들을 유틸성이 아닌 객체로 역할을 넘겨주면 더욱 좋을 것 같습니다 :)


Q4. BlackjackGame을 만들어서 컨트롤러를 쪼갰습니다. 하지만 여전히 컨트롤러에서 하는 일이 많고, BlackjackGame에서 뭔가 가져오지 않으면 처리하기 힘든 부분이 많습니다. 이렇게 계속 get으로 가져오면 나눈 의미가 있나? 싶기도 했구요. 그래서 수익 구하는 부분만 BlackjackGame으로 옮겼는데 이게 더 나을까요? 두 부분 다 커밋을 해둬서 봐주셨으면 합니다.
A4. 반영해주신 코드를 확인하니 BlackjackGame을 분리하는 것이 오히려 가독성을 떨어트리는 느낌이 보이네요..ㅎㅎ
해당 피드백은 도메인과 View의 범위를 생각해보면 좋을 것 같다는 의미로 남긴 피드백인데요!
서비스가 커져 웹 서비스로도 공개된다 했을 때 도메인에 대한 코드는 변경되거나 웹과 콘솔에 중복되는 부분이 있다면 도메인이 할 일을 View나 Controller에서 하는게 아닐까? 라고 고민해보시면 좋을 것 같습니다 :)

2021-03-20 11:33 UTC, merged