[2단계 - 블랙잭 구현] 아론(장세환) 미션 제출합니다.
woowacourse/java-blackjack pull request #184
Opened 2021-03-11 08:17 UTC by Sehwan-Jang

안녕하세요 휴!
이번 step2 단계는 수업시간에 배운 상태패턴을 구현해보는데 주안점을 두어 진행했습니다.

## Q1
사실 상태패턴을 적용한 이유는 다형성을 이용하여 수 많은 if문들을 없애보자는 수업을 듣고 적용해보자는 것에서 시작했습니다. 
하지만 막상 구현을 다해보고 나니, 제가 잘 알지 못하고 적용한 것인지 기존의 boolean 값을 필드로 가지고 사용한 방식에 비해 크게 개선된 점이 보이지 않았습니다. 오히려 상태패턴을 적용하려는 본래의 목적보다는 수익률을 구하는 부분에서 유용하게 사용한것 같은데요. 
그렇다면 수익률은 Enum(`ResultType`) 이 도맡아서 반환하도록하고, 그것을 제외한 나머지는 상태패턴을 적용하기 전의 구조가 더 낫지 않았나...라는 생각도 들었습니다 ㅎㅎ..
그래서 실제로 제가 상태패턴을 잘못 적용한 것인지, 혹은 굳이 상태패턴이 필요할 정도의 미션이 아닌건지 궁금합니다.

## Q2
미션의 요구사항이 승패를 출력하는 것에서 각 참가자들의 수익을 출력하도록 하게끔 바뀌면서 기존의 `GameResult` 클래스를 더이상 사용하지 않고 `Player` 객체가 그 책임을 가지도록 수정했습니다.
그 이유는 `Player` 객체가 이미 `Money` 와 수익률을 반환 해주는 `State`를 필드로 가지고 있기 때문에 그 둘을 곱해주는 메소드 하나만 만들면 바로 수익을 구할 수 있었기 때문입니다.
하지만 수정하는 과정에서 과연 Player 객체가 그 책임을 가지도록 하는 것이 객체지향적이라고 볼 수 있을까? 라는 의문이 들었습니다. 

## 
이번에도 제 코드 봐주셔서 감사합니다 :)
질문 이외에 어떠한 것이라도 즐겁게 리팩토링할 준비가 되어있으니 부탁드려요 ㅎㅎ

PS. 1단계 에서 지적해주신 CheckedException 이슈는 사실 UnChecked 커스텀예외는 이미 전단계 미션에서 사용해본적이 있어서 _이번에는 checked도 한번 써보자_ 하는 생각으로 구현했었습니다. 
하지만 말씀해주신 것처럼 유쾌한 경험은 아니었고... 링크 주신 클린코드 글을 읽고 확신을 가지고 UnChecked 로 바꾸었습니다!
(이외에도 휴가 주신 참고할 링크들 모두 정말 유익하더라구요 감사합니다 ㅠㅠ)

2021-03-11 18:44 UTC, Hue9010 requested changes
아론!  잘 요구사항에 맞게 잘 구현해주셨네요. 👍
질문에 대해서 답변 남겼는데 한번 확인해주세요!
피드백에 대해서는 어떻게 적용할지는 아론이 판단해주시면 될 것 같아요. 😉

2021-03-11 18:44 UTC, Hue9010 commented on src/main/java/blackjack/domain/participant/Player.java
>          return ResultType.getResultType(getScore() - dealer.getScore());
> 1. 사실 상태패턴을 적용한 이유는 다형성을 이용하여 수 많은 if문들을 없애보자는 수업을 듣고 적용해보자는 것에서 시작했습니다.
하지만 막상 구현을 다해보고 나니, 제가 잘 알지 못하고 적용한 것인지 기존의 boolean 값을 필드로 가지고 사용한 방식에 비해 크게 개선된 점이 보이지 않았습니다. 오히려 상태패턴을 적용하려는 본래의 목적보다는 수익률을 구하는 부분에서 유용하게 사용한것 같은데요.
그렇다면 수익률은 Enum(ResultType) 이 도맡아서 반환하도록하고, 그것을 제외한 나머지는 상태패턴을 적용하기 전의 구조가 더 낫지 않았나...라는 생각도 들었습니다 ㅎㅎ..
> 그래서 실제로 제가 상태패턴을 잘못 적용한 것인지, 혹은 굳이 상태패턴이 필요할 정도의 미션이 아닌건지 궁금합니다.

우선 State부터 보죠.

```java
public interface State {

    State update(Hand hand);

    State stay();

    boolean isFinished();

    double profitRate(ResultType match);
}
```

사실 코드와 함께 봤을 때 느껴진 부분이 상태패턴을 적용했다기보다는 강의때 배운 인터페이스 그대로 상태 패턴을 맞춰 넣은 느낌이에요. 기존 코드 베이스로 인터페이스를 추상화한게 아니라 기존 코드는 고려치 않고 인터페이스만 먼저 생각하고 작업하면서 안되는부분은 그때 그때 고치지 않았을까 싶어요. (인터페이스부터 생각할 수도 있지만 먼저 생각한 다음 기존 구현에 맞춰 재정의를 해야겠죠.)

그러다보니 인터페이스에 맞춰 개발이 되지 않고 개발에 맞춰 인터페이스가 끌려다닌 것 같습니다.
이런 얘기를 왜 했냐하면 상태패턴과 전략패턴의 가장 큰 차이는 다음 상태를 상태 자신이 정한다는 것이죠. 그러면 이 정해진 상태를 어떻게 적용시킬지에 대한 고민도 같이 들어가야 합니다. 근데 이부분이 빈약했던걸로 보여요. 그러다보니 딜러, 플레이어가 draw 후 상태를 변경하는 부분이 굉장히 복잡해 보입니다. (참고로 상태가 바껴야하는 핵심 시점은 카드를 새로 뽑아 점수가 바뀔 때가 될겁니다.)

그리고 질문과 위 인터페이스를 봤을 때 상태패턴을 통한 다형성을 어디까지 적용할 지에 대한 구분을 확실히 하지 못했 던 것 같아요. 이미 결과에 관한 다형성은 ResultType을 통해 구현이 끝난 상태입니다. 그렇기 때문에 결과에 관련된 내용은 ResultType에 있는게 더  응집도가 있어 보여요.
그런면에서 선택할 수 있는 방법이 몇가지 있을 것 같은데 ResultType을 통한 다형성 부분을 State로 옮기고 ResultType은 타입으로서 사용한다. Stat는 결과를 만드는 것 까지만 관여한다. 크게 이 두가지가 될 것 같아요. (구현상의 과정까지는 덜 고려해서 실제 쉽게 깔끔히 적용될지는 좀더 고민해봐야 할 것 같아요. 😋 )

인퍼테이스를 만든다는 것은 설계를 하는 거랍니다. 그렇기 때문에 설계를 구현에 맞추기보다는 설계에 맞춰 구현하도록 노력해보는게 좋습니다. 설계 후 구현에 맞춰 인터페이스가 바뀔 수는 있지만 이는 설계에 대한 변경이 돼야하지 당장의 문제 해결에 맞춰 인터페이스를 바꾸지 말아야합니다!


그리고 패턴을 적용하는게 꼭 좋다고는 생각안해요. 지금은 굉장히 적은 조건을 가지기 때문에 약간의 변경이 추가되는 거라면 조건문일 때가 분기에 대한 이해나 변경이 빠를 수도 있어요. 근데 지속적으로 변경 요청이 들어온다면 엄청난 분기의 조건문이 탄생하게 될겁니다. 🙄 그래서 초기상태라면 상황에 따라 조건문으로 유지하고 있다 필요해졌을 때 패턴을 적용하는것도 좋습니다.
유지하는게 좋다고 하긴 했지만 만약 `3번 연속으로 bust일 때는 원금을 돌려준다.` `세번 이상 블랙잭일 때는 10배의 금액을 준다` 같은 조건이 추가되면 어떨까요? 이럴 땐 상태 패턴으로 관리하는게 효율적일 겁니다.
이게 어려운 법인데 그래서 지금과 같은 요구사항에서는 어떤게 옳다는 정답은 없답니다. (개인적으로는 심플한걸 선호하기에 조건문으로 처리할겁니다. 😉 ) 대신 개발 경험이 많거나 도메인에 대한 이해도가 높다면 미래에 대해서 어느정도 예상이 가능해 그에 대한 대응을 할 수 도 있답니다.

2021-03-11 18:44 UTC, Hue9010 commented on src/main/java/blackjack/domain/participant/Player.java
>          return ResultType.getResultType(getScore() - dealer.getScore());
그래서 약간 무책임하게 얘기해보자면 😋 
State에 대해서는 강의 내용은 참고만 하고, 이번 블랙잭에서 어떤 역할을 할지를 고민한다음 어떤 인터페이스를 가질지 고민하고 설계한다음 적용해보세요.(알아서 해보라는 소리죠🙄 )
설계라고 어렵게 생각 할 것 없이 어디에 어떻게 적용할지정도 고민한다고 생각하면 됩니다.

위에서도 말씀드렸지만 개인적으로는 상태패턴보다는 조건문으로 처리했겠지만 이김에 패턴이란걸 한번 학습해보는 차원으로 적용해보는 것도 좋다고 봐요. 그래도 너무 막힌다 싶으면 과감하게 상태 패턴 없이 ResultType을 활용해주세요. 패턴이 중요한게 아니거든요!! 패턴은 어느 패턴이 있고 대략적인 형태와 특징만 아는 것 만으로 충분해요!! 😉

2021-03-11 18:44 UTC, Hue9010 commented on src/main/java/blackjack/domain/participant/Player.java
>          return ResultType.getResultType(getScore() - dealer.getScore());
이런 것도 있습니다. 😉 
[개발자 1년차 5년차 10년차의 코드](https://blog.daum.net/luckyman717/3210)

사실 학습에 목적을 두기 때문에 참고할만한 얘기는 아니지만 학습이 목적이 아니라면 꼭 무언가를 하기보다 심플하게 작업하는게 좋다고 생각해요. 하지만 학습이 목적이라면 어느게 더 낫다는 크게 의미 없을 수도 있어요. 상태패턴을 사용해보는게 목적이였으니 ResultType만 쓰는게 더 효율적이였을 것 같다가 의미 없어질 수도 있는거죠. 적용 자체만으로도 의미가 있고 적용 후 비교하는 것까지도 다 의미가 있어요.
여러모로 개인적인 의견이 크게 섞인 얘기들이였다보니까 다른 분은 상반된 얘기가 나올 수도 있는 사항이라 참고만 해주시는게 좋습니다!

약간 길게 적다 내용이 산만해졌는데 고민되는 부분은 언제든 질문주세요! (업무 시간에는 빠른 답변 못 드리는점 양해 부탁드려요. 😢)

2021-03-13 08:08 UTC, Sehwan-Jang commented on src/main/java/blackjack/domain/participant/Player.java
>          return ResultType.getResultType(getScore() - dealer.getScore());
자세하고 친절한 피드백 정말 감사합니다 휴!
남겨주신 피드백 몇번씩 읽어보면서 많이 배운것 같습니다.

일단 정말 정확하게 짚어주신게 상태패턴에 대한 강의를 듣고 '와 신기하다 나도 한번 적용해봐야겠다' 라는 생각으로 기존 
설계와 코드에 대한 고민 없이 제이슨이 사용했던 설계를 그대로 가져오고 거기에 맞춰 기존의 코드를 수정 한것 같습니다. 그렇기에

> 인퍼테이스를 만든다는 것은 설계를 하는 거랍니다. 그렇기 때문에 설계를 구현에 맞추기보다는 설계에 맞춰 구현하도록 노력해보는게 좋습니다. 설계 후 구현에 맞춰 인터페이스가 바뀔 수는 있지만 이는 설계에 대한 변경이 돼야하지 당장의 문제 해결에 맞춰 인터페이스를 바꾸지 말아야합니다!

라는 피드백을 곱씹으면서 생각해보게 된것 같아요.

결론적으로는 휴가 말씀하신것처럼 저도 if문을 사용해서 보다 심플하게 코드를 짜는 것이 좋을 것 같다는것에 동의합니다. 
또 아직 OOP에 대한 개념도 확실히 잡지 못한 상황에서 디자인패턴부터 학습하고 적용해보려고 하는 시도 또한 시기상조이지 않았나 하는 생각도 들고요.
하지만 이왕 여기까지 적용해본거 조금더 고민해서 더 개선해보자 하는 생각으로 피드백을 참고하여 리팩토링해봤습니다.
아직도 미흡한 점이 많겠지만 다시한번 잘 부탁드립니다!

2021-03-13 08:22 UTC, Sehwan-Jang commented
# [JDK] Null 체크

## 내용

**Validation 코드에서 null까지 체크하는 코드**

```java
if ( name.isEmpty() || !VALID_NAME_FORMAT.matcher(name).matches()
			 ||name == null ) {
    throw new IllegalArgumentException("이름은 한글, 영문 혹은 숫자로 1자 이상 입력해야합니다.");
}

-----------------------------------------------------------
if (name == null || name.isEmpty() || 
			!VALID_NAME_FORMAT.matcher(name).matches()) {
    throw new IllegalArgumentException("이름은 한글, 영문 혹은 숫자로 1자 이상 입력해야합니다.");
}
```

- 위의 코드는 Null포인터 에러가 발생하지만, 밑의 코드는 의도한 에러가 발생한다.
- 그 이유는 null 검증 코드로 가기도 전에 `name.isEmpty()` 에서 name을 사용하면서 null 포인터 에러가 발생하기 때문이다. 따라서 null을 체크하려면 해당 코드를 제일 앞으로 빼야한다.

## 링크

- 

# [JDK] Line Separator

## 내용

- 출력 코드 작성 시 흔히 (자바의 경우) `"\n"` 의 개행문자열을 사용해서 작성하는 경우가 많다. 하지만 위와 같은 개행 문자열은 OS 마다 다르다.
- 따라서 Java에서는 `System.lineSeparator();` 라는 개행 메소드를 제공한다.

## 링크

- 링크

# [JDK] checked vs unChecked

## 내용

- checked 보다는 unchecked 에러를 사용하자
    - 확인 오류는 OCP를 위반한다.
    - 에러처리를 하는 구문까지 계속 선언부에 예외를 정의해야 한다.
- 그럼에도 checked를 사용하려 한다면 이부분은 반드시 예외처리가 필요하다! 라는 부분에 적용할 것
    - ex. 결제과정 도중에 에러가 발생한 상황에서 이미 사용자가 결제를 마친 상황이라면 사용자가 지불한 돈은 반드시 환불되어야 할 것이다. 이부분은 checked 에러를 던지도록 작성할 수 있을 것.

> 클린코드 : 프로그래머들은 확인된(checked) 예외의 장단점을 놓고 논쟁을 벌여왔다.
하지만 안정적인 소프트웨어를 제작하는 요소로 반드시 필요하지 않다는 사실이 분명해졌다.

## 링크

- [https://velog.io/@kwj1270/클린-코드-오류-처리](https://velog.io/@kwj1270/%ED%81%B4%EB%A6%B0-%EC%BD%94%EB%93%9C-%EC%98%A4%EB%A5%98-%EC%B2%98%EB%A6%AC)

# [OOP] 상태 패턴

## 내용

- 상태라는 인터페이스를 구현하여 수많은 if-else 혹은 switch문을 별도의 클래스들로 분리하여 관리할 수 있도록 하는 디자인 패턴
- 전략 패턴과는 달리 상태 스스로 자신의 상태를 변경할 수 있다.
- 별로 복잡하지 않은 로직에 사용할 경우 오히려 설계만 더 복잡해질 수 있다.
    - 어떤 디자인 패턴이든 마찬가지지만 의도적으로 사용하려고 하지말고 기존의 설계를 구현하는 과정에서 필요성을 느꼈을때 사용을 고민해보는 습관을 기르자.

## 링크

- [https://www.notion.so/e73a302880094b8997611cb4930f3949](https://www.notion.so/e73a302880094b8997611cb4930f3949)
- [https://okky.kr/article/133477](https://okky.kr/article/133477)

2021-03-14 05:19 UTC, Hue9010 approved these changes
이전 pr에선 상태 패턴 적용에서 많이 고생하셨던 것 같은데 🤔 
이번엔 수월히 작업하신 것 같네요. 👍
잘해주셔서 간단한 내용만 남겼는데 그 외에도 궁금한건 언제든 질문주세요!

블랙잭 진행하느라 고생많으셨습니다! 남은 과정도 화이팅입니다!!

2021-03-14 05:19 UTC, Hue9010 commented on src/main/java/blackjack/domain/state/NotStarted.java
> +public class NotStarted implements State {
NotStarted보다는 InitState와 같이 초기, 최초 상태를 의미하는 네이밍을 가질 수 있을 것 같아요.

2021-03-14 05:19 UTC, Hue9010 commented on src/main/java/blackjack/domain/state/finished/Finished.java
> +    }
👍 
표준 예외를 사용할 때도 메시지를 추가할 수 있다는걸 챙겨보죠. 😉

2021-03-14 05:19 UTC, Hue9010 commented on src/main/java/blackjack/domain/state/finished/Finished.java
> +    }
Stay에서만 사용되는데 Stay로 옮기고 ResultType에 메시지를 보내서 matcher.apply를 실행시키게 할 수 있을 것 같아요.

2021-03-14 05:19 UTC, merged

2021-03-14 05:25 UTC, Hue9010 commented
checked 드린 의견은 일반적이진 않으니 이럴수도 있다는 점으로만 참고해주세요. 😉
특히 널리 퍼져있는 시각이 아니라면 면접과 같은 상황때 언급하는건 잘못하면 독이 될 수도 있어요. 예외 처리가 강제되어야 할 상황이 있었고 그걸 활용해본 경험이 있어 어땠는지 설명하면 좋겠지만 돈과 관련된 일이 아닌 이상 그렇게까지 할 상황을 만나긴 힘들겁니다. 
회원가입 실패 시 실패 알림을 사용자한테 주는게 개발적인 비용도 싸고 사용자도 이해하고 넘길 수 있죠 그렇기 때문에 꼭 강제할 필요성까진 없습니다.

그런 면에서 저도 직접 경험해보진 못해서 조심스럽게 생각하고 이런 견해도 있다는 것 정도로만 참고하시는게 좋을 것 같아요.