[2단계 - 블랙잭 구현] 우기(박병욱) 미션 제출합니다.
woowacourse/java-blackjack pull request #187
Opened 2021-03-11 09:54 UTC by jujubebat

안녕하세요 미립! 😀 2단계에서는 상태 패턴을 적용해봤습니다. 기존의 방식이 클래스 수도 적고 더 간단하다고 생각 하지만 변경에 유연한 코드를 작성해보고 싶어서 도전 해봤습니다. 부족한 부분이 너무 많을텐데 하나씩 지적해주시면 많이 배워가도록 하겠습니다! 추가적인 질문은 DM으로 드리겠습니다!!

2021-03-12 08:31 UTC, seok-2-o requested changes
유한 상태 머신을 잘 적용해주셨네요 👍 
추가로 배팅은 큰 구조 변화 없이 잘 적용해주셨네요 💯 
좋은 객체 지향 설계 일수록 변화에 둔감한 것 같아요 !

조금 더 중복을 제거 하면 좋을 것 같은 부분이 있어 코멘트 남겨 놓았어요.
확인 후 리펙토링 진해주세요.

2021-03-12 08:31 UTC, seok-2-o commented on src/main/java/blackjack/domain/state/Blackjack.java
> +        throw new IllegalArgumentException(BLACKJACK_DRAW_ERROR);
UnsupportedOperationExceptiond 조금 더 의미를 명확하게 할 수 있는 익셉션도 제공하고 있어요.

2021-03-12 08:31 UTC, seok-2-o commented on src/main/java/blackjack/domain/state/Bust.java
> +public class Bust extends State {
Finish State 를만들어면 어떤 장점이 있을까요?

2021-03-12 08:31 UTC, seok-2-o commented on src/main/java/blackjack/domain/state/Stay.java
> +    }
중복 제거 할 수 있는 방법이 없을지 고민해보면 좋을 것 같아요.

2021-03-12 10:13 UTC, jujubebat commented
# [OOP] 인터페이스 - 1
## 내용
- 이펙티브 자바를 읽으며 학습함
- 인터페이스를 사용해서 구현하면 변경에 유연한 프로그램을 만들 수 있다는 것을 배움
- 인터페이스를 사용하면 구현체를 손쉽게 바꿀 수 있음. (단 교체되는 구현체는 호환 되어야함)
## 링크
- [개인 기술 블로그 포스팅](http://byungwook.me/java/2021/03/12/이펙티브자바_아이템64.html)

2021-03-12 10:15 UTC, jujubebat commented
# [OOP] 인터페이스 - 1
## 내용
- 이펙티브 자바를 읽으며 학습함
- 상수 관리만을 위한 인터페이스는 안티 인터페이스라는 것을 배움
- 상수는 강하게 연관되는 클래스 또는 인터페이스 내부, Enum, 인스턴스화 되지 않은 유틸 클래스로  관리하는게 좋다는 것을 배움
- 인터페이스를 사용하면 구현체를 손쉽게 바꿀 수 있음. (단 교체되는 구현체는 호환 되어야함)
## 링크
- [개인 기술 블로그 포스팅](http://byungwook.me/java/2021/03/12/이펙티브자바_아이템22.html)

2021-03-12 10:22 UTC, jujubebat commented
# [Design Pattern] 상태패턴 - 3
## 내용
- 블랙잭 프로그램에 상태패턴을 적용해서 유한 상태 머신을 구현함
- 새로운 상태가 추가되더라도 상태를 사용하는 콘텍스트 코드에 영향을 주지 않도록 함
- 상태에 따른 동작을 구현한 코드가 각 상태 별로 구분되기 때문에 상태별 동작을 수정하기가 쉽다.
- 상태 패턴을 통해 유지보수가 더 용이해진 코드를 구현함

## 링크
- [객체 지향과 디자인 패턴](https://book.naver.com/bookdb/book_detail.nhn?bid=7255217)

2021-03-12 10:32 UTC, jujubebat commented on src/main/java/blackjack/controller/BlackjackController.java
> +        return new Players(players);
```java
private Players createPlayers() {
        List<String> names = InputView.getPlayerNames();
        List<Player> players = new LinkedList<>();
        for (String name : names) {
            Player player = new Player(name);
            Money money = new Money(InputView.getBetMoney(player));
            player.addMoney(money);
            players.add(player);
        }
        return new Players(players);
    }
```

2021-03-12 10:36 UTC, jujubebat commented on src/main/java/blackjack/domain/blackjackgame/BlackjackGame.java
> +        if (currentPlayers.size() == 0) {
BlackjackGame객체에 인스턴스 변수로 존재하던 currentPlayers를 Players 객체로 옮겨서 리팩토링 했습니다!

2021-03-12 10:47 UTC, jujubebat commented on src/main/java/blackjack/domain/blackjackgame/Money.java
> +        return new Money(value + money.getValue());
다음부턴 불변 객체를 구현할때 위와 같은 예외 상황도 생각해보겠습니다.
궁금한 점이 있는데 매개변수로 들어온 money 객체의 private 필드 value에 대해 위 코드와 같이 .으로 어떻게 접근이 허용되는지 궁금합니다!

2021-03-12 11:48 UTC, jujubebat commented on src/main/java/blackjack/domain/player/Participant.java
> +    protected State state;
private으로 선언한 다음 부모 클래스의 메서드를 통해서 접근하게 하면 되는데, 구현할 때는 생각하지 못했던 것 같습니다.
부모 클래스를 상속할지라도 부모, 자식 클래스간에 정보 은닉을 해줘서 서로 의존과 영향을 주고 받지 않도록 하는게 좋다고 판단하여 private으로 수정했습니다. 그리고 제가 구현한 코드에서는 Player만 Money를 사용하기 때문에 추상 클래스에 있던 Money를 Player로 이동 시켰습니다.

2021-03-12 12:25 UTC, jujubebat commented on src/main/java/blackjack/domain/state/Blackjack.java
> +        throw new IllegalArgumentException(BLACKJACK_DRAW_ERROR);
추가로 찾아보니 IllegalStateException라는 예외가 더 명확한 의미를 전달해줄 거 같아서 적용해봤습니다.

2021-03-12 12:39 UTC, jujubebat commented on src/main/java/blackjack/domain/state/Bust.java
> +public class Bust extends State {
아래와 같은 장점이 있다고 생각했습니다.
1. 상태를 좀 더 명확하게 표현할 수 있다.
2. 중복 코드를 제거할 수 있다. (예를들어 Finished를 상속한 Bust와 Blackjack이 Finished의 isFinished 구현체를 받아서 사용)

State를 상속하는 Finished와 Running이라는 클래스를 만들어 위 2가지 장점을 실천해봤습니다!

2021-03-13 05:12 UTC, jujubebat commented
두 번째 코드 리뷰 요청 드립니다 😀 1단계에서 컨트롤러에 있던 블랙잭 게임을 객체로 캡슐화하라고 조언 주셨을 때 마음에 크게 와닿지 않았습니다. 하지만 2단계에서 컨트롤러에 영향을 끼치지 않고 내부 구현을 상태 패턴으로 바꿔가는 과정에서 캡슐화의 이점을 느꼈습니다!

#### 추가적으로 한 리팩토링
- Deck에 Card를 캐싱하는 이너클래스를 만들어봄
- [링크](https://codingnuri.com/choose-method-names-carefully/)를 참고하여 객체나 값을 반환하는 메서드들의 이름을 명사 형태로 수정함

#### 느낀점과 질문
- 테스트 코드 메서드 크기가 큰 것 같은데, 제가 객체지향 설계를 잘못해서 그런건지 아님 무방한건지 궁금합니다.

2021-03-13 05:23 UTC, jujubebat commented
두 번째 코드 리뷰 요청 드립니다 😀 1단계에서 컨트롤러에 있던 블랙잭 게임을 객체로 캡슐화하라고 조언 주셨을 때 마음에 크게 와닿지 않았습니다. 하지만 2단계에서 컨트롤러에 영향을 끼치지 않고 내부 구현을 상태 패턴으로 바꿔가는 과정에서 캡슐화의 이점을 느꼈습니다! 감사합니다 ㅎㅎ

#### 추가적으로 한 리팩토링
- Deck에 Card를 캐싱하는 이너클래스를 만들어봄
- [링크](https://codingnuri.com/choose-method-names-carefully/)를 참고하여 객체나 값을 반환하는 메서드들의 이름을 명사 형태로 수정함

#### 질문
- 테스트 코드 메서드 크기가 큰 것 같은데, 제가 객체지향 설계를 잘못해서 그런건지 아님 무방한건지 궁금합니다.

2021-03-14 02:44 UTC, seok-2-o commented on src/main/java/blackjack/domain/blackjackgame/Money.java
> +        return new Money(value + money.getValue());
같은 클래스의 내부 변수에는 접속이 가능합니다!

2021-03-14 02:48 UTC, seok-2-o approved these changes
안녕하세요 우기. 피드백 빠르게 잘 반영해주셨네요 💯 
추상 클래스를 통해서 중복도 잘 제거 해주셨구요 👍 

테스트코드는 보통 프러덕션 코드보다 1.5~2배정도 많은 것 같아요
걱정 하지 않으셔도 될 것 같습니다.

이번 미션은 여기서 마무리하도록 하겠습니다 :)
우기와 함꼐한 시간이 너무 즐거웠네요.

다음 미션도 재밌게 진행하기를 바랍니다.

감사합니다.

2021-03-14 02:48 UTC, merged