[2단계 - 블랙잭 구현] 바다(조아라) 미션 제출합니다.
woowacourse/java-blackjack pull request #202
Opened 2021-03-12 14:41 UTC by xrabcde

안녕하세요 코니! 바다입니다 🌊
지난 1단계 미션에서 추가해주신 피드백과 2단계 베팅 로직을 구현해보았습니다.

2단계 베팅로직을 구현하며 한 가지 궁금한 점은 바로 __테스트코드__ 에 관한 것인데요!
블랙잭은 워낙 로직이 복잡한 게임이다보니 다양한 경우의 수가 나올 수 있는 것 같아요.
이 경우의 수들에 대해 테스트를 하는 것이 좋을 것 같은데, 그렇게 되면 또 테스트코드에 중복이 너무 심해지더라구요😭
테스트코드에서는 플레이어들에게 그 상황에 맞는 카드들을 배분한다고 설정하고 그에 맞는 로직으로 처리되는지를 확인해보고 싶은데 이 배분하는 과정을 어떻게 하면 깔끔하게 작성할 수 있을지 고민입니다!

이번 리뷰도 잘 부탁드립니다 ㅎㅎ 🙏
감사합니다!

2021-03-14 12:24 UTC, choihz requested changes
안녕하세요, 바다!

2단계를 깔끔하게 잘 구현해 주셨네요 👍 몇 가지 코멘트 달았는데 확인 부탁드리고, 궁금한 점은 언제든 DM 주세요~!

2021-03-14 12:24 UTC, choihz commented on src/main/java/blackjack/domain/participant/Participant.java
>      public abstract List<Card> showInitialCards();
이름이 조금 부적절한 것 같아요. 아무래도 `show`라고 하면 출력할 것 같은 느낌이 들죠?

2021-03-14 12:24 UTC, choihz commented on src/main/java/blackjack/domain/result/GameResult.java
>      }
이미 구한 `playersResult`와는 상관 없이 새로 수익을 계산하고 있네요. 결과와 수익을 한번에 구할 수 있지 않을까요?

2021-03-14 12:24 UTC, choihz commented on src/main/java/blackjack/domain/result/GameResult.java
>      }
테스트 코드에서만 사용되고 있네요 🤔

2021-03-14 12:24 UTC, choihz commented on src/main/java/blackjack/domain/result/Result.java
> +    }
이 메서드도 테스트해야 하지 않을까요?

2021-03-14 12:24 UTC, choihz commented on src/main/java/blackjack/domain/result/Result.java
>      }
조금 더 고민해 보면 `if` 문을 줄일 수 있을 것 같아요. 딜러와 플레이어 사이에 발생할 수 있는 케이스들을 표로 정리해 보고, 잘 묶어 보면 더 나은 방법이 보일지도 몰라요 😉

2021-03-14 12:30 UTC, choihz reviewed
> 테스트코드에서는 플레이어들에게 그 상황에 맞는 카드들을 배분한다고 설정하고 그에 맞는 로직으로 처리되는지를 확인해보고 싶은데 이 배분하는 과정을 어떻게 하면 깔끔하게 작성할 수 있을지 고민입니다!

생각이 다 다르겠지만, 그래도 보통 테스트 코드에서의 중복은 프로덕션 코드에서의 중복보다 관대하게 허용하는 것 같아요. 지금 바다의 테스트 코드에서도 크게 거슬린다고 느껴지는 부분도 없고요. 저는 테스트 데이터 생성을 위한 메서드를 만들 때도 있고, 이게 더 커지면 별도 클래스로 분리하기도 해요. 또는 JUnit5의 다양한 기능들을 이용할 수도 있겠죠?

2021-03-14 12:30 UTC, choihz commented on src/test/java/blackjack/domain/participant/ParticiapantTest.java
> +        player = new Player("bada", 10000);
이 테스트 클래스 이름에 오타가 있어요. 확인 부탁드려요!

2021-03-14 13:41 UTC, xrabcde commented
안녕하세요 코니! 바다입니다 🌊
꼼꼼한 피드백 감사드립니다 ㅎㅎ 
승부계산 로직을 좀 더 간단하게 리팩토링 해봤어요!
조언해주신대로 표를 그려 정리했더니 기존에 했던 딜러 중심 방식보다
__플레이어 중심으로 승부를 결정하는 방식__ 이 더 깔끔한 것 같아 이렇게 바꿔보았습니다!
그리고 승부계산에 대한 테스트코드는 JUnit5의 `@ParameterizedTest`로 다양한 경우를 테스트해보았는데 괜찮은가요 ㅎㅎ?

피드백을 반영할수록 점점 로직이 깔끔해지는 것 같아 기분이 좋네요 😊
감사합니다!

2021-03-14 13:43 UTC, xrabcde commented
안녕하세요 코니! 바다입니다 🌊
꼼꼼한 피드백 감사드립니다 ㅎㅎ 
승부계산 로직을 좀 더 간단하게 리팩토링 해봤어요!
조언해주신대로 표를 그려 정리했더니 기존에 했던 딜러 중심 방식보다
__플레이어 중심으로 승부를 결정하는 방식__ 이 더 깔끔한 것 같아 이렇게 바꿔보았습니다!
그리고 승부계산에 대한 테스트코드는 JUnit5의 `@ParameterizedTest`로 다양한 경우를 테스트해보았는데 괜찮은가요 ㅎㅎ?

피드백을 반영할수록 점점 로직이 깔끔해지는 것 같아 기분이 좋네요 😊
감사합니다!

2021-03-15 15:28 UTC, choihz approved these changes
안녕하세요, 바다! 🌊

마지막 피드백까지 잘 반영해 주셨네요. 블랙잭 미션은 여기서 마무리하도록 할게요. 정말 고생 많으셨고, 즐거운 배움의 시간이었길 바랍니다. 다음에 또 만나요! 👋

2021-03-15 15:28 UTC, choihz commented on src/test/java/blackjack/domain/participant/PlayerTest.java
> +    }
메서드가 이렇게 길어질 땐 중간에 적당히 줄바꿈을 넣어 주면 훨씬 읽기 좋답니다. 😉

2021-03-15 15:28 UTC, merged