[2단계 - 블랙잭 구현] 마크(김병화) 미션 제출합니다.
woowacourse/java-blackjack pull request #206
Opened 2021-03-12 17:12 UTC by binghe819

### 안녕하세요 지노!

<br>

## 느낀점

이번에 디자인패턴을 공부하게 되어서 상태패턴을 적용해보았고, 가능한 모든 것을 객체에게 메시지를 보내도록 했어요!

그리고 컴파일 타임때 `if-else`문을 통한 로직을 최대한 제거하였고, 런타임때 의존성에 따라서 로직이 실행되도록 변경해봤어요!

`if-else`를 최대한 줄이니 확실히 유지보수나 확장면에서는 편할 것 같단 생각이 들었어요 :)

하지만 객체의 수가 많아져서... 시간이 지난다면 코드를 보고 이해하는 것이 어렵진 않을까.. 싶더라구요!

정답이 없고, 트레이드 오프가 있는 분야인만큼 **적절히** 사용하는 것이 좋겠구나란 생각이 들었습니다 :)

<br>

## 궁금한 점

<br>

### 테스트 코드에서의 의존성
게임 결과와 베팅 결과에 대해서 테스트를 하기위해선 게이머, 플레이어등 여러 객체가 필요하더라구요!

그러다보니 **만약 한 객체의 멤버 필드나 메서드의 시그니처가 변경되면 의존하고있는 여러 테스트 코드도 다 바꿔줘야하는 것이 힘들다고 느꼈습니다ㅠ**

물론 가능한 시그니처나 멤버를 바꾸지 않는 것이 좋지만, 처음부터 완벽한 설계는 쉽지 않다고 느껴집니다.

( 그러다보니 테스트를 위한 생성자를 만들고 싶단 생각도 많이 들더라구요ㅠ )

**테스트 코드로 인해 결합도가 낮아진다는 느낌을 받는데요! 이 문제에 대한 지노의 의견을 듣고 싶어요!**

<br>

ps. 디자인 패턴 공부하다보니 PR을 늦게 날리네요ㅠ 1단계의 피드백중 하나였던 게임 결과 도출 로직도 리팩토링 진행했습니다! :)

2021-03-14 13:26 UTC, hyunssooo commented
안녕하세요 조엘! 

우테코에서 테스트를 위한 생성자는 괜찮다라고 가이드가 나간걸로 알고 있어요! 😀 
해당 부분에서는 조엘이 테스트를 위한 생성자를 만들어 보는 것도 좋은 경험이라고 생각합니다! (개인적으로 좋아하지는 않습니다🙄)

당연히 처음부터 완벽한 설계는 없습니다! 제일 중요한 것은 요구사항을 만족하는 것이 가장 중요합니다! 그리고 나서 설계는 언제든 변할 수 있다고 생각해요! 😀 우선 요구사항을 만족하고 리팩토링을 하는 경험도 중요하다고 생각합니다! 

개인적으로 디자인패턴은 필요하다면 공부하는 것이 더 좋다고 생각해요.  디자인 패턴을 공부하기 보다는 필요에 따라서 혹은 개발하다보니 자연스럽게 깨닫는 패턴도 분명히 존재한다고 생각해요!

2021-03-14 18:27 UTC, hyunssooo requested changes
안녕하세요 마크!
step2 매우 잘 진행해주셨어요! 👏
꼼꼼하게 테스트도 작성해주셨고 테스트에 사용하는 객체들도 중복제거 잘 해주셨어요! 👍
pr확인이 늦어져 죄송합니다.🙇‍♂️ 몇 가지 코멘트 남겼어요!

2021-03-14 18:27 UTC, hyunssooo commented on src/main/java/blackjack/domain/result/ResultType.java
> +        return ResultType.DRAW;
```suggestion
        if (this == WIN) {
            return LOSE;
        }
        if (this == LOSE) {
            return WIN;
        }
        return DRAW;
```

이렇게도 가능하겠네요 🙂

2021-03-14 18:27 UTC, hyunssooo commented on src/main/java/blackjack/domain/state/StateFactory.java
> +
이 클래스는 인스턴화를 막아주면 좋을 것 같아요! 
```suggestion
public class StateFactory {

    private StateFactory() { 
    }
```

`이펙티브 자바 item 4. 인스턴스화를 막으려거든 private 생성자를 사용하라.` 를 참고하면 좋을 것 같네요!

2021-03-14 18:27 UTC, hyunssooo commented on src/main/java/blackjack/domain/Money.java
> +    }
이 부분은 money가 아닌 double을 받는 것이 좋아보여요! 
money * money는 어색하지 않나요?

2021-03-14 18:27 UTC, hyunssooo commented on src/main/java/blackjack/domain/batting/Betting.java
> +            .sum();
이 부분을 위해 Money.plus() 를 구현해보는 것은 어떨까요?? 
```java
public Money plus(Money that) {
  return new Money (this.value + that.value);
}
```

2021-03-15 02:53 UTC, binghe819 commented on src/main/java/blackjack/domain/batting/BettingResult.java
> +    }
#### 저의 의도
`BettingResult`가 뷰로 보내지기 때문에 방어적 복사를 의도하여 작성한 코드입니다!! (불변)

`LinkedHashMap`을 사용한 이유는 `Player`들의 순서를 지키기 위함입니다!

<br>

#### 궁금한 점
생성자와 `getter`에서 모두 방어적 복사를 하였는데, 혹시 문제가 되는 코드일까요???

2021-03-15 04:02 UTC, binghe819 commented on src/main/java/blackjack/domain/Money.java
> +    }
매번 실수하네요ㅠ 피드백 감사합니다! 👍

2021-03-15 04:45 UTC, binghe819 commented
### 피드백 감사해요 지노!

<br>

피드백 남겨주신 부분들 모두 리팩토링 진행했습니다 :) 놓친 부분들이 많았는데 좋은 지적 감사합니다 👍

2021-03-15 09:14 UTC, binghe819 commented
# [OOP] 디자인패턴 - 상태패턴
## 내용
- 플레이어의 카드 내용을 바탕으로 상태 패턴을 적용함.
- `if-else`가 아닌 동일한 메시지 요청을 의존성에 따라 다르게 동작하도록 만들게 됨.
## 링크
- https://github.com/woowacourse/java-blackjack/pull/206/files#diff-129b9d84de33bade6e1b1b3f18ee237d60fb15eab5c55767271e62e71b8d0334
- [상태 패턴 정리 글](https://github.com/binghe819/TIL/blob/master/OOP/%EB%94%94%EC%9E%90%EC%9D%B8%ED%8C%A8%ED%84%B4/State%20Pattern.md)

<br>

2021-03-15 18:02 UTC, hyunssooo approved these changes
안녕하세요 **마크**! 
블랙잭 미션 진행한다고 수고 많으셨어요! 
남겨준 링크를 보고 마크가 학습한 부분도 볼 수 있어서 좋았습니다. 👏👏
미션 진행하면서 확인이 늦어서 죄송합니다🙇‍♂️

2021-03-15 18:03 UTC, merged