[2단계 - 블랙잭 구현] 김김(김기문) 미션 제출합니다.
woowacourse/java-blackjack pull request #214
Opened 2021-03-14 04:07 UTC by tributetothemoon

안녕하세요 코니! 2단계에서 다시 뵙습니다🙂. 상세한 리뷰를 남겨주셔서 정말 감사했습니다. 스스로 많은 시간을 회고해보기도 했고, 또한 배우고 얻어간 점도 많았습니다. 덕분에 정말 성장할 수 있었다고 느꼈습니다. 감사합니다.
1단계를 머지해주시면서 지적해주신 부분에 대해서는 Closed된 PR의 각각의 코멘트에 답을 달아 놓았습니다. [PR링크](https://github.com/woowacourse/java-blackjack/pull/136)를 확인해주시면 감사하겠습니다 :)

플레이어들의 베팅 금액과 관련해 생긴 주요한 클래스는 아무래도 `Money`와 `ProfitTable`입니다.
`Money`는 돈을 Wrapping하기 위한 클래스입니다. `ProfitTable`은 결과 유형에 따라 몇배의 수익률을 가져가는지를 가지고 있는 enum 클래스입니다. 그대로 승,패,무승부의 타입을 가진 ResultType 클래스에 배당률을 뜻하는 인스턴스 변수를 넣으면 더욱 로직이 간단해졌겠지만, 수익과 관련한 부분은 단순히 승패여부를 나타내는 타입과는 별개의 정보로 저장되고, 관련 로직이 실행되는 것이 맞지 않나라는 생각에, 조금 돌아가더라도 분리해보았습니다.

감사합니다 :)

2021-03-14 14:56 UTC, choihz requested changes
안녕하세요, 김김!

2단계도 잘 구현해 주셨네요. 몇 가지 코멘트 남겼는데 확인 부탁드리고, 궁금한 것이 있으시다면 언제든 DM 주세요~

2021-03-14 14:56 UTC, choihz commented on src/main/java/blackjack/domain/user/Names.java
> +    private List<Name> names;
```suggestion
    private final List<Name> names;
```

2021-03-14 14:56 UTC, choihz commented on src/main/java/blackjack/domain/ProfitTable.java
> +    }
> 그대로 승,패,무승부의 타입을 가진 `ResultType` 클래스에 배당률을 뜻하는 인스턴스 변수를 넣으면 더욱 로직이 간단해졌겠지만, 수익과 관련한 부분은 단순히 승패여부를 나타내는 타입과는 별개의 정보로 저장되고, 관련 로직이 실행되는 것이 맞지 않나라는 생각에, 조금 돌아가더라도 분리해보았습니다.

결과에 따라 배당률이 결정되는데 둘을 이렇게 분리하신 이유가 잘 와닿지는 않아요. 두 `enum`의 항목이 완전히 동일하고, 둘은 아주 강하게 결합되어 있기에 한쪽이 변경이 발생하면 다른 쪽에도 반드시 변경이 발생하게 됩니다. 하나의 `enum`을 사용했다면 이렇게 반복문을 돌 필요도 없을 테고요.
하지만 본인이 의도를 가지고 이렇게 작성하신 것이기 때문에 굳이 수정하실 필요는 없습니다. 장단점을 고민해 보시기만 해도 좋을 것 같아요.

2021-03-14 14:56 UTC, choihz commented on src/main/java/blackjack/domain/result/Results.java
> +    }
`winOrLose`라는 이름이 사용되고 있는데 `ResultType`에 `WIN`과 `LOSE`만 있는 것도 아니고, 그렇다고 하더라도 이렇게 드러낼 필요는 없어 보입니다.

2021-03-14 14:56 UTC, choihz commented on src/main/java/blackjack/domain/result/Results.java
> +        return (int) this.winOrLoseMap.values().stream().parallel()
`parallel()`을 사용하신 이유가 무엇인가요?

2021-03-14 14:56 UTC, choihz commented on src/test/java/blackjack/domain/card/CardsTest.java
>      }
👍

2021-03-14 14:56 UTC, choihz commented on src/main/java/blackjack/domain/user/User.java
> +    abstract boolean canContinue();
추상 클래스는 가장 아래에 배치해 주세요.

2021-03-14 14:56 UTC, choihz commented on src/main/java/blackjack/domain/MatchRule.java
> +    public static ResultType getMatchResult(Player player, Dealer dealer) {
이 메서드에 대한 테스트 코드를 작성한다면 `Players`의 `generateResultsMapAgainstDealer()`보다 더 작은 단위로 테스트할 수 있지 않을까요?

2021-03-15 05:28 UTC, tributetothemoon commented on src/main/java/blackjack/domain/user/Names.java
> +    private List<Name> names;
[커밋링크](https://github.com/tributetothemoon/java-blackjack/commit/367d82d69e12ce2ece42aa2d17aa305367c45553)😅 감사합니다...

2021-03-15 05:31 UTC, tributetothemoon commented on src/main/java/blackjack/domain/result/Results.java
> +        return (int) this.winOrLoseMap.values().stream().parallel()
병렬 스트림을 사용해도 결과에 영향을 미치지 않는 경우 성능을 위해 되도록 병렬 스트림을 사용하려고 습관을 들여보고 있습니다. 코멘트를 달아주시니 문득, 처리해야할 데이터의 양이 작아서 쓰레드 생성을 위한 오버헤드가 더 큰 것이 아닌가 라는 생각이 들기도 하네요😖

2021-03-15 05:31 UTC, tributetothemoon commented on src/test/java/blackjack/domain/card/CardsTest.java
>      }
🙌

2021-03-15 05:33 UTC, tributetothemoon commented on src/main/java/blackjack/domain/user/User.java
> +    abstract boolean canContinue();
그렇군요...! [반영](https://github.com/tributetothemoon/java-blackjack/commit/18592e6041c0c39fe3a732d41835be36823bfeec)하였습니다!

2021-03-15 07:47 UTC, tributetothemoon commented on src/main/java/blackjack/domain/MatchRule.java
> +    public static ResultType getMatchResult(Player player, Dealer dealer) {
[커밋](https://github.com/tributetothemoon/java-blackjack/commit/caaf7228baeaa4dc6b4e10368196e0a19c1980bd): 1단계를 머지하며 귀띔해주신 ParameterizedTest, MethodSource를 이용하여 모든 경우에 대한 테스트케이스를 작성해보았습니다.
모든 경우에 대해 테스트 메소드를 일일히 생성하는 것보다 MethodSource를 통해 일괄적으로 테스트하면서도, 어떠한 경우를 테스트하기 위함인지를 명시하기 위해 방법이 없을까 찾아보았더니 아니나 다를까 name attribute를 이용해 하는 방법이 있더군요! 테스트 메소드는 다소 코드 퀄리티에 신경을 쓰지 않는 경향이 있는데, 코니의 리뷰를 받고 나니 그러한 저의 태도가 바뀌어가는 것이 보입니다. 감사합니다 :)

2021-03-15 07:56 UTC, tributetothemoon commented on src/main/java/blackjack/domain/result/Results.java
> +    }
[커밋](https://github.com/tributetothemoon/java-blackjack/commit/c47fc617cc7c1d17e748b2de873e29362b9d4eb6): 클래스 명이 Results이다보니 되도록 result가 들어가지 않는 단어이면서 구체적으로 무엇을 나타내는지 명시하고 싶었습니다. 그렇지만 역시나  Draw도 있고, 2단계를 넘어가며 BlackJackWin도 생겨나다보니 저도 내내 찝찝한 면이 있었고 무엇보다 변수명에 타입명이 들어가는 것도 뭔가 아쉬움이 있었습니다.
몇번 고민해보다 결과를 result가 아닌 outcome, consequence... 등으로 바꾸는 것도 다소 억지스러운 면이 있는 것 같아 접두사 match를 사용해 winOrLostMap -> matchResults 로 바꾸어 보았습니다.

2021-03-15 08:41 UTC, tributetothemoon commented on src/main/java/blackjack/domain/ProfitTable.java
> +    }
설득력 높은 의견이라고 생각합니다. 제 의도가 있는 코드지만, 분명 단점도 있다는 것을 새겨두도록 하겠습니다👍

P. S. 말씀하신 반복문을 도는 문제는 분명한 성능상 단점이라고 생각해서, [해쉬맵을 이용해 시간 복잡도를 줄여보았습니다](https://github.com/tributetothemoon/java-blackjack/commit/5d2e23711458aaefabe49c7bde56c242437f920f) :)

2021-03-15 12:51 UTC, tributetothemoon commented on src/main/java/blackjack/domain/result/Results.java
> +        return (int) this.winOrLoseMap.values().stream().parallel()
현재 스트림에 관한 부분을 공부중이었는데, 적은 데이터에 대해서는 병렬 스트림이 성능상 이점이 없다는 점을 배웠습니다. [커밋](https://github.com/tributetothemoon/java-blackjack/commit/5d2e23711458aaefabe49c7bde56c242437f920f) 해쉬맵을 이용해 최적화하는 과정에서 parallel()은 삭제되었습니다!

2021-03-15 17:19 UTC, choihz approved these changes
안녕하세요, 김김!

피드백을 잘 반영해 주셨네요 👍 리뷰 코멘트에 본인의 생각을 자세히 남겨 주셔서 리뷰어로서 더 좋은 리뷰를 하는 데도 큰 도움이 되는 것 같아요. 감사합니다 🙇🏻‍♀️ 블랙잭 미션은 여기서 마무리하도록 할게요. 정말 고생 많으셨고, 다음에 또 만나요! 👋

2021-03-15 17:19 UTC, choihz commented on src/main/java/blackjack/domain/result/Results.java
> +    }
[자바 HashMap을 효과적으로 사용하는 방법](http://tech.javacafe.io/2018/12/03/HashMap/)

2021-03-15 17:19 UTC, choihz commented on src/main/java/blackjack/domain/result/Results.java
> +    }
이곳과 `Results`에서 `parallel()`이 여전히 사용되고 있네요. 저도 아직 병렬 스트림을 깊게 다뤄보지는 못해 많은 설명을 드리기 어렵지만, 코멘트에서 말씀해 주신 것처럼 보편적인 수준에선 사용했을 때의 이점이 크지 않은 것 같습니다. [When to use parallel streams](http://gee.cs.oswego.edu/dl/html/StreamParallelGuidance.html) 이런 글도 있네요! (그리고 병렬 스트림 같은 건 지금 단계에서 깊게 공부할 내용은 아닌 것 같습니다. 언제나 우선순위를 잘 따져 보아요~)

2021-03-15 17:20 UTC, merged

2021-03-24 17:12 UTC, tributetothemoon commented on src/main/java/blackjack/domain/result/Results.java
> +    }
[커밋 링크](https://github.com/tributetothemoon/java-blackjack/commit/be526fd17d59efcd8465bb9a596fa14f0d8b013f)
정말 마음에 들지 않았던 부분이었는데, 코멘트를 남겨주셔서 두고두고 기억해두었던지라 스터디를 하는 와중에 해결 방법을 배우게 된 순간 바로 적용해보았습니다. 🙌😆

2021-03-25 07:35 UTC, tributetothemoon commented
# 김김의 학습로그 - 블랙잭 2단계
-----------

# [Java] merge, compute를 통한 해쉬맵 초기화 - 2
## 내용
- 해쉬맵을 초기화하는 일반적인 패턴 중, key가 해쉬맵이 없을 때와 key와 value가 해쉬맵에 있을 때 수행하는 조건이 다를 때 분기문 없이 초기화할 수 있다. e.g., ) key에 상응하는 value들의 모든 총합을 구해야할 때 등
- Map을 선언하고, `map.merge(newKey, newValue, (key, value) -> ...some expression);` [예시링크](https://github.com/tributetothemoon/java-blackjack/commit/be526fd17d59efcd8465bb9a596fa14f0d8b013f)
## 링크
- [자바 HashMap을 효과적으로 사용하는 방법](http://tech.javacafe.io/2018/12/03/HashMap/)
- [A Guide to Java HashMap
](https://www.baeldung.com/java-hashmap)

------------
# [Java] 병렬 처리와 성능의 연관 관계
## 내용
- 결과에 지장을 주지 않는다면 병렬 스트림을 사용하는 것이 무조건 이득이라고 생각했다. 그러나 병렬 쓰레드를 생성하는 것은 상당한 오버헤드를 발생시키기에, 모든 경우에 효과적인 것은 아니다.
- 병렬 스트림이 활용하는 자료구조, 처리해야할 데이터의 수(유의미하게 많지 않다면 순차 스트림을 사용한다), 또한 순차 스트림보다 오히려 성능을 떨어트리는 일부 메소드(FindFirst, Limit 등)를 주의한다.
## 링
- [[모던 자바 인 액션 정리] 7장. 병렬 데이터 처리와 성능](https://willseungh0.tistory.com/25)