[1단계 - 블랙잭] 판다(김건웅) 미션 제출합니다.
woowacourse/java-blackjack pull request #222
Opened 2022-03-10 18:36 UTC by woong7

안녕하세요 닉, 
연료주입 연습미션 & 블랙잭 1단계 미션을 수행한 판다입니다! 

이번 미션을 진행하며 두 가지 고민을 하게 되었습니다. 

1. Participant 클래스에서 정적 팩토리 메소드를 통한 객체의 생성 방식을 Player와 Dealer의 두 가지로 나누어 처리하도록 하였는데요, 이 방식과 Participant 인터페이스를 상속하는 Dealer와 Player의 클래스를 각각 정의하는 방식 중 어느 것이 더 좋은 방식일지 결론을 내리기가 어려웠습니다. 

2. InputView와 ResultView를 인스턴스 변수로 사용할지, 클래스 변수로 사용할지에 대해 고민이 있었습니다. 
개인적인 결론으로는 ResultView는 필드를 갖지 않는 없는 유틸 클래스의 성격을 띄고 있는 것 같아 클래스 변수로 호출하도록 하였고, InputView는 객체마다 서로 다른 scanner를 가져야 한다고 생각해서 인스턴스 변수로 호출하도록 구현하였습니다. 
(입력 콘솔이 여러개가 되었을 때 사용이 끝난 scanner를 닫아 줄 필요성이 있다고 생각했는데 이 부분에 대한 확신이 없습니다...)

감사합니다. 이번 블랙잭 미션도 잘 부탁드리겠습니다!

2022-03-11 06:31 UTC, wbluke requested changes
안녕하세요 판다! 블랙잭 리뷰를 맡게 된 닉입니다 🙌 
코드가 상당히 깔끔하네요! 잘 봤습니다 ㅎㅎ
몇 가지 고민해볼 수 있는 포인트 남겼으니 참고해서 리팩토링 진행해 보셔요 🙂

2022-03-11 06:31 UTC, wbluke commented on src/main/java/blackjack/view/ResultView.java
> +public class ResultView {
> InputView와 ResultView를 인스턴스 변수로 사용할지, 클래스 변수로 사용할지에 대해 고민이 있었습니다.
개인적인 결론으로는 ResultView는 필드를 갖지 않는 없는 유틸 클래스의 성격을 띄고 있는 것 같아 클래스 변수로 호출하도록 하였고, InputView는 객체마다 서로 다른 scanner를 가져야 한다고 생각해서 인스턴스 변수로 호출하도록 구현하였습니다.
(입력 콘솔이 여러개가 되었을 때 사용이 끝난 scanner를 닫아 줄 필요성이 있다고 생각했는데 이 부분에 대한 확신이 없습니다...)

자바에서는 기본적으로 **static은 안티 패턴**입니다.
클래스가 정적이 되어버리는 순간 OOP의 장점을 포기하게 되거든요.

그리고 유틸 클래스의 성격인지 판단하는 기준을 필드의 유무로 말씀해주신 것 같은데요,
필드의 수가 중요하다기 보다는 해당 객체가 유틸의 성격을 갖고 있는지를 봐야 맞을 것 같아요.
제가 생각하는 유틸은, 도메인 로직과 관련 없이 모든 애플리케이션 영역에서 데이터/객체 가공 등의 역할을 담당하는 클래스에요. (ex. String 입력값을 LocalDate로 변환해주는 LocalDateUtils 클래스)
그래서 저는 유틸 클래스는 꼭 범용적으로 필요한 기능인지 체크하면서 만들고, 정적 클래스는 되도록 지양하고 있습니다.

저는 보통 레벨1의 콘솔 게임 기반 미션에서 InputView, ResultView를 정적 클래스로 만들었다고 해서 이를 변경하라고 피드백 드리지는 않지만(상대적 중요도가 낮다고 생각해서), 제가 구현한다면 인스턴스만 1개 만들어서 사용할 것 같아요 :)

2022-03-11 06:31 UTC, wbluke commented on src/main/java/blackjack/domain/BlackJack.java
> +	private final Map<Participant, Boolean> result;
Boolean의 경우 참/거짓의 정보밖에 담을 수 없기 때문에 확장에 상당히 제한적일 수 있는데요.
지금은 승/패 밖에 담을 정보가 없다고 하더라도 확장을 대비해서 각 참가자의 결과 정보를 담고 있는 객체를 만들어봐도 좋을 것 같아요 :)

2022-03-11 06:31 UTC, wbluke commented on src/main/java/blackjack/domain/card/CardDeck.java
> +	}
카드 덱 만든 것 좋네요 👍 
한 가지 고민해볼 점은, 만약 여러 게임이 동시다발적으로 진행되거나, 해당 카드 덱을 여러 개 사용하는 게임이 추가된다면 어떻게 될까요?
View 쪽에도 static 관련 피드백 남겼는데요, 참고해서 리팩토링 진행해 보아요 :)

2022-03-11 06:31 UTC, wbluke commented on src/main/java/blackjack/domain/card/CardDeck.java
> +		Collections.shuffle(deck);
pickCard()를 할때마다 셔플이 일어날 것 같은데요, 게임 시작할 때만 섞으면 되지 않을까요?
뽑을 때마다 섞다보니 불필요한 연산이 많이 일어날 것 같아요 :)

2022-03-11 06:31 UTC, wbluke commented on src/main/java/blackjack/domain/card/CardDeck.java
> +		return pickedCard;
이 행위를 보니, List 대신 Stack 자료구조를 사용해서 pop()을 해보는 건 어떨까요? :)

2022-03-11 06:31 UTC, wbluke commented on src/main/java/blackjack/domain/card/Cards.java
> +			.reduce(0, Integer::sum);
```suggestion
		int sum = cards.stream()
			.mapToInt(Card::getValue)
			.sum();
```

더 간단하게 가능합니다 :)

2022-03-11 06:31 UTC, wbluke commented on src/main/java/blackjack/domain/card/Cards.java
> +			.reduce(0, Integer::sum);
그리고 이런 가공 로직은 별도의 메서드로 추상화해보면 더 좋을 것 같아요 :)

2022-03-11 06:31 UTC, wbluke commented on src/main/java/blackjack/domain/card/Cards.java
> +			.anyMatch(x -> x.equals(true));
```suggestion
		return cards.stream()
                         .anyMatch(Card::isAce);
```
여기도요 :)

2022-03-11 06:31 UTC, wbluke commented on src/test/java/blackjack/domain/card/CardDeckTest.java
> +		assertThat(CardDeck.pickCard()).isInstanceOf(Card.class);
만약 CardDeck이 정적 클래스가 아니라 인스턴스를 생성가능하다면,
카드 묶음을 받아 덱을 만들게 할 수도 있을 것 같아요.
(물론 파라미터를 안받고 기본 48장 만들어주는 생성 메서드도 있을 수 있구요.)
그렇게 되면 테스트에서는 내가 테스트하고자 하는 카드를 넣고, 카드가 잘 뽑히는지를 볼 수 있을 것 같아요.
isInstanceOf() 체크도 좋지만 뽑고 나서 개수가 줄었는지를 체크하는 것도 좋겠죠 :)

2022-03-11 14:23 UTC, woong7 commented
안녕하세요 닉, 피드백을 반영해서 리팩토링 해보았습니다!

InputView, ResultView, CardDeck 모두 static을 최대한 제거하고 인스턴스를 생성해서 사용하는 쪽으로 가닥을 잡았고, 
게임의 결과 정보를 저장하는 Result 객체를 만들어서 사용하도록 하였습니다. 

자세한 피드백 감사드립니다!

2022-03-13 02:00 UTC, wbluke approved these changes
피드백 반영 잘 해주셨네요 👍 
추가 피드백 조금 더 남겼는데요, 2단계 진행하시면서 같이 고민해 주세요 🙂

2022-03-13 02:00 UTC, merged