[1단계 - 블랙잭] 열음(이주형) 미션 제출합니다.
woowacourse/java-blackjack pull request #223
Opened 2022-03-11 03:16 UTC by Juhyung990122

소니 안녕하세요! 저는 블랙잭 미션을 진행한 열음입니다!
만나뵙게 되어 반갑습니다ㅎㅎ
이번 미션을 진행하며 궁금했던 점은 다음과 같습니다.

---

  ###  컨트롤러 vs 도메인 분리
  현재 컨트롤러에서는 다음과 같은 역할을 합니다.
  - dealer와 players 관리
  - 반복문 돌면서 순차처리 (계산과 같은 로직은 도메인에 위치)
  - DTO 변환
  
  여기에서 dealer와 players 관리, 반복문도는 부분을 다른 도메인(Game)으로 분리해야할지 고민되었습니다.
  
  제 생각엔 컨트롤러를 줄이고자 하는 이유가 
  “비즈니스 로직을 컨트롤러에 위치시키지 않기 위해서” 라면  지금 상태도 괜찮지 않나 싶으면서도.. 
  도메인으로 분리하면 컨트롤러의 역할이 더 작아지고 dealer와 players가 객체내의 요소로 관리된다는 점이 좋을 것 같아서 좀 고민이 되네요.
  소니는 어떻게 생각하시나요?

---

부족한 점 말씀해주시면 열심히 고쳐보겠습니다!
시간내어 리뷰해주셔서 감사합니다😄  
잘부탁드려요~~

2022-03-12 13:21 UTC, sonypark requested changes
열음 안녕하세요.
코드를 살펴보고 실행해보니 블랙잭 규칙이 제대로 적용되지 않은 부분이 보이네요😭
리팩토링할 부분을 코멘트 하기 전에 블랙잭 규칙에 맞게 어플리케이션이 동작하는지를 먼저 확인할 필요가 있을 것 같아요.

- 현재 블랙잭을 판단하는 로직이 보이지 않습니다. 블랙잭은 무엇이고 어떻게 구현이 되어야 하나요? 플레이어가 블랙잭인 경우, 딜러가 블랙잭인 경우 모두 고려해주세요.
- 카드 숫자의 합이 21이 넘는 경우는 어떻게 되나요? 현재는 플레이어가 카드를 계속해서 받을 수 있네요. 이 부분도 확인 부탁드립니다.

블랙잭 게임 규칙을 다시 한 번 살펴보시고 정상적으로 실행되는걸 확인해주세요~
그 후 코멘트 남긴 부분도 적용해서 리뷰 요청 주시면 이어서 리뷰 드리겠습니다 🙏🏻

2022-03-12 13:21 UTC, sonypark commented on src/main/java/BlackJack/domain/User/Dealer.java
> +    }
오버라이딩한 메서느는 최하단에 놓는게 컨벤션 입니다 :)

2022-03-12 13:21 UTC, sonypark commented on src/main/java/BlackJack/domain/User/Dealer.java
> +    }
- 여기도 매직넘버가 많네요.
- compare라는 함수가 Dealer에 있는게 맞을까요?
- 승/패를 검증하는 로직이 블랙잭 규칙과 다른것 같은데 확인해보시겠어요? (블랙잭인 경우는 고려되었나요?)

2022-03-14 07:04 UTC, kang-hyungu commented on src/main/java/BlackJack/controller/BlackjackController.java
> +package BlackJack.controller;
패키지명에 대문자를 쓰지 않습니다.
스타일 가이드 참고해서 수정해보시기 바랍니다.

2022-03-14 07:06 UTC, kang-hyungu commented on src/main/java/BlackJack/controller/BlackjackController.java
> +public class BlackjackController {
단순한 콘솔 게임이라 복잡한 UI나 웹처리가 없는데 컨트롤러가 필요할까요?
컨트롤러 대신 적절한 이름으로 바꿔봅시다.

2022-03-14 07:06 UTC, kang-hyungu commented on src/main/java/BlackJack/controller/BlackjackController.java
> +//        Dealer dealer = new Dealer(CardFactory.drawTwoCards());
불필요한 주석은 제거하고 커밋하시기 바랍니다.

2022-03-14 07:06 UTC, kang-hyungu commented on src/main/java/BlackJack/controller/BlackjackController.java
> +        Game game = new Game(inputPlayerNames,new Dealer());
```suggestion
        Game game = new Game(inputPlayerNames, new Dealer());
```

2022-03-14 07:07 UTC, kang-hyungu commented on src/main/java/BlackJack/controller/BlackjackController.java
> +        game.handOutInitCard();
카드 초기화의 책임을 클라이언트에게 맡기는 이유가 무엇인가요?
게임 객체가 생성자에서 바로 초기화해도 되지 않나요?

2022-03-14 07:08 UTC, kang-hyungu commented on src/main/java/BlackJack/controller/BlackjackController.java
> +    private List<UserDto> convertToListDto(Dealer dealer, Players players) {
dto를 추가하면서 관련 처리를 위한 코드가 생겨나네요.
dto가 필요한 시스템 규모인가요?
그냥 도메인 객체에서 뷰에 필요한 값을 바로 반환해도 충분하지 않을까요?

2022-03-14 07:09 UTC, kang-hyungu commented on src/main/java/BlackJack/controller/BlackjackController.java
> +        while (dealer.checkPossibleAdd()) {
checkPossibleAdd 대신 메서드명을 실제 문장처럼 작성해주셔야 의미 전달도 잘 되고 코드가 읽혀서 협업할 때 도움이 됩니다.

2022-03-14 07:10 UTC, kang-hyungu commented on src/main/java/BlackJack/controller/BlackjackController.java
> +            dealer.addCard();
메서드명에 add가 붙으면 보통 파라미터로 적절한 객체를 전달해서 추가해야 할텐데 전달하는 값이 없군요.
메서드명이 적절한가요?
딜러가 카드를 뽑는것을 의미하는 적절한 동사를 찾아보시기 바랍니다.

2022-03-14 11:12 UTC, Juhyung990122 commented on src/main/java/BlackJack/domain/Card/CardFactory.java
> +
분배역할을 분리하면서 동시에 자료구조를 사용해보았습니다:)

2022-03-14 11:14 UTC, Juhyung990122 commented on src/main/java/BlackJack/controller/BlackjackController.java
> +        List<Player> players = joinGame(inputPlayerNames);
Game, Players 도메인 추가하였습니다:)
Players 도메인에서 이제 player의 생성을 담당하는데 이게 의도하신 Factory 클래스가 맞을까요?

2022-03-14 11:14 UTC, Juhyung990122 commented on src/main/java/BlackJack/domain/User/Dealer.java
> +    }
넵 감사합니다:)

2022-03-14 11:16 UTC, Juhyung990122 commented on src/main/java/BlackJack/domain/User/Dealer.java
> +    }
블랙잭인 경우를 고려하는 로직을 추가하였으며, 
compare함수는 judge로 바뀌어 Result 도메인으로 이동시켰습니다:) 
해당 매직넘버는 상수화 시켰습니다.

2022-03-14 11:17 UTC, Juhyung990122 commented on src/main/java/BlackJack/controller/BlackjackController.java
> +package BlackJack.controller;
수정했습니다 감사합니다!

2022-03-14 11:19 UTC, Juhyung990122 commented on src/main/java/BlackJack/controller/BlackjackController.java
> +        while (dealer.checkPossibleAdd()) {
감사합니다. 해당 메소드는 isPossibleToAdd로 변경하였습니다.

2022-03-14 11:28 UTC, Juhyung990122 commented on src/main/java/BlackJack/controller/BlackjackController.java
> +            dealer.addCard();
넵 해당 메소드는 requestCard 로 변경하였습니다:)

2022-03-14 12:18 UTC, Juhyung990122 commented on src/main/java/BlackJack/controller/BlackjackController.java
> +    private List<UserDto> convertToListDto(Dealer dealer, Players players) {
현재로써 dto가 필요한 정도의 시스템 규모는 아닌듯 하여 dto를 삭제하였습니다!
구구는 DTO 사용여부를 결정할때, 시스템 규모외에 어떤 것을 기준으로 결정하시나요?

2022-03-14 12:41 UTC, Juhyung990122 commented
안녕하세요 소니!
소니와 구구가 남겨주신 코멘트들을 기반으로 리팩토링을 진행해보았습니다.
크게는 다음과 같이 정리해볼 수 있을 것 같아요.

- 카드 생성 로직 수정
- Game 도메인 추가 및 로직 이동
- 블랙잭 판정 로직 추가
- 결과 출력 로직 변경
- DTO 삭제

블랙잭 미션 너무 어렵네요ㅜ 그래도 열심히 해보았습니다!
이번 리뷰도 잘부탁드려요ㅎㅎ
시간내어 리뷰해주셔서 감사합니다:)

2022-03-15 11:13 UTC, sonypark requested changes
열음 안녕하세요.
블랙잭 미션이 조금 까다롭죠?🥲
도메인 규칙도 이해해야 하고 로직도 로또보다 더 까다로워서 구현하기 힘든 부분이 있을거에요.
잘 구현해주신 부분도 있는데 아쉬운 부분도 있어 코멘트 남겼습니다. 확인 부탁드려요!

**요청 사항**
- 블랙잭 게임 규칙을 다시 한 번 읽어보고 구현해주세요.
- 어플리케이션 실행 후 규칙대로 동작하는지 확인해주세요.
- 블랙잭 게임에서 사용하는 도메인 이름을 사용해주세요.

**수정할 사항**
카드 숫자의 합이 21을 넘어도 계속 받을 수 있네요🧐
<img width="325" alt="image" src="https://user-images.githubusercontent.com/34808501/158357211-8c455fe4-6451-46dc-a144-720b2204cdc5.png">

2022-03-15 11:13 UTC, sonypark commented on src/main/java/blackJack/domain/User/User.java
> +    }
User가 Card에 직접적으로 의존해서 카드를 가져오고 있네요.
`user.addCard(card)` 형태가 되어야 하지 않을까요?

2022-03-15 11:13 UTC, sonypark commented on src/main/java/blackJack/domain/User/User.java
> +    }
이 메서드는 카드를 초기화하는 메서드인가요...?

2022-03-15 11:13 UTC, sonypark commented on src/main/java/BlackJack/controller/Blackjack.java
> +    }
메서드 이름과 내용이 일치할까요?

2022-03-15 11:13 UTC, sonypark commented on src/main/java/blackJack/domain/Game.java
> +    }
Score를 계산하는 클래스에게 역할을 위임하면 어떨까요?

2022-03-15 11:14 UTC, sonypark commented on src/main/java/blackJack/domain/Game.java
> +
이 클래스는 꼭 필요한걸까요?

2022-03-15 12:16 UTC, sonypark approved these changes
리뷰 반영은 2단계에 해주세요~ 1단계는 머지하겠습니다 :)

2022-03-15 12:17 UTC, merged

2022-03-16 08:07 UTC, Juhyung990122 commented on src/main/java/blackJack/domain/User/User.java
> +    }
딜러와 플레이어의 카드를 초기화하는 메서드입니다..! 처음 두장 받는건데 메소드명을 바꿔봐야겠네요

2022-03-16 08:13 UTC, Juhyung990122 commented on src/main/java/blackJack/domain/User/User.java
> +    }
딜러기준으로는 맞을 것 같은데, 플레이어 기준으로는 처음 받은 카드인지 확인하는 조건이 추가되어야 할 것 같네요!

2022-03-16 08:29 UTC, Juhyung990122 commented on src/main/java/blackJack/domain/User/User.java
> +    }
처음 받은 두개의 카드 합이 21인 경우 블랙잭인데, 이 메소드가 호출되는 시점이 카드 추가 전(처음 카드만 받았을때) 이므로 합이 21인것만 테크해주면 블랙잭이 될 것 같습니다👀

2022-03-16 09:00 UTC, Juhyung990122 commented on src/main/java/blackJack/domain/Card/Number.java
> +public enum Number {
네 좋습니다! 
- denomination 은 [다음 링크](https://ko.wikipedia.org/wiki/%ED%94%8C%EB%A0%88%EC%9E%89_%EC%B9%B4%EB%93%9C)에서 알게되었습니다!
- Suit와 Denomination으로 변경하려 하는데 어떠신가요?

2022-03-16 10:03 UTC, Juhyung990122 commented on src/main/java/BlackJack/controller/Blackjack.java
> +    }
아니요! 수정했습니다~!

2022-03-16 10:06 UTC, Juhyung990122 commented on src/main/java/blackJack/domain/Card/Cards.java
> +                .count();
좋아요! 수정했습니다~

2022-03-17 00:08 UTC, Juhyung990122 commented on src/main/java/blackJack/domain/User/User.java
> +    }
아뇨! 카드 두장 확인 로직 추가했습니다~!

2022-03-17 11:50 UTC, Juhyung990122 commented on src/main/java/blackJack/domain/Game.java
> +    }
네! 각각 playerScore와 DealerScore로 위임했습니다:)

2022-03-17 11:59 UTC, Juhyung990122 commented on src/main/java/blackJack/domain/Card/Cards.java
> +}
음.. 제안해주신 방법하고 지금하고 있는 로직하고 차이점을 모르겠어요.

지금은 
calculateScore에서 에이스를 1로 가정하고 총합을 계산한 후에
addAceScore에서 에이스 갯수만큼 for문을 돌면서
calculateAceScore로 ace 하나를 11로 쳤을때 21을 넘지 않는지 체크 후 
21을 넘지 않으면 10점을 더한다

는 로직인데.. 이러면 총합을 구한 뒤 Ace에 따라 10점을 추가하는 것 아닌가요?

2022-03-17 12:01 UTC, Juhyung990122 commented on src/main/java/BlackJack/controller/Blackjack.java
> +
Result에 플레이어가 블랙잭임을 판단하는 로직 추가했습니다!

2022-03-18 01:09 UTC, Juhyung990122 commented on src/main/java/blackJack/domain/User/User.java
> +    }
넵 바깥에서 추가가능여부를 보고, 카드까지 뽑아서 user에 넘겨주는 방식으로 수정했습니다!

```
        while (player.isPossibleToAdd() && InputView.askOneMoreCard(player)) {
            player.requestCard(CARD_CACHE.poll());
```

2022-03-18 01:19 UTC, Juhyung990122 commented on src/main/java/blackJack/domain/Game.java
> +
Blackjack 클래스가 있긴한데 
```
 private final Players players;
    private final Dealer dealer;
    private final Cards cards;
    private PlayerScore playerScore = new PlayerScore();
    private DealerScore dealerScore = new DealerScore();
```
이 요소들을 클래스 내의 메소드에서 사용하기 위해선 전역변수로 선언해야 합니다.
하지만 전역변수로 두었을때 동시성이슈 관련한 리뷰를 받은적이 있어서 분리했습니다!
근데 항상 동시성에 관련해서 좀 헷갈리는게

![IMG_B9899673598C-1](https://user-images.githubusercontent.com/43205258/158919040-e39c4211-cd37-4b9b-af2a-1f92a94b170a.jpeg)

어플리케이션에서 new 로 객체를 생성하고 run을 할때 
- 위처럼 유저별로 객체가 따로 생성되는건지, 
- 아래처럼  new로 생성되는 객체까지는 유저사이에서 공유되어서 
유저간 동시성이 없으려면 game처럼 따로 객체를 생성해줘야하는건지 

궁금합니다! 소니는 어떻게 생각하시나요?

2022-03-18 09:35 UTC, Juhyung990122 commented on src/main/java/blackJack/domain/Game.java
> +
코멘트로 질문드렸다가 좀더 생각해보니 해결법을 알겠어서 삭제합니다!
Game도메인은 삭제했으며 그 안의 로직은 Blackjack으로 옮겼습니다:)