[1단계 - 블랙잭] 알린(장원영) 미션 제출합니다.
woowacourse/java-blackjack pull request #232
Opened 2022-03-11 07:02 UTC by OzRagwort

안녕하세요 제이! 알린이라고 합니다.

블랙잭 미션을 하면서 상속을 최대한 잘 적용해보려 노력했는데 상속에 대해 잘 이해하지 못해서 특히 어려웠던 것 같습니다.

이번 미션 잘 부탁드립니다! 😃

2022-03-11 09:14 UTC, OzRagwort commented on src/test/java/blackjack/domain/AbstractGamerTest.java
> +public class AbstractGamerTest {
제가 골격 구현으로 구조를 변경하면서 추상 클래스(`Gamer`) -> 인터페이스(`Gamer`)와 `Gamer`를 상속받은 추상 클래스(`AbstractGamer`)로 구조가 수정되었습니다. 그리고 `AbstractGamer`를 상속받은 `Dealer`와 `Player`가 있습니다.

그렇다면 이 클래스들에 대한 테스트를 할 때 `AbstractGamer`, `Dealer`, `Player` 클래스 모두 모든 메서드 테스트를 하는게 좋을까요?

아니면 `AbstractGamer`만 모두 테스트하고 `Dealer`와 `Player`는 @Override한 메서드가 있다면 테스트해도 될까요?

2022-03-12 15:34 UTC, jjj0611 requested changes
안녕하세요 알린! 리뷰어 제이입니다.

블랙잭이 고민해야할 부분들이 참 많은데 구현하느라 고생하셨어요!
이번 주제에 맞게 고민을 많이 해보신 것 같네요 :)

고민할만한 부분들 & 질문 주신 내용 관련하여서는 코멘트 전체적으로 확인해주세요.
그리고 지금 도메인 패키지가 전혀 정리가 안되어 있는 것 같은데,
패키지 구조도 한 번 잡아주세요
코드를 읽는데 많은 도움이 되고, 알린이 생각한 도메인 구조를 이해하는데도 많은 도움이 된답니다 :)

코멘트 보시고 반영 부탁드려요!

2022-03-12 15:34 UTC, jjj0611 commented on src/main/java/blackjack/domain/AbstractGamer.java
> +    public static final int LOSE = -1;
public이 아닌 상태로 구현할 수 없을까요?
WIN, DRAW, LOSE에 대한 코드 값 없이 구현할 수는 없나요?

2022-03-12 15:34 UTC, jjj0611 commented on src/main/java/blackjack/domain/Gamer.java
> +    boolean isBust();
blackjack에서 사용하는 실제 용어를 잘 사용해주셨네요.

2022-03-12 15:34 UTC, jjj0611 commented on src/main/java/blackjack/domain/Gamers.java
> +    public Gamers(List<Gamer> gamers) {
new Gamers(null); 을 호출하면 어떻게 되나요?

2022-03-12 15:34 UTC, jjj0611 commented on src/main/java/blackjack/controller/BlackjackController.java
> +        Gamers players = createPlayers(names, deck);
중복된 이름이거나 10명이 넘어서 플에이어 생성에 실패하면, 게임이 다시 진행되지는 않네요.

2022-03-12 15:34 UTC, jjj0611 commented on src/main/java/blackjack/controller/BlackjackController.java
> +                && hitOrStayAnswer.equals(HIT_ANSWER);
y나 n이 아닌 입력이 들어오면 게임이 바로 에러로 종료 되네요!

2022-03-12 15:34 UTC, jjj0611 commented on src/test/java/blackjack/domain/FixDeck.java
> +public class FixDeck implements Deck {
interface를 활용해서 테스트를 쉽게 해주셨네요!
그런데 FixDeck이라는 것을 보고는 어떤 덱인지 알기가 쉽지 않은 것 같아요.
결국에는 안 쪽에서 어떤 상태인지를 들어가봐야 할 것 같네요.

2022-03-12 15:34 UTC, jjj0611 commented on src/main/java/blackjack/domain/Card.java
> +    }
매번 재생성 할 필요가 있을까요?

2022-03-12 15:34 UTC, jjj0611 commented on src/main/java/blackjack/domain/Gamer.java
> +    int compareWinning(Gamer o);
compareWinning이라는 이름으로 int를 사용하고 있는데,
dealer 구현체냐, player 구현체냐에 따라서 내용이 바뀌어야 하는 점이 혼란스러울 수 있을 것 같아요.
판단 주체를 좀 더 명시적으로 변경해보면 어떨까요?

2022-03-12 15:34 UTC, jjj0611 commented on src/main/java/blackjack/domain/Player.java
> +public class Player extends AbstractGamer {
처음에 그냥 클래스 이름만 봤을 때는 Player가 상위 인지, Gamer 상위인지 파악하기가 쉽지 않은 것 같아요.
Dealer는 Gamer이긴 하면서 Player는 아닌거라는 내용으로 작성해주신 것 같은데,
Gamer와 Player에 대한 네이밍이 저는 살짝 혼동이 있는 것 같아요.
알린은 어떻게 생각하시나요?

2022-03-12 15:34 UTC, jjj0611 commented on src/main/java/blackjack/domain/Cards.java
> +public class Cards {
이 카드가 이름만 보고는 Card들을 모아놓은 친구인지,
플레이어의 손에 들려 있는 Card인지 알기가 어려운 것 같아요.
좀 더 명시적으로 변경해볼 수 있을까요?

2022-03-12 15:34 UTC, jjj0611 commented on src/main/java/blackjack/domain/Dealer.java
> +    }
이 부분은 어떤 의미로 추가된걸까요?

2022-03-12 15:34 UTC, jjj0611 commented on src/main/java/blackjack/domain/Player.java
> +    }
이게 추가된 건 어떤 의미일까요?

2022-03-12 15:34 UTC, jjj0611 commented on src/main/java/blackjack/domain/RandomDeck.java
> +    private static List<Card> cards;
static 변수로 생성을 해두신 이유가 있을까요?

2022-03-12 15:34 UTC, jjj0611 commented on src/main/java/blackjack/domain/AbstractGamer.java
> +public abstract class AbstractGamer implements Gamer {
> 그렇다면 이 클래스들에 대한 테스트를 할 때 AbstractGamer, Dealer, Player 클래스 모두 모든 메서드 테스트를 하는게 좋을까요?
아니면 AbstractGamer만 모두 테스트하고 Dealer와 Player는 @OverRide한 메서드가 있다면 테스트해도 될까요?

AbstractGamer로 뽑은 이유가 뭘까요? 그 이유를 고민해보면 어떤 부분을 테스트해야할지 감이 좀 잡힐 것 같아요! :)

2022-03-13 21:35 UTC, OzRagwort commented on src/main/java/blackjack/controller/BlackjackController.java
> +    }
[블랙잭 규칙](https://namu.wiki/w/%EB%B8%94%EB%9E%99%EC%9E%AD(%EC%B9%B4%EB%93%9C%EA%B2%8C%EC%9E%84))에서 딜러는 16이하인 경우 무조건 카드를 받는다고 했기 때문에 `dealer.isValidRange()`함수로 16이하인 경우 계속 받도록 했습니다.

예를들어 모든 플레이어가 bust가 되면 더 이상 hit할 필요없이 딜러의 승리가 되지만, 그런 경우에도 16을 초과할 때까지 hit하도록 했습니다.

어차피 승무패를 판별할 때 플레이어가 bust면 무조건 딜러가 승리하기 때문에 상관없다고 생각했습니다.

2022-03-13 21:37 UTC, OzRagwort commented on src/main/java/blackjack/domain/Gamer.java
> +    boolean isBLACKJACK();
아닌 것 같습니다! 네이밍 컨벤션 수정했습니다.. 너무 당연한 것인데 민망하네요 ... 😢

2022-03-13 21:40 UTC, OzRagwort commented on src/main/java/blackjack/domain/AbstractGamer.java
> +    }
제가 블랙잭이 되는 조건을 AK, AQ, AJ만 블랙잭이라고 이해하고 작성했는데 그게 아니라 처음받은 2장의 카드의 합이 21이면 블랙잭이었더라구요

조건에 맞게 조금 더 이해하기 쉽도록 로직을 수정했습니다. [30db1f8](https://github.com/woowacourse/java-blackjack/pull/232/commits/30db1f882f6f130c0fbb01a72b3edf9c2932d52b)

2022-03-13 21:46 UTC, OzRagwort commented on src/main/java/blackjack/domain/AbstractGamer.java
> +    public static final int LOSE = -1;
수정하면서 WIN, DRAW, LOSE를 사용하던 `compareWinning()`의 역할을 Outcome 열거형 클래스에서 하도록 수정하면서 WIN, DRAW, LOSE를 삭제했습니다.

MAX_SCORE는 Panticipant에서 `@Override`한 메서드에서 사용했는데, 이 메서드가 `@Override`할 필요가 없었습니다.

그래서 public일 필요가 없어지면서 private로 수정했습니다. [3776173](https://github.com/woowacourse/java-blackjack/pull/232/commits/37761735b8413bb40f814070fd5a897b2870c64c)

2022-03-13 21:49 UTC, OzRagwort commented on src/main/java/blackjack/domain/Gamers.java
> +    public Gamers(List<Gamer> gamers) {
기존 코드에서는 에러가 발생합니다.

null을 확인하는 로직을 추가하면서 `isEmpty()`확인도 추가했습니다. (최소 인원 1명이어야 함)

커밋을 하면서 중간에 rebase를 잘못하면서 커밋이 합쳐져서 이 수정 부분이 다른 커밋에 합쳐져있네요.. [b644487](https://github.com/woowacourse/java-blackjack/pull/232/commits/b64448700dd5bb94e6369b581cd26acc9126c9a6)

2022-03-13 21:53 UTC, OzRagwort commented on src/main/java/blackjack/controller/BlackjackController.java
> +        Gamers players = createPlayers(names, deck);
이름이 null, 공백("", " ")이거나 다른 이름과 중복, 입력한 이름의 수가 1~8이 아닌 경우 등 입력을 잘못하면 이름을 입력받는 부분부터 다시 반복하도록 수정했습니다. [4264ed9](https://github.com/woowacourse/java-blackjack/pull/232/commits/4264ed98b815b6875de6432b07ddf7d492a6e7a1)

2022-03-13 21:55 UTC, OzRagwort commented on src/main/java/blackjack/controller/BlackjackController.java
> +                && hitOrStayAnswer.equals(HIT_ANSWER);
[4264ed9](https://github.com/woowacourse/java-blackjack/pull/232/commits/4264ed98b815b6875de6432b07ddf7d492a6e7a1)

이 부분도 y, Y, n, N외 다른 문자열이 입력되면 재입력받도록 수정했습니다.

y와 n은 HitOrStayAnswer 열거형 클래스를 만들어 비교 할 수 있도록 했습니다.

y, n이 아닌 다른 문자열로 수정되거나 새로운 문자열이 추가될 경우 수정이 더 쉬울 것 같았기 때문입니다.

2022-03-13 21:57 UTC, OzRagwort commented on src/test/java/blackjack/domain/FixDeck.java
> +public class FixDeck implements Deck {
구현할 때에는 제가 구현했으니 값을 알고있어서 그부분을 신경쓰지 못했습니다. 

[cdea36b](https://github.com/woowacourse/java-blackjack/pull/232/commits/cdea36b31a70e59d3d5ff451158c0af830a7b428)에서 FixDeck보다 10 스페이드의 카드만을 반환한다는 것을 더 이해하기 쉽도록 이름을 JustTenSpadeDeck으로 수정했습니다.

2022-03-13 21:59 UTC, OzRagwort commented on src/main/java/blackjack/domain/Card.java
> +    }
이번 미션에서는 게임을 단 한번 하기 때문에 어차피 한 번만 만들어질 것이라고 생각해서 캐싱하지 않았습니다.

하지만 게임이 여러번 실행될 수도 있다고 생각하면 캐싱을 해서 카드를 재사용하는것도 좋을 것 같았습니다.

[306474e](https://github.com/woowacourse/java-blackjack/pull/232/commits/306474e86325f2aa246a86bfb8b03b4c0d2136b8)에서 이부분을 캐싱하여 재사용할 수 있도록 수정했습니다!

2022-03-13 22:03 UTC, OzRagwort commented on src/main/java/blackjack/domain/Gamer.java
> +    int compareWinning(Gamer o);
이 부분을 더 명시적으로 하기위해 고민하던중 딜러와 참가자에 따라 로직도 다르고 이걸 판단해서 int 타입으로 반환하면 결국 다른곳에서 다시 확인해야하니 무언가 잘못된 것 같다고 생각했습니다. 

그래서 Dealer와 Participant가 아닌 승무패 정보를 가지고있는 Outcome의 `match()`에서 두 Player를 받아서 비교하도록 수정했습니다.

2022-03-13 22:06 UTC, OzRagwort commented on src/main/java/blackjack/domain/Player.java
> +public class Player extends AbstractGamer {
기존의 Dealer, Player, Gamer를 보면 조금 헷갈릴 수도 있을 것 같습니다. 특히 `Dealer는 Gamer이긴 하면서 Player는 아닌거라는 내용으로 작성해주신 것 같은데,`를 보니 이해가 되었습니다.

조금 더 명확하게 구분할 수 있도록 Player를 인터페이스로 만들고 Player를 상속받는 Dealer와 Participant 구현 클래스를 만들었습니다.

클래스 명 수정된 점
- 인터페이스 : `Gamer` -> `Player`
- 추상 클래스 : `AbstractGamer` -> `AbstractPlayer`
- 구현 클래스 : `Dealer` -> `Dealer`, `Player` -> `Participant`

2022-03-13 22:08 UTC, OzRagwort commented on src/main/java/blackjack/domain/Cards.java
> +public class Cards {
이 부분도 무의식적으로 Card를 모아놨으니 Cards다 라고 만든것 같습니다.

Cards로 하면 `RandomDeck`의 `List<Card>`도 Cards라고 볼 수도 있는건가? 와 같이 생각하니 더 이해가 잘 되었습니다.

조금 더 명확하게 플레이어가 가지고 있는 카드뭉치라는 것을 알려주기 위해 `Cards`를 `PlayerCards`로 이름을 수정했습니다. [9cf095e](https://github.com/woowacourse/java-blackjack/pull/232/commits/9cf095e96ec7137b669a76142548ccca35d62b62)

2022-03-13 22:10 UTC, OzRagwort commented on src/main/java/blackjack/domain/Dealer.java
> +    }
equals, hashCode, toString을 만드는 것이 익숙하지 않아서 무의식적으로 equals, hashCode, toString를 만들고 보니 의미없이 추가된 것 같습니다. 

super.XXX()로 추상클래스에서 정의된 메서드가 호출되어 재정의가 의미없다고 봐도 될 것 같습니다

2022-03-13 22:11 UTC, OzRagwort commented on src/main/java/blackjack/domain/RandomDeck.java
> +    private static List<Card> cards;
처음 RandomDeck의 코드를 작성할 때는 pick함수를 static으로 작성하면서 `List<Card>`도 static으로 작성했던 것 같습니다. 

이후 수정하면서 신경 쓰지 못한 것 같습니다. 

지금은 컨트롤러에서 게임이 시작하면 new RandomDeck()로 만든 Deck을 계속 사용하기 때문에 static이 있을 이유가 없습니다 [80904ed](https://github.com/woowacourse/java-blackjack/pull/232/commits/80904ed63836754a69a104f303f4f12b9346e405)

2022-03-13 22:14 UTC, OzRagwort commented on src/main/java/blackjack/domain/AbstractGamer.java
> +public abstract class AbstractGamer implements Gamer {
`AbstractPlayer`로 뽑은 이유는 딜러와 게임 참가자 객체의 중복되는 코드를 미리 정의해서 코드 중복을 방지하기 위함이었습니다.

구현 클래스(`Dealer`, `Participant`)에서 공통되는 부분은 추상 클래스에서 정의가 되어있는데 그러면 구현 클래스에서 재정의하지 않은 메서드의 테스트는 `AbstractPlayer`의  테스트와 같은 동작을 할 것 같습니다.

그래서 재정의를 하지 않는다면 꼭 할 필요는 없다고 생각됩니다.

테스트가 의미없이 중복되면 `AbstractPlayer`에서 기능이 변경되면 `AbstractPlayer`, `Dealer` , `Participant`의 테스트를 모두 고쳐야할 것 같은데 이것도 의미없이 테스트가 중복되어 발생하는 문제라고 생각됩니다.

2022-03-15 05:53 UTC, OzRagwort commented on src/main/java/blackjack/domain/Dealer.java
> +    }
다시 고민해보면서 toString은 구현  클래스마다 재정의하는것으로 바꿨습니다. [1a28291](https://github.com/woowacourse/java-blackjack/pull/232/commits/1a2829132ae9c06ee97b07a4deaff17c6e3c38e0)

Dealer.toString()하면 Delaer{name= ...
Participant.toString()하면 Participant{name= ...
이렇게 보면 더 좋을 것 같아서요!

2022-03-15 06:04 UTC, OzRagwort commented
[1a28291](https://github.com/woowacourse/java-blackjack/pull/232/commits/1a2829132ae9c06ee97b07a4deaff17c6e3c38e0)에서 Player 하위 클래스들의 구조를 조금 바꿨습니다.

수정 전 :
Interface Player
ㅣ
public class AbstractPlayer implements Player
ㅣ
public class Dealer extends AbstractPlayer implements Player
public class Panticipant extends AbstractPlayer implements Player

이런 구조였는데 딜러와 참가자가 따로 구현해야할 메서드를 AbstractPlayer에 넣고 구현해버리니 추상 메서드가 다 사라졌습니다.
그래서 사실상 Player를 상속해서 Panticipant를 만들고 extends해서 Dealer를 만든것과 다르지 않는 구조였습니다.
그리고 AbstractPlayer가 추상 클래스가 아니어서 바로 사용할 수 있다는 것도 문제가 되었습니다.

수정 후 :
Interface Player
ㅣ
public abstract class AbstractPlayer implements Player
ㅣ
public class Dealer extends AbstractPlayer implements Player
public class Panticipant extends AbstractPlayer implements Player

딜러와 참가자가 다르게 구현되어야 할 메서드는 isDealer와 canHit(이전 isValidRange 메서드)입니다.

그래서 이 둘을 AbstractPlayer에서 추상 메서드로 만들고 딜러와 참가자가 `@Override`해서 사용하도록 수정했습니다.

2022-03-17 00:18 UTC, jjj0611 commented on src/main/java/blackjack/domain/AbstractGamer.java
> +public abstract class AbstractGamer implements Gamer {
넵 맞아요 알린 저도 동의해요.
`같은 동작`을 하도록 의미했다가 핵심일 것 같아요 :)

2022-03-17 00:20 UTC, jjj0611 approved these changes
안녕하세요 알린! 리뷰어 제이입니다.

정말 눈에 띄게 코드가 바뀌었어요...
rule 같은 부분도 너무 잘 적용해주셨고,
코멘트 드린 것들의 의미 파악이나 적용 방향이 너무 좋아요! :)

1단계는 바로 머지하고 2단계 쭉 진행해주셔도 좋을 것 같아요.

리뷰가 조금 늦어서 혹시 궁금한거나 고민되는게 있다면 DM으로 편하게 물어봐주세요!
1단계는 이만 머지하겠습니다!

2022-03-17 00:20 UTC, merged