[1단계 - 블랙잭] 크리스(공병주) 미션 제출합니다.
woowacourse/java-blackjack pull request #241
Opened 2022-03-11 07:32 UTC by Byeongju-Kong

닉! 반가워요! 이번 블랙잭 미션하면서 들었던 고민들을 아래에 정리해보았어요!
사실 리팩토링 해야 할 부분들이 보이는데, 미션 제출 기한 때문에 일단 PR 날려요! 리뷰해주시면 참고하면서 리팩토링 하겠습니다~!

 1. View에서 이름 값들을 받기 때문에, Application은 이름 값들을 알 수 있어요.
 그렇다면, 이름 값들을 담은 객체를 불변으로 만든 후, 아래와 같이 names.stream()을 통해 반복하면서 이름 값을 기준으로 게임을 진행하는 건 어떨까요?
 
 ```java
names.forEach(this::playTurnOf);

private void playTurnOf(String name) {
    while(blackJackGame.isTurnOver(name) {
        //BlackJackGame에 이름 값을 받아 게임을 진행하는 메소드 구현
    }
}
```

2. DTO 변환 위치
 현재, Player에는 Player의 상태를 변경할 수 있는 draw 메소드가 있기 때문에, 출력을 위해서 DTO를 사용했어요. 따라서, Player를 DTO로 변환해주어야 하는데, 변환 위치가 현재는 도메인이예요. 이 부분에 대해서 어떻게 생각하시나요? controller layer를 두고 controller에서 변환을 하는 것이 어떨까? 라는 생각이 들어요. 그렇다면 controller에서는 Player의 draw 메소드를 호출할 수 있는 상황이 되는데, 여기에 대한 문제는 없을까요? 

3. 상속 및 구현
저는 이번 미션에서 상속은 state 와 Participant 패키지에서 사용해보았고 구현은 state에서만 사용했어요. Participant가 추상클래스인 이유는 Dealer와 Player는 책임이 다르고 그에 따라 메소드들도 달라요. 그래서 Dealer와 Player를 Participant 타입으로 참조할 것이 아닌, 단순 Dealer와 Player의 중복 로직을 제거하기 위한 목적이기 때문에 추상클래스를 적용했어요. 반대로 State는 모든 구현체들을 State 타입으로 관리할 것이고 같은 메소드를 사용하기 때문에, 명세(?)와 같은 개념으로 인터페이스를 사용했어요. 제 생각에 대한 피드백 부탁드릴께요!

4. state 패키지
처음에는, Hit, Stay, Bust, BlackJack을 state를 implement하는 enum으로 관리하려고 했어요. 하지만 코드의 중복이 너무 많아져서 class로 분리를 했는데, 관리할 클래스가 많아졌고 구조가 보다 복잡해졌다는 생각이 드네요. state 패키지의 구조에 대한 피드백도 부탁드려요!

2022-03-12 16:06 UTC, wbluke requested changes
안녕하세요 크리스~! 블랙잭 미션 리뷰를 맡은 닉입니다 🙌 
코드가 정말 깔끔하네요 👍 
크게 피드백 드릴 부분은 안보였지만, 남겨주신 질문에 대한 답변과 몇 가지 고민해볼 수 있는 지점 남겼으니 참고 부탁드려요 🙂

2022-03-12 16:06 UTC, wbluke commented on src/test/java/blackjack/domain/card/CardNumberTest.java
> +    }
엣지 케이스는 잘 뽑아서 테스트 해주신 것 같아요 👍 

제가 항상 중요하게 생각하는 테스트의 기능 중 하나는 바로 애플리케이션에 대한 **명세**라는 것인데요.
다시말해 위 테스트 문서를 봤을 때 실제 프로덕션 코드가 어떤 기능을 하는지 알 수 있어야 한다고 생각해요.

`a 10은 스코어가 21이다.` 라는 문장은 실제 테스트 픽스처에 대한 설명이고, 
실제로 테스트하고자 하는 명세는 `총합이 21이 넘지 않는 경우 a는 기본적으로 11로 계산된다.` 정도가 아닐까요?
애플리케이션을 사용하는 클라이언트 관점에서, 혹은 새로 합류한 팀원이 테스트 문서만 보고도 프로덕션 코드의 동작을 유추할 수 있게끔 테스트 문서를 작성하는 연습을 하면 좋을 것 같아요 ㅎㅎ
한번 전체적으로 체크해 보셔요 :)

2022-03-14 07:49 UTC, kang-hyungu commented on src/main/java/blackjack/Application.java
> +public class Application {
메인 클래스가 너무 복잡합니다.
아래 코드와 같이 단순하게 만들어봅시다.

```suggestion
public class Application {
    public static void main(final String[] args) {
        var blackJackGame = new BlackJackGame();
        blackJackGame.run();
    }
}
```

2022-03-14 07:49 UTC, kang-hyungu commented on src/main/java/blackjack/controller/BlackJackController.java
> +public class BlackJackController {
단순한 콘솔 게임이라 복잡한 UI나 웹처리가 없는데 컨트롤러가 필요할까요?
컨트롤러 대신 적절한 이름으로 바꿔봅시다.

2022-03-14 07:49 UTC, kang-hyungu commented on src/main/java/blackjack/controller/BlackJackController.java
> +    public List<PlayerFinalResultDto> getPlayerResultInfos() {
클린코드
p32
클래스 이름
클래스 이름과 객체 이름은 명사나 명사구가 적합하다. Customer, WikiPage, Account, AddressParser 등이 좋은 예다. Manager, Processor, Data, Info 등과 같은 단어는 피하고, 동사는 사용하지 않는다.

2022-03-14 07:50 UTC, kang-hyungu commented on src/main/java/blackjack/controller/BlackJackController.java
> +    public List<PlayerFinalResultDto> getPlayerResultInfos() {
dto가 필요한 시스템 규모인가요?
오히려 dto를 처리하기 위한 코드가 추가되면서 시스템 복잡도를 높이고 있지 않나요?

2022-03-14 07:51 UTC, kang-hyungu commented on src/main/java/blackjack/domain/card/Card.java
> +    public static Card of(final CardPattern pattern, final CardNumber number) {
생성자가 있는데 팩터리 메서드를 만든 이유가 무엇인가요?

2022-03-14 07:55 UTC, kang-hyungu commented on src/main/java/blackjack/domain/card/Card.java
> +    public static List<Card> cards() {
자바 관례상 메서드명은 동사를 써주는게 좋습니다.

2022-03-14 07:57 UTC, kang-hyungu commented on src/main/java/blackjack/domain/card/CardDeck.java
> +            throw new IllegalStateException("남은 카드가 2장 미만입니다.");
```suggestion
            throw new IllegalStateException("남은 카드가 " + INIT_PROVIDING_CARD_SIZE + "장 미만입니다.");
```

게임 규칙이 바뀐다면 이 메시지도 수정해줘야겠네요. 상수를 메시지에 포함시키면 수정 내용이 같이 반영되겠네요

2022-03-14 07:59 UTC, kang-hyungu commented on src/main/java/blackjack/domain/card/CardNumber.java
> +        while (bonusSum <= MIN_VALUE_ADDING_BONUS && countOfA-- > 0) {
while문 조건이 너무 복잡하네요.
좀더 읽기 좋게 수정해보시기 바랍니다.

2022-03-14 13:19 UTC, wbluke requested changes
피드백 반영해주신 부분 잘 봤습니다 ㅎㅎ
다만 의도한 방향과 조금 다른 부분이 있어서, 한번 더 체크해주시면 좋을 것 같아요 🙂

2022-03-14 13:19 UTC, wbluke commented on src/test/java/blackjack/domain/card/CardNumberTest.java
> +        }
음 제가 의도했던 방향이 아닌데요.
일단 상위 DisplayName을 위해 Nested 클래스를 정의하는 것이 좋아보이지는 않고요,
저는 각 테스트 케이스의 제목이 `테스트 픽스처(테스트 시에 사용되는 데이터)`가 아니라 `테스트 명세`가 되기를 원했던 거였어요.

```java
int number1 = 3;
int number2 = 5;

Calculator calculator = new Calculator();
int result = calculator.add(number1, number2);

assertThat(result).isEqualTo(8);
```

테스트 픽스처를 가지고 위 테스트의 이름을 짓는다면 `3 + 5 는 8이다.` 겠지만
테스트 명세를 가지고 이름을 짓는다면 `계산기로 두 수를 더한 값을 구할 수 있다.` 정도가 아닐까요?

위 케이스들만 봐도 에이스를 1로 계산하는 케이스와 11로 계산하는 케이스, 에이스가 없는 일반적인 케이스, 에이스가 2장인 경우 등 명세로 나타낼 수 있는 여지가 많아보여요.
케이스가 비슷하면 테스트 하나로 합치거나, 더 쪼갤 수 있다면 쪼개도 좋구요.

조금 다른 말로 해보자면, 이 프로젝트를 처음 보는 제 3자가 해당 문장을 읽었을 때, 에이스가 1로 계산되는걸 테스트해야하는건지, 11로 계산되는걸 테스트해야하는건지 명확하게 알 수 없을 것 같아요. 오히려 해당 규칙을 모르는 상태에서 테스트 문서를 읽는다면 테스트 간 전제가 달라서 혼란만 가중될 것 같네요.

한번 곰곰히 생각해 보셔요 :)

2022-03-14 13:19 UTC, wbluke commented on src/main/java/blackjack/domain/state/finished/BlackJack.java
> +        if (State.isSameState(another, BlackJack.class)) {
음 static 메서드보다 더 나은 방법이 있을 것 같아요.
`another.isBlackJack()` 같은 형태면 되지 않을까요 :)

2022-03-14 22:59 UTC, wbluke approved these changes
피드백 반영 감사해요 👍 
다음 단계 진행해 주세요 🙂

2022-03-14 22:59 UTC, wbluke commented on src/main/java/blackjack/domain/state/finished/Stay.java
> +        } else if (another.isSameStateWith(Bust.class)) {
`else 예약어를 쓰지 않는다.`
저번에도 드린 피드백 같은데요, 프로그래밍 요구사항을 확인해 주세요 :)

2022-03-14 22:59 UTC, wbluke commented on src/test/java/blackjack/domain/card/CardNumberTest.java
> +    @DisplayName("카드 숫자들을 받아, 21 이하의 최대 합을 반환한다. J, Q, K는 10으로 계산하고 A는 1 혹은 11로 계산할 수 있다.")
적어도 Ace의 테스트 케이스는 1과 11 둘로 나누는 게 좋을 것 같아요 :)

2022-03-14 23:00 UTC, merged