[1단계 - 블랙잭] 소주캉(강승주) 미션 제출합니다
woowacourse/java-blackjack pull request #252
Opened 2022-03-11 08:01 UTC by sojukang

안녕하세요 `럿고`👏👏!! 블랙잭 미션 리뷰를 부탁드리게 된 소주캉입니다. 
기본적으로 네이밍은 영문 블랙잭 게임 용어를 참고하였습니다. 
이번 미션 잘 부탁드립니다✨✨🤝

2022-03-12 06:54 UTC, ksy90101 commented on src/main/java/blackjack/controller/GameController.java
> +            OutputView.printPlayerCards(new ParticipantVo(player));
Vo라는 단어를 붙이는게 맞을까요?
아울러 View와 Controller의 통신을 무엇으로 하면 좋을지 고민해보세요 :)

2022-03-12 07:09 UTC, ksy90101 requested changes
안녕하세여 :) 소주캉 리뷰어 럿고입니다.
블랙잭을 구현하시느라 너무 고생 많으셨습니다 💯 
몇가지 피드백을 남겼으니, 한번 보시고 수정해보시면 좋을거 같습니다. 

언제든지 질문이 있다면 DM이나 댓글을 이용해주세요~

2022-03-12 07:09 UTC, ksy90101 commented on src/main/java/blackjack/domain/card/CardDeck.java
> +    public static CardDeck createNoShuffle() {
해당 메서드는 테스트를 위한 코드인거 같네요.
프로덕션에서는 테스트를 위한 코드가 있으면 안된다고 생각하는데요.
이런 경우에는 어떻게 하면 좋을까요?

힌트를 조금 드리자면, 자동차 경주게임에서 랜덤값을 어떻게 테스트 했는지 한번 고민해보세요.

위와 같은 구조로 변경된다면 CardDeck에서는 CardDeck을 생성하고, shuffle해서 Cache의 책임을 모두 사용할 수 있을거 같아요.

그렇다면 CardDeck을 그냥 가져다 쓰면 되는 구조가 될거 같네요 :)

2022-03-12 07:09 UTC, ksy90101 commented on src/main/java/blackjack/domain/card/Cards.java
> +    private final Set<Card> value;
👍

2022-03-12 07:09 UTC, ksy90101 commented on src/main/java/blackjack/domain/card/PlayStatus.java
> +    public static final int BUST_SCORE = 21;
public으로 해야 하는 이유가 있을까요?

2022-03-12 07:09 UTC, ksy90101 commented on src/main/java/blackjack/domain/participant/Dealer.java
> +public class Dealer extends Participant {
👍

2022-03-12 07:09 UTC, ksy90101 commented on src/main/java/blackjack/domain/participant/Dealer.java
> +        return "딜러";
"딜러"라는 건 계속 고정일거 같은데, 상수로 빼면 어떨까요?

2022-03-12 07:09 UTC, ksy90101 commented on src/main/java/blackjack/domain/participant/Dealer.java
> +        while (getStatus() == PlayStatus.HIT && getScore() <= 16) {
16 매직넘버!

2022-03-12 07:09 UTC, ksy90101 commented on src/main/java/blackjack/domain/participant/Participant.java
> +public abstract class Participant {
Dealer를 보니 init()이라는 메서드가 있네요.
근데 Participant에 보니 init이라는 메서드가 또 존재하네요.
Dealer 입장에서는 Overloading이 되버릴꺼 같은데, 이 구조를 한번 바꿔볼까요?

2022-03-12 07:09 UTC, ksy90101 commented on src/main/java/blackjack/view/InputView.java
> +        if (!text.matches("[YyNn]")) {
matchers는 굉장히 비싼 연산입니다 :) 어떻게 하면 성능 개선을 할 수 있을지 한번 고민해보세요~

2022-03-12 07:09 UTC, ksy90101 commented on src/main/java/blackjack/vo/ParticipantVo.java
> +        return participant.getCards().getValue();
디미터의 법칙을 위반한거 같은데 한번 참고해볼까요?
https://mangkyu.tistory.com/147

2022-03-14 07:35 UTC, sojukang commented on src/main/java/blackjack/controller/GameController.java
> +            OutputView.printPlayerCards(new ParticipantVo(player));
해당 객체는 단순히 값을 담는 객체가 아니고, 동등성 비교도 옳지 않으니 Vo가 아니군요! dto로 변경해보았습니다.

2022-03-14 07:52 UTC, sojukang commented on src/main/java/blackjack/domain/Record.java
> +    Record getOpposite() {
저는 `public` 밑으로 좁힐 수 있는 경우 좁히는 편을 선호하는데 `럿고`의 생각은 어떠신가요??

2022-03-14 07:54 UTC, sojukang commented on src/main/java/blackjack/domain/card/Card.java
> +        return "Card{" +
인텔리제이에서 자동으로 만들어주는 `toString`만 사용해왔는데, `럿고`가 남겨주신 글 보고 이번 미션에는 `ToStringBuilder`를 사용해보자! 라고 결정해보았습니다. 필드가 변경될 경우나 다양한 포멧으로 출력할 수 있는 장점이 있군요!

2022-03-14 07:55 UTC, sojukang commented on src/main/java/blackjack/domain/card/CardCount.java
> +            .orElseThrow();
만들 당시에는 `어차피 예외가 발생할 것이니 따로 정의해주지 말자`로 넘어갔는데, 확실하게 정의해주는 편이 좋을 것 같아서 수정해보았습니다. 감사합니다.

2022-03-14 07:58 UTC, sojukang commented on src/main/java/blackjack/domain/card/CardDeck.java
> +    public static CardDeck createNoShuffle() {
`DeckStrategy`를 인터페이스로 정의하고, 어플리케이션에서는 `RandomDeck` 구현체를 사용하고, 테스트에서는 `TestDeck`구현체를 사용하도록 변경해보았습니다.

2022-03-14 07:59 UTC, sojukang commented on src/main/java/blackjack/domain/card/PlayStatus.java
> +    public static final int BUST_SCORE = 21;
다른 클래스에서 사용하는 상수라서 `public`으로 열어두었는데, 굳이 다른 클래스에서 상수를 직접 사용하지 않고 PlayStatus에 책임을 주는 방식으로 변경하여 `isBust()` 메소드를 새로 만들어 상수를 `private`으로 바꾸어보았습니다.

2022-03-14 08:00 UTC, sojukang commented on src/main/java/blackjack/domain/participant/Dealer.java
> +        return "딜러";
상수로 빼보았습니다!

2022-03-14 08:01 UTC, sojukang commented on src/main/java/blackjack/domain/participant/Dealer.java
> +        while (getStatus() == PlayStatus.HIT && getScore() <= 16) {
앗! 롤백 중에 날아가버렸군요 😅. 상수로 만들어보았습니다.

2022-03-14 08:02 UTC, sojukang commented on src/main/java/blackjack/domain/participant/Participant.java
> +public abstract class Participant {
`TDD`로 만들던 결과로 테스트에서만 남게 된 `init`이 남아있었군요😅. 삭제하고 테스트를 수정하였습니다.

2022-03-14 08:05 UTC, sojukang commented on src/main/java/blackjack/view/InputView.java
> +        if (!text.matches("[YyNn]")) {
`럿고`가 남겨주신 글을 보고 `matches` 대신 collection의 `contains`를 이용해 새로운 메서드를 만들고 두 로직을 1억번 검증해보았는데 약 10배나 matches가 걸리는군요😮! 앞으로 정규표현식을 사용할 땐 주의해보겠습니다.

2022-03-14 08:08 UTC, sojukang commented on src/main/java/blackjack/vo/ParticipantVo.java
> +        return participant.getCards().getValue();
확실히 `participant.getCards()`가 위임하여 비포장형을 내보내도록 하면 깔끔하긴 한데, 도메인 객체 외부의 사정에 의해 도메인 객체의 접근 메서드가 수정되는 것이 마음에 걸리긴 합니다. 이 부분은 항상 고민되네요🤔.

2022-03-14 08:12 UTC, sojukang commented
안녕하세요 `럿고`👋👋!
다시 리뷰 요청을 드리게 된 `소주캉`입니다. 
이번에는 기본적으로 남겨주신 피드백을 바탕으로 수정하였고, 고려한 내용은 다음과 같습니다. 
1. 객체 간 적절한 책임 분산
2. 연관 있는 객체 모듈화

일요일에 진행해주신 내용도 너무 도움이 되었습니다! 이번 리뷰도 잘 부탁드립니다🙏.

2022-03-14 14:45 UTC, ksy90101 commented on src/main/java/blackjack/domain/Record.java
> +    Record getOpposite() {
저도 좁힐수 있으면 좁히는거 좋아합니다 :) 혹시 알고 쓰셧나 해서 여줘봤어요 :)
개인적으로 default생성자가 많으면 많을수록 도메인의 행위나 상태가 잘 드러나지 않는다고 생각을 합니다 👍

2022-03-14 14:45 UTC, ksy90101 commented on src/main/java/blackjack/domain/card/Card.java
> +        return "Card{" +
ㅎㅎㅎㅎㅎ 넵넵 저도 최근에 봤는데 좋은거 같더라구요~

2022-03-14 14:58 UTC, ksy90101 requested changes
소주캉 안녕하세요 :) 리뷰어 럿고입니다.
피드백 적용하시느라 너무 고생 많으셨습니다 💯 
의견을 적어주신것도 잘 봤습니다!
간단한 피드백을 좀 더 남겼으니, 참고해보시고 수정해주세요~

질문은 언제든지 환영입니다 👍

2022-03-14 14:58 UTC, ksy90101 commented on src/main/java/blackjack/controller/GameController.java
> +            Player player = game.findHitPlayer().get();
Optional.empty()가 나와버리면 어떻게 될까요?

2022-03-14 14:58 UTC, ksy90101 commented on src/main/java/blackjack/domain/RecordFactory.java
> +    private final Map<Record, Integer> dealerRecord;
EnumMap을 고려해보면 어떨까요?

2022-03-14 14:58 UTC, ksy90101 commented on src/main/java/blackjack/domain/RecordFactory.java
> +    private void updateDealerRecord(Record record) {
지금 사용하는 java version에서는 record 기능이 없지만, 이후 버전에서는 record가 예약어 일거에요.
이건 참고만 해주세요~

2022-03-15 13:31 UTC, sojukang commented on src/main/java/blackjack/domain/card/CardDeck.java
> +    private final Stack<Card> deck;
`Stack`은 Thread safe 하지 않고 성능도 느리군요! `Deque`로 바꿔보았습니다. 감사합니다.

2022-03-15 13:34 UTC, sojukang commented on src/main/java/blackjack/controller/GameController.java
> +            Player player = game.findHitPlayer().get();
`Optional.empty()`가 나올 경우 `while` 바깥으로 나가서 `drawPlayerCards` 단계가 넘어가니 옳은 동작이라고 생각하였습니다. 조건문에서 `isPresent`로 체크하였으니 내부에서 `get()`을 사용할 수 있다고 보았는데, 혹시 다른 놓친 부분이 있을까요? 아예 플레이어가 없을 경우를 체크하는 검증을 추가해보았습니다.

2022-03-15 13:43 UTC, sojukang commented on src/main/java/blackjack/controller/GameController.java
> +    private void ParticipantsResult(Game game) {
앗! 놓친 부분이 있었군요😓

2022-03-15 13:44 UTC, sojukang commented on src/main/java/blackjack/domain/RecordFactory.java
> +    private final Map<Record, Integer> dealerRecord;
더 성능 좋고 안정적인 `EnumMap`으로 바꾸어보았습니다. 감사합니다.

2022-03-15 13:45 UTC, sojukang commented on src/main/java/blackjack/domain/RecordFactory.java
> +    private void updateDealerRecord(Record record) {
14 버전부터 `Record`가 예약어이군요! `PlayRecord`로 바꾸어 보았습니다. 감사합니다.

2022-03-15 13:45 UTC, sojukang commented on src/main/java/blackjack/controller/GameController.java
> +                (a, b) -> b, LinkedHashMap::new));
의미를 명확하게 `(recordA, recordB) -> recordB`로 바꾸어 보았습니다. 감사합니다.

2022-03-15 13:47 UTC, sojukang commented on src/main/java/blackjack/domain/Record.java
> +            .orElseThrow();
스트림으로 순회하는 것보다 조건문을 통해 간단하게 반환하는 게 더 깔끔하고 읽기 쉽다고 생각하여 바꾸어보았습니다.

2022-03-15 13:47 UTC, sojukang commented on src/main/java/blackjack/domain/Record.java
> +            .filter(record -> record.name.equals(opposite))
위와 같은 이유로 바꾸어 보았습니다.

2022-03-15 13:49 UTC, sojukang commented on src/main/java/blackjack/dto/ParticipantDto.java
> +public class ParticipantDto {
그렇군요! 따로 ModelMapper를 두어 거기서 도메인 객체를 받아 값을 DTO에 할당하는 방식으로 바꾸어보았습니다. 감사합니다.

2022-03-15 13:55 UTC, sojukang commented on src/main/java/blackjack/domain/PlayStatus.java
> +    public static PlayStatus hitOrBust(int sum) {
`hitOrBust`를 위한 별도의 테스트를 만들어보았습니다.

2022-03-15 13:56 UTC, sojukang commented on src/main/java/blackjack/domain/Game.java
> +    public Optional<Player> findHitPlayer() {
`findHitPlayer`를 위한 테스트를 추가해보았습니다. 감사합니다.

2022-03-15 14:00 UTC, sojukang commented
안녕하세요 `럿고`👋👋!!
저번 리뷰도 다시 한번 감사드립니다. 
남겨주신 리뷰를 보고 느낀 점이 처음 페어 프로그래밍을 하며 구현할 당시 
_이건 지금은 페어 시간이 없으니 다음에 혼자 할 때 추가 or 수정하고 넘어가야겠다_
하고 넘어간 게 부메랑이 되어서 돌아오는군요😓 역시 그때 발견한 문제점은 시간이 부족해도 즉시 해결하거나 꼭 기록해두는 편이 좋은 것 같습니다. 
이번에도 기본적으로 남겨주신 피드백을 바탕으로 수정하면서 부족했던 테스트는 보강하고, 객체간 역할 분담을 고려해보았습니다. 
이번에도 잘 부탁드립니다✨🙏!!

2022-03-16 00:04 UTC, ksy90101 approved these changes
안녕하세요 :) 소주캉 
피드백 적용하시느라 고생하셨습니다 💯 
1단계는 이만 머지할게요~
2단계때 봐요~

2022-03-16 00:04 UTC, merged

2022-03-18 00:16 UTC, ksy90101 commented on src/main/java/blackjack/controller/GameController.java
> +            Player player = game.findHitPlayer().get();
앗 이부분은 제가 잘못 봤네요.