[1단계 - 블랙잭] 차리(이찬주) 미션 제출합니다.
woowacourse/java-blackjack pull request #259
Opened 2022-03-11 08:16 UTC by cjlee38

안녕하세요, 럿고 ! 

먼저, 바쁜 시간 내셔서 리뷰해주시는 점 감사의 말씀 드립니다. 이번 블랙잭 미션은 구현하면서 꽤 난이도가 있었다고 생각이 드는데요.
중간중간 어려워서 깔끔하게 해결하지 못한 부분들이 꽤 많이 있는데 😢, 해당 부분에 대한 질문 comment 따로 남기겠습니다.

감사합니다! ☺️

2022-03-11 08:31 UTC, cjlee38 commented on src/main/java/blackjack/controller/BlackJackController.java
> +    }
HitStrategy와 전반적으로 관련된 내용을 이곳에 남기겠습니다!

먼저, 저는 기본적으로 다음과 같이 생각했는데요.
딜러와 플레이어의 공통점은 게임에 참여한다는 점과 블랙잭 자체의 규칙에 지배받는다고 생각하여, 이 부분을 User라는 이름으로 공통 로직을 뽑아냈습니다.

그리고 딜러와 플레이어의 차이점은 초기에 패를 한 장만 보여준다는 점(이부분은 따로 질문 남기겠습니다)과 카드를 더 뽑을것인지(hitOrStay) 의 결정 방식인데요. 플레이어는 21이하이면서 동시에 "y"가 입력되어야하고, 딜러는 16 이하여야 카드를 더 뽑을 수 있는데, 여기서 딜러의 카드 뽑기 유무를 플레이어와 같은 방식으로 다루고자 "21이하인가?" 와 "16이하인가? 로 구분하였습니다.

그리고 플레이어의 "y를 입력받았는가?" 와 딜러의 "16이하인가?" 를 같은 메소드로 처리하고자 하였는데, 메소드의 시그니쳐가 다르다보니 이를 HitStrategy 라는 인터페이스로 빼내서 사용하게 되었습니다. 

여기까지는 괜찮은데, 이후에 실질적으로 Controller에서 이 부분을 사용하려다보니 위와 같이 우스꽝스러운 모습이 나와버렸는데요. controller의 `hitOrStayCardPlayer`와 `hitOrStayCardDealer` 를 `hitOrStayPerUser` 로 묶고, 외부에서 HitStrategy를 넣어주는 방식을 취하고 싶은데  inputView, 그리고 outputView와 얽혀서 따로 구분할 수 밖에 없는 상황이 되어버렸습니다 ㅠ

뭔가 추상화를 잘못했다는 생각이 드는데, 어디서부터 손대야할지 감을 못잡겠습니다. 럿고가 보시기에 "어느 객체에 책임 할당이 잘못되었는지" 에 대해서 한마디 조언 부탁드릴 수 있을까요?

2022-03-11 09:05 UTC, cjlee38 commented on src/main/java/blackjack/domain/user/User.java
> +    public abstract List<Card> showInitCards();
초기에 플레이어와 딜러의 공통적인 부분은 user에 두고, 차이가 있는 부분은 concrete class인 Dealer 와 Player에 배치시키고자 하였습니다. 플레이어와 딜러의 차이가 있는 부분은 "카드를 더 뽑을것인가?"에 대한 전략, 그리고 "초기에 카드를 몇 장 보여줄 것인가?" 의 이 두 부분인데요. 앞서 말씀드린바와 같이 "카드를 더 뽑을 것인가?" 에 대한 책임을 HitStrategy 라는 인터페이스로 넘겨주었기 때문에, 남아있는 구분되는 책임은 "초기에 카드를 몇 장 보여줄것인가?" 가 남아있습니다.

그런데 HitStrategy를 만들고보니, 이 부분 또한 "CardShowBehaviour(혹은 Strategy)"와 같이 별도로 뽑아낼 수 있을 것 같은데요. 그렇게될 경우 User 하나만 남게 되고, Player와 Dealer를 구분하는 방법은 변수의 이름밖에 없는 것 같아, 이 부분까지 걷어내는 것은 그리 좋은 방법은 아니라는 생각이 들어 남겨두게 되었습니다.

따라서 현재 코드는 이도저도 아닌 상황에 놓여있는 것 같다는 생각이 드는데요... 뭔가 통일성이 없는 것 같다는 생각이 드는데, 아직 배움이 짧아 어느 부분에서 문제가 될 수 있는지, 어떻게 개선하는 것이 더 나은 방향일지 잘 모르겠습니다. 럿고의 생각을 여쭙고 싶습니다!

2022-03-13 03:15 UTC, ksy90101 requested changes
안녕하세요 차리 :) 리뷰어 럿고입니다.
블랙잭 미션하시느라 고생 많으셨습니다 💯 
간단한 피드백을 남겼으니, 참고해주세요

언제든지 질문은 DM이나 댓글을 이용해주세요~

2022-03-13 03:15 UTC, ksy90101 commented on src/main/java/blackjack/domain/card/Deck.java
> +                .collect(Collectors.toList());
stream 안에 stream이 있다면 depth는 몇일까요?

2022-03-13 03:15 UTC, ksy90101 commented on src/main/java/blackjack/domain/strategy/DealerHitStrategy.java
> +public class DealerHitStrategy implements HitStrategy {
👍

2022-03-13 03:15 UTC, ksy90101 commented on src/test/java/blackjack/domain/strategy/HitStrategyTest.java
> +    @DisplayName("(플레이어) y가 입력되면 카드를 한장 더 받을 수 있다.")
n에 대한 테스트도 있어야 할거 같은데요!?

2022-03-13 03:15 UTC, ksy90101 commented on src/test/java/blackjack/domain/user/DealerTest.java
> +    @DisplayName("딜러는 카드를 뽑을 수 있다.")
테스트를 보다보니, 딜러의 정책중 하나는 17이상이면 카드를 뽑을수가 없다는것인데요.
이것도 한번 테스트 코드를 작성해서 책임을 딜러에게 주면 어덜까요?

2022-03-15 07:28 UTC, cjlee38 commented on src/main/java/blackjack/controller/BlackJackController.java
> +public class BlackJackController {
일전에 말씀드린것처럼, 딜러는 16 이하인 경우 한장만 받았었는데, 규칙 상 계속 카드를 받아야 하기 때문에 이 부분 반영하였습니다!

2022-03-15 07:28 UTC, cjlee38 commented on src/main/java/blackjack/domain/card/Card.java
> +    @Override
😢 수정하였습니다!

2022-03-15 07:28 UTC, cjlee38 commented on src/main/java/blackjack/domain/card/Deck.java
> +    private final Deque<Card> cards;
말씀주신대로 미리 52장의 카드를 캐싱해놓고, 생성을 요청할때마다 copy 및 shuffle을 통해 돌려주도록 변경하였습니다!

2022-03-15 07:28 UTC, cjlee38 commented on src/main/java/blackjack/domain/card/Score.java
> +        this(0);
0은 그 자체로 충분히 의미를 갖는다고 생각하여 상수화 하지 않았는데, 다시 살펴보니 사용되는 부분이 꽤 많아 상수화할 가치가 있다고 판단하여 적용하였습니다!

2022-03-15 07:28 UTC, cjlee38 commented on src/main/java/blackjack/domain/card/Deck.java
> +                .collect(Collectors.toList());
아하.. stream이 중첩되면 depth가 추가된 것으로 보는군요.. 몰랐습니다. 해당 부분 따로 메소드로 추출하였습니다!

2022-03-15 07:28 UTC, cjlee38 commented on src/test/java/blackjack/domain/strategy/HitStrategyTest.java
> +    @DisplayName("(플레이어) y가 입력되면 카드를 한장 더 받을 수 있다.")
깜빡하고 놓쳤습니다 ㅠ 이 부분 또한 추가하였습니다!

2022-03-15 07:28 UTC, cjlee38 commented on src/test/java/blackjack/domain/user/DealerTest.java
> +    @DisplayName("딜러는 카드를 뽑을 수 있다.")
말씀주신대로 딜러 + Hit전략이 결합되었을 경우의 테스트를 추가하고자 하였는데, 여러가지 의문이 들어 질문드립니다!

기존 유저가 카드를 뽑는 drawCard가 랜덤으로 shuffle된 Deck을 입력받아, List<Card>에 카드를 추가할 때 deck으로부터 카드를 뽑도록 구현되어있었는데요. 그러다보니 유저에게 특정한 카드를 넘겨줄 수 없어, 딜러가 17이상, 21이하의 값을 가지도록 적용할 수가 없었습니다.

그러다보니 drawCard(Deck deck) 메소드를 고쳐 receiveCard(card) 로 변경하고, deck에서 카드를 뽑는 로직은 외부에서 호출하도록 변경하였는데요. 이 부분을 적용하면서 드는 생각이, "덱으로부터 카드를 뽑는 순간이 어디여야 하는가?" 에 대한 근원적인 의문이 생겼습니다. 현재 구조가 users -> user -> hand 로 연결되는데, users에서도, user에서도, hand에서도 각각 다 pop을 할 수 있는 당위성이 주어진 것 같은데, 어느 클래스에서 실행하는게 조금 더 개념적으로 합리적인지.. 혹은 유연성을 가질 수 있는지에 대해 궁금합니다. 지난 리뷰어분으로부터 마지막에  "행위와 책임을 구분해야한다" 라는 피드백을 받긴 했었는데, 아직도 그 부분을 이해하지 못한 것 같아 럿고에게 여쭤봅니다 ㅠ

2022-03-15 07:41 UTC, cjlee38 commented
안녕하세요, 럿고! 말씀주신 피드백은 어느정도 반영한 것 같습니다. 또한, 피드백을 반영하면서 구조가 일부 변경되었는데요 (controller -> controller + game) 코드를 작성하다 보니 기존에 드렸던 질문에 대해서 어떤 부분이 고민이었는지, 그리고 왜 이렇게 변경하였는지에 대해서 조금 설명을 드릴 필요가 있는 것 같아 몇 자 남깁니다!

기존에 제가 "공통되는 부분이 있는데 이 부분을 별도로 구분하는 점이 마음에 들지 않는다" 라고 말씀드렸었는데요. 물론 그 부분도 제가 생각했던 불편한 점 중 하나였지만, 조금 더 근원적으로 생각해보니 "유저의 hit/stay가 외부에 의해 결정된다" 라는 부분 또한 어색했었던 것 같습니다. 

"객체지향스러운" 코드는 모든 객체가 능동적으로 행동할 수 있어야 하고, 그렇기 때문에 저희가 getter로 값을 꺼내서 작업을 하거나, 혹은 setter를 사용하는 것을 지양하는 것으로 알고 있습니다. 그런데, 기존의 controller에서 inputview로부터 "y" 혹은 "n"을 받아서 플레이어가 카드를 더 받을지 말지 여부를 1차 검사하고, 또 if (!player.isBust()) 와 같은 조건검사를 통해서 카드를 추가하냐 마냐를 판단하게 되는데, 이는 플레이어가 수동적으로 행동하는 것 같아, getter 혹은 setter를 쓰는 것과 다를바가 없다고 느껴졌습니다. 

그렇기에 이번 변경된 코드에서는 전략패턴을 활용하고, 함수형 인터페이스를 활용하여 플레이어가 hitOrStay 메소드를 실행할 때에 실질적으로 inputView가 실행될 수 있도록 변경하였습니다.

한편, 기존 controller에서 users와 deck을 가지고 게임을 진행했었는데, deck이 반복적으로 사용되기 때문에 파라미터로 계속 넘겨줘야 한다는 점이나, users와 deck이라는 도메인 로직이 controller에서 활동하는 것이, 도메인과 컨트롤러가 서로 분리되지 않았다는 생각이 들어, Controller와 Game으로 분리하고, view의 호출은 함수형 인터페이스를 활용하도록 하였습니다. 이렇게 분리하고보니 컨트롤러가 "뷰와 도메인의 연결다리" 역할을 제대로 하고 있다는 생각이 들어 괜찮은 것 같은데, 이 부분이 괜찮은지 한번 여쭙고 싶습니다 😅

혹시라도 추가적으로 하시고 싶은 말씀 혹은 피드백 있으시면 DM이나 코멘트 남겨주시면 감사하겠습니다!!

2022-03-15 14:13 UTC, ksy90101 commented on src/main/java/blackjack/domain/card/Deck.java
> +                .collect(Collectors.toList());
stream의 stream은 결국 for문안에 for문이 아닐까요?
헷갈린다면 위의 코드를 for문으로 변경해보세요 :)

2022-03-15 23:48 UTC, ksy90101 commented on src/main/java/blackjack/controller/BlackJackController.java
> +            user -> () -> inputView.inputWhetherToDrawCard(UserDto.fromEvery(user)),
오오 👍

2022-03-15 23:54 UTC, ksy90101 approved these changes
안녕하세요 :) 차리 리뷰어 럿고입니다.
피드백 적용하시느라 너무 고생 많으셨습니다 💯 
1단계 블랙잭은 이만 머지할게요~
2단계때 뵙겠습니다!

2022-03-15 23:54 UTC, ksy90101 commented on src/main/java/blackjack/domain/card/Score.java
> +    }
이건 상수로 관리하면 더 좋지 않을까요?

2022-03-15 23:54 UTC, ksy90101 commented on src/main/java/blackjack/dto/MatchRecordDto.java
> +            .collect(Collectors.joining(" "));
매직스트링!

2022-03-15 23:54 UTC, merged