[1단계 - 블랙잭] 파랑(이하은) 미션 제출합니다.
woowacourse/java-blackjack pull request #260
Opened 2022-03-11 08:18 UTC by summerlunaa

안녕하세요! 파랑입니다. 블랙잭 미션 제출합니다.

블랙잭 구현하면서 궁금했던 점 질문 드립니다!

1. 객체를 감싸고 감싸고 하다보니 getter를 너무 많이 쓰는 것 같아서 고민입니다.

Controller에서 `players`, `dealer`를 많이 사용하게 되는데 `players`를 사용하려면 `BlackjackGame` -> `Participants` -> `players` 이렇게 2번의 getter를 사용하게 됩니다. 

우선은 `blackjackGame.getParticipants.getPlayers()`와 같이 사용하는 것을 피하기 위해서, 아래 코드처럼 `BlackJackGame`에서 바로 `participants`의 `players`를 가져올 수 있도록 `getPlayers` 메서드를 생성해 놓았습니다.
이런 식으로 사용하는 것이 좋은 방법일까요? 

그렇다고 `Participants`를 `BlackjackGame`에서 빼기에는 참가자들은 블랙잭 게임의 인스턴스가 되는 게 맞는 것 같아서ㅠㅠ 다른 더 좋은 방법이 있는지 궁금합니다.

```java
// BlackJackGame

    public Participants getParticipants() {
        return participants;
    }

    public Dealer getDealer() {
        return participants.getDealer();
    }

    public List<Player> getPlayers() {
        return participants.getPlayers();
    }
```

2. 상속 테스트
현재 `Dealer`와 `Player`가 `Participant`를 상속하고 있는데 이런 경우 부모 클래스에 있는 메서드는 어떻게 테스트 해야하나요? 딜러와 플레이어 둘 다 테스트 하기엔 같은 메서드를 중복으로 테스트하는 것 같아서 우선 플레이어 테스트에만 테스트를 구현했습니다. 찾아보니 Mock 객체라는 것이 있는데 이런 방법을 사용해서 테스트하는 것이 좋을까요?

감사합니다!!

2022-03-12 08:50 UTC, ddu0422 requested changes
안녕하세요 파랑 :) 블랙잭 미션 잘 구현해주셨어요 ㅎ_ㅎ
코드가 깔끔해서 읽기 편했네요 💯 
간단한 코멘트 남겨드렸어요. 확인해주시면 감사하겠습니다 😄 
애매한 부분이 있거나 궁금한 부분이 있다면 언제든지 코멘트 달아주시거나 DM 주세요 !

## Q&A
> 객체를 감싸고 감싸고 하다보니 getter를 너무 많이 쓰는 것 같아서 고민입니다.

이 부분은 저도 항상 고민하고 있지만, getPlayers와 같은 메서드를 생성하는 방식도 괜찮다고 생각해요 !

> 상속 테스트

상위 클래스에 있는 내용은 상위 클래스에서만 테스트하고 하위 클래스에서 확장한 부분이나 Override 한 부분은 하위 클래스에서 테스트하면 되지 않을까요 ?_?

Mock은 현재 사용안하셔도 충분히 테스트가 가능할 것 같아요 ㅎ_ㅎ

2022-03-12 08:50 UTC, ddu0422 commented on src/main/java/blackJack/domain/card/Deck.java
> +    private final LinkedList<Card> deck;
LinkedList를 사용하는 것보다 적절한 자료구조는 없을까요?

2022-03-12 08:50 UTC, ddu0422 commented on src/main/java/blackJack/domain/participant/Dealer.java
> +    }
딜러는 처음에 받은 2장의 합계가 16점 이하이면 1장을 무조건 받아야하고 17점 이상이라면 카드를 받을 수 없는 규칙이죠 !
딜러에게 턴이란 개념이 있을까요 ?_?

2022-03-12 08:50 UTC, ddu0422 commented on src/main/java/blackJack/domain/participant/Participant.java
> +    }
해당 메서드의 위치만 사용한 순서와 다르군요 !_!

2022-03-12 08:50 UTC, ddu0422 commented on src/main/java/blackJack/domain/participant/Participant.java
> +            countAce--;
💯  💯

2022-03-12 08:50 UTC, ddu0422 commented on src/main/java/blackJack/domain/participant/Player.java
> +    }
꼼꼼한 체크 👍🏻

2022-03-12 08:50 UTC, ddu0422 commented on src/main/java/blackJack/domain/result/BlackJackGameResult.java
> +public class BlackJackGameResult {
WinOrLose가 Player 입장에서 승리 여부를 판단하는 것보단 Player와 Dealer가 승리판별여부 내용을 가지고 있는건 어떨까요?

2022-03-12 08:50 UTC, ddu0422 commented on src/main/java/blackJack/domain/result/WinOrLose.java
> +public enum WinOrLose {
WinOrLose이지만 실제로는 DRAW도 있군요! 적절한 네이밍으로 변경해보는건 어떨까요?

2022-03-12 08:50 UTC, ddu0422 commented on src/main/java/blackJack/domain/result/WinOrLose.java
> +    }
해당 메서드명만 보고는 누가 이기고 졌는지 파악하기 힘들겠네요 😭

2022-03-12 08:50 UTC, ddu0422 commented on src/main/java/blackJack/domain/result/YesOrNo.java
> +    }
해당 메서드 테스트가 필요하지 않을까요?

2022-03-14 08:02 UTC, summerlunaa commented on src/main/java/blackJack/domain/participant/Participant.java
> +    protected MatchResult getMatchResult(int otherParticipantScore) {
해당 메소드는 Dealer와 Player의 `calculatePlayerMatchResult`에서만 사용하는 메소드입니다. 중복적으로 사용되는 메서드라 부모 클래스인 Participant에 구현해놓았습니다. 

그런데 이 메소드는 단독으로는 사용하면 안 되고 꼭 `calculatePlayerMatchResult` 내에서 사용되어야 합니다ㅠㅠ `getMatchResult` 메소드만으로는 정확한 승부 결과를 반환할 수 없거든요.. 

그래서 자식 클래스에서는 사용할 수 있으면서, 외부에서는 접근할 수 없도록 `protected` 접근 제어자를 사용했는데, 이렇게 사용해도 괜찮을까요?

`protected` 접근 제어자를 한 번도 사용해본 적이 없어서 혹시 사용했을 때 어떤 문제가 있을지 궁금합니다! 나중에 앱이 커지면서 상속관계가 깊어지고 더 복잡해지는 경우에 문제가 생길까요?

2022-03-14 08:02 UTC, summerlunaa commented on src/main/java/blackJack/domain/card/Deck.java
> +    private final LinkedList<Card> deck;
Queue로 변경하였습니다!

2022-03-14 08:02 UTC, summerlunaa commented on src/main/java/blackJack/domain/participant/Dealer.java
> +    }
메소드 이름에 게임 용어가 적용되지 않은 것 같아 전체적으로 메소드 이름을 게임 용어에 맞게 변경하였습니다!

2022-03-14 08:03 UTC, summerlunaa commented on src/main/java/blackJack/domain/result/BlackJackGameResult.java
> +public class BlackJackGameResult {
Player와 Dealer에게 승리판별여부를 묻는 것이 더 좋은 것 같아서 수정하였습니다!

2022-03-14 08:04 UTC, summerlunaa commented on src/main/java/blackJack/domain/result/WinOrLose.java
> +    }
Player와 Dealer에게 승리판별여부를 묻는 것으로 수정하면서 해당 문제가 해결되었습니다ㅎㅎ

2022-03-14 08:06 UTC, summerlunaa reviewed
리뷰 반영하였습니다! 질문 한 가지 달아놓았습니다ㅎㅎ

2022-03-14 16:00 UTC, ddu0422 approved these changes
안녕하세요 파랑 :) 1단계 빠르게 반영해주셨군요 !!
간단한 코멘트 남겨드렸으니 확인해주시면 감사하겠습니다 :)
1단계 진행하시느라 고생많으셨어요 !! 2단계도 화이팅이예요 🔥

2022-03-14 16:02 UTC, merged