[1단계 - 블랙잭] 페퍼(최수연) 미션 제출합니다.
woowacourse/java-blackjack pull request #270
Opened 2022-03-11 08:32 UTC by SuyeonChoi

안녕하세요 에단! 저는 페퍼입니다 😊😊
이번 블랙잭 미션 잘 부탁드려요!

2022-03-11 09:11 UTC, SuyeonChoi commented on src/main/java/blackjack/domain/gamer/Dealer.java
> +    }
자식 클래스인 `dealer`에서는 16이하인 경우에만 카드를 추가하기 위해 부모의 메서드를 재정의하였습니다. 이때, 조건을 확인한 뒤 다시 카드를 추가하는 행위를 수행하기 위해 재정의 대상인 부모메서드를 사용하였습니다. 그런데 메서드를 부모와 다른 방식으로 사용하기 위해 재정의를 한다고 생각하는데 해당 방식이 자연스러운지 의심스럽습니다..
`overriding 메서드에서 overridden 메서드를 사용하면 안된다!` 라는 정보를 찾지 못해 사용해보았는데 에단은 어떻게 생각하시나요..?

2022-03-11 09:11 UTC, SuyeonChoi commented on src/main/java/blackjack/dto/DealerResultDto.java
> +    private final int drawCount;
DTO는 View에 값을 전달하기 위한 객체로 캡슐화가 필요하지 않다고 생각하여 인스턴스 변수를 3개 이상 선언하였습니다. DTO에도 `인스턴스 변수를 2개 이하로 제한` 원칙을 적용해야 할까요?

2022-03-11 14:14 UTC, Laterality requested changes
안녕하세요 페퍼, 리뷰어 에단입니다 :)

질문 주신 부분과 몇군데에 추가로 코멘트를 남겨드렸어요. 확인 부탁드릴게요.

2022-03-11 14:14 UTC, Laterality commented on src/main/java/blackjack/view/OutputView.java
> +        stringBuilder.append(gamerCardsResultDto.getGamerCardsDto().getName()).append(": ");
메서드 대신 지역 변수로 분리해보면 어떨까요?

2022-03-15 07:14 UTC, SuyeonChoi reviewed
에단 피드백 감사합니다👍👍
리뷰 반영과 함께 코멘트를 남겼습니다!
확인 부탁드릴게요😊

2022-03-15 07:14 UTC, SuyeonChoi commented on src/main/java/blackjack/domain/card/property/CardProperty.java
> +    private final CardNumber number;
`CardProperty`에서는 카드의 모양과 숫자에 관련된 로직을 처리하고, `Card`에서는 현재 카드의 공개 여부 로직을 구분해서 처리할 수 있습니다. 
현재까진 각각의 클래스가 하나로 합친 것보다는 엔티티를 작게 유지할 수 있다는 장점이 있습니다. 
하지만 추후에 만약 기능이 추가된다면, 카드의 고정된 속성은 `CardProperty`에서, 카드의 상태와 관련된 로직은 `Card` 클래스에서 처리하여 높은 응집력을 유지할 수 있을거 같아요.

2022-03-15 07:28 UTC, SuyeonChoi commented on src/main/java/blackjack/domain/gamer/Gamer.java
> +    }
에단의 코멘트를 보고 다시 한번 코드를 살펴보니 꼭 필요하지 않는 `getCardGroupSum`은 제거하고 다른 메서드 두개는 구체적인 네이밍으로 리팩토링하였습니다!

- `getMaxCardGroupSum()` ➡️ `getSumWithMaximumAce()`
  - ACE를 무조건 11로 카드의 합을 계산
  - 딜러가 카드를 뽑을 수 있는지 확인할 때, 딜러 및 플레이어의 최종 점수 계산 시 사용
- `getCardGroupScore()` ➡️ `getFinalScore()`
  - 21과 최대한 가깝게 이득이 되는 경우로 ACE의 값을 1과 11 중 선택하여 카드의 합을 계산

2022-03-15 14:50 UTC, Laterality requested changes
안녕하세요 페퍼,

코드는 전반적으로 깔끔하게 작성하셔서 특별히 피드백 드릴 곳이 많지 않네요 💯 

질문 주신 곳과 몇군데에 추가로 코멘트를 남겨드렸으니 확인 부탁드려요.

코드를 통해 해결해야 하는 도메인(문제 영역)이 복잡할수록 도메인의 용어를 일관되게 사용하는 것 또한 굉장히 중요한데요. 블랙잭에서는 어떤 용어와 지식들이 등장하는지, 이 용어들을 코드에 어떻게 드러낼 수 있을지 고민해보시면 좋겠어요.

2022-03-15 14:50 UTC, Laterality commented on src/main/java/blackjack/domain/card/CardGroup.java
> +    private boolean isReducingAceNumberBeneficial(int score, int aCount) {
어떤 조건을 나타내는지 더 쉽게 나타낼 수 있는 이름은 없을까요?

2022-03-17 14:02 UTC, SuyeonChoi reviewed
에단 자세한 리뷰 정말 감사해요! 많은 내용을 배울 수 있었습니다😊 
리뷰를 최대한 반영해보았고 고민한 점을 코멘트로 남겼습니다.
확인해주시면 감사하겠습니다〰️


> 한가지 아쉬운 점은 비교 결과(점수의 대소관계)에 따라 정수가 반환되고 있어서 반환값을 사용하는 클라이언트 입장에서는 이 정수가 무엇을 의미하는지 직관적으로 알기 어렵다는 것인데요. 상황에 따라 비교를 어떤 방식으로 하면 좋을지에 관해서는 다른 크루에게 남겨드렸던 코멘트를 참고해보시면 도움이 되겠어요. 만약, 이 메서드가 비교 결과를 정수 대신 Match로 반환한다면 어떨까요?

이 부분엔 코멘트가 안달리네요! 
리뷰를 참고해서 Match 타입으로 반환했습니다. 꼼꼼한 리뷰 감사해요 에단!!👍👍

2022-03-18 12:54 UTC, Laterality approved these changes
안녕하세요 페퍼, 잘 반영해주셨어요 👍 

이번 미션은 여기서 머지하도록 할게요. 

몇가지 간단한 코멘트를 남겨드렸는데, 다음 단계 진행하시면서 참고해주세요.

사용자와 상호작용하는 부분이 중간중간에 들어있다보니 게임을 진행하는 메서드들이 작은 단위로 노출되는 것으로 보여요. 어떻게 하면 이런 메서드를 모두 노출할 필요 없이 한두 개 정도의 메서드로 게임을 진행할 수 있을지도 고민해보시는 것도 좋겠어요.

1단계 고생 많으셨습니다. 다음 단계에서 뵐게요 :)

2022-03-18 12:54 UTC, Laterality commented on src/main/java/blackjack/controller/BlackJackController.java
> +    private void requestCardAddition(Player player) {
블랙잭이라는 현실 세계의 문제를 코드로 나타내 해결하는 것인 만큼, 도메인(블랙잭)의 지식이나 용어를 코드에 잘 드러내는 것이 다른 동료들과 문제에 관해 소통할 때도 유리하고, 복잡한 문제를 해결해야 하는 경우에는 중요한 힌트가 되기도 합니다.

문제를 코드로 해결하기에 앞서 문제와 관련된 지식이나 용어들을 살펴보고 이를 어떻게 코드로 나타낼 지 고민해보는 것도 좋은 경험이 될 수 있어요 :)

2022-03-18 12:54 UTC, Laterality commented on src/main/java/blackjack/controller/BlackJackController.java
> +    private void requestStatus(Player player) {
무엇을 하는 메서드인자 더 잘 나타낼 수 있는 이름이 있을까요?

2022-03-18 12:54 UTC, Laterality commented on src/main/java/blackjack/domain/BlackJack.java
> +public class BlackJack {
이 클래스가 블랙잭 게임의 전체적인 흐름을 관리할 거라 생각했는데, (카드를 추가하거나 딜러의 카드를 오픈하는 등)게임의 진행과 관련된 메서드가 외부에 많이 노출돼 있네요. 무엇이 메서드를 외부로 노출하게 만드는 걸까요?

2022-03-18 12:54 UTC, Laterality commented on src/main/java/blackjack/domain/card/Card.java
> +    public static Card of(CardShape shape, CardNumber number, boolean isOpen) {
복사를 위한 메서드라면 팩토리 대신 `card.copy()` 형태로 새 인스턴스를 반환하면 어떨까요?

2022-03-18 12:54 UTC, Laterality commented on src/main/java/blackjack/domain/gamer/PlayerGroup.java
> +    public Map<String, Match> getPlayerResult(int sum) {
딜러의 점수를 받아 각 플레이어들과 점수를 비교해 결과를 계산하는 메서드인데, 이름으로는 이 점을 알기 어려워보여요. 어떻게 하면 이 메서드의 용도와 인자의 역할을 드러낼 수 있을까요?

2022-03-18 12:54 UTC, Laterality commented on src/main/java/blackjack/domain/gamer/Gamer.java
> +    public int getCardsSize() {
테스트에서만 사용되는 메서드네요. 어떻게 하면 이 메서드 없이 원하는 결과를 검증할 수 있을까요?

2022-03-18 12:54 UTC, merged