[1단계 - 블랙잭] 수달(허수진) 미션 제출합니다.
woowacourse/java-blackjack pull request #277
Opened 2022-03-11 08:40 UTC by her0807

## 안녕하세요 스티치,  수달입니다. 🦦 

만나게 되어 영광입니다. 잘 부탁드립니다 !!!
스티치가 제 코드를 이해할 때 도움이 되었으면.. 하는 바람으로 아래와 같이 코멘트를 남겼습니다 🤪 

> 1. 수달이 이해한 블랙잭 요구사항

우선, 블랙잭 게임을 이번 미션을 통해 처음 접하여 맨 처음 도메인 지식을 쌓기 위해 
페어인 매트와 게임을 함께 해보며 [요구사항 도출](https://necessary-sundial-178.notion.site/5ec5744c73ed4522a0631c7794bb6c51)을 먼저 진행했습니다.

> 2. TDD 연습

이번에 코드를 구현하며 Test 코드 작성 후, 비지니스 로직을 생성하고자 노력했습니다. 객체에 어떤 행동이 필요할까 요구사항을 미리 도출한
덕분에 조금 수월하게 할 수 있었던 것 같습니다. 또한 페어인 매트가 ArgumentsProvider 를 활용한 test Data 생성 방법을 알려주어서
새롭게 적용시켜 보았습니다!!!

> 3. Gamer 와 Player, Dealer 를 상속 구조로

도메인을 도출하는 과정에서 `플레이어와 딜러의 행동이 공통점이 많다는 것을 발견`하였습니다. 
공통점을 묶어서 상속화한다면 중복을 제거할 수 있겠다는 생각이 들어 상속 구조를 사용해보았습니다.

> 4. DTO 사용

지난 로또 미션을 하며 View 와 Domain 은 의존 관계를 맺으면 안된다는 것을 배웠습니다. 
따라서 출력에 필요한 데이터만 가공하여 DTO 로 만들었습니다.

> 5. GameResult Enum Class 에 Predicate 활용으로 조건문 제거

승, 무, 패 결과를 계산하기 위해서는 조건문 사용이 불가피 했습니다. 그래서 어떻게하면 조금 더 직관적이게
로직을 수정할 수 있을까 고민하다가 지난 수업 때 배운 Enum value 로 연산값을 넣어보는게 어떨까? 라는 생각에 작성했습니다. 

> 6. Card를 미리 만들어두고 캐싱하여 사용

블랙잭에서 사용하는 52장의 Card 외에 다른 카드는 생성이 안되었으면 좋겠다는 생각에 Card 를 미리 발급해두어 데이터를 만들고
그것을 캐싱해서 사용하도록 Card class 에 Value 값을 만들었습니다. 

---
이번 미션기간 동안 스티치와 즐거운 대화를 나누고 싶습니다. 감사합니다. 👍🏻

2022-03-12 02:30 UTC, her0807 reviewed
지난 미션을 하며 배웠던 점들을 최대한 녹여내고자 했습니다!

올바르게 적용하지 않았거나, 추가적으로 생각해볼 내용이 있다면 의견 남겨주세요.
귀 기울여 듣겠습니다.🤪 👂🏻 

주말에도 귀한 시간 내주셔서 무한 감싸 .. 드립니다.  

코로나 조심하세요 !!

---

<img width="526" alt="스크린샷 2022-03-12 오전 11 30 06" src="https://user-images.githubusercontent.com/26570275/158000361-4f62b144-3462-4863-a52f-481f92ab1322.png">

2022-03-12 02:30 UTC, her0807 commented on src/main/java/blackjack/domain/Deck.java
> +    }
게임 시작 전, 플레이어와 딜러에게 각각 2장씩을 나눠주기 위해서 만든 메서드 입니다.

메서드를 만들지 않고, draw() 를 두번 해줄까? 생각💡 을 하다가,  `명시적으로 시작을 위한 카드 배부를 한다! `라는 것을
메서드 명으로 표현하면 좋겠다고 생각하여 메서드로 추출했습니다.

2022-03-12 02:30 UTC, her0807 commented on src/main/java/blackjack/domain/Denomination.java
> +    }
### ACE 는 1과 11이라는 두 개의 점수를 가지고, 블랙잭(21점)이 되기 위해 유연하게 선택하여 사용이 가능하다. 

이 요구 사항을 위해서 addScore 를 할 때 ACE 의 기본 값을 11로 사용하고, 
블랙잭 점수에 오바되었을 때 (21 이상으로 Bust 라 게임 참여를 하지 못하게 되었을 때)
ACE를 1점으로 사용하게끔 로직을 작성했습니다. 🤓

2022-03-12 02:30 UTC, her0807 commented on src/main/java/blackjack/domain/Gamer.java
> +    abstract GameResult createResult(int targetScore);
### createResult 를 추상 메서드로 만든 이유

현재 Gamer 는 플레이어와 딜러가 공통적으로 해야하는 행위
1. 카드의 총점을 구한다.
2. 카드를 한장씩 받는다.

외에 게임 결과를 구할 때 다른 조건을 가지고 있습니다. 
`둘 다 Bust 일 경우 딜러가 승리한다.`

내부 동작은 다르지만, 이 로직을 반드시 구현해야하기 때문에 구현을 강제하기 위해서 추상 메서드로 구현했습니다.

2022-03-12 02:30 UTC, her0807 commented on src/main/java/blackjack/domain/Name.java
> +    }
## 검증 전 할당
이펙티브 자바 책 내용에서
`멀티 스레딩 환경일 때 객체의 불변을 보장할 수 없다` 
따라서 검증 후 할당을 할 경우 검증이 끝났을 때 값이 변해있을 수 있기 때문에
검증 전 미리 할당을 하고, 할당한 값을 검증해라. 라는 부분을 읽고 의도하여 작성했습니다. 
실무에서도 이렇게 많이 쓰이나요? 🥴

2022-03-12 02:30 UTC, her0807 commented on src/main/java/blackjack/dto/CardDto.java
> +    }
## 올바른 DTO 사용방법

지난 미션 때 리뷰해주신 `핀`  께서 웹 환경에서 통신 할 때를 예를 들어주시며 
뷰에 도메인 비지니스 로직을 노출하지 않고, 불필요한 데이터를 제거 한 후 통신하면 훨씬 안전하다는 것을 근거로
DTO 사용의 필요성을 알려주셨습니다. 

따라서 이번 미션에도 DTO 를 적용 시켜 보았는데요! 

도메인은 DTO 를 알고 있으면 안되지만(가변성 때문에) DTO 는 Domain 을 기준으로 데이터가 생성 되기 때문에 알아도 괜찮지 않을까? 라는 생각에서 `from 이라는 정적 팩토리 메서드`를 사용해서 변환해보았습니다. 제가 잘 이해하고 사용한게 맞을까요?

2022-03-12 07:53 UTC, lxxjn0 requested changes
수달, 안녕하세요. 이번에 블랙잭 리뷰를 맡게 된 스티치입니다 :)

수달의 블랙잭 코드를 보기에 앞서 따로 블랙잭 도메인에 대한 정리를 한 글을 읽어봤습니다!! 도메인에 대한 깊은 이해를 한 부분이 매우 인상깊었어요!! 블랙잭이 처음 구현하기에 규칙도 까다롭고 용어도 다양해서 그에 맞는 코드를 구현하기 어려운데, 수달의 경우 시작하기에 앞서 도메인 이해를 철저히 한 덕분에 코드가 매우 멋있게 작성된 것 같습니다!! 👍🏼 

전체적으로 코드의 수준도 높아서 제가 정말 코멘트 남길 부분이 잘 보이지가 않더군요.. ㅠㅠ 하지만 조금 더 보완하면 좋은 점들, 그리고 객체지향적인 관점에서 조금 확인해보면 좋을 부분에 대해서 코멘트 남겨두었습니다!! :) 한번 확인해보고 리뷰 반영 부탁드릴게요 👍🏼

2022-03-12 07:53 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Card.java
> +    }
static 스코프의 stream 연산에서 활용되는 메서드로 보여지네요. static 스코프의 stream 최종 연산에서 toSet을 하기 때문에 해당 메서드에서는 굳이 toSet을 해 줄 필요는 없을 것 같아요!!
해당 메서드에서 stream을 반환하도록 하면 코드가 좀 더 간결해질 것 같습니다 :)

2022-03-12 07:53 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Card.java
> +        VALUES = Collections.unmodifiableSet(cards);
추가로 Java 8에서는 불변 객체를 만들기 위해 `Collections.unmodifiableXXX` 메서드를 사용해야 했지만, Java 9부터는 `List.of`나 `Set.of`를 사용할 수 있습니다!!
그리고 Collectors에서 제공하는 collectingAndThen을 사용하면 최종 연산의 collecting 결과를 한번 더 가공할 수 있어요!!! 제 코멘트를 한번 참고해서 개선해보면 좋을 것 같아요 :)

2022-03-12 07:53 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Card.java
> +    }
생성자를 private으로 막고 정적 팩토리 메서드를 통해서만 접근하도록 제한한 부분  💯 💯 💯 
추가로 of 메서드의 불필요한 공백은 제거해도 좋을 것 같아요 :)

2022-03-12 07:53 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Card.java
> +    private boolean isSame(Denomination denomination, Suit suit) {
hasSame이란 메서드도 괜찮을 것 같아요!! 이건 저의 제안이라 참고만 해주세요 :)

2022-03-12 07:53 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Cards.java
> +    public void combine(Card card) {
append나 add와 같은 메서드는 어떤가요?? combine이 '본인이 가지고 있는 카드에 새로운 카드를 추가한다'라는 상황에는 조금 어울리지 않는 단어 같아서 한번 제안 드려볼게요 :)

2022-03-12 07:53 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Cards.java
> +    public List<Card> getValue() {
List의 copyOf 메서드를 한번 찾아보고 활용해봐도 좋을 것 같아요!! 👍🏼

2022-03-12 07:53 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Denomination.java
> +public enum Denomination {
도메인에 대한 깊은 이해 덕분에 이렇게 멋진 클래스 이름이 나온 것 같아요!! 굿입니다 👍🏼

2022-03-12 07:53 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Denomination.java
> +    }
해당 메서드는 클래스 메서드가 아닌 인스턴스 메서드로 해결이 가능할 것 같은데 클래스 메서드로 작성한 이유가 있을까요??

2022-03-12 07:53 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Cards.java
> +            totalScore = Denomination.addScore(card.getDenomination(), totalScore);
해당 메서드를 Card에게 넘겨줘서 해결해보면 어떨까요?? Card의 Denomination을 가져와서 연산하는데 Card가 Denomination을 가지고 있으니 Card에게 메시지를 보내도록 해결해도 좋을 것 같아요!! :)

2022-03-12 07:53 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Dealer.java
> +    public boolean isDrawable() {
canHit이란 메서드는 어떨까요?? 블랙잭 도메인에서 '카드를 추가로 더 뽑는 행위를 hit이다'라고 정리해두신 것 같아서 한번 참고해보시면 좋을 것 같아요!!

2022-03-12 07:53 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Dealer.java
> +    }
해당 메서드에서는 score를 직접 받아와서 내부에서 비교를 하고 있습니다. 내부에서 플레이어의 점수가 버스트인지, 아닌지 여부를 판단하는데 이를 조금 더 객체지향적으로 개선해볼 수 있을 것 같아요!! 힌트는 파라미터로 score가 아닌 다른 객체를 가져온다면 isBust와 같은 메서드 등을 추가로 구현해서 더 멋지게 개선이 가능할 것 같네요 :)

2022-03-12 07:53 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Deck.java
> +    }
수달의 의도는 잘 이해했습니다 :) 하지만 조금만 더 객관적으로 Deck이라는 이름은 게임을 진행하기 위한 카드를 관리하는 곳이라고 볼 수 있어요!! 
그렇다면 게임 시작에 플레이어에게 2장의 카드를 배부하는 규칙은 deck이 가져야 하는 규칙일까요 아니면 블랙잭이라는 게임이 가져야 하는 규칙일까요? 객체에 메서드를 준다는 것은 곧 행위를 부여하는 것입니다. 덱이 스스로 첫 번째 턴에 2장의 카드를 뽑는 규칙을 관리하는게 좋을지 아니면 외부에서 블랙잭 규칙을 관리하고 덱은 단순히 게임을 진행하기 위한 카드를 공급하는 용도로 사용하는게 좋을지 한 번 고민해보면 좋을 것 같아요!! 👍🏼

2022-03-12 07:53 UTC, lxxjn0 commented on src/main/java/blackjack/domain/GameResult.java
> +    public static GameResult of(int targetScore) {
of의 파라미터인 targetScore는 of에서 어떠한 값을 전달받아야 할 지 의미가 모호한 것 같아요!! 그리고 GameResult라는 객체가 게임의 승패 여부를 판단하는 로직이라면 매개변수로 판단할 대상의 점수, 비교할 대상의 점수를 같이 받아서 내부에서 해당 값을 연산 후 처리해보면 어떨까요??
of 메서드를 사용하는 사람으로 하여금 더 확실한 메서드를 제공해줄 수 있을 것 같아요!!

2022-03-12 07:53 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Name.java
> +    }
그런 것 같아요!! 해당 부분을 고려하면서 코드를 작성하는 사람도 있고 그렇지 않은 사람도 있지만, 수달처럼 최대한 안전하게 작성할 수 있는 방법을 사용하는 것은 정말 좋은 습관이라 생각합니다 👍🏼 
저도 수달이 작성한 코드처럼 초기화 후 유효성 검사를 진행하도록 코드를 작성하는 편이에요 :)

2022-03-12 07:53 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Player.java
> +    public boolean isPlaying() {
해당 메서드도 canDraw와 같은 메서드이면 더 적절할 것 같아요!!

2022-03-12 07:53 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Gamer.java
> +    protected static final int PLAYING_STANDARD = 21;
해당 스코어는 실질적으로 블랙잭 스코어와 같은 의미를 가진다고 생각해요!! 그렇다면 Denomination에서 사용하는 변수를 public으로 열어서 해당 값을 사용하는 건 어떨까요??

2022-03-12 07:53 UTC, lxxjn0 commented on src/main/java/blackjack/Application.java
> +        players.getValue().forEach(player -> playing(deck, player));
현재 Players 객체는 player 인원에 대한 유효성 검증 이외의 행위는 가지지 않는 것 같아요!! Player를 꺼내서 행위를 시키기 보다는 players 객체에게 해당 행위를 하도록 하는 건 어떨까요??

2022-03-12 07:53 UTC, lxxjn0 commented on src/main/java/blackjack/dto/CardDto.java
> +    }
넵!! 맞습니다 :) 도메인이 dto를 의존하게 된다면 이는 곧 view에 도메인이 의존하는 꼴을 띄게 되죠. 하지만 dto가 도메인을 의존하는 것은 상관이 없어서 이렇게 사용하셔도 좋습니다!!

2022-03-12 07:53 UTC, lxxjn0 commented on src/main/java/blackjack/view/PlayCommand.java
> +public enum PlayCommand {
사용자의 응답을 enum으로 관리한 부분 👍🏼

2022-03-12 07:58 UTC, lxxjn0 commented on src/main/java/blackjack/Application.java
> +    }
앗 제가 이 부분을 조금 더 꼼꼼하게 확인하지 않고 코멘트를 남겨두었네요.. ㅠㅠ 수달이 말씀하신 대로 해당 로직은 view에 의존을 가지게 될 수 밖에 없어서 우선은 application에 위치하는 것이 좋을 것 같아요!! 제가 해당 부분에 대한 로직은 한번 고민해보도록 할게요!! :)

2022-03-13 05:22 UTC, her0807 commented on src/main/java/blackjack/domain/Cards.java
> +            totalScore = Denomination.addScore(card.getDenomination(), totalScore);
오오 ! 메세지를 Card 에게 보내면 Denomination 을 꺼낼 필요가 없겠군요! ㅎㅎㅎ
Denomination이 Enum 클래스라서  내부 값이 상수라는 느낌에 get 해도 괜찮겠다고 생각해서 저렇게 작성했나봐요 🥲 
최대한 메세지를  보내는 연습을 한다고 생각하고 적용해보겠습니다!!

2022-03-13 07:38 UTC, her0807 commented on src/main/java/blackjack/domain/Cards.java
> +    public List<Card> getValue() {
관련 내용을 공부하고 적용해보았습니다 🤓 
- [수달의 방어적 복사vs Unmodifiable vs copyOf 의 차이점
](https://prolog.techcourse.co.kr/studylogs/2089)

2022-03-13 10:35 UTC, her0807 commented on src/main/java/blackjack/domain/Dealer.java
> +    }
스티치 조언을 듣고 코드를 바라보니, 개선점들이 눈에 들어오네요! ㅎㅎㅎ 
얼른 수정하겠습니다.

2022-03-13 10:41 UTC, her0807 commented on src/main/java/blackjack/domain/Deck.java
> +    }
스티치 조언을 듣고 나니 블랙잭이라는 게임을 진행하는 곳에서 가져가야하는 규칙같네요. 👍🏻

2022-03-13 10:54 UTC, her0807 commented on src/main/java/blackjack/domain/Card.java
> +    }
중복으로 toSet 을 하고 있었군요.. ! ㅎㅎ 변경하겠습니다.😵‍💫

2022-03-13 11:03 UTC, her0807 commented on src/main/java/blackjack/domain/Card.java
> +        VALUES = Collections.unmodifiableSet(cards);
스티치가 알려주신 메서드들을 살펴보다가 `Collectors.toUnmodifiableSet` 이라는 기똥찬 친구를 발견했습니다 !!!!

2022-03-13 11:08 UTC, her0807 commented on src/main/java/blackjack/domain/Card.java
> +    private boolean isSame(Denomination denomination, Suit suit) {
Denomination, Suit 두 가지를 비교하여 해당 카드가 있는지 판별하는 로직이라는 점에서
스티치가 제안해주신 hasSame이 더 적절해보이네요 👍🏻

2022-03-13 11:14 UTC, her0807 commented on src/main/java/blackjack/domain/Cards.java
> +    public void combine(Card card) {
List 내부에 add 라는 메서드를 호출해서, 이름이 중복되지 않게 하려고 combine 을 사용했었는데,
add 라는 네이밍이 의도가 더 명확하게 드러나는 것 같아서 수정하겠습니다 !

2022-03-13 11:16 UTC, her0807 commented on src/main/java/blackjack/domain/Denomination.java
> +    }
앗.. 이부분은 실수입니다.. 얼른 고치겠습니다.. ㅠㅠ

2022-03-13 11:29 UTC, her0807 commented on src/main/java/blackjack/domain/Gamer.java
> +    protected static final int PLAYING_STANDARD = 21;
아주 좋아요!

2022-03-13 11:38 UTC, her0807 commented on src/main/java/blackjack/domain/GameResult.java
> +    public static GameResult of(int targetScore) {
`BiPredicate<Integer, Integer>` 를 사용해서 적용해보겠습니다아  😃

2022-03-13 12:13 UTC, her0807 reviewed
스티치  즐거운 주말 보내셨나요! 🥴  🤙🏻 

저는 스티치가  당근 가득한 피드백을 주신 덕분에  
행복한 마음으로 관련 내용들을 공부하고 적용해보며 보냈습니다 ㅎㅎ

ACE 관련해서 에러도 있어서 수정해서 PR 보냅니다. 

이번 피드백도 잘부탁드립니다아. 🙋🏻‍♀️

2022-03-13 12:13 UTC, her0807 commented on src/main/java/blackjack/domain/Gamer.java
> +    abstract boolean canHit();
원래 player 와 dealer 가 카드를 뽑는 메서드명이 각 각 isPlaying, isDrawable 이었는데, 
생각해보니 두 메서드 모두  `(기준만 다르고 )카드를 더 뽑을 수 있는지  판별하는 로직`이기 때문에 이름을 통일해도 괜찮겠다고 
판단하여 상속 구조로 변경하되, 재정의하여 사용하도록 변경했습니다!

2022-03-13 12:13 UTC, her0807 commented on src/main/java/blackjack/domain/Name.java
> +        this.value = value.trim();
`sudal, mat ` 라고 입력하면  앞 뒤 공백이 포함되는 것을 제거하기 위해 
생성자에서 초기화 시 trim() 을 사용하였습니다 😶‍🌫️

2022-03-14 11:37 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Cards.java
> +    }
제가 미처 캐치하지 못한 부분에 대해서도 확인을 해주셨군요 🙇🏼‍♂️

2022-03-14 11:38 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Gamer.java
> +    }
넵!! 동일한 클래스 내에서 중복되는 이름이라면 조금 더 고려해야 할 사항이 많겠지만 다른 클래스 간의 메서드 명 중복은 수달이 말씀하신 부분 정도만 고려해도 충분하다고 생각합니다 :)

2022-03-14 12:12 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Cards.java
> +    private int ConvertCloseBlackJack(int totalScore) {
메서드 명이 대문자로 시작해요 😨

2022-03-14 12:18 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Dealer.java
> +    }
오버라이딩한 메서드의 경우 위에 `@Override` 어노테이션을 붙이면 가독성이 더 좋아질 것 같아요!! :)

2022-03-14 12:19 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Deck.java
> +    }
유효성 검증 good 👍🏼

2022-03-14 12:24 UTC, lxxjn0 commented on src/main/java/blackjack/view/OutputView.java
> +                .collect(joining(", "));
`", "` 값은 여러번 사용되는 것으로 보이는데 상수로 추출하는 건 어떨까요??

2022-03-14 12:26 UTC, lxxjn0 commented on src/test/java/blackjack/domain/AceIncludeCardsArgumentsProvider.java
> +public class AceIncludeCardsArgumentsProvider implements ArgumentsProvider {
ArgumentProvider 사용 👍🏼

2022-03-14 12:27 UTC, lxxjn0 commented on src/test/java/blackjack/domain/AceIncludeCardsArgumentsProvider.java
> +public class AceIncludeCardsArgumentsProvider implements ArgumentsProvider {
추가로 이렇게 테스트에서 사용되는 유틸리티성 클래스들의 경우에는 테스트 내에서도 따로 패키지를 나눠서 관리해주면 코드를 읽을 때 더 편할 것 같아요 :)

2022-03-14 12:33 UTC, lxxjn0 commented on src/test/java/blackjack/domain/PlayerArgumentsProvider.java
> +                arguments(List.of(new Player("stitch", CardsTestDataGenerator.generateCards()),
🤩

2022-03-14 12:35 UTC, merged

2022-03-15 03:17 UTC, her0807 commented on src/main/java/blackjack/domain/Cards.java
> +    private int ConvertCloseBlackJack(int totalScore) {
😨 😨 😨 😨 😨 😨 😨

2022-03-15 03:32 UTC, her0807 commented on src/main/java/blackjack/domain/Cards.java
> +    }
홉!! 아주 좋은 의견이네요 스티치 !!! 

이해하기 쉽게 설명해주신 덕분에 코드를 조금 더 효율있게 작성할 수 있을 것 같아요 👍🏻

2022-03-15 05:33 UTC, her0807 commented on src/main/java/blackjack/Application.java
> +        Players players = createPlayers(deck);
@lxxjn0 

흐름이 느껴질 수 있게 코드를 작성하라! (직관적으로 코드를 파악하기 수월하게 ~ )

스티치가 설명해주신 부분을 시도해보고 장단점을 느껴보고자 합니다 👍🏻 
그런데 위에 설명해주신 흐름대로 코드를 작성하려면, `Cards 에 대해 Set 을 진행해야할 것 같은데.. `
set을 만들어두게되면, 변경 가능성이 커지는 상황이라 우려되는 점이 많아지네요 .. !
혹시 set 말고 다른 방법으로도 할 수 있을까요 ?

2022-03-15 12:08 UTC, lxxjn0 commented on src/main/java/blackjack/Application.java
> +        Players players = createPlayers(deck);
베팅 금액을 예시로 들어주니 약간 고민이 되긴 하겠네요.. 수달이 말씀해주신 예시를 생각해보면서, 제가 '왜 플레이어를 생성하는 시점에 2장의 카드를 주는게 어색하다고 느꼈을까?'를 한번 같이 고민해봤어요. 

첫 번째로는 카드를 뽑는 행위가 처음에만 하는 행위가 아니라는 점에서 어색함을 느꼈던 것 같아요. 처음 2장의 카드를 뽑는 행위도 결국 플레이어가 게임에서 카드를 뽑는 행위가 아닌가? 하는 생각이 들었던 것 같아요. 

두 번째로는 플레이어를 생성할 때 생성자로 전달하는 2장의 카드가 생성 시점의 플레이어 속성이라고 봐야하나? 라는 생각도 들었던 것 같아요. 말씀하신 배팅 금액의 경우 처음 플레이어의 값이 된 이후 변경이 없는 것으로 알고 있어요. 그런 성격 탓에 플레이어를 생성할 때 같이 배팅 금액을 전달해서 생성하더라도 '이는 플레이어가 가지고 생성될 만한 특성이 아닐까?' 라는 생각이 들었어요. 카드는 게임 진행 과정 중에서도 계속 변하는 속성이다보니 생성과 동시에 초기화를 해야하나? 라는 생각이 들었던 것 같아요!!

그런데 위 두 가지 이유가 '생성자에서 2장의 카드를 가지고 생성한다'라는 로직이 어색하다라고 주장하기엔 부족한 것 같아요. 지금 다시 생각해보니 제가 느끼기에? 어색하다고 느껴졌던 것 같네요... ㅠㅠ

해당 피드백은 수달이 한번 읽어보고 본인이 생각하기에 적절한 방향으로 한 번 고민해봐도 좋을 것 같아요!! :)

2022-03-15 12:17 UTC, her0807 commented on src/main/java/blackjack/Application.java
> +        Players players = createPlayers(deck);
@lxxjn0 

해당 내용에 대해서 스티치 의견을 들어보니 머릿속에 퍼져있던 생각이 한결 정리되는 느낌이네요 🤓 

제가 맨처음 두 장을 플레이어에게 주고 시작했던 이유는 2장을 받는 것은 `플레이어 의지와 상관없이 
무조건 두장을 받은 뒤 플레이어가 받을지 말지 의사결정을 하기 때문에 ` 이부분은 생성시점에 주어도 괜찮겠다고
판단하여 작성했던 로직입니다. ㅎㅎ ㅠㅠ  스티치 관점에서 어색하다고 느꼈다면 분명 개선의 여지가 있는 코드 같아요. 

 `흐름` 에 집중해서 리팩토링해보겠습니다. 의견 감사합니다. ☺️