[1단계 - 블랙잭] 범고래(조충범) 미션 제출합니다.
woowacourse/java-blackjack pull request #284
Opened 2022-03-11 08:48 UTC by cndqjacndqja

안녕하세요 카일~! 범고래입니다 😊
잘 부탁드립니다!.

코드를 보면서 왜 이렇게 작성했는지 궁금해 하실 것 같은 부분들에 대한 제 생각도 적어 보았습니다!
그리고 아래와 같은 방식으로 생각한 것이 괜찮은지도 궁금합니다.

--- 
### 추상 클래스, 인터페이스를 사용하지 않은 이유

Dealer와 Player가 하는 역할이 거의 흡사하여 재정의 하는 것이 중복된 코드를 만드는 것 같아 사용하지 않았습니다. 

클래스 상속을 사용하면서 명확한 단점을 느끼며 인터페이스 or 추상 클래스를 사용하는 것으로 변경되는 과정이 더 배울 점이 많다고 생각했습니다. 초기에는 중간에 변경될 것으로 예상했으나 1차 PR을 보내기 전까지 명확히 느끼지 못하여 아직 수정되지 않았습니다. 아마도 리팩토링 기간을 거치면서 좀 더 공부한 후, 좀 더 명확한 이유와 생각을 가지고 수정하는 것을 목표로 생각하고 있습니다!

---
### BlackJackGame에서의 역할이 너무 많은가 고민하고 있습니다.

**1. `BlackJackGame` 에서 현재 사용자 이름 중복 체크** 
→ 아마 Player를 관리하는 Players 클래스를 만들어 역할과 책임을 옮겨줄 것 같습니다.

**2. 플레이어, 딜러에게 카드 나눠주기** 
→ 이 부분은  Cards(카드들을 관리하는 클래스)라는 클래스를 만들어 플레이어와 딜러가 각자 관리하게 수정해서 역할과 책임을 분리할지 고민 중에 있습니다.

**3. 플레이어, 딜러, 카드뭉치를 전부 가지고 있습니다.** 
→ 현재 BlackJacjGame에는 세 개의 필드를 가지고 있습니다. 필드만 보더라도 해당 클래스가 역할과 책임을 분리하는 것이 좋을 것 같다는 의심이 드는데 이런 방식으로 문제를 인식해 보는 것이 적당할까요?? 아니면 설계부터 놓치는 부분이 있었던 것일까요? 카일의 생각은 어떤지 궁금합니다.

---

카일은 제 코드를 리뷰해 주실 때, 어떤 흐름으로 체크하시는지 궁금합니다!
ex). 각 객체의 책임과 역할을 파악한 후, 내부 구현은 어떻게 되어있는지 확인하시나요??
만약 카일 방식대로 전체적인 코드를 체크하셨다면, 어떤 부분이 가장 부족했을지도 궁금합니다.

2022-03-12 16:29 UTC, KIMSIYOUNG requested changes
안녕하세요 범고래!
어려운 미션인데 잘 구현해주셨네요.
고민해볼만한 것들에 대해 피드백 남겼으니 확인 부탁드려요.

카일은 제 코드를 리뷰해 주실 때, 어떤 흐름으로 체크하시는지 궁금합니다!
- 어플리케이션이 동작하는지 확인하고 프로그램 시작점에서 부터 흐름대로 쭉 읽어가는 것 같아요. 그 과정에서 어떤 객체와 협력하는지 의존관계는 어떤지 주로 보는 것 같습니다. 제가 느끼기엔 현재 구조에서 `BlackJackGame`과 `DTO` 두가지 없이 구현해보는 것이 우선되는 것 같아서 코멘트 남겨두었습니다🙂

2022-03-12 16:29 UTC, KIMSIYOUNG commented on src/main/java/blackjack/domain/gamer/Gamer.java
> +public class Gamer {
여기서 처음 남겨주신 내용에 대해서 조금 더 이야기해보면 좋을 것 같습니다. 

전체적으로 좋은 방향으로 생각해나가시는 것 같아요🙂 그렇다면 조금 더 나아가서 `Gamer`라는 클래스를 딜러와 플레이어가 각각 상속하는 이유는 무엇인가요? 상속과 조합에 대해서도 고민해보면 좋을 것 같아요.

2022-03-12 16:29 UTC, KIMSIYOUNG commented on src/main/java/blackjack/domain/BlackJackGame.java
> +public class BlackJackGame {
각기 다른 도메인들의 호출순서를 결정하고 뷰와 연결해주는 `Controller`만 있어도 될 것 같아요. 

해당 클래스 없이 `Controller`만 사용해서 구현해볼 수 있을까요?

2022-03-12 16:29 UTC, KIMSIYOUNG commented on src/main/java/blackjack/domain/result/BlackJackResult.java
> +public enum BlackJackResult {
블랙잭인 경우가 포함되어있지 않은 것 같아요.🙂

2022-03-12 16:29 UTC, KIMSIYOUNG commented on src/main/java/blackjack/domain/BlackJackGame.java
> +    private final CardFactory cardFactory;
3번에서 문의주신 내용에 대해서 얘기해보면 좋을 것 같아요.

필드가 많다는 것은 분명 역할분리의 신호가 될 수 있고, 이를 통해 파악하는 것도 매우 현명한 방법이에요. 설계부터가 잘못되었는가는 사실 처음부터 판단하기는 쉽지 않아요. 개발하면서 분명 도메인지식과, 구현방법에 대해서는 더 나은 방법이 나오기 마련이고 그렇기 때문에 개발하면서 계속 리팩토링하는 것이 일반적이라고 생각해요. 
TDD 사이클(실패 > 성공 > 리팩토링)처럼 코드 전체에 대해서도 (실패 > 성공 > 리팩토링)이 반복되는 형태가 일반적인 것 같아요🙂   

다만 블랙잭 미션에서 현재 클래스와 DTO를 제외하고 `Controller`에서 게임의 흐름을 충분히 제어할 수 있을 것 같아요.

2022-03-13 16:40 UTC, cndqjacndqja commented on src/main/java/blackjack/domain/card/Card.java
> +        CARDS = Arrays.stream(CardShape.values())
처음 Card가 여러 클래스에서 호출이 될 것이라 예상하여 캐싱 후, 정적 팩토리 메서드로 캐싱된 객체를 불러오는 방식으로 코드를 작성했습니다.
하지만 리팩토링 과정에서 코드를 보니, Card가 처음 생성되어 저장 후 다시 생성될 일이 없어 Card에서 생성하는 것을 제거했습니다.

하지만 이러한 이유 이외에 카일이 말씀하신 것은 Card, Deck 중에 어느 곳에서 카드 리스트가 생성되어야 적절한지 여쭤보신 것 같아서 그에 대한 답변을 드리자면.

Deck 객체가 생성될 때, 카드 리스트를 생성하여 저장하기 때문에 Card에서 생성된 것을 불러오는 것이 아닌, Deck에서 생성하여 저장하는 방식이 더 적절하다고 생각했습니다.

2022-03-13 16:42 UTC, cndqjacndqja commented on src/main/java/blackjack/domain/card/CardFactory.java
> +    public CardFactory(List<Card> deck) {
네 저도 Factory라는 이름 보다는 Deck이라는 이름이 더 적절한 것 같아서 수정했습니다 😊

2022-03-13 16:48 UTC, cndqjacndqja commented on src/main/java/blackjack/controller/dto/GamerDto.java
> +    public List<Card> getCards() {
제가 질문을 정확히 이해한 것인가 싶어서 리팩토링 과정에서의 제 생각을 적어보았습니다.

<img width="388" alt="image" src="https://user-images.githubusercontent.com/48307960/158069839-b8fe76c6-da4d-4be0-bac0-7120afa406e9.png">
첫 번째로 Dealer의 카드를 보여줄 때만 한장만 보여준 후, 나머지는 전체를 보여주는 것을 보고 이것은 도메인 영역 보다는 View의 영역이라고 생각했습니다. 
때문에 도메인에서 getFirstCard를 제거한 후, View에서 딜러의 첫 번째 카드를 보여주는 방식으로 수정했습니다.

혹시 이 생각이 카일이 말한 것과 같은 뜻일까요??

2022-03-13 17:05 UTC, cndqjacndqja commented on src/main/java/blackjack/domain/gamer/Gamer.java
> +public class Gamer {
조합을 사용했을 경우, 결국에 딜러, 플레이어에서 각각 gamer.getCards()을 사용하는 등, 중복 코드가 많이 발생할 것이라 생각하여 이 경우에는 이점을 느끼지 못했습니다.

우선 딜러와 플레이어가 Gamer를 상속했던 이유는 모든 딜러와 플레이어는 게이머(이 관계를 IS-A관계라고 이해했습니다.)이고 이들 간에 상속 관계를 가지게 되면 상위 클래스의 코드를 재사용하여 중복을 줄여줄 수 있다고 생각했습니다. 하지만 상속의 경우 하위 클래스가 상위 클래스에 종속되기 때문에, 상위 클래스에서의 수정이 일어나면 모든 하위 클래스에도 영향을 끼치기 때문에 어떤 관계인지 잘 생각하고 사용해야 할 것 같습니다.

제가 이해한 대로 적어 보았는데, 혹시 제가 놓친 부분이 어떤 것이 있을까요?

2022-03-13 17:12 UTC, cndqjacndqja commented
안녕하세요 카일!
꼼꼼한 리뷰 정말 감사드립니다 😊
피드백 주신 내용 반영한 후, 다시 리뷰 요청 드립니다!

2022-03-14 11:46 UTC, KIMSIYOUNG commented on src/main/java/blackjack/domain/card/Card.java
> +        CARDS = Arrays.stream(CardShape.values())
좋은 관점인 것 같습니다🙂 결국 만들어내는 카드뭉치는 블랙잭에서 사용할 덱을 만드는 것이기 때문에 `Card`보단 `Deck`에 있는 것이 자연스러운 것 같아요.

2022-03-14 12:27 UTC, KIMSIYOUNG requested changes
안녕하세요 범고래! 
많은 부분을 반영해주셨네요. 
조금 더 고민해보면 좋을 것들 남겨두었습니다. 
확인 부탁드려요!

2022-03-14 12:27 UTC, KIMSIYOUNG commented on src/main/java/blackjack/domain/card/Deck.java
> +        return Arrays.stream(CardShape.values())
요렇게 하면 new LinkedList가 없어도 될 것 같아요.

```java
Arrays.stream(CardShape.values())
                .flatMap(shape -> Arrays.stream(CardNumber.values())
                        .map(number -> new Card(shape, number))
                )
                .collect(Collectors.toCollection(LinkedList::new))

```

2022-03-14 12:27 UTC, KIMSIYOUNG commented on src/main/java/blackjack/domain/gamer/Gamers.java
> +    public static final int INIT_DISTRIBUTION_COUNT = 2;
2장이라는 값과, `Gamer`에 있는 21이라는 값이 어디에서 관리하는 것이 나을까요?

2022-03-14 12:27 UTC, KIMSIYOUNG commented on src/main/java/blackjack/domain/gamer/Gamers.java
> +    public Player findPlayerByName(String name) {
플레이어들을 반복문 돌면서 카드를 분배하거나, 추가 카드를 받거나 할 수 있을 것 같은데 이름 기반으로 찾아와서 반복문 도는 이유가 있을까요?

2022-03-14 12:27 UTC, KIMSIYOUNG commented on src/main/java/blackjack/domain/gamer/Gamers.java
> +        return !player.canDraw();
`뽑을 수 없는` 이라는 것이 `버스트`와 동일하게 사용될 수 있을까요?

동일하게 사용될 수 있더라도, 조금 더 버스트의 의미를 살릴 수 있도록 메소드를 추가해보는 건 어떨까요?

2022-03-14 12:27 UTC, KIMSIYOUNG commented on src/main/java/blackjack/view/OutputView.java
> +            System.out.printf("딜러는 16이하라 %d장의 카드를 더 받았습니다.\n\n", count);
요 부분 오류가 있는 것 같아요! 확인해주세요~

2022-03-14 12:27 UTC, KIMSIYOUNG commented on src/main/java/blackjack/domain/Answer.java
> +    private static final String INVALID_VALUE_ERROR = "입려값이 y 또는 n이 아닙니다.";
오타!

2022-03-14 12:27 UTC, KIMSIYOUNG commented on src/main/java/blackjack/domain/gamer/Gamer.java
> +        if (ace.isAce() && ace.getValue() + sum > MAX_CARD_VALUE) {
에이스가 1 또는 11로 계산된다는 것은 ACE 라는 객체를 관리하는 곳에 있는게 자연스러울 것 같아요.

2022-03-14 12:27 UTC, KIMSIYOUNG commented on src/main/java/blackjack/domain/result/BlackJackResult.java
> +            (isBlackJack(player) && !isBlackJack(dealer)
isBlackJack(player) && !isBlackJack(dealer) 요 경우에는 플레이어의 승리기 때문에, ( ) 로 한 번 묶고 아래의 케이스를 하나로 묶어주고 해야할 것 같아요.

2022-03-14 12:27 UTC, KIMSIYOUNG commented on src/main/java/blackjack/domain/result/BlackJackReferee.java
> +    private final Map<BlackJackResult, Integer> dealerResult = new HashMap<>();
플레이어의 결과를 바탕으로 딜러의 결과를 반환할 수 있기 때문에, 필드로 가지지 않아도 될 것 같아요. 

기존의 필드를 바탕으로 구할 수 있는 값을 필드로 갖지 않을 때와, 구할 수 있음에도 필드로 가지고 있는 것의 장단점도 공부해보면 좋을 것 같아요.

2022-03-14 14:47 UTC, cndqjacndqja commented on src/main/java/blackjack/domain/Answer.java
> +    private static final String INVALID_VALUE_ERROR = "입려값이 y 또는 n이 아닙니다.";
🤭

2022-03-15 05:58 UTC, cndqjacndqja commented on src/main/java/blackjack/domain/result/BlackJackResult.java
> +            (isBlackJack(player) && !isBlackJack(dealer)
😱

2022-03-15 08:03 UTC, cndqjacndqja commented on src/main/java/blackjack/domain/gamer/Gamers.java
> +    public static final int INIT_DISTRIBUTION_COUNT = 2;
"처음 생성될 때, 카드를 얻는 개수 2", "딜러, 플레이어가 가질 수 있는 최대 카드 값 21"
이 두 개의 값은 딜러, 플레이어가 사용하는 값 or 해당 값이 딜러, 플레이어를 표현하는 값(?)이기 때문에 ( 이런 추상적인 내용을 말로 옮기기가 쉽지 않네요 ㅠㅠ 혹시 이해가 안되시면 알려주시면 감사합니다..!) Gamer에서 관리하는 것이 맞다고 판단했습니다.

2022-03-15 08:17 UTC, cndqjacndqja commented on src/main/java/blackjack/domain/gamer/Gamers.java
> +    public Player findPlayerByName(String name) {
Application에서 Player에게 카드를 나눠준 후( 이 부분은 Players와 Deck을 관리하는 BlackJackGame에서 이뤄집니다.), 해당 Player를 바로 출력해야 한다고 생각했습니다.

이렇게 될 경우, Application에서 BlackJackGame의 Players를 가져온 후, 그 Players를 다시 BlackJackGame에 넘겨주어 
상태 값을 변경해 주는 방식이 되었었는데, 이것이 조금 이상하다고 느꼈었습니다.
이유는 BlackJackGame의 필드인 Players의 상태를 변경하는 것인데, 그것을 BlackJackGame가 직접 하는 것이 아니라 외부에서 받아온 Player에 상태를 변경하는 것이기 때문입니다.

카일이 말씀해주신 것을 보면 다른 방법이 있을 것 같은데, 현재는 BlackJackGame을 제거하고 해당 역할을 Application으로 옮겨주는 것 외에는 생각이 잘 떠오르지 않는 상태입니다 😭

혹시 현재 변경한 상태가 카일이 생각하신 것과는 거리가 먼 것일까요??

2022-03-15 09:19 UTC, cndqjacndqja commented on src/main/java/blackjack/domain/gamer/Gamers.java
> +        return !player.canDraw();
처음에는 입력 받은 name의 Player가 isDrawPossible(카드를 뽑는 것이 가능한지 확인) 메서드를 통해 확인하려 했습니다. 이때 카드를 뽑기 위해서는 버스트(21을 초과한 상태)가 아니고 and 사용자 입력 값이 y가 되어야 합니다.
이 맥락에서 "뽑을 수 있는"-> isDrawPossible이 되고, isBurst(21을 초과한 상태인지)를 확인한다고 생각해서 
뽑을 수 없는 == 버스트 를 의도하지는 않았었습니다. (혹시 이 내용이 해당 코드와 어울리지 않았을까요?)

현재는 피드백 주신 내용 중, findPlayerByName()을 사용하지 않고, Players에서 반복문으로 수행하며 "뽑을 수 있는지"를 확인하기 때문에 canDrawToPlayer()로 변경해 보았습니다.

2022-03-15 09:48 UTC, cndqjacndqja commented on src/main/java/blackjack/BlackJackGame.java
> +public class BlackJackGame {
이전의 BlackJackGame은 제거 되었고, 그에 따라 Controller도 수정이 됐었습니다.
현재 BlackJackGame의 역할은 Deck과 Gamers를 필드로 가지고, 블랙잭 게임의 전체 비즈니스 로직을 수행하기 위해 다른 도메인과 협력하는 객체라고 생각했습니다.

이 역할이 BlackJackController보다는 BlackJackGame(Application에서 블랙잭의 전체 비즈니스 로직을 호출하는 곳)이 더 적합하다 느껴서 변경하게 됐습니다.

2022-03-15 12:20 UTC, cndqjacndqja commented on src/main/java/blackjack/domain/result/BlackJackReferee.java
> +    private final Map<BlackJackResult, Integer> dealerResult = new HashMap<>();
**기존의 필드를 바탕으로 구할 수 있는 값을 필드로 가지고 있을 때의 장점**
playerResults를 구할 때, dealerResult도 같이 구하기 때문에 코드 길이가 줄어들 수 있는 것 같습니다. 

**단점** 
객체는 명확하고 적절한 역할과 책임을 수행하여 서로 협력하는 것이 좋은 객체지향 코드라고 생각했습니다. 
객체의 상태라고도 불리는 인스턴스 필드가 많을 수록, 그 만큼 많은 역할을 하게 될 가능성이 생길 것이라 생각했습니다.

또한 개인적인 느낌으로는.. 저는 어떤 역할을 하는 클래스인지 볼 때, 클래스 명과 그 안의 인스턴스 필드를 먼저 확인했습니다. 
이런 관점에서 혼자가 아닌 여러 사람과 코딩할 때, 불필요한 필드를 가지는 것은 어떤 객체인지 파악하는데 좋지 않은 영향을 줄 것 같았습니다.


+ 객체지향 관련 개념을 찾아볼 때는 제가 느끼기에 추상적인 설명들이 많은 것 같습니다.😭 혹시 도메인이나 객체지향 원칙과 같은 추상적으로 느껴지는 개념들에 대해 카일은 어떤 방식으로 학습하셨을까요?? 해당 자료를 보시고 문제 없이 이해가 잘 되셨을까요?? 이런 개념들을 직접 구현해보면서 가장 쉽게 느껴볼 수 있는 상황이 레벨1인 것 같은데 시간이 빠르게 느껴져 걱정이 조금 되네요

2022-03-16 05:00 UTC, cndqjacndqja commented on src/main/java/blackjack/domain/gamer/Gamer.java
> +public class Gamer {
이 질문에 대해 다시 한번 생각해 봤는데요! 

**중복 로직이 존재하더라도 서로 다른 객체로 보는 것이 맞을까?**
저도 순간 왜 다른 객체로 보았을까..하면서 대답이 바로 나오지 않았습니다.
우선, 각 플레이어들은 하나의 객체로 보아도 요구사항에 맞게 기능을 수행하는데에 문제가 없지만, 딜러의 경우만 출력이 다르고 그 안의 규칙(16이상까지 무조건 draw를 계속 해야 한다 등)도 다르다는 관점에서 "다른 객체"로 보게 된 것 같습니다.

**이러한 로직을 다른 객체로 보지 않고, 하나의 클래스 안에서 구현한다면?**
하나의 클래스 안에서 다른 성격의 역할이 서로 섞이게 되면서 역할이 분명하지 않을 뿐더러, 책임이 많아지게 될 것 같습니다.

**조합을 사용한다면? 그 이유와 장단점은?**
현재 상황에서 조합을 사용했다면, 아무래도 상속의 단점을 줄일 수 있다는 장점이 있는 것 같습니다.

장점
상속의 단점은 상위 클래스와 하위 클래스 간에 의존도가 높다는 점 입니다. 상위 클래스에서 변경이 일어난다면 모든 하위 클래스에도 영향을 주기 때문에, 유연하게 대처하기 어려질 것 입니다.
조합을 사용한다면 상속 보다는 낮은 의존도로 설계할 수 있을 것 같습니다.

단점
하지만 위에서 언급한 "결국에 딜러, 플레이어에서 각각 gamer.getCards()을 사용하는 등"과 같은 단점으로 인해, 현재는 강한 의존성을 가지더라도 많은 중복 코드를 줄일 수 있다는 장점 때문에 상속을 사용하게 됐습니다.

2022-03-16 05:25 UTC, cndqjacndqja commented on src/main/java/blackjack/domain/gamer/Gamer.java
> +public class Gamer {
이 질문에 대해 다시 한번 생각해 봤는데요! 

**중복 로직이 존재하더라도 서로 다른 객체로 보는 것이 맞을까?**
저도 순간 왜 다른 객체로 보았을까..하면서 대답이 바로 나오지 않았습니다.
우선, 각 플레이어들은 하나의 객체로 보아도 요구사항에 맞게 기능을 수행하는데에 문제가 없지만, 딜러의 경우만 출력이 다르고 그 안의 규칙(16이상까지 무조건 draw를 계속 해야 한다 등)도 다르다는 관점에서 "다른 객체"로 보게 된 것 같습니다.

**이러한 로직을 다른 객체로 보지 않고, 하나의 클래스 안에서 구현한다면?**
하나의 클래스 안에서 다른 성격의 역할이 서로 섞이게 되면서 역할이 분명하지 않을 뿐더러, 책임이 많아지게 될 것 같습니다.

**조합을 사용한다면? 그 이유와 장단점은?**

장점
현재 상황에서 조합을 사용했다면, 아무래도 상속의 단점을 줄일 수 있다는 장점이 있는 것 같습니다. 상속의 단점은 상위 클래스와 하위 클래스 간에 의존도가 높다는 점 입니다. 상위 클래스에서 변경이 일어난다면 모든 하위 클래스에도 영향을 주기 때문에, 유연하게 대처하기 어려질 것 입니다. 조합을 사용한다면 상속 보다는 낮은 의존도로 설계할 수 있을 것 같습니다.

단점
하지만 위에서 언급한 "결국에 딜러, 플레이어에서 각각 gamer.getCards()을 사용하는 등"과 같은 단점으로 인해, 현재는 강한 의존성을 가지더라도 많은 중복 코드를 줄일 수 있다는 장점 때문에 상속을 사용하게 됐습니다.

2022-03-16 13:06 UTC, KIMSIYOUNG commented on src/main/java/blackjack/domain/gamer/Gamer.java
> +public class Gamer {
좋은 생각의 방향인 것 같습니다. 

현재의 구조가 강한 의존성을 가질 수 있다는 점과 많은 중복을 제거할 수 있다는 점을 인지하고 사용하시면 괜찮을 것 같아요. 
상속과 조합 그리고 상속자체를 하지 않는 것 모두 선택지에서 항상 고려될 수 있다는 점을 인지하고 계시면 좋을 것 같습니다.

2022-03-16 13:13 UTC, KIMSIYOUNG commented on src/main/java/blackjack/domain/gamer/Gamers.java
> +    public static final int INIT_DISTRIBUTION_COUNT = 2;
좋은 생각인 것 같습니다.

관점에 따라 다를 수 있지만 저는 개인적으로 2라는 숫자가 처음 분배해야하는 카드의 갯수를 의미하기에, 이를 분배하는 작업을 하는 객체가 적절하다고 생각했어요.
그리고 21이라는 숫자는 게임규칙상으로 의미있는 숫자이기에 게임의 규칙을 관리하거나 각 수가 어떤 값을 의미하는지에 따라 결과를 관리하는 객체에서 관리하는 것이 적절하지 않을까 라고 생각했습니다.

2022-03-16 13:15 UTC, KIMSIYOUNG commented on src/main/java/blackjack/domain/gamer/Gamers.java
> +    public Player findPlayerByName(String name) {
현재의 구조를 유지해야한다면 범고래의 말대로 각각의 플레이어를 전달하는 형태로 작성해야할 것 같아요. 

이 부분에 대한 피드백도 Application만 있고 Application에서 반복문을 돌며 카드를 분배받을 수 있는지 묻고 분배하고 출력한다면 현재의 구조는 사라지지 않을까 라는 의미였습니다.

2022-03-16 13:18 UTC, KIMSIYOUNG commented on src/main/java/blackjack/domain/gamer/Gamers.java
> +        return !player.canDraw();
현재 카드의 합이 21인 경우에 뽑을 수 없지만 버스트는 아니기 때문에 말씀드렸었습니다🙂 추가로 동일한 기능을 제공하더라도, (예를들어 정말 뽑을 수 없는 상태 == 버스트) 이 둘의 의미를 함축하는 다른 메소드명을 짓는 것이 혼선을 방지할 수 있을 것 같아요.

2022-03-16 13:29 UTC, KIMSIYOUNG commented on src/main/java/blackjack/domain/result/BlackJackReferee.java
> +    private final Map<BlackJackResult, Integer> dealerResult = new HashMap<>();
장단점에 대해서 많이 고민해보신 것 같아요. 제가 생각했던 장단점도 추가로 말씀드릴게요. 

현재의 구조처럼 두 가지 값을 모두 가지고 있는 경우 초기화와 동시에 결과값이 저장될 수 있는 장점이 있을 것 같아요. 다만 플레이어의 값만을 저장한다면 딜러의 결과는 매번 재계산되는 단점이 있을 것 같아요. 각각의 장단점이 반대의 경우엔 그 반대가 되겠죠?

필드로 가지거나, 필요한 필드만 갖고 그 필드를 기준으로 계산하고 그 결과를 메소드로만 제공하는 것은 사실상 역할의 관점에서 보면 동일한 것 같아요. (결국 매번 계산하여 제공하는가, 필드로 한 번에 초기화하고 Getter를 제공하는가의 차이로 봤습니다.)
추가로범고래는 필드를 먼저 바라본다고 하셨는데 저는 해당 객체가 제공하는 메소드를 먼저 보는 것 같아요. 내부가 어떤식으로 구현되든 우리가 사용하고자 하는 메소드는 무엇이 있는지, 그 메소드들이 결국 이 객체가 제공하는 기능들이고 그 기능을 묶고 군집화한 것이 역할이라고 생각했어요. 그렇기 때문에 저는 필드가 많아졌다고 파악하기 어렵다거나, 필드가 하나 줄었다고 파악하기 쉽다거나 라는 관점으로 생각하진 않았던 것 같아요.

맞아요. 객체지향이나 좋은 소프트웨어에 대한 부분은 추상화된 언어들이 많기 때문에 파악하기도 어렵고 내가 적용하려고 해도, 이게 맞는건지 항상 고민이 되는 것 같아요. 저는 조금 마음을 편하게 먹어도 된다고 생각하는데요. 이유는 저도 객체지향이나 좋은 소프트웨어에 대해서 잘 모르고 항상 헷갈리고 제 주위 동료들도 비슷한 것 같아요. 유지보수하기 좋고 가독성 좋은 프로그램을 만들겠다는 생각으로 조금씩 코드를 수정하고 변경해보고 비교해보는 작업들을 범고래보다 조금 더 많이해봤기 때문에 리뷰를 하고 있는 것이지, 제가 객체지향을 잘 이해해서 리뷰를 하는 건 아니라고 생각하셔도 될 것 같아요. 

그리고 레벨1이라는 과정에서 객체지향을 집중적으로 다루지만, 해당 과정에서만 객체지향을 학습할 수 있는 건 아니에요. 레벨2에서 웹을 하시더라도 동일하게 객체지향에 대해서 고민해야하고 레벨3에서도 객체지향, 좋은 소프트웨어 등에 대해 항상 고민할 수 밖에 없어요. 그렇기 때문에 레벨1에서 객체지향에 대해서 내가 완벽하게 이해하겠어라는 것 자체가 비현실적인 목표이고 부담은 내려놓으셔도 될 것 같아요. 

저 개인적으로는 항상 구현과 설명이 같이 있는 책을 학습하는게 저한테는 도움이 되었던 것 같아요. `객체에게 메시지를 보내라` 라는 말을 코드없이 이해하기엔 너무나 추상적인 것 처럼 코드와 설명이 함께 있는 책들을 주로 학습했던 것 같아요.

2022-03-16 13:32 UTC, KIMSIYOUNG approved these changes
안녕하세요 범고래! 
1단계 미션은 여기서 머지해도 될 것 같아요. 
범고래가 남겨주신 의견에 대한 댓글은 추가로 달아두었습니다.
충분히 잘하고 계시니까 학습속도에 대해서 너무 걱정하지 않으셔도 될 것 같아요. 
궁금하신 내용은 언제나 디엠이나 댓글로 남겨주세요🙂

고생하셨고 2단계에서도 잘 부탁드립니다.

2022-03-16 13:33 UTC, merged