[1단계 - 블랙잭] 필즈(조성우) 미션 제출합니다.
woowacourse/java-blackjack pull request #286
Opened 2022-03-11 08:49 UTC by progress0407

안녕하세요 스티치 ! 필즈에요!  

아래와 같이 블랙잭을 구현했어요 !
TDD를 통해서 비즈니스 로직에 대한 검증을 최대한 해보려 했는데 시간에 많이 쫓기듯 한 감이 있어서 ㅠ
아직 요구사항을 충족하지 못한 곳이 있을 것으로 보일 것 같아요
새로운 브랜치 내에서, Push하지 않는 선에서 리펙터링하고 있을게요 !

2022-03-12 09:24 UTC, lxxjn0 requested changes
필즈, 안녕하세요. 이번에 블랙잭 미션을 리뷰하게 된 스티치입니다 :)

블랙잭이 규칙도 복잡하고 다양한 용어들이 사용되어서 쉽지 않은 도메인인데 잘 구현해준 것 같습니다!! 이번에는 도메인의 역할에 대한 부분들에 대해서 주로 코멘트를 남겨두었어요!!

그리고 한번 같이 고민해보면 좋을 부분으로 dealer와 player가 게임 결과를 가지고 있는데 이 부분을 없애보는 것, 그리고 게임 전반적인 규칙을 따로 관리하는 곳이 없어서 dealer가 너무 많은 책임을 가지고 있는 것 같아요!! 물론 이러한 구조가 잘못된 것은 아니지만 게임의 규칙을 관리하는 객체를 따로 두고 딜러는 게임의 참가자로서 책임을 가지도록 개선해보면 코드가 현재와는 조금 더 다르게 개선될 것 같아요!!

마지막으로 현재도 충분히 블랙잭 도메인의 다양한 용어들을 코드에 잘 녹여낸 것 같아요!! 하지만 조금 더 블랙잭 도메인을 꼼꼼히 분석해보면서 한번 개선해보면 좋을 것 같아요!! 예를 들어 카드를 한장 더 뽑는 행위를 블랙잭에서는 hit이라고 하는데 이런 부분들을 한번 더 챙겨보면 좋을 것 같습니다! :)

피드백은 많이 않지만 위에서 말씀드린 부분들에 대한 개선을 해보면 많은 코드가 변경될 것 같아요!! 해당 부분들 참고해서 리뷰 반영 부탁드릴게요 :)

2022-03-12 09:24 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Hand.java
> +        }
현재 Ace의 개수를 고려하면서 연산을 진행하는 것으로 보여집니다. 그런데 Ace의 경우 1장만 11로 사용이 가능하고 2장부터는 사용이 불가능합니다. 단순히 Ace를 2장 가지고 있다고 한다면 두장 다 11로 사용하면 22가 되면서 bust가 됩니다. 그래서 한 장만 11로 사용이 가능하고 이후 Ace는 강제적으로 1로만 사용이 가능해요. 

그렇기 때문에 해당 로직은 단순히 Ace를 가지고 있는 지 여부만 확인하고, 1이 아닌 11로 점수를 계산했을 때 bust인지만 확인해서 점수를 계산하면 될 것 같아요!!

2022-03-12 09:24 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Hand.java
> +    }
현재는 ace 여부를 확인해서 없는 경우, 있는 경우 따로 연산하는 것 같아요!! 이러한 로직 말고 ace를 1로 무조건 계산하고 만약 11로 사용할 수 있는 경우 추가 점수인 10만 더하도록 하면 어떨까요?? 그럼 로직을 보다 단순하게 개선할 수 있을 것 같아요!!

2022-03-12 09:24 UTC, lxxjn0 commented on src/main/java/blackjack/domain/MatchResult.java
> +    DRAW("무", (self, other) -> drawCondition(self, other));
승패 판단 로직을 enum이 가지도록 구현하였군요!! 👍🏼

2022-03-12 09:24 UTC, lxxjn0 commented on src/main/java/blackjack/domain/card/Card.java
> +    }
해당 로직도 단순한 로직이긴 하지만 denomination에게 메시지를 던지도록 개선해보면 좋을 것 같아요!!

2022-03-12 09:24 UTC, lxxjn0 commented on src/main/java/blackjack/domain/card/Denomination.java
> +    private final int[] scores;
현재는 점수를 int[] 배열로 관리하는 이점이 전혀 보이지 않아요!! 단순히 기본 점수로만 저장하고 ACE의 추가적인 점수를 상수로 관리해서 사용자가 적절하게 사용하는 것은 어떨까요??

2022-03-12 09:24 UTC, lxxjn0 commented on src/main/java/blackjack/domain/participant/Participant.java
> +public class Participant {
해당 클래스를 추상 클래스로 활용할 순 없을까요?? dealer와 player가 가지고 있는 decideMatchResult와 같은 메서드의 파라미터만 조금 개선하면 Participant가 관리할 수 있을 것 같아요!!

2022-03-12 09:24 UTC, lxxjn0 commented on src/main/java/blackjack/domain/participant/Player.java
> +    }
플래이어의 결과를 반환하는 메서드를 만들어 둔다면 두 메서드를 1개로 줄일 수 있을 것 같아요!!

2022-03-12 09:24 UTC, lxxjn0 commented on src/main/java/blackjack/domain/participant/Dealer.java
> +    }
딜러는 게임을 진행하는 책임을 가지는 객체로 보입니다. 그런 관점에서 matchResultScores가 정말 필요한 맴버 변수인지 잘 모르겠어요. 결과는 결국 블랙잭 게임에서 판단이 가능한 부분이라고 생각이 됩니다. 현재는 게임을 참가한 딜러가 가지기에 과도한 책임을 가지는 것 같아요!!

deck을 가지는 건 딜러가 덱을 관리하고 카드를 배분하는 사람이라서 그런 것으로 보이는데 맞을까요?? 해당 부분은 필즈의 관점에 따라서 딜러가 가질 수 있는 부분이라고 생각되어서 괜찮을 것 같아요!! 

저의 추가적인 의견은 블랙잭 게임을 진행하는 테이블이 있고, 덱이 테이블 위에 놓여져서 참가자와 딜러가 테이블에서 게임을 진행하는 것. 그러면서 덱에서 카드를 뽑는 것은 테이블이 진행해준다는 관점으로 개선해본다면 딜러의 책임도 줄일 수 있고 카드를 배분하거나 게임을 진행하는 다양한 비즈니스 로직을 적절하게 분리할 수 있을 것 같아요!! 이 부분은 한번 참고해주세요 :)

2022-03-12 09:24 UTC, lxxjn0 commented on src/main/java/blackjack/domain/participant/Player.java
> +    private MatchResult matchResult;
해당 부분도 굳이 플레이어가 가져야 하는 속성인지는 의문이 드는 부분입니다!! 한번 고민해주시면 좋을 것 같아요!!! 👍🏼

2022-03-13 10:52 UTC, progress0407 commented on docs/blackjack/README.md
> +### 기능 요구 사항
ㅎ 넵 !

2022-03-13 10:53 UTC, progress0407 commented on src/main/java/blackjack/domain/MatchResult.java
> +    DRAW("무", (self, other) -> drawCondition(self, other));
ㅎㅎ 맞습니다 !

2022-03-13 10:54 UTC, progress0407 commented on src/main/java/blackjack/domain/card/Card.java
> +    }
아 ㅎ 그렇네요 체크할게요!!

2022-03-13 10:54 UTC, progress0407 commented on src/main/java/blackjack/domain/Hand.java
> +    }
아아, 어느 한쪽 값으로 계산후 증감을 하라는 뜻이군요, 알겠습니다 ㅎ

2022-03-13 10:56 UTC, progress0407 commented on src/main/java/blackjack/domain/Hand.java
> +        }
헉...! 생각해보니 그렇네요. 제가 블랙잭에 대한 이해도가 좀 낮았었다는게 느껴집니다.. ㅎㅎ 알겠습니다!

2022-03-14 10:58 UTC, progress0407 commented on src/main/java/blackjack/domain/Deck.java
> +    }
서로 다른 두 가지의 생성 스타일이 있으면 사용자가 Deck을 생성할 때 혼란이 올 것 같다는 생각이 드네요!
현재는 Card를 생성하는 `GenerateStrategy`를 주입받아서 생성하는 로직을 사용하는 방향으로 바꾸었습니다 !

2022-03-15 09:30 UTC, progress0407 commented on src/main/java/blackjack/domain/card/Denomination.java
> +    private final int[] scores;
처음에는 ACE가 두 가지 모두 상태를 가질 수 있어서 저렇게 표시하는 것에 의의를 두고 구조를 잡았던게 기억나네요..ㅎㅎ
확실히 그쪽 방면이 유지보수하기 더 편할 것 같아요

2022-03-15 09:38 UTC, progress0407 commented on src/main/java/blackjack/domain/participant/Participant.java
> +public class Participant {
지금은 `abstract` 로 변경했어요! 확실히 해당 클래스는 인스턴스화될 일이 없네요!

2022-03-15 09:39 UTC, progress0407 commented on src/main/java/blackjack/domain/participant/Player.java
> +    }
ㅎㅎ 지금은 하나로 되었습니다!

2022-03-15 09:40 UTC, progress0407 commented on src/main/java/blackjack/domain/participant/Player.java
> +    private MatchResult matchResult;
리펙터링 완료!

2022-03-15 12:11 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Hand.java
> +    }
해당 부분은 반드시 그래야 한다는 아니에요 :) 
한번 참고해주시고 필즈가 생각하기에 적절한 방향으로 코드를 가져가시면 될 것 같아요!! :)

2022-03-15 14:21 UTC, progress0407 commented on src/main/java/blackjack/domain/Hand.java
> +    }
ㅎㅎ 알겠습니다

2022-03-15 15:00 UTC, lxxjn0 approved these changes
필즈, 리뷰 반영한 코드 잘 봤습니다 :)

전체적으로 코드가 깔끔하고 테스트가 정말 꼼꼼히 잘 작성되어 있어서 인상깊었습니다!! 👍🏼  전반적인 코드의 구조가 잘 잡혀있어서 추가로 확인해볼만한 부분들에 대해서 피드백을 남겨두었습니다!!

해당 피드백들은 2단계 미션을 진행하면서 함께 반영해주시면 좋을 것 같아요!! 💯 
1단계 진행하느라 수고 많으셨고 2단계에서 다시 만나요~~ :)

2022-03-15 15:00 UTC, lxxjn0 commented on src/main/java/blackjack/controller/BlackJackController.java
>      public void run() {
현재 deck, dealer, players가 필드로 관리되지 않고 run 메서드 내부의 로컬 변수로 선언해서 충분히 코드를 동작시킬 수 있어보입니다!! 필드 변수는 객체의 존재 이유를 나타냅니다!! 현재 컨트롤러에서 해당 필드들을 관리해야 하는 이유가 보이지 않아요!!

컨트롤러가 어떤 목적을 가지고 사용되는지, 그렇다면 어떻게 관리하면 좋을지 한번 고민해보는 것도 좋을 것 같아요!!

2022-03-15 15:00 UTC, lxxjn0 commented on src/main/java/blackjack/domain/ScoreBoard.java
> +    }
> 해당 코멘트는 저의 주관적인 코멘트이니 참고만 해주세요 :)

저는 보통 생성자의 경우는 해당 객체가 가지는 필드만으로 생성할 수 있는 메서드로 제공하고 필드와 다른 값들을 받아서 내부적인 가공을 통해서 객체를 생성해야 하는 경우는 정적 팩토리 메서드를 사용합니다!!

지금과 같은 경우도 dealerMatchResult, playersMatchResult가 아닌 dealer와 players를 받아서 해당 객체를 생성하고 있습니다!! 이런 경우 모든 필드를 매개변수로 받을 수 있는 생성자(private으로 제한)를 만들어두고, 추가로 ScoreBoard.of(dealer, players) 와 같은 메서드를 제공해서 생성하도록 합니다. 

이런 규칙을 전반적으로 적용해서 코드를 작성해두면 사용자는 '생성자를 사용하면 아무런 가공 없이 객체를 생성할 수 있구나. 만약 적절한 가공을 통해서 객체가 생성되는 경우에는 정적 팩토리 메서드를 제공해주는 구나'라는 이해를 자연스럽게 이끌어 낼 수 있다고 생각합니다. 사용자가 굳이 내부를 보지 않더라도 어떠한 의도로 생성자 / 정적 팩토리 메서드 를 개발자가 제공했는지 코드에서 느껴질 수 있게 하려고 합니다. 

그러나 이러한 의견은 저의 개인적인 생각이기 때문에 필즈가 한번 읽어보고 동의되는 부분들에 대해서만 한번 참고해보면 좋을 것 같아요!! :)

2022-03-15 15:00 UTC, lxxjn0 commented on src/test/java/blackjack/constant/CommandTest.java
> +    }
앞선 코드에서 제안한 방법을 적용한다면 해당 테스트 코드도 보다 적절한 구조를 띌 수 있을 것 같아요!! :)

2022-03-15 15:00 UTC, merged

2022-03-16 06:59 UTC, progress0407 commented on src/main/java/blackjack/constant/Command.java
> +    STAY("n");
아 ㅎㅎ 지인의 코드를 보며 영감(?) 을 얻은 것인데 알아봐주셧군요!!

2022-03-16 07:02 UTC, progress0407 commented on src/main/java/blackjack/constant/Command.java
> +    public static final String NOT_FOUND_COMMAND_EXCEPTION_MESSAGE = "[ERROR] 존재하지 않는 명령어입니다.";
체크 완료!

2022-03-16 07:04 UTC, progress0407 commented on src/main/java/blackjack/controller/BlackJackController.java
> +    private static final String Y = "Y";
맞습니다 :), 체크 완료

2022-03-16 07:05 UTC, progress0407 commented on src/main/java/blackjack/constant/CommonConstant.java
> +    public static final int BLACKJACK_SYMBOL_NUMBER = 21;
아 해당 상수가 각각 다른 두 클래스에서 사용이 되거든요 ㅎ
스티치는 두 클래스 각각에 넣어 두는 식으로 관리 하나요?? 의견이 궁금하네요 !

2022-03-16 07:10 UTC, progress0407 commented on src/main/java/blackjack/constant/Command.java
> +    }
API를 사용하는 사용자가 능동적으로 예외 상황에 대해 처리를 할 수 있도록 위처럼 해놓았었는데
위 커맨드의 경우 예외를 발생하는 경우로만 사용하기 때문에 스티치 의견대로 해당 커맨드 객체 자신이 처리를 하는 것이 나을 것 같아요! 본격적으로 의도가 생기면 그때 `Optional`로 사용하는 게 나을 것 같아요 ! ㅎ

2022-03-16 07:11 UTC, progress0407 commented on src/main/java/blackjack/controller/BlackJackController.java
>      public void run() {
`필드 변수는 객체의 존재 이유` 
헐.. 이건 정말 놓치고 있었던 사상이네요 ㅠㅠ 맞아요...
필드 변수는 해당 객체가 어떤 친군지를 나타내 주는 항목 중 하나인데, 다시 생각해 보아야겠네요..ㅎㅎㅎ

2022-03-16 07:12 UTC, progress0407 commented on src/main/java/blackjack/domain/card/strategy/FixedCardsGenerateStrategy.java
> +public class FixedCardsGenerateStrategy implements CardsGenerateStrategy {
맞아요 테스트에서만 사용되는 클래스입니다,, :) 넵 !

2022-03-16 07:15 UTC, progress0407 commented on src/main/java/blackjack/domain/card/strategy/RandomCardsGenerateStrategy.java
> +    }
맞네요 놓친 부분이에요 ㅜ 체크 완료!

2022-03-16 07:25 UTC, progress0407 commented on src/main/java/blackjack/domain/participant/Dealer.java
>          super.name = new Name(DEALER_NAME);
아.. 마치 객체의 생성은 부모에게 위임한다 라는 느낌의 접근으로 받아드리면 될까요?? 괜찮은 것 같아요

2022-03-16 07:25 UTC, progress0407 commented on src/test/java/blackjack/constant/CommandTest.java
> +    }
ㅎㅎ 그렇네요 맞습니다 ~~ 리펙터링 합니다

2022-03-16 10:02 UTC, progress0407 commented on src/main/java/blackjack/domain/ScoreBoard.java
> +    }
헉 접근 방법이 참신합니다 !!

스티치가 말한 내용을 정리하면 아래와 같은데

`생성자` - 자신의 필드만으로 생성할 수 있을 때

`정적 팩터리 메서드` - 자신의 필드와 다른 값들을 받아와서 내부적인 가공을 통해서 객체 생성할 때

위와 같은 기준을 확립하게 된 기준이 있었던 건가요!? (책 혹은 강연)