[2단계 - 블랙잭(베팅)] 후니(최재훈) 미션 제출합니다.
woowacourse/java-blackjack pull request #296
Opened 2022-03-14 09:14 UTC by jayjaehunchoi

안녕하세요 제이!!

1단계 리뷰 잘 봐주셔서 감사합니다!!!
이번 리뷰도 잘 부탁드립니다!!

# final인 값 객체

이번에 베팅금을 받는 클래스로 ```Bet```이라는 VO를 만들었습니다.
이를 사용하는 ```Gamer``` 클래스에서는 ```final``` 키워드를 추가하였으나, 막상 ```Bet```클래스의 구현을 보면 ```amount```의 변경이 생깁니다.
이런 경우에는 ```Gamer``` 클래스에 존재하는 필드에 ```final``` 키워드를 제거해야 할까요?

# 상태 패턴

동일한 ```calculateBenefit``` 메서드가 상태에 따라 다른 계산 결과를 갖게 하기 위해 이 패턴을 적극 활용하였는데요,
막상 ```Bet``` 클래스에 필드로 넣기에는 맞지 않는 것 같아 매개변수로 ```Result``` 구현체를 주입해주게 되었습니다.

이런 방식으로도 상태 패턴을 사용할 수 있을까요? 

그리고 저는 사실상 enum으로 상태를 구현한 것 같아서 이게 정상적인 디자인 패턴의 사용인지에 대한 근본적인 의문도 듭니다.

++ ```잘 생각해보니 저는 전략패턴에 유사한 디자인 패턴을 사용한 것  같네요 디자인 패턴을 사용하려고 노력했으나 그 사용이 조금 미숙했던 것 같네요```

감사합니다.
후니 드림.

2022-03-15 02:56 UTC, jayjaehunchoi commented on src/main/java/blackjack/domain/player/Bet.java
> +    }
여기에서 새로운 ```Bet``` 클래스를 반환하게 만들면 불변객체임을 유지할 수 있을 것 같은데, 그렇게 되면 이 객체를 갖고 있는 ```Gamer```클래스에서도 새로운 ```Gamer``` 인스턴스를 만들어야 하고, ```Gamers``의 요소도 변경되어야 할 것 같아요. 설계자체가 잘못된 걸까요?

2022-03-15 02:56 UTC, jayjaehunchoi commented on src/main/java/blackjack/domain/player/Bet.java
> +    }
여기에서 새로운 ```Bet``` 클래스를 반환하게 만들면 불변객체임을 유지할 수 있을 것 같은데, 그렇게 되면 이 객체를 갖고 있는 ```Gamer```클래스에서도 새로운 ```Gamer``` 인스턴스를 만들어야 하고, ```Gamers``의 요소도 변경되어야 할 것 같아요. 설계자체가 잘못된 걸까요?

2022-03-15 08:39 UTC, JunHoPark93 requested changes
안녕하세요 후니!
2단계 빠르게 잘 구현해주셨네요.
몇 가지 코멘트 남겼는데요, 확인 후 반영부탁드려요!
궁금한점 코멘트 남겨주세요~

2022-03-15 08:39 UTC, JunHoPark93 commented on src/main/java/blackjack/domain/player/Bet.java
> +    }
> 이번에 베팅금을 받는 클래스로 Bet이라는 VO를 만들었습니다.
> 이를 사용하는 Gamer 클래스에서는 final 키워드를 추가하였으나, 막상 Bet클래스의 구현을 보면 amount의 변경이 생깁니다.
> 이런 경우에는 Gamer 클래스에 존재하는 필드에 final 키워드를 제거해야 할까요?

금액을 Bet으로 포장해주셨어요. 계산하는것의 책임이 이쪽이 맞을까요? 
https://tecoble.techcourse.co.kr/post/2020-06-11-value-object/ 여기도한번 참고해보셔요.

2022-03-15 08:39 UTC, JunHoPark93 commented on src/main/java/blackjack/domain/player/Bet.java
> +    }
> 이번에 베팅금을 받는 클래스로 Bet이라는 VO를 만들었습니다.
> 이를 사용하는 Gamer 클래스에서는 final 키워드를 추가하였으나, 막상 Bet클래스의 구현을 보면 amount의 변경이 생깁니다.
> 이런 경우에는 Gamer 클래스에 존재하는 필드에 final 키워드를 제거해야 할까요?

금액을 Bet으로 포장해주셨어요. 계산하는것의 책임이 이쪽이 맞을까요? 
https://tecoble.techcourse.co.kr/post/2020-06-11-value-object/ 여기도한번 참고해보셔요.

2022-03-15 08:39 UTC, JunHoPark93 commented on src/main/java/blackjack/domain/result/Result.java
> +}
> 동일한 calculateBenefit 메서드가 상태에 따라 다른 계산 결과를 갖게 하기 위해 이 패턴을 적극 활용하였는데요,
> 막상 Bet 클래스에 필드로 넣기에는 맞지 않는 것 같아 매개변수로 Result 구현체를 주입해주게 되었습니다.
> 
> 이런 방식으로도 상태 패턴을 사용할 수 있을까요?

상태 패턴이 아니라 전략패턴으로 구현해주신것으로 보여요. 방식은 여러개니 이런방식으로 해도 상관은없다고 생각해요.

2022-03-15 08:39 UTC, JunHoPark93 commented on src/main/java/blackjack/domain/BlackJackGame.java
> +                .sum();
부호를 바꾸는것을 더 명시적으로 나타내볼수있을까요?

2022-03-15 08:39 UTC, JunHoPark93 commented on src/main/java/blackjack/domain/BlackJackGame.java
> +import blackjack.domain.player.Bet;
이 클래스안에 COUNT_UNIT 는 안쓰이는것으로 보여요!

2022-03-15 08:39 UTC, JunHoPark93 commented on src/main/java/blackjack/domain/result/BlackJackResult.java
> +    HIT(new Keep(), Player::isSatisfyReceiveCondition);
이 부분도 두 번째 질문주신 부분으로 보이는데요, 가독이 떨어지는거같아요. 메서드로 추출해서 명시적으로 나타내보면 어떨까요?

2022-03-15 08:39 UTC, JunHoPark93 commented on src/main/java/blackjack/domain/player/Gamers.java
> +    public Map<Player, Bet> compareResult(final int dealerPoint) {
이번요구사항으로 원시값포장 및 일급컬렉션 사용이 있는데요, 이 결과값도 결과라는 도메인으로 포장해보면 어떨까요?

2022-03-15 08:39 UTC, JunHoPark93 commented on src/main/java/blackjack/domain/player/Gamer.java
> +    public Gamer(final String name, final Bet bet) {
부모클래스 생성자의 접근제한자도 확인부탁드려요 :)

2022-03-15 08:41 UTC, JunHoPark93 commented on src/main/java/blackjack/domain/result/Result.java
> +}
pr 본문을 업데이트해주셨군요.
이렇게 했을때의 장점과 단점을 한번 생각해보시고 장점이 커서 단점을 커버할 수 있는지 한번 판단해보셔요!

2022-03-15 08:42 UTC, JunHoPark93 commented on src/main/java/blackjack/domain/player/Bet.java
> +    }
넵 아래 코멘트를 남겨두었는데요, VO와 결과를 나타내는 클래스를 이용하면 고민이 해결될것같아요.

2022-03-15 17:33 UTC, jayjaehunchoi commented on src/main/java/blackjack/domain/player/Bet.java
> +    }
제이 이 부분 참고 잘했습니다!!

Bet을 불변객체로 변경할 수 있었어요!! 그리고 결과를 계산하는 로직이 BlackJackResult라는 새 객체로 옮겨져서 더 책임이 명확해진 것 같네요!

2022-03-15 17:37 UTC, jayjaehunchoi commented on src/main/java/blackjack/domain/result/Result.java
> +}
BlackJackResult에서 필드 Map의 Value로 Result 계산 전략을 넣어 사용했습니다.

장점은 Gamer마다 계산 전략을 갖는 효과를 얻는 것 같아요. 게다가 만약 상태로 전략을 갖고 있었다면 전략이 변경될 때 set을 호출해서 불변객체가 유지되지 않을 것 같아요.

단점은 객체에서 직접 상태를 갖는 것이 아니라 자료구조에 보관하다보니 응집성이 떨어질 것 같다는 생각은 들어요

저는 이번에 객체의 불변성을 유지하기위해 지금 코드를 작성했는데 이런 관점이라면 제이의 생각은 어떠세요?

2022-03-16 03:53 UTC, jayjaehunchoi commented on src/main/java/blackjack/domain/player/Bet.java
> +    }
[링크](https://prolog.techcourse.co.kr/studylogs/2098)의 과정을 통해 Bet 클래스를 불변 객체로 유지하게 됐으나, 이제는 중간 결과를 집계해야 하는 경우(블랙잭, 버스트, 히트)가 조금 문제점이 됐습니다.

사실 최종 결과 확인으로 모든 경우의 수를 계산 할 수 는 있지만, 이는 실제 블랙잭 도메인과 맞지 않다는 생각이 듭니다. 

요구사항 상 들어온 순서대로 순서 보장이 돼야 하고(중간에 결과가 집계되다 보면 순서 보장이 어려워질 수 있다고 생각합니다.), 또 BlackJackResult 내부 필드 요소에는 변경이 들어갈 텐데 이를 불변으로 유지해야 하는 것 때문에 이 부분들이 많이 고민됩니다.

링크 마지막에 해결되지 않은 문제점이라는 제목으로 글을 남겨두었습니다. 혹시 질문이 조금 이해가 되지 않으신다면 참고 부탁드립니다!

2022-03-16 14:13 UTC, JunHoPark93 commented on src/main/java/blackjack/domain/player/Bet.java
> +    }
Bet는 해결이 된것이고 BlackJackResult 내부의 값들이 계속 바뀌는게 문제라는것이죠?
BlackJackResult가 중간중간 계산의 책임을 부여하셨으면 수정하는 메서드에 적절한 검증이 있다면 괜찮을것같아요.
혹시 질문하신게 이 부분이 맞을까요?
아니라면 dm다시 부탁드려요~

2022-03-16 14:17 UTC, JunHoPark93 commented on src/main/java/blackjack/domain/result/Result.java
> +}
BlackJackGame에서 전략을 찾아줬는데, 찾은 전략을 다시 BlackJackResult로 넘겨주고있어요. 넘겨줄필요없이 바로 계산해서 BlackJackResult를 만들면 되지 않을까요?
그럼 말씀하신 자료구조에 보관하는 문제는 해결될것같아요!
지금 구조기반으로 말씀드리는것이니 혹시 수정해보시고 기존과 비교했을때 어느것이 나은지 보시면 좋을것같아요~

2022-03-16 14:22 UTC, JunHoPark93 approved these changes
안녕하세요 후니!
리뷰 반영하시느라 고생많으셨습니다.
많은 고민을 해주신거같아요!
이만 머지하도록할게요~
구조가 새로 바뀐부분에 대해서는 추가로 질문주신 부분에 코멘트 남겨두었는데요,
수정해보고 싶으시면 다시해보시고 dm주세요!

2022-03-16 14:23 UTC, merged

2022-03-16 15:01 UTC, jayjaehunchoi commented on src/main/java/blackjack/domain/player/Bet.java
> +    }
생각해보니 중간중간 hit인지 확인이 되네요 굳이 결과를 계산할 필요 없이 어떤 조건에 맞는지 확인하고 넘어간다면 문제는 해결될 것 같습니다!

2022-03-16 15:02 UTC, jayjaehunchoi commented on src/main/java/blackjack/domain/result/Result.java
> +}
계산해서 넘겨주니 문제점이 해결됐어요! 불필요한 메서드도 줄어들고 불변성도 유지될 것 같습니다!