[2단계 - 블랙잭(베팅)] 오찌(오지훈) 미션 제출합니다.
woowacourse/java-blackjack pull request #301
Opened 2022-03-15 15:16 UTC by Ohzzi

안녕하세요 범블비 :)
빠르게 2단계 미션으로 돌아왔습니다. 베팅을 추가하는 것 자체는 어려운 것이 아니었는데 최대한 객체 간의 연관성을 고려하면서 짜다 보니 머리를 싸매고 짜게 됐었네요. 최대한 인스턴스 필드 수를 줄이면서 하자니 순환 참조가 일어났었어서 결국 인스턴스 필드는 3개 이상 만들지 않는다는 규칙을 깨고(사실 Participant의 dto에서 이미 깨지긴 했습니다만) 플레이어에 Betting 클래스를 넣어 주었습니다.

사실 그래서 베팅을 넣고 났더니 프로젝트 구조가 뭔가 맘에 안드는 상황이 생긴 것 같긴 합니다. 😭 한번 보시고 부족한 점이 있다면 리뷰 부탁드려요 :)

2022-03-16 15:37 UTC, ddaaac requested changes
안녕하세요 오찌!

빠르게 2단계 미션 구현해주셨네요. 
기존 클래스들을 크게 건들지 않고 잘 구현해주셔서 변경 폭이 크다고는 느껴지지 않는데요, 구조가 맘에 안 드는 상황이 어떤 상황인지 구체적으로 말씀해주시면 좋을 거 같아요 😄 

몇몇 코멘트 남겼으니 확인 부탁드립니다~

2022-03-16 15:37 UTC, ddaaac commented on src/main/java/blackjack/domain/GameResult.java
> +        return (int) (player.getBetting().getValue() * outcome.getEarningsRate());
이 부분 관련해서 [코멘트](https://github.com/woowacourse/java-blackjack/pull/225#discussion_r826168624) 남겼는데요, 점점 더 도메인 로직들이 많아지네요. 한 번 확인부탁드립니다.

2022-03-16 15:37 UTC, ddaaac commented on src/main/java/blackjack/domain/GameResult.java
> +        return (int) (player.getBetting().getValue() * outcome.getEarningsRate());
> 최대한 인스턴스 필드 수를 줄이면서 하자니 순환 참조가 일어났었어서 결국 인스턴스 필드는 3개 이상 만들지 않는다는 규칙을 깨고(사실 Participant의 dto에서 이미 깨지긴 했습니다만) 플레이어에 Betting 클래스를 넣어 주었습니다.

`너 얼마 벌었어?`라는 질문에 대답해줄 수 있는 객체는 누구일까요? `Player`가 이 질문에 대한 답을 해줄 수 있을 거 같지 않나요? 이를 코드로 변환한다면 `player.calculateProfit(outcome)`처럼 나타낼 수 있을 거 같아요.
조금 더 들어가면 `player.calculateProfit(dealer)`와 같이도 표현될 수 있는데 지금 구조에서는 위 방법이 조금 더 적당해보이네요.
이렇게 되면 `Player`가 배팅 금액을 아는 게 자연스러워집니다. 그리고 가이드가 정확히 어떻게 되는지 기억은 안나지만 아마 3개까지 허용하는 걸로 기억해요. 잘 구현해주셨습니다.

2022-03-16 15:37 UTC, ddaaac commented on src/main/java/blackjack/domain/Outcome.java
> +    WIN_BLACKJACK("승", 1.5);
승리를 했을 때는 2배의 금액을 돌려받고 블랙잭일 경우 1.5배를 돌려받습니다.
이율은 0.5배 아닐까요?

2022-03-16 15:37 UTC, ddaaac commented on src/main/java/blackjack/domain/Score.java
> +public class Score implements Comparable<Score> {
> 객체지향 생활 체조? 를 보면 한 줄에 점(.)은 하나만 찍으라고 되어 있는데, 지금 cards.calculateScore().getValue()로 두 번 꺼내서 쓰고 있더라고요. 우선 cards.getCards().size()는 Cards에 size를 만들면 해결이 될 것 같은데, Cards가 Score 클래스의 value 값이 int라는걸 알지 못하게 하면서 여기서 getter를 한 단계 줄일만한 좋은 방법이 생각이 나지가 않아요 ㅠㅠ 이 경우에는 점(.) 찍는 규칙을 위반하면서 짜는게 나은걸까요?

getter가 등장하면 로직을 객체 안으로 넣을 수 있는지 확인해보면 좋습니다. `score.isBust()` `score.canBlackjack()`과 같은 메서드로 감쌀 수 있을 거 같아요.

그리고나서 추천드리는 건 `State` 클래스를 제거해보세요. `Cards` 클래스의 메서드만으로도 충분히 깔끔하게 표현이 될 거 같네요.
아마 `State`란 단어를 사용해주신 걸 보면 상태 패턴에 대해서 알고 계신게 아닐까 추측되는데 https://github.com/woowacourse/java-blackjack/pull/225#discussion_r825456780 이전에 말씀드렸던 거처럼 이 부분은 머지할 때 피드백을 드리는 게 좋을 거 같아요. 우선 `State` 클래스를 제거하는 걸 추천드립니다!

2022-03-16 15:37 UTC, ddaaac commented on src/main/java/blackjack/domain/participant/Participant.java
> +    public boolean isBlackjack() {
Participant 관련 질문에 대한 답변은 여기 달게요.

> 제가 추상 클래스 Participant의 필드들을 private으로 막아놨는데요, 이렇게 하니 상속받는 클래스에서 해당 필드를 쓰려면 getter로 꺼내와야 하는데요, 어차피 상속받는 클래스들이 해당 필드를 가지고 있는 개념이라고 생각하는데, 이 경우에 그냥 필드들을 protected로 만들어서 쓰는게 더 낫다는 생각이 들어요! 범블비는 어떻게 생각하세요?

https://github.com/woowacourse/java-blackjack/pull/225#discussion_r826924353 이전 단계의 코드에 코멘트 남겼습니다. 그런데 Participant의 필드들은 모두 외부에서 getter로 사용중인데요 protected로 바꿀 수 있는 것들이 있을까요?

2022-03-17 04:34 UTC, Ohzzi commented on src/main/java/blackjack/domain/Outcome.java
> +    WIN_BLACKJACK("승", 1.5);
처음에 좀 헷갈리긴 했는데 금액으로 생각한다면 본인이 원래 베팅한 금액 + 수익 으로 해서 이겼을 때 2배를 받는거가 생각해보면 맞기는 한데, 여기서 수익으로 계산하는 부분은 원래 베팅한 금액을 배제한 금액이 되는 것 같더라고요!(그래서 LOSE면 베팅 금액을 잃으니까 수익이 -가 되는 상황이 되는거죠)

2022-03-17 05:22 UTC, Ohzzi commented on src/main/java/blackjack/domain/Score.java
> +public class Score implements Comparable<Score> {
사실 작성할 때는 상태 패턴을 알고 작성한건 아니고 어떻게 하면 클래스를 뺄 수 있을까 생각하긴 한거였는데...ㅎ
안그래도 이 부분은 State 클래스가 꼭 필요할까 고민했던 부분이었어요! 그런데 어차피 isBust나 isBlackjack으로 호출을 할테니 별 의미가 없겠네요! 제거하는걸 고려해볼게요!

2022-03-17 08:08 UTC, Ohzzi commented on src/main/java/blackjack/domain/participant/Participant.java
> +    public boolean isBlackjack() {
원래는 getCards를 쓰는게 있었던 것 같은데 리팩토링 과정에서 없어진 것 같네요! 😢
지금은 말씀하신대로 쓰는 일이 없습니다! ㅎㅎ 감사합니다 :)

2022-03-17 08:09 UTC, Ohzzi commented on src/main/java/blackjack/domain/GameResult.java
> +        return (int) (player.getBetting().getValue() * outcome.getEarningsRate());
생각해보니 이걸 static 메서드로 뺄 필요가 없었네요!

2022-03-17 08:10 UTC, Ohzzi commented on src/main/java/blackjack/domain/GameResult.java
> +        return (int) (player.getBetting().getValue() * outcome.getEarningsRate());
확인했습니다 😄 확실히 제가 봐도 로직이 이상하게 복잡해지네요. 최대한 로직을 줄이면서도 동작이 같도록 리팩토링 해볼게요 :)

2022-03-17 08:29 UTC, Ohzzi commented on src/test/java/blackjack/domain/card/CardDeckTest.java
>      }
어차피 card를 넣었는데 다시 꺼내서 확인하는 것은 card가 참조 변수니까 actual과 무조건 같은 값을 가리켜서 의미가 없지 않을까 했습니다! 그런데 바꾼 방식도 별 의미가 없네요. 보통 이런 메서드는(카드를 한 장 드로우 해 주는지 확인하는 것 같은) 어떻게 테스트 하시나요?

2022-03-17 08:48 UTC, Ohzzi commented on src/main/java/blackjack/domain/Score.java
> +    }
혹시 방법이 통일된다는게 정확히 어떤 말씀을 말하시는건가요?
사실 지금 정확하게 이해가 가지 않네요 😢

2022-03-17 16:02 UTC, Ohzzi commented on src/test/java/blackjack/domain/OutcomeTest.java
> +    @CsvSource(value = {"20, WIN", "19, DRAW", "18, LOSE"})
테스트 유틸을 빼면서 @MethodSource를 @CsvSource 로 바꿔주었는데요, 제가 받은 리뷰는 아니지만 다른 크루의 리뷰로부터 @MethodSource의 사용이 그렇게 좋지 않다는 리뷰가 있었다는 이야기를 들었습니다! 저는 원래 객체가 조금만 복잡해지면 MethodSource를 사용했었는데요😅 혹시 MethodSource가 다른 CsvSource나 ValueSource에 비해 큰 단점이 있는걸까요?

2022-03-18 16:28 UTC, ddaaac requested changes
안녕하세요 오찌!

리뷰 잘 반영해주셨습니다.
몇 가지 코멘트 남겼으니 확인해주세요!

2022-03-18 16:28 UTC, ddaaac commented on src/main/java/blackjack/BlackjackGame.java
> +                .map(name -> new Player(name, deck.drawDouble(), inputBetting(name)))
1단계 코멘트에도 남겼지만 도메인에 대한 로직이 도메인에 있는건 크게 어색하지 않은 거 같아요.
여기서 로직은 `이름이 중복되면 안된다`보다는 `플레이어들의 이름이 중복되면 안된다`가 적당하지 않을까요?
해당 도메인 로직을 처리하기 위해서는`Players` 객체가 필요하지 않을까요?

아마도 검증 이후에 getter를 사용해서 데이터를 꺼내쓰면 의미가 없지 않나에 대해서 고민하고 계신 거 같아요.
이 부분은 [콜백](https://myhappyman.tistory.com/106) 함수를 통해서 해결할 수 있습니다. 여유가 되신다면 한 번쯤 구현해보시고 지금 코드와 변경된 코드의 장단점을 비교해보는 것도 좋을 거 같네요.

2022-03-18 16:28 UTC, ddaaac commented on src/test/java/blackjack/util/BlackjackTestUtil.java
> +    }
> 그런데 유틸 클래스의 경우 객체 지향과는 맞지 않는 거라고들 하잖아요? 그래서 도메인을 다루는 로직에 유틸 클래스를 지양하는 것으로 알고 있는데, 특히나 지금 이 테스트 유틸은 도메인의 인스턴스를 만들어서 반환해 주는 거고요. 도메인을 다룬다고 하더라도 도메인 로직에 직접적인 연관이 가지 않고 테스트 코드의 유연성을 더해준다면 이런 식으로 테스트 유틸을 만들어서 하는 것이 더 나은 방향일까요?

이 부분은 트레이드오프의 영역인거 같아요. 지금 방식은 테스트 코드의 유연성과 가독성은 크게 늘어나는 대신에 `BlackjackTestUtil`에 대한 테스트가 필요할 것도 같고, 유틸은 도메인으로 옮길 수 있다는 생각을 해보면 `Cards`가 인터페이스가 돼야하나 이런 생각도 해볼 수 있을 거 같구요. 
하지만 개인적으로 지금 코드 정도면 적당한 합의점을 찾지 않았나 싶습니다. 테스트 코드기 때문에 도메인 영역을 크게 건들지 않고 있고(물론 도메인이 변경되면 이 Util도 변경대상이 될 수 있기 때문에 취약하긴 하죠) 덕분에 테스트 코드의 가독성은 정말 크게 향상되었습니다. 이런 부분은 정말 정답이 없기 때문에 매번 고민이 많이 되는 거 같아요. 아마 오찌 정도로 깊게 생각하시는 분이라면 매번 좋은 합의점을 찾아내실 거라고 생각합니다.

+) 추가로 createCard(10)처럼 더 단순하게 만드는 건 어떨까요? 모양은 크게 중요한 값은 아닌 거 같아서요.

2022-03-18 16:28 UTC, ddaaac commented on src/main/java/blackjack/domain/Score.java
> +    }
지금과 같은 구조를 의도하는 코멘트였습니다. 제대로 표현을 못했네요 🥲

사실 이 방법이나 `compareTo`나 가독성이 그리 좋지 않습니다. 이 부분은 자바라는 언어가 갖고 있는 한계이기 때문에 그러려니하고 넘어가시면 될 거 같아요. [연산자 오버로딩](https://www.codingame.com/playgrounds/6847/kotlin-operator-overloading)을 지원하는 다른 언어를 사용하면 해결될 문제입니다.

2022-03-18 16:28 UTC, ddaaac commented on src/main/java/blackjack/domain/Outcome.java
> +    WIN_BLACKJACK("승", 1.5);
아하 제가 룰을 오해하고 있었네요 🥲
블랙잭은 운이 좋아서 걸린거니 0.5배의 수익만 가져가는 거라고 이해하고 있었습니다.

2022-03-18 16:31 UTC, ddaaac commented on src/main/java/blackjack/domain/participant/Participant.java
> +    public boolean isBlackjack() {
관련해서 1단계에 [코멘트](https://github.com/woowacourse/java-blackjack/pull/225#discussion_r826924353)를 남겼었습니다. 확인 부탁드려요!

2022-03-21 07:58 UTC, Ohzzi commented on src/test/java/blackjack/util/BlackjackTestUtil.java
> +    }
테스트코드 가독성이 향상되었다고 말씀해주시니 기분이 좋네요 😄
모양을 굳이 넣어준 것은 카드가 중복되면 안된다는 검증 조건이 들어가서 어쩔수 없이 넣어주었습니다. 테스트 경우에 따라 다양한 모양을 사용할 필요가 있더라고요! 중복 검증 조건에 대해 더 고민해 보고 뺄 수 있다면 빼서 단순화하도록 해보겠습니다!

2022-03-21 08:01 UTC, Ohzzi commented on src/main/java/blackjack/BlackjackGame.java
> +                .map(name -> new Player(name, deck.drawDouble(), inputBetting(name)))
자바에도 콜백이 있는줄은 처음 알았네요! 지금은 적용할 여유가 없을 것 같고 따로 공부를 해보도록 하겠습니다 :)

2022-03-21 08:02 UTC, Ohzzi commented
피드백 사항을 반영하면서 상태 패턴까지 적용하려다 보니까 리뷰 요청이 조금 늦었습니다 😢 

DM으로 여쭤봤던 부분들 까지 적용하기 위해 노력했는데요, 다만 피드백 사항 중에 `여기서 로직은 이름이 중복되면 안된다보다는 플레이어들의 이름이 중복되면 안된다가 적당하지 않을까요? 해당 도메인 로직을 처리하기 위해서는Players 객체가 필요하지 않을까요?` 라는 부분을 적용하면서, 검증 로직을 Players를 만들어서 Players에서 가져갔었는데, Players 생성자에서 Betting 입력 때문에 매개변수로 메서드를 넘겨주는 방식을 채용했다보니 무한루프에 빠지는 오류가 발생했습니다. 그래서 일단은 부득이하게 PlayerNames라는 클래스를 다시 만들어서 거기서 이름에 대한 검증 책임을 가지도록 했습니다. (다만 인원 수 검증에 대한 부분은 여기에 있는게 맞는지 조금 의문이 드네요.)

콜백함수 부분은 적용하려고 공부해보려고 했는데, 아직 명확하게 이해가 가지 않아서 일단은 보류해두었습니다. 미션이 끝난 이후에 다시 한번 공부해보고 미션과는 별개로 적용해볼 수 있도록 할게요 😄

2022-03-21 15:38 UTC, ddaaac commented on src/main/java/blackjack/domain/participant/Player.java
> +        }
콜백 시도의 흔적이군요 😀

2022-03-21 15:49 UTC, ddaaac commented on src/main/java/blackjack/domain/participant/PlayerNames.java
> +public class PlayerNames {
> Players를 만들어서 Players에서 가져갔었는데, Players 생성자에서 Betting 입력 때문에 매개변수로 메서드를 넘겨주는 방식을 채용했다보니 무한루프에 빠지는 오류가 발생했습니다. 그래서 일단은 부득이하게 PlayerNames라는 클래스를 다시 만들어서 거기서 이름에 대한 검증 책임을 가지도록 했습니다. (다만 인원 수 검증에 대한 부분은 여기에 있는게 맞는지 조금 의문이 드네요.)

지금은 이름과 배팅 금액을 따로 생각해서 이름 검증을 먼저한 다음에 배팅 금액을 입력받아서 `Players`를 생성하려고 하시는 거 같아요.(아마 콘솔 환경의 영향이 큰 거 같네요)
만약 플레이어 이름과 배팅 금액 두 가지가 플레이어를 만들기 위한 하나의 데이터 덩어리라고 생각하면 플레이어 이름과 배팅 금액을 모두 입력 받은 다음에 이후에 `Players`를 생성하면서 검증이 일어나도 될 거 같네요.

2022-03-21 15:51 UTC, merged

2022-03-21 15:54 UTC, Ohzzi commented on src/main/java/blackjack/domain/Score.java
> +    }
일단 구현되어있는 메서드를 사용하려고 하다 보니 그렇게 됐는데, 확실히 greaterThan끼리 체이닝 하는게 더 알아보기 쉽겠네요!

2022-03-21 15:59 UTC, Ohzzi commented on src/main/java/blackjack/domain/state/Running.java
> +public abstract class Running extends AbstractState {
사실 저는 클래스 자체를 많이 분리하는것도 좋지 않은 설계가 아닌가 하고 생각하고 있어서 메서드가 조금 중복되더라도 클래스를 새로 안만드는 방향으로 하고 싶었거든요! 아마 지금 리뷰 남겨주신게 내부 클래스를 사용한 것 같은데 저는 중첩 클래스에 아직 익숙하지는 않아서요. 이런식으로 설계하면 클래스 파일을 많이 만들지 않으면서도 중복을 제거할 수 있는 걸까요?

2022-03-21 16:00 UTC, Ohzzi commented on src/main/java/blackjack/domain/state/State.java
> +public interface State {
사실 이부분이랑 Cards에서도 고민을 한게 플레이어가 가지고 있는 손패를 의미하니까 Hand라고 하고 싶었는데, 다른 크루들과 얘기해보니 Hand라고 지으면 뭔가 잘 알아듣지 못할 것 같다는 이야기를 하더라고요? Hand 정도면 쉽게 이해할 수 있는(손패라는 의미로) 단어일까요?

2022-03-21 16:00 UTC, Ohzzi commented on src/main/java/blackjack/domain/state/DealerRunning.java
> +    }
블랙잭 확인 다음 부분으로 hit을 사용하는 방법을 고려해보도록 하겠습니다! :)

2022-03-21 16:01 UTC, Ohzzi commented on src/main/java/blackjack/domain/participant/Player.java
> +        }
흔적은 남아있지만 콜백을 명확하게 이해하는데는 실패했어요 😢

2022-03-21 16:03 UTC, Ohzzi commented on src/main/java/blackjack/domain/participant/PlayerNames.java
> +public class PlayerNames {
사실 이 미션 자체가 콘솔에서만 진행되어서 그런건지는 몰라도, 아니면 제가 미션 진행 예시에 집착하고 있는 건지는 몰라도 아직은 이 문제를 해소하기 위한 방법이 잘 떠오르지는 않네요 😢 플레이어 이름과 베팅 금액 모두 플레이러를 만들기 위한 데이터 덩어리라는 말씀은 확실히 공감하는 부분인 만큼, 머지 이후에도 조금 더 고민해보도록 하겠습니다!

2022-03-21 16:40 UTC, ddaaac commented on src/main/java/blackjack/domain/state/Running.java
> +public abstract class Running extends AbstractState {
중첩 클래스에 관련된 코멘트는 아니었습니다. 지금과 클래스 갯수는 동일하고, `hit`은 `Running`에서 오버라이딩하고 참가자별로 동작이 달라지는 부분만 구현체들에서 `hitByParticipant`로 처리할 수 있겠네요.

```java
// Running.java
public abstract class Running extends AbstractState {
  
    protected abstract State hitByParticipant(Card card);

    @Override
    public State hit(Card card) {
      // 공통 로직이 들어가는 자리

      return hitByParticipant(Card card);
    }
}

// DealerRunning.java
public final class DealerRunning extends Running {

    @Override
    protected State hitByParticipant(Card card) {
        if (shouldHit(cards)) {
            return new DealerRunning(cards);
        }
        return new Stand(cards);
    }
```

2022-03-21 16:40 UTC, ddaaac commented on src/main/java/blackjack/domain/state/State.java
> +public interface State {
`Cards`도 괜찮아보이네요. 보통 카드게임에서는 손패를 `Hand`라고 하니 도메인 용어를 사용하는 건 괜찮다고 생각합니다.
하지만 가장 중요한 건 같이 코드를 짜는 팀원들이 쉽게 알아볼 수 있는 단어겠죠 😀