[2단계 - 블랙잭(베팅)] 수달(허수진) 미션 제출합니다.
woowacourse/java-blackjack pull request #304
Opened 2022-03-16 07:27 UTC by her0807

안녕하세요 스티치:) 

1차 피드백을 반영한 뒤, 요구사항을 적용한 코드입니다. ✌🏻 

> 1. 배팅 금액에 대한 [요구사항](https://github.com/her0807/java-blackjack/blob/step2/README.md#%EB%B0%B0%ED%8C%85-%EA%B8%88%EC%95%A1) 도출

배팅 금액은 어떤식으로 계산되는 지 요구사항 파악을 먼저 진행했습니다.

자세한 사항은 코멘트로 남겨두겠습니다. 

이번 리뷰도 잘부탁드립니다!

---
![스크린샷 2022-03-16 오후 4 15 09](https://user-images.githubusercontent.com/26570275/158538136-3d797ad3-94bd-4ba3-8374-31a2582353cf.png)

2022-03-16 08:01 UTC, her0807 reviewed
tdd 로 구현하니 테스트 커버리지가 높아져서 좋아요 :ㅎㅎ

![스크린샷 2022-03-16 오후 3 59 09](https://user-images.githubusercontent.com/26570275/158543490-ab75a46f-df95-4f30-80b9-758b8ace48c1.png)

2022-03-16 08:01 UTC, her0807 commented on src/test/java/blackjack/domain/DealerTest.java
>  public class DealerTest {
DealerTest 에서 최종 결과 계산 로직을 -> 최종 수익 계산으로 변경했습니다.

2022-03-17 07:52 UTC, her0807 commented on src/main/java/blackjack/domain/GameResult.java
>          return Arrays.stream(values())
## 무조건 점수가 21이면 블랙잭이 아니라, 최초 두장의 합이 21이면 블랙잭.
나무위키를 보던 중 그동안 블랙잭에 대해 잘못된 이해를 하고 있음을 깨달았습니다. 
따라서 최초 2장의 합이 21 일 때만 블랙잭이 성립되도록 로직을 변경했습니다!!

[카드 두 장을 기본적으로 지급받게 되며, 카드 숫자를 합쳐 가능한 21에 가깝게 만들면 이기는 게임. 처음 받은 2장 합쳐 21이 나오는 경우만 블랙잭이된다.](https://namu.wiki/w/%EB%B8%94%EB%9E%99%EC%9E%AD(%EC%B9%B4%EB%93%9C%EA%B2%8C%EC%9E%84))

2022-03-17 08:15 UTC, her0807 commented on src/main/java/blackjack/domain/Gamer.java
> +    private final String name;
### 프로그래밍 요구 사항

- 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다. 

를 지키기 위해서 세개의 인스턴스 변수 중 어떤 것을 제거할 수 있을까 고민하다가
Name 이라는 클래스 내부에서 이름에 대한 검증만 이뤄질 뿐, 다른 비지니스 로직이 없다는 점에서
Name 의 원시값 포장을 풀고, 검증 로직을 Gamer 내부로 가져왔습니다.

검증 로직을 InputView 에서 하지 않고, 도메인 내부에서 한 이유는 뷰에서 받아온 데이터 외에도
다른 곳에서 객체를 생성할 때 이름 값이 유효함을 보장하고 싶어서 입니다. 🥰

2022-03-17 13:03 UTC, her0807 commented on src/main/java/blackjack/domain/BettingMoney.java
> +    public BettingMoney(String value) {
batting 은 야구 방망이를 휘두를 때 사용하고, 
내기나 도박에 사용되는 것은 betting 임을 알게되어 변경했습니다. ~ 🤙🏻

2022-03-17 13:19 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Gamer.java
> +    public boolean addMoney(int value) {
라이브러리의 코드를 참고해서 작업을 해주셨군요!! 단순히 코드만 작성되어 있다면 의문이 생겼을 수 있는데 따로 추가 부연 설명을 남겨주셔서 감사합니다 👍🏼

2022-03-17 13:22 UTC, her0807 commented on src/main/java/blackjack/domain/Denomination.java
> +    ACE(1, "A"),
나무 위키에서 블랙잭에 관한 요구사항을 다시 살펴보다가 `딜러의 A는 bust가 되기 전까지 11로 계산한다.`
라는 규칙을 발견하여` Ace 기본 값을 11로 변경했었습니다.`

그런데 이 로직을 플레이어랑 같이 사용하다보니 플레이어가 A,A,A 를 뽑을 경우 최적값이 13이지만, 23이 나오는 오류를 발견했습니다.

그리고다시 생각해보니 최초의 로직으로 하면 Ace 는 최초 값인 1에 10을 더해 11인A 를 맨 처음 가지고, 
그 이후부터는 A가 11로 계산되면 Bust 이기 때문에 1로 더해져 제가 의도한 로직과 일치하게 동작함을 확인하여
다시 이전 코드로 변경했습니다 - 🍰

2022-03-17 15:46 UTC, lxxjn0 requested changes
수달, 2단계 리뷰 잘 봤습니다!! 👍🏼 

이번에도 코드가 잘 짜여있어서 건드릴 부분이 거의 없는 것 같아요!! 제가 몇가지 부분들에 대해서만 피드백 남겼으니 한번 확인해보고 반영해주세요 :)

추가로 Application에서 게임 관련 로직들이 많이 관리되고 있는 것 같은데 블랙잭 게임 규칙을 관리해주는 객체를 하나 만들어 보는 것도 재밌을 것 같아요!! 👍🏼

2022-03-17 15:46 UTC, lxxjn0 commented on src/main/java/blackjack/domain/GameResult.java
>          return Arrays.stream(values())
해당 로직에서 score를 계산하지말고 Cards를 넘겨보는 건 어떨까요?? 또는 참가자도 괜찮고요!! 그렇다면 따로 blackjack 여부를 bool 값으로 넘겨주지 않아도 내부에서 처리할 수 있을 것 같아요!!

2022-03-17 15:46 UTC, lxxjn0 commented on src/main/java/blackjack/domain/GameResult.java
> +    }
이렇게 처리하기보단 인스턴스 메서드로 처리해보는 건 어떨까요??

2022-03-17 15:46 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Player.java
> +    public static final int CONVERT_POSITIVE_VALUE = -1;
엇 여기도 접근 지정자요!!

2022-03-17 15:46 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Dealer.java
> +    public boolean calculateBattingMoneyResult(Player player) {
확인해보니 -1을 곱해주는 로직으로 인해서 이런 상황이 발생하는 것 같아요!! Dealer 내에서 `player.getBettingMoney()` 를 가져와서 -1을 곱해주는 로직을 가지면 괜찮을 것 같아요!! 어떤가요??

2022-03-18 05:53 UTC, her0807 commented on src/main/java/blackjack/domain/Dealer.java
> +    public boolean calculateBattingMoneyResult(Player player) {
오오 좋은 의견이네요 👍🏻

2022-03-18 06:02 UTC, her0807 commented on src/main/java/blackjack/domain/GameResult.java
>          return Arrays.stream(values())
@lxxjn0 저도 맨 처음에는 그렇게 작성했었는데, 그러니까 10줄 이 넘더라구요. ㅠㅠ

그래서 옮겨 놨던 코드 입니다 .. ㅠ

```java
    public GameResult createResult(Gamer dealer) {
        if (isBust()) {
            return GameResult.LOSE;
        }
        if (dealer.isBust()) {
            return GameResult.WIN;
        }
        if (this.isBlackJack()) {
            return BLACKJACK;
        }
        return GameResult.of(getTotalScore(), dealer.getTotalScore(), isBlackJack());
    }

```

2022-03-18 06:23 UTC, her0807 commented on src/main/java/blackjack/domain/BettingMoney.java
> +    public static final int BATTING_MIN_VALUE = 0;
오호!!! 😯  블랙잭에 여러 규칙을 생각해보았을 때 딜러는 초기 배팅을 하지 않으니
`초기값으로 0을 가질 수 있게 생성 로직 내부에서 배팅 머니를 0으로 설정해주겠습니다.`

2022-03-18 06:29 UTC, her0807 commented on src/main/java/blackjack/domain/Card.java
> +                .filter(card -> card.equals(target))
추출했던 이유는 hasSame 에서 하고 있던 연산이 equals 내부에 있다는 점을 발견했어요.

그래서 기존에 있던 메서드를 활용해볼까? 라는 생각에서 변경했던 부분인데 

`로직 중복 vs 불필요한 객체 생성 ` 둘 중 뭐가 더 불편하냐?! 생각해보면 불필요한 객체 생성이 더 불편하네요 👍🏻 

이전 로직으로 .. 총총총

```java
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Card card = (Card) o;
        return denomination == card.denomination && suit == card.suit; // 이 부분!
    }
```

2022-03-18 06:59 UTC, her0807 commented
@lxxjn0 

인텔리 상수 추출 단축키를 새로 배워서 남발했는데 .. 거기서 기본으로 `public` 으로 지정해주는 바람에  .. 흡흡 죄송합니다 . ㅠㅠ

우선 피드백 주신 부분 반영했어요! 그 이후에 추가로 `블랙잭 게임 규칙을 관리해주는 객체` 생성에 대해 생각해봤는데

getInitCards, drawDealer 외에 다른 메서드들은 뷰와 관계를 맺고 있어서 어떤 식으로 변경할지 감이 안오네요! ㅠㅠ (😭 )

2022-03-19 02:36 UTC, lxxjn0 requested changes
수달, 리뷰 반영한 코드 잘 봤습니다!! :)

전체적인 코드의 구조는 이제 충분히 잘 잡혀있는 것 같아요!! 따로 블랙잭 게임 규칙을 관리해보면 좋을 것 같다는 피드백은 아무래도 입출력 로직이 깊게 관여될 것 같아서 어려울 것 같네요 ㅠㅠ

이번에 몇가지 피드백을 남겼는데 해당 피드백 말고도 추가로 개선해볼만한 부분이 있어요!! 현재 코드에서는 대부분 예외에 대한 처리가 되지 않는 것 같습니다! 빈 칸을 입력해도 플레이어가 등록되고 숫자가 아닌 값을 입력하면 바로 에러가 발생하고 있어요!!

사용자가 프로그램을 사용했을 때 에러 상황에 대해 인지받고 다시금 프로그램을 동작시킬 수 있도록 다양한 예외 방어 로직들을 한번 추가해보면 좋을 것 같습니다 :)

2022-03-19 02:36 UTC, lxxjn0 commented on src/main/java/blackjack/Application.java
>      }
베팅 머니를 입력받은 값을 InputView에서 바로 int로 바꿔주는 것 같아요!! view는 단순히 사용자에 대한 입력을 받도록 하고 생성의 책임을 도메인에 넘겨주는 건 어떨까요?? BettingMoney가 문자열 값을 받아서 생성하도록 해주는 것도 좋을 것 같아요!!

LocalDateTime 클래스를 생각해보면 사용자 입장에서는 올바른 문자 타입이 들어가는지, 정수인지 문자인지 고민하지 않고 생성할 수 있어요. 만약 "ㅁ"라는 문자열을 넘겨주면 그에 맞는 적절한 예외가 발생하면서 객체가 생성되지 않습니다. 이렇게 다양한 타입의 값을 받아서 생성할 수 있도록 하면 도메인 객체가 더 풍부해지고 사용성이 좋아질 것 같아요!!

2022-03-19 02:36 UTC, lxxjn0 commented on src/main/java/blackjack/Application.java
>      }
playing 메서드의 내부 로직이 자연스럽게 읽고 이해하기가 조금 어려운 것 같아요!! while 문 내부에 player가 hit을 할 수 있고 command가 yes이면 다시 사용자에게 입력을 받고 있어요!! 조건을 보면 이미 사용자의 입력이 yes라고 생각이 되는 부분인데 다시 조건을 체크하는 것이 어색한 것 같아요!!

while 문 내부의 조건을 메서드로 뽑아보면 어떨까요?? 해당 조건에서 플레이어의 힛 가능 여부와 사용자의 입력을 받아서 hit을 할 것인지 판단하는 코드를 함께 묶어두면 코드가 좀 더 이해하기 좋은 구조가 될 것 같아요!!

2022-03-19 02:36 UTC, lxxjn0 commented on src/main/java/blackjack/domain/BettingMoney.java
> +    public static final int BETTING_MONEY_INIT_VALUE = 0;
해당 상수를 확인해보니 dealer를 생성할 때 사용하기 위한 값으로 보여져요!! 이 또한 기본 생성자로 제공해주고 dealer와 gamer의 생성자를 다양하게 오버로딩 해두면 따로 해당 상수를 사용하지 않고도 생성할 수 있을 것 같아요!!

2022-03-19 02:36 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Cards.java
> +    private int convertCloseWin(int totalScore) {
해당 메서드에도 Score와 같은 이름이 있으면 좋을 것 같아요!! `convertToClosestScore`와 같이요!! 단순히 해당 메서드만 읽었을 때 바로 이해가 가는 이름이 아니었던 것 같아서 한번 참고해봐주세요 :)

2022-03-19 02:36 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Dealer.java
> +    public boolean calculateBattingMoneyResult(Gamer player) {
여기도 batting이에요~~

2022-03-19 02:36 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Dealer.java
> +    public boolean calculateBattingMoneyResult(Gamer player) {
해당 메서드 네이밍이 bettingMoneyResult를 계산해서 값을 반환할 것 같은데 boolean을 반환하니 어떠한 역할을 하는 메서드인지 이해하기가 어려웠어요!! 앞서 list의 add 메서드와 같이 의도해서 작성한 것으로 보이는데 이에 따른 반환값을 사용하지 않는다면 void로 해주고 적절한 메서드 명을 가져가는 것이 더 좋을 것 같습니다!!

2022-03-19 02:36 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Player.java
> +        }
로직을 확인해보니 calculateBettingMoneyResult 메서드에서 다시금 딜러와 플레이어가 둘 다 blackjack인지 확인하고 있어요!! 이는 사실 현재 메서드인 createResult 메서드에서 draw로 반환해줄 수 있는 부분이라고 생각되는데 수달은 어떻게 생각하나요??

추가로 블랙잭 규칙에서 한 플레이어가 블랙잭이면 블랙잭이 아닌 모든 참가자는 전원 패배를 한다고 알고 있습니다!! 해당 규칙이 적용 가능하게 작성되어 있는지 한번 확인해보면 좋을 것 같아요!!

2022-03-19 03:25 UTC, her0807 commented on src/main/java/blackjack/Application.java
>      }
사용성에 대해서 고민하면서 예외처리를 신경쓰지 않았다니 .. 😵‍💫 
이번에 페어랑 예외 처리는 나중에 구현하고, 비지니스로직에 집중하자. 라고 정하고 진행했었는데
페어가 깨진 후에 구현한다는 것을 빼먹었네요 ㅠㅠ 

부족한 부분을 알려주셔서 감사합니다.

2022-03-19 04:31 UTC, her0807 commented on src/main/java/blackjack/domain/BettingMoney.java
> +    public static final int BETTING_MONEY_INIT_VALUE = 0;
오오 ~ 정말 좋은 생각이네요💡

2022-03-19 06:26 UTC, her0807 commented on src/main/java/blackjack/Application.java
>      }
오오 .. 그렇네요. 우선 반복문은 최초 한번은 무조건 실행 되었으면 좋겠다는 생각에 작성했던 것인다.
` while 이 아니라 do while 을 사용`해서 로직을 변경해보겠습니다. 메서드도 분리하구요!

2022-03-19 07:07 UTC, her0807 commented on src/main/java/blackjack/domain/Cards.java
> +    private int convertCloseWin(int totalScore) {
오오,,. 😯  그렇다면 `convertToClosestBlackJackScore` 로 변경하겠습니다

2022-03-19 07:24 UTC, her0807 commented on src/main/java/blackjack/domain/Dealer.java
> +    public boolean calculateBattingMoneyResult(Gamer player) {
헙 그렇군요 .. !! `changeByBettingMoneyResult`로 메서드명에 구체적인 설명을 추가했습니다.

2022-03-19 11:11 UTC, her0807 reviewed
안녕하세요 스티치! ㅎㅎ 
즐거운 주말입니다. :)

스티치 덕분에 부족한 점이 많이 보완되어 기쁘네요. 
현재 리뷰해주신 부분은 대부분 개선을 해 놓은 상태입니다.

2단계가 끝나면 추후로 상태패턴을 적용해볼까 합니다 👍🏻

2022-03-19 11:11 UTC, her0807 commented on src/main/java/blackjack/domain/Player.java
> +        if (isBlackJack() && !dealer.isBlackJack()) {
둘다 블랙잭일 때는 무승부로 result 가 반환되도록 설정했습니다.

2022-03-19 11:11 UTC, her0807 commented on src/main/java/blackjack/domain/Players.java
> +        if (!hasBlackJack()) {
플레이어들에게 카드를 한장씩 받을건지 물어보기 전, 
플레이어 중 한명이라도 블랙잭이라면 바로 종료되도록 조건을 추가했습니다.

2022-03-19 11:12 UTC, her0807 commented on src/main/java/blackjack/domain/Player.java
> +        }
오호 ~ 둘다 블랙잭일때 애초에 결과값을 무승부로 보낸다는 아이디어, 정말 좋네요! ㅎㅎㅎ
관련 로직은 작성 후 코멘트 달아두겠습니다. 감사합니다.

2022-03-20 03:10 UTC, lxxjn0 approved these changes
수달, 블랙잭 미션 진행한다고 수고 많으셨습니다 😄 

제가 코맨트 남긴 부분 이외로 추가로 수정할만한 부분이 이제 없어보입니다!! 👍🏼 전체적으로 객체들이 적절한 책임을 가지고 분리되어 있고 mvc 패턴의 형식으로 구조도 잘 나뉘어져 있어서 코드가 읽기 편하고 좋았어요!!

수정 필요한 부분만 수정하고 리뷰 요청하시면 바로 머지하도록 할게요!! 그간 미션 진행하시느라 수고 많으셨습니다!! 👍🏼 다음에 더 발전한 수달을 다시 뵙길 기대할게요 ㅎㅅㅎ

2022-03-20 03:10 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Dealer.java
> +        addMoney(reversBettingMoney((Player) player));
reversBettingMoney 메서드 명이 오타가 난 것 같은데 맞을까요??

2022-03-20 03:10 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Player.java
> +        if (isBlackJack() && !dealer.isBlackJack()) {
현재 로직에서는 딜러만 블랙잭인 경우에 대해서 처리가 안될 것 같아요!! 단순히 21점만 비교하면 딜러가 블랙잭, 플레이어가 3장의 카드를 가져서 21점 인 경우가 동점으로 처리가 됩니다!! 해당 부분의 로직을 한번 확인해보면 좋을 것 같아요!!

2022-03-20 03:10 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Player.java
> +        addMoney((int) result);
long 타입을 int 타입으로 강제 변경하면 오버플로우에 대한 대응이 어렵게 됩니다!! Math 클래스에 이를 처리해주는 메서드가 있는데 한번 참고해보시면 좋을 것 같아요!!!

2022-03-20 03:10 UTC, lxxjn0 requested changes
앗 모르고 approve로 해서 다시 request changes로 변경할게요!!

2022-03-20 06:01 UTC, her0807 commented on src/main/java/blackjack/Application.java
>      }
스티치 .. 대단하신데요?

계속 같은 로직을 보다보니 점점 눈이 흐려지는지.. 개선점이 안보였는데 
친절한 예시와 함께 설명해주셔서 훨씬 간결한 코드가 되었네요! 

리팩토링하겠습니다 :)

2022-03-20 06:22 UTC, her0807 commented
스티치와 2주간 대화, 정말 즐거웠습니다!!! 다음에 또 부탁드립니다 ㅎㅎㅎㅎ  !!!!!👍🏻

2022-03-21 12:50 UTC, lxxjn0 approved these changes
수달, 블랙잭 미션 진행하느라 수고 많으셨습니다!! 즐거운 시간이었네요 :)
이번 미션은 여기서 머지할게요 😄

2022-03-21 12:51 UTC, merged