[2단계 - 블랙잭(베팅)] 알파(배철환) 미션 제출합니다.
woowacourse/java-blackjack pull request #325
Opened 2022-03-17 06:56 UTC by bcc0830

안녕하세요 핀! 알파입니다!
 1단계에서 도메인 규칙을 숙지하지 못해서 너무나 죄송스럽게 생각합니다.. 이번 2단게에서는 확실히 도메인 규칙을 숙지하여 작성하였고, 부족하게나마 핀이 1단계에서 가르쳐 주신 것들을 최대한 반영하려 노력하였습니다! 늘 감사합니다!

2022-03-17 10:21 UTC, lalize requested changes
안녕하세요 알파!
리뷰 남겨두었으니 확인하여 반영 부탁드릴게요!

2022-03-17 10:21 UTC, lalize commented on src/main/java/blackjack/domain/BettingToken.java
> +	}
베팅 금액이 수익률을 알고, 수익을 계산하는 책임을 갖는게 적절한가요?

2022-03-17 11:43 UTC, bcc0830 commented on src/main/java/blackjack/controller/BlackJackGameController.java
>  	private void initializeCard(Players players, Dealer dealer, Deck deck) {
추가하였습니다

2022-03-17 11:43 UTC, bcc0830 commented on src/main/java/blackjack/controller/BlackJackGameController.java
>  	private void progressDealerTurn(Players players, Dealer dealer, Deck deck) {
추가하였습니다

2022-03-17 11:46 UTC, bcc0830 commented on src/main/java/blackjack/domain/BettingToken.java
> +	private final int money;
수정하였습니다

2022-03-17 12:34 UTC, bcc0830 commented on src/main/java/blackjack/domain/Gamer.java
> +	protected abstract boolean isWinByBust(Gamer gamer);
수정하였습니다

2022-03-17 12:35 UTC, bcc0830 commented on src/main/java/blackjack/domain/Name.java
> +	}
삭제하였습니다

2022-03-17 12:35 UTC, bcc0830 commented on src/main/java/blackjack/domain/Player.java
>  	}
삭제하였습니다

2022-03-17 12:35 UTC, bcc0830 commented on src/main/java/blackjack/domain/Gamer.java
> +	}
삭제하였습니다

2022-03-18 05:07 UTC, bcc0830 commented on src/main/java/blackjack/domain/Player.java
> +		super(new Cards(), name);
수정하였습니다

2022-03-18 05:07 UTC, bcc0830 commented on src/main/java/blackjack/domain/Cards.java
> +		if (cards.stream().anyMatch(Card::isAce) && score + ACE_SCORE_DIFFERENCE <= BUST_THRESHOLD) {
수정하였습니다

2022-03-18 05:07 UTC, bcc0830 commented on src/main/java/blackjack/domain/Result.java
>  public class Result {
수정하였습니다

2022-03-18 05:08 UTC, bcc0830 commented on src/main/java/blackjack/domain/BettingToken.java
> +	}
베팅 금액과 수익 계산을 제안해주신대로 분리하였습니다

2022-03-18 05:10 UTC, bcc0830 commented on src/main/java/blackjack/domain/BettingToken.java
> +	private int profit = 0;
이익이 베팅금액에서 파생되기 때문에 필드로 가지면 베팅 금액에서 처리하면 용이할 것이라는 판단이었습니다
그러나, 실제 생활에서 이자는 원금에 이자율을 곱해야 알 수 있듯이, 수익도 베팅 금액에 수익률을 곱해야 하기 때문에 원금에 해당하는 베팅 금액이 이자율에 해당하는 수익률을 안다는 게 맞지 않다고 생각합니다

2022-03-18 19:14 UTC, lalize requested changes
안녕하세요 알파!
몇 가지 리뷰 남겨두었으니 확인 부탁드릴게요~

2022-03-18 19:16 UTC, lalize commented on src/main/java/blackjack/domain/process/BettingResult.java
> +	public static BettingResult of(Players players, Dealer dealer, BettingTokens bettingTokens) {
https://github.com/woowacourse/java-blackjack/pull/325#discussion_r830275461

2022-03-18 19:16 UTC, lalize commented on src/main/java/blackjack/domain/process/MatchResult.java
> +	public static MatchResult of(Players players, Dealer dealer) {
https://github.com/woowacourse/java-blackjack/pull/325#discussion_r830275461

2022-03-19 06:39 UTC, bcc0830 commented on src/main/java/blackjack/domain/gamer/Players.java
> +		this.players.addAll(players);
수정하였습니다

2022-03-19 06:39 UTC, bcc0830 commented on src/main/java/blackjack/domain/betting/BettingTokens.java
> +	}
BettingTokens 삭제하였습니다

2022-03-19 06:39 UTC, bcc0830 commented on src/main/java/blackjack/domain/betting/BettingTokens.java
> +	}
BettingTokens 삭제하였습니다

2022-03-19 06:39 UTC, bcc0830 commented on src/main/java/blackjack/domain/betting/BettingTokens.java
> +	private final List<BettingToken> bettingMonies;
수정하였습니다

2022-03-19 06:39 UTC, bcc0830 commented on src/main/java/blackjack/domain/process/MatchResult.java
> +			Match.LOSE);
수정하였습니다

2022-03-19 06:39 UTC, bcc0830 commented on src/main/java/blackjack/domain/process/BettingResult.java
> +		Map<Player, Match> matchResultCache = MatchResult.of(players, dealer).getPlayersMatchCache();
수정하였습니다

2022-03-19 06:39 UTC, bcc0830 commented on src/main/java/blackjack/domain/gamer/Gamer.java
> +			&& this.getScore() == gamer.getScore()) || this.isBlackJack() && gamer.isBlackJack();
수정하였습니다

2022-03-19 06:40 UTC, bcc0830 commented on src/main/java/blackjack/domain/betting/Profit.java
> +	}
아래의 코드로 수정하였습니다

2022-03-19 06:40 UTC, bcc0830 commented on src/main/java/blackjack/domain/gamer/Player.java
> +		if (!this.isBlackJack() && !gamer.isBlackJack() && !this.isBust() && !gamer.isBust()){
수정하였습니다

2022-03-19 06:40 UTC, bcc0830 commented on src/main/java/blackjack/domain/process/BettingResult.java
> +	public static BettingResult of(Players players, Dealer dealer, BettingTokens bettingTokens) {
수정하였습니다

2022-03-19 06:40 UTC, bcc0830 commented on src/main/java/blackjack/domain/process/MatchResult.java
> +	public static MatchResult of(Players players, Dealer dealer) {
MatchResult 삭제하였습니다

2022-03-20 13:17 UTC, lalize requested changes
알파 안녕하세요!
리뷰 남겨두었으니 확인하여 반영 부탁드릴게요!
궁금한 점 있으시면 DM, 코멘트 남겨주세요~

2022-03-20 13:17 UTC, lalize commented on src/main/java/blackjack/domain/gamer/Gamer.java
> +	}
컨벤션상 getter는 일반 메서드보다 아래에 위치하도록 합니다.
기본 들여쓰기도 4 tab이 아니라 4 space입니다!
우아한테크코스 자바 스타일 가이드 적용 후 전체 코드에 대해 반영 부탁드릴게요!
* [우아한테크코스의 자바 스타일 가이드](https://github.com/woowacourse/woowacourse-docs/tree/master/styleguide/java)

```suggestion
        public boolean isBust() {
		return this.cards.isBust();
	}

	public boolean isBlackJack() {
		return this.cards.isBlackJack();
	}
	
	public List<Card> getCards() {
		return this.cards.getCards();
	}

	public int getScore() {
		return this.cards.getScore();
	}

	public String getName() {
		return this.name.getName();
	}
```

2022-03-20 13:17 UTC, lalize commented on src/main/java/blackjack/domain/process/BettingResult.java
> +		bettingResult.put(this.dealer, Profit.of(Match.NONE, NEGATE * profits.stream()
딜러의 수익을 구하기 위해 Match.NONE 타입이 생긴 것 같은데요!
해당 부분 없이 구할 방법은 없을까요?

2022-03-20 13:17 UTC, lalize commented on src/main/java/blackjack/domain/process/BettingResult.java
> +			.map(player -> Profit.of(Match.of(player, this.dealer), player.getBettingToken().getMoney()))
`player.getBettingToken().getMoney()` 값을 꺼내지 말고 메시지를 보내는 건 어떨까요?
player를 전달하고 실제 계산하는 시점에 `player.earnings(rate)` 처럼 메시지를 보낼 수도 있을 것 같아요.

2022-03-21 07:46 UTC, bcc0830 commented on src/main/java/blackjack/domain/process/BlackJackGame.java
> +	}
수정하였습니다

2022-03-21 07:46 UTC, bcc0830 commented on src/main/java/blackjack/controller/BlackJackGameController.java
>  		outputView.displayNewLine();
수정하였습니다

2022-03-21 07:47 UTC, bcc0830 commented on src/main/java/blackjack/domain/betting/BettingToken.java
> +		this.money = 0;
수정하였습니다. 단, 주 생성자의 validate에 의거하여 최소 금액인 100원으로 money를 설정하였습니다

2022-03-21 07:47 UTC, bcc0830 commented on src/main/java/blackjack/domain/card/CardDenomination.java
>  public enum CardDenomination {
수정하였습니다

2022-03-21 07:47 UTC, bcc0830 commented on src/main/java/blackjack/domain/card/Cards.java
> +		if (hasAce && score + ACE_SCORE_DIFFERENCE <= BUST_THRESHOLD) {
수정하였습니다

2022-03-21 07:47 UTC, bcc0830 commented on src/main/java/blackjack/domain/card/Deck.java
> +	public int getCardsSize() {
수정하였습니다

2022-03-21 07:48 UTC, bcc0830 commented on src/main/java/blackjack/domain/gamer/Dealer.java
> +		return this.cards.getRandomCard();
Cards에서 getCards라는 메소드가 이미 존재하기 때문에 딜러의 책임으로 바꿔도 충분하다고 생각합니다.

2022-03-21 07:48 UTC, bcc0830 commented on src/main/java/blackjack/domain/gamer/Gamer.java
> +	}
수정하였습니다

2022-03-21 07:48 UTC, bcc0830 commented on src/main/java/blackjack/domain/process/BettingResult.java
> +		bettingResult.put(this.dealer, Profit.of(Match.NONE, NEGATE * profits.stream()
수정하였습니다

2022-03-21 07:50 UTC, bcc0830 commented on src/main/java/blackjack/domain/process/BettingResult.java
> +			.map(player -> Profit.of(Match.of(player, this.dealer), player.getBettingToken().getMoney()))
Profit에 이미 Match와 베팅금액을 가지고 있기 때문에 굳이 player에게 메세지를 보내지 않아도 Profit에 메세지를 보내면 충분히 계산이 가능하다고 생각합니다. 필드로 Player를 가지면 어떨까 생각을 해봤는데 그렇게 된다면 딜러의 입장에서 수익을 구할 때 문제가 된다고 생각합니다. 
 다만, 현재 getter를 두번쓰기보다는 바로 int값을 가져오도록 수정하였습니다

2022-03-21 07:53 UTC, bcc0830 commented on src/main/java/blackjack/domain/gamer/Dealer.java
> +	}
```java
    public Dealer(Cards cards) {
        super(cards, new Name(DEALER_NAME));
    }

    public Dealer() {
        this(new Cards());
    }
```

위와 같이 변경하였으나, 주 생성자가 아직도 부모의 생성자를 호출하는데, 개인적으로 어떻게 구현해야 할 지 감이 오질 않습니다. 개인적으로 cards를 Player와 Dealer에게 각각 private 필드로 설정하면 Gamer에서는 name 필드만 있기 때문에 다른 규칙이 생겨도 대응이 가능하다고 생각되나, 이렇게 되면 중복되는 필드가 있어서 자칫 Gamer를 부모로 뺀 의미가 퇴색될 수도 있다고 생각합니다. 혹시 힌트를 조금 더 주실 수 있으실까요?

2022-03-22 00:02 UTC, lalize approved these changes
알파 안녕하세요!
블랙잭 구현 고생많으셨어요~
이번 미션은 여기서 마무리 하도록 할게요!
다음 미션도 화이팅 입니다!!

2022-03-22 00:03 UTC, merged