[2단계 - 블랙잭(베팅)] 매트(최기현) 미션 제출합니다.
woowacourse/java-blackjack pull request #326
Opened 2022-03-17 07:01 UTC by hyeonic

안녕하세요 럿고! 매트입니다. 😃

**🚀 2단계 - 블랙잭(베팅)** 에 요구사항이 추가되었습니다!

우선 1단계에서 머지와 함께 남겨주신 코멘트는 아래와 같이 반영하였습니다.

---

> [String의 비교를 한번 찾아보시면 어떨까요? ==을 사용하는게 좋을지 equal을 사용하면 좋을지요 :)](https://github.com/woowacourse/java-blackjack/pull/237#discussion_r827009978)

요구사항이 변경되어 이전 승패 판단을 위한 enum이 변경되었습니다! 해당 로직은 이제 BettingResult가 담당하게 되었습니다.

--- 

> [final static](https://github.com/woowacourse/java-blackjack/pull/237#discussion_r827010325)

언급해주신 것 처럼 final과 static 키워드의 위치를 변경하였습니다.
```java
private static final Scanner SCANNER = new Scanner(System.in);
```

---

> [생성자도 protected로 접근제어자를 변경해보면 어떨까요?](https://github.com/woowacourse/java-blackjack/pull/237#discussion_r827010759)

생성자의 접근제어자를 protected로 사용하여 상속 받은 Player와 Dealer만 사용할 수 있도록 제한하였습니다. 추가적으로 Participant에서 선언한 인스턴스 변수들을 접근제어자를 private으로 제한하고 해당 변수를 사용하는 메서드를 Participant 내부로 이동하여 이전 보다 캡슐화를 잘 지킬 수 있도록 개선하였습니다!

Player와 Dealer의 가장 큰 차이점은 카드를 뽑을 수 있는 hit가 가능한 카드 합산 점수라고 판단합니다. 해당 기능을 제외하고 대부분의 기능을 공통적으로 사용하고 있기 때문에 차이점 부분만 abstract 메서드를 활용하여 추상화를 진행하였습니다. 

`상속이 적절한 경우`는 클래스의 행동을 확장(extend)하는 것이 아니라 `정제(refine)`할 때라고 학습한 경험이 있습니다. 정제란 부분적으로 불완전한 행동을 완전하게 만드는 것이라고 이해하였습니다. 

해당 학습 내용을 기반으로 Player와 Dealer는 불완전한 `canHit` 메서드를 `정제`라는 과정을 통해 온전한 객체를 만들도록  의도 하였습니다. 이것이 적절히 상속을 이해하고 사용한 것인지 질문드립니다! 

---

> [딜러가 16이하인데, 카드를 받지 않네요? 정책을 다시 확인인해보면 어떨까요?](https://github.com/woowacourse/java-blackjack/pull/237#discussion_r827013336)

while을 재귀로 개선하던 중 누락된 부분이 있었습니다. 확인하여 반영하였습니다!

```java
public class BlackjackRunner {
    ...
    private void drawDealer(Deck deck, Dealer dealer) {
        if (dealer.canHit()) {
            dealer.append(deck.draw());
            OutputView.printDealerDrawable();
            drawDealer(deck, dealer); // 누락된 부분
        }
    }
    ...
}
```

---

> [Players에도 테스트 코드를 추가해보면 어떨까요?](https://github.com/woowacourse/java-blackjack/pull/237#discussion_r827014742)

언급하신대로 Players의 책임을 정리하여 필요한 테스트 코드를 작성하였습니다!

```java
class PlayersTest {

    @DisplayName("플레이어는 1명 이상이어야 한다.")
    @Test
    void 플레이어들_생성() {
        assertDoesNotThrow(() -> new Players(new Deck(new RandomCardsGenerator()), generatePlayers()));
    }

    @DisplayName("플레이어는 1명 이상이어야 한다. 1명 보다 작은 경우 예외를 던진다.")
    @Test
    void 플레이어들_생성_실패() {
        assertThatThrownBy(() -> new Players(new Deck(new RandomCardsGenerator()), Map.of()))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("플레이어는 최소 1명입니다.");
    }
}
```

---

> ["," 매직스트링!](https://github.com/woowacourse/java-blackjack/pull/237#discussion_r827018078)

매직 스트링 확인 후 상수로 변경하였습니다!

```java
public class InputView {

    private static final String SPLIT_REGEX = ",";
    ...
}
```

---

> [System.lineSeparator() 이걸 한번 알아보면 어떠신가요?](https://github.com/woowacourse/java-blackjack/pull/237#discussion_r827018790)

`System.lineSeparator()`은 JDK 1.7부터 제공되며 프로그램이 실행되는 OS에 따라 적합한 개행 문자를 리턴해주는 것을 확인했습니다. Java에서 이러한 메서드를 제공하는 이유는 윈도우(\r\n), 맥(\r), 유닉스(\n)과 같은 운영체제 별로 개행문자를 다르게 해석하기 때문이라고 생각합니다. 

더 나아가 자동으로 개행을 작성해주는 `System.out.println()` 메서드의 내부도 살펴보았습니다. 내부 로직을 따라가다 보면 newLine 부분에서 `System.lineSeparator()`을 활용하여 줄바꿈을 진행하는 것을 확인하였습니다!

```java
public class BufferedWriter extends Writer {
    ...
    public void newLine() throws IOException {
        write(System.lineSeparator());
    }
    ...
}
```

이 밖에도 제가 놓친 부분이나 좋지 않은 습관 등 피드백 주시면 적극 반영 하겠습니다! 이번 리뷰도 잘 부탁드립니다. 감사합니다! 🙏

2022-03-17 23:58 UTC, ksy90101 requested changes
안녕하세요 :) 매트 리뷰어 럿고입니다.
2단계 진행하시느라 고생 많으셨습니다 💯 
1단계 마지막 피드백도 잘 적용해주시고, 의견도 잘 남겨주셨네요.

간단한 피드백을 남겼으니, 확인해주시면 감사하겠습니다!

2022-03-17 23:58 UTC, ksy90101 commented on src/test/java/blackjack/domain/participant/PlayerTest.java
> +        assertThat(bettingMoney).isEqualTo(0);
0을 비교할때는 isZero()라는 메서드도 있습니다 :) 어떤게 더 가독성이 좋을지는 매트가 고민해보세요 :)

2022-03-17 23:58 UTC, ksy90101 commented on src/main/java/blackjack/domain/BettingResult.java
> +                .findAny()
findFirst()가 더 맞지 않을까요?

2022-03-17 23:58 UTC, ksy90101 commented on src/main/java/blackjack/domain/participant/BettingMoney.java
> +        return new BettingMoney(amount.multiply(BigDecimal.valueOf(percent)));
복잡성이 조금 있어보이네요.
가독성을 조금 높여보이시겠어요?
예를들면, 인자를 변수로 빼서 처리할수 잇을거 같아요.

2022-03-17 23:58 UTC, ksy90101 commented on src/main/java/blackjack/domain/participant/BettingMoney.java
> +    private final BigDecimal amount;
BigDecimal을 선택하신 이유가 있나요?

2022-03-17 23:58 UTC, ksy90101 commented on src/main/java/blackjack/domain/participant/Participant.java
> +    protected Participant(String name, List<Card> cards) {
👍

2022-03-17 23:58 UTC, ksy90101 commented on src/main/java/blackjack/domain/participant/Player.java
> +        return BettingResult.of(this, dealer).getResult(bettingMoney);
디미터의 법칙을 위반한거 같은데, 한번 확인해주세요.
https://mangkyu.tistory.com/147

2022-03-17 23:58 UTC, ksy90101 commented on src/main/java/fuel/RentCompany.java
> +        return car.getName() + " : " + (int) car.getChargeQuantity() + "리터" + "\n";
여기도 System.lineSeparator();이걸 쓰면 어떠신가요?

2022-03-17 23:58 UTC, ksy90101 commented on src/test/java/blackjack/domain/PlayerTestDataGenerator.java
> +public class PlayerTestDataGenerator {
👍

2022-03-19 05:35 UTC, hyeonic commented on src/main/java/fuel/RentCompany.java
> +        return car.getName() + " : " + (int) car.getChargeQuantity() + "리터" + "\n";
확인 못하고 누락됬네요 ㅜㅠ 바로 수정하겠습니다.

2022-03-19 05:41 UTC, hyeonic commented on src/main/java/blackjack/domain/participant/Player.java
> +        return BettingResult.of(this, dealer).getResult(bettingMoney);
디미터 법칙을 잘 지키도록 수정하였습니다!

```java
public class Player extends Participant {
    ...
    public int calculateProfit(Participant dealer) {
        double earningRate = state.earningRate(dealer.state);
        BettingMoney profit = bettingMoney.times(earningRate);
        return profit.getAmount();
    }
}
```

한 가지 궁금한 점이 있습니다! 로직 상에는 단순히 변수로 꺼내어 실행하는 차이만 존재하는 것 같은데 단순히 가독성을 위해서만 디미터를 적용한 경우가 되는 건가요??

2022-03-19 05:45 UTC, hyeonic commented on src/main/java/blackjack/domain/participant/BettingMoney.java
> +    private final BigDecimal amount;
배팅 머니라서 돈이라는 도메인을 다루기 위해 BigDecimal을 사용하였습니다. Java에서 실수는 기본적으로 부동 소수점 방식을 활용하기 때문에 연산 시 정확한 답을 보장하지 않는다고 학습한 경험이 있습니다. 다양한 승리 조건에 따라 1.5, 1, 0 등을 곱해야 하기 때문에 단순히 double로 연산하게 될 경우 소중한 돈이 변경될 것을 우려하여 BigDecimal을 사용하였습니다!

2022-03-19 05:48 UTC, hyeonic commented on src/main/java/blackjack/domain/participant/BettingMoney.java
> +        return new BettingMoney(amount.multiply(BigDecimal.valueOf(percent)));
말씀대로 가독성을 위해 적절히 수정하였습니다!

```java
public class BettingMoney {
    ...
    public BettingMoney times(double percent) {
        BigDecimal multiplied = BigDecimal.valueOf(percent);
        BigDecimal result = amount.multiply(multiplied);
        return new BettingMoney(result);
    }
}
```

2022-03-19 05:50 UTC, hyeonic commented on src/main/java/blackjack/domain/BettingResult.java
> +                .findAny()
이번에 상태 패턴을 도입하며 해당 클래스의 역할이 사라져 삭제하였습니다! 언급하신 것 처럼 `findFirst()`와 `findAny()`의 차이점에 대해 학습하겠습니다!

2022-03-19 05:51 UTC, hyeonic commented on src/test/java/blackjack/domain/participant/PlayerTest.java
> +        assertThat(bettingMoney).isEqualTo(0);
검증에 활용할 수 있는 다양한 메서드가 많네요.. 꾸준히 학습하면서 다양한 메서드를 활용하겠습니다! 럿고가 말씀하신 것 처럼 0을 그대로 사용하는 것 보다 훨씬 가독성이 좋은 것 같아요! 😀

2022-03-19 06:12 UTC, hyeonic commented
안녕하세요 럿고! 매트입니다! 😀

앞서 주신 리뷰는 코멘트 아래 남겨두었습니다!

추가적으로 금요일 블랙잭 피드백 수업을 진행하며 `상태 패턴`에 대해 알게 되었습니다! 아래는 제가 이해한 것을 바탕으로 상태 패턴에 대해 간단히 정리한 것입니다.

> 상태 패턴은 특정 기능을 수행한 뒤 다음 상태를 반환하는 것이다. 동일한 메서드가 상태에 따라 다르게 동작할 수 있도록 별도의 하위 타입으로 구현한다. 같은 기능을 단순히 조건문을 활용할 경우 상태가 추가될 때마다 조건문도 함께 추가된다. 하지만 상태 패턴을 사용하게 될 경우 코드의 복잡도가 증가하지 않고 상태를 추가할 수 있다.

아래는 이번 미션에 실제 적용한 상태 패턴입니다. 가지고 있는 카드의 점수를 기반으로 현재 상태를 판단하여 다음 상태를 반환하는 방식으로 구현하였습니다.

### State Interface
필요한 공통 상태를 선언한 인터페이스입니다.
```java
public interface State {

    State draw(Card card);

    State stay();

    boolean isRunning();

    boolean isFinished();

    Cards cards();

    double earningRate(State state);
}
```

해당 인터페이스를 기반으로 적절한 상태를 하위 클래스로 만들어 구현하였습니다. 상태 패턴을 적용한 클래스들의 다이어그램은 아래와 같습니다. 

![image](https://user-images.githubusercontent.com/59357153/159109492-3677601f-6009-4abd-8d8a-cd13684426ef.png)

모든 상태의 시작이 `Ready`가 될 수 있도록 나머지 상태는 `protected`로 외부 생성을 제한하였습니다! 

```java
public class Blackjack extends Finished {

    protected Blackjack(Cards cards) {
        super(cards);
    }
    ...
}
```

또한 중간에 공통 상태(Finished)를 추상 클래스로 묶어 공통적인 행위들을 final로 지정하여 상속 받은 하위 타입이 다시 오버라이딩 할 수 없도록 제한하였습니다!

```java
public abstract class Finished extends Started {

    protected static final double BLACKJACK_WIN_RATE = 1.5;
    protected  static final int WIN_RATE = 1;
    protected static final int TIE_RATE = 0;
    protected static final int LOW_RATE = -1;

    protected Finished(Cards cards) {
        super(cards);
    }

    @Override
    public final State draw(Card card) {
        throw new IllegalStateException("카드를 뽑을 수 없는 상태입니다.");
    }

    @Override
    public final State stay() {
        throw new IllegalStateException("스테이 상태로 변경할 수 없습니다.");
    }

    @Override
    public final boolean isRunning() {
        return false;
    }

    @Override
    public final boolean isFinished() {
        return true;
    }
}
```

이 밖에도 제가 놓친 부분이나 좋지 않은 습관 등 피드백 주시면 적극 반영 하겠습니다! 감사합니다!

![image](https://img1.daumcdn.net/thumb/R800x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FdlIuQA%2FbtqDp1Uj6Jq%2FCMYEGtDakNmQMQRZqJUnrk%2Fimg.gif)

2022-03-20 03:09 UTC, ksy90101 commented on src/main/java/blackjack/domain/BlackjackRunner.java
> +        if (!dealer.isFinished()) {
명명이 조금 안좋은거 같아요.
dealer는 끝났냐? 이렇게 해석이 될거 같은데, 어떻게 생각하실까요?
좀 더 가독성이 높게 이름을 지어보시면 좋을거 같아요.

2022-03-20 03:11 UTC, ksy90101 commented on src/main/java/blackjack/domain/card/Cards.java
> +        this(new ArrayList<>());
```
this(Collections.emptyList());
```
이런식으로 작성이 불가능 할까요?

2022-03-20 03:25 UTC, ksy90101 requested changes
매트 안녕하세요 :)
상태패턴 적용한 이야기 너무 잘 봤습니다.
피드백도 적용하시느라, 너무 고생 많으셨어요 💯 
좀 더 피드백을 남겼는데, 확인해주시면 감사하겠습니다!

질문은 언제든지 환영입니다~

2022-03-20 03:25 UTC, ksy90101 commented on src/main/java/blackjack/domain/participant/BettingMoney.java
> +    private final BigDecimal amount;
좋은 근거입니다~ 👍

2022-03-20 03:25 UTC, ksy90101 commented on src/main/java/blackjack/domain/participant/Dealer.java
> +        super(new Name(DEALER_NAME), new Ready());
new Name("딜러"); 자체를 상수로 관리해도 될듯 한데, 혹시 어떻게 생각하실까요?

2022-03-20 03:25 UTC, ksy90101 commented on src/main/java/blackjack/domain/participant/Dealer.java
> +        return getTotalScore() > 16;
원래 상수화가 되어 있었는데, 다시 매직넘버로 돌아왔네요 👀

2022-03-20 03:25 UTC, ksy90101 commented on src/main/java/blackjack/domain/participant/Name.java
> +        validate();
별건 아닌데요. 한번 찾아보셨으면 좋겠습니다.
필드로 할당한 다음 validate가 더 좋은지? 아니면 할당하기 전에 더 좋을지?
아울러 일반적으로 Validate는 언제 하는지?

2022-03-20 03:25 UTC, ksy90101 commented on src/main/java/blackjack/domain/participant/Players.java
> +}
```suggestion
}

```

2022-03-20 03:25 UTC, ksy90101 commented on src/main/java/blackjack/domain/state/Stay.java
> +        return LOW_RATE;
이렇게 if문을 쓰지 않고 가능할거 같은데요.
예를들면 enum같은게 있을꺼 같아요.
혹시 매트는 enum으로 관리해서 좀더 편리하게 쓰는게 좋을까요? 아니면 지금처럼 이렇게 두는게 좋을까요?
(이건 무조건적으로 변경하라는 이야기가 아니라 매트의 의견을 듣고 싶습니다!)

2022-03-20 03:25 UTC, ksy90101 commented on src/main/java/blackjack/view/InputView.java
> +            return Integer.parseInt(SCANNER.nextLine());
Integer 범위 이상을 입력하면 어떻게 될까요?
BattingMoney가 아무리 BigDecimal이라고 해서, 모든 금액을 받을수 있을까요?

2022-03-20 03:25 UTC, ksy90101 commented on src/main/java/blackjack/dto/PlayerResult.java
> +    private final int profit;
<img width="642" alt="image" src="https://user-images.githubusercontent.com/53366407/159146657-f3c01aee-f221-4bc1-b2e9-d25e6bdce779.png">

이 결과값을 참고해보시고, 변경해볼까요요?

2022-03-20 03:25 UTC, ksy90101 commented on src/main/java/blackjack/view/OutputView.java
> +                .collect(joining(", "));
"," 이것도 상수로 뺴면 어떨까요~?

2022-03-20 03:25 UTC, ksy90101 commented on src/main/java/blackjack/view/OutputView.java
> +    }
getter를 이렇게 쓰는게 아니라 card에게 DenominationName이 뭔지 알게 한다면 더 좋지 않을까 합니다 :)
```suggestion
    private static String generateCardMessage(Card card) {
        return card.getDenomination() + card.getSuit();
    }
```
이렇게 되어야 하지 않을까 합니다 :)

2022-03-20 03:25 UTC, ksy90101 commented on src/test/java/blackjack/domain/CardFixtures.java
> +public class CardFixtures {
👍

2022-03-20 11:22 UTC, hyeonic commented on src/main/java/blackjack/domain/BlackjackRunner.java
> +        if (!dealer.isFinished()) {
말씀하신 것 처럼 끝났는지 물어보는 것은 어색하다고 판단하여 이전에 작성한 것과 유사하게 더 뽑을 수 있는지를 의미하는 `isDrawable`로 변경하였습니다! 내부 구현의 경우 이전과 반대되도록 반환할 수 있도록 변경하였습니다.

2022-03-20 11:26 UTC, hyeonic commented on src/main/java/blackjack/domain/card/Cards.java
> +        this(new ArrayList<>());
[Collections.emptyList() vs. New List Instance](https://www.baeldung.com/java-collections-emptylist-new-list)

해당 글을 기반으로 `Collections.emptyList()`에 대해 학습하였습니다. 현재 비어있는 리스트를 전달하여 주 생성자에서new 키워드를 통해 새롭게 생성하고 있기 때문에 명시적으로 빈 목록을 만들고 싶을 때 의도를 더 잘 표현할 수 있는 `Collections.emptyList()`로 변경하였습니다!

2022-03-20 11:29 UTC, hyeonic commented on src/main/java/blackjack/domain/participant/Dealer.java
> +        super(new Name(DEALER_NAME), new Ready());
객체 자체를 상수로 선언하는 것이 아직 익숙치 않아 생각하지 못한 방법 이네요! 말씀하신 것 처럼 딜러 네임 객체 자체를 상수로 선언하여 개선하였습니다!

```java
public class Dealer extends Participant {

    private static final Name DEALER_NAME = new Name("딜러");

    public Dealer() {
        super(DEALER_NAME, new Ready());
    }
    ...
}
```

2022-03-20 11:30 UTC, hyeonic commented on src/main/java/blackjack/domain/participant/Dealer.java
> +        return getTotalScore() > 16;
기존 코드를 전부 삭제하고 작성하는 과정에서 누락된 것 같습니다 😂  다시 확인 후 상수로 추출하였습니다!

2022-03-20 11:37 UTC, hyeonic commented on src/main/java/blackjack/domain/participant/Name.java
> +        validate();
이펙티브 자바 `아이템 50. 적시에 방어적 복사본을 만들어라`를 읽고 학습한 내용을 기반으로 작성 히였습니다! 

###  매개변수의 유효성 검사 전 방어적 복사본을 만들고, 복사본으로 유효성 검사
멀티스레드 환경에서 원본 객체의 유효성 검사 후 복사본을 만드는 찰나에 다른 스레드가 원본 객체를 수정할 위험이 있다. 이러한 공격을 검사시점/사용시점(time-of-check/time-of-use) 공격 혹은 TOCTOU 공격이라고 한다.

이러한 근거를 기반으로 할당 이후 검증을 진행하였습니다! 물론 해당 미션이 멀티스레드 환경을 염두 하며 작성한 것은 아니지만 추가적인 학습을 통해 얻은 지식들을 적용 하였습니다.

2022-03-20 11:39 UTC, hyeonic commented on src/main/java/blackjack/domain/participant/Players.java
> +}
개행 추가하였습니다!

2022-03-20 12:14 UTC, hyeonic commented on src/main/java/blackjack/domain/state/Stay.java
> +        return LOW_RATE;
만약 enum으로 변경하게 되면 `Blackjack`과 `Bust`, `Stay`가 해당 enum을 사용할 것으로 판단됩니다. 너무 많은 상황을 고려하게 되면 상태 패턴을 적용하기 이전과 다를 것 없는 복잡한 조건문이 필요한 enum을 만들게 되어 좀 더 각각의 상태에 집중할 수 있도록 유지하려 합니다!

2022-03-20 12:52 UTC, ksy90101 commented on src/main/java/blackjack/domain/participant/Player.java
> +        return BettingResult.of(this, dealer).getResult(bettingMoney);
제가 잘못봤네요.
현재 상태에서는 디미터의 법칙을 위반했다고 볼수 없네요.
그러나 가독성을 위해서라도 위와 같은 방식이 더 좋다고 생각이 듭니다.

2022-03-20 13:01 UTC, hyeonic commented on src/main/java/blackjack/view/OutputView.java
> +    }
수정하여 반영하였습니다!

```java
private static String generateCardMessage(Card card) {
    return card.getDenomination() + card.getSuit();
}
```

2022-03-20 13:02 UTC, hyeonic commented on src/main/java/blackjack/view/OutputView.java
> +                .collect(joining(", "));
공통적으로 사용하는 상수 부분 처리하였습니다!

2022-03-20 13:04 UTC, hyeonic commented on src/main/java/blackjack/view/InputView.java
> +            return Integer.parseInt(SCANNER.nextLine());
말씀대로 View에서는 간단히 숫자인지에 대한 검증 여부만 진행하도록 변경하였습니다!

```java
public class InputView {
    ...
    private static Map<String, String> generateNames(String[] splitNames) {
        Map<String, String> names = new HashMap<>();
        for (String name : splitNames) {
            System.out.println(NEW_LINE + name + "의 배팅 금액은?");
            String money = SCANNER.nextLine();
            validateNumeric(money);
            names.put(name, money);
        }

        return names;
    }

    private static void validateNumeric(String input) {
        if (!input.chars().allMatch(Character::isDigit)) {
            throw new IllegalArgumentException("정수만 가능합니다.");
        }
    }
    ...
}
```

문자열로 전달된 배팅 금액의 validation은 모두 배팅 금액에서 진행됩니다!

2022-03-20 13:09 UTC, hyeonic commented on src/main/java/blackjack/dto/PlayerResult.java
> +    private final int profit;
기존 Int로 제한된 범위를 해결하기 위해 모든 연산을 문자열 기반으로 변경하여 작성하였습니다! 또한 초기 BettingMoney 세팅 시 1000이상이고 1000으로 나누어 떨어지는 상황을 연출하기 위해 추가적인 검증을 진행하였습니다. 이러한 생성은 정적 팩토리 메서드활용 하였습니다.

정적 팩토리 메서드를 사용한 이유는 외부에서 생성될 때만 해당 검증을 진행하기 위해서 입니다. 객체 내부에서 사용할 때 해당 검증을 적용할 필요가 없기 때문에 검증을 분리하는 식으로 구현하였습니다. 또한 자주 사용 되는 ZERO를 상수로 선언하여 이익 계산을 할 때 초기값으로 활용할 수 있도록 작성하였습니다!

```java
public class BettingMoney {

    private static final int MONEY_SCALE = 0;
    private static final int MONEY_LENGTH = 4;
    private static final String MONEY_DIVIDE_STANDARD = "000";

    public static final BettingMoney ZERO = new BettingMoney("0");

    private final BigDecimal amount;

    private BettingMoney(BigDecimal bigDecimal) {
        this.amount = bigDecimal.setScale(MONEY_SCALE, RoundingMode.FLOOR);
    }

    private BettingMoney(String amount) {
        this(new BigDecimal(amount));
    }

    public static BettingMoney of(String amount) {
        validateLength(amount);
        validateDivide(amount);
        return new BettingMoney(amount);
    }

    private static void validateLength(String amount) {
        if (amount.length() < MONEY_LENGTH) {
            throw new IllegalArgumentException("배팅 금액은 1000원 이상입니다.");
        }
    }

    private static void validateDivide(String amount) {
        if (!amount.endsWith(MONEY_DIVIDE_STANDARD)) {
            throw new IllegalArgumentException("배팅 금액은 1000으로 나누어 떨어져야 합니다.");
        }
    }

    public BettingMoney times(double percent) {
        BigDecimal multiplied = BigDecimal.valueOf(percent);
        BigDecimal result = amount.multiply(multiplied);
        return new BettingMoney(result);
    }

    public BettingMoney add(BettingMoney otherBettingMoney) {
        BigDecimal add = amount.add(otherBettingMoney.amount);
        return new BettingMoney(add);
    }

    public String getAmount() {
        return amount.toString();
    }
    ...
}

```

2022-03-20 13:12 UTC, hyeonic commented
안녕하세요 럿고! 매트입니다! 

앞서 주신 피드백과 제 생각을 정리하여 코멘트 아래에 남겨 두었습니다. 확인해주시면 감사하겠습니다!

이번 블랙잭 미션 동안 다양한 시선에서 생각할 수 있도록 던져주신 키워드 덕분에 많은 고민을 진행할 수 있었습니다. 이 밖에도 제가 놓친 부분이나 좋지 않은 습관 등 피드백 주시면 적극 반영 하겠습니다! 감사합니다!

2022-03-20 13:16 UTC, ksy90101 commented on src/main/java/blackjack/domain/state/Stay.java
> +        return LOW_RATE;
좋습니다~

2022-03-20 13:22 UTC, ksy90101 approved these changes
매트 안녕하세요 :) 리뷰어 럿고입니다.
블랙잭 미션 진행하시느라 너무 고생 많으셨습니다 💯 
피드백에 대한 의견을 너무 잘봤습니다.
함께 계속해서 이야기 하면서 재미있었습니다 :)

블랙잭 미션은 여기서 마무리할게요.

혹시 더 궁금한거나, 리팩토링을 한 부분이 있어서 좀 더 피드백을 받고 싶다면 언제든지 연락주세요!

2022-03-20 13:22 UTC, ksy90101 commented on src/main/java/blackjack/domain/participant/Players.java
> +                .map(name -> new Player(name, names.get(name)))
player의 인자는 name과 money같은데요.
names.get(name)이 money인가요?

2022-03-20 13:22 UTC, merged