[2단계 - 블랙잭(베팅)] 기론(김규철) 미션 제출합니다.
woowacourse/java-blackjack pull request #328
Opened 2022-03-17 09:03 UTC by Gyuchool

안녕하세요 또링!
오래 걸려서, 이제야 pr을 보내네요😢
블랙잭이 생각보다 너무 복잡하네요 ㅎㅎ.. 많은 조건들때문에 코드 길이 줄이려고 노력을 했습니다.
1단계에 해주셨던 리뷰를 반영했고 2단계도 잘 부탁드립니다!!

항상 감사합니다!

2022-03-18 08:55 UTC, jnsorn requested changes
안녕하세요. 기론! 2단계 잘 구현해주셨어요. 👍🏼
리뷰 반영해주신 부분과 새 요구사항에 의해 변경된 부분 모두 확인했습니다. 
우선 몇가지 코멘트 남겼는데, 확인해보시고 다시 요청주세요! 😃

2022-03-18 08:55 UTC, jnsorn commented on src/main/java/blackjack/domain/Card/Card.java
> +package blackjack.domain.Card;
아직 대문자가 보여요! 🧐

2022-03-18 08:55 UTC, jnsorn commented on src/main/java/blackjack/domain/User/Betting.java
> +public class Betting {
betting이라는 단어가 조금 어색하게 느껴지는데, 기론은 어떻게 생각하시나요?

2022-03-18 08:55 UTC, jnsorn commented on src/main/java/blackjack/controller/BlackjackController.java
> +public class BlackjackController {
메서드 순서를 읽기 좋게 정렬해주세요!

2022-03-18 08:55 UTC, jnsorn commented on src/main/java/blackjack/domain/User/Players.java
> +            players.add(new Player(playerNames.get(i), bettings.get(i), deck.drawInitCards()));
player의 이름과 배팅금액을 map으로 관리하면 어떨까요?

2022-03-18 08:55 UTC, jnsorn commented on src/main/java/blackjack/view/OutputView.java
> +        System.out.printf((CARD_FORMAT) + "%n", DEALER, users.get(0).getCards().get(0));
view의 입장에서는 첫 번째 원소가 딜러인지 어떻게 알 수 있을까요? START_PLAYERS_INDEX를 사용하지 않고 구현해보면 어떨까요? 
또 한 장의 카드만 출력하면 된다고 했는데 굳이 모든 카드를 알 필요가 있을까요? 🤔

2022-03-18 08:55 UTC, jnsorn commented on src/main/java/blackjack/domain/User/Betting.java
> +    private final int amount;
1원을 배팅한 플레이어가 블랙잭으로 승리한다면 얼마를 받을 수 있을까요?

2022-03-18 08:55 UTC, jnsorn commented on src/main/java/blackjack/controller/BlackjackController.java
> +    private void finishGame(Dealer dealer, Players players, List<UserDto> userDtos) {
딜러의 수익도 구해야해요!

2022-03-18 08:55 UTC, jnsorn commented on src/main/java/blackjack/service/batchService.java
> +public class batchService {
어떤 책임이 있는 클래스일까요?

2022-03-18 08:55 UTC, jnsorn commented on src/main/java/blackjack/service/batchService.java
> +        Map<String, Double> info = new LinkedHashMap<>();
info보다 명확한 이름을 지어줄까요?

2022-03-18 08:55 UTC, jnsorn commented on src/main/java/blackjack/domain/User/Dealer.java
> +        return cards.getScore() <= DEALER_ADD_CARD_LIMIT;
getter를 사용하지 않고 구현해볼까요?

2022-03-18 08:55 UTC, jnsorn commented on src/main/java/blackjack/domain/Card/Card.java
> +    }
👍🏼

2022-03-18 08:55 UTC, jnsorn commented on src/main/java/blackjack/domain/User/Betting.java
> +public class Betting {
VO 객체 👍🏼 VO 객체는 어떤 특징이 있을까요~?

2022-03-18 08:55 UTC, jnsorn commented on src/main/java/blackjack/domain/Card/Cards.java
>      }
deck이 맞을까요? 👀

2022-03-18 08:55 UTC, jnsorn commented on src/main/java/blackjack/domain/Card/Cards.java
>      }
Cards의 역할이 맞을까요? 기론이 생각하는 Cards의 역할은 무엇인지 궁금해요!

2022-03-18 12:10 UTC, Gyuchool commented on src/main/java/blackjack/domain/User/Betting.java
> +public class Betting {
배팅 금액이어서 `Betting`으로 했었는데 금액을 명확히 표시하도록 `BettingMoney` 또는 `Money`와 같이 하는게 좋을까요?

VO객체 특징은 불변이라고 생각합니다! 한 번 생성되면 상태가 변하지 않도록이요!

2022-03-19 06:00 UTC, Gyuchool commented on src/main/java/blackjack/domain/User/Betting.java
> +    private final int amount;
1원 배팅에 블랙잭 승리면 1.5배를 한 1.5원을 받게 되지 않나요?

2022-03-19 06:12 UTC, Gyuchool commented on src/main/java/blackjack/service/batchService.java
> +public class batchService {
플레이어와 그 결과들 리스트들을 일괄적으로 한번에 받아서 `결과에 따른 배팅 금액 계산`만 해주는 역할로 만들었습니다. 
상태를 가지고 있지 않아서 도메인으로 만들기보단 그냥 계산 처리만 해주는 서비스 역할이라고 생각해서 batchService라는 이름의 클래스로 만들었습니다!

2022-03-19 09:01 UTC, Gyuchool commented on src/main/java/blackjack/domain/Card/Cards.java
>      }
Cards는 유저들이 가지고 있는 카드들을 관리하는 역할로 만들었었습니다.  카드들의 합이 버스트인지 아닌지와 같이요.
`isSameScoreWithNotBlackJack()`메서드도 원래 카드들 점수를 비교한다고 생각되어서 Cards 클래스 내에서 처리했었는데
 지금은 User끼리 카드들을 비교하여 승패를 결정하므로 우선 User에서 처리하도록 변경했습니다!

2022-03-19 18:44 UTC, jnsorn commented on src/main/java/blackjack/domain/User/Betting.java
> +public class Betting {
Betting, Bet이라는 단어는 배팅금액보다는 배팅 그 자체에 대한 이름 같아요. 배팅 룰이나, 참여자 등이 담길 수 있는 느낌이에요. 조금 더 명확하게 money, amount 등의 의미를 넣어보면 좋을 것 같아요. (혹시 betting, bet에 금액과 관련된 의미가 있다면 이대로 네이밍해도 좋구요!)

2022-03-19 18:58 UTC, jnsorn commented on src/main/java/blackjack/controller/BlackjackController.java
> +public class BlackjackController {
혹시 기론은 어떤 기준으로 메서드를 정렬하시나요? 🧐

2022-03-19 18:58 UTC, jnsorn commented on src/main/java/blackjack/controller/BlackjackController.java
> +    }
a와 b는 어떤 의미일까요?

2022-03-19 18:58 UTC, jnsorn commented on src/main/java/blackjack/domain/user/Dealer.java
> +    }
OneCard보다 명확한 이름이 필요하지 않을까요?

2022-03-19 18:58 UTC, jnsorn commented on src/main/java/blackjack/domain/User/Betting.java
> +    private final int amount;
앗 코멘트 위치를 잘못 달았네요 ㅎㅎ `REVENUE_FORMAT = "%s: %.0f\n";`에 대한 리뷰였습니다~

2022-03-20 08:28 UTC, jnsorn requested changes
기론! 리뷰 반영한 부분 확인했습니다. 😃
이번에는 batchService에 대해 고민해보면 좋을 것 같아요. 관련 코멘트 남겨두었으니 확인해주세요.
궁금한 점은 언제든 DM 주시구요!

2022-03-20 08:28 UTC, jnsorn commented on src/main/java/blackjack/service/batchService.java
> +public class batchService {
네 개인적으로 이 클래스를 조금 수정해보면 좋을 것 같아요. 우선 이름을 통해 이 클래스가 어떤 역할을 하는지 파악하기 어렵다는 문제가 있고, calculate 메서드에서 getter가 상당히 많이 사용되고 있어요. getter가 많이 사용되었다는 건 어떤 의미일지 고민해보시면서 getter를 최대한 제거하여 수익률을 구하도록 수정해봅시다! 그 과정에서 클래스가 제거 되어도 좋아요.

2022-03-20 14:11 UTC, Gyuchool commented on src/main/java/blackjack/controller/BlackjackController.java
> +public class BlackjackController {
아 저는 run()매서드 내에서 순서만 생각했었네요..😂😂
전체적인 컨트롤러를 보니 순서가 뒤죽박죽이었네요!

바로 수정했습니다!!

2022-03-20 17:07 UTC, Gyuchool commented on src/main/java/blackjack/service/batchService.java
> +public class batchService {
players에서 결과를 만든 후, 다시 batchService에서 결과를 계산하는게 불필요하다고 생각이 되었습니다.
애초에 players에서 dealer와 비교하면서 계산을 하고 결론을 지을수 있었네요!
그래서 players로 매서드를 옮겼습니다. 그런데 옮긴 후, 테스트 코드를 작성하는데 `Players.create()`가 deck을 인자로 받아 players 내부에서 카드를 나눠주기때문에 테스트하기 어려운 구조였습니다.

그래서 배팅 금액을 나눠줄때 처럼, player 이름에 맞게 카드를 미리 배분 후, players 내부에서 생성하는 구조로 바꿨습니다. 이때 `Map<String, Cards>`와 `Map<String, Money>`로 key가 같은데 두 가지로 나뉘어져서 `Map<String, Map<Cards, Money>>`와 같은 구조로 바꾸려고 헀는데 막상 바꾸고 Map에 값을 넣는 로직을 작성해보니 한 매서드에서 두가지 일을 *(카드도 배분하고, 배팅 금액도 받는 구조)* 한다고 생각되어서 카드와 배팅 금액을 각각 받는 형식으로 바꿨습니다.

이에 대해서 또링은 어떤 방식이 더 괜찮다고 생각하시나요? 
혹은 `players.getStatistics()` 은 사실상  Player 클래스에서  `calculateProfit()`매서드를 반복하는 뿐이니 기존에 `Players.create()`에서 deck을 인자로 받는 방식을 그대로 두고 따로 `players.getStatistics()` 테스트는 만들지 않고 Player 클래스의  `calculateProfit()`매서드만 테스트 하는 것은 어떻게 생각하시나요?

2022-03-21 15:14 UTC, jnsorn requested changes
안녕하세요, 기론! 피드백 반영해주신 부분들 확인했습니다.😃 
질문주신 부분에 대해 코멘트 남겨두었어요. 이 부분에 대해 고민해보시고 다시 요청주세요! 
애매하거나 궁금한 내용은 언제든 DM 주시구요!

2022-03-21 15:14 UTC, jnsorn commented on src/main/java/blackjack/domain/user/Players.java
> +    public UserProfitDto getStatistics(Dealer dealer) {
https://github.com/woowacourse/java-blackjack/pull/328#discussion_r830645496

많은 고민을 해보셨네요! 질문에 대해 답을 드리기에 앞서, 기론에게 궁금한 것이 있어요. 🤔

1. 기론이 생각하는 Players, PlayerResult 객체의 역할은 무엇인가요?
2. DTO의 역할은 무엇인가요?

2022-03-22 01:39 UTC, Gyuchool commented on src/main/java/blackjack/domain/user/Players.java
> +    public UserProfitDto getStatistics(Dealer dealer) {
1. Players는 List<player>들을 관리해주고 List<Player>처리에 대한 로직들을 Players 내부에서 일급컬션으로 처리하는 역할이라고 생각합니다. 
그리고 PlayerResult는 dealer와 player를 받아서 결과를 산출해주는 역할을 합니다.
처음에 Players 내부에서 dealer와 비교하여 결과를 처리하는 로직이 있어서 players에 있는게 맞나 싶었는데 컨트롤러에서 처리하기엔 중요한 비즈니스 로직이라고 생각되어 players내부로 넣었습니다!

2. DTO는 도메인 로직에서 반환한 결과들을 담아서 전달만 하는 역할로 해야 하는데 도메인안에 들어있으면 순수한 비즈니스 로직이 아니여서 파악하기 어려울것 같네요.

그렇다면 dto로 변환은 어디서 하는게 좋을까요? dto내부에도 도메인이 들어가면 도메인이 수정될때 Dto도 영향받아서 안좋다고 알고있는데 그러면 controller에서 `new Dto()`에 인자값으로 도메인 객체의 get()함수를 통해서 상태를 넣어주면 될까요?

2022-03-22 09:16 UTC, jnsorn commented on src/main/java/blackjack/domain/user/Players.java
> +    public UserProfitDto getStatistics(Dealer dealer) {
1.  Players는 말씀하신대로 Player에 대한 로직을 관리하는 일급컬렉션입니다. 하지만 지금은 플레이어들의 수익률 계산 뿐만 아니라 딜러에 대한 수익률도 같이 계산하고 있는데, 과연 Players의 책임이 맞을까요? 아니라면 어디로 이동되어야 할까요? controller밖에 없을까요? 수익률에 대한 객체를 만들어도 좋고, 현재 결과에 따른 수익률을 가지고 있는 PlayerResult에서 처리해도 좋을 것 같아요.

2. https://tecoble.techcourse.co.kr/post/2021-04-25-dto-layer-scope/ 이 글이 도움될 것 같네요! 현재 구조에서는 말씀하신대로 Controller가 가장 적합해보입니다. (view와 domain을 연결해주는 역할을 하니까요)

2022-03-22 09:17 UTC, merged