[2단계 - 블랙잭(베팅)] 유콩(김유빈) 미션 제출합니다.
woowacourse/java-blackjack pull request #330
Opened 2022-03-17 09:06 UTC by kyukong

안녕하세요 토니!
블랙잭 2단계 미션 제출합니다

크게 달라진 것은 없고 1단계때 받았던 피드백 적용 및 베팅 기능 추가했습니다.

이번에도 잘 부탁드립니다.🙇‍♀️

2022-03-20 06:26 UTC, toneyparky requested changes
안녕하세요 유콩! 

1단계 리뷰를 반영하심과 동시에 상태 패턴을 적용해보셨네요! 

코드 잘 확인했고 리뷰도 완료했어요. 처음 학습하신 패턴을 이렇게 적용해보신게 멋지네요.
리뷰를 확인해주시고 궁금한 부분은 댓글이나  DM 부탁드릴게요!

화이팅입니다 😉

2022-03-20 06:26 UTC, toneyparky commented on src/main/java/blackjack/controller/BlackjackGame.java
> +public class BlackjackGame {
상태인 블랙잭과 혼동을 방지하기 위해 클래스의 이름을 바꿔주셨네요! 
코드를 읽는 사람을 고려한 좋은 리팩터링이에요!

2022-03-20 06:26 UTC, toneyparky commented on src/main/java/blackjack/domain/card/Suit.java
> +    DIAMOND("♦"),
기호를 사용해주셨네요 😁

2022-03-20 06:26 UTC, toneyparky commented on src/main/java/blackjack/domain/game/Dealer.java
>  public class Dealer extends Gamer {
아래 두개의 상수에 대해 접근 제어자를 확인해볼까요?

2022-03-20 06:26 UTC, toneyparky commented on src/main/java/blackjack/domain/game/Gamer.java
> +        return state instanceof Bust;
instanceof를 사용하지 않고 행위를 수행할 수 있는 방법이 있을까요?
instanceof가 코드에 사용되면 어떤 단점이 존재하는지도 공부해보면 좋겠네요~!

2022-03-20 06:26 UTC, toneyparky commented on src/main/java/blackjack/domain/game/Player.java
> +    private double findRate(final Dealer dealer) {
유콩이 메서드를 배치하는 규칙이 혼용되는거 같아요. 

어떤 경우에는 public 뒤에 private이 배치되고 어떤 경우에는 public뒤에 해당 메서드에서 사용하는 private 메서드가 위치하구요.

유콩만의 컨벤션을 지키며 일관성 있는 코드를 만들어볼까요?

2022-03-20 06:26 UTC, toneyparky commented on src/main/java/blackjack/domain/game/Players.java
> +            if (player.isRunning()) {
indent(인덴트, 들여쓰기) depth를 2를 넘지 않도록 구현한다. 1까지만 허용한다.

요구사항을 지켜봅시다 😁

2022-03-20 06:26 UTC, toneyparky commented on src/main/java/blackjack/domain/state/Ready.java
> +        if (!string.matches("-?[0-9]+")) {
정규식을 사용하여 숫자인지 검증을 해주셨어요.

자바에서 정규식을 사용할 때에는 성능적인 부하가 많이 걸린다고해요. 이를 해결하기 위해 `Pattern`객체와 상수화에 대해 공부해보고 적용해볼까요?

2022-03-20 06:26 UTC, toneyparky commented on src/main/java/blackjack/domain/state/Started.java
> +    protected static final double DEFAULT_RATE = 1;
상속 구조에 따르면 `Running, Ready, Hit` 모두 `DEFAULT_RATE`에 대해 알게 되는군요!

2022-03-20 06:26 UTC, toneyparky commented on src/main/java/blackjack/domain/state/State.java
> +    double profit();
profit은 어떤 의미를 가지나요? 이득을 얻다라는 동사로 사용하신걸까요?
제가 영어가 부족하여 의미를 잘못 파악했을 수 있어서 알려주신다면 저도 배울 수 있을거 같아요 😬
<img width="301" alt="image" src="https://user-images.githubusercontent.com/37579660/159150575-02b71257-4af9-40a6-bce6-3d3009dd7a03.png">

2022-03-20 06:26 UTC, toneyparky commented on src/main/java/blackjack/domain/state/State.java
> +    PlayingCards partOfPlayingCards();
둘은 게터 형식의 함수군요! 

컨벤션을 맞춰서 이름을 수정해볼까요?

2022-03-20 06:26 UTC, toneyparky commented on src/main/java/blackjack/domain/state/Stay.java
> +    private double profitRate = DEFAULT_RATE;
`Finished`의 하위 세개의 구현체에 `profitRate`이 중복 선언 되어 있네요!

2022-03-20 06:26 UTC, toneyparky commented on src/main/java/blackjack/domain/state/Started.java
> +    protected Betting betting = new Betting(0);
`State` 객체가 배팅 금액까지 관리하고 있군요!
`Gamer`는 `State` 객체를 필드로 가지고 있구요!
결과적으로 `Gamer`를 구현하는 `Dealer`는 사용하지 않는 `betting`이라는 필드를 가지게 되네요!

상속의 맹점이 드러나는 구조로 보여져요 😂

2022-03-20 06:26 UTC, toneyparky commented on src/main/java/blackjack/view/InputConverter.java
>  import blackjack.domain.game.Players;
사용하지 않는 임포트문을 제거해볼까요?

2022-03-20 06:26 UTC, toneyparky commented on src/main/java/blackjack/view/OutputView.java
> +    private static final String CARD = "\uD83C\uDCCF";
요거 귀엽네요🤠
상수의 이름을 `CARD_EMOJI` 정도로 해주면 이해하기 더 쉽겠어요!

2022-03-20 06:26 UTC, toneyparky commented on src/test/java/blackjack/domain/state/BlackjackTest.java
> +class BlackjackTest {
상태와 관련된 테스트를 탄탄하게 작성해주셨어요 💯 
좋습니다!

2022-03-20 06:26 UTC, toneyparky commented on src/test/java/blackjack/domain/state/HitTest.java
> +    }
예외가 발생하는 두가지 테스트에 대해 메서드의 컨벤션이 다른것 같아요.
하나는 뒤에 `exception`이 붙는데 다른건 아니네용

요럴 경우에 다른 개발자가 예외가 발생하는 테스트 메서드를 구현할 경우 이름을 정할 때에 고민을 하겠죠?
일관된 네이밍 컨벤션을 지켜서 협업에 도움을 줘볼까요?!

2022-03-21 03:55 UTC, kyukong commented on src/main/java/blackjack/domain/game/Dealer.java
>  public class Dealer extends Gamer {
헉..!! DRAWING_MAXIMUM(딜러 hit 기준 숫자)를 private 으로 수정을 안했군요!! public 에서 private 으로 바꾸었습니다!😱 DEALER_NAME(딜러 이름)은 플레이어 생성 시 딜러 이름과 동일한 기능이 필요했고, 플레이어를 생성하는데 딜러를 입력받는 것이 어색하다 생각하여 딜러와 플레이어가 상속받는 Gamer 클래스로 옮겼습니다. 옮기면서 딜러와 플레이어가 모두 접근 가능해야 했기에 디폴트로 접근 제어자를 수정했습니다!

2022-03-21 04:54 UTC, kyukong commented on src/main/java/blackjack/domain/game/Player.java
> +    private double findRate(final Dealer dealer) {
헉...!!!!😲 이번 2단계에서는 이전에 지키려고 노력했던 것들을 신경을 못썼네요 죄송합니다ㅜㅜ 저는 메소드 위치를 다음과 같은 기준으로 정리합니다.

> public 메서드 -> private 메서드 -> getter 메서드 -> 오버라이딩한 메서드

다른 분들의 피드백을 보니 getter 와 오버라이딩한 메서드는 하단에 두라는 피드백이 있더라구요. 저는 이전에는 getter 나 오버라이딩에 관계 없이 public 다음 private 이며 호출되는 순서로 뒀었는데 위의 순서대로 바꾸어보니 클래스를 보기 한결 편해졌습니다. 메인 로직을 상위에 두고 상대적으로 덜 보게되는 메서드를 하단에 두니 클래스 파일에 처음 들어오면 한번에 파악하기 쉽더라구요. 놓쳤던 부분들 수정했습니다!

그리고 딜러의 초기 카드를 오픈할 때 한장만 전달하는 메서드를 getter 로 봐야하는지 헷갈리더라구요. 이전에는 단순하게 값을 전달하니까 getter 로 취급하여 클래스 하단에 위치해두었는데 생각이 바뀌었습니다. `블랙잭` 미션이기에 딜러의 카드를 `한 장` 오픈하는 것이니 이것 또한 비즈니스 로직을 포함한다고 생각합니다. 토니는 어떻게 생각하시나요?

2022-03-21 05:09 UTC, kyukong commented on src/main/java/blackjack/domain/game/Players.java
> +            if (player.isRunning()) {
매번 early return 을 하면 인덴트 규칙을 지키기 어렵더라구요.. 그러다보니 가독성이 괜찮다면 어느정도는 지키지 않아도 될지 않을까? 생각했던것 같습니다.🥲 이렇게 하나둘 규칙을 지키지 않는다면 규칙의 의미가 없겠지요.. 피드백 감사합니다. steam 을 이용하여 수정하였습니다!

2022-03-21 05:15 UTC, kyukong commented on src/main/java/blackjack/domain/state/Started.java
> +    protected static final double DEFAULT_RATE = 1;
헛! `DEFAULT_RATE` 를 `Stay`, `Bust`, `Blackjack` 에서만 접근하므로 이 셋 클래스의 상위 클래스인 `Finished` 로 위치를 이동했습니다! 꼼꼼하게 봐주셔서 감사합니다!!!🙇‍♀️

2022-03-21 05:32 UTC, kyukong commented on src/main/java/blackjack/domain/state/State.java
> +    double profit();
게이머의 `수익` 을 의미했습니다..!! 근데 한번에 코드를 보고 이해가지 않는다면 제가 이름을 헷갈리게 지은듯합니다. `Finished` 에서 특정 상태의 수익률을 가져오는 메서드로 `earningRate` 이라고 정해두어 기존 `profit` 을 `earning` 으로 수정하였습니다!

2022-03-21 05:42 UTC, kyukong commented on src/main/java/blackjack/domain/state/State.java
> +    PlayingCards partOfPlayingCards();
알아볼 수만 있다면 getter 를 굳이 `get + 변수명` 의 형식으로 하지 않아도 된다고 생각했습니다. 근데 그건 클래스명과 getter 하려는 변수 이름의 종속 관계가 확실하여 어떤 개발자던 의문 없이 받아들일 수 있어야 하는 상황에서야 맞겠네요... 토니가 짚어주신 카드에 관한 getter 는 클래스가 `State` 이기 때문에 `state.playingCards` 로 사용해서 알아보기 힘들겠군요. 통일성을 위해 모든 getter 를 `get + 변수명` 형식으로 수정하였습니다!

2022-03-21 05:49 UTC, kyukong commented on src/main/java/blackjack/domain/state/Stay.java
> +    private double profitRate = DEFAULT_RATE;
헉! 알려주셔서 감사해요!! `Finished` 에서 선언하여 중복 선언 제거하였습니다!

2022-03-21 05:50 UTC, kyukong commented on src/main/java/blackjack/view/InputConverter.java
>  import blackjack.domain.game.Players;
제거했습니다..!!😱

2022-03-21 05:51 UTC, kyukong commented on src/main/java/blackjack/view/OutputView.java
> +    private static final String CARD = "\uD83C\uDCCF";
`CARD_EMOJI` 로 이름을 바꾼다면 의미가 더 명확해지겠군요! 수정했습니다!

2022-03-21 05:58 UTC, kyukong commented on src/test/java/blackjack/domain/state/HitTest.java
> +    }
다시 확인해보니 붙인것보다 안붙인 것이 더 많군요!!!😱😭😭😭 꼼꼼하게 확인하지 않고 코드리뷰 요청드려서 너무 죄송합니다ㅠㅠ 예외가 발생하는 테스트코드 모두 `exception` 을 붙여주었습니다!!

2022-03-21 06:58 UTC, kyukong commented on src/main/java/blackjack/domain/state/Ready.java
> +        if (!string.matches("-?[0-9]+")) {
String 의 `matches` 는 내부적으로 매번 `Pattern` 객체를 생성하고 삭제하는군요...!! 아직 두 곳밖에 사용하지 않지만 여러 클래스에서 접근이 가능해야 하기 때문에 util 패키지를 만들어 `Regex` 에 미리 컴파일 해두었습니다!

2022-03-21 08:08 UTC, kyukong commented on src/main/java/blackjack/domain/state/Started.java
> +    protected Betting betting = new Betting(0);
베팅은 플레이어만 하므로 Player 가 Betting 의 정보를 가지고 State 내에서 betting 관련 로직을 Betting 이 하도록 옮겼습니다..!!!😭😭😭 상속은 신경써야 하는 범위가 늘어나서 어렵군요.. 알려주셔서 감사해요😭

2022-03-21 08:22 UTC, kyukong commented on src/main/java/blackjack/domain/game/Gamer.java
> +        return state instanceof Bust;
`isRunning` 과 `isFinished` 처럼 State 내부에서 확인할까 하다가 단 하나의 상태(객체)에 종속되어 있는 것마저 State 가 가져도 될까? 싶어서 instanceof 를 썼었습니다. 하지만 안티패턴이라고 하는 instanceof 를 사용하는 것보다 State 를 이용하는 것이 객체지향에 더 맞을 듯 싶네요. 수정하였습니다!

2022-03-21 08:35 UTC, kyukong commented
토니! 마지막 코드리뷰 요청 드립니다!😂 

이번 블랙잭 미션 2단계에는 아쉬운 점이 너무 많네요. 피드백을 보아하니 제가 사소한 것들을 제대로 지키지 못했던 것 같습니다.(네이밍 컨벤션, 메서드 위치, 접근 제어자 등등) 2단계에서 저만의 목표는 피드백을 적게 받는 코드를 짜보자! 였었는데 마음과는 달리 꼼꼼하게 살펴보지 못했습니다. 괜히 너무 사소한것들까지 피드백을 하게 만든것 같아서 죄송하네요...🥲

그래도 정규식, 상속 구조 설계들의 주의할 점들을 알게 되었고 새로운 패턴도 사용해보았기 때문에 아쉽긴해도 얻어가는 것도 있었던 미션이었습니다. 감사했습니다!!

2022-03-21 09:10 UTC, kyukong commented on src/main/java/blackjack/domain/state/Ready.java
> +        if (!string.matches("-?[0-9]+")) {
토니 제가 `상수화`에 대한 답변을 빠트린것 같네요. 상수화라면 `"-?[0-9]+"` 이 부분을 말씀하시는 것 맞나요? 정규식 문자열은 메소드명으로 그 의미를 명확하게 나타낸다고 생각하기 때문에 상수화를 하지 않았습니다! `Regex` 객체로 이동한 후에도 상수명으로 의미를 나타낸다고 생각합니다!

2022-03-21 11:20 UTC, toneyparky commented on src/main/java/blackjack/domain/game/Dealer.java
>  public class Dealer extends Gamer {
좋아요 확인했습니다! 
자바의 접근 제어자는 최대한 보수적으로 설정하셔야 의도치 않은 의존성의 범람을 막을 수 있답니다!

2022-03-21 11:20 UTC, toneyparky commented on src/main/java/blackjack/domain/game/Gamer.java
> +        return state instanceof Bust;
네, 저도 상태패턴을 적용하셨으니 상태에게 물어보는 방향으로 가는 게 좋겠다는 생각이 들어서 리뷰 달아봤는데 잘 수정해주셨네요 👍

2022-03-21 11:20 UTC, toneyparky commented on src/main/java/blackjack/domain/game/Player.java
> +    private double findRate(final Dealer dealer) {
메서드의 순서는 절대적인 규칙이 있는게아니라 유콩과 협업하시는 팀원의 논의하에 결정하시면 되어요! 지금처럼 유콩이 편리하다고 생각하는 논리적인 근거가 있으면 충분합니다!
저는 오버라이딩도 직접 상속받은 객체의 오버라이딩과, `equals` 와 같은 오버라이딩을 구분하여 전자는 게터보다 앞에 적어줄거 같아요. 후자 보다 중요하니까요!

---

`openPartOfCards`에 대해서 이야기하신걸까요? 
저도 유콩의 말대로 도메인적인 의미를 부여해도 괜찮다고 생각합니다! 그래서 open이라는 이름도 좋아요!

2022-03-21 11:20 UTC, toneyparky commented on src/main/java/blackjack/domain/game/Players.java
> +            if (player.isRunning()) {
호호.. 맞아요 오히려 규칙을 지키면 코드가 더 읽기 힘들어지는 경우가 생기죠! 하지만 유콩도 알고 계시듯 지금은 학습을 하는 시간이기에 규칙을 잘 지켜보면 도움이 될거에요!

수정도 잘 하셨습니다😊

2022-03-21 11:20 UTC, toneyparky commented on src/main/java/blackjack/domain/state/Ready.java
> +        if (!string.matches("-?[0-9]+")) {
좋아요. 잘 적용하셨어요!

적었던 상수화는 static으로 선언하여 메모리 상에 미리 올려두어 인스턴스가 재생성 될 때에 다시 생성하지 않도록 처리함을 의미했어요.
이 부분도 처리해주셨기에 좋습니다~~

2022-03-21 11:20 UTC, toneyparky commented on src/main/java/blackjack/domain/state/Started.java
> +    protected static final double DEFAULT_RATE = 1;
좋아요~! 상속으로 계층을 구성할 때에는 이처럼 관계성을 잘 확인해야해요!

2022-03-21 11:20 UTC, toneyparky commented on src/main/java/blackjack/domain/state/State.java
> +    double profit();
이해했습니다~! 기존 단어도 좋고 바꿔주신 단어도 좋네요!
개발하다보면 영어가 늘게 되는.. 마법..😂

2022-03-21 11:20 UTC, toneyparky commented on src/main/java/blackjack/domain/state/State.java
> +    PlayingCards partOfPlayingCards();
네 사용하는 부분에서 약간 이해하기가 어려워서 코멘트 드렸어요 😀
자바스크립트와 같은 프로토타입 기반 언어에서는 유콩이 구현하셨던대로 게터라는 명칭보다는 가지고 있는 속성을 바로 사용하는걸로 알고 있어요. 하지만 자바에서는 게터를 사용하는게 컨벤션이기에 다른 개발자의 이해를 돕기 위한 적절한 수정이라 생각해요 !

2022-03-21 11:20 UTC, toneyparky commented on src/main/java/blackjack/domain/state/Started.java
> +    protected Betting betting = new Betting(0);
맞아요 상속은 코드의 재사용을 강제하기에 부모, 조부모(?)의 코드 내용을 계속 파악해야한다는 단점이 있어요. 제한된 인지적 자원으로 실수하기 쉬운 환경을 유발하죠!

## 여기서 질문 하나!!!
유콩이 이번에 이렇게 상태패턴을 적용하시면서 어떤 점을 느끼셨는지 궁금해요😬

2022-03-21 11:20 UTC, toneyparky commented on src/test/java/blackjack/domain/state/HitTest.java
> +    }
확인했어요 유콩! 아무래도 익숙하지 않은 새로운 시도를 하다보니 다른 부분에는 상대적으로 시선이 덜 갔다고 생각해요. 저도 새로운 기술을 적용하거나 구조로 코딩하면 그런 경향이 있어요 😂

지금은 학습하는 과정이고 리뷰를 받을 수 있는 환경이기에 마음껏 도전해보시고 성장해나가죠!

2022-03-21 11:21 UTC, toneyparky approved these changes
안녕하세요 유콩! 

코멘트에 답변 달아주셔서 저도 답변과 의견을 달아봤어요. 상태 패턴을 새로 접하고 바로 적용하시느라 힘드셨을텐데 잘 마무리가 되었네요. 이번에 리팩터링하시면서 보다 깔끔하고 이해하기 쉬운 코드가 되었다고 생각해요. 질문 하나 남겼으니 확인 부탁드려용

리뷰어는 유콩의 성장을 돕기 위해 있기에 미안해하지 않으셔도 됩니다 😬
컨벤션과 관련된 부분을 잘 지키며 다음 미션도 진행해보죠! 다음 미션은 이번보다 더 재미있을거에요!
고생 많으셨어요 👍

2022-03-21 11:21 UTC, merged

2022-03-21 12:04 UTC, kyukong commented on src/main/java/blackjack/domain/state/Started.java
> +    protected Betting betting = new Betting(0);
상태패턴을 적용하기 전에는 플레이어가 가지는 정보가 많아 인스턴스 변수 제한(3개 미만)을 지키지 어렵더라구요. 그래서 좀 억지로 객체를 분리하는 느낌도 있었습니다. `상태` 를 객체로 생성함으로써 플레이어(또는 딜러)가 가지는 정보(책임)를 상태에게 넘겨줄 수 있었고 무생물(?)을 객체로 만드는 경험도 할 수 있었습니다.ㅋㅋ 매번 실제 존재하지 않는 것도 객체로 만들 수 있다고 하지만 제대로 이해하진 않았거든요.

근데 책임을 분리하고 상황을 나누면서 객체 하나가 가지는 책임은 줄어들어 코드가 간략해졌지만 코드를 짜는 입장에서 모든 구조를 완벽하게 파악해야 했습니다. 객체의 상위 객체마저 모두 파악하여 어떤 코드를 어디에 두어야 가장 이상적인지를 판단하는 것이 어려웠습니다. 또 상태를 여러개로 분리하다보니 특정 메서드를 사용하는 객체가 매우 적어도 모든 메서드를 최상위 클래스가 가져야 한다는 것이 아쉬웠습니다. 

그래도 책에서 배우는 장단점이 아닌 실제로 사용해보면서 제가 직접 느낄 수 있어서 좋았습니다. 추상 클래스와 인터페이스를 완전히 이해한 것은 아니지만 어떻게 사용해야 하는지 맛보기정도는 한 것 같습니다!ㅎㅎ😁