[2단계 - 블랙잭(베팅)] 아스피(신동석) 미션 제출합니다.
woowacourse/java-blackjack pull request #335
Opened 2022-03-17 11:17 UTC by shindong96

안녕하세요 소니! 아스피입니다.
먼저 앞선 1단계의 피드백들에 너무 감사드립니다! DM으로도 피드백을 받을 수 있어서 너무 좋았어요 :)
2단계 미션도 잘 부탁드리겠습니다!

1단계 종료하면서 받은 피드백에 관해 여러 고민을 해보았어요. 제 메서드명이와 메서드가 제 의도와 다르게 보이는 부분이 많은 것 같아서 한 번 수정해보았습니다. 그리고 Players 클래스를 Name없이 활용하는 방법을 아직 떠올리지 못했어요ㅜㅜ조금만 더 고민해보겠습니다!

피드백 기다리겠습니다!

2022-03-18 16:48 UTC, sonypark requested changes
아스피 안녕하세요.
2단계 미션인 베팅 금액까지 구현하느라 고생하셨습니다 👍
몇가지 코멘트 남겼는데 확인 부탁드립니다 :)

추가로 테스트 코드 작성 관련 코멘트 남깁니다.
- 테스트가 깨지는 곳 확인해주세요
- 테스트 코드의 가독성을 신경써주세요. PlayersTest,ResultTest는 이해하기 쉽지 않네요..🥲
- 테스트 코드 내 변수는 가능한 필드 변수가 아닌 메서드 내 로컬 변수로 선언해주세요.
- 테스트 데이터는 가능한 테스트 메서드 마다 독립적으로 만들어주세요.
- TDD로 개발하고 계신 것 맞을까요?

2022-03-18 16:48 UTC, sonypark commented on src/main/java/domain/participant/info/Hand.java
> +	}
이 메서드는 왜 필요한가요?

2022-03-18 16:48 UTC, sonypark commented on src/main/java/domain/participant/info/Hand.java
> +
- 점수를 계산하는 로직을 더 단순화 할 수는 없을까요?
- ACE의 갯수를 계산할 필요가 있을까요? ACE가 2개이든 1개이든 결국 +11을 하는건 같지 않나요?
- ACE가 존재하는지 여부만 확인하고 11을 더했을때 21이 넘는지 안 넘는지만 체크해주면 되지 않을까요?

2022-03-18 16:48 UTC, sonypark commented on src/main/java/domain/participant/info/ParticipantInfo.java
> +}
이 클래스는 왜 필요할까요..?🤔

2022-03-18 16:48 UTC, sonypark commented on src/main/java/view/OutputView.java
> +				(int)(entry.getKey().getBetting().getBettingMoney() * entry.getValue().getEarningRate())));
get().get().get() 이렇게 호출하는 건 객체지향적인 코드 일까요?
디미터의 법칙에 대해 공부해봅시다 🧐

2022-03-18 16:48 UTC, sonypark commented on src/main/java/view/OutputView.java
> +			.map(card -> String.join("", List.of(card.getDenomination().getDenomination(), card.getSuit().getSuit())))
여기도 get().get() 보이네요.
- 어떻게 개선할 수 있을까요?
- participantInfo이 꼭 필요할까요?

2022-03-18 16:48 UTC, sonypark commented on src/main/java/controller/Controller.java
> +	}
`stream.forEach`를 선호하시는 이유가 있나요?
참고: [Collection.forEach와 Stream.forEach는 뭐가 다를까?](https://tecoble.techcourse.co.kr/post/2020-09-30-collection-stream-for-each/)

2022-03-18 16:48 UTC, sonypark commented on src/main/java/controller/Controller.java
> +		while (isKeepDraw && InputView.askDraw(name.getName())) {
`isKeepDraw`는 결국 `player.isNotBust()` 또는 `!player.isBust()` 아닐까요?

2022-03-18 16:48 UTC, sonypark commented on src/main/java/controller/Controller.java
> +		}
이 부분이 필요한가요?
플레이어가 버스트인지에 대한 여부는 askAndDrawForPlayer()에서 해줘야하지 않나요?

2022-03-18 16:48 UTC, sonypark commented on src/main/java/controller/Controller.java
> +	}
```suggestion
		for (ParticipantInfo participantInfo : playersInfo) {
			OutputView.printHandAndScore(participantInfo);
		}
	}
```
ParticipantInfo 없이 participant.getName(), participant.getCards(), participant.getScore() 로 전달해도 되지 않을까요?

2022-03-18 16:48 UTC, sonypark commented on src/main/java/domain/participant/Players.java
>  	public Players(List<Player> players) {
이전 리뷰에서도 말씀드렸지만 Name으로 Player를 묶으신 이유가 있나요?
이렇게 되면 Name에 강하게 종속되는데요. Name이 같은 Player가 있으면 어떻게 되나요?
이 블랙잭 게임은 이름이 같은 플레이어는 함께 게임을 할 수 없는건가요?

2022-03-18 16:54 UTC, shindong96 commented on src/main/java/domain/participant/info/Hand.java
> +
충격적이네요...!생각도 못했습니다...

2022-03-18 17:27 UTC, shindong96 commented on src/test/java/domain/participant/ParticipantTest.java
>  	}
아앗...죄송합니다 확인했어야하는데...수정하겠습니다!

2022-03-18 17:56 UTC, shindong96 commented on src/main/java/domain/participant/info/Hand.java
> +	}
카드를 드로우하다가 21이 되면 드로우할지 안할지 물어보지 않고 다음 참가자에게 물어보는 방식으로 구현했습니다. 굳이 없어도 되는 로직이지만 깔끔한 게임진행에 좋다고 판단했는데 아닐까요?

2022-03-19 07:36 UTC, shindong96 commented on src/main/java/controller/Controller.java
> +		Deck deck = Deck.from(new GenerationStandardDeckStrategy());
의미가 없다고 느껴져서 수정했습니다! 감사합니다!

2022-03-19 07:37 UTC, shindong96 commented on src/main/java/domain/participant/info/Hand.java
> +	private static final int BLACKJACK_SCORE = 21;
두 가지가 같은 숫자지만 의미가 다르다고 느껴져서 두 개다 작성했는데 삭제하는 것이 더 좋을까요?

2022-03-19 07:41 UTC, shindong96 commented on src/main/java/domain/participant/info/Hand.java
> +	}
플레이어 드로우시에 21이 되면 자동으로 드로우를 멈추기 위해 해두었습니다. 사실 플레이어가 n을 입력하면 되는 상황이라 불필요할 수도 있지만 있으면 진행이 매끄러울 거라고 생각했어요! 과한 설정일까요?

2022-03-19 07:41 UTC, shindong96 commented on src/main/java/domain/participant/info/ParticipantInfo.java
> +}
수정했습니다!

2022-03-19 07:41 UTC, shindong96 commented on src/main/java/view/OutputView.java
> +			.map(card -> String.join("", List.of(card.getDenomination().getDenomination(), card.getSuit().getSuit())))
수정했습니다!

2022-03-19 07:44 UTC, shindong96 commented on src/main/java/controller/Controller.java
> +		}
모든 플레이어가 버스트일경우 딜러는 드로우를 하지 않고 게임이 끝나는 방식을 구현했습니다. 수정하겠습니다!

2022-03-19 08:35 UTC, shindong96 commented on src/main/java/domain/participant/Players.java
>  	public Players(List<Player> players) {
중복이 가능하게 수정해보았습니다!

2022-03-19 08:35 UTC, shindong96 commented on src/main/java/controller/Controller.java
> +	}
수정하겠습니다!

2022-03-19 08:36 UTC, shindong96 commented on src/main/java/controller/Controller.java
> +		while (isKeepDraw && InputView.askDraw(name.getName())) {
수정하겠습니다!

2022-03-19 08:51 UTC, shindong96 commented
안녕하세요 소니!
피드백 감사합니다 :)
2단계 구현에 있어서 TDD를 생각치않고 구현한 것 같아요. 새로운 기능인데 리팩토링이라고 단순히 생각하고 접근했네요...반성하겠습니다! 

Players에 관해 고민을 해보았는데요 저는 List를 사용하고 idx로 구분하는 방식을 생각해보았습니다! 그런데 하면서 드는 의문이 Players객체를 사용했을때 가지는 장점이 Controller가 List<Player>를 가질 때보다 장점이 많은가에 대해 생각하게 되네요...List가 하는 역할만을 가지는 것 같아서요. 불변이라는 장점이 크지만 제외하고는 잘 모르겠습니다. 혹시 제가 놓치고 있는 부분이 있을까요?

또, Hand의 존재 이유에 대해서 생각해보게 됩니다. Hand객체는 add라는 함수를 가져서 불변의 장점조차 없게 느껴집니다. 그저 포장을 위한 설계였을까요?

제가 Players를 구현한 방식이 괜찮은지 의문이 드네요...
피드백 기다리겠습니다!

2022-03-20 03:38 UTC, sonypark commented on src/main/java/domain/participant/info/Hand.java
> +	private static final int BLACKJACK_SCORE = 21;
네 사실 BLACKJACK_SCORE 도 WINNING_SCORE가 더 적합할 것 같기도 하네요. 블랙잭이 되는 조건은 (카드 두장 && 숫자의 합 21)이니까요.

2022-03-20 03:50 UTC, shindong96 commented on src/main/java/domain/participant/info/Hand.java
> +	private static final int BLACKJACK_SCORE = 21;
수정했습니다! 감사합니다!

2022-03-20 05:02 UTC, sonypark requested changes
아스피 안녕하세요~
추가로 코멘트 남겼으니 확인 부탁드려요~

2022-03-20 05:02 UTC, sonypark commented on src/main/java/domain/result/EarningRate.java
> +	BLACK_JACK_WIN(1.5);
클래스 이름이 EarningRate가 맞을까요?
WIN, DRAW, LOSE는 EarningRate인가요?

2022-03-20 05:02 UTC, sonypark commented on src/main/java/domain/participant/Player.java
>  	}
더 적절한 메서드 네이밍은 없을까요?
- player.getResult()만 봤을 때 무엇을 의미하는지 모를것 같아요🥲
- 반환값은 EarningRate인데, player에게 결과값을 물어보면 수익률을 리턴하나?라고 생각하게 되겠네요.

2022-03-20 07:01 UTC, shindong96 commented on src/main/java/domain/participant/Players.java
> +	private final List<Player> players;
공부해보겠습니다!!!

2022-03-20 07:12 UTC, shindong96 commented on src/main/java/domain/participant/info/Hand.java
> +	}
anyMatch 공부하겠습니다!

2022-03-20 12:09 UTC, shindong96 commented
안녕하세요 소니 :)
가르쳐주신 Iterable 덕분에 개인적으론 코드가 좀 깔끔해진것 같아서 좋아요. 감사합니다!!

이번에 리팩토링을 하면서 Player가 과연 승패를 판단하는 책임을 가지는게 맞을까라는 생각을 하게 되었어요. 결론적으로 해당 책임은 Result가 가져야하는게 맞겠다는 생각이 들어 그렇게 수정해보았습니다!

그리고 손패를 보고 점수를 계산하거나 버스트, 블랙잭 등을 판단하는 책임은 참가자 객체로 옮겼습니다!

피드백 기다리겠습니다.
항상 감사합니다!

2022-03-21 11:49 UTC, sonypark requested changes
아스피 안녕하세요.
코드가 한결 깔끔해졌네요!
간단한 코멘트 남겼으니 확인 부탁드려요~

2022-03-21 11:49 UTC, sonypark commented on src/main/java/controller/Controller.java
> +		while (!player.isBlackJack() && !player.isBust()
!player.isBlackJack() && !player.isBust() -> player.canDraw() 메서드로 만들어도 좋을 것 같네요

2022-03-21 11:49 UTC, sonypark commented on src/main/java/domain/participant/Dealer.java
>  	}
`NO_BETTING`을 넣어주지 않고 기본값으로 0을 넣어주는 new Dealer() 생성자를 만들어줘도 되겠네요

2022-03-21 11:49 UTC, sonypark commented on src/main/java/domain/participant/Players.java
> +		this.players = players;
List<Player>가 아닌 List<Participant>로 구현하신 이유가 있을까요?

2022-03-21 11:49 UTC, sonypark commented on src/test/java/domain/result/ResultTest.java
> +		cards_17 = new ArrayList<>(Arrays.asList(ACE_CLOVER, SIX_CLOVER));
승패가 나올 수 있는 경우의 수와 그에 따른 수익률에 대한 모든 테스트가 작성되었나요?
- 블랙잭: 딜러만 블랙잭인 경우, 플레이어만 블랙잭인 경우, 둘 다 블랙잭인 경우
- 버스트: ...
- 점수에 따른 승패: .. 등

2022-03-21 11:49 UTC, sonypark commented on src/test/java/domain/participant/DealerTest.java
>  	}
경계값 테스트 👍

2022-03-21 14:58 UTC, shindong96 commented on src/main/java/controller/Controller.java
> +		while (!player.isBlackJack() && !player.isBust()
감사합니다!!수정하겠습니다!

2022-03-21 15:17 UTC, shindong96 commented on src/main/java/domain/participant/Players.java
> +		this.players = players;
Player가 따로 추가적인 메서드를 가지지 않아 삭제했었습니다! 지금은 canDraw 메서드가 생겨서 재생성하였습니다.
그런데 혹시 따로 메서드가 없더라도 Player를 가독성을 위해 구현해두는게 맞을까요?

2022-03-21 15:53 UTC, shindong96 commented on src/test/java/domain/result/ResultTest.java
> +		cards_17 = new ArrayList<>(Arrays.asList(ACE_CLOVER, SIX_CLOVER));
중요한 건데 안해버렸군요...수정하겠습니다!

2022-03-21 15:54 UTC, shindong96 commented
안녕하세요 소니!
피드백을 반영해서 리팩토링 해보았습니다!

피드백 기다리겠습니다!

2022-03-22 10:30 UTC, sonypark commented on src/main/java/domain/participant/Dealer.java
>  	}
네 의도한건 아래와 같은 생성자였습니다 :)
```java
	public Betting() {
		this(0);
	}

	public Betting(int money) {
		validatePositiveNumber(money);
		bettingMoney = money;
	}
```

2022-03-22 10:32 UTC, sonypark commented on src/main/java/domain/participant/Players.java
> +		this.players = players;
Player만의 로직이 없다면 Participant 자체가 Player 겠네요. 그렇게 되면 따로 만들지 않아도 괜찮습니다. 책임이나 역할의 분리 목적이 아닌 가독성 때문에 클래스를 새로 만드는 경우는 없을 것 같네요 :)

2022-03-22 10:34 UTC, merged