[2단계 - 블랙잭(베팅)] 리차드(전형중) 미션 제출합니다.
woowacourse/java-blackjack pull request #348
Opened 2022-03-17 21:47 UTC by HJ-Rich

핀 안녕하세요~ 
2단계 구현 완료하여 리뷰 요청드립니다 !

---

####2단계 요구사항과 더불어 핀이 1단계에서 남겨주셨던 부분 중 아래 항목을 적용하였습니다.

- PlayingCard 의 맥락 내에서는 변수명을 cards로 축약 (메서드 매개변수로 사용되는 경우 등)
- 주/부 생성자를 통한 유연하고 테스트하기 쉬운 코드 구현 (테스트 시 addCard대신 생성자로 전달)
- dto내 도메인 반환 제거
- BlackjackController -> BlackjackGame 변경 및 View 의존 제거
- 참가자 수 딜러 포함 8인 제한 적용
- 게임 결과 반환 타입 Map<Name, Revenue> 로 Vo로만 구성된 값을 Dto로 감싸서 반환 

---

1단계를 진행하며 정말 많이 배웠습니다 핀! 

### 컨트롤러 없이 블랙잭 게임 하기
컨트롤러 없이 블랙잭 게임하기 관련하여 인터페이스와 람다 중 람다를 사용해봤습니다.
인터페이스로 명세를 작성하고, 그 구현체를 전달하여 사용하는 것이 코드상으로는 간결해지겠지만,
비교적 익숙지 않은 함수형 인터페이스를 사용해볼 수 있다는 점과, 인터페이스보다 테스트에 용이하다는 점에서 선택해봤습니다.

이 부분을 고민하고 구현하며, BlackjackGame이 View와 직접적 결합이 끊어질 수 있다는 점에 대해 경험했습니다.
이러한 설계를 아예 경험해본 적이 없어서 핀의 피드백을 이해하는 데 시간이 많이 소요되었네요.
민망하고 감사합니다.

### dto와 도메인의 의존관계 관련
dto는 레이어간 데이터 전송에 사용되며, 특히 불필요한 정보가 누수되는 것을 막고, 값이 오염되는 것을 막습니다.
이를 위해 불변 객체를 사용하는 것이 권장되며, 로직은 최소화해야 하고, 도메인을 반환해서는 안됩니다.

기존 제 코드는 Dto에서 PlayingCard 값을 반환하고 있었는데,
해당 도메인 클래스가 Enum값 두 개만 필드로 가지고 있어서 상관없지 않나 하는 안일한 생각이 있었습니다.
현재는 Dto 생성 시점에 util클래스를 통해 PlayingCard를 String으로 변환하여 View에 전달하도록 구성하였고,
Dto는 모두 원시값 혹은 Vo만 반환하도록 구성하였습니다.

핀이 여러 차례 피드백해주셨는데 제가 잘 이해하지 못해서 많이 답답하셨으리라 생각됩니다 😢 
아마 지금도 부족한점이 많겠지만, 정말 많이 배웠습니다 핀, 감사합니다!

#### 미결사항
BlackjackGame 클래스가 3개의 인스턴스 변수를 사용중입니다.
요구사항은 2개까지만 허용이기에 이부분에 대해 추가적으로 개선하겠습니다.

2단계도 잘부탁드립니다 핀.

항상 건강하세요! 감사합니다! 😃

2022-03-18 15:02 UTC, lalize requested changes
안녕하세요 리차드!
몇 가지 리뷰 남겨두었으니 확인 후 반영해주세요~

2022-03-19 01:36 UTC, lalize commented on src/main/java/dto/BlackjackResultDto.java
> +package dto;
Dto에 대해서 학습하고 적용해보는 것은 좋지만, 저는 사실 이번 미션에서 Dto를 사용해야 하는지에 대한 의문이 있어요.
View가 도메인을 의존하면 생길 수 있는 문제를 이해하고 영향을 최소화하기 위한 수단으로 Dto를 사용한다 정도로 이해하고
레벨 1에서는 Dto 보다는 조금 더 도메인에 집중하면 좋을 것 같아요.

2022-03-19 05:56 UTC, HJ-Rich commented on src/main/java/domain/BlackJackResult.java
>      }
- 21번 라인 : 정적 팩터리 메서드에선 간결하게 어떤 매개변수를 받아 어떤 객체를 생성하는지만 나타내고 싶었습니다
- 32번 라인 : 다른 로직이 충분히 있는 메서드 내에서 stream연산을 해야할 때 메서드로 분리해 가독성을 높이려 했습니다!

혹시 핀이 물어보신 포인트가 제가 말씀드린 부분이 맞을까요?

2022-03-19 06:23 UTC, HJ-Rich commented on src/main/java/domain/MatchResult.java
>  public enum MatchResult {
1. 겜블러에게 수익액을 요청하기 위해 딜러를 전달한다.
2. 겜블러는 전달받은 딜러와 자신을 비교하여 자신의 승무패 결과를 확인한다.
3. 승무패 결과에게 자신의 배팅액과 블랙잭여부를 전달하여 수익액을 계산한다.
4. 반환된 수익액을 View에 전달하기 위해 수익액을 VO(Revenue)로 감싼다.

현재 위와 같은 로직인데요,
이렇게 구성한 이유는 다음과 같습니다.

1. 비즈니스 관심사가 1단계의 승무패출력에서 2단계 배팅 결과 출력으로 변경.
2. 겜블러.match(딜러) -> 승무패 로 1단계를 진행했듯, 겜블러.getRevenue(딜러) -> 수익액 으로 구성 시도.
3. 각각 match는 PlayingCards에게, getRevenue는 MatchResult에게 협력을 요청하기 때문에, 
과도한 책임 부여는 아니라고 판단.
4. 클래스명을 MatchResult에서 변경하지 않은 이유는, 기존 승무패 판정 로직인 match를 그대로 사용하고 있고,
match의 반환값이 승무패이며, 겜블러는 수익액 계산로직을 알 필요 없이 자신의 블랙잭 여부와 승무패 여부만 전달하여 수익액을 반환할 수 있어서 좋다고 생각했습니다. 
5. 이겼을때, 블랙잭이면, 1.5배다 이렇게 읽힐 수 있는 부분도 장점이라 생각했습니다.

Revenue객체는 현재 VO역할이기 때문에 어떤부분이 이상한지 잘 모르겠습니다..

수익 계산에 대한 테스트는 BlackjackResultTest 클래스에 있는데요,
혹시 추가적인 테스트가 필요할까요?

2022-03-19 06:31 UTC, HJ-Rich commented on src/main/java/view/InputView.java
> +        validateMaximumGamblers(names.size());
현재 구성상 식별할 수 있는 기준이 이름 밖에 없어서 
이름 중복 제한으로 식별하면 어떨까 생각해봤었는데요,
꼭 필요한 로직은 아닌 것 같아 제거하였습니다.

말씀하신 대로 참가자 수 제한은 도메인 규칙이라고 생각합니다.
Gamblers에서 List<Gambler>를 생성하는 시점에 7을 초과하는지 검증하도록 추가하였습니다.

2022-03-19 06:45 UTC, HJ-Rich commented on src/main/java/dto/BlackjackResultDto.java
> +package dto;
핀 혹시 어떤 부분에서 도메인에 대해 조금 더 집중하면 좋을지
조금더 구체적으로 말씀 부탁드려도 될까요?..

저는 아직 도메인의 구분 및 다른 레이어와의 책임 분리에 대해 익숙지 않아서
Dto 사용 관련해서 주신 피드백도 많이 배웠다고 느꼈었고...
또 제가 많이 부족해서 핀의 피드백을 잘 캐치하지 못하고 있다고 자주 느꼈거든요..

최대한 피드백을 다 반영하고.. 상속과 인터페이스 관련해서도 소홀하고 있다고 생각하진 않았는데 😢 
분발하겠습니다..

2022-03-19 18:02 UTC, HJ-Rich commented on src/main/java/controller/BlackjackGame.java
> +package controller;
BlackjackGame이 컨트롤러가 아니려면 dto를 의존하지 않아야 하는데
이부분은 제가 놓친 것 같습니다.

컨트롤러 없이 블랙잭 게임하기 라는 말씀을 저는
View와의 직접적 연결을 느슨하게 풀어서
만약 View가 콘솔에서 웹으로 변경되더라도
대응할 수 있게 변경해보라는 말씀으로 오해했었네요..

그래서 비록 BlackjackApplication에서 View의 메서드 참조를 전달하지만,
이는 코드의 재사용성을 활용한 것이고,
만약 View를 웹으로 변경하더라도 전달하는 함수형 인터페이스를 변경하면 되니
결합도를 낮추어 성공적이라고 생각했었습니다.. 🥲

도메인은 Dto를 몰라야하고, 현재의 BlackjackGame은
Dto를 알고 있으니까 도메인이라고 할 수 없고,
그렇기에 결국 컨트롤러인지 질문해주신 것으로 이해했고, 동의됩니다.

dto의 사용과 mvc패턴
컨트롤러의 정의가 무엇인지
이런 부분에 대해 애매모호하게 느껴지고 아직 많이 어려운 것 같습니다..

핀이 보시기에 아무래도 많은 부분이 정돈되지 않아있는데
이것저것 하려고 하는 것 같이 보이실 것 같다고 생각됩니다.

혹시 이번 미션에서 어떤부분이라도 집중적으로 학습하고
적용해봤으면 좋겠다 하는 부분을 링크나 키워드로 부탁드려도 될까요?

너무 떠먹여달라고 하는 것 같아 민망하기도 하지만
여쭤보고 공부해서 해결하고 넘어가고 싶은 마음입니다.. 🙏

2022-03-19 18:07 UTC, HJ-Rich commented on src/main/java/controller/BlackjackGame.java
> +    }
1. 인&아웃 두 개의 인터페이스를 전달 받아 처리하기
2. 전체를 개별적 함수형 인터페이스로 처리하기
3. 인터페이스와 함수형 인터페이스를 동시에 사용하기

위 옵션 중 3번은 오히려 로직이 불필요하게 분산되어
관리의 어려움을 초래할 것 같아 가장 먼저 배제하였고,

이번 미션에서는 연습삼아 함수형 인터페이스를 사용하여
개별적 메서드에 대해 테스트 용이성을 경험해볼까 하는 생각으로
모두 개별적 함수형 인터페이스를 사용했었는데요,

사실 조금 헷갈리는데
모든 부분을 바꿀 필요는 없다는 말씀은
3번 옵션처럼 함수형 인터페이스와 인터페이스를 조합해서 사용해보라는 말씀이실까요?

아니면 전체 인터페이스로 할지 아니면..
View를 직접 호출하라는 말씀이실지..

2022-03-19 18:09 UTC, HJ-Rich commented on src/main/java/controller/BlackjackGame.java
> +    }
핀의 피드백을 자꾸 이해하지 못하고 
다시 묻게 되어 죄송합니다 🙏

다소 수동적으로 비춰지고 답답하실지라도
한번 배우면 잘 숙지해서 같은 질문 하지 않도록 노력하겠습니다.
조금만 도와주시길 부탁드릴게요!

2022-03-19 18:11 UTC, HJ-Rich commented on src/main/java/domain/player/Gambler.java
> +    }
넵 말씀해주신 대로 수정하겠습니다.

사실 이부분 진행하며 말씀해주신 대로 할지
아니면 부모 생성자를 호출할지 고민이 됐었는데요,

자식 클래스 내 주/부 생성자를 만들 경우,
자식의 부 생성자는 부모 생성자를 호출하기 보다
같은 클래스 내 주 생성자를 호출하는 구조로 짜는 것이 권장된다

라고 이해해도 괜찮을까요?!

2022-03-19 18:12 UTC, HJ-Rich commented on src/main/java/domain/player/Player.java
> +    protected final Wallet wallet;
맞습니다.. 수정하겠습니다!

2022-03-19 18:14 UTC, HJ-Rich commented on src/main/java/dto/BlackjackResultDto.java
> +package dto;
핀이 Dto의 사용 범위에 대해 피드백 해주신 부분은
저에게 많은 도움이 된 것 같습니다만,
말씀해주신 대로 남은 기간동안 도메인에 더 집중하겠습니다.

혹시 제가 더 집중했으면 하는 부분이
BlackjackGame 클래스 관련 말씀이실까요?
아니면 Player Dealer Gambler 관련 말씀이실까요?!

거듭 죄송하지만 제가 핀의 피드백을 너무 이해하지 못하고
시간은 이제 얼마 남지 않아서..
핀이 보시기에 이거라도 좀 챙겨가라!! ㅋㅋ 싶은 걸
집중적으로 지적해주시면 저도 그부분에 대해 더 집중해서
성장하는 모습을 보여드리고 싶습니다.. 🥲

2022-03-19 18:16 UTC, HJ-Rich commented on src/main/java/domain/BlackJackResult.java
>      }
혹시 핀이 보시기에 어색한 부분이 있을까요?! 배우고 싶습니다 😅

2022-03-19 18:48 UTC, HJ-Rich commented on src/main/java/BlackJackApplication.java
> +        blackjackGame.printRevenue(OutputView::printResult);
View의 메서드를 참조 형식으로 전달하는 것이기 때문에
BlackjackGame가 View를 직접 의존하지 않게 되었다는 점에서
저는 의미가 있다고 생각했는데... 혹시 어떻게 더 개선해볼 수 있을까요?

기존 View의 메서드 참조를 직접 전달한 것은 코드 재사용성을 생각해서였어요.
BlackjackGame에서 필요한 Consumer, Supplier등을
하나의 인터페이스에 선언해두고 인터페이스를 의존하게 한다면,
기존 Input/OutputView가 인터페이스를 구현하게 하고
그 View를 구현체로서 전달하기 때문에 큰 차이가 있나 하는 생각을 했습니다.

핀의 다른 클래스에서의 피드백처럼
가독성 측면에서 인터페이스로 하나에서 관리하는 게
장점이 있다고 생각하지만 이번엔 연습삼아 + 개별적 함수형 인터페이스 사용을 통한 테스트 용이성을 경험해보고자 이렇게 구성해봤습니다.

제가 이해하는 바로는 현재 BlackjackGame이 
View에 대한 의존이 없기 떄문에
컨트롤러는 아니게 된 것 같고,
그래서 컨트롤러 내 비즈니스로직 과도한 집중은 해소된 게 아닌가 하는 생각을 해보는데요,

핀의 생각은 어떠실까요?!

2022-03-19 21:50 UTC, lalize commented on src/main/java/BlackJackApplication.java
> +        blackjackGame.printRevenue(OutputView::printResult);
View 구현체에 대한 의존은 없어졌지만 함수형 인터페이스가 View 메서드 시그니처 그대로 사용되고 로직 사이에 화면 출력을 위해 함수형 인터페이스를 의존하는 부분도 결국 View를 위한 부분이 아닌가? 생각이 들었어요. 블랙잭 게임이 거의 컨트롤러로 보이기도 하고요. 그냥 저의 개인적인 느낌정도로 이해해주시고 좋은 설계란 무엇인지 끊임없이 고민하고 찾아나가시면 좋을 것 같아요! 정답은 없어요!

2022-03-19 21:57 UTC, lalize commented on src/main/java/controller/BlackjackGame.java
> +    }
1, 2, 3번을 의도하고 드린 코멘트는 아니고요.
플레이어, 딜러, 카드덱을 받아서 초기화하지 않고 굳이 함수형 인터페이스로 처리하는 이유가 있을까 싶어서요. View 중심으로 결정된 설계가 아닌가 싶네요.

2022-03-19 22:21 UTC, lalize commented on src/main/java/controller/BlackjackGame.java
> +package controller;
컨트롤러라, Dto를 사용하는 것 굳이 말리지는 않지만 블랙잭 미션은 메인 함수를 컨트롤러 처럼 사용할 수도 있고, Dto를 꼭 써야할 필요도 없죠. 이런 부분 때문에 더 중요한 부분을 놓치고 있진 않은지 생각해보시면 좋을 것 같아요. 다른 어떤 부분을 더 배우기 보다는 코딩 컨벤션이나 객체지향 생활체조 등 레벨 1 미션에서 요구하는 부분들을 집중하면 좋을 것 같아요.

2022-03-19 22:33 UTC, lalize commented on src/main/java/domain/player/Gambler.java
> +    }
자식 클래스만의 규칙 및 필드 초기화와 같은 것들이 생기면 각 생성자들이 부모 생성자만 호출하면 완전하지 않은 상태의 객체가 생성될 수 있지 않을까요? 그래서 저는 자식 클래스의 주생성자를 호출해야 한다고 생각해요.

리차드가 권장된다라고 느끼신 이유는 무엇인가요?

2022-03-19 22:35 UTC, lalize commented on src/main/java/dto/BlackjackResultDto.java
> +package dto;
하나만 특정할 수는 없는 것 같아요. 설계는 언제든지 바뀔 수 있으니까요. 블랙잭 도메인 그 자체에 집중하시면 됩니다 :)

2022-03-19 22:58 UTC, lalize commented on src/main/java/domain/MatchResult.java
>  public enum MatchResult {
View에 전달하기 위한 VO라는 게 이해가 되지 않아요. 패키지는 도메인인데.. 객체라면 어떤 책임을 갖고 있어야 할 것 같은데 아무런 도메인 규칙도 없고 단순 getter만 있어서 Dto로 보이네요.

카드 점수를 구할 때는 카드 점수 계산기로 구하지 않았는데, 수익은 수익 계산기로 구해야하나요?
수익 객체가 수익을 구할 수 있는 게 더 객체지향적이라고 생각하는 데 리차드의 생각은 어때요?

아래는 블랙잭 코드와 관계 없고 생각해보시면 좋을 것 같은 코드입니다.
```java
Profit profit = new Profit(player); // 플레이어의 수익. (선언형으로 가독성이 좋음)
...
if (수익이 필요하면) {
  profit.doubleValue(); // 실제 계산되는 시점. (최적화)
}
```

2022-03-19 23:06 UTC, lalize commented on src/main/java/domain/MatchResult.java
>  public enum MatchResult {
View에 전달하기 위한 VO라는 게 이해가 되지 않아요. 객체라면 어떤 책임을 갖고 있어야 할 것 같은데 아무런 도메인 규칙도 없고 단순 getter만 있어서 Dto로 보이네요. 그리고 vo는 왜 도메인 패키지가 아닌가요? 도메인 객체 아닌가요?

카드 점수를 구할 때는 카드 점수 계산기로 구하지 않았는데, 수익은 수익 계산기로 구해야하나요?
수익 객체가 수익을 구할 수 있는 게 더 객체지향적이라고 생각하는 데 리차드의 생각은 어때요?

아래는 블랙잭 코드와 관계 없고 생각해보시면 좋을 것 같은 코드입니다.
```java
Profit profit = new Profit(player); // 플레이어의 수익. (선언형으로 가독성이 좋음)
...
if (수익이 필요하면) {
  profit.doubleValue(); // 실제 계산되는 시점. (최적화)
}
```

2022-03-19 23:11 UTC, lalize commented on src/main/java/domain/MatchResult.java
>  public enum MatchResult {
View에 전달하기 위한 VO라는 게 이해가 되지 않아요. 객체라면 어떤 책임을 갖고 있어야 할 것 같은데 아무런 도메인 규칙도 없고 dto처럼 사용되네요. 그리고 vo는 왜 도메인 패키지가 아닌가요?

카드 점수를 구할 때는 카드 점수 계산기로 구하지 않았는데, 수익은 수익 계산기로 구해야하나요?
수익 객체가 수익을 구할 수 있는 게 더 객체지향적이라고 생각하는 데 리차드의 생각은 어때요?

아래는 블랙잭 코드와 관계 없고 생각해보시면 좋을 것 같은 코드입니다.
```java
Profit profit = new Profit(player); // 플레이어의 수익. (선언형으로 가독성이 좋음)
...
if (수익이 필요하면) {
  profit.doubleValue(); // 실제 계산되는 시점. (최적화)
}
```

2022-03-19 23:47 UTC, lalize commented on src/main/java/domain/BlackJackResult.java
>      }
네 물어본 포인트는 그게 맞습니다.

추가 리뷰를 드리면 생성자(정적 팩토리 메서드)에서 로직을 수행하면 객체 생성 비용이 커지고 최적화가 어렵습니다. 그리고 객체가 책임 없이 필드를 반환하는 단순 getter만 제공하고 있는데 함수와 다를게 뭘까요?

```java
// 함수
public static int calc(a, b) {
  return a + b;
}

// 함수와 다를게 없다.
private final int value;

public Static Result of(a, b) {
  return new Result(a + b);
}

public int get() {
  return value;
}
```

이 부분은 앞서 드린 수익에 대한 피드백에 예시 코드를 참고하면 좋을 것 같아요.

2022-03-20 03:18 UTC, HJ-Rich commented on src/main/java/dto/BlackjackResultDto.java
> +package dto;
도메인은 무엇인가 도메인은 다른 요소들과 어떻게 구분되는가 도메인에서 지켜야하는 규칙은 무엇인가 도메인이라는 컨텍스트마다 어떤 다른 의미를 갖는가 등 제가 아직 저의 이해가 정립되지 않아 어려운 부분이 많네요 ㅠ.ㅠ 분발해보겠습니다 감사합니다

2022-03-20 03:54 UTC, HJ-Rich commented on src/main/java/controller/BlackjackGame.java
> +    }
컨트롤러 없이 블랙잭 게임하기를 제가 잘못 이해했었네요!
함수를 받는게 아니라 말씀하신대로 완성된 플레이어 딜러 카드덱을 전달받도록 하면 되는데...
그렇게 구성할 수 있다는 점을 아예 상상도 못했습니다.. ㄴㅇㄱ
결국엔 View중심으로 결정된 설계라는 지적이 이해가 되고 공감됩니다.

힌트 감사합니다 핀, 피드백 주신대로 진행해볼게요!

2022-03-20 04:28 UTC, HJ-Rich commented on src/main/java/controller/BlackjackGame.java
> +package controller;
미션마다 리뷰어가 집중하길 원하는 것에 집중해서 학습하는 방식으로 미션마다 성장하고자 했는데
그걸 달성하는 제 방식은 리뷰어의 모든 피드백을 반영하는 과정에서 저의 생각을 정립하는 거였어요.

여전히 아직은 제가 핀의 깊은 뜻을 쫓아가지 못한다는 느낌이 많이 들긴하지만.. ㅠ.ㅠ
말씀해주신대로 코딩 컨벤션이나 객체지향 생활체조를 다시 한 번 살펴보고 개선해보겠습니다.

핀의 리뷰 방향성을 알려주셔서 감사합니다!

2022-03-21 08:46 UTC, HJ-Rich commented
핀 안녕하세요~
Dto를 제거하고 최대한 BlackjackGame이 MVC에서의 C처럼 사용되지 않도록 해봤습니다.
컨트롤러 없이 게임하기, 컨트롤러 비대화 방지하기 관련하여 크루들과 이야기를 나누면서
제가 핀의 피드백을 이해하기 어려웠던 이유가 뭔지 대략 감을 잡은 것 같긴한데
결과 코드가 핀이 의도하신 도메인에 집중하기에 맞는지 궁금합니다.

아직 미숙한 부분이 많습니다만 마지막 PR제한시간이어서 드립니다!
오늘도 감사합니다 핀!

2022-03-22 00:29 UTC, lalize approved these changes
리차드 안녕하세요!
컨트롤러에 비즈니스 로직을 모이는 것을 방지하기 위해 많은 고민을 하셨네요 👍 
여러 방법으로 리팩토링 하셨지만 정답은 없다고 생각해요.
이번 미션은 여기서 마무리 하도록 할게요. 고생 많으셨습니다.
다음 미션도 화이팅하세요!

2022-03-22 00:29 UTC, lalize commented on src/main/java/domain/BlackjackGame.java
> +public class BlackjackGame {
리뷰 반영이 안된 부분이 있어 보이는데요. 리뷰 코멘트에 답변을 주시면 좋겠습니다!

2022-03-22 00:29 UTC, lalize commented on src/main/java/domain/BlackjackGame.java
> +public class BlackjackGame {
컨트롤러, dto 학습하여 적용한 것을 제거할 필요는 없었을 것 같아요.

2022-03-22 00:29 UTC, merged