[2단계 - 블랙잭(베팅)] 페퍼(최수연) 미션 제출합니다.
woowacourse/java-blackjack pull request #379
Opened 2022-03-20 11:57 UTC by SuyeonChoi

안녕하세요 에단!
1단계에서는 딜러의 첫번째 카드를 숨기기 위해 `Card`를 가변객체로 만들었습니다. 하지만 고민 끝에 뷰에 전달하지 않는 방식으로 충분히 구현 가능하다고 판단하고, `Card`의 변경을 최소화하기 위해 2단계에서는 불변으로 변경했습니다.

> 이 클래스가 블랙잭 게임의 전체적인 흐름을 관리할 거라 생각했는데, (카드를 추가하거나 딜러의 카드를 오픈하는 등)게임의 진행과 관련된 메서드가 외부에 많이 노출돼 있네요. 무엇이 메서드를 외부로 노출하게 만드는 걸까요?

뷰로부터 입력받으며 게임이 진행되기 때문에 게임의 진행은 컨트롤러가, `BlackJack`에서는 게임에 참가하는 딜러, 플레이어와 카드들의 상태를 관리하도록 구현하였습니다. `BlackJack`에서 현재 관리하는 객체들의 상태를 컨트롤러에서 관리한다면, 너무 무거워질거 같아 해당 방식을 사용하였습니다. 하지만 `BlackJack`이 너무 적은 책임을 가진거 같아 에단이 해당 코멘트를 주신거 같은데 차라리 컨트롤러에서 모두 관리하는게 더 좋은 방법일까요?

2단계 미션도 잘부탁드리겠습니다!

2022-03-21 11:51 UTC, Laterality requested changes
안녕하세요 페퍼, 

2단계도 빠르게 구현해주셨네요 👍 

간단한 코멘트를 남겨드렸으니 확인 부탁드릴게요 :)

1단계에서 남겨드린 코멘트를 잘 이해하셨네요! 게임 중간중간에 뷰와 입출력이 필요하다보니 게임의 전체 흐름을 `BlackJack`이 온전히 제어하지 못하고 있는데요. 이 상황에서 `BlackJack`이 어떤 책임을 가져야 하는지 한번 고민해보시면 좋겠어요. 만약 어떤 책임을 가져야 하는지 모르겠다면 말씀하신 것처럼 다른 클래스가 그 역할을 맡는 것도 방법일 수 있겠네요.

2022-03-21 11:51 UTC, Laterality commented on src/main/java/blackjack/domain/gamer/Gamer.java
> +    public boolean isInstantBlackJack() {
Instant blackjack은 일반 blackjack과 어떤 차이가 있을까요?

2022-03-21 11:51 UTC, Laterality commented on src/main/java/blackjack/domain/gamer/PlayerGroup.java
> +            Player copiedPlayer = new Player(player.getName(), player.getCards(), player.getBettingMoney());
`player.copy()` 처럼 복사하면 어떨까요?

2022-03-21 15:03 UTC, SuyeonChoi reviewed
에단 피드백 감사합니다 🙏🙏
피드백을 기반으로 리팩토링을 수행했습니다!
Blackjack과 BlackjackController의 각각의 책임에 대해서 고민해보았는데, 경계가 모호하여 동일한 책임을 지는거 같아 하나로 합쳤습니다.

확인 부탁드릴게요!

2022-03-22 00:06 UTC, Laterality approved these changes
안녕하세요 페퍼,

잘 수정해주셨어요 💯 

이번 미션은 더이상 피드백드릴 것이 없어 이만 머지하도록 할게요.

쉽지 않은 미션인데 고생 많으셨습니다. 다음 미션도 화이팅하세요!

2022-03-22 00:06 UTC, Laterality commented on src/main/java/blackjack/domain/result/GameResult.java
> +                .sum();
연산자는 크기가 작다보니 눈에 잘 안띄는 경우가 많은데요. 

특히 (`-value`나 `!isBust`처럼)연산자가 앞에 붙는 경우 코드를 읽는 사람이 못보고 지나칠 수도 있기 때문에, 가급적 눈에 잘 띄는 형태로 값을 표현하는 것이 좋습니다(e.g., `value * -1`, `isNotBust` 등).

2022-03-22 00:07 UTC, merged