[2단계 - 블랙잭(베팅)] 아키(허영운) 미션 제출합니다.
woowacourse/java-blackjack pull request #383
Opened 2022-03-21 08:50 UTC by yeongunheo

안녕하세요. 희봉!

새로 알게된 개념을 학습하면서 미션을 진행하느라 PR이 늦어졌네요😢

1단계 때 주신 피드백을 모두 반영하려고 노력했습니다. 그런데 디자인패턴으로 if문을 없애는 것 만큼은 정말 어렵더라구요.
일단 중복코드로 작성된 부분부터 제거했습니다. 디자인패턴은 익숙지 않아 좀 더 연습해봐야 할 것 같습니다.

1단계 이후 가장 고민했던 부분은 컨트롤러로부터 `BlackjackGame` 도메인을 분리하는 작업이었습니다.
최대한 깔끔하게 분리하려고 했지만 마음처럼 쉽지 않더라구요.
출력하는 부분이 생기면 Dto를 반환해 처리할 수 있도록 만들었습니다.

2단계 미션도 잘 부탁드립니다.
감사합니다.

2022-03-21 15:35 UTC, heebong requested changes
안녕하세요, 아키! 리뷰어 희봉입니다. 😄 
`BlackjackGame`객체와 프론트와의 의존을 거의 끊었네요 👍 프론트가 웹으로 변경되어도 컨트롤러부분이 많이 변경되지 않을 것 같네요 👍 
디자인패턴은 바로 적용하길 바라고 말씀드린건 아니었습니다 그러긴 쉽지 않죠 😅 다만 그런 해결 방법이 있다는걸 알아두시면 적절한 상황에 도움이 될걸로 생각됩니다.(아키 화이팅! 😄)
몇가지 코멘트를 추가로 남겼습니다. 확인 부탁드려요. 궁금한점이 생기면 언제든 DM 주세요!

2022-03-21 15:35 UTC, heebong commented on src/main/java/blackjack/domain/BlackjackGame.java
> +    public Players start(List<String> names) {
advance 🆙 `명령-쿼리 분리 원칙`에 대해 알아봅시다 😎 

hint 🖊️ 명령과 조회 쿼리는 분리하는게 좋다는 원칙입니다. 사이드이펙트가 적은 함수를 만들기 위한 원칙 중 하나에요. 책 [오브젝트]에 나온 부분을 발췌해볼게요
```
명령-쿼리 분리와 참조 투명성

지금까지 살펴본 것처럼 명령과 쿼리를 엄격하게 분류하면 객체의 부수효과를 제어하기가 수월하다. 쿼리는 객체의 상태를 변경하지 않기 때문에 몇 번이고 반복적으로 호출하더라도 상관이 없다. 명령이 개입하지 않는 한 쿼리의 값은 변경되지 않기 때문에 쿼리의 결과를 예측하기 쉬워진다. 또한 쿼리들의 순서를 자유롭게 변경할 수도 있다.
(06_메시지와 인터페이스 211p)
```

2022-03-21 15:35 UTC, heebong commented on src/main/java/blackjack/domain/BlackjackGame.java
> +    public Players start(List<String> names) {
물론 지금은 필드를 초기화하는 함수라서 생성자를 활용하는게 가장 좋습니다. `start()`를 무조건 호출하지 않고 `takeInitHand()`같은 함수를 호출하면 `NPE`가 발생하겠네요.

2022-03-21 15:35 UTC, heebong commented on src/main/java/blackjack/domain/BlackjackGame.java
> +    public ResponseInitHandDto takeInitHand(Deck deck) {
`ResponseInitHandDto`는 프론트에서 사용되는 `dto`객체네요. 프론트에서 사용하는 `dto`가 변경되면 도메인도 같이 변경되겠네요.
advance 🆙 명령-쿼리 분리 원칙에 따라 명령과 쿼리를 나눠볼 수 있겠네요. 😄

2022-03-21 15:35 UTC, heebong commented on src/main/java/blackjack/domain/BlackjackGame.java
> +    public ResponseProfitDto calculateProfit(Map<String, BetMoney> playerNameAndBets) {
advance 🆙 객체를 더 추가해서 역할을 나눌 수 있을 것 같아요.
`playerNameAndBets`가 `Map<User, BetMoney>`라도 괜찮을 것 같네요.
그리고 `BetRate` enum값을 계산하는 객체와 수익률을 생성하는 객체를 나눠도 좋겠네요.
`BetRate` 리턴하는 함수는 `User`가 추상함수로 가져서 `Player`와 `Dealer`가 구현할수도 있겠네요 😄 
관심사를 분리해서 변경에 강할 수 있도록 고민하는것도 좋아보입니다. 👍

2022-03-23 11:47 UTC, yeongunheo commented on src/main/java/blackjack/view/InputView.java
> +        return input.replace(" ", "");
불필요한 띄어쓰기를 모두 제거하기 위해 `replace`를 사용했습니다.
피드백 주신대로 이름을 입력받을 때에는 `trim`을 사용하는게 더 좋겠네요!
입력받은 이름들을 `split`을 한 뒤 순회하면서 `trim`을 할 수 있도록 변경했습니다.

2022-03-23 11:51 UTC, yeongunheo commented on src/main/java/blackjack/domain/BlackjackGame.java
> +        List<Player> players = names.stream()
'`dealer`인데 타입을 `User`로 하면 다른 사람이 보기에 헷갈리지 않을까?' 라는 생각으로 구현체로 모두 수정했었는데요,
지금은 괜찮을지라도 요구사항이 변경된다면 수정할 사항이 훨씬 많아지겠네요ㅠ
추상 타입으로 모두 수정했습니다!

2022-03-23 12:01 UTC, yeongunheo commented on src/main/java/blackjack/domain/BlackjackGame.java
> +    public Players start(List<String> names) {
명령과 쿼리 부분을 메소드로 따로 분리했습니다!

---
`명령-쿼리 분리 원칙`을 공부하면서 궁금한 점이 하나 생겼습니다.

제가 작성한 메소드를 보니 대부분 명령과 쿼리를 하나의 메소드에서 처리하도록 만들었더라구요,
왜 이런 구조가 나왔을까 생각해보니 `getter`를 최대한 쓰지않기위해 이렇게 짰던 것 같습니다.
명령할 때 변경한 데이터를 return하면 `getter`를 쓰지 않아도 되니까요!

명령과 쿼리 업무를 각각의 메소드로 분리하면 조회할 때 `getter`를 쓸 수 밖에 없던데,
그럼 어떻게 `게터/세터/프로퍼티를 쓰지 않는다.`라는 요구사항을 충족할 수 있을지 궁금합니다🤔

2022-03-23 12:04 UTC, yeongunheo commented on src/main/java/blackjack/domain/BlackjackGame.java
> +    public ResponseInitHandDto takeInitHand(Deck deck) {
`takeInitHand` 메소드는 데이터를 변경하는 업무(=명령)만 담당하도록 수정했습니다.
Dto의 경우 생성자를 통해 Dealer와 Players를 넣어주는 방식으로 만들도록 변경했습니다.

2022-03-23 13:23 UTC, heebong approved these changes
안녕하세요, 아키! 리뷰어 희봉입니다. 😄 
이번 미션도 고생하셨습니다. 피드백 반영도 잘 해주시고 코드도 더 깔끔해졌네요 👍 
블랙잭 미션은 여기서 머지하도록 하겠습니다. 상속, 추상 객체는 한 번에 이해하기 어려운 개념이에요. 체스 미션, 그 다음 미션들을 진행하면서 곰곰히 생각해보면 좋겠습니다 🙂 
궁금한 것이 있으면 언제든 DM 보내주세요. 블랙잭 미션 수고하셨습니다 👍

2022-03-23 13:23 UTC, heebong commented on src/main/java/blackjack/domain/BlackjackGame.java
> +    public void start(List<String> names) {
명령과 쿼리를 잘 분리해주셨네요 👍 추가로 생각한 것도 아주 좋은 의문입니다.
왜 우테코에서는 게터를 쓰지 말라고 했을까요? 🤔 
정답은 객체지향적인 코드에 있습니다. 객체지향의 장점 중 하나는? 은닉, 캡슐화, 내부 구현 숨김이죠. 구현을 숨김으로써 관심을 분리시켜 코드를 더 깔끔하게 유지할 수 있습니다. (높은 응집도를 유지할 수 있고요)
때문에 객체지향에서는 `메시지를 보내라`고 이야기합니다. 만약 어떤 객체 값에 10을 곱한 값을 알고 싶다면 아래처럼 구현하라는 의미에요
```
// bad case
int value = object.getValue();
int answer = value * 10;

// good case
int answer = object.multiply(10);
```
예시가 극단적이긴 하지만 😅 어떤 느낌인지 아시겠나요? 

그럼 다시 왜 `getter`를 사용하지 말라고 하는지를 생각해봅시다. 정답은 `getter`를 사용하면 객체에게 메시지를 보내는게 아니라 구현을 하게 되기 때문이에요. 위에 코드에도 보이는 것 처럼 프론트 노출 목적이 아닌 경우 `getter`를 사용한다면 대부분 해당 값을 사용해 직접 구현을 하게됩니다. 때문에 `메시지를 보내는 연습`을 하기 위해 `getter` 사용을 지양하는 규칙을 추가한거에요.

이제 어느정도 익숙해졌으니 `왜 이런 규칙이 있을까`를 생각하며 개발해보는것이 좋습니다 😄 이유를 생각하다보면 더 깊게 이해할 수 있고 좋은 아이디어가 생길 수 있어요. 쉽진 않겠지만! 고민해보시길 추천합니다 👍

2022-03-23 13:25 UTC, merged