[1단계 - 블랙잭 게임 실행] 주드 (홍성민) 미션 제출합니다.
woowacourse/java-blackjack pull request #396
Opened 2023-03-03 05:33 UTC by kevstevie

2023-03-03 07:02 UTC, kevstevie commented
안녕하세요 코다! 주드입니다
이번 블랙잭 미션 잘 부탁드립니다.

2023-03-05 03:18 UTC, yjksw requested changes
안녕하세요 주드 ~! 
이번에 리뷰를 맡은 코다 입니다 🙇‍♀️
 
이번 미션 구현을 아주 잘 해주셨어요.
메서드 책임이 잘 나뉘어져 있어서 코드 이해가 수월했습니다 👍

몇가지 코멘트 남겼으니 확인 부탁드려요 ~! 
질문은 댓글이나 DM 주세요.

2023-03-05 03:18 UTC, yjksw commented on src/main/java/controller/Controller.java
> +public class Controller {
정보가 없는 일반적인 이름보다 구체적인 네이밍을 사용하면 어떨까요 ? 
지금은 컨트롤러가 하나밖에 없지만, 애플리케이션이 커지면서 여러 컨트롤러가 생길수도 있습니다 😊

2023-03-05 03:18 UTC, yjksw commented on src/main/java/controller/Controller.java
> +        }
`player.isBustedGambler()`와 `player.getScore()`가 모두 Player에 있는 메서드인데 외부에서 주입해주고 있어요. 
내부 구현은 객체 안으로 숨기는 것이 어떨까요 ?

2023-03-05 03:18 UTC, yjksw commented on src/main/java/controller/Controller.java
> +    }
`Player`가 `isHit()`라면 카드를 하나 고르는 행위가 컨트롤러의 책임이라고 할 수 있을까요?

2023-03-05 03:18 UTC, yjksw commented on src/main/java/controller/Controller.java
> +        while (dealer.getScore() <= dealer.getPickBoundary()) {
딜러는 추가 한 장의 카드만 받을 수 있는 것으로 알아요 ~ 확인 부탁드려요 
[블랙잭 규칙](https://namu.wiki/w/%EB%B8%94%EB%9E%99%EC%9E%AD(%EC%B9%B4%EB%93%9C%EA%B2%8C%EC%9E%84) )

2023-03-05 03:18 UTC, yjksw commented on src/main/java/controller/Controller.java
> +        System.out.println(DEALER_HIT);
컨트롤러에서 출력을 하고 있네요 😉

2023-03-05 03:18 UTC, yjksw commented on src/main/java/controller/Controller.java
> +    }
이 로직도 컨트롤러에 있기엔 중요한 비즈니스 로직 같군요 ! 
컨트롤러 전체적으로 몰려있는 책임을 도메인으로 한번 넘겨 보는 것은 어떤가요 ?

2023-03-05 03:18 UTC, yjksw commented on src/main/java/domain/Card.java
> +package domain;
패키지 관련은 남길 곳이 없어서 여기다 남겨요 ~ 
domain도 관련 domain끼리 패키지를 나누어 관리해보면 어떨까요 ?

2023-03-05 03:18 UTC, yjksw commented on src/main/java/domain/Dealer.java
> +    }
딜러도 처음 받을 때 두 장 받는 것 아닌지 확인 부탁드려요 ~

2023-03-05 03:18 UTC, yjksw commented on src/main/java/domain/Dealer.java
> +    }
컨트롤러에서 `PICK_BOUNDARY`를 채크하는게 중복인 것 같네요  😉

2023-03-05 03:18 UTC, yjksw commented on src/main/java/domain/Deck.java
> +    }
요것도 사실상 2depth가 아닐까요 ?

2023-03-05 03:18 UTC, yjksw commented on src/main/java/view/OutputView.java
> +}
파일 마지막에 왜 개행이 항상 추가되어야 할까요 ? 
[참고링크](https://yeonyeon.tistory.com/241)

2023-03-05 03:18 UTC, yjksw commented on src/test/java/domain/CardsTest.java
> +class CardsTest {
블랙잭 요구사항이 매우 복잡한 것이 비해 테스트코드 개수가 적은 것 같아요 ! 
아마 그 이유는, 핵심 게임 요구사항이 대부분 컨트롤러에 몰려있기 때문이 아닌가 싶은데요, 
컨트롤러에 모여있는 게임 요구사항을 도메인으로 옮기고 그 요구사항에 대해서 테스트 해보면 어떨까요?

2023-03-05 09:11 UTC, kevstevie commented
안녕하세요 코다!
컨트롤러에 있는 로직을 대폭 제거하고 도메인 역할 확보에 최대한 신경써서 리팩터링 했습니다.
피드백에 대한 질문으로, 컨트롤러가 사실상 서비스의 역할도 병행하고 있다고 생각해서 입력을 받아서 카드를 뽑게 하는 것도 컨트롤러의 역할이라고 생각했는데 아닐까요?

2023-03-05 16:32 UTC, yjksw approved these changes
안녕하세요 주드 ~ 코다 입니다 🙇‍♀️

빠르게 피드백 잘 반영해주셨어요 ! 
복잡한 요구사항인데됴 메서드 단위가 매우 간결하고 코드가 깔끔해서 이해하기 정말 쉬웠어요 💯
또 리팩토링을 통해서 많은 책임을 도메인으로 옮겨주신 것 같아요. 

주드가 보내주신 링크를 보니 알던 블랙잭 룰과 또 다르군요 ! ㅠㅠ 
저는 우테코 요구사항과 리뷰어 가이드에 있는 요 [링크](https://namu.wiki/w/%EB%B8%94%EB%9E%99%EC%9E%AD(%EC%B9%B4%EB%93%9C%EA%B2%8C%EC%9E%84) ) 를 확인하긴 했는데, 무엇이 맞는지 잘 모르겠네요 ㅎㅎ 
맞다고 생각하시는대로 구현해주시면 참고하겠습니다 ~!

1단계 잘해주셔서 머지하려고 해요 ㅎㅎ 
그럼 2단계에서 만나요 ~

2023-03-05 16:32 UTC, yjksw commented on src/main/java/view/OutputView.java
> +    }
혹시 코드 어디선가 정렬을 위해 `players` 리스트나 `dealerStats` 리스트의 순서를 바꾸게 되면 결과가 달라질 것 같아요 ~

2023-03-05 16:32 UTC, yjksw commented on src/main/java/domain/card/Cards.java
> +    }
객체에 메시지를 보내보면 어떨까요 ?

2023-03-05 16:32 UTC, yjksw commented on src/main/java/domain/card/Cards.java
> +    }
여기도 한번 메시지를 보내봐요 ~

2023-03-05 16:32 UTC, yjksw commented on src/main/java/domain/score/Score.java
> +    }
점수가 같으면 어떻게 되나요 ? 🤔

2023-03-05 16:32 UTC, yjksw commented on src/main/java/controller/BlackjackController.java
> +public class BlackjackController {
정말 깔끔해졌네요 ~  💯💯

2023-03-05 16:32 UTC, yjksw commented on src/main/java/controller/BlackjackController.java
> +        printInitialCards(dealer, players);
_처음에는 각 딜러와 플레이어는 2장씩 뽑는다_ 라는 비즈니스 요구사항을 도메인으로 옮겨보면 좋을 것 같아요 ~

2023-03-05 16:32 UTC, yjksw commented on src/main/java/controller/BlackjackController.java
> +    }
이 부분과 관련된 로직이 주드가 질문을 남겨주신 부분이군요 ! 
다시보니 매번 입력을 받고 그 결과에 따라 카드를 뽑아야 해서 
주드가 말씀하신 것처럼 컨트롤러에 있는 것이 더 좋아보이네요 😊

2023-03-05 16:33 UTC, merged