[1단계 - 블랙잭 게임 실행] 케로(김지현) 미션 제출합니다.
woowacourse/java-blackjack pull request #398
Opened 2023-03-03 05:38 UTC by jyeost

안녕하세요 검프 ! 
5기 케로 입니다 ㅎㅎ 리뷰 잘부탁드립니다! 🐸 🐸 

제가 이번 미션에서 구현하고자 노력한 부분은 

- 도메인에 알맞은 책임을 분리하고 알맞은 테스트 코드 작성
- mvc 패턴에서 model과 view의 완벽한 분리 (데이터를 원하는 형태로 가공하여 사용하도록 함)
- 모든 엔티티를 작게 유지하고 3개 이상의 인스턴스 변수를 가지지 않도록 하기
- 딜러와 플레이어에서 발생하는 중복 코드를 제거하고 각자 다른 메서드도 구현해주기 위해 player 추상클래스를 상속하여 기능을 확장하도록 하기
- enum을 활용하여 사용가능한 값을 제한함

이 정도입니다...!!

이번에 CardValue에 카드의 값과 점수를 저장하면서 에이스의 값을 1로 둘지 11로 가져갈지 계산해주는 역할에 대한 고민을 많이 했는데요...! 그 역할은 사용자가 해주는 것이 맞을 것 같아서 각 player에서 해주도록 하였는데, 괜찮은지 검프의 생각이 궁금합니다!

2023-03-04 03:36 UTC, Livenow14 requested changes
안녕하세요 케로, 몇가지 간단한 피드백 남겼으니 확인부탁드려요.
진행하시가다 어려운 부분이 있으면, 언제든 DM 및 커멘트 남겨주세요 :) 

전반적으로 피드백 남긴다면, 

> 테스트 코드 추가.

Test가 실제 요구사항을 전부 이행할 수 없을 것 같아서, 구현의 변경보다, 우선 테스트를 더 작성해보시는걸 추천드립니다.

수고많으셨어요!

2023-03-04 03:36 UTC, Livenow14 commented on README.md
> +최종승패를 보여준다
기능 목록보단, 사용자 스토리에 조금더 어울리겠네요 :)

2023-03-04 03:36 UTC, Livenow14 commented on src/main/java/blackjackgame/Application.java
> +    }
인스턴스 생성과, 실행을 분리해보는게 어떨까요? 

지나친 코드 단축은 오히려 가독성을 떨어뜨려요.

2023-03-04 03:36 UTC, Livenow14 commented on src/main/java/blackjackgame/controller/blackJackController.java
> +    }
큰 범위에서 -> 게임 준비, 더 할것인지 물어보기 -> 게임결과 등이 잘 나눠져있네요.

2023-03-04 03:36 UTC, Livenow14 commented on src/main/java/blackjackgame/controller/blackJackController.java
> +    }
재귀함수의 사용을 지양해주세요.

side effect와 debug시 파악이 힘들 수 있습니다.

2023-03-04 03:36 UTC, Livenow14 commented on src/main/java/blackjackgame/controller/blackJackController.java
> +    }
setGame -> initializeGame

2023-03-04 03:36 UTC, Livenow14 commented on src/main/java/blackjackgame/controller/blackJackController.java
> +        askDealerHitCard(dealer, deck);
다만 ask라는게 어색하게 느껴지는데 밑에서 더 다룰게요.

2023-03-04 03:36 UTC, Livenow14 commented on src/main/java/blackjackgame/controller/blackJackController.java
> +        deck.initPlayersCards(guests, dealer);
```java
        deck.initPlayersCards(guests, dealer);
```

여기 메서드에 포함하지 않아도 될것 같은느낌이 드네요. 
파라미터로 보내고 -> initialize만 하고있어서요.

2023-03-04 03:36 UTC, Livenow14 commented on src/main/java/blackjackgame/controller/blackJackController.java
> +        final Deck deck = new Deck();
불변 객체가 아닌걸까요?

2023-03-04 03:36 UTC, Livenow14 commented on src/main/java/blackjackgame/controller/blackJackController.java
> +    private void askGuestsHitCard(final List<Guest> guests, final Deck deck) {
list를 가지고 와서, 추가 작업을 진행하고 있는데, 이경우 메서드화가 필요한 부분이었을까요? 
파라미터인 guests의 역할이, 단순 for문을 열어주고, 다른 메서드의 인자로 넘기고 있어서요.

2023-03-04 03:36 UTC, Livenow14 commented on src/main/java/blackjackgame/controller/blackJackController.java
> +    }
askGuestsHitCard를 이해하기위해서, 
askGuestsHitCard -> askGuestHitCardRepeat -> askGuestHitCard -> deck.distributeCard(guest)

를 다 확인해봐야 하는 것 같아요. 메서드 추상화를 조금 줄여보는건 어떨까요?

2023-03-04 03:36 UTC, Livenow14 commented on src/main/java/blackjackgame/controller/blackJackController.java
> +    }
이번 미션에서는 크게 추상화가 필요하지 않은 부분들도, depth1을 위해 추상화 된다면, 과감히 depth 2를 사용해주세요. 
(저는 dpeth2까지는 괜찮다 생각해서요.)

2023-03-04 03:36 UTC, Livenow14 commented on src/main/java/blackjackgame/domain/Result.java
> +    private static final int BLACKJACK_MAX_SCORE = 21;
좋은 상수화네요 :) 
다만, Result에 해당 변수가 있는게 옳을까요?!?! 
Result가 전체 게임을 총괄하는 느낌이여서요.

2023-03-04 03:36 UTC, Livenow14 commented on src/main/java/blackjackgame/domain/Result.java
> +    }
생성자에는 최대한 로직을 피해주세요.

생성자가 무거워진다면, 사용하기 꺼려지는 객체가 될 것 같습니다.

2023-03-04 03:36 UTC, Livenow14 commented on src/main/java/blackjackgame/domain/Result.java
> +    }
생성자를 이해하기 위해, 해당 코드를 다 이해해야 겠네요.

외부에서 만들어서 넣어줄 순 없을까요?

2023-03-04 03:36 UTC, Livenow14 commented on src/main/java/blackjackgame/domain/Result.java
> +    private GameOutcome judgeGuestResult(final int dealerScore, final int guestScore) {
Result라는 suffix는 전체 메서드에서 제거해도 괜찮을 것 같아요.

Result내에 포함된 메서드이기 때문에, 그 의미를 충분히 유추할 수 있습니다.

2023-03-04 03:36 UTC, Livenow14 commented on src/main/java/blackjackgame/domain/Result.java
> +    }
Map을 그대로 반환하지 않고, Dto등을 사용해보는 것은 어떨가요? 
해당 구현이 변경되면, outputView에도 영향이 갈 것 같아서요.

2023-03-04 03:36 UTC, Livenow14 commented on src/main/java/blackjackgame/domain/card/Card.java
> +    }
card는 get책임밖에 없는걸까요? 
단순한 자료구조 인 것 같은데, 이경우 그냥 상태를 반환하는게 어떨가요?


++ 메서드가 다른 곳의 비교로직으로 사용되네요?! 
비교메서드를 Card내에 둬도 괜찮을 것 같아요.

2023-03-04 03:36 UTC, Livenow14 commented on src/main/java/blackjackgame/domain/card/CardValue.java
> +    KING("K", 10);
깔끔하네요 :)

2023-03-04 03:36 UTC, Livenow14 commented on src/main/java/blackjackgame/domain/player/Guests.java
> +    private static final String ERROR_DUPLICATE_GUEST_NAMES_MSG = "참여자의 이름은 중복될 수 없습니다.";
한번씩만 쓰이는 상수화의 경우, 제거 후 메서드 내에 그대로 노출해주세요.

2023-03-04 03:36 UTC, Livenow14 commented on src/main/java/blackjackgame/domain/player/Guests.java
> +    }
여기도 생성자에 로직..!

2023-03-04 03:36 UTC, Livenow14 commented on src/main/java/blackjackgame/domain/player/Guests.java
> +    }
early return을 사용해보는건 어떨까요?

2023-03-04 03:36 UTC, Livenow14 commented on src/main/java/blackjackgame/domain/player/Player.java
> +    public abstract String getName();
해당 메서드가 외부에서만 쓰이고있어요.
이경우 추상화 클래스사용이 정말 필요한 순간일까요?

추상 메서드의 경우, 추상클래스의 메서드내에 노출되어야 그 의미가 더 명확히질 것 같아요.

2023-03-04 03:36 UTC, Livenow14 commented on src/test/java/blackjackgame/domain/ResultTest.java
> +        }
given when then 패턴을 사용해보시는 건 어떨까요?
"일관성"의 부분에서 모든 메서드가일관된 상태를 가지는게 좋을 것 같아서요.

2023-03-04 03:36 UTC, Livenow14 commented on src/test/java/blackjackgame/domain/DealerTest.java
> +        dealer.addCard(card1);
인스턴스 명을 조금더 명확하게 해주세요.
1, 2 의 suffix는 테스트의 의미를 크게 드러내지 못합니다.

2023-03-06 12:20 UTC, jyeost commented on src/main/java/blackjackgame/controller/blackJackController.java
> +    }
그동안 너무 코드의 간결성과 구현의 편리함으로 인해 생각없이 재귀함수를 계속해서 써온것 같습니다...! 앞으로도 사용을 자제하려 노력하겠습니다

2023-03-07 04:43 UTC, jyeost commented on src/main/java/blackjackgame/controller/blackJackController.java
> +    }
depth 때문에 메서드를 분리해 주면서 
1. 메서드 명을 짓는게 어려워짐
2. 가독성이 더 떨어짐
의 문제를 느끼고 있었는데 다행이네여...!! 반영해서 리팩 하겠습니다 !!

2023-03-07 08:22 UTC, jyeost commented on src/main/java/blackjackgame/domain/Result.java
> +    }
생성자에서 로직을 피하고 외부에서 어느정도 만들어서 넣어주려고 Judge 객체를 만들었습니다 !

2023-03-07 08:24 UTC, jyeost commented on src/main/java/blackjackgame/domain/player/Guests.java
> +    }
생성자의 로직을 컨트롤러 메서드에서 처리해주도록 만들었습니다!

2023-03-07 12:33 UTC, jyeost commented on src/main/java/blackjackgame/controller/blackJackController.java
> +        final Deck deck = new Deck();
해당 객체들은 생성 이후에 내부의 상태가 변할 수 있기 때문에, 불변 객체가 아니며 
final을 통해 재할당만 막아주고 있는 상태입니다...!

이전까지는 불변객체에 대한 이해도가 낮아서 구현해보지 못했는데, 2차구현에서 시간이 된다면 바꿔보도록 하겠습니다...!!

2023-03-07 12:52 UTC, jyeost commented on src/main/java/blackjackgame/domain/Result.java
> +    private static final int BLACKJACK_MAX_SCORE = 21;
해당 상수도 Jugde 클래스로 이동하도록 하였습니다

2023-03-07 13:50 UTC, jyeost commented on src/main/java/blackjackgame/domain/Result.java
> +    }
result의 dto를 만들어서 사용하는 식으로 해보았는데요!
첨으로 구현해 본 것이라 제대로 되었는지 모르겠네요..ㅜㅜ
이번미션에서 dto를 제대로 사용해 보고 싶었는데 resultDto 처럼 만들어도 된다고 하면 다른 객체들도 한 번 만들어 보고 싶습니다..!!

2023-03-08 05:58 UTC, jyeost commented on src/main/java/blackjackgame/domain/player/Player.java
> +    public abstract String getName();
`추상 메서드의 경우, 추상클래스의 메서드내에 노출되어야 그 의미가 더 명확히질 것 같아요.`

이 부분은 접근제한자를 private 으로 만들라는 말인가요??
의미가 명확해진다는 것이 무슨 뜻인지 모르겠어요...

해당 부분에 대해 더 알아 볼 수 있는 자료가 있을까요? ㅜㅜ 추후에 수정하도록 하겠습니다...

2023-03-09 10:57 UTC, Livenow14 approved these changes
안녕하세요 케로...! 고생많으셨어요.

몇가지 간단한 피드백 남겼는데, 다음 미션 진행하면서 같이 진행해주시면 좋을 것 같아요.

전반적인 피드백 남긴다면
> comment에 의견(댓글)을 꼭 달아주세요.

이해가지 않는 부분이 있다거나, 동의되지 않는 부분이 있다면, 꼭 댓글로 반영여부 남겨주시길 부탁드려요. 
반영 여부를 확인하기 힘들어 더 나은 리뷰를 하기 힘들어서요. 

단순히 미션 완료에 목표를 잡지 않고, 함께 좋은 소프트웨어를 만들어 간다고 생각해주시면 좋겠어요 :) 

진행하시다가 어려운 부분이 있으면, 언제든 DM 주세요 :)

2023-03-09 10:57 UTC, Livenow14 commented on src/main/java/blackjackgame/controller/blackJackController.java
> +        final Dealer dealer = new Dealer(deck.firstPickCards());
Deck과 Dealer가 만들어진 상황에서, Quest가 들어온다 가정해보면 어떨까요?? 
그러면, 생성자의 인자로, 넣어줄 수 있을 것 같아요. 
ex) BlackJackGame 객체 등을 만들어 보는것. 

Controller의 책임이 모호해지는 것 같아서요.

2023-03-09 10:57 UTC, Livenow14 commented on src/main/java/blackjackgame/controller/blackJackController.java
> +        askDealerHitCardRepeat(dealer, deck);
"물어본다"라는 의미가 모호한것 같아요. 단순히 hitCard 로 할 수 없을까요?

Card getCards()를 Card askGiveCard() 등으로 바꾼거 같은 느낌이에요.

2023-03-09 10:57 UTC, Livenow14 commented on src/main/java/blackjackgame/controller/blackJackController.java
> +        askDealerHitCardRepeat(dealer, deck);
GameController의 책임이, 정말로 다른 객체에게 "물어보는것"일까요?

객체에 메세지를 전달하는 것은, "~~를 수행하세요" 가 되어야하지, "~~를 수행할 수 있는지 물어보기" 가 되면 안돼요.
그 이유로는, "~~를 수행하세요를" 수행할 수 있는 객체가  그 책임을 수행하기 때문이에요. 

판사가, 피고인에게 "증언하세요" 라고 한다면 
해당 요청을 수행해야하는 피고인은 "증언하다"라는 책임을 수행하는 것이에요..

판사가, 피고인에게 "증언할수 있는 사람이면, 증언하세요"라고 한다면 어색하지 않을까요?
애초에, 판사는 "증언하세요"를 수행할 수 잇는 사람을 피고인 역할로 설정하기 때문이에요.

2023-03-09 10:57 UTC, Livenow14 commented on src/main/java/blackjackgame/controller/blackJackController.java
> +        judgeAndPrintResult(guests, dealer);
printPlayersCardScore  -> printScore

2023-03-09 10:57 UTC, Livenow14 commented on src/main/java/blackjackgame/controller/blackJackController.java
> +        judgeAndPrintResult(guests, dealer);
judgeAndPrintResult -> printResult

2023-03-09 10:57 UTC, Livenow14 commented on src/main/java/blackjackgame/controller/blackJackController.java
> +    }
의도는 파악되나, 잘 읽히지 않아요. 
정말 generateGuests의 책임을 위한 구현일까요?

2023-03-09 10:57 UTC, Livenow14 commented on src/main/java/blackjackgame/domain/GameOutcome.java
> +public enum GameOutcome {
GameOutcome  -> GameResult

2023-03-09 10:57 UTC, Livenow14 commented on src/main/java/blackjackgame/domain/Judge.java
> +        Map<Guest, GameOutcome> guestsResult = new LinkedHashMap<>();
결과를 출력해야할 때, 매번 LinkedHashMap이 생성되겠네요..!

2023-03-09 10:57 UTC, Livenow14 commented on src/main/java/blackjackgame/domain/card/Card.java
> +        return cardValue.getValue().equals(CardValue.ACE.getValue());
cardValue == CardValue.ACE

2023-03-09 10:57 UTC, Livenow14 commented on src/main/java/blackjackgame/domain/player/Player.java
> +    public abstract String getName();
추상메서드가 외부에서 사용하기 위해서만 사용된다면, 인터페이스로도 충분하지 않을까요? 

물론, 추상클래스의 구현클래스의 속성 중복을 막을 수 있다지만, 
구현클래스가 2개정도라면, 중복해도 괜찮을 것 같아서요.

2023-03-09 10:57 UTC, Livenow14 commented on src/main/java/blackjackgame/view/AddCardResponse.java
> +    }
enum이 아닌, 클래스로 관리해보는건 어떨까요?

2023-03-09 10:57 UTC, Livenow14 commented on src/test/java/blackjackgame/domain/CardTest.java
> +        Card spadeFive = new Card(Symbol.SPADE, CardValue.FIVE);
test fixture를 활용해봐도 좋겠네요 :)

2023-03-09 10:57 UTC, merged

2023-03-13 06:43 UTC, jyeost commented on src/main/java/blackjackgame/controller/blackJackController.java
> +        judgeAndPrintResult(guests, dealer);
수정하였습니다 ! 🫡

2023-03-13 06:43 UTC, jyeost commented on src/main/java/blackjackgame/controller/blackJackController.java
> +        judgeAndPrintResult(guests, dealer);
수정하였습니다 ! 🫡

2023-03-13 06:44 UTC, jyeost commented on src/main/java/blackjackgame/domain/card/Card.java
> +        return cardValue.getValue().equals(CardValue.ACE.getValue());
정신을 빼놓고 작성 했나바여... ㅜㅜ 수정했습니다...!!!

2023-03-14 04:23 UTC, jyeost commented on src/main/java/blackjackgame/domain/player/Player.java
> +    public abstract String getName();
일단, 요구 사항에 
3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.
딜러와 플레이어에서 발생하는 중복 코드를 제거해야 한다.

두가지 이유가 있었기 때문에 추상클래스를 사용하여 게스트와 딜러의 공통 변수인 state를 빼서 필드에 저장하고, 구현 메소드를 만들어 중복을 없애주었습니다.

또 추상메서드는 protected를 사용하여 구현체에서 사용하도록 하였고, 구현 메서드들은 final 키워드를 붙여 재할당을 막았습니다.

2023-03-14 04:29 UTC, jyeost commented on src/main/java/blackjackgame/controller/blackJackController.java
> +        askDealerHitCardRepeat(dealer, deck);
지금까지 메서드명을 기능에 치중하여 쓰고 있었다는 생각이 드네요.... 
이런게 바로 객체에 기반한 메서드명이군여.... 앞으로 참고하고 메서드명 짓도록 하겠습니다..!!!

좀 다른 질문인데 view에 입력값을 받아오기 위하여 read를 앞에 붙인 메서드명은 괜찮을까여...??

2023-03-14 04:31 UTC, jyeost commented on src/main/java/blackjackgame/controller/blackJackController.java
> +    }
generateGuests -> initializeGuests
getGuests -> generateGuests

이렇게 고쳤는데 잘 고친지 모르겠어요.. 아무리 생각해도 좋은 메서드명이 떠오르지 않습니다....🥲

2023-03-14 04:33 UTC, jyeost commented on src/main/java/blackjackgame/controller/blackJackController.java
> +    private void printFirstCards(final Guests guests, final Dealer dealer) {
아예 플레이어 객체 자체를 넘겨서 컨트롤러의 해당 메서드를 없앴는데, 객체를 참조하는 view에서는 노출이 되어도 되는지 궁금합니다...!!

2023-03-14 04:34 UTC, jyeost commented on src/main/java/blackjackgame/domain/GameOutcome.java
> +public enum GameOutcome {
수정하였습니다 ! 🫡

2023-03-14 04:55 UTC, jyeost commented on src/main/java/blackjackgame/domain/Judge.java
> +        Map<Guest, GameOutcome> guestsResult = new LinkedHashMap<>();
해당 메서드를 static 함수로 고쳤고, 만약 다른 플레이어들의 수익금도 계산/출력 해야할 때 util처럼 사용하려면 메서드를 실행할때마다 새로 생성해서 사용하는 것이 좋다고 생각하는데...

검프는 어떻게 생각하시는지 궁금합니다...!

2023-03-14 12:36 UTC, jyeost commented on src/test/java/blackjackgame/domain/CardTest.java
> +        Card spadeFive = new Card(Symbol.SPADE, CardValue.FIVE);
넵!! 🫡

2023-03-14 12:45 UTC, jyeost commented on src/main/java/blackjackgame/view/AddCardResponse.java
> +    }
저는 YES와 NO이외의 다른 값이 추가될 가능성이 없고, YES와 NO의 상관관계를 알기 명확하다는 점, 
y와 n에 해당하는 값이 들어오지 않았을 때, Optional을 반환해 줄 수 있어서 에러를 던지지 않고 처리할 수 있다는 점,
이를 사용하는 컨트롤러에서도 y인지 n인지 확인하기 위한 별도의 메서드가 필요하지 않다는 편리성 때문에 enum클래스를 사용하였습니다..!!

클래스로 관리하면 이만큼의 장점을 가질지는 솔직히 잘 모르겠어용....

2023-03-14 12:59 UTC, jyeost commented on src/main/java/blackjackgame/controller/blackJackController.java
> +        final Dealer dealer = new Dealer(deck.firstPickCards());
Quest가 Guest 였던 걸까여...??
BlackJackGame의 생성자에 Guests를 넣어준다는 뜻이였나요..??
사실 이 부분은 제대로 이해하진 못하고 컨트롤러에 로직이 많아서 이런 리뷰를 주셨다고 생각했어요.
그래서 BlackJackGame을 만들어보려 했는데,,, 뭔가 뷰와 소통하는 부분이 많은데 단계만 한 번 더 늘어나고 복잡해지는 것 같아서  추가하진 못했습니다.... ㅜㅜ