[1단계 - 블랙잭 게임 실행] 하디(전동혁) 미션 제출합니다.
woowacourse/java-blackjack pull request #425
Opened 2023-03-03 08:09 UTC by jundonghyuk

안녕하세요 또링! 리뷰이 하디입니다.

제가 고민한 점은 다음과 같습니다.
**1. Deck을 static으로 정의할지 외부에서 주입받을지를 고민했습니다.**
- Deck은 모든 플레이어와 딜러가 공유하는 자원이므로, static으로 선언하는게 적절하다 생각했으나, 애초에 static자체는 객체지향적인 느낌과는 거리가 있는 것 같고, 모든 플레이어와 딜러가 블랙잭 게임내에서 같은 덱을 공유하는건 쉽게 처리해줄 수 있으므로, 인스턴스를 하나만 생성하여 주입시켜줬습니다.

**2. OutputView가 Enum Class를 알고 있어도 되는지 고민입니다.**
- 도메인과 뷰의 의존성을 끊는게 서로 영향을 줄일 수 있으므로 좋은 방법이라고 생각하지만, Enum정도는 넘겨줘도 될 것 같아 넘겨주었습니다. Outcome Enum내 "Win", "Draw", "Lose"는 바뀌지 않을 것 같아 이렇게 처리하였습니다.
하지만 뷰가 도메인을 알고있는 꼴이긴하니 쓰면서도 좀 걱정이 되었습니다.

**3. 컨트롤러의 역할은 어디까지인가 ?**
- 컨트롤러는 흐름제어의 역할이라고 생각합니다.
그런데 흐름제어의 기준점이 너무 헷갈립니다. 만약 전체 플레이어를 돌면서 어떤 로직을 실행시켜야한다면, 전체 플레이어를 도는 for문은 컨트롤러에 있어야하는지 서비스 격인 BlackJackGame에 있어야하는지 고민이 됩니다.

읽어주셔서 감사합니다.
오늘도 좋은 하루 되세요:)

2023-03-05 11:21 UTC, jnsorn requested changes
안녕하세요 하디! 블랙잭 잘 구현해주셨네요. 🃏
전반적으로 프로그래밍 요구사항이 잘 지켜져서 코드가 깔끔하다는 느낌을 받았어요.
다만 BlackJackGame이 많은 일을 하고 있는 것 같아요. 해당 객체의 역할에 대해 더 고민해보면 좋을 것 같습니다. 그 외에 몇 가지 코멘트 남겨두었으니 확인해주시고, 다시 요청주세요 😃

2023-03-05 11:21 UTC, jnsorn commented on src/test/java/domain/DealerTest.java
> +    }
테스트가 깔끔하네요 👍

2023-03-05 11:21 UTC, jnsorn commented on src/test/java/domain/BlackJackGameTest.java
> +public class BlackJackGameTest {
결과에 대한 테스트는 빠져있네요. 추가해주세요!

2023-03-05 14:29 UTC, jundonghyuk commented on src/main/java/controller/MainController.java
> +public class MainController {
예를 들면,
MainController에 
```java
private void drawCardsPlayer() {
        names.forEach(this::drawWhileYes);
}

private void drawWhileYes(final String playerName) {
     boolean answer = true;
     while (answer) {
         OutputView.printOneMoreCard(playerName);
         answer = isOneMore(playerName);
     }
}
```
로직입니다. 더이상 카드를 안뽑겠다는 n이라는 인풋이 올 때 까지 컨트롤에서 반복을 돌리는데, n이라는 인풋을 판단하는 로직이 컨트롤러에 들어가있습니다.
물론 메시지를 보내 더 받을 건지 도메인에 물어보긴 했지만, 이 부분이 고민입니다.

2023-03-05 14:32 UTC, jundonghyuk commented on src/main/java/view/OutputView.java
> +    private static void printDealerResult(final Map<String, Outcome> result) {
모든 이넘이 그렇다고 생각하진 않습니다.
현재 Outcome이라는 이넘안에는 단순히 WIN, DRAW, LOSE라는 이넘 객체만 정의되어있고 별다른 로직은 없습니다.
이 WIN, DRAW, LOSE라는 이넘 도메인은 절대 변하지 않을 것 같아 이정도는 뷰가 알아도 상관없다고 생각했습니다.
애초에 도메인과 뷰가 서로 몰라야 하는 이유가 둘 중 하나에 변경이 일어날 때 둘다 바뀌어야 되는 의존관계가 있다고 생각해서 입니다.
하지만, Enum Domain인 Outcome은 위와 같은 이유로 로직도 없고 바뀌기 어렵다고 생각해 뷰가 해당 이넘을 알도록 설계했습니다.

2023-03-05 14:41 UTC, jundonghyuk commented on src/main/java/controller/MainController.java
> +        Deck deck = new Deck();
단적으로 static으로 설계하면, 모든 곳에서 접근이 가능합니다. 
해당 객체를 필요로하는 곳 이외에 접근이 가능하므로, 어디서든 호출해서 사용할 수 있으므로 값을 공유하는 특성상 불안정하다고 생각했습니다.

멀티스레드 환경에 대한 저의 생각을 말해보겠습니다!
static이 멀티스레드 환경에서의 근본적인 문제인가요 ??
동시성의 문제라 static이든 static이 아니든, 특정 도메인이 공유하는 자원을 사용할 경우 어디든 생길 수 있는 문제가 아닌가라는 생각을 해봤습니다. 그 중 대표적인 예시가 스태틱이라 생각합니다.

어떻게 생각하시는지 리뷰어님의 고견이 궁금합니다 :)!!

2023-03-05 14:44 UTC, jundonghyuk commented on src/main/java/domain/game/BlackJackGame.java
> +public class BlackJackGame {
적용해보겠습니다 ! 
감사합니다 ㅎㅎㅎㅎ
다른 것에 초점을 맞추느라 일급컬렉션 사용을 잊고있었습니다..!

2023-03-05 14:44 UTC, jundonghyuk commented on src/main/java/domain/player/Name.java
> +            throw new IllegalArgumentException();
깜빡했네요 채워넣겠습니다 :) 
좋은 지적 감사합니다.

2023-03-05 14:50 UTC, jundonghyuk commented on src/main/java/domain/deck/Deck.java
> +    private final Stack<Card> cards;
deque로 바꾸었습니다.
리뷰어님 덕분에 스택을 상속구조를 뜯어보는 좋은 경험이 되었습니다 :)
감사합니다 !!

2023-03-05 14:53 UTC, jundonghyuk commented on src/main/java/domain/deck/Deck.java
> +            cards.push(new Card(suit, rank));
이 부분에서 제일 고민을 많이했습니다. 
리뷰어님의 질문을보고 52개의 카드를 리스트안에 보관했습니다

이 과정속에서 생각한 것들을 조금 길지만 글로 적어보겠습니다. ..!

Card를 생성자를 통해 생성하는 방식은 매번 같은 문양과 같은 숫자의 카드를 중복해서 생성할 가능성이 있습니다.

그렇다고, 이넘안에 52개를 정의한다..? (뭔가 좀 아닌 것 같아서 배제했습니다. 코드량이 많아져서,,?)

그러므로 내부에서 52장의 카드를 모두 만들어 컬렉션(리스트)에 저장해두고 외부에서 필요한 카드가 있으면 이 안에서 찾아서 반환해주었습니다.

여기서 trade-off를 생각해보면,

매번 new Card(Suit suit, Rank rank)로 같은 문양과 숫자의 카드를 계속 생성하여 메모리 낭비가 있을 수 있다라는 단점이 존재한다.

이를 개선하고자 정적 메서드를 사용해서 그 안에서 52장의 카드 인스턴스를 모두 생성해 리스트로 보관하고 외부에서 특정 문양과 숫자를 가진 카드를 찾을 때 마다 getCard라는 메서드를 통해 미리 52개의 카드를 저장해두었던 리스트를 순회하면서 인스턴스를 반환한다. 그렇기에 항상 카드가 필요할 때 마다 리스트를 순회해야해 시간이 더 많이 드는 단점이 있다.

결국 생성자를 통하면 메모리 낭비가 될 수 있다는 단점이있고, 정적으로 52개의 인스턴스를 보관하며 이를 매번 찾아서 반환해주면 시간이 많이 든다는 단점이 있다.

프로젝트가 메모리에 critical한지, 시간에 critical한지에 따라 달라지겠지만, 일반적으로 걸리는 시간의 중요도가 더 높다고 생각해 처음방법보다 바꾼 방법이 더 손해이다(?)라는 생각이 들었습니다.



이를 개선하고자, 문양인 Suit과 숫자의 Rank를 필드로 갖는 Key라는 클래스를 정의하여 key로는 새로 정의한 Key Class를, value로는 그에 맞는 카드 인스턴스를 52개 쌍을 갖는 Map을 정의하고자 했다.

Map은 List처럼 순회하지 않아도 되어서 시간적인 이점이 있을거라 생각했다.

근데 이것도 결국 똑같은게, 결국에 Suit, Rank로 Key라는 객체를 만들어야하므로 메모리 낭비(?)가 나는건 아닌가 라는 생각이 들었습니다. 물론 그 객체는 카드 인스턴스를 찾기위한 Key로만 사용되어 그에 맞는 카드를 찾아 반환한 뒤에는 쓰지 않아 GC가 금방 처리해줄 것 같지만 말이죠..



이러한 Key라는 클래스를 새로 정의해서 하고자한 이유는, Suit, Rank 두 개의 조합이 key라고 생각했기 때문입니다. key는 하나여야 하기에 둘을 조합할 수 있는 방법으로 하나의 클래스 설계를 떠올렸던 것입니다.

결론을 말하자면, 현재 제가 구현한 방법인 52개의 카드를 리스트에 담아 매번 순회하며 반환해주는 방식이 time consuming한 방법이라 별로인 방법인지 궁금합니다.
아니면 더 좋은 방법이 있는지 궁금합니다.

2023-03-05 14:54 UTC, jundonghyuk commented on src/test/java/domain/DealerTest.java
> +    }
감사합니다 :)

2023-03-06 04:57 UTC, jundonghyuk commented on src/test/java/domain/BlackJackGameTest.java
> +public class BlackJackGameTest {
넵 추가했습니다 !

2023-03-06 06:05 UTC, jundonghyuk commented
안녕하세요 ! 리뷰이 하디입니다.

리뷰어님의 질문에 대해서 저의 생각을 각 커멘트 밑에 리플라이로 달아 두었습니다.

그 중에서 Card 객체의 생성에 대해서 길게 쓴 댓글이 있는데 읽어주시면 감사하겠습니다 !

오늘도 좋은 하루되세요 :)

2023-03-08 02:40 UTC, jnsorn approved these changes
안녕하세요, 하디! 피드백 잘 반영해주셨네요. 👍 
조금 더 이야기 나눠보면 좋을 부분에 대해 코멘트 남겨두었어요.
2단계 진행하면서 같이 반영해주세요. 🃏

2023-03-08 02:40 UTC, merged

2023-03-08 03:13 UTC, jnsorn commented on src/main/java/domain/game/BlackJackGame.java
> +    }
참고로 블랙잭에는 Hit이라는 용어도 있어요 😃

2023-03-08 07:02 UTC, jundonghyuk commented on src/main/java/domain/game/BlackJackGame.java
> +public class BlackJackGame {
다른 도메인과 컨트롤러 사이의 다리라고 생각합니다.
여러 도메인들간의 로직이 필요한 경우 블랙잭 게임에서 해야한다고 생각합니다.
예를 들면, 플레이어(Player)와 딜러(Dealer)의 점수를 비교하여 View에 건내줄 자료구조를 정의한 뒤 초기화 시키는 것이 있습니다.
decideDealerOutcome등이 그 예시입니다.

2023-03-08 07:42 UTC, jundonghyuk commented on src/main/java/view/OutputView.java
> +    private static void printDealerResult(final Map<String, Outcome> result) {
넵 모아보겠습니다 !

2023-03-08 08:16 UTC, jundonghyuk commented on src/main/java/domain/player/Players.java
> +    }
채워넣었습니다 !

2023-03-08 08:23 UTC, jundonghyuk commented on src/main/java/domain/player/Dealer.java
> +public class Dealer extends Player {
딜러는 플레이어의 역할도 수행하고 있기 때문에 상속을 선택하였습니다.
결국 딜러도 플레이어이기 때문에 is a 관계라고 생각해서 상속을 선택했습니다.

2023-03-08 08:26 UTC, jundonghyuk commented on src/main/java/domain/player/Players.java
> +    }
`.filter(player -> ! (player instanceof Dealer))`를 사용했습니다.

2023-03-10 05:33 UTC, jundonghyuk commented on src/main/java/controller/MainController.java
> +public class MainController {
처음엔 다른 도메인 접근없이 서비스 도메인만 받아 그를 통해 흐름을 제어한다고 생각했는데, 생각이 바뀌었습니다..

2023-03-10 05:33 UTC, jundonghyuk commented on src/main/java/domain/game/BlackJackGame.java
> +    }
참고하겠습니다 !