[1단계 - 블랙잭 게임 실행] 주노(최준호) 미션 제출합니다.
woowacourse/java-blackjack pull request #429
Opened 2023-03-03 08:13 UTC by Choi-JJunho

서브웨이 🥪 안녕하세요!
페어 블랙캣 🐈‍⬛과 함께 블랙잭 게임 미션 1단계를 진행했습니다.

리뷰 잘부탁드립니다🙇‍♂️

# ✔️ 구조 설명

저희는 블랙잭게임을 아래와 같이 도메인을 분석하고, 설계하였습니다. 

블랙잭 게임에 존재하는 `User`는

- 플레이어 (`Player`)
- 딜러 (`Dealer`)

게임 진행에 필요한 주요 클래스는

- 카드 (`Card`)
- 카드팩 (`CardPack`)

플레이어와 딜러의 공통(`User`) 역할은 다음과 같습니다.

- ‘*카드팩에서 카드를 뽑을 수 있다*’
- ‘*이름을 가질 수 있다.*’

# ✔️ 전략패턴의 사용

카드팩을 섞는 로직은 *`ShuffleStrategy`*인터페이스를 이용한 전략 패턴으로 

구현부는 크게 `MasterShuffleStrategy`, `NoviceShuffleStrategy`로 구성했습니다.

Production 부분의 `MasterShuffleStrategy` 구현 클래스는 `Collections.suffle()` 메소드를 이용하였고, Test 부분의 `NoviceShuffleStrategy` 구현 클래스는 카드를 맨 밑장을 맨 위로 올리는 임의의 규칙을 정의하여 로직으로 구현하여 테스트를 진행했습니다.

# ✔️ 심판 역할

게임 결과를 도출하는 과정에서 다음과 같은 역할을 구성하였습니다.

- 카드 숫자의 합을 계산하는 역할인 `ScoreReferee` 클래스
- 각 유저/딜러의 점수를 기록하는 역할인 `ScoreBoard` 클래스
- 각 플레이어의 승부결과(승리, 패배, 무승부)를 계산하는 `ResultReferee` 클래스

---

# Q. 점수관련

다음과 같이 Enum 내부에 View와 관련된 필드가 다수 존재하여 도메인이 View를 의존하게 되는건 아닌지 조금은 조심스러웠지만 일단 출력을 하기 위해 필요한 부분이니 추가하였습니다.

``` java
public enum GameResult {

    WIN("승"),
    LOSE("패"),
    DRAW("무");

    private final String view;

    GameResult(final String view) {
        this.view = view;
    }

    public String getView() {
        return view;
    }
}

```

위와 같이 Enum의 특정 필드가 View에 의존하게 되는 상황에 대해 저는 단순하게 상태만 나타내는 상수의 모임이기 때문에 View에 의존해도 어느정도 괜찮지 않을까? 라는 안일한 생각으로 위와같이 구성했습니다..😅

Enum 필드를 View에서 출력하기 위해서는 어떻게 해야하는가? 에 대한 서브웨이의 의견이 궁금합니다.

2023-03-05 08:56 UTC, joseph415 requested changes
안녕하세요 주노!

블랙잭 미션 구현하시느라 고생 많으셨습니다!
코멘트 남겼습니다! 확인부탁드려요~ 질문해주신거는 리뷰에 같이 남겼습니다!

2023-03-05 08:56 UTC, joseph415 commented on src/main/java/blackjack/view/InputView.java
> +                        + "(예는 " + Command.YES.name()
View에서 하라는대로 입력하니까, 에외가 발생하네요ㅎ

2023-03-05 08:56 UTC, joseph415 commented on src/main/java/blackjack/controller/BlackjackController.java
> +        while (!blackjackGame.isDealerEnd(dealer)) {
```
딜러는 처음에 받은 2장의 합계가 16이하이면 반드시 1장의 카드를 추가로 받아야 하고, 17점 이상이면 추가로 받을 수 없다.
```
가 요구사항인데요. 딜러는 2장의 합계가 16이하면, 1장의 카드를 받아야하는데, 이렇게 되면 딜러는 항상 16이상인거고,  16이하일 경우 계속 받게 될텐데 버그이지 않을까요~?

2023-03-05 08:56 UTC, joseph415 commented on src/main/java/blackjack/domain/game/GameResult.java
> +    private final String view;
보통 말하는 View에 대한 의존성은 직접 import해서 사용한다던가, 객채를 그대로 가져와서 사용할 때(?)를 이야기합니다ㅎ 그래서 그냥 WIN, LOSE, DRAW를 나타내는 속성정도로 생각해도 좋을 것 같긴 한데요ㅎㅎ

그런데, 굳이 필요하지 않는 속성값이라고 생각이 들어서 찜찜하다면, **VIEW에서 WIN일 경우 "승"을 보여주도록 하는 방식**도 좋을 것 같습니다.

해당 ENUM은 그냥 상수가 아니라 도메인 비지니스에 관련된 상수이기 때문에 관리가 필요한 상수입니다. 그래서
> View에 의존해도 어느정도 괜찮지 않을까? 
라는 생각은 잘못된것 같아요!

웹서비스에서 enum을 출력할 떄, name으로 꺼내서 클라이언트에서  **WIN일 경우 "승"을 보여주도록 하는 방식** 으로 사용한다던가 웹으로 데이터를 내려줄 때, dto로 정제해서 내려주기도 합니다. 그대로 내려주지는 않습니다~

2023-03-06 06:10 UTC, Choi-JJunho commented on src/test/java/blackjack/domain/util/NoviceShuffleStrategy.java
> +package blackjack.domain.util;
`util은 어느 패키지, 혹은 어느 로직에 사용되어도 무관해야한다.` 라는 규칙을 생각해보면 맞는 말인것 같아요!

cardpack에서만 사용되는 전략으로 생각하여 cardpack 패키지로 이동하여 해당 문제를 해소했습니다.

2023-03-06 06:12 UTC, Choi-JJunho commented on src/main/java/blackjack/domain/card/Card.java
> +    @Override
equals와 hashCode는 자주 사용해보지 않아 순서에 관하여 익숙하지 않았네요!
정리 및 참고글 감사합니다!

2023-03-06 06:17 UTC, Choi-JJunho commented on src/test/java/blackjack/domain/cardpack/CardPackTest.java
> +        Assertions.assertThat(cardPack.pop()).isNotEqualTo(card);
적절한 테스트가 아니라고 생각되네요...

CardPack의 초기 사이즈와 뽑은 후 사이즈를 비교하는 테스트로 수정했습니다!

2023-03-06 06:21 UTC, Choi-JJunho commented on src/test/java/blackjack/domain/cardpack/CardPackTest.java
> +                for (int i = 0; i < 13; i++) {
앗 테스트를 미처 신경못썼네요 😅

2023-03-06 07:03 UTC, Choi-JJunho commented on src/main/java/blackjack/view/InputView.java
> +                        + "(예는 " + Command.YES.name()
헉.. name이 아니라 getCommand을 만들어서 사용했어야했는데 😂
수정했습니다!

2023-03-06 07:30 UTC, Choi-JJunho commented on src/main/java/blackjack/domain/game/ScoreReferee.java
> +    public static final int BUST_NUMBER = -1;
상수 자동추출간 자동으로 public으로 설정되었는데 미처 확인하지 못했네요 😂

2023-03-06 07:43 UTC, Choi-JJunho commented on src/main/java/blackjack/domain/user/User.java
> +public class User {
초기에는 딜러와 플레이어가 `카드를 뽑는다`, `카드를 보여준다`, `이름을 보여준다` 라는 공통된 역할을 가진다. 라고 생각하여 공통된 로직은 상속으로 분리해야지~ 라는 단순한 생각으로 구성을 진행했습니다 😂

왜 상속을 사용하는지, 상속을 사용하면 어떤 점이 좋은지에 대한 부분을 고민해보지 못했네요.

제시해주신 합성으로 풀어내는 방식을 시도해봐야겠어요!!

2023-03-07 06:51 UTC, Choi-JJunho commented
서브웨이 🥪 안녕하세요!
상속으로 구성했던 구조를 조합으로 수정하면서 많은 고민을 했습니다.

- 왜 상속을 사용해야하는가?
- 왜 조합을 사용해야하는가?
- 조합을 사용하면 어떤 이점이 있는가?
- 현재 내가 구성한 도메인은 상속, 조합 중 어떤 것이 유리하다고 생각하는가?

다양한 의문점에 대한 답변을 스스로 하면서 합당한 근거를 찾아가는 과정을 거치느라 리팩터링 과정이 많이 느렸습니다.
구조 자체를 변경하다보니 커밋도 하나로 뭉쳐졌네요 ㅠㅠ 🥺

처음 알게된 조합에 대한 이해를 위해 리팩터링을 진행하다보니 말씀해주신 `상속보다 조합(Composition)을 사용하자`라는 말을 이해할 수 있었던 시간이였습니다.

고민을 해소하는 과정으로 리팩터링을 진행하다보니 부족한점이 많을것 같습니다 😂

---

위 고민에 대한 스스로의 답변은 다음과 같습니다.

## 기존 (왜 상속을 사용해야하는가?)

공통된 로직이 존재하면 상속을 이욯아여 분리할 수 있다. 
상위 도메인 혹은 비즈니스 로직에서 instanceOf를 이용하여 각 구현체 별로 분기를 나눌 수 있어 코드를 간략화 할 수 있다.
ex)
``` java
// User를 상속받는 Player, Dealer가 존재할때

public void drawCard(User user) {
    // 상위 도메인에서 공통된 동작을 요구할 때 같은 부모를 가지는 객체를 인자로 받아 간략하게 추릴 수 있다.
    user.draw();
}
```

## 현재 (왜 조합을 사용해야하는가?)

상속을 이용하면 부모 클래스의 구현체를 알고 해당 필드를 직접 사용한다는 부분에서 부모의 변경사항에 자식 클래스의 구현 내용이 취약해진다는 점을 알게 되었습니다.

조합을 이용한다면 객체간 메시지 전달을 통해 연관관계가 구성되므로 필드로 포함된 객체의 변경사항에 큰 영향을 주지 않는다는 장점을 인지하게 되었습니다.

조합이라는 방식이 매우 생소하여 왜 조합을 사용해야하지? 에 대한 의문을 계속 가지고 고민을 했었는데 서브웨이 덕분에 좋은 혜안을 얻을 수 있었습니다 😆

## 현재 내가 구성한 도메인은 상속, 조합 중 어떤 것이 유리하다고 생각하는가?

### 상속?

현재 상태에서는 상속을 사용하면 다음과 같은 이점이 있다고 생각합니다.
- 공통 로직을 상위 클래스로 분리할 수 있다.
- 상위 도메인을 인자로 받음으로써 해당 객체를 사용하는 다른 메소드의 재사용성이 용이해진다.

### 조합?

조합을 사용한다면 다음과 같은 이점이 있다고 생각합니다.
- 객체간 메시지 전달을 통해 값을 이용할 수 있으므로 공통객체(?) 에 대한 변경에 보다 용이한 구성을 가질 수 있다.
  - 이는 곧 객체간 강한 결합 및 의존성을 약하게 풀어줄 수 있음을 의미하기도 한다.
  - 또한 강한 결합으로부터 자유로워짐으로써 캡슐화에 용이한 구조를 가질 수 있다.
  - 강한결합으로부터 자유로워짐으로써 Runtime 시점에서 변경이 용이하다는 점도 하나의 예시가 될 수 있다.
- is-a 관계를 명확하게 구분할 수 없을 때 사용하기 좋다.


추가적인 장단점은 지금 당장 생각나지 않지만 지금으로서 조합에 대한 설득력이 더욱 타당하다고 생각하여 상속 대신 조합을 사용하는 구조를 채택하여 리팩터링을 진행했습니다.

---

코드를 변경하면서 다음과 같은 변경사항도 있었습니다.

# 변경사항

- User를 상속받아서 사용했던 구조를 Participant를 필드로 가지는 조합 구조로 변경했습니다.

- 기존의 ScoreReferee가 수행하던 점수 계산 로직을 Hand 클래스에 위임했습니다.
  - 플레이어 / 딜러로부터 즉시 점수를 얻을 수 있습니다.
  - 딜러로부터 딜러의 승부 결과를 얻을 수 있습니다. (n승/n패)

- ResultReferee가 수행하던 로직을 Controller에 위임했습니다
  - 이제 Controller에서 플레이어의 승부 결과를 모아서 View에서 사용하도록 변환해줍니다.

> 해당 부분은 View에 출력하기 위해 데이터를 변환하는 과정으로 인지하였기에 BlackjackGame 도메인이 아닌 Controller에 위치시켰습니다.
```java
private Map<String, GameResult> getPlayerScoreResult(final Dealer dealer, final Players players) {
    Map<String, GameResult> result = new HashMap<>();

    players.getPlayers().forEach((player) -> {
        int playerScore = player.getScore();
        GameResult gameResult = dealer.declareGameResult(playerScore);
        result.put(player.getName(), gameResult);
    });

    return result;
}
```

# 추가된 기능

- 잘못된 입력 시 재입력을 요구합니다.

2023-03-07 17:11 UTC, joseph415 commented on src/main/java/blackjack/view/OutputView.java
> +import blackjack.domain.card.Card;
요거는 놓치신것 같은데, 답변 부탁드릴게요ㅎㅎ

2023-03-07 17:45 UTC, joseph415 commented
### 기존 (왜 상속을 사용해야하는가?)

상속을 이용하는 이유로 공통 로직이 존재하기 때문에 사용하는것 이라고 해줬는데 해당 이유로 상속을 사용하면 단점이 더 큰 상황이 될거라고 생각합니다! 저는 위에 리뷰 답변으로 달아둔 것 처럼 상속은 다음과 같을 때 사용하는데

1. 추상클레스로 알고리즘 뼈대를 만들고 추상화할 메서드를 구체클레스로 구현할 때
2. 구체 클래스 별로 특별한 행위를 하게될 때

단순히 공통된 로직때문에 상속을 사용한다는 것은 장점보다 단점이 더 많아 보여요ㅎ instanceOf 를 사용하면서 OCP 가 깨지는 문제도 그렇고요!
**그래서 저는 상속은 추상클레스를 사용해 메서드를 추상화 해야할 때만 사용하는것 같아요.**

그리고 상속을 사용하는 이유중 가장 큰 이유는 다형성을 이용하는 것이라고 생각하는데, 주노가 작성해주신 코드를 봤을 땐 그걸 이용하는 거 같지 않아서 리뷰를 드렸습니다!

2023-03-07 18:30 UTC, joseph415 requested changes
안녕하세요 주노!

전체적으로 리펙토링을 해주셨군요ㅎㅎ👍
이전 리뷰에 대한 답변중 추가 답변달아둔 것 확인해주세요! 코멘트 적용했는데, 확인 부탁드리겠습니다.

2023-03-07 18:30 UTC, joseph415 commented on src/main/java/blackjack/domain/game/BlackjackGame.java
> +    public boolean isEnd(final int score) {
요거는 카드팩만을 갖고있는 BlackjackGame이 하는 역할이 맞나? 라는 생각이 드는데요ㅎㅎ. participant 에서 처리해주는게 어떤가요?

그렇게 하다보니, participant에서 할 수 있는 일을 값을 꺼내와서 처리하는 느낌입니다!

2023-03-07 18:30 UTC, joseph415 commented on src/main/java/blackjack/view/OutputView.java
>  import blackjack.domain.user.Players;
도메인 의존관련해서 첫번째 리뷰에 질문드렸습니다. 답변부탁드릴게요

2023-03-07 18:30 UTC, joseph415 commented on src/main/java/blackjack/domain/user/Dealer.java
> +    public GameResult declareGameResult(final int playerScore) {
해당 메서드가 여기 있어도 상관은 없다고 생각하는데요ㅎㅎ. 
GameResult에서 게임결과를 판단해서 자기자신을 생성하도록 해도 좋을것 같다는 생각이 들어서 의견남깁니다~ 한번 생각해보시고 괜찮은 방법으로 진행해주세요~!

2023-03-08 07:26 UTC, Choi-JJunho commented on src/main/java/blackjack/domain/user/Dealer.java
> +    public GameResult declareGameResult(final int playerScore) {
딜러의 입장에서 보는 승패와, 플레이어의 입장에서 보는 승패의 기준이 다르다는 부분에서 다음과 같이 생각했습니다.

1. GameResult에 결과를 판단하여 생성하는 경우

- 인자로 딜러와 플레이어를 받는 경우 객체간 강한 의존성이 존재하는 코드가 작성 될 수 있다.
``` java
// GameResult.java 중
public static GameResult of(Dealer dealer, Player player) {
    ...
}
```
위 경우 코드는 깔끔해지나 GameResult, Player, Dealer간 강한 의존성이 생기는 부분을 경계하게 되어 섣불리 적용하기 어려운 부분이 있습니다.

- 인자로 정수만 받는 경우 순서를 타입으로 강제하지 않아 순서를 혼동할 수 있다.
``` java
public static GameResult of(int dealerScore, int playerScore) {
    ...
}
```

해당 메소드를 사용하는 부분에서 인자 순서를 잘못 사용할 경우 예측하지 못한 결과값을 반환받을 가능성이 있다고 생각하여 적용하지 않았습니다.

때문에 딜러가 판단하여 GameResult를 생성하는 경우를 채택하게 되었습니다.

2023-03-08 07:35 UTC, Choi-JJunho commented on src/main/java/blackjack/view/OutputView.java
> +import blackjack.domain.card.Card;
앗! 조합에 너무 심취한 나머지 답변드리는것을 깜빡 잊었네요 ㅠㅠ

> View와 Domain의 의존이 발생했는데, 혹시 View와 Domain이 의존이 생겼을 때 생기는 문제에 대해서 알고계실까요?

뷰가 도메인을 의존한다면 도메인의 비즈니스로직을 침범할 수 있는 상황이 올 수 있을 것 같습니다.
이 때문에 도메인을 잘못 호출할 경우 다른 레이어에서 사용중인 도메인까지 영향을 미칠 수 있기 때문에 지양해야한다고 이해했습니다.

DTO를 이용하여 도메인과 다른 레이어간의 의존도 혹은 결합도를 약하게 만들어 줌으로써 이를 해결할 수 있을 것 같습니다.

2023-03-08 07:56 UTC, Choi-JJunho commented
서브웨이 🥪 안녕하세요
구조가 자꾸 변경되는 바람에 커밋을 또 다시 한뭉텅이로 뭉쳐버렸네요 ㅠㅠ
크게 변경된 사항은 다음과 같습니다.

# 변경사항

- 플레이어에게 getResult 기능 추가
- 기존 isEnd의 역할을 Dealer에게 위임
- 점수를 표현하는 Score 객체 추가
- Controller레이어에서 View레이어로 정보를 전달할 때 의존관계를 약하게 만들어주기 위해 DTO 사용
- 코드 포맷팅

2023-03-08 17:55 UTC, joseph415 commented on src/main/java/blackjack/view/OutputView.java
>  import blackjack.domain.user.Players;
> 뷰가 도메인을 의존한다면 도메인의 비즈니스로직을 침범할 수 있는 상황이 올 수 있을 것 같습니다.

비지니스 로직은 도메인 비지니스를 풀어내기위한 로직인데요. **로직을 침범한다는 말보단, 도메인영역 자체를 침범해버린다가 쫌 더 맞는것 같습니다.**

> 도메인을 잘못 호출하면 도메인을 사용하는 모든 레이어에 영향을 미친다.

해당 답변이 `View == Console` 이라는 가정이 들어가서 View에서 도메인을 잘못 `호출`한다. 라는 답변이 나온 것 같은데요. 요것도 맞는 말이긴 하지만, 더 정확히 집고 넘어가 볼게요ㅎ

**우선 View를 콘솔말고도 사용자 측면 이라는 개념으로 생각해볼게요!(console 이에외도 웹, 앱 등이 될 수 있음).** 
View는 아주 많이 변경되는 레이어입니다. View가 Domain을 의존하게 되면 도메인이 그 변경에 대한 영향을 그대로 받게 됩니다. 따라서 **해당 영향때문에 비지니스 요구사항에 대해 유연하게 대응하지 못해서 의존을 끊어주는것입니다.** 

저희가 과제로 계속 연습하고 있는 객체에 책임을 부여해 메시지를 던저서 해결하는 모든 과정들의 주된 목표는 비지니스 변경사항에 유연하게 대응하기 위함입니다. 그걸 이루지 못하게 한다는 것으로 생각하시면 될 것 같습니다~

여기서 View의 변경과 도메인이 받는 영향이라는 것은 무엇일까요?

만약에 클라이언트에 Domain이 그대로 나가버렸을 때, 하위호환성을 지켜야 하기 때문에 외부로 나간 도메인들은 변경이 영원히 불가능할 수 있습니다. 그런데 비지니스 요구사항은 계속 추가되고 변경되는데, 앞선 이유때문에 변경사항에 대응하는데 큰 제약이 생깁니다. 그래서 dto를 쓰던가, 다른 값을 클라이언트 측면으로 보내서 의존을 끊어버리는것입니다.

> DTO를 이용하여 도메인과 다른 레이어간의 의존도 혹은 결합도를 약하게 만들어 줌으로써 이를 해결할 수 있을 것 같습니다.

네, dto가 아니더라도 그냥 player이름을 보내주던가 or String 값으로 풀어서 보내줘서 그 의존을 해결 할 수 있을 것 같습니다.

--- 

제 답변이 실무경험의 의한 답변이긴 하지만, 왜 MVC가 생겨나고 레이어간의 의존방향을 중요시하고 하는 것인지 한번 생각해보시는 것도 좋을 것 같아요!

View에 도메인이 나가는 것을 없애고는 싶지만, View=console 이라고 생각한다면 큰 문제는 아니라서 따로 변경요청은 드리지 않겠습니다!

답변이 길어져서 이해안가는 부분있으시면 말씀주세요(_ _)

2023-03-08 18:33 UTC, joseph415 approved these changes
안녕하세요 주노.

리뷰 빠르게 잘 적용해주셨네요ㅎㅎ 1단계는 이만 merge하곘습니다💯 
2단계 진행해주세요~!

추가로 도메인과 View 의존에 대한 리뷰관련해서 답변 달았습니다 확인 부탁드려요!

2023-03-08 18:33 UTC, joseph415 commented on src/main/java/blackjack/dto/DealerDto.java
> +import blackjack.domain.user.Score;
이렇게 View로 나가면 결국 도메인이 View로 노출되는것은 같은 상황인것 같네요ㅎㅎ

2023-03-08 18:34 UTC, merged

2023-03-09 11:58 UTC, joseph415 commented on src/main/java/blackjack/view/OutputView.java
>  import blackjack.domain.user.Players;
간단한 예시도 남기겠습니다.

1. 만약에 제가 api 개발자여서 외부에 api 버전 1.0.0 으로 배포를 했는데 처음부터 대박이 나서 1000명의 사용자들이 생겼다고 가정해볼게요.

비지니스 요구사항이 크게 변경되어서 대응을 하기위해 수정해야하는 상황이 생기는데, 도메인이 그대로 외부로 노출돼서 해당 도메인을 변경하면, 1000명의 사용자 모두 영향을 받게 됩니다. 하위호환성을 지켜야합니다. 그래서 변경에 유연하게 대응하지 못합니다.

2. 서로 의존을 하고있어서 도메인을 변경하기가 쉽지 않습니다. 도메인의 변경이 View로 그대로 이어질수 있습니다.

핵심은 이로인해 비지니스 요구사항에 쉽사리 대응하지 못한다는 것입니다!