[1단계 - 블랙잭 게임 실행] 베로(김은솔) 미션 제출합니다.
woowacourse/java-blackjack pull request #435
Opened 2023-03-03 08:18 UTC by Cyma-s

안녕하세요, 다니! 🙌  베로입니다!

이번 블랙잭 게임은 구현할 것, 고민할 것이 많아서 시간이 촉박했네요 😭
시간에 쫓겨 구현하다보니 리팩토링이 덜 된 부분도 있습니다. 양해를 구합니다 🙇‍♀️

미션하면서 궁금했던 부분은 코멘트로 남겨두었습니다!
리뷰 감사합니다 😄

2023-03-03 08:25 UTC, Cyma-s commented on src/main/java/blackjack/domain/BlackJackManager.java
> +public class BlackJackManager {
BlackJackManager는 역할로 보았을 때 서비스와 컨트롤러의 역할이 혼합된 클래스라고 생각합니다!
그러나 사용하는 것들이 protected 메서드라 컨트롤러 패키지로 따로 분리하지는 못했습니다.

현재 도메인인 Participant의 메서드의 접근 제한자는 도메인 내부에서만 사용되어야 한다고 생각해서 protected로 유지하려는 생각입니다. 그렇지만 BlackJackManager는 도메인에 어울리지 않는다고 생각할 때, 어떤 방식이 가장 효율적일까요?

1. BlackJackManager를 controller 패키지로 분리한다.
2. Participant의 protected 메서드를 Public으로 변경한다.

2023-03-05 07:19 UTC, da-nyee requested changes
안녕하세요 베로! 다니입니다 🙌

어려운 블랙잭 게임 구현하시느라 수고 많으셨습니다!
꼼꼼한 테스트가 인상적이네요 👍👍👍

코드리뷰 확인하고 반영 후에 리뷰 재요청해주세요!
질문답변은 별도 코멘트로 남길게요.
추가로 궁금한 점은 언제든지 코멘트/슬랙 DM 주세요 🙇‍♀️

2023-03-05 07:19 UTC, da-nyee commented on src/main/java/blackjack/domain/Dealer.java
> +        if (dealerPoint > 21 || dealerPoint < participantPoint) {
요런 조건도 메서드 분리하면 좋을 것 같아요 ㅎㅎ

2023-03-05 07:19 UTC, da-nyee commented on src/main/java/blackjack/view/InputView.java
> +    public static final String ADDITIONAL_HIT_APPROVE = "y";
요기는 public으로 선언한 이유가 있을까요?

2023-03-05 07:19 UTC, da-nyee commented on src/main/java/blackjack/view/OutputView.java
> +    public static void printParticipantsInitCards(final Dealer dealer, final List<Player> players) {
아키텍처 관점에서 View가 Domain(Model)을 알고 있으면, 어떤 문제가 발생할 수 있을까요?

2023-03-05 07:19 UTC, da-nyee commented on src/main/java/blackjack/view/OutputView.java
> +    private static String createBlackJackResult(BlackJackResults blackJackResults) {
요런 로직은 domain에서 처리할 수 있지 않을까요?

2023-03-05 07:19 UTC, da-nyee commented on src/main/java/blackjack/view/OutputView.java
> +                .filter(entry -> entry.getValue() != 0)
`0`은 무엇을 의미할까요?

2023-03-05 07:19 UTC, da-nyee commented on src/main/java/blackjack/view/OutputView.java
> +                    stringBuilder.append(resultTypeCount).append(resultType).append(" ");
어떤 로직인지 한 눈에 안 들어오는데, 메서드 분리하는 건 어떨까요?

2023-03-05 07:19 UTC, da-nyee commented on src/test/java/blackjack/domain/CardNumberTest.java
> +    @MethodSource("getMaxValueNear21Dummy")
👍

2023-03-05 07:19 UTC, da-nyee commented on src/test/java/blackjack/domain/DealerTest.java
> +class DealerTest {
꼼꼼한 테스트 👍👍

2023-03-05 07:35 UTC, da-nyee commented
> 실제 블랙잭 게임과 얼마나 똑같아야 할까요? 요구 사항에는 나와있지 않지만 기존 블랙잭 게임을 조사하면서 알게 된 규칙들도 구현했는데, 이런 방향의 구현 방식이 맞는 것인지 궁금합니다.

요구사항 +a를 하셨군요 👍👍
실제 업무였다면 기획서에 없는 내용이기 때문에 문제가 될 수도 있지만, 우테코 미션에서는 학습 측면에서 좋다고 생각해요 ㅎㅎ
물론 주어진 요구사항은 전부 지켰다는 전제 하예요.

<br/>

> 현실 세계와 비슷한 책임을 갖는 구현이 좋을지, 객체지향적으로 생각했을 때 책임이 적절하게 분배된 구현이 좋을지 궁금합니다. 이번 미션에서 구현할 부분이 현실 세계와 다른 구현들이 있어 그 부분을 설계할 때 어려웠습니다. 다니는 어떤 경우에 현실 세계와 비슷한 책임을 갖고, 어떤 경우에는 객체지향적으로 책임을 나누시나요?

처음에는 현실 세계와 비슷하게 책임을 분배하다가, 한 객체가 너무 많은 책임을 가지고 있다는 생각이 들면 객체지향적으로 객체를 잘게 쪼개고 책임을 분리하는 것 같아요.
절대적인 기준은 없고.. 개발하면서 그때그때 고려해요.

2023-03-05 07:51 UTC, Cyma-s commented on src/main/java/blackjack/domain/ParticipantCards.java
> +    private void validate(final List<Card> cards) {
private과 public 메서드의 순서에 대해서 페어와 의논을 했었습니다.
저는 메서드의 사용 순서에 따라 메서드를 정렬하자는 입장이었습니다. public 메서드에서 사용되는 순서대로 private 메서드를 정렬하는 방향이었어요.
페어는 외부에 노출되는 public 메서드가 가장 위에 노출되어야 한다고 생각하고, private은 public 메서드의 로직이 궁금할 때만 찾아보면 된다는 입장이었습니다!

저는 페어의 의견에 설득되어 public 메서드를 모두 위 쪽으로 올리는 선택을 했는데, 다니는 이 방법에 대해 어떻게 생각하시나요? 🤔

2023-03-05 08:10 UTC, Cyma-s commented on src/main/java/blackjack/Application.java
> +        blackJackManager.run();
출력이 누락되었네요 😅
수정했습니다!

2023-03-05 08:11 UTC, Cyma-s commented on src/main/java/blackjack/domain/CardNumber.java
> +    public static final int ACE_CONVERT_NUMBER = 10;
상수를 자동으로 추출하는 과정에서 public으로 설정된 것 같습니다 🥺
접근 제어자를 private으로 수정했습니다!

2023-03-05 08:17 UTC, Cyma-s commented on src/main/java/blackjack/domain/Dealer.java
> +        if (participantPoint > 21) {
버스트 되지 않은 점수 중 가장 큰 값입니다!
매직 넘버를 상수로 추출했습니다 👍

2023-03-05 08:19 UTC, Cyma-s commented on src/main/java/blackjack/view/InputView.java
> +    public static final String ADDITIONAL_HIT_APPROVE = "y";
이 부분도 상수 추출 되면서 public으로 실행 된 것 같네요.. 😥
private으로 변경했습니다 🙂

2023-03-05 08:28 UTC, Cyma-s commented on src/main/java/blackjack/view/OutputView.java
> +                .filter(entry -> entry.getValue() != 0)
승, 패, 무승부를 ResultType으로 저장합니다!
각 ResultType이 0인 경우는 해당 경기 결과가 존재하지 않는 경우이므로 출력할 때 0이 아닌 값을 가져오는 로직입니다 🙂

가독성을 위해 매직 넘버를 상수로 리팩토링했습니다! 👍

2023-03-06 05:43 UTC, Songusika commented on README.md
> +## 요구사항
각 도메인 요구사항이 섞여있어서 보기 쪼오오끄음 힘든거 같아요! 도메인별로 분류해보시는건 어떨까요?? 🙋‍♂️

2023-03-06 05:50 UTC, Songusika commented on src/main/java/blackjack/domain/BlackJackManager.java
> +        List<Player> players = createPlayers();
읽는 순서대로 메서드가 위치했으면 좋겠습니다😊

2023-03-06 05:53 UTC, Songusika commented on src/main/java/blackjack/domain/BlackJackManager.java
> +        return new ParticipantCards(List.of(deck.draw(), deck.draw()));
추후 요구사항이 변경되어서 2번 이상 뽑으라고 할 경우에는 어떡하죠...?!

2023-03-06 05:58 UTC, Songusika commented on src/main/java/blackjack/domain/CardNumber.java
> +        return IntStream.range(0, aceCount)
성능을 고려하신 `IntStream` 활용 좋습니다 👍

2023-03-06 06:06 UTC, Songusika commented on src/main/java/blackjack/domain/Participant.java
> +    public List<Card> open(final int cardCount) {
`cardCount` 인자로 List<Card> 의 길이보다 더 큰 값이 들어오면 어떻게 될까요>

2023-03-06 06:15 UTC, Songusika commented on src/main/java/blackjack/view/OutputView.java
> +        stringBuilder.append(System.lineSeparator());
`System.lineSeparator()` 활용 굿 👍

2023-03-06 06:19 UTC, Songusika commented on src/test/java/blackjack/domain/NameTest.java
> +    @EmptySource
`@EmptySource` 어노테이션 활용 굿 👍

2023-03-06 15:10 UTC, Cyma-s commented on src/main/java/blackjack/domain/BlackJackResult.java
> +    private final List<ResultType> results;
다시 보니 네이밍이 적절하지 않네요 🤔
`BlackJackResult`를 `MatchResults`로 네이밍을 변경했습니다!

2023-03-07 15:30 UTC, Cyma-s commented on src/main/java/blackjack/domain/Deck.java
> +    public Deck() {
Card 클래스에 Suit와 CardNumber로 Card를 미리 만들어 두었습니다!
Card 객체를 생성하지 못하도록 생성자를 private으로 변경하는 대신 정적 팩토리 메서드로 생성된 Card를 찾을 수 있도록 했습니다 😊
팩토리 메서드가 Card를 찾는 시간을 줄이기 위해 캐싱된 Card는 Map으로 구현했습니다.

2023-03-07 15:32 UTC, Cyma-s commented on src/main/java/blackjack/domain/BlackJackManager.java
> +public class BlackJackManager {
view와 연결되는 부분은 BlackJackController라는 컨트롤러로 옮겨서 책임 분리를 수행했습니다 👍

BlackJackManager는 함수형 인터페이스를 넘겨 받아 값을 입력 받거나 출력하게 됩니다. Player가 hit할 때 입력 로직이 필요해서 hit 여부를 판단하는 함수형 인터페이스를 컨트롤러에서 BlackJackManager로 넘겨주었습니다.

2023-03-08 04:43 UTC, Cyma-s commented on src/main/java/blackjack/view/OutputView.java
> +    private static String createBlackJackResult(BlackJackResults blackJackResults) {
DTO에서 로직을 처리하고 view로 넘겨주도록 처리했습니다 👍

2023-03-09 16:26 UTC, da-nyee commented on src/main/java/blackjack/Application.java
> +        blackJackController.showGameResult();
Controller에서 하나의 메서드로 묶을 수 있지 않을까요?

2023-03-09 16:26 UTC, da-nyee commented on src/main/java/blackjack/domain/ParticipantCards.java
> +    private void validate(final List<Card> cards) {
저는 베로의 방식처럼 사용해요!
public 메서드 - public 메서드에서 사용하는 private 메서드 순으로 정렬했을 때, 코드 흐름이 자연스럽고 더 잘 읽히는 것 같아요.
다른 클래스에서 어떤 클래스의 public 메서드를 사용하고, 이를 확인할 때는 보통 IDE로 코드를 타고 들어가기 때문에 public 메서드의 순서는 크게 신경쓰지 않습니당

2023-03-09 16:33 UTC, da-nyee commented on src/main/java/blackjack/domain/ParticipantCards.java
> +    private void validate(final List<Card> cards) {
저는 베로의 방식처럼 사용해요!
public 메서드 - public 메서드에서 사용하는 private 메서드 순으로 정렬했을 때, 코드 흐름이 자연스럽고 더 잘 읽히는 것 같아요.
어떤 클래스에서 사용 중인 public 메서드의 구현을 확인할 때는 보통 IDE로 코드를 타고 들어가기 때문에 public 메서드의 순서는 크게 신경쓰지 않아요.

2023-03-09 16:33 UTC, da-nyee commented on src/main/java/blackjack/domain/ParticipantCards.java
> +    private void validate(final List<Card> cards) {
저는 베로의 방식처럼 사용해요!
public 메서드 - public 메서드에서 사용하는 private 메서드 순으로 정렬했을 때, 코드 흐름이 자연스럽고 더 잘 읽히는 것 같아요.
어떤 클래스에서 사용 중인 public 메서드의 구현을 확인할 땐, 보통 IDE로 코드를 타고 들어가기 때문에 public 메서드의 순서는 크게 신경쓰지 않아요.

2023-03-09 16:36 UTC, da-nyee commented on src/main/java/blackjack/domain/BlackJackResults.java
> +        for (int index = 0; index < dealerResults.size(); index++) {
앗 제가 졸릴 때 코멘트 남겼나봐요..
여기는 메서드 분리를 할 수가 없네요 ㅜ

2023-03-09 17:09 UTC, da-nyee approved these changes
베로~~ 다니입니다 🙌

처음에도 좋았지만, 리팩토링 후에 코드가 더 좋아졌네요 👍👍👍

1단계는 이 정도면 충분한 것 같아서 어프루브 & 머지할게요!
추가 코멘트 몇 개 남겼는데, 한번 확인하고 2단계 진행해주세요 ㅎㅎ

다음 단계에서 만나요 ~~!

2023-03-09 17:09 UTC, da-nyee commented on src/main/java/blackjack/dto/BlackJackGameResultDTO.java
> +    public static BlackJackGameResultDTO of(final BlackJackResults blackJackResults) {
[정적 팩토리 메서드 네이밍 방식](https://velog.io/@saint6839/%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C-%EB%84%A4%EC%9D%B4%EB%B0%8D-%EB%B0%A9%EC%8B%9D) 참고해주세요 ㅎㅎ

2023-03-09 17:10 UTC, merged

2023-03-10 08:02 UTC, Cyma-s commented on src/main/java/blackjack/domain/ParticipantCards.java
> +    private void validate(final List<Card> cards) {
그렇다면 읽는 순서대로 바꿔보도록 하겠습니다 :)

2023-03-11 14:12 UTC, Cyma-s commented on src/main/java/blackjack/view/OutputView.java
> +    public static void printParticipantsInitCards(final Dealer dealer, final List<Player> players) {
제가 코멘트 남기는 것을 깜빡했네요... 🥺
view가 model을 알고 있다면 model의 변화에 따라 바뀌는 부분이 view까지 전파될 것 같습니다.
만약 view가 model 객체에 접근할 수 있게 된다면 출력에는 관련 없는 도메인 로직까지 알게 되어 버리기 때문에 불필요하다고 생각합니다.

따라서 1단계 미션 리팩토링 단계에서 도메인 객체 대신 DTO를 전달하는 것으로 변경했습니다 👍

2023-03-11 14:14 UTC, Cyma-s commented on src/main/java/blackjack/dto/BlackJackGameResultDTO.java
> +    public static BlackJackGameResultDTO of(final BlackJackResults blackJackResults) {
from 으로 변경했습니다! 👍

2023-03-11 14:16 UTC, Cyma-s commented on src/main/java/blackjack/Application.java
> +        blackJackController.showGameResult();
코멘트를 보고 생각해봤는데, 저도 하나의 메서드로 묶는 것이 좋은 것 같습니다!
컨트롤러가 세세하게 어떤 역할을 하는지 Application에서 아는 것보다 세부적인 메서드 진행은 컨트롤러에서 하는 게 맞는 것 같네요 👍
또한 외부로 노출되는 public 메서드를 줄일 수 있어 좋아 보입니다 🤔

2023-03-11 14:30 UTC, Cyma-s commented on src/main/java/blackjack/domain/BlackJackManager.java
> +        while (player.isHittable() && checkPlayerHit.test(player.getName().getValue())) {
해당 부분이 너무 많은 정보를 갖고 있긴 하네요... 다만 디미터의 법칙을 지키려고 하니 걸리는 점이 있습니다 🤔
checkPlayerHit는 OutputView의 함수를 함수 인터페이스로 넘겨준 것입니다.
저번 리팩토링 때 view와 domain을 분리하기 위해 매개변수로 domain을 넘겨주는 로직을 모두 제거했습니다! 그런데 이번에 디미터 법칙을 지키기 위해 checkPlayerHit에 Name 객체를 넘겨주게 되면 view와 domain이 완전히 분리되지 않은 것처럼 보일 것 같습니다 😥
아니면 view로 Name 객체를 넘기지만 Name 객체의 public 메서드가 getter 만 존재하니 그냥 매개변수로 넘겨도 괜찮을까요? 다니의 의견이 궁금합니다!

조건문 추상화 수준을 높이는 것은 코드를 읽는 사람들의 이해를 돕기 위해 꼭 필요할 것 같아 변경했습니다 😊