[1단계 - 블랙잭 게임 실행] 홍실(홍혁준) 미션 제출합니다.
woowacourse/java-blackjack pull request #439
Opened 2023-03-03 08:21 UTC by hong-sile

안녕하세요! 제이미! 이번 리뷰이인 홍실이에요!

궁금한 부분에 대한 질문은 코드에 직접 코멘트 남겼어요!

이번 미션에서 시간이 많이 모자라서 미쳐 고려하지 못한 부분들이 많습니다.
오늘 밤내로 리팩터링 할 수 있는 내용은 리팩터링하고 코멘트를 남기도록 하겠습니다! 감사합니다.

2023-03-03 18:51 UTC, hong-sile reviewed
안녕하세요 제이미 조금 늦게 코멘트 달아요!!

원래는 걸리는부분 전부를 리팩터링 하려했는데, 그러면 페어 프로그래밍의 의미가 퇴색되는 것 같아 조금 하다 중단하였습니다.
제이미에게 저희가 봐도 개선할 여지가 보이는 코드(Users의 getUser...)를 리뷰 요청 드리는게 죄송하네요...
피드백 이후엔 정말 열심히 만들어 보겠습니다.

이번 코드를 작성하면서 새롭게 시도해본 것들이 좀 있어요.
조금 더 확실한 view와 domain의 분리, abstract class 등 새로 시도하는 만큼 의문점이 많아 질문 남겼습니다.

아 그리고 리뷰해주시는거 정말 감사합니다.

2023-03-03 18:51 UTC, hong-sile commented on src/main/java/blackjack/view/ViewRenderer.java
> +
딜러의 승패 결과 값과 플레이어의 승패 결과 값의 형태가 달랐기 때문에,
어떤식으로 구현할지 페어와 고민을 좀 해보았습니다.

플레이어들의 결과값들로 딜러의 승패 수를 구할 수 있다고 생각하였고, 이를 Collectors.groupingBy와 Collectors.counting()으로 구현하였습니다.

하지만 이러한 연산 부분이 ViewRenderer에 있는 것이 옳지 않다고 생각하여 추후 BlackJackGame에서 딜러의 승패 결과값을 반환하는 로직으로 리팩터링 진행할 것 같습니다.

2023-03-03 18:51 UTC, hong-sile commented on src/main/java/blackjack/domain/User.java
> +
이번 미션의 주요 요구사항 중 하나였던, 플레이어와 딜러의 중복로직 제거를 위해 abstract class를 이용하였습니다.

abstract class를 이용한 이유는 다음과 같습니다.
1. 중복로직을 abstract class에서 정의하여, 중복을 제거할 수 있다.
2. interface와 달리 abstract class는 filed를 가질 수 있기에, 딜러와 플레이어가 갖는 상태 또한 중복 제거 가능하다.
3. abstract method로 딜러와 플레이어의 차이를 추상화 할 수 있다.(차이점을 추상메서드화)

그리고, 혹여, 상속받은 객체에서 User의 메서드를 오버라이드할 수 있으니 final 키워드로 상속을 못하게 막았습니다.

2023-03-03 18:51 UTC, hong-sile commented on src/main/java/blackjack/domain/User.java
> +        this.name = new Name(name);
추가적으로, User의 Test에 관해서 페어와 고민을 해보았습니다.
abstract class같은 경우에는, 객체를 만들지 못하기에, 내부의 메서드를 실행할 수 없었습니다.

저희는 이 로직들의 유효성을 검증하고자, User의 하위 클래스인 Dealer와 Player에서 해당 메서드의 테스트를 동시 진행했는데요.

이런 식으로, 상속받은 클래스에서 단위 테스트를 전부 구현하는게 맞을까요?
아니면, UserTest 클래스를 만들고, 아무 User를 상속받는 아무 자식 클래스의 객체를 넣은 다음에, 해당 메서드들을 테스트하는게 맞을까요?

먼저 코드를 다시 돌아보니 리팩토링을 할 때, UserTest를 만들어서 각각의 메서드를 테스트 할 것 같습니다.
1. 저희 User의 메서드의 경우에, 모두 상속이 불가능하고, abstract class의 filed만 사용한다.
2. abstract method의 반환값을 이용하는 메서드가 없기에, User class에서 구현한 메서드들이 상속을 받는다해서 영향을 받을 요소가 없다.

위와 같은 이유로 UserTest를 추후에 만들 것 같습니다.(abstract method는 자식 객체에서 테스트)

> UserTest 클래스를 만들고, 아무 User를 상속받는 아무 자식 클래스의 객체를 넣은 다음에, 해당 메서드들을 테스트하는게 맞을까요?

위 방식처럼 구현했을 때 제가 생각하지 못한 문제점이 있을까요? 아니면 UserTest를 만들더라도 더 개선할 여지가 있을까요?

2023-03-05 08:51 UTC, jamie9504 requested changes
홍실, 안녕하세요. 리뷰어 제이미입니다 😄 

피드백과 코멘트를 조금 남겨두었습니다.

남은 주말 즐겁게 보내세요 !

2023-03-05 08:51 UTC, jamie9504 commented on README.md
> +#### domain
게임을 딜러 혼자서도 진행할 수 있네요.

<img width="420" alt="image" src="https://user-images.githubusercontent.com/59511689/222935115-0f081ec0-76a1-4a2f-bcf6-e345459f33d7.png">

2023-03-05 08:51 UTC, jamie9504 commented on README.md
> +  - [x] Ace는 1또는 11로 가진다
```suggestion
  - [x] Ace는 1또는 11을 숫자로 가진다
```

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/Application.java
> +        backJackController.run();
오타로 보이네요!

```suggestion
        BlackJackController backJackController = new BlackJackController();
        blackJackController.run();
```

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/controller/BackJackController.java
> +        final List<String> names = inputView.readPlayerNames();
`playNames`, `playName`, `names` 같은 의미를 사용하는 용어가 세 개나 되니 하나로 통일하는 것도 좋겠죠?

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/controller/BackJackController.java
> +        outputView.printLineBreak();
outputView가 consoleView가 아닌 다른 view로 바뀐다면, 그때도 controller에서 lineBreak를 출력해줘야 할까요?

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/controller/BackJackController.java
> +        return new BlackJackGame(names, new RandomDeckGenerator());
예외 발생시, 사용자에게 StackTrace를 노출하는 것은 좋지 않은 것 같아요.
이 부분 개선해볼까요?

<img width="886" alt="image" src="https://user-images.githubusercontent.com/59511689/222935148-a87e2528-88d7-4c66-8440-307187ce0ff6.png">
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/59511689/222935193-6be9eec4-c6cd-480b-9d58-8acfc9565468.png">

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/controller/BackJackController.java
> +        outputView.printInitialStatus(ViewRenderer.renderStatus(blackJackGame.getInitialStatus()));
괄호가 여러개 중첩되면, 읽는 방향이 좌->우가 아닌 괄호 가장 안 -> 밖으로 바뀌어야 해서
가독성을 해칠 수 있다고 생각해요.
이런 부분들을 개선해볼 수 있을까요?

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/controller/BackJackController.java
> +    private void playPlayerTurn(final BlackJackGame blackJackGame) {
player가 여러명이 될 수 있으니 players로 짓는 게 더 직관적이겠죠?

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/controller/BackJackController.java
> +    private void playFor(final BlackJackGame blackJackGame, final String name) {
for이라는 전치사는 메서드명에 잘 사용하지 않는 것 같아요!

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/controller/BackJackController.java
> +            List<Card> userCards = blackJackGame.getStatus().get(name);
디미터의 법칙에 대해 공부해보는 것도 좋겠네요!

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/controller/BackJackController.java
> +        int dealerDrawCount = blackJackGame.playDealerTurn();
`void playDealerTurn`
`int playDealerTurn`

같은 이름의 메서드명이 어떤 메서드는 반환값이 있고 어떤 메서드는 반환값이 없네요.
이렇게 되면 프로그램을 이해하기에 조금 더 공수가 많이 들 것 같아요.

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/controller/BackJackController.java
> +            final CardResult cardDto = cardResult.get(name);
CardResult의 변수명이 cardDto인 이유가 따로 있을까요?

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/controller/BackJackController.java
> +        outputView.printLineBreak();
아래 순서대로 정렬되는 것은 의도된 부분인가요?
요구사항에서 보여진 출력과는 다른 정렬인 것 같아서요~

<img width="416" alt="image" src="https://user-images.githubusercontent.com/59511689/222935263-76e393a8-07d9-4378-871f-df804da3c6b8.png">

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/controller/DrawInput.java
> +public enum DrawInput {
이 Enum의 패키지의 위치가 controller가 맞을까요?

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/domain/BlackJackGame.java
> +    public Map<String, CardResult> getCardResult() {
cardResult는 뭔가 CardResult 객체만 리턴해야할 것 같은데요.
이 Map 객체에 적절한 이름을 붙여주거나, 일급컬렉션으로 포장해보는 건 어떨까요?

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/domain/BlackJackRule.java
> +    public static int getScore(final User user) {
해당 클래스의 메서드들은 결국 요 메서드에 모두 의존을 하고 있는데요.
user를 받아서 score를 만들어주고 있는데, (int로 반환)
이 score도 원시값 포장이 가능하지 않을까요? 그렇게되면 책임을 이동시켜서 유틸성 클래스가 필요하지 않을 수도 있겠네요.

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/domain/Card.java
> +    private final CardNumber number;
위는 cardShape로 아래는 number로 선언한 이유가 궁금하네요.

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/domain/CardGroup.java
> +                .sum();
취향마다 차이가 있겠지만, 전반적으로 `.` 마다 개행을 해주는 것은 어떨까요?
(추후에 해당 라인을 삭제할 때도 용이합니다)

```suggestion
        return cards.stream()
                .map(Card::getNumber)
                .mapToInt(CardNumber::getValue)
                .sum();
```

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/domain/CardGroup.java
> +                .filter(card -> card.getNumber() == CardNumber.ACE)
card에게 number를 요청해서, ACE와 비교하지 않고 card에게 ACE인지 물어보는 건 어떨까요?

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/domain/DeckGenerator.java
> +public interface DeckGenerator {
👍

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/domain/User.java
> +        this.name = new Name(name);
👏👏👏👏👏 말씀주신대로 User에서만 정의가 가능하고 하위 구현이 불가능하게 막혀있는 경우 User를 구현한 테스트 객체로 테스트를 한 번만 해도 무관하고, 하위 객체에서 재구현한 경우엔 하위 객체에서 테스트를 하면 될 것 같습니다 😄 

TDD로 진행한다고 하면, User abstract class를 추출하면서 하위 객체에서 재구현할 수 없게 막아놓도록 변경하는 시점 쯤에 테스트가 변경되었겠네요!

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/domain/Users.java
> +    private static final String NOT_CONTAIN_DEALER = "Users에 Dealer 객체가 없습니다.";
예외 메시지로 사용할 상수는 접미사로 `_MESSAGE`를 붙여주는 건 어떨까요?

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/domain/Users.java
> +        this.users = List.copyOf(users);
users는 `List<User> users`를 복사해서 넘겨주는군요!
copyOf를 쓴 이유는 무엇인가요? User객체는 불변인가요?

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/domain/Users.java
> +    }
딜러와 플레이어를 구분하는 로직들이 많은데,
이렇게 되면 Users에서 이들을 하나로 묶는게 옳은 방향인지 고민해볼 필요가 있겠네요 😄

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/view/InputView.java
> +    private static final String DELIMITER = "\\s*,\\s*";
구분자라기보단 구분용 정규표현식같네요! (상수명)

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/view/InputView.java
> +
이유가 있는 개행일까요?

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/view/InputView.java
> +        final String nameInput = SCANNER.nextLine();
소소한 취향 차이일 수 있지만 `inputName`이 조금 더 잘 읽히는 느낌이 있네요!

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/view/InputView.java
> +    }
사실상 readLine만 하는 로직인데요.
메서드명을 `readDrawOrStay`로 지어주면 어떤 이점이 있을까요?

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/view/OutputView.java
> +    private static final String DRAW_CARD_REQUEST_MESSAGE = "%s는 한장의 카드를 더 받겠습니까?(예는 y, 아니오는 n)";
이 친구는 왜 접미사로 `_FORMAT`이 붙지 않았을까요? 일관성을 유지해주세요!

---

사용자 입장에서 은(는)을 지원하면 더 읽기 좋겠죠?
<img width="365" alt="image" src="https://user-images.githubusercontent.com/59511689/222935416-3f2f63b7-06e6-4a86-8be3-5a2adef9442e.png">

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/view/OutputView.java
> +    private static final String DELIMITER = ", ";
구분자도 위의 `_MESSAGE`나 `_FORMAT`처럼 어떤 구분자인지 명시되면 좋을 것 같네요!

2023-03-05 08:51 UTC, jamie9504 commented on src/main/java/blackjack/view/OutputView.java
> +        printLineBreak();
개행을 해야 하면 FORMAT에 개행문자를 포함하는 것도 좋겠네요.

[공통] 개행 관련해서는 아래 항목들을 알아보면 좋을 것 같아요~
System.lineSeparator()
System.getProperty("line.separator")
String#format() - %n

2023-03-05 08:51 UTC, jamie9504 commented on src/test/java/blackjack/controller/DrawInputTest.java
> +    @DisplayName("y또는 n이외의 값을 입력시 예외처리하는지 테스트")
실패 케이스가 있다면 성공 케이스도 있어야 좋다고 생각합니다 😄

2023-03-05 08:51 UTC, jamie9504 commented on src/test/java/blackjack/domain/DealerTest.java
> +            assertThat(dealer.comparePlayer(player)).isEqualTo(WinningStatus.WIN);
딜러가 플레이어랑 비교하는 메서드인데, 플레이어의 승리를 반환하는 것을 예측할 수 있을까요?

`WinningStatus.WIN`을 보았을 때, 딜러의 결과라고 오인하기 쉬울 것 같아보여요.

2023-03-05 08:51 UTC, jamie9504 commented on src/test/java/blackjack/domain/NameTest.java
> +                .hasMessage(Name.BLANK_NAME_EXCEPTION_MESSAGE);
이름으로 `null`을 입력하는 건 괜찮을까요?

2023-03-05 08:51 UTC, jamie9504 commented on src/test/java/blackjack/domain/TestDeckGenerator.java
> +public class TestDeckGenerator implements DeckGenerator {
Test용 제너레이터지만, 덱을 생성할 때 카드들을 받아서 셔플하지 않고 생성한 그대로 들고 있는 방식이란게 클래스명에 드러나면 좋을 것 같아요.

2023-03-06 05:00 UTC, hong-sile commented on src/main/java/blackjack/Application.java
> +        backJackController.run();
앗 이런 오타를... 🥲

2023-03-06 05:11 UTC, hong-sile commented on src/main/java/blackjack/controller/BackJackController.java
> +            final CardResult cardDto = cardResult.get(name);
처음에 CardResult의 클래스 네이밍이 CardDto였다가 나중에 네이밍을 변경해서 남아있는 것 같습니다.

수정할게요!!

2023-03-06 12:58 UTC, hong-sile commented on src/main/java/blackjack/domain/Users.java
> +    }
Dealer와 Player를 분리하여 저장하고 싶긴 하나, Deck도 저장해야 하기에, 필드변수를 3개 이하로 유지하라는 요구사항을 지키지 못합니다. ㅠㅠ

service를 없애고, controller의 run메서드에서 필드변수로 가져서 관리할지 고민중입니다.

2023-03-06 13:06 UTC, hong-sile commented on src/main/java/blackjack/domain/Users.java
> +        this.users = List.copyOf(users);
저는 users가 불변형태로 저장되길 원했습니다. 처음 초기화를 한 뒤에 user를 추가하거나 삭제할 수 없게요.

그래서 playerNames와 딜러를 추가한 리스트를 Copy.of로 불변형태로 복사해서 저장하려고 했습니다.
단순히 playerNames만 있었다면 unmodifialbeList로 collecting해 users에 넣어줬겠지만
dealer라는 객체도 추가해야했기에, 위처럼 구현하였습니다.

2023-03-07 00:55 UTC, hong-sile commented on src/main/java/blackjack/view/InputView.java
> +    }
위처럼 메서드 분리를 하면 
나중에 readDrawOrStay 내부에 변경이 있어도 controller의 코드를 변경하지 않아도 됩니다.

2023-03-07 07:18 UTC, hong-sile commented on README.md
> +#### domain
아, split(delimiter)를 했을 때, delimiter만 연속으로 입력되면 없는 값처럼 사용되는 군요!

split(delimiter, -1)로 해결하였습니다.

2023-03-07 07:48 UTC, hong-sile commented on src/main/java/blackjack/controller/BackJackController.java
> +        final List<String> names = inputView.readPlayerNames();
용어가 혼용되니 착각을 할 수 있군요, 
Player의 이름인 경우 playerName을
User의 이름도 포함된 경우엔, userName으로 변경하였습니다.

2023-03-07 07:49 UTC, hong-sile commented on src/main/java/blackjack/controller/BackJackController.java
> +        outputView.printLineBreak();
lineBreak는 확실히 view의 메서드 내부에서 호출하는게 나을 것 같네요

출력형식이 바뀌면 view뿐 아니라 controller까지 수정해야 하니까요.

2023-03-07 07:50 UTC, hong-sile commented on src/main/java/blackjack/controller/BackJackController.java
> +        return new BlackJackGame(names, new RandomDeckGenerator());
outputView에서 exception을 출력하는 로직을 만들어놓고, try - catch 구문을 잊었군요... 

예외처리하는 로직을 controller에 추가하였습니다.

2023-03-07 07:51 UTC, hong-sile commented on src/main/java/blackjack/controller/BackJackController.java
> +            List<Card> userCards = blackJackGame.getStatus().get(name);
급하게 짜다 보니 get으로 구현한 로직들이 좀 있어요..
바로 객체에 메시지를 보내는 방식으로 리팩터링 하였습니다.

2023-03-07 07:54 UTC, hong-sile commented on src/main/java/blackjack/domain/BlackJackRule.java
> +    public static int getScore(final User user) {
확실히 BlackJackRule이라는 유틸클래스에서 점수와 관련된 메서드들만 있네요.

BlackJackRule에서 점수를 계산하는 것을 Score클래스의 생성자로 만들고,
다른 점수를 이용하는 메서드를 따로 정의하면 더 객체지향적이게 짤 수 있겠요

2023-03-07 07:55 UTC, hong-sile commented on src/main/java/blackjack/domain/Card.java
> +    private final CardNumber number;
아 단순히, 카드를 저희가 읽을 때 모양+숫자로 읽어서 순서를 위와같이 정의했어요

출력할때는 숫자,모양 순이지만, 출력형태는 언제든지 바뀔 수 있기에, 이해하기 더 편한 순으로 배열했습니다.

2023-03-07 07:57 UTC, hong-sile commented on src/main/java/blackjack/domain/CardGroup.java
> +                .filter(card -> card.getNumber() == CardNumber.ACE)
이것도 메시지를 보내보는 것이 좀 더 좋겠네요.(디미터 법칙)

2023-03-07 08:03 UTC, hong-sile commented on src/main/java/blackjack/domain/Dealer.java
> +        return List.of(getStatus().get(0));
확실히 처음 상태라는 네이밍은 이해하기 조금 어려운 것 같네요
firstOpenCardGroup이라는 네이밍으로 변경하였습니다.

2023-03-07 08:05 UTC, hong-sile commented on src/main/java/blackjack/domain/Deck.java
> +    }
유저의 수를 제한을 하여, 위와같은 일이 발생하지 않도록 하였습니다.
빈 Queue에서 poll을 하였을 때 NPE 가능성에 대해 간과했네요. 유의하면서 사용하겠습니다.

2023-03-07 08:23 UTC, hong-sile commented on src/main/java/blackjack/controller/BackJackController.java
> +        int dealerDrawCount = blackJackGame.playDealerTurn();
int를 반환하는 blakcJackGame의 playDealerturn은 현재 몇 번 딜러가 카드를 뽑는지까지 반환하기에,
명령과 조회가 동시에 있는게 마음에 걸리긴 했습니다.

delaer가 카드를 뽑아야하는지에 대한 여부를 반환하는 메서드와, delaer가 카드를 뽑는 메서드로 분리하고,
해당 메서드들로 조건문을 구성하는 방향으로 리팩터링 하였습니다

2023-03-07 23:59 UTC, hong-sile commented on src/test/java/blackjack/domain/TestDeckGenerator.java
> +public class TestDeckGenerator implements DeckGenerator {
음 명시적인게 좋긴한데, 뭔가 이거다! 하는 네이밍이 떠오르진 않네요
TestNonShuffledDeckGenerator로 네이밍을 변경했습니다.

2023-03-08 00:06 UTC, hong-sile commented on src/test/java/blackjack/domain/NameTest.java
> +                .hasMessage(Name.BLANK_NAME_EXCEPTION_MESSAGE);
Name의 생성자에서 파라미터(String name)이 null이면 NPE가 터질 것 같습니다.

하지만, 저는 Name이 null을 받는 상황이 나오지 않을 것 같아서 null을 체크하지 않았습니다.
현재 Name는 InputView에서 넘어온 값들로 생성됩니다.
하지만 현 상태에서 InputView는 콘솔에서 입력을 받고 있는 상황이고, 콘솔에서 입력을 읽을 때 null을 반환하지는 않는 것으로 알고 있습니다.
(buffer를 직접적으로 건들지 않으면 null이 발생하지 않는 것으로 알고 있습니다, 혹시 ctrl+d와 같은 것이 null을 반환할까 확인해보았지만 그 경우 NoSuchElementException이 발생하여 프로그램이 종료되었으니, validateName에 null이 들어가는 경우는 아닌 것 같습니다).

만약에 프로그래머가 new Name(null)와 같은 코드를 작성한다면, 이 경우는 체크하지 못할 것 같긴합니다.
근데, 그런 케이스를 고려한다면? 모든 코드에서 null체크를 해야 할 것 같다는 생각이 듭니다.
굳이 생성자가 아니어도, reference type을 파라미터로 받는 모든 메서드에서 null을 넣을 수 있으니까요.
만약 모든 refernce type을 사용할 때마다 null을 체크한다면 프로그램에 부하가 많이 갈 것 같습니다.

결론적으로 저는 제 코드에서 null이 생성되어 넘어갈만한 요소가 없다고 생각하여 null체크를 하지 않았습니다.
만약 null을 반환할지도 모르는 메서드(ex : 외부 API)를 사용한다면 무조건 체크해야 한다는 것에 대해 동의합니다.
하지만 그렇지 않은 경우에 체크하는 것은 과하다는 느낌이 있습니다.

혹시 현 프로그램에서 NPE가 터질만한 요소가 있을까요? 
null은 항상 조심히 다뤄지는 친구기에, 제가 null이 발생할만한 곳을 찾지 못했나? 싶기도 하네요?

2023-03-08 00:09 UTC, hong-sile commented on src/test/java/blackjack/domain/DealerTest.java
> +            assertThat(dealer.comparePlayer(player)).isEqualTo(WinningStatus.WIN);
확실히 메서드를 실행하는 주체가 Dealer이니 오인할만하군요.
player로 WinningStatus를 반환하는 메서드를 옮겼습니다.
또한, 좀 더 명시적으로 알 수 있게, calculatePlayerWinningStatus라고 지어줬습니다.

2023-03-08 00:17 UTC, hong-sile commented on src/main/java/blackjack/domain/Users.java
> +    }
```mermaid
flowchart TD
       Users --> Players
       Users --> Dealer

       Players --> Player
```

필드 제약 때문에 Users에서 Players(Player의 일급컬렉션), Dealer를 갖도록 하였습니다.

리팩터링을 하다보니 합성으로 변경하고 싶기도 하였는데, 일단 상속으로도 구현은 가능하니 이번 기회에 학습해보고자
계속 상속을 유지해보겠습니다.

2023-03-08 00:20 UTC, hong-sile commented on src/main/java/blackjack/view/InputView.java
> +    private static final String DELIMITER = "\\s*,\\s*";
맨처음에 ", " 만 만들고나서, 후에 "\\s*,\\s*"와 같은 식으로 리팩터링 하여서 네이밍을 그대로 유지했네요.
(컴마 주위에 공백이 들어가는 것을 없애기 위해)
DELIMIT_REGEX라는 네이밍으로 리팩터링 하였습니다.

2023-03-08 00:27 UTC, hong-sile commented on src/main/java/blackjack/dto/CardResult.java
> +public class CardResult {
아마 저렇게 지었던 이유가 추후에 승무패 결과를 GameResult로 정의하려고 했어서, CardResult라고 정의했었어요.
(물론 현재 승무패 결과의 네이밍을 WinningResult라고 해서 의미가 없죠...😂)

2023-03-08 00:36 UTC, hong-sile commented on src/main/java/blackjack/domain/BlackJackGame.java
> +    public Map<String, CardResult> getCardResult() {
확실히 반환타입과 메서드명이 일치하지 않네요.
getUserNameAndCardResults로 수정하였습니다..

2023-03-08 00:36 UTC, hong-sile commented on src/main/java/blackjack/controller/DrawInput.java
> +public enum DrawInput {
해당 Enum을 사용하는 곳이 controller밖에 없으니까 controller 가 맞지 않을까요? 
다른 domain 또는 view에서 사용되지 않으니까요.

2023-03-08 00:37 UTC, hong-sile commented on src/main/java/blackjack/controller/BackJackController.java
> +        outputView.printLineBreak();
의도된 부분은 아닙니다. 리팩터링 하기전엔 Map(HashMap)으로 반환했기에 순서가 보장이 안 되어있네요.
LinkedHashMap을이용하여 순서를 보장하도록 수정하였습니다.

2023-03-08 00:50 UTC, hong-sile commented on src/main/java/blackjack/controller/BackJackController.java
> +    private void playFor(final BlackJackGame blackJackGame, final String name) {
확실히 파라미터만 보더라도 for는 좀 이상하군요... playPlayer로 수정하였습니다.

2023-03-08 01:37 UTC, hong-sile commented on src/main/java/blackjack/controller/BlackJackController.java
> +        try {
이 부분은 indent 1을 지킨다는 조건을 맞추기 위해
기존 continuous를 파라미터로 받고 repeat에서 try-catch 처리하였습니다.

(마음에 안들긴 한데 더 좋은 방법이 생각이 안 났어요... 더 나은 방법이 생각나면 바로 리팩터링 할 예정입니다.)

2023-03-08 06:24 UTC, hong-sile commented on src/main/java/blackjack/controller/BackJackController.java
> +        outputView.printInitialStatus(ViewRenderer.renderStatus(blackJackGame.getInitialStatus()));
좀 더 가독성이 좋게 반환값을 중간에 분리하였습니다.

2023-03-08 06:24 UTC, hong-sile commented on src/main/java/blackjack/controller/BlackJackController.java
> +        try {
수정하였습니다. drawInput 부분만 에러 발생할 수 있으니, 해당 부분만 trycatch로 감싸서 처리하였습니다.

2023-03-08 10:02 UTC, hong-sile commented on src/main/java/blackjack/domain/user/Players.java
> +        players.forEach(player ->
제출하고 코드를 다시 보고 있는데, 이 map의 반환 타입이 Map<String,CardGroup> 보다 Map<Name, CardGroup>이 적당한 것 같군요.
이 메서드 말고 다른 메서드들도 key를 String이 아닌 Name으로 리팩터링 해보도록 하겠습니다.

2023-03-08 23:14 UTC, jamie9504 requested changes
홍실, 안녕하세요. 리뷰어 제이미입니다 😄 

리뷰 조금 남겨두었는데, 변경하시고 싶은 부분 변경하신 후 리뷰 요청 다시 주세요.

이번 반영 후에 2단계로 넘어가면 될 것 같습니다.

2023-03-08 23:14 UTC, jamie9504 commented on src/main/java/blackjack/view/OutputView.java
> +    }
println을 직접 호출하는 것과 메서드를 분리한 것의 차이점이 있을까요?

2023-03-08 23:14 UTC, jamie9504 commented on src/test/java/blackjack/domain/BlackJackGameTest.java
> +                .containsExactly("필립", "홍실");
필립, 홍실, 딜러 등의 반복되는 이름은 상수로 빼도 되지 않을까요?
변경지점을 하나로 줄일 수 있을 것 같아요!

2023-03-08 23:14 UTC, jamie9504 commented on src/test/java/blackjack/domain/BlackJackGameTest.java
> +     */
요 부분은 취향 차이이니 참고만 해주세요/
주석은 편하도록 정보를 전달해주고 있지만, 코드 수정시 체크를 하지 못할 수도 있습니다.

테스트 메서드 내에서 필립, 홍실, 딜러의 점수를 계산해서 보여주는 로직이 있어도 좋지 않을까요?
ex) `assertThat(blackJackGame.getScore("필립")).isEqualTo(21)`

2023-03-09 02:17 UTC, hong-sile commented on src/main/java/blackjack/domain/Users.java
> +    }
아 3개 이하 유지가 아니라 2개 이하였습니다. 글을 잘못 썼군요.

2023-03-09 07:52 UTC, hong-sile commented on src/main/java/blackjack/controller/BlackJackController.java
> +        for (final String name : firstOpenCardGroups.keySet()) {
그렇네요 firstOpenCardGroups.keySet()와 userNames가 내부의 값들이 전부 같으니, 위에서 만든 userNames를 이용하고 userName으로 통일하는게 더 나을 것 같네요

2023-03-09 07:54 UTC, hong-sile commented on src/main/java/blackjack/controller/BlackJackController.java
> +        return true;
아 위처럼 바꿀수도 있다고 생각은 하였는데, 더 읽기 어려운 것 같아서 일부로 if문으로 나눠서 분리했어요.

2023-03-09 10:36 UTC, hong-sile commented on src/main/java/blackjack/domain/user/Dealer.java
> +    public static final String DEALER_NAME = "딜러";
제가 이번 미션에서 작성한 코드 중에 딜러의 이름을 public으로 연 이유는 player에서 사용하기 위해서에요.
player의 이름으로 "딜러"라는 이름이 오면 이를 예외처리해야 한다고 생각하여서 public으로 열고 player에서 접근을 하죠.
private으로 막고, player에도 딜러의 이름을 상수화해서 가지고 있는 것도 생각을 해봤지만, 그럴 경우 딜러의 이름이 변경될 경우에 문제가 생긴다고 생각하여, public으로 열고 이를 사용했어요.

static final을 public으로 열었다고 해서 생기는 문제는 저는 없다고 생각해요. DEALER_NAME에 내부값이 변경 가능한 레퍼런스 타입이 아닌 문자열이 오니까요.

아마 발생할 수 있는 문제는 다른 레이어에서 접근해서 확인할 수 있는 문제들이 있긴 한데, 접근한다 한들 확인밖에 못하기에, 단점이 크게 있다곤 생각하지 않아요.

저도 private static final이 아닌 public static final을 쓰는게 불안하긴 하지만,
1. 불변이 유지되는 값이고,
2. 단순한 문자열이며
3. public static final이 아닌 private로 만들고, player에서 따로 정의하면, 추후 변경시 생기는 문제점이 더 크다고 생각하여서
public static final을 사용했습니다.

그리고, 이펙티브 자바 [Item15 클래스와 멤버의 접근 권한을 최소화하라]에서도, 기본값이나 불변객체이며, 해당 요소가 클래스를 구성하는데 꼭 필요한 상수면 public static final로 선언해도 된다고 나와있습니다.

딜러의 이름이 클래스를 구성하는데 꼭 필요한 상수이진 않지만, 불변 상수를 외부에 공개하는 것에서 발생할 만한 사이드 이펙트가 유의미하지 않다고 책에서 시사한다고 이해했습니다.

아마 추가적으로 변경한다면, 지금 딜러 이름을 외부에서 접근하는 곳이 Player밖에 없으니 접근제어자를 pakage-priavte하게 바꿀 것 같습니다. 문제가 없다하여도 접근권한은 최소화 하면 좋으니까요.

2023-03-09 10:50 UTC, hong-sile commented on src/main/java/blackjack/domain/user/Dealer.java
> +    public static final String DEALER_NAME = "딜러";
+ 추가적으로 찾아보면서 아래와 같은 글도 보았습니다.

[public static final vs private static final + static get](https://stackoverflow.com/questions/10047802/public-static-final-or-private-static-final-with-getter)

위 글에 의하면 public static final로 상수를 관리하는 경우, 
상수를 제공하는 클래스(제 코드 같은 경우엔 Dealer)에서 값을 바꿔버린다면, 
상수를 제공받는 클래스(제 코드 같은 경우에선 Player)를 리컴파일 하지 않는 경우, 변경이 제대로 적용되지 않는다고 나와있습니다.(제가 이해한 바는 이렇습니다.)

하지만 제가 개발하는 환경 및 사용하는 환경에서 일부만 컴파일 하지 않는 일은 일어나지 않기 때문에, 현재 제 상황에서는 문제가 생기지 않을 것 같습니다. 

사실 일부 클래스만 리컴파일 되지 않는 경우가 얼마나 많을지 모르겠습니다. 그러한 경험이 없었어서요. 혹시 실제로 일부 코드만 리컴파일 되지 않는 경우가 있을까요?

2023-03-09 12:49 UTC, hong-sile commented on src/test/java/blackjack/domain/BlackJackGameTest.java
> +     */
와우 이건 생각 못한 아이디어네요. assertThat으로 유효성 검증만 할 생각만 했지.
assserThat으로 정보를 표시하다니! 앞으로 종종 테스트 코드에 적용하도록 하겠습니다.

2023-03-09 12:49 UTC, hong-sile commented on src/test/java/blackjack/domain/BlackJackGameTest.java
> +                .containsExactly("필립", "홍실");
아주 좋은 방법인 것 같아요. 다 분리하였습니다.

2023-03-09 13:39 UTC, hong-sile commented on src/main/java/blackjack/domain/card/CardGroup.java
> +    public CardGroup(final Card firstCard, final Card secondCard) {
위와 같이 두 값으로로만 만든 이유는, CardGroup이 처음 생성될 때 카드를 두 장만 받으니, 
좀 더 제약을 강하게 두고자 똑같은 타입임에도 명시적으로 변수 두 가지로 설정하였습니다.

추후 초기 손패가 3,4장으로 늘어나면, 변경을 많이 해야된다는 점에서 확장성이 떨어질 것 같긴 합니다.

2023-03-10 00:44 UTC, hong-sile commented on src/main/java/blackjack/view/OutputView.java
> +    }
개행을 위해 System.out.println을 호출한 것보다, 메서드를 분리하고 이름으로 표현하는게 더 읽기 편하다고 생각해서 메서드를 분리하였습니다.

2023-03-10 00:51 UTC, hong-sile commented on src/main/java/blackjack/domain/card/RandomDeckGenerator.java
> +        return cards;
제가 생각한 Deck란 도메인의 기준은 카드들의 집합이고, 카드를 반환할 때마다 Deck에서 해당 카드를 제거하는 것이 Deck의 역할이라고 생각했습니다.(그래서 Queue를 떠올린 거고요.)

단순히 Deck이 위와 같은 역할을 포함한다고 생각하여, generator에서 52장을 생성하는 로직을 넣었습니다.
부가적으로 Deck이 받는 개수를 제한을 두지 않음으로써 테스트가 훨씬 편해졌습니다.

만약 Deck이 정렬된 상태로 생성되고, Generator가 Random 셔플만 해준다면, 테스트를 할 때, 유동적으로 덱을 세팅할 수 없어서 불편했을 겁니다. 원하는 카드를 세팅하기 어려웠겠죠.

그래서 저는 2번을 계속 유지할 것 같습니다.

2023-03-10 01:53 UTC, hong-sile commented on src/main/java/blackjack/domain/card/CardGroup.java
> +    }
Score가 CardGroup을 알아도 된다는 의미가 정확하게 이해가 안 되서요.
아래와 같은 내용이 맞을까요?

1. Score의 파라미터로 CardGroup을 받는다.
2. Score의 필드로 CardGroup을 갖는다.

1번이라면, Score를 계산하는데 필요한 값이 ace의 개수와, cardGroup의 총 숫자의 합이기에, 그 값만 단순히 넘겨주었고요.

2번인 경우라면 아마, User필드로 Score를 갖고, Socre의 필드로, Cardgroup을 갖는 경우를 말씀하신 것 같아요.
먼저 그렇게 안 한 이유는 Score 객체를 불변으로 유지하고 싶어서입니다. 
도메인에서 계속해서 변하는 스코어를 사용합니다. 카드를 새로 뽑을 때마다 Socre의 값이 계속해서 변하기 때문에, 필요한 시점마다 Score를 생성해서 반환을 해줍니다.
(근데 너무 과하게 Score가 생성되고, 소멸되는 느낌도 있긴 하네요, 아마 이런 부분은 캐싱으로 해결할 수 있긴 하겠군요.)

그리고 저는

2023-03-10 03:03 UTC, hong-sile commented on src/main/java/blackjack/domain/Deck.java
> +    }
해당 클래스에서만 봤을 때 Null을 반환하는 케이스가 있을수도 있으니
optional로 감싸고, null이면 IllegalStateException을 throw하게 리팩터링 하였습니다.

궁금한게 하나 있어요. 이 코드에서 사실 위에서 인원수 제약을 했기 때문에, IllegalStateException이 throw 될 일은 없어요. 
그리고 Deck만 보더라도, 빈 Deck에서 poll을 했을 때 IllegalStateException이 발생하기에, Deck이 null을 반환해 어딘지 모르는 곳에서 NPE가 발생할 위험도 방지하였습니다.

혹시 이렇게 실제 발생할 일이 없는 Exception을 catch하여 처리하는 로직도 현재에선 필요할까요?

2023-03-10 04:06 UTC, hong-sile commented on src/main/java/blackjack/domain/card/Deck.java
> +    }
초기에 players에서 firstCardGroup을 생성하는 로직 즉, deck의 draw를 호출하여 CardGroup을 만드는 로직을 짰었습니다.

하지만, 외부에서 deck draw를 두 번 호출해주는 것보다 Deck의 내부에서 만들어서 반환해주는게 더 낫다고 생각했어요. 
players가 너무 많은 책임을 지니고 있는 것 같았거든요.

지금보니 처음의 CardGroup을 반환하는 것은 Deck의 책임이다!라고 보기는 애매한 것 같아요.
그렇다고, 그것이 players의 책임이냐? 라고 묻는다면 그것도 애매하고요.

그럼 혹시, CardGroup에서 Deck을 인자로 받아서, 초기 CardGroup을 생성해서 반환해주는 것은 어떻게 생각하시나요?
처음에 2장을 뽑는다는 것을 아는 것은 CardGroup만 알면 된다고 생각하거든요.
기존의 public CardGroup(Card Card1, Card Card2)를 public CardGroup(Deck deck)으로 바꾸는 거죠.

2023-03-10 04:09 UTC, hong-sile commented on src/main/java/blackjack/domain/user/User.java
> +    }
확실히 CardGroup의 상태에 따라서, 뽑거나 안 뽑거나가 결정되는데,
외부에서 체크하고 뽑는 상황에만 draw를 호출하니 말씀하신 오류가 발생할 수 도 있겠네요

2023-03-10 05:13 UTC, hong-sile commented on src/main/java/blackjack/domain/BlackJackGame.java
> +    public CardGroup getCardGroupBy(final String name) {
> 1. Controller에서 일부 BlackjackGame이 가져야할 역할을 가지고 있는 게 아닐지 고민해보면 좋을 것 같습니다.
지금 제가 생각하기에 Controller에서 BlackjackGame으로 넣을 수 있는 기능은 다음과 같습니다.

1. isContinuous -> 모두 blackjackGame의 메서드로 로직이 구성됨. blackjackGame에서 통합해서 반환할 수 있음
2. y 또는 n에 따라 카드를 뽑고 안 뽑고가 결정되는 로직 -> 나중에서야 확인했는데, 마지막에 n을 입력해도 카드를 한 장 더 뽑더라고요... blackjackGame에서 y또는 n이 들어있는 Enum(DrawOrStay)에 따라, 뽑을지 말지를 결정하는 로직을 넣었습니다.

blackjackGame에서 도메인과 관련된 모든 분기를 처리하고, Controller에서는 단순히 입력과 출력을 매핑해줘야한다는 의견에 적극 동의합니다. 

하지만 입력된 값에 따라 이후에 
"현재 플레이어에 대한 yn을 받을지, 다음 플레이어에 대한 yn을 받을지"가 결정되기에 controller에서 로직을 어느정도 만들었습니다.

음... 이건 적용하진 않았지만 고민한 로직인데, InputView의 y,n을 입력받는 메서드랑, 그 출력하는 메서드를 함수형 인터페이스로 넘길까도 생각해봤어요 (inputView.read -> Supplier, outputView.print -> Consumer)

실제로 이런식으로 하면 controller에서는 로직이 엄청 간단해지고, 입출력함수들도 함수형 인터페이스로 포장되기 때문에, blackjackGame에서의 로직도 간단해집니다.

하지만 view의 메서드들이 비록 함수형 인터페이스라곤 하나, domain내부에 코드가 씌이는게 괜찮을지? 몰라서 고민이 되네요. 
view가 바뀐다 하더라도, 전혀 domain의 코드를 바꿀 필요도 없긴 하지만(그래서 의존하는게 아니라고 생각했습니다.)
너무 생소한 방법이다보니? 어떠한 사이드이펙트가 발생할지 몰라서 실제로 코드를 짜서 사용은 해봤지만 커밋은 하지 않았어요.
이렇게 함수형 입출력함수를 함수형 인터페이스로 받아, blackjackGame에서 처리해도 문제가 없을까요?

> 2. Users를 파라미터 2개로 묶어놨는데, 이 부분을 묶어야 할 필요가 있었을지 고민해봐도 좋을 것 같습니다.

> 3. step1 미션을 할 땐, step2 미션을 고려하지 않고 미션을 진행해야 다음 step으로 넘어갈 때 변경점이 많고 거기서 배우는 점들도 많다고 생각하는데, 이 부분은 진행정도와 취향에 따라 선택하면 될 것 같아요.

저도 이 말에 동의를 해요. 저도 step1을 작성할 때 step2를 고려하지 않고, 코드를 작성합니다. 그래야 실패도 해보고 실패에서 배울게 많다고 생각하거든요. 
책에서 아무리 안 좋은 설계라 이야기해도 직접 본인이 설계를 하다 실패를 겪는 것에서 좀 더 많이 배울 수 있다고 생각해요.
추가적으로 step2를 고려하지 않아야, 일반적으로 코드가 변경되는 상황(실무에서 갑자기 기능이 추가되는 경우)을 겪을 수 있다고 생각하거든요. 만약에 step2를 보고 코드를 작성한다면, 그 step2에 최적화된 코드로 작성하게 될 것 같아서
저는 step1을 짤 땐 step2를 고려하지 않고 짜긴 합니다.

2023-03-10 05:35 UTC, hong-sile commented on src/main/java/blackjack/domain/user/Players.java
> +                .collect(Collectors.toUnmodifiableList());
> 초기에 players에서 firstCardGroup을 생성하는 로직 즉, deck의 draw를 호출하여 CardGroup을 만드는 로직을 짰었습니다.
> 
> 하지만, 외부에서 deck draw를 두 번 호출해주는 것보다 Deck의 내부에서 만들어서 반환해주는게 더 낫다고 생각했어요. players가 너무 많은 책임을 지니고 있는 것 같았거든요.
> 
> 지금보니 처음의 CardGroup을 반환하는 것은 Deck의 책임이다!라고 보기는 애매한 것 같아요. 그렇다고, 그것이 players의 책임이냐? 라고 묻는다면 그것도 애매하고요.
> 
> 그럼 혹시, CardGroup에서 Deck을 인자로 받아서, 초기 CardGroup을 생성해서 반환해주는 것은 어떻게 생각하시나요? 처음에 2장을 뽑는다는 것을 아는 것은 CardGroup만 알면 된다고 생각하거든요. 기존의 public CardGroup(Card Card1, Card Card2)를 public CardGroup(Deck deck)으로 바꾸는 거죠.

players에서도 해당 책임을 맡기엔 애매하다고 생각해요. CardGroup에 Deck을 인자로 받는 생성자를 추가하였습니다.

2023-03-10 06:27 UTC, jamie9504 commented on README.md
> -# java-blackjack
.

2023-03-10 06:27 UTC, jamie9504 commented on src/main/java/blackjack/domain/Deck.java
> +    }
// TODO

2023-03-10 06:27 UTC, jamie9504 commented on src/main/java/blackjack/domain/Users.java
> +    }
> **추가된 요구 사항**
> 모든 엔티티를 작게 유지한다.
> 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.
> 딜러와 플레이어에서 발생하는 중복 코드를 제거해야 한다.

위와 같이 미션 인지했었는데, 2개 이하로 유지하는 조건이 어디에 있었을까요?

2023-03-10 06:27 UTC, jamie9504 commented on src/main/java/blackjack/domain/BlackJackGame.java
> +    public CardGroup getCardGroupBy(final String name) {
// TODO

2023-03-10 06:42 UTC, jamie9504 commented on src/main/java/blackjack/controller/BlackJackController.java
> +            outputView.printCardGroup(name, renderedCardGroup);
// TODO

2023-03-10 06:44 UTC, jamie9504 commented on src/main/java/blackjack/domain/card/CardGroup.java
> +    public CardGroup(final Card firstCard, final Card secondCard) {
저는 CardGroup이 카드를 2개 받는다는 것을 알고 있을 필요가 있는지에 대해서 고민이 되는 것 같아요.

처음에 카드를 2장 뽑는다는 것은, BlackjackGame의 룰이라서
CardGroup이 카드를 2개를 고정해서 받을 책임이 있을지에 대한 의문인 것 같네요 😄

2023-03-10 06:44 UTC, jamie9504 commented on src/main/java/blackjack/domain/card/CardGroup.java
> +    }
// TODO

2023-03-10 06:45 UTC, jamie9504 commented on src/main/java/blackjack/domain/card/Deck.java
> +    }
// TODO

2023-03-10 06:46 UTC, jamie9504 commented on src/main/java/blackjack/domain/user/Dealer.java
> +    public static final String DEALER_NAME = "딜러";
// TODO

2023-03-10 06:47 UTC, jamie9504 commented on src/main/java/blackjack/domain/Deck.java
> +    }
// TODO

2023-03-10 06:48 UTC, jamie9504 commented on README.md
> +#### domain
,

2023-03-10 06:48 UTC, jamie9504 commented on src/main/java/blackjack/domain/Deck.java
> +    }
// TODO

2023-03-10 06:49 UTC, jamie9504 commented on src/main/java/blackjack/domain/Deck.java
> +    }
// TODO

2023-03-10 08:34 UTC, merged

2023-03-13 04:09 UTC, hong-sile commented on src/main/java/blackjack/controller/BlackJackController.java
> +            outputView.printCardGroup(name, renderedCardGroup);
이전에 네오가 이전에 UI(System.out, System.in)는 시간이 걸리니 테스트하지 말라고 하셨던거 더라고요. 그래서 System.out과 System.in 즉 직접적인 입출력이 아닌 로직은 테스트하기 쉬우니 테스트 했습니다.

뭐 그래도 안해도 되는 거긴 하지만, 저는 요구사항 외로 테스트를 하고 싶었어요. 만들어두니까 편하더라고요

2023-03-13 05:23 UTC, hong-sile commented on src/main/java/blackjack/domain/card/CardGroup.java
> +    public CardGroup(final Card firstCard, final Card secondCard) {
아 이해했습니다. 확실히 CardGroup이 필요없는 책임까지 들고있는 느낌이네요. 해당방식으로 수정해보도록 하겠습니다.

2023-03-13 05:43 UTC, hong-sile commented on src/main/java/blackjack/domain/card/CardGroup.java
> +    }
아 어떤 의도이신지 알 것 같습니다. User에서도 충분히 Score를 생성할 수 있는데, 굳이 그 생성하는 책임이 CardGroup까지 가야 하냐였군요.

일단 그렇게 안한 이유는 다음과 같습니다.
Score의 파라미터로 cardGroup을 받지 않습니다.
실질적으로 Score를 생성하는데 필요한 값은 카드의 cardNumber의 총합, ace의 개수, 총 카드의 개수(이 부분은 step2를 하면서 필요해진 값입니다.)입니다.
위 세 값은 CardGroup의 필드로 충분히 구할 수 있습니다. 그래서 CardGroup에서 생성해주었습니다.

만약 Score의 파라미터로 CardGrouop을 받았다면 cardNumber의 총합, ace의 개수, 총 카드의 개수을 반환하는 메서드를 public으로 지정해서 단순히 Score 내부에서 호출만 해줄 것입니다.

저는 그것보단 private으로 각 값들을 숨기고, CardGroup내부에서 Score를 생성하도록 하였습니다.

2023-03-13 05:45 UTC, hong-sile commented on src/main/java/blackjack/domain/card/Deck.java
> +    }
blackjackGame에서 Queue<CardGroup>을 생성해서 넘겨주고, Queue<CardGroup>을 생성할 때, CardGroup에 두 장씩 넣어주도록 수정하였습니다.

2023-03-13 05:47 UTC, hong-sile commented on src/main/java/blackjack/domain/user/Players.java
> +                .collect(Collectors.toUnmodifiableList());
> blackjackGame에서 Queue<CardGroup> 을 생성해서 넘겨주고, Queue <CardGroup> 을 생성할 때, CardGroup에 두 장씩 넣어주도록 수정하였습니다.