[1단계 - 블랙잭 게임 실행] 마코 (이규성) 미션 제출합니다.
woowacourse/java-blackjack pull request #440
Opened 2023-03-03 08:24 UTC by aak2075

안녕하세요 마코입니다!
설계를 할 때는 만만하게 본 미션이었으나 구현에서 크게 혼났네요.
따끔한 리뷰 잘 부탁드립니다 😄 

---

Deck은 Dealer나 player가 Card를 요청하면 가지고 있는 List<Card>에서 랜덤 위치의 Card를 반환합니다. Deck은 생성자에서 모든 CardType과 CardNumber별로 Card 객체를 생성해서 리스트에 담습니다.  저는 이때 리스트에 어떠한 카드를 생성해서 어떠한 방식으로 리스트에 초기화하는지 결정하는 로직은 외부로 분리해야 한다고 주장했습니다. 그러나 페어의 의견은 Deck의 상태는 Deck 안에서 관리하는 것이 맞다고 주장했습니다.  이에 대해서 조언이 필요합니다.

처음에는 BlackjackGame이 Dealer, List<Player>, Deck을 인스턴스 변수로 가져서 게임의 전반적인 진행을 담당했습니다.
그러나  `3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.` 라는 요구사항에 의해 모든 플레이어와 딜러를 관리하는 People 클래스를 만들어 모든 사람에 대한 관리를 하도록 했습니다. 그렇게 분리를 하다 보니 BlackjackGame의 역할은 컨트롤러와 People의 사이에서 메시지만 전달한다는 느낌이 들었습니다.  또한, People에서는 Dealer와 List<Player>를 둘 다 관리하다 보니 책임이 너무 커졌다고 생각했습니다.  이에 대해서 어떻게 생각하시는지 궁금합니다!

2023-03-03 11:46 UTC, Laterality requested changes
안녕하세요 마코, 리뷰어 에단입니다. 

잘 구현해주셨어요 👍 

몇가지 간단한 코멘트 남겨드렸습니다. 확인 부탁드려요.

## Q&A

1. Deck의 초기화 로직
    a. 서로 그렇게 생각하신 이유가 궁금합니다.
2. a. `BlackjackGame`이 초기에 의도했던 역할을 제대로 하지 못하고 있다는 뜻일까요? 만약 `BlackjackGame`을 없앤다면 그 역할을 어디서 대신하는 것이 적절할까요?
    b. `People`에서 `players`와 `dealer`만 가졌음에도 역할이 많다면 그 둘과 `deck`을 함께 가졌던 초기 `BlackjackGame`의 역할은 더 컸던 것은 아닐까요? 만약 지금 `People`의 역할도 많다고 생각하신다면 어떤 역할들로 나누어 분리할 지 고민이 필요하겠네요.

2023-03-03 11:46 UTC, Laterality commented on src/main/java/domain/card/CardNumber.java
> +public enum CardNumber {
[위키피디아](https://ko.wikipedia.org/wiki/%ED%94%8C%EB%A0%88%EC%9E%89_%EC%B9%B4%EB%93%9C)에 따르면 카드의 숫자/알파벳은 끗수(denomination), 문양은 슈트(suit)라고 부른다고 하네요. 용어에 맞게 이름도 바꿔보면 어떨까요?

2023-03-03 11:46 UTC, Laterality commented on src/main/java/domain/game/BlackjackGame.java
> +    public boolean isBurst(String playerName) {
버스트의 철자는 "Bust"라고 하네요([참고](https://namu.wiki/w/%EB%B8%94%EB%9E%99%EC%9E%AD(%EC%B9%B4%EB%93%9C%EA%B2%8C%EC%9E%84)#s-4.3)).

2023-03-03 11:46 UTC, Laterality commented on src/main/java/domain/game/Deck.java
> +        return cards.get(numberGenerator.generate(cards.size()));
`Deck`에서 한번 뽑은 카드가 다시 나오지는 않을까요?

2023-03-03 11:46 UTC, Laterality commented on src/main/java/domain/user/CardPool.java
> +public class CardPool {
참여자와 딜러가 가진 패를 나타내는 것 같은데, "Hand"라는 이름은 어떨까요?

2023-03-03 11:46 UTC, Laterality commented on src/main/java/view/InputView.java
> +        for (String target : targets) {
`target(s)`보다 더 좋은 이름이 있을까요?

2023-03-03 11:46 UTC, Laterality commented on src/test/java/domain/CardPoolTest.java
> +}
파일 끝에는 빈 줄을 추가해주세요.

2023-03-04 06:42 UTC, aak2075 commented on src/main/java/domain/card/CardNumber.java
> +public enum CardNumber {
그런 용어가 있었는지는 몰랐네요! 좋은 의견 감사합니다.

2023-03-04 06:42 UTC, aak2075 commented on src/main/java/domain/game/BlackjackGame.java
> +    public boolean isBurst(String playerName) {
반영했습니다~

2023-03-04 06:43 UTC, aak2075 commented on src/main/java/domain/user/CardPool.java
> +public class CardPool {
위키에서 용어가 따로 없었어서 임의로 정했었는데 더 찾아보니 `일반적으로 블랙잭 카드 게임에서 플레이어가 손에 들고 있는 카드 세트를 "hand" 라고 합니다.` 라는 내용이 있었네요! 좋은 지적 감사합니다.

2023-03-04 06:43 UTC, aak2075 commented on src/main/java/domain/user/CardPool.java
> +    private static final int CARD_POINT_LIMIT = 21;
CardPool은 카드를 저장하고 관리하는 일급 컬렉션으로 게임에 대한 룰은 몰라야 한다고 생각했습니다. 따라서 `BLACKJACK_NUMBER`를 전달 받지 않고 구현하려다 보니 같은 의미이면서 따로 선언을 해버렸습니다.

리팩토링을 하는 과정에서 CardPool의 `CARD_POINT_LIMIT`를 제거하고 `BlackjackGame`에서 `BLACKJACK_NUMBER`를 계속 파라미터로 넘겨주다 보니 파라미터가 너무 많이 생겨 코드가 지저분해진다는 생각이 들었습니다.

이를 해결하기 위해 `게임 룰에 관한 상수를 다루는 GameRule Enum` 을 만들어서 상수를 따로 관리했습니다. 단순히 파라미터가 많아지는 것을 막기 위해 어느 클래스에서나 접근 가능한 상수를 사용하는 것이 맞는지 의문이 듭니다.

2023-03-04 06:43 UTC, aak2075 commented on src/main/java/domain/user/CardPool.java
> +        }
`decideAceNumber()` 라는 메서드를 추가해서 모든 카드의 합이 21이 넘었을 때 에이스 카드의 개수만큼 합에서 10을 빼주도록 구현했습니다.

```java
    private int decideAceNumber(int sum, int unDecidedAceCount) {
        if (sum > GameRule.BLACKJACK.getNumber() && unDecidedAceCount > 0) {
            sum = sum - (Denomination.ACE.value() - GameRule.MIN_ACE.getNumber());
            return decideAceNumber(sum, unDecidedAceCount - 1);
        }
        return sum;
    }
```

위의 코드에서, `GameRule.MIN_ACE.getNumber()`이라는 숫자는 ACE의 작은 값인데 Denomination에서 알아야 하는 값이라고 생각했지만 ACE만 따로 값을 두 개 가지도록 하기가 어려워서 다음과 같이 생각했습니다.
`조건에 따라서 바뀌는 에이스의 숫자는 게임의 룰이기 때문에 GameRule에서 관리해도 된다`
저의 생각이 타당하다고 생각하시는지 궁금합니다!

2023-03-04 06:43 UTC, aak2075 commented on src/main/java/domain/user/PlayerName.java
> +        if (target.length() < 1 || target.length() > 5) {
반영했습니다~

2023-03-04 06:43 UTC, aak2075 commented on src/main/java/view/InputView.java
> +        for (String target : targets) {
targets -> list
target -> element

위와 같이 수정했습니다.

2023-03-04 06:43 UTC, aak2075 commented on src/test/java/domain/CardPoolTest.java
> +package domain;
패키지 분리를 나중에 했더니 테스트의 패키지는 깜빡했네요. 😯

2023-03-04 06:43 UTC, aak2075 commented on src/test/java/domain/CardPoolTest.java
> +}
인텔리제이의 자동 개행 추가 설정이 해제되어있었네요!

2023-03-05 02:40 UTC, aak2075 commented on src/main/java/domain/game/Deck.java
> +        return cards.get(numberGenerator.generate(cards.size()));
`cards.remove()` 로 수정하여 한 번 뽑은 카드는 나오지 않도록 수정했습니다.

2023-03-06 06:28 UTC, aak2075 commented
안녕하세요 에단!

정성껏 피드백 해주셔서 감사합니다! 

피드백을 반영하고 수정이 필요하다고 생각하는 부분을 추가로 리팩토링했습니다.

이번에도 잘 부탁드립니다!!

## Q & A 답변

> 1. Deck의 초기화 로직
    a. 서로 그렇게 생각하신 이유가 궁금합니다.

**나의 의견**
Deck이 단순히 카드 리스트를 가지고 있고, 카드를 랜덤으로 뽑아주는 책임이라고 생각했습니다.
카드 리스트를 만드는 것은 특별한 로직이 들어가 있고 이 책임까지 Deck에 부여하는 것은 책임이 많아진다고 생각했기 때문에 외부에서 카드 리스트를 만들어서 주입해야 한다고 생각했습니다.

**페어의 의견**
카드 리스트는 Deck의 **상태**이고, Deck의 상태는 Deck이 관리하는 것이 맞기 때문에 카드 리스트를 만드는 책임도 Deck이 가져야 하는 것이 맞다고 생각했습니다.

> 2. a. BlackjackGame이 초기에 의도했던 역할을 제대로 하지 못하고 있다는 뜻일까요? 만약 BlackjackGame을 없앤다면 그 역할을 어디서 대신하는 것이 적절할까요?

초기에 의도했던 역할을 제대로 못하고 있었습니다. BlackjackGame은 게임의 흐름을 제어해야 하는데 이를 **컨트롤러에서 제어**하고 있었고, 리팩토링 과정에서 담당하도록 수정했습니다. 따라서 BlackjackGame을 없앨 필요는 없어졌네요!

>  b. People에서 players와 dealer만 가졌음에도 역할이 많다면 그 둘과 deck을 함께 가졌던 초기 BlackjackGame의 역할은 더 컸던 것은 아닐까요? 만약 지금 People의 역할도 많다고 생각하신다면 어떤 역할들로 나누어 분리할 지 고민이 필요하겠네요.

people의 역할은 players와 dealer를 가지고 이들에게 카드를 뽑게하고, 점수를 가져오도록 하는 역할이 있습니다. player와 dealer의 공통된 역할이 있기 때문에 묶어서 같은 메시지를 전달하도록 구현되어 있습니다.  처음에는 책임이 크다는 생각이 들었지만 잘 생각해 보니 **필요한 책임을 적절하게 수행하고 있다는 생각이 듭니다.**

## 주요 리팩토링 사항 

- 피드백 반영
- 컨트롤러에서 outputView로 데이터를 DTO로 전달하여 출력하도록 함
- 명령어에 따른 게임의 흐름 제어를 컨트롤러에서 담당하지 않고 BlackjackGame에서 담당하도록 수정

## 궁금한 점

BlackjackGame이 게임의 흐름을 제어하기 위해서 다음과 같이 필요한 인풋과 아웃풋의 메서드를 파라미터화 해서 넘겨주었습니다.

`blackjackGame.hitAllPlayersByCommand(inputView::inputCardCommand, outputView::printPlayerCardWithName);`

해당 메서드를 따라가다 보면 아래 코드와 같이 Player가 카드를 뽑고, 결과를 출력해줍니다.

```java
draw(deck.serve());
outputPlayer.accept(PlayerParameter.from(this));
```

이 때 DTO인 `PlayerParameter` 를 생성하게 되는데요, 도메인에서 DTO를 생성하는 것이 괜찮은 것인지 의문이 듭니다.  또한, 이러한 방식으로 수정하여 컨트롤러가 게임의 로직을 관리하지 않게 책임을 잘 분리했다는 생각이 들지만 코드가 복잡하다는 생각도 듭니다. 이에 대해 어떻게 생각하시나요?

2023-03-06 13:38 UTC, Laterality requested changes
안녕하세요 마코.

피드백 잘 반영해주셨어요 👍 

몇가지 코멘트와 지난 리뷰에 추가 의견 달아드렸습니다. 참고해주세요.

## Q&A

1. Deck의 초기화 로직

    1. 둘 다 타당한 근거가 있다면 초기화 방법은 어느 쪽이든 크게 문제는 없다고 생각해요. 미래에 도메인이 어떻게 변화하느냐에 따라 서로 주장하는 방법 중 하나가 더 적합할 수 있을텐데, 도메인이 어떻게 변화할 지 예측하는 게 쉽지 않으니까요. 

    2. 마코의 의견은 초기화 방법이 다양해질 수록 유리하겠네요. 가령, 카드의 상태를 DB나 외부의 라이브러리, API 등을 통해 초기화하는 경우라면 이를 모두 `Deck` 안에서 처리하기엔 무리가 있어보여요.

    3. 페어의 의견은 초기화 방법이 더이상 변하지 않는 경우에 유리하겠어요. 변할 가능성이 낮은 코드를 과도하게 분리하는 건 오히려 코드를 이해하고 사용하기 어렵게 만들 수도 있으니까요. 

2. `PlayerParameter`

    1. `PlayerParameter`는 `view`에 위치한 클래스인데, 이를 `domain`에 위치한 `Player`가 의존성을 갖네요. 바람직한 구조일까요?

3. `BlackjackController`

    1. 뷰 메서드의 적절한 호출 시점을 컨트롤러에서 제어하기 어려워 도메인에 함수형 인터페이스로 넘기신 걸로 보이네요. 제 생각에 코드가 복잡해 보이는 이유는 `play` 메서드 본문이 "가로와 세로" 모두 너무 길기 때문이에요.

        1.  DTO(`PlayerParameter`) 생성에 너무 많은 단계의 메서드 호출이 발생하고 있어요(참고. [디미터 법칙](https://tecoble.techcourse.co.kr/post/2020-06-02-law-of-demeter/)).
        2. 메서드 이름이 불필요하게 깁니다. 예를 들어 `printPlayersInfoWhenGameStarted`는 `printGameStarted` 정도로 줄여도 충분합니다. 뷰에서 어떻게 메시지를 출력하는지는 컨트롤러의 관심사가 아니니까요.

    2. `play` 메서드는 아래 정도면 흐름을 이해하기에 충분하지 않을까요? 

        ```java
        public void play() {
            initializeGame();
            blackjackGame.startHit();

            printGameStarted();

            hitPlayers();
            hitDealer();

            printGameResult();
        }
        ```

2023-03-07 08:47 UTC, aak2075 commented on src/main/java/domain/card/Card.java
> +    private final Denomination number;
수정했습니다.

2023-03-07 08:47 UTC, aak2075 commented on src/main/java/domain/game/GameResult.java
> +    private final BiFunction<Integer, Integer, Boolean> function;
점수를 비교하는 역할에 맞게 `comparePoint` 라는 이름으로 수정했습니다.

2023-03-07 08:47 UTC, aak2075 commented on src/main/java/domain/game/GameRule.java
> +    MIN_ACE(1);
사실 이렇게 게임 룰에 관한 상수를 모아둘 것이면 이 게임에서 사용되는 상수를 다 모아 놓는것이 맞았겠네요.
하지만 다시 생각해 보니 사용하는 클래스에서 선언해주는 것이 좋다고 생각합니다.

2023-03-07 08:47 UTC, aak2075 commented on src/main/java/domain/game/HitCommand.java
> +public enum HitCommand {
HitCommand가 연산에 대한 응답으로 사용되는 부분은 제거하고 따로 `Boolean hittable`을 반환하도록 변경했습니다.

2023-03-07 08:47 UTC, aak2075 commented on src/main/java/domain/game/HitCommand.java
> +    n("n");
수정했습니다.

2023-03-07 08:47 UTC, aak2075 commented on src/main/java/domain/user/PlayerName.java
> +    }
수정했습니다.

2023-03-07 08:47 UTC, aak2075 commented on src/main/java/view/InputValidator.java
> +public class InputValidator {
책임 분리의 이점이 있다고 생각합니다. InputView는 input 로직을 실행하는 데에만 집중할 수 있고, validator 클래스는 검증에만 집중할 수 있기 때문입니다.

2023-03-07 08:47 UTC, aak2075 commented on src/main/java/view/InputView.java
> +        return trimList(List.of(splitNames));
`trimList()` 메서드도 제거할 수 있어서 깔끔하고 좋은 것 같습니다! 👍 👍

2023-03-07 08:47 UTC, aak2075 commented on src/main/java/view/dto/PlayerParameter.java
> +public class PlayerParameter {
패키지로 DTO로 구분하면 충분하다는 이야기도 있어서 이렇게 지어봤습니다. 
Dto라는 이름이 들어가면 명확하게 DTO라는 것을 알 수 있어 좋습니다.
하지만 그럼 다른 클래스들도 뒤에 vo, wrapper와 같은 접미사를 붙여줘야 하지 않나? 라는 생각이 드네요.

Player의 정보를 출력하기 위해 전달해준다는 의미에서 `PlayerInfoDto`로 이름을 수정했습니다.

2023-03-07 08:48 UTC, aak2075 commented on src/test/java/domain/user/PlayerNameTest.java
> +    @DisplayName("5자 초과의 이름은 만들 수 없다")
중요한 내용을 빼먹었네요! 경계값에서 올바른 값을 넣었을 때 예외를 던지지 않는지 체크하는 테스트도 추가했습니다.

2023-03-07 08:57 UTC, aak2075 commented
안녕하세요 에단!

피드백을 반영하면서 궁금했던 점들을 적어봤습니다.

이번에도 잘 부탁드립니다 😄 

## 디미터의 법칙

> DTO(PlayerParameter) 생성에 너무 많은 단계의 메서드 호출이 발생하고 있어요(참고. [디미터 법칙](https://tecoble.techcourse.co.kr/post/2020-06-02-law-of-demeter/)).

현재 제가 구현한 블랙잭 게임은 컨트롤러에 로직을 최소화하고 BlackjackGame에서 게임의 흐름을 최대한 담당하도록 했습니다. 이러한 구조로 구현을 하니 너무 많은 getter를 사용할 수밖에 없게 되네요.
예를 들어) 뷰에서 Dealer의 이름이 필요하다면 컨트롤러가 BlackjackGame에서 Dealer를 꺼내서 Dealer에서 Name을 꺼내야 합니다. 

너무 많은 단계의 호출을 해결하기 위해 다음과 같이 해결했어요.

원래는 BlackjackGame -> People -> Dealer.get() 으로 딜러를 꺼냈다면,
현재는 `BlackjackGame.getDealer()` 로 getter를 추가해서 꺼내도록 수정했습니다.

제가 이 문제를 잘 해결한 것이 맞나요?

## 도메인의 뷰 의존

이전 리팩토링 때 `Player` 클래스에서 함수형 인터페이스로 다음과 같이 Input과 output메서드를 받아 실행하도록 했었습니다.

`HitCommand hitCommand = HitCommand.findCommand(inputCommand.apply(playerName.getValue()));`
`outputPlayer.accept(PlayerInfoDto.from(this));`

다시 생각해 보니 View에서 사용하는 DTO를 만들거나 뷰에서 필요한 데이터를 파라미터로 직접 도메인에서 만들어 주기 때문에 도메인이 뷰에 의존하는 부분이 약간은 있는게 아닌가? 라는 생각이 듭니다. 이에 대해서 어떻게 생각하시나요?

2023-03-07 11:27 UTC, Laterality approved these changes
안녕하세요 마코.

피드백 잘 반영해주셨습니다 👍 

이번 단계는 이만 머지하도록 할게요.

남겨드린 코멘트는 다음 단계에서 참고해주세요.

고생 많으셨습니다. 다음 단계도 화이팅하세요 :)

## Q&A

1. 👍 
2. DTO 패키지가 뷰에 있었군요. 그렇다면 도메인에서 뷰에 직접적인 의존성을 갖는 셈이네요. 개선이 필요하다면 다음 단계에서 어떻게 개선할 수 있을지 고민해보시면 좋겠어요.

2023-03-07 11:27 UTC, Laterality commented on src/main/java/view/dto/PlayerParameter.java
> +public class PlayerParameter {
`Info`와 같은 단어가 유의미한 경우는 생각보다 많지 않습니다. `PlayerDto`로도 의미는 충분히 드러나니까요.

클린코드 p.25. "의미있게 구분하라"를 참고해보세요.

2023-03-07 11:27 UTC, Laterality commented on src/main/java/controller/BlackjackController.java
> +    private List<PlayerInfoDto> makePlayersParameterWithResult(List<Player> players) {
메서드명도 바뀌어야겠네요~

2023-03-07 11:27 UTC, Laterality commented on src/main/java/domain/game/BlackjackGame.java
> +    public int getDealerSumHand() {
`sumDealerHand` 같은 이름은 어떨까요?

2023-03-07 11:27 UTC, Laterality commented on src/main/java/domain/game/GameResult.java
> +    private static int calculateGameResult(Collection<GameResult> gameResults, GameResult gameResultType) {
`countMatchedResults` 같은 이름은 어떨까요?

2023-03-07 11:27 UTC, merged

2023-03-08 08:10 UTC, aak2075 commented on src/main/java/view/dto/PlayerParameter.java
> +public class PlayerParameter {
`Info`와 같은 단어는 **불용어** 이군요!

앞으로 이름을 지을 때 정말로 의미 있는 이름인지 잘 생각해 봐야겠습니다.

2023-03-08 08:12 UTC, aak2075 commented on src/main/java/controller/BlackjackController.java
> +    private List<PlayerInfoDto> makePlayersParameterWithResult(List<Player> players) {
수정했습니다.

2023-03-08 08:12 UTC, aak2075 commented on src/main/java/domain/game/GameResult.java
> +    private static int calculateGameResult(Collection<GameResult> gameResults, GameResult gameResultType) {
어떤 역할을 하는지 더 명확해지네요!

2023-03-08 08:13 UTC, aak2075 commented on src/main/java/domain/game/BlackjackGame.java
> +    public int getDealerSumHand() {
`getDealerSumHand` 라는 이름은 BlackjackGame 안에 dealerSumHand라는 필드가 있다고 오해할 수도 있겠네요.