[1단계 - 블랙잭 게임 실행] 오리(오현서) 미션 제출합니다.
woowacourse/java-blackjack pull request #444
Opened 2023-03-03 08:33 UTC by carsago

안녕하세요 제이온 !!

리뷰 잘부탁드립니다 ㅎㅎ 

아무래도 타임 리밋에 맞추다보니 코드가 엉성한편도 많네요 ㅠㅠ 

그리고 질문도 좀 정리된 형태가 아닌데 혹시 괜찮으시다면 Slack DM이나 PR 코멘트에 질문을 추가해도 괜찮으실까요?

2023-03-03 16:30 UTC, pjy1368 requested changes
안녕하세요 오리! 이번 블랙잭 리뷰어를 맡은 제이온입니다 ✌
추상 클래스를 활용하여 중복 코드를 제거하시고 복잡한 블랙잭 도메인의 요구 사항을 잘 구현해 주신 것 같습니다!
다만 Service 객체가 과도하게 비대해진 것 같아서 이 부분의 로직을 도메인에 잘 나눠준다면 더욱 객체 지향적인 프로그램이 가능해 보입니다~
관련 피드백을 남겨뒀으니 반영해 보시고 리뷰 요청 주세요 😊

2023-03-03 16:30 UTC, pjy1368 commented on src/main/java/dto/DrawnCardsInfo.java
> +    }
생성자를 굳이 막으실 필요는 없을 것 같아요. 특별한 이유가 있나요?

2023-03-03 16:30 UTC, pjy1368 commented on src/main/java/dto/WinLoseResult.java
> +    }
여기도 정적 팩터리 메서드는 지우고 오히려 생성자만 남겨둬도 될 것 같습니다.

2023-03-03 16:30 UTC, pjy1368 commented on src/main/java/dto/ParticipantResult.java
> +    }
DTO도 결국 View에다 전달할 객체다 보니, 도메인을 필요 이상을 많이 의존하면 안 된다고 생각해요!
getter 정도 뽑아내는 것은 문제가 되지 않지만, `participant.calculateCardScore()` 같이 비즈니스 로직을 DTO가 활용해서 자신의 필드를 초기화한다면 어떠한 단점이 있을지 고민해 보세요 ㅎㅎ

2023-03-03 16:30 UTC, pjy1368 commented on src/main/java/view/InputView.java
> +}
Wow! '은/는' 처리하는 분은 처음 봤습니다 ㅋㅋㅋㅋ 훌륭합니다 👍

2023-03-03 16:30 UTC, pjy1368 commented on src/main/java/view/OutputView.java
> +        System.out.println(NEW_LINE + "딜러는 16이하라 한장의 카드를 더 받았습니다.");
이 16이라는 값은 도메인(블랙잭) 규칙에 의거하여 나온 값일텐데, 게임의 규칙이 바뀌어서 16이 아니라 18이 되면 어떻게 될까요?

2023-03-03 16:30 UTC, pjy1368 commented on src/main/java/domain/Dealer.java
> +        return Collections.unmodifiableList(openCards);
동료 개발자가 `openDrawnCards()` 메서드를 가져가 쓴다고 할 때, 반환 받은 리스트가 UnmodifiableList면 어떠한 문제점이 있을까요?

2023-03-03 16:30 UTC, pjy1368 commented on src/main/java/service/BlackJackService.java
> +public class BlackJackService {
Service 라는 네이밍이 붙은 클래스는 어떠한 역할을 갖는 클래스라고 생각하시나요? 이번 블랙잭 미션을 기준으로 설명해주세요!

2023-03-03 16:30 UTC, pjy1368 commented on src/main/java/service/BlackJackService.java
> +    private static final int DEALER_DRAW_LIMIT_SCORE = 16;
NUMBER_OF_SPLIT_CARDS -> 나눠 줄 카드의 수
BURST_NUMBER -> 게임 오버 조건
DEALER_DRAW_LIMIT_SCORE -> 딜러의 무승부 수

위 상수를 나열해 보면, 현재 Service 객체가 전부 가져가기보다는 적절히 Card나 Player, Dealer, Participant에 위임하면서 관련된 로직을 상당수 가져갈 수 있어 보이네요!

2023-03-03 16:30 UTC, pjy1368 commented on src/main/java/domain/DrawCommand.java
> +
y와 n은 Controller, View 정도만 쓰이는 조건으로 보이는데, 도메인 패키지에 이 객체가 정의될 필요가 있을까요?

2023-03-03 16:30 UTC, pjy1368 commented on src/main/java/domain/Type.java
> +public enum Type {
더 직관적이게 CardType으로 하면 어떨까요?

2023-03-03 16:30 UTC, pjy1368 commented on src/main/java/domain/Value.java
> +public enum Value {
여기도 Value보다는 CardValue와 같은 한 눈에 알아볼 수 있는 클래스명이면 좋겠습니다~

2023-03-03 16:30 UTC, pjy1368 commented on src/main/java/domain/Value.java
> +    ACE(11, "A");
에이스는 11 외에 1이라는 숫자를 가질 수도 있는데 extraScore를 추가해보는건 어떻게 생각하시나요?

2023-03-03 16:30 UTC, pjy1368 commented on src/main/java/domain/Players.java
> +            throw new IllegalArgumentException("플레이어의 수는 최소 1명, 최대 4명입니다.");
이왕 1과 4를 상수로 정의한 겸, 예외 메시지에도 활용해 줍시다 ㅎㅎ

2023-03-03 16:30 UTC, pjy1368 commented on src/main/java/application/BlackJackApplication.java
> +public class BlackJackApplication {
컨트롤러의 역할을 BlackJackApplication이 수행하는 것 같은데, 네이밍을 Application으로 둔 이유가 있으신가요?

2023-03-03 16:30 UTC, pjy1368 commented on src/main/java/service/BlackJackService.java
> +        cardInfos.add(DrawnCardsInfo.toDto(dealer));
Service는 어떤 계층에 해당한다고 생각하시나요? 현재 도메인 로직도 있고, View 생성 로직이 혼재되어 있어서 질문드립니다.

2023-03-04 04:42 UTC, carsago commented on src/main/java/domain/CardDeckGenerator.java
> +        }
저도 미션의 요구사항을 항상 지키려고하고 이 부분을에 depth를 없애기 위해서 flatMap을 사용해봤는데

이중 for문을 사용하는것에 비해서 가독성이 훨씬 안좋다고 판단해서(물론 가독성은 주관적인 기준이긴 합니다.)

요구사항을 어김에도 이중 for문을 사용했습니다. 요구사항을 엄격히 지키려면 flatMap을 사용하는게 맞겟죠 ㅎㅎㅠ

2023-03-04 04:48 UTC, carsago commented on src/main/java/domain/Players.java
> +            throw new IllegalArgumentException("플레이어의 수는 최소 1명, 최대 4명입니다.");
저는 1이랑 4라는 값은 의미가 불명확해서 상수로 추출하여서 명칭을 주고, 예외 메시지는 오히려 상수화하는게 가독성을 더 해친다고 봐서 하드코딩 하는 형태를 사용했어요. ```"플레이어의 수는 최소 1명, 최대 4명입니다."``` 라는 텍스트를 보면 바로 이해할 수 있지만,
```PLAYERS_SIZE_EXCEPTION_MESSAGE```는 다시 확인하기 위해 한번 더 올려봐야하니까요.

다만 이렇게할거면 상수를 최대한 안쓰기 위해 ```"players.size() < MIN_PLAYERS_SIZE || players.size() > MAX_PLAYERS_NUMBER```  보다는 ```players.size() < 1 || players.size() > 4```를 메소드 추출해서 ValidateSize 같이 메소드명을 주는게 좋을 것 같네요 ㅎㅎ

2023-03-04 04:48 UTC, carsago commented on src/main/java/domain/Value.java
> +public enum Value {
위와 마찬가지로 동의합니다!

2023-03-04 04:53 UTC, carsago commented on src/main/java/application/BlackJackApplication.java
> +public class BlackJackApplication {
이 클래스에게 ```Controller```라는 명칭을 주는 것이 어색하다고 여겼어요.  왜냐하면

1. 이 클래스는 run이라는 public 메소드를 한 번 호출함으로써 블랙잭 게임의 모든 로직을  진행해요. 여러개의 public 메소드를 가지고 호출되는 형태가 아니라서 Controller가 어색하다고 여겨졌어요.

2. Controller가 뷰나 다른 로직과 엮여있는 부분이긴 하지만 제가 이번 미션에서 사용한 ```BlackJackApplication``` 직접적으로 View Class를 주입받고, 그 객체들의 메소드들을 내부에서 호출하는 형태인데 이걸 Controller라 보기 조금 어색한 면도 있다고 판단했습니다.

위 2가지 이유로 전 ```BlackJackApplication이라는 명칭이 BlackJackController보다 자연스럽다고 여겼습니다.```

2023-03-04 05:31 UTC, carsago commented on src/main/java/domain/CardDeck.java
> +    }
```상수 이용 관점에서 더 코드 읽기가 좋아보입니다 ``` 라는 말씀을 풀어서 설명해주실 수 있을까요?

전 우선 사이즈를 체크하는 로직이, 중복 체크를 하는 로직 보다 더 간단하다고 판단해서 사이즈 체크 검증을 위에 두었는데, 말씀하신 뜻을 정확하게 파악못하겠어요 ㅠㅠ

2023-03-04 05:31 UTC, carsago commented on src/main/java/domain/DrawCommand.java
> +
맞아요 이 부분은 도메인이라 보기 어려울 것 같네요

2023-03-04 07:00 UTC, carsago commented on src/main/java/view/InputView.java
> +}
ㅋㅋㅋ 페어가 고수라서 잔재주를 부렸습니다

2023-03-04 07:01 UTC, carsago commented on src/main/java/service/BlackJackService.java
> +    private static final int DEALER_DRAW_LIMIT_SCORE = 16;
이런 식으로 책임 분리에 힌트를 앞으로도 생각해볼 수 있을것같네요~

2023-03-04 07:32 UTC, carsago commented on src/main/java/dto/DrawnCardsInfo.java
> +    }
현재는 정적 팩토리 메소드를 통해서만 객체를 생성하는데 기본 생성자를 public으로 열어두면 코드를 읽어주는 사람들에게 혼란을 줄 수 있을 것이라 판단했습니다.

구체적으로, ```이 객체는 어떨 때 생성자를 통해 생성하고, 어떨 때 정적 팩토리 메소드를 생성하는거지?```라는 의문을요.

만약 로직상 생성자로 생성 해야 할 이유가 있다면 그렇게 했었으나, 그렇지 않아서 닫아놓았어요.

물론 로직이 들어간 정적 팩토리 메소드 때문에 테스트가 어려워질 수도 있지만(이 경우는 DTO이지만) 만약 그렇다면 생성자를 public으로 여는 것이 아니라 객체 생성의 책임을 분리하는 식으로 고민을 할 것 같아요!

물론 이건 제 의견이고 사람마다 다 생각은 다를거라고 생각해요!!, 제이온이 생각하시기에 이런 경우 생성자를 여는 것은 어떤 장점이 있을까요?

2023-03-04 08:14 UTC, carsago commented on src/main/java/service/BlackJackService.java
> +public class BlackJackService {
사실 이 객체의 명칭은 BlackJackGame이라고 하고, 패키지는 domain으로, 인스턴스 변수를 Dealer, Players, CardDeck로 가지고 싶었습니다.

다만 그렇게 하지 않은점은 ```3개 이상의 인스턴스 변수를 사용하지 않는다.```라는 요구 사항을 지키기 위해서였습니다.
(물론 CardDeck을 static 클래스로 활용하거나, Player와 Dealer를 묶어서 Participants로 활용하는 방법도 있었지만, 오직 요구사항을 위해 안좋은 방법을 택하는 것 같아서 하지않았어요.)

그때문에 Service라는 명칭을 사용하고, 파라미터로 도메인 객체들을 받아서 로직을 실행한건데, 결국 이 방법도 어색함이 있다고 느껴져요.

돌아와서 이 객체의 역할은 도메인 객체들을 알고, 이를 바탕으로 로직을 실행하여 Dto로 넘겨주는 역할을 하고있어요.

또한 view에 대한 의존을 없애기 위해서, dto의 정적 팩토리 메소드에 인자로 넘겨줘서 이를 메소드 내부에서 실행했고요.

이 객체가 내부에  Dealer, Players, CardDeck를 가지고 있었다면 이러한 역할도 덜 어색하게 느껴졌을 것 같네요

그리고 BlackJackApplication은 진행 순서에 따라 적절한 메소드를 출력하는 역할만을 담당하고 싶었어요.

2023-03-04 08:22 UTC, carsago commented on src/main/java/service/BlackJackService.java
> +        cardInfos.add(DrawnCardsInfo.toDto(dealer));
위의 대답으로 갈음할게요!

2023-03-05 04:34 UTC, carsago commented on src/main/java/domain/Dealer.java
> +        return Collections.unmodifiableList(openCards);
반환한 리스트의 값을 변경시키지 않기 위해서  UnmodifiableList를 사용했지만 ```그럼에도 리스트 내부가 변경될 때 예외까지 던지는게 맞을까?```  라는 의문을 가져볼 수 있을 것 같아요. "예외는 예외상황에서만 사용하라" 라는 말도 있으니까요.

하지만 전 요구사항을 생각하면 ```openDrawnCards()``` 메소드를 통해 반환된 리스트가 변경된다면 충분히 예외적인 상황이라고 여겨져요.  메소드 내부의 로직에서 반환 해야하는 완벽한 형태를 만들었기 때문에 반환된 값을 절대로 변경되면 안돼요.  굳이 이런 처리 없이 API를 사용하는 사람을 믿는 방법도 있지만, 예외적인 상황을 열어둘 필요는 없을 것 같다고 판단했습니다.

하지만 도메인 요구사항에 따른 메소드가 아니라 getter 메소드라면?, view에 출력할 때 어떤 이유에서든지 변경할 이유가 생길 수가 있다면? .. 이런 경우에 기계적으로 UnmodifiableList로 반환하여 UnsupportedOperationException가 발생할 수 있는 상황을 만들어 놓는게 맞을까? 라는 생각을 해볼 수 있을 것 같아요.

제가 생각못한 제이온이 경험한, 혹은 생각하는 문제점이 또 있을까요?

2023-03-05 07:30 UTC, carsago commented on src/main/java/dto/ParticipantResult.java
> +    }
맞습니다 이 이부분은 치명적인 실수였네요 ㅠㅠ

이게 메소드가 단순히 값을 리턴 해주는 로직이라 그렇지, 객체의 상태를 변경시키는 메소드였다면 생각지도 못한곳에서 사이드 이펙트가 날 수 도 있었을거에요. 특히 DTO에서 난다면 더 찾기 어려울 것이고요..

2023-03-05 07:39 UTC, carsago commented on src/main/java/view/OutputView.java
> +        System.out.println(NEW_LINE + "딜러는 16이하라 한장의 카드를 더 받았습니다.");
이 부분은 해결하기가 참 어렵네요.

본래 존재하지 않던 getter를 통해서 파라미터로 16(혹은 변경될 수도 있는)값을 받는건 view에 domain이 의존하는 꼴이라 부정적이고

그렇다고 private한 상수를 public으로 변경해서 사용하는 것도  마찬가지라고  느껴지네요

요구사항의 변경에 따라 view에서 출력해야하는 값이 달라지는건 이번 미션뿐만 아니라 다른 온라인 게임등에도 존재하는 문제일텐데.. 

별도의 상수를 관리하는 클래스를 활용하는 것이 최선일까요? 다만, 관련된 상수를 활용하는 객체 내부이 상수를 정의하고 싶어서 썩내키진 않습니다..

2023-03-05 07:44 UTC, carsago commented on src/main/java/application/BlackJackApplication.java
> +    }
이 부분에서 재귀를 통해 무한 호출하는 식으로 재시도하고싶진 않았어요.

가능하면 while 문이나 for문을 활용하고 지정된 tryCount를 넘어선 5번 ~ 10번 정도의 재시도를 요청한다면 아예 application이 종료되는 식으로 만들고 싶었지만..! 그렇게하면 depth를 지킬 수가 없더라고요.

2023-03-05 07:47 UTC, carsago commented
아무래도 최초 PR은 허겁지겁 하다보니 문제가 있는걸 알면서도 수정하지 못한 부분들과, 나도 모르게 문제가 있는 로직을 작성한 부분이 많았습니다. 그런 부분에 대한 리팩토링이 우선적이였고요. 

제이온이 언급해주신대로 좀 더 도메인 객체의 행위로 옮길 수 있는 부분들이 많아서 그런 부분들에 대한 수정, 최대한 domain과 view의 분리를 하였습니다. 

구조나 가독성 면에서 요구사항을 억지로 지키다보니 조금 마음에 안드는 부분도 있었는데.. 그냥 그래도 지키는 방향으로 완전 수정했습니다.!

그리고 패키지 분리가 필요해서 이걸 바꿨는데.. 제이온이 보기에는 더 어렵게 된 것 같아요 ㅠ 죄송합니다.

2023-03-05 16:20 UTC, pjy1368 requested changes
안녕하세요 오리!
전반적으로 피드백을 잘 반영해 주시고 자신의 의견을 조리 있게 전달해 주시는 점이 인상 깊었습니다 👍 기존보다 더욱 객체지향적인 코드로 개선되었고 저 또한 생각할 수 있는 질문들이었어서 좋았습니다 ㅎㅎ
몇 가지 코멘트 더 남겨두었는데 수정해 보시고 궁금하신 점 있으면 또 질문주세요!

2023-03-05 16:20 UTC, pjy1368 commented on src/main/java/domain/BlackJackGame.java
> +                                           final CardDeck cardDeck) {
이 외에도 Dealer, Players, CardDeck를 사용하는 메서드들이 종종 보이는데, 일단 인스턴스 필드로 빼서 작성해 보면 어떨까 합니다!

2023-03-05 16:20 UTC, pjy1368 commented on src/main/java/domain/card/CardValue.java
> +    private int extraScore;
final로 두고 ACE 외에 나머지 열거형 상수는 기본 score랑 같게 채워 주면 어떨까요?
지금은 그렇지 않지만 ACE 외에 나머지 열거형 상수를 사용하고, extraScore를 쓰려고 하면 널포인터가 발생할 것 같습니다!

2023-03-05 16:20 UTC, pjy1368 commented on src/main/java/domain/participant/Player.java
> +
요기 엔터가 한 번 더 들어갔네요 ㅎㅎ

2023-03-05 16:20 UTC, pjy1368 commented on src/main/java/domain/card/CardDeckGenerator.java
> +    }
여기와 ParticipantGenerator의 create 테스트 케이스는 없는데 의도하신걸까요?

2023-03-05 16:20 UTC, pjy1368 commented on src/main/java/domain/participant/Name.java
> +        return name.length() > 10;
10도 매직 넘버로 볼 수 있지 않을까요??

2023-03-06 07:35 UTC, carsago commented on src/main/java/domain/card/CardValue.java
> +    private int extraScore;
그렇네요. 치명적인 에러를 피할 수 있을 것 같아요!

2023-03-06 11:34 UTC, carsago commented on src/main/java/application/DrawCommand.java
> +    DRAW("y"),
이 클래스를 BlackJackApplication의 inner class로 넣는 것을 고려했는데요.

그런데 application 클래스가 너무 비대해져서 아예 분리하는 방향으로 택했습니다.

2023-03-06 11:43 UTC, carsago commented
안녕하세요 제이온 !

말씀해주신 내용들을 바탕으로 리팩터링을 한 부분이 많았습니다. 테스트에 관한 질문도 하나 덧붙였구요 !

그리고 BlackJackGame에선 도메인 관련된 부분만 처리하고, BlackJackApplication에서 DTO를 변환하는게 어떠냐고 말씀하셨는데,

전 BlackJackGame에서 하는걸로 택했습니다. Service class를 염두해둔건 아니지만, 그런 유사한 역할을 해도 괜찮다고 생각했고,

구조적으로도 그렇게 하는게 자연스럽다고 느꼈어요.

구체적으로, BlackJackGame 특정 메소드를 실행한뒤에 Apllication에서 DTO를 만들어내는것보다, View에 던져줄 DTO를 BlackJackGame의 return 타입으로 넘겨주는게 더 자연스럽게 느껴졌어요.  이정도는 하나의 동작이라고 파악했고, 이게 분리되면 Application에서 메소드 순서가 조금만 잘못돼도 문제를 파악하기가 어려워질 것 같았어요.

또한 BlackJackGame이 여러값을 넘겨줘야 한다면 DTO를 안쓸때,  Map이나 List등의 값을 매핑해서 넘겨줘야할텐데, 이러한 로직은 return type이 DTO가 아닐 뿐이지 View에 의존하는거나 다름없다고 느꼈습니다 !!

2023-03-06 11:45 UTC, carsago commented on src/main/java/domain/card/CardDeckGenerator.java
> +    }
TDD를 최대한 했지만 이 부분은 Application에서 하던 역할로 처음에 만들고 이걸 분리하다보니 테스트가 빠졌네요 ㅠ

2023-03-06 12:03 UTC, carsago commented on src/main/java/domain/participant/Player.java
> +    public boolean isDrawable() {
이 부분도 여쭤보고 싶었어요!

```전 public 메소드가 private 메소드가 아닌 내부의 다른 public 메소드를 호출하는게 너무 부자연스럽게 느껴졌습니다.```

다른 객체가 이 public 메소드를 활용하여(협력하여) 로직을 진행하는게 자연스러운거 아닌가..? 라는 생각이 들더라고요.

최초 PR에서 도메인 객체에 책임 분리가 잘 안됐다고 느껴질만한 코드를 짠거엔 이러한 이유도 있었습니다.

```물론 public 메소드가 내부의 다른 public 메소드를 호출하는게 안되나요? 라고 여쭤보면 잘 모르겠어요.``` 아직 객체간의 책임 분리에 대해선 저  나름의 기준이 많이 정립되지 않은 상태라 이것 저것 생각 해보는 중이고, 이게 조금 의심스럽게 느껴졌거든요.

내부를 조금 리팩터링하면 이러한 부분을 해결할 수 있을 것 같긴한데, 제이온이 보시기엔 이런 부분은 책임과 역할 분리가 어색하다고 느껴지시나요?

2023-03-06 12:04 UTC, carsago commented on src/main/java/domain/participant/Player.java
> +    }
이 부분도 여쭤보고 싶었어요!

전 public 메소드가 private 메소드가 아닌 내부의 다른 public 메소드를 호출하는게 너무 부자연스럽게 느껴졌습니다.

다른 객체가 이 public 메소드를 활용하여(협력하여) 로직을 진행하는게 자연스러운거 아닌가..? 라는 생각이 들더라고요.

최초 PR에서 도메인 객체에 책임 분리가 잘 안됐다고 느껴질만한 코드를 짠거엔 이러한 이유도 있었습니다.

물론 public 메소드가 내부의 다른 public 메소드를 호출하는게 안되나요? 라고 여쭤보면 잘 모르겠어요. 아직 객체간의 책임 분리에 대해선 저 나름의 기준이 많이 정립되지 않은 상태라 이것 저것 생각 해보는 중이고, 이게 조금 의심스럽게 느껴졌거든요.

내부를 조금 리팩터링하면 이러한 부분을 해결할 수 있을 것 같긴한데, 제이온이 보시기엔 이런 부분은 책임과 역할 분리가 어색하다고 느껴지시나요?

2023-03-07 14:41 UTC, pjy1368 approved these changes
안녕하세요 오리!
깊게 고민하신 흔적이 보이며 그만큼 더 나은 코드로 잘 수정해주신 것 같습니다 👍
나머지는 이번 단계에서 선택적으로 반영해 보시거나 2단계 구현해 보시면서 생각해보시면 도움이 될 듯 합니다. 이만 머지할게요~

2023-03-07 14:41 UTC, merged