[1단계 - 블랙잭 게임 실행] 이리내(성채연) 미션 제출합니다.
woowacourse/java-blackjack pull request #445
Opened 2023-03-03 08:34 UTC by hectick

시간이 너무 촉박해서 일단 돌아가는 상태로 제출합니다...
리팩토링이 많이 필요한 코드입니다..

## 질문 사항
현재 코드에선 `dealer`와 `player`가 추상클래스인 `state`를 가지고 있습니다. 이 `state`가 `dealer`와 `player`의 행동마다 `state`의 구현체를 변경하는 구조로 만들고자 했습니다. (행동은 예를 들면 카드 뽑기, 처음부터 21인 카드 뽑기, `y`나 `n`을 입력해 카드 그만 뽑기) 하지만 최종 승패를 판단하려는 과정에서 `isBust`, `isBlackjack`등의 메소드가 불필요하게 많아진 것  같습니다. 승패를 판단할 때, 참여자들의 정확한 상태를 알아야만 할 것 같아 이렇게 되었는데 다른 방법이 있을까요?

또, `player`가 입력된 `y`나 `n`에 따라 다시 카드를 뽑거나 뽑지않는 상황이 존재하기에, 입력값에 따라 `player`들의 동작을 다르게 해줘야 해서 `player`들을 `players`로 포장하지 못하고 바로 `controller`에서 `player`가 동작을 하면서 `controller`가 비대해진것 같습니다. 이럴 경우에 다른 좋은 방법을 아직까진 잘 모르겠습니다.

아니면 이렇게 `state`를 사용한 방법이 이러한 상황에는 어울리지 않는 설계인 건가요?

2023-03-03 13:15 UTC, toneyparky requested changes
안녕하세요 이리내~ 토니입니다!

작성해주신 코드 가볍게 확인하여 리뷰 남겼어요. 개선하면 좋을 부분에 대해서 이리내도 고민하고 추가적으로 개선해주시면 좋겠네요. 질문에 대한 답변은 추후에 추가로 달도록하겠습니다. 

주말 잘 보내세요~!

2023-03-03 13:15 UTC, toneyparky commented on src/main/java/blackjack/controller/GameController.java
> +                }
해당 클래스 전체적으로 중첩되는 if문이 존재하는군요~

코드를 읽는 이가 이해하기 쉽도록 개선할 수 있을까요?

2023-03-03 13:15 UTC, toneyparky commented on src/main/java/blackjack/model/card/CardScore.java
> +}
파일의 가장 마지막 줄은 빈 라인으로 끝나는 게 좋아요. 왜 그런지에 대한 이유를 확인하고 답변 남겨주시면 좋겠네요~!
아래와 같이 깃헙에서도 경고 문자를 보여준답니다~

<img width="102" alt="image" src="https://user-images.githubusercontent.com/37579660/222728488-d067e58d-b413-4a34-957b-ffca9361319b.png">

2023-03-03 13:15 UTC, toneyparky commented on src/main/java/blackjack/model/participant/Participant.java
> +        if (isBust() || cardScore().bigScore() > 21) {
21은 어떤 의미에요?

2023-03-03 13:15 UTC, toneyparky commented on src/main/java/blackjack/model/state/DrawState.java
> +        if (hand.score().smallScore() > BLACKJACK_NUMBER && hand.score().bigScore() > BLACKJACK_NUMBER) {
해당 if문의 내용은 >나 &&와 같은 내용을 해석해야 이해할 수 있네요..! 보다 읽는 사람이 쉽게 이해할 수 있도록 수정해볼 수 있을까요?

2023-03-03 13:15 UTC, toneyparky commented on src/test/java/blackjack/model/participant/PlayerTest.java
> +}
해당 부분에 공백이 있는 경우와 없는 경우가 있네요. 하나의 컨벤션으로 통일하면 좋겠어요.

2023-03-03 17:58 UTC, hectick commented on src/main/java/blackjack/model/state/DrawState.java
> +        if (hand.score().smallScore() > BLACKJACK_NUMBER && hand.score().bigScore() > BLACKJACK_NUMBER) {
조건문으로 분리하였습니다!

2023-03-03 17:58 UTC, hectick commented on src/main/java/blackjack/model/participant/Participant.java
> +        if (isBust() || cardScore().bigScore() > 21) {
상수로 뺐습니다!

2023-03-03 18:15 UTC, hectick commented on src/main/java/blackjack/model/card/CardScore.java
> +}
이전에도 리뷰 받았던 내용인데 미처 확인하지 못했네요😂
구글링을 해봤을땐 POSIX 표준때문 이라고는 하지만, 아직 그게 뭔지는 잘 모르겠고, 마지막에 줄바꿈을 안해주면 의도치 않은 에러나 충돌이 발생할수 있다...? 정도로만 이해하고 있습니다!

2023-03-05 06:41 UTC, toneyparky requested changes
안녕하세요 이리내~ 토니입니다! 

확실히 리팩터링 이후에는 코드가 눈에 더 잘 들어오네요! 고생하셨어요. 본격적으로 리뷰를 남기고 질문에 답변달았으니 확인 및 답변 남겨주세요 😬

남은 주말 푹 쉬시구요~! DM은 편하게 부탁드립니다!

2023-03-05 06:41 UTC, toneyparky commented on src/main/java/blackjack/controller/GameController.java
> +    private Participants initializedParticipants() {
동사의 과거형이 올바른 의미를 표현한걸까요? 해당 동사는 실제로 참가자를 초기화하는 행위를 하는걸로 보여서요. 혹은 과거분사로 사용하여 명사를 꾸며주신걸까요? 그렇다면 메서드는 동사로 시작하는 자바의 컨벤션을 따르도록 수정하면 좋겠네요~!

2023-03-05 06:41 UTC, toneyparky commented on src/main/java/blackjack/controller/GameController.java
> +    private Map<String, List<String>> dealerNameAndHand(Dealer dealer) {
컨트롤러의 메서드가 전체적으로 명사로 시작하는 경향이 있네요. 위에서 코멘트 남겼듯 동사로 시작하면 읽는 사람이 더 쉽게 파악할 수 있을 것 같아요. 혹시 이리내가 이렇게 명사로 시작하도록 네이밍하신 이유가 있으신가요~?

2023-03-05 06:41 UTC, toneyparky commented on src/main/java/blackjack/controller/GameController.java
> +    private void hitOrStand(CardDeck cardDeck, Participants participants) {
남겨주신 질문에 대해 이야기해보죠~ 

> 또, player가 입력된 y나 n에 따라 다시 카드를 뽑거나 뽑지않는 상황이 존재하기에, 입력값에 따라 player들의 동작을 다르게 해줘야 해서 player들을 players로 포장하지 못하고 바로 controller에서 player가 동작을 하면서 controller가 비대해진것 같습니다. 이럴 경우에 다른 좋은 방법을 아직까진 잘 모르겠습니다.

카드를 더 받을지에 대해 판단하는 부분은 View 레이어의 도움이 필요하기에 컨트롤러와 도메인이 연결될 수 밖에 없어요. 그렇기에 컨트롤러가 비대해졌네요. 이를 해소하기 위해서는 컨트롤러가 현재 가지는 책임이 무엇인지를 판단해볼 필요가 있어요. 단순히 뷰와 모델 레이어를 엮어주는 역할을 하는가 이외의 로직이 수행되는가. 

지금은 엮어주는 역할을 수행하고 있다고 보여지네요. 다만 객체를 원시 값으로 변환하거나 우승과 관련된 결과 로직(`printWinningResult`)이 조금 포함되어 있지만요. 우승 결과 로직을 담당할 도메인 객체를 만들거나 변환을 담당할 DTO 객체를 만들어서 변환 로직을 숨기고 컨트롤러를 깔끔하게 만들 수 있을거 같네요.

2023-03-05 06:41 UTC, toneyparky commented on src/main/java/blackjack/model/card/Card.java
> +    public static Card of(CardSuit suit, CardNumber number) {
of가 호출되기 전에는 카드를 굳이 생성하지 않고, 호출되었을 때에는 캐싱을 하는 효율적인 코드라고 생각해요 👍 

다만 블랙잭 게임이라는 도메인의 특성상 어차피 모든 카드를 사용하거나 만들어두고 있으니 미리 다 생성해놔도 무방할거 같긴하네요~!

2023-03-05 06:41 UTC, toneyparky commented on src/main/java/blackjack/model/card/CardNumber.java
> +    ACE("A", 1, 11),
ACE에 대한 요구사항을 해결하기 위해 bigScore, smallScore라는 개념이 나왔군요~! 

여러가지 방법을 생각해보셨을텐데 지금처럼 결정하신 이유가 궁금합니다 😬

2023-03-05 06:41 UTC, toneyparky commented on src/main/java/blackjack/model/result/ResultChecker.java
> +public class ResultChecker {
해당 행위를 `Result`에서 하지 않고 따로 객체를 만드신 이유가 궁금합니다~!

2023-03-05 06:41 UTC, toneyparky commented on src/main/java/blackjack/model/result/ResultChecker.java
> +    public boolean isPlayerTie(Player player, Dealer dealer) {
사용하지 않는 메서드가 있네요!

2023-03-05 06:41 UTC, toneyparky commented on src/main/java/blackjack/model/state/DealerDrawState.java
> +    public State checkStandOrBustState(){
check라기에는 실제로 상태를 변형시키기까지 하네요.

2023-03-05 06:41 UTC, toneyparky commented on src/main/java/blackjack/model/participant/Dealer.java
> +    public Card getFirstCard(){
```suggestion
    public Card getFirstCard() {
```
포매팅이 잘못 되어 있네요. 위의 형 변환도 마찬가지입니다.

`this.currentState = ((DealerDrawState) currentState).checkStandOrBustState();`

2023-03-05 06:41 UTC, toneyparky commented on src/main/java/blackjack/model/state/State.java
> +    public abstract boolean isBust();
남겨주신 질문에 대해 이야기해봐요:

> 현재 코드에선 dealer와 player가 추상클래스인 state를 가지고 있습니다. 이 state가 dealer와 player의 행동마다 state의 구현체를 변경하는 구조로 만들고자 했습니다. (행동은 예를 들면 카드 뽑기, 처음부터 21인 카드 뽑기, y나 n을 입력해 카드 그만 뽑기) 하지만 최종 승패를 판단하려는 과정에서 isBust, isBlackjack등의 메소드가 불필요하게 많아진 것 같습니다. 승패를 판단할 때, 참여자들의 정확한 상태를 알아야만 할 것 같아 이렇게 되었는데 다른 방법이 있을까요?

`isBust`, `isBlackjack`과 같은 메서드가 상태와 직접적으로 연관되지 않는다고 판단하셨군요? 결국 이런 상태에 도달하려면 `Hand` 객체의 도움을 받아야하니까요. 그렇다면 `getHand` 노출한 Hand 객체가 점수를 계산하여 블랙잭인지 버스트인지 판단하도록 하면 어때요? 우려하시는 상태에서 불필요하게 추상 메서드로 노출하는 상황이 해소되지 않을까 싶어요.

2023-03-05 06:41 UTC, toneyparky commented on src/main/java/blackjack/model/state/DrawState.java
> +    public State turnStandState() {
보통 상태 패턴에서 상태가 바뀔 때에는 `전이`한다는 표현을 많이 사용해요. 영어로는 `transit`으로 주로 사용하는듯합니다. 

이런 경우에 `transitToStandState()` 정도면 동료 개발자가 쉽게 이해할 수 있을거에요.

2023-03-05 06:41 UTC, toneyparky commented on src/main/java/blackjack/view/OutputView.java
> +    }
일종의 싱글턴 패턴을 사용하셨군요~ 좋네요!

2023-03-05 06:41 UTC, toneyparky commented on src/main/java/blackjack/model/result/ResultChecker.java
> +    public boolean isPlayerWin(Player player, Dealer dealer) {
이 객체의 로직은 블랙잭 게임의 핵심적인 부분이라 생각해요. 그렇지만 테스트가 빠져있네요. 전반적으로 테스트를 추가해봅시다!

2023-03-05 06:41 UTC, toneyparky commented on src/main/java/blackjack/model/participant/Participants.java
> +    public Participants(Dealer dealer, List<Player> players) {
해당 클래스에 대한 테스트를 추가해주시면 프로젝트가 보다 탄탄해질거에요!

2023-03-06 14:38 UTC, hectick commented on src/main/java/blackjack/controller/GameController.java
> +    private Map<String, List<String>> dealerNameAndHand(Dealer dealer) {
그 동안 저는 무의식적으로 메소드명을 동사로 지어왔었는데, 이번 페어가 `조회`와 `동작`을 구분하기 위해서 조회를 위한 메소드는 명사로 짓고, 동작을 위한 메소드는 동사로 짓는다고 하더라고요! 이런 확고한 기준이 있는게 신기해서 저도 한번 이렇게 써보았습니다! 그런데 메소드가 동사로 시작한다는 자바의 컨벤션이 있었다는걸 완전 망각하고 있었네요 수정하도록 하겠습니다..😂

2023-03-06 14:40 UTC, hectick commented on src/main/java/blackjack/controller/GameController.java
> +    private Map<String, List<String>> dealerNameAndHand(Dealer dealer) {
그런데 사이즈를 가져오는 메소드 같은 경우에는 size() 이런식으로 많이들 작명 하시던데, getSize() 이렇게 하는게 아니라 size()로 하는 이유가 있나요? 관습적으로 써왔던 것은 명사형으로 그대로 쓰는 걸까요?

2023-03-06 14:58 UTC, hectick commented on src/main/java/blackjack/model/result/ResultChecker.java
> +    public boolean isPlayerTie(Player player, Dealer dealer) {
사용하지 않긴 합니다만, `ResultChecker` 클래스에서 `플레이어가 이기는 상황`, `플레이어가 비기는 상황`, `플레이어가 지는 상황`을 각각 케이스를 적어두고 싶어서 메소드를 살렸습니다. 이부분에 대한 설명을 따로 readme에 빼고 메소드를 지우는게 좋을까요?

2023-03-06 15:05 UTC, hectick commented on src/main/java/blackjack/model/state/DrawState.java
> +    public State turnStandState() {
뭘로 시작해야할지 고민을 하다가 포기했었는데 의견제시 감사합니다!!

2023-03-06 15:07 UTC, hectick commented on src/main/java/blackjack/model/state/DealerDrawState.java
> +    public State checkStandOrBustState(){
아래의 의견을 참고해서 `transitStateOrNot`으로 바꿔봤는데 메소드 이름이 좀 포괄적인가요?

2023-03-07 03:01 UTC, hectick commented on src/main/java/blackjack/model/result/ResultChecker.java
> +public class ResultChecker {
그러게요, Result에서 하면 되네요..

2023-03-07 03:15 UTC, hectick commented on src/main/java/blackjack/model/card/CardNumber.java
> +    ACE("A", 1, 11),
1. ACE("A", 1) 이렇게 쓰고 외부에서 11이 필요할때 바꿔주는 방법
2. ACE("A", List.of(1,11))
3. ACE("A", 1, 11)
이렇게 세개를 생각해 봤는데요,

2023-03-07 06:42 UTC, hectick commented on src/main/java/blackjack/model/card/CardNumber.java
> +    ACE("A", 1, 11),
아무래도 3번이나 2번이 카드와 관련되어 있는 점수들을 한번에 보기에 좋고, 2번의 경우에는 2~10까지는 불필요하게 List에 하나밖에 없는 원소를 매번 get을 해와야 할 것 같아서 3번을 선택하였습니다. 그런데 생각해보니 ACE카드가 두장인 경우에는 11+11 -> 11+1 -> 1+1 이 순으로 최적화가 되어야 할 것 같은데, 지금 상황에서는 11+1로 계산이 안되서수정해야 할 것 같네요..😂😂

2023-03-07 08:16 UTC, hectick commented on src/main/java/blackjack/model/state/State.java
> +    public abstract boolean isBust();
Hand 객체가 점수를 계산하도록 하고 State에서 불필요한 추상 메소드를 제거하였습니다!
위의 bigScore, smallScore을 삭제하고 다른 방식으로 점수 계산 방법도 변경하면서 코드의 엄청난 수정이 있었네요..

2023-03-07 08:44 UTC, hectick commented
안녕하세요 토니!! 말씀해주신 피드백 반영하고 리팩터링해서 제출합니다~!
크게 변경된 부분은 다음과 같습니다.

## ResultChecker 삭제
`ResultChecker`에 있던 부분은 `Result`로 이동시키고 `ResultChecker`는 삭제하였습니다. 

## 카드 점수 계산 방법 수정
기존에는 `smallScore`끼리 합한 것과 `bigScore`끼리 합한 것을 계산하여 둘을 비교해 최적의 결과를 내고자 하였으나, `Ace`카드 두장만을 가지고 있을 경우 `11+1`로 계산할 수 없다는 치명적인 단점이 존재하여, `Ace` 카드를 기본으로 1로 계산하되, 보너스 스코어인 10을 더하였을때 `Bust`가 되지 않는 경우에만 `10`을 추가적으로 더하도록 변경하였습니다. 이 메소드는 `Hand` 클래스의 `getScore`입니다. 덤으로 CardScore 클래스도 삭제하였습니다.

## 불필요한 추상메소드 삭제
[여기](https://github.com/woowacourse/java-blackjack/pull/445#discussion_r1125605366)에서 코멘트 해주신 대로 `isBlackjack()`, `isStand()`, `isBust()` 메소드를 `State`에서 지우고, 이 판단을 `Hand`에서 하고자 하였습니다. 다만 `Player`는 `State`를 통해서만 `Hand`에 접근할 수 있기 때문에 `State` 내에서 `isBlackjack()`을 쓰지 않으려면 `Player`가 `State`에서 `Hand`를 `getHand`로 가져와서 상태를 판단해야 했습니다. 그래서 `FinishedState` 라는 `enum`을 만들어서 여기에 `Hand`를 넘겨서 블랙잭/버스트/스탠드를 판단하도록 변경했습니다.

## dto 추가
`ParticipantDto`와 `ResultDto`를 추가하였습니다.

2023-03-07 11:00 UTC, toneyparky commented on src/main/java/blackjack/model/participant/Participant.java
> +    }
질문 주신 부분 이야기해봐요 ~

> 원시값을 포장하다보니 player.getName().getName() 이런식으로 전자의 getName()에서는 Name 객체가 반환되고, 후자의 getName()에서는 String이 반환되는데, 중복된 메소드명을 사용한다는게 깔끔해보이지 않습니다. 좋은 해결방법이 있을까요?

이리내는 원시값을 포장하는 목적이 뭐라고 생각하세요? 포장하는 목적을 이뤘다면 게터에서는 객체가 아닌 원시값으로 넘겨줘도 될 것 같아서요 😀

2023-03-07 11:00 UTC, toneyparky commented on README.md
> +- [ ] 비대해진 컨트롤러
이정도면 많이 줄어들었다 생각하는데 체크해도 괜찮을까요~?

2023-03-07 11:00 UTC, toneyparky commented on src/test/java/blackjack/model/participant/DealerTest.java
> +    @DisplayName("딜러는 점수가 16 초과이면 카드를 더 뽑지 못한다.")
더 뽑을 수 있는 상황/블랙잭 상황에 대해서는 테스트하지 않은 이유가 있으신가요~?

2023-03-07 11:00 UTC, toneyparky commented on src/test/java/blackjack/model/result/ResultTest.java
> +class ResultTest {
결과는 이보다 복잡한 경우의 수가 있을걸로 보여요. 

딜러와 플레이어가 블랙잭, 버스트가 아닐 경우 숫자만으로 비교하여 승패가 결정되는 경우. 한쪽이 블랙잭이거나 버스트인 경우, 혹은 둘 다 블랙잭이거나 버스트인 경우와 같이요.

해당 케이스를 세분화하여 테스트를 해주시면 좋겠어요.
이를 위해서는 DCI 패턴을 적용하면 보다 구조화된 테스트를 작성할 수 있을거에요 ([참고](https://johngrib.github.io/wiki/junit5-nested/))

예를들면 : 

```
플레이어가 버스트인 경우
  딜러가 버스트인 경우 
  딜러는 블랙잭인 경우 
  딜러는 일반 점수인 경우
플레이어가 블랙잭인 경우
  딜러가 버스트인 경우 
  딜러는 블랙잭인 경우 
  딜러는 일반 점수인 경우
플레이어가 일반 점수인 경우
  딜러가 버스트인 경우 
  딜러는 블랙잭인 경우 
  딜러는 일반 점수인 경우
```

이런식으로 구조화할 수 있답니다~

2023-03-07 11:00 UTC, toneyparky commented on src/main/java/blackjack/model/card/CardScore.java
> +}
굳굳~ 맞습니다. 혹여나 있을 문제를 대비하기 위해 꼭 추가해두도록해요. 인텔리제이 설정으로 자동화해두면 더 좋겠죠?

2023-03-07 11:00 UTC, toneyparky commented on src/main/java/blackjack/controller/GameController.java
> +    private void hitOrStand(CardDeck cardDeck, Participants participants) {
네 잘 리팩터링해주셨어요~! 컨트롤러가 기존 131줄에서 92줄까지 줄어들었네요 💯 

MVC에서 컨트롤러 레이어는 M과 V를 연결해주는 역할을 하고 현재 구조에서 DTO는 컨트롤러 레이어에 속하기에 해당 책임을 충분히 가질 수 있다고 생각합니다.

2023-03-07 11:00 UTC, toneyparky commented on src/main/java/blackjack/model/card/CardNumber.java
> +    ACE("A", 1, 11),
기존 방법의 애로사항이 발견되었군요..! 수정하신 부분 감안하여 확인하도록 할게요. 고민을 깊게 하신 덕에 발견하셨네요 👍

2023-03-07 11:00 UTC, toneyparky commented on src/main/java/blackjack/model/state/State.java
> +    public abstract boolean isBust();
고생하셨습니다..! 커밋을 보는데 변경량이 많네요 😭😭

남겨주신 내용에 대해서 더 이야기해보죠!

> getter로 hand를 가져와서 사용하는 것

이건 트레이드-오프라고 생각해요. 추상 클래스에서 메서드를 노출하지 못하기에 행위를 할 객체 자체를 노출시킬 수 밖에 없겠죠?
우테코에서 배우길 게터를 사용하지 말라고 하지만 이는 게터를 오용하지 말자는 내용으로 이해하고 있어요. 게터로 인해 객체가 수동적으로 값을 제공하기만하는 경우를 의미해요. 

지금과 같은 경우는 State에서 Hand가 노출되어도 각 객체가 서로 능동적으로 행동하기에 충분히 괜찮다 생각합니다..!

2023-03-07 11:02 UTC, toneyparky approved these changes
안녕하세요 이리내~ 

우여곡절이 많은(?) 1단계였군요. 고생많으셨어요! 리뷰 드린 내용 잘 반영해주셨네요!
남겨주신 질문에 답변을 달았고 추가로 개선하면 좋을 부분에 대해서도 남겨봤어요. 
해당 부분은 2단계 시작할 때에 반영을 먼저 하시면 좋겠네요😀

이번 단계는 머지하도록 하겠습니다~~! 고생하셨어요!

2023-03-07 11:02 UTC, merged

2023-03-09 07:55 UTC, hectick commented on src/test/java/blackjack/model/result/ResultTest.java
> +class ResultTest {
오 구조화하니까 딜러와 플레이어가 둘다 스탠드고, 동점일 때 무승부로 처리하는 로직을 빠뜨렸단 걸 알았네요!!

2023-03-09 10:16 UTC, hectick commented on src/test/java/blackjack/model/participant/DealerTest.java
> +    @DisplayName("딜러는 점수가 16 초과이면 카드를 더 뽑지 못한다.")
딜러와 플레이어의 차이로는 딜러가 16 이하일때는 카드를 추가로 뽑아야 한다 말고는 없어서, 특수한 상황에 대한 테스트 코드만 작성했는데요, 아무래도 테스트가 빈약하다고 느끼셨던 거겠죠? 추가하도록 하겠습니다!

2023-03-10 02:50 UTC, hectick commented on src/main/java/blackjack/model/participant/Participant.java
> +    }
디미터의 법칙

2023-03-10 05:03 UTC, hectick commented on src/main/java/blackjack/model/participant/Participant.java
> +    }
값이 유효한지 검증하기 위한 것이라 생각합니다!
원시값으로 포장된 순간 검증이 완료된 것이니, 말씀해주신 대로 원시값으로 보내는 것이 디미터의 법칙을 위반하지도 않고 좋은 것 같네요!!
그동안 제가 너무 "포장"이라는 단어에 꽂혀 있던 것 같습니다..

2023-03-11 05:07 UTC, toneyparky commented on src/main/java/blackjack/model/participant/Participant.java
> +    }
> 원시값으로 포장된 순간 검증이 완료된 것이니, 

좋아요~ 객체가 생성될 때에 유효성 검증을 하는 게 포장의 의미라면 게터에서는 원시 값을 넘겨줘도 충분하겠죠! 다만 포장의 의미가 객체에 자율성을 부여하는 것 까지(객체에 메서드를 만들거나)확장되면 객체를 넘기는 것도 생각해야하구요.

2023-03-11 05:09 UTC, toneyparky commented on src/test/java/blackjack/model/participant/DealerTest.java
> +    @DisplayName("딜러는 점수가 16 초과이면 카드를 더 뽑지 못한다.")
네, 만일 이 프로젝트에 새로운 개발자가 합류해서 추가로 개발을 진행한다고 했을 경우 요구사항이 아무리 잘 정리 되어있다고해도 놓칠 수 있어요. 그럴 때를 대비하여 테스트 코드에도 해당 요구사항을 반영하는 편이 좋아요. 물론 테스트 코드도 완벽하지 않지만 실수할 `확률`을 줄여줄 수 있다고 생각합니다.