[1단계 - 블랙잭 게임 실행] 그레이(김동욱) 미션 제출합니다.
woowacourse/java-blackjack pull request #446
Opened 2023-03-03 08:34 UTC by Kim0914

안녕하세요, 바다 ! 
그레이입니다 😀 

이번 미션은 이전 미션들보다 생각하고 고민할 점이 많아 어려웠던 것 같습니다..!

미션을 진행하며 궁금했던 부분을 남겨보았습니다 !

감사합니다 😄

## 궁금한 점

1. TDD 개발 방식으로 커밋 진행 시 테스트 코드와 프로덕션 코드를 함께 커밋하는지, 나눠서 커밋하는지 궁금합니다. 어떤 방식으로 커밋을 남기는게 좋을지 페어와 의논한 결과, TDD를 학습하는 과정이기 때문에 테스트 코드와 프로덕션 코드를 나눠서 커밋했습니다. 다만 테스트 코드와 프로덕션 코드를 나눠서 커밋을 하다보니 **커밋 수가 너무 많아지는 것이 아닌가** 라는 고민이 들었습니다 !

2. 부모 클래스를 상속하는 자식 클래스에서 부모 클래스에 정의된 메서드에 대한 테스트를 진행해야하는지 궁금합니다. 현재 `Participant`라는 부모 클래스가 있고, 부모 클래스를 상속하는 `Dealer`와 `Player`가 존재합니다. 부모 클래스에 존재하는 메서드를 오버라이드하는 경우 자식 클래스에서 테스트를 진행하는 것은 당연하다고 생각합니다. 하지만 부모 클래스에 정의되어 있고, 별도로 오버라이드 하지 않는 메서드는 **부모 클래스를 생성해 테스트를 진행해야할지**, **자식 클래스에서 해당 테스트를 진행해야할지,** **부모-자식 클래스 둘 다 테스트를 진행해야하는지** 궁금합니다 !

3. 현재 애플리케이션에서 컨트롤러의 역할에 대해 의문점이 듭니다. 제가 생각하는 컨트롤러의 역할은 외부 요청에 응답하여 비즈니스 로직을 실행하고, 실행 결과를 응답으로 보내주는 것이라고 생각합니다. 하지만 현재 BlackJackController는 외부 요청(뷰)에 응답하여 애플리케이션의 흐름을 제어하는 것은 맞지만, **애플리케이션의 흐름을 제어하는 역할만**하고 있는 것 같습니다. 그래서 컨트롤러가 아닌 메인 애플리케이션에서 모든 로직을 수행해야하는 것은 아닐까? 라는 생각이 들었고, MVC 패턴을 사용하기 위해 큰 고민 없이 컨트롤러를 사용하는게 아닐까? 라는 생각도 드는 것 같습니다..!

2023-03-04 15:16 UTC, xrabcde requested changes
안녕하세요 그레이 ~ 바다입니다 🌊
블랙잭 미션을 함께 하게 되어 반갑습니다 ㅎㅎ
프로그램을 실행해보니 짧은 시간이었는데도 완성도 있게 구현해주셨네요 👍🏻
몇 가지 리뷰 남겼는데 확인해보시고 궁금한 점은 언제든 코멘트나 DM으로 알려주세요~
질문에 대한 답변 드릴게요 :)

> 1 . TDD 개발 방식과 커밋 단위

그레이가 커밋수가 많아지면 왜 안된다고 생각하시는지 궁금한데요..!
커밋수가 너무 적어서 문제가 되는 경우는 있지만 너무 많다고 문제가 되진 않는 것 같아요 ㅎㅎ
게다가, 말씀해주신대로 지금은 TDD를 학습하시는 과정이므로 더더욱 커밋수에 대한 걱정없이 커밋을 마음껏 하셔도 된다고 생각합니다 ~

> 2 . 상속 시 테스트 위치

테스트를 하시는 이유가 뭐라고 생각하시나요? 어디에 작성해야한다고 정해진 것은 없어요. 
테스트를 하려는 의도에만 잘 맞는다면 그레이가 작성하고 싶은 위치에 작성해주시면 된다고 생각합니다 ~

> 3 . 컨트롤러의 역할

현재 작성해주신 코드 중 BlackJackGame 은 어떤 역할을 한다고 생각하시나요? 
아래 코멘트에도 남겨두었지만 Controller와 Game의 역할을 다시 정리해보셔도 좋을 것 같아요 ~

2023-03-04 15:16 UTC, xrabcde commented on src/test/java/blackjack/domain/participant/PlayersTest.java
> +    void createPlayersWrongSize(List<String> inputNames) {
경곗값 테스트 💯

2023-03-06 07:14 UTC, Kim0914 commented on src/main/java/blackjack/controller/BlackJackController.java
> +    }
넵 !
반영하여 리팩토링 진행하겠습니다 :)

2023-03-06 07:26 UTC, Kim0914 commented on src/main/java/blackjack/controller/BlackJackController.java
> +            return players;
**현재와 같이 따로 사용되지 않을 값은 바로** `return Players.create(names)`**로 넘겨줘도 될 것 같군요** 😄

해당 코멘트를 보며 평소에 궁금했던 점이 레벨 1의 사다리 타기 미션을 진행하면서 
`Player player = new Player(inputView.readName())` 와 같이 라인 수를 줄이기 위해 메서드를 호출 하는 과정을 인자로 넘기는 것 보다, 
```java
String name = inputView.readName()
Player player = new Player(name)
```
입력 받은 값은 변수로 일단 받은 후, 해당 변수를 전달해 주는 방법이 보기 좋은 것 같다는 생각이 들어 해당 방식을 사용하고 있었습니다 !

저는 위 방식이 보기 편하다고 생각하는데 바다는 어떻게 생각하는지, 어떤 방식을 선호하는지 궁금합니다 ㅎㅎ

2023-03-06 07:29 UTC, Kim0914 commented on src/main/java/blackjack/domain/participant/Players.java
> +    public List<Player> getPlayers() {
미션 마무리를 급하게 한다고 놓친 부분이었던 것 같아요 😅

리팩토링 시 반영하겠습니당

2023-03-06 17:21 UTC, Kim0914 commented on src/main/java/blackjack/domain/card/Deck.java
> +    private final Stack<Card> cards;
평소에 전혀 인지하지 못하고 있었던 내용이네요...!!

참고하여 리팩토링 시 반영하겠습니다 ㅎㅎ

좋은 글 공유 감사드려요 !

2023-03-06 17:21 UTC, Kim0914 commented on src/main/java/blackjack/domain/participant/Dealer.java
> +        }
반영하겠습니다 !!

2023-03-06 17:25 UTC, Kim0914 commented on src/main/java/blackjack/controller/BlackJackController.java
> +    }
처음 설계할 당시에는 y와 n만 받아서 판단할 수 있다고 생각해서 컨트롤러에 구현했었습니다.

말씀해주신 것처럼 yes or no 자체가 true or false의 역할을 하고 있다고 생각이 드는 것 같아요 !!

결론적으로 yes or no 자체는 뷰 로직인 것 같습니다 !

2023-03-07 12:20 UTC, Kim0914 commented on src/main/java/blackjack/domain/card/Deck.java
> +    }
체크하겠습니다 !!

2023-03-07 12:28 UTC, Kim0914 commented on src/main/java/blackjack/view/NumberMapper.java
> +    KING(Number.KING, "K");
맞습니다.

Number 요구사항이 바뀌게 되면 Number와 NumberMapper 클래스 둘 다 변경사항이 발생한다는 단점이 있습니다 !

페어와 Mapper 클래스를 따로 둔 이유는 `도메인에 뷰 로직을 담지 않기`로 방향을 설정했습니다.

Number enum 클래스는 Card라는 도메인 클래스에 사용될 객체라고 판단해 현재 domain 패키지에 위치하여 있고 value만 정의되어 있습니다.

만약 해당 클래스에서 `TEN(10, "ten")` 과 같이 뷰 로직이 포함되는 경우, 도메인이 뷰에 의존하는 상황이 발생합니다. 그러므로 현재와 같이 view 패키지에 Mapper 클래스를 두었습니다. 수정사항이 많은 뷰를 도메인이 의존하는 것 보다, 도메인 요구사항이 변경될 때 뷰가 영향을 받는 것이 더 낫다고 판단했기 때문입니다..!

그렇기 때문에 이중으로 관리 포인트가 드는 것은 사실이라 설계를 하는 시점에서도 고민이 많았습니다 😅
바다는 어떻게 생각하시는지 궁금합니다 !!

2023-03-07 12:34 UTC, Kim0914 commented on src/test/java/blackjack/domain/card/CardTest.java
> +        assertThat(card).isNotNull();
객체가 정상적으로 생성되는지 테스트를 해보고 싶었습니다 !

assertDoesNotThrow를 사용하면 new Card()를 했을 때 **예외가 발생하지 않는다 라는 의미를 담는 것 같아**

생성된 객체가 null이 아니다를 표현해보고자 assertThat(card).isNotNull()을 사용했습니다.

그렇다면 아래와 같이 생성된 객체에 값이 정확히 할당되었는지 확인해보는 방법은 `객체가 정상적으로 생성된다`라는 의미를 담을 수 있을지 궁금합니다 😁

```java
Card card = new Card(Symbol.SPADE, Number.ACE);

assertThat(card.getSymbol()).isEqualTo(Symbol.SPADE);
assertThat(card.getNumber()).isEqualTo(Number.ACE);
```

2023-03-07 12:47 UTC, Kim0914 commented on src/test/java/blackjack/domain/game/BlackJackGameTest.java
> +                () -> assertThat(result.get(luca)).isEqualTo(Result.LOSE)
와..!
Map에 대한 containsEntry도 제공하군요 !!
딱 원했던 테스트인데 하나 배워갑니다 👍

2023-03-07 15:46 UTC, Kim0914 commented on src/main/java/blackjack/controller/BlackJackController.java
> +        }
제가 많이 부족해서인지, 미션을 처음 제출할 때 부터 지금까지도 해결하지 못한 고민인 것 같습니다 😂😂

현재 BlackJackGame 은 `전체 게임을 진행하기 위해 필요한 동작들을 하는 책임`을 가지도록 했습니다.

1. 게임이 시작되면 딜러와 플레이어에게 2장의 카드를 세팅하도록 합니다.
2. Participant 객체 즉, 딜러와 플레이어에게 카드를 전달하도록 합니다.
3. 게임 최종 결과를 계산하도록 합니다.

바다가 말씀해주신 것 처럼, game에서 직접해줘도 되는데 getter로 꺼내 컨트롤러에서 추가 카드를 나눠주는 이유는

현재 블랙잭 게임에서 추가 카드를 받는 경우, **플레이어의 이름을 뷰에 노출시켜야 하고** **해당 플레이어가 카드를 받을 수 있는 상황인지 체크, 해당 플레이어가 받는다는 의사를 보였는지 체크**해야 하기 때문입니다..

현재 컨트롤러에서 위 동작을 하는 메서드가 `passExtraCardToDealer`, `passExtraCardToPlayers` 입니다.
해당 동작을 BlackJackGame에서 하는 것이 가장 자연스럽다고 생각하지만
그렇게 되면 아래 코드와 같이 dealer와 player를 blackJackGame에서 따로 처리해야하는 상황이 발생하고, name에 따른 player를 찾는 로직이 blackJackGame에 추가되어야 한다고 생각합니다 ㅜㅜ

```java
// 딜러가 추가 카드를 받는 경우
if (blackJackGame.canDealerReceive()) {
    blackJackGame.addExtraCardToDealer();
}

// 플레이어가 추가 카드를 받는 경우
List<String> playerNames = blackJackGame.getPlayerNames();

for ( String name : playerNames ) {
    if (blackJackGame.canPlayerReceive(name)) {
        blackJackGame.addExtraCardToPlayer(name);
    }
}
```

그러므로 현재 컨트롤러에서 getter를 사용해 딜러와 플레이어를 가져오는 것은 불가피하다고 생각합니다..

저도 이 부분을 개선하려고 많이 고민해봤지만, 크게 개선할 수 있는 방안이 떠오르지 않습니다 😥

바다가 생각하고 계시는 좋은 방안이 있을까요 ?!

너무 궁금합니다 !!

2023-03-07 16:16 UTC, Kim0914 commented
안녕하세요 바다 🌊

말씀해주신 피드백을 기반으로 리팩토링을 진행했습니다 !

바다의 리뷰 덕분에 스스로 생각해볼 수 있는 시간이었습니다 ㅎㅎ

이번 주에 있을 테코톡을 준비하느라 리뷰 반영이 많이 늦어진 것 같습니다 ㅜ

달아주신 리뷰에 대해 궁금한 점은 댓글로 남겨놓았습니다 !!

감사합니다 😃😃

## 변경사항
* 컨트롤러에서 출력의 흐름을 제어하는 private 메서드 재배치
* 컨트롤러에서 참여자가 **뽑아야 하는 카드 수**를 알지 못하도록, **blackJackGame에서 자체적으로 수행하도록 변경**
* 덱 검증 메서드 명 불일치 수정
* Card의 Symbol, **Number -> Suit, Denomination 으로 클래스명 변경**
* burst를 판단하는 **최종 결과 계산 메서드 participant 에서 하도록 변경**

2023-03-09 12:24 UTC, xrabcde commented on src/main/java/blackjack/domain/card/Deck.java
> +    private final Deque<Card> cards;
👍🏻👍🏻

2023-03-09 12:36 UTC, xrabcde commented on src/main/java/blackjack/controller/BlackJackController.java
> +            return players;
> 라인 수를 줄이기 위해 메서드를 호출 하는 과정을 인자로 넘기는 것 보다, 입력 받은 값은 변수로 일단 받은 후, 해당 변수를 전달해 주는 방법이 보기 좋은 것 같다는 생각이 들어 해당 방식을 사용하고 있었습니다 !

네 저도 라인수를 줄이기 위해 인자로 바로 넘겨주는 것은 코드의 가독성을 해친다는 의견에는 아주 동의합니다 ~ 
지금 같은 경우는 `create` 이라는 함수의 이름을 통해 동작이 명시적으로 드러나 있고 생성 후 바로 반환하는 로직이므로 
굳이 변수로 받지 않아도 된다는 생각이었어요 :)

2023-03-09 12:44 UTC, xrabcde approved these changes
안녕하세요 그레이 ~ 바다입니다 🌊
리뷰가 많이 늦어져서 죄송합니다 😢
테코톡과 미션을 병행하는 것이 쉽지 않았을텐데 피드백을 꼼꼼하게 반영해주셨네요! 

질문에 대한 답변과 추가 코멘트 몇 가지 남겼으니 
다음 단계 진행하시면서 참고해주세요 ~!
2단계에서 만나요 🙌

2023-03-09 12:44 UTC, xrabcde commented on src/main/java/blackjack/domain/card/Card.java
> +    private final Denomination denomination;
네이밍을 변경해주셨군요 ! 👍🏻

2023-03-09 12:44 UTC, xrabcde commented on src/main/java/blackjack/view/NumberMapper.java
> +    KING(Number.KING, "K");
개인적으로는 현업에서 `도메인에 뷰 로직을 담는 것에 생기는 리스크` 보다 
`관리포인트를 이중으로 둘 때 발생할 리스크` 가 더 크다고 생각하지만,
현재는 학습의 단계이므로 MVC 패턴을 철저히 지켜 보는 경험도 좋은 경험이라고 생각해서 그레이의 의견을 존중합니다 :)

2023-03-09 12:44 UTC, xrabcde commented on src/test/java/blackjack/domain/card/CardTest.java
> +        assertThat(card).isNotNull();
네 테스트에 정답은 없으니 본인이 마음에 들고 확신할 수 있다면 어떤 방법을 사용하셔도 무방하다고 생각합니다 ㅎㅎ

2023-03-09 12:44 UTC, xrabcde commented on src/main/java/blackjack/controller/BlackJackController.java
> +        }
그레이가 의도하신 BlackjackGame 의 책임인 `전체 게임을 진행하기 위해 필요한 동작들을 하는 책임` 을 지금 모두 달성한다고 볼 수 있을까요 ? 
만약 현재 코드에서 컨트롤러가 없다면 Game 혼자서 블랙잭 게임을 진행할 수 있을까요? 
다음 단계를 진행하시면서 같이 개선해보셔도 좋을 것 같아요 ㅎㅎ

2023-03-09 12:44 UTC, merged