[1단계 - 블랙잭 게임 실행] 져니(이지원) 미션 제출합니다.
woowacourse/java-blackjack pull request #452
Opened 2023-03-03 08:36 UTC by Cl8D

안녕하세요, 코일! 우테코 5기 백엔드 크루 져니입니다 ⛄️
지토와 함께 세 번째 페어 프로그래밍을 진행하였습니다.

이번 페어 프로그래밍은 요구사항이 복잡하고, 스스로 생각해야 하는 부분이 많았어서 조금 더 애먹으면서 미션을 진행했던 것 같아요 💦
그래도 좋은 페어를 만나서 잘 마무리할 수 있었던 것 같습니다.
또한, 플레이어와 딜러 사이의 중복 코드를 줄이기 위해서 '참가자'라는 추상 클래스를 생성해서, 공동으로 사용할 수 있는 메서드는 최대한 해당 클래스에서 진행할 수 있도록 책임을 넘기고, 딜러와 플레이어 각각이 책임을 가지는 부분에 대해서는 별도의 메서드에서 처리할 수 있도록 진행하였던 점이 가장 기억에 남는 것 같아요. (물론, 요즘은 상속하지 않는 것이 좋은 방향성이라는 의견도 봤었는데... 제가 상속을 제대로 사용한 것인지도 의문이 들어요 🥹)

미션을 진행하면서 몇 가지 궁금증이 남았어서, 그거에 대해서 간단하게 질문드릴게요 🙇‍♀️

---

### ✔️ 로직상 절대 발생하지 않을 케이스에 대해 예외 처리를 해야 하는가?
블랙잭 게임에서 참여할 수 있는 인원을 제한한 상태이기 때문에, 카드가 소진될 수 있는 경우가 없다고 판단하여서 `Deck`에서 카드를 꺼낼 때 (`deck.poll()`) 굳이 해당 큐가 비어있는지 판단하지 않았어요. (isEmpty()가 아닐 때만 poll을 진행) 오히려 이러한 경우에 막게 되면 비어있는 경우에 대해서 또 다시 Exception Handling을 진행해야 하고, 이러면 **코드가 복잡해질 것이라고 생각했어요**. (불필요한 로직이라는 생각이 들었습니다!) 코일은 이런 경우가 있을 때 예외 처리를 진행하실 것인지 의견을 듣고 싶어요! 
+) Exception Handling이 아니더라도, Optional을 활용해서 처리할 수는 있겠지만, 아무튼 외부에서 추가적인 로직이 들어가야 한다는 점이 마음에 걸립니다... ㅎㅎ

---

### ✔️ bypass하는 메서드에 대한 테스트를 진행해야 할까?
현재 도메인의 단위를 최대한 작게 나누고, TDD를 진행하면서 프로덕션 코드를 개발하다 보니 단순히 bypass하는 메서드가 많이 생기게 되었어요. (ex. `Card`의 `isAce()` 메서드 -> `CardNumber`의 `isAce()`) 단위 테스트의 목적으로 봤을 때는 `CardNumber`의 `isAce()`메서드만 테스트하더라도 충분할까? 라는 생각이 들지만, TDD로 기능을 개발하기 위해서는 모든 메서드에 대해서 진행을 하는 게 맞다고 생각이 들더라구요. 그러나 코드를 작성하면서 자꾸 의미없는, 중복된 코드가 늘어나는 모습을 보니 '이걸 해야 하나...?' 라는 생각도 같이 들어서 고민이 들었습니다. 관련해서 어떤 식으로 생각을 잡으면 좋을까요? 🤔

---

### ✔️ Collections.shuffle()에 대하여
카드 리스트를 섞기 위해서 Collections에서 제공하는 `shuffle()`을 사용하였어요. 그리고 커스텀으로 정의한 `CardRandomShuffler`에서 해당 collection을 섞은 다음, 반환하도록 진행을 하였어요! 이 부분에서 2가지 정도의 궁금증이 생겼어요.

**💬 shuffle() 메서드의 네이밍으로 미루어 보았을 때, 단순히 '섞는 행위'만 진행하고 collection 자체를 반환하는 건 2가지의 책임을 가지는 것이 아닌가?**

-> 이 부분에 대해서 저희는 우선 컬렉션을 반환하도록 진행하였어요. 자바에서 제공하는 `List<T>`의 경우에도 add를 한 이후 boolean으로 더한 것에 대한 true / false 여부를 반환하고, 객체지향적 설계로 봤을 때 C언어 같은 곳에서 포인터와 같은 의미로 전달받은 리스트에 변화가 일어났다는 것을 굳이 명시해주지 않아도 void로 반환해도 되지만, 자바에서 '객체의 변화'에 초점을 두고 생각해보았을 때 그냥 아무것도 반환하지 않는 게 어색하게 느껴져서 반환을 하도록 진행했어요. (물론, 자바의 레퍼런스 타입을 생각해보면 같은 맥락이기는 하지만요.) **한 가지 책임을 하게 하는 것 vs 객체의 행위와 변화를 명시적으로 나타내는 것**을 생각했을 때 어떤 쪽이 조금 더 객체지향과 가까운 설계인지 갈피를 잡기 힘들어서 이렇게 질문드립니다!

💬 **자바에서 제공하는 API는 믿고 사용하는 것이 맞을까?**
```java
    @Test
    @DisplayName("create()는 호출하면 섞인 52장의 카드 뭉치를 생성한다.")
    void create_whenCall_thenSuccess() {
        final Deck deck = assertDoesNotThrow(() -> Deck.create(mockShuffler));

        assertThat(deck)
                .isExactlyInstanceOf(Deck.class);
    }
```
이 코드를 보면 굉장히 이질감이 드실 것 같아요 🥲 현재 정적 팩터리 메서드를 통해 `Deck`을 생성할 때, `shuffle()`을 통해서 섞인 카드 뭉치를 반환하게 되는데, 테스트상 검증할 때 어떤 식으로 섞였다는 것을 명시해줘야 할지 모르겠어서 우선은 **객체의 생성에 초점을 두고** 테스트를 진행했습니다. 또한, `Deck`에서 필드로 가지고 있는`Queue<Card> deck`을 외부에서 직접적으로 접근하는 일은 없기 때문에 별도의 getter를 두지 않았어요. 처음에는 assertJ에서 제공하는 extracting을 활용하여 내부 원소를 체크하는 것이 더 좋은 방향인지도 고민했지만, **리플랙션 기반으로 동작하는 해당 기능을 사용하면 테스트 비용이 지나치게 올라갈 것 같다고 판단해서** 진행하지 않았어요. (이전에 자동차 미션을 구현할 때 리플랙션을 활용하여 테스트 코드를 작성한 적이 있었는데, 테스트 비용이 너무 높을 것 같다는 피드백을 들었기도 했구요. ㅎㅎ) '섞였다'는 행위 자체를 검증할 필요는 없을 것 같다고 생각해서 저런 요상한(?) 테스트 코드를 작성하게 되었는데, 이런 테스트 코드가 과연 옳은 것일까... 라는 생각이 들어서 머리가 어지러웠어요 🤯 테스트를 위한 getter를 생성해서 내부 deck의 사이즈가 52장인 것 정도는 검증하는 것이 옳은 방향일까요? 코일의 생각이 궁금해요!

---

변경했으면 좋겠는 점이나 궁금한 점, 마음껏 피드백해주시면 감사드리겠습니다!
좋은 하루 되세요!! 💪

2023-03-04 14:03 UTC, iphwade requested changes
안녕하세요 져니! 블랙잭은 난이도가 꽤 있는 미션인 것 같습니다-!
우선 코드 작성, 구조, 설계 정말 잘해주셨습니다-!
작성하시다보면 너무 구조가 잘게 쪼개졌나라고 생각하실수도 있는데요!
미션의 의도와 부합하고 충분히 잘 하고 계시니 그런 걱정은 안하셔도 괜찮을 것 같습니다-! 
간단한 질문 몇가지 남겼습니다-! 
가장 중요한 부분은 명시적 형변환 없이 처리해볼 수 없을까에 대한 질문인데요-! 
요 부분 집중적으로 고민해보시면 좋아보입니다-! 

 - 기능 다이어그램이 깨졌네요-! 
 - 생성자를 바로 사용하지 않고 정적 팩토리 메서드를 사용하신 이유가 있을까요-!? 

답변
✔️ 로직상 절대 발생하지 않을 케이스에 대해 예외 처리를 해야 하는가?
 - 말씀하시는 클래스가 온전히 블랙잭만을 위해 사용되는 걸까요? 코드 작성할 떄에는 재사용성과 일반화성을 고려하며 작성하셔야 합니다-! 또한 도메인 규칙이 어떻게 바뀔지도 모르구요-! 그럴 경우를 고려한다면 이 케이스에 대해서도 예외처리가 필요하다고 생각됩니다-! 다만 언제나 판단은 본인의 몫이므로 충분히 고려하지 않다고 생각되면 없어도 괜찮지 않을까 생각됩니다-! 

✔️ bypass하는 메서드에 대한 테스트를 진행해야 할까?
넵, 위와 마찬가지로 언제나 져니께서만 코드를 작성하는 것은 아닐겁니다-! 바이패스였던 메서드가 먼훗날 다른 개발자의 수정에 의해 그렇게 되지 않을 수도 있구요. 의미없는 장치라고 생각되지는 않습니다-! 또, 그런 부분들이 TDD가 더 견고한 구조를 가져갈 수 있는 이점이기도 하니까요-! 

✔️ Collections.shuffle()에 대하여

💬 shuffle() 메서드의 네이밍으로 미루어 보았을 때, 단순히 '섞는 행위'만 진행하고 collection 자체를 반환하는 건 2가지의 책임을 가지는 것이 아닌가?
 -> 요부분은 잘 이해가 가지않네요ㅠ 다시 질문 주실 수 있으실까요-!? 

💬 자바에서 제공하는 API는 믿고 사용하는 것이 맞을까?
굳이 자바가 아니더라도 다른 라이브러리에서 제공하는 API에서도 비슷한 고민들을 하기마련인데요-!
도메인 로직에 직접적인 영향을 끼친다 싶으면 라이브러리 업데이트에 대응하여 테스트하나를 작성해두기도 합니다만, 사실 이런 식이면 Scanner를 통해 입력을 받는 저수준의 모든 동작들까지도 믿지못하는 상황들이 생기는데요-! 그래서 위와 같은 상황이 아니라면 충분히 믿고 사용해도 무방하다고 생각됩니다-! 

질문을 온전히 잘 이해했는지는 잘 모르겠네요,,, 답변이 이해가 가지않는다면 다시 DM주시면 살펴보도록 하겠습니다-!

2023-03-06 02:30 UTC, Cl8D commented on src/main/java/domain/card/Deck.java
> +                .collect(Collectors.toList());
사실 요즘 stream에 대해서 공부 중이나 욕심내서 flatMap을 사용해보기는 했는데, 가독성 측면에서 그렇게 좋지는 않다는 생각이 들었어요. 또한, 저런 식으로 stream 내부에서 한 번 더 stream을 도는 건 depth가 깊어지는 것과 동일하다는 생각이 들어서 수정해두겠습니다 ㅎㅎ 감사해요!

2023-03-06 02:42 UTC, Cl8D commented on src/main/java/domain/card/Deck.java
> +        return new Deck(new LinkedList<>(shuffledCards));
현재 Deck에서 내부적으로 Queue를 사용하고 있는데, 단방향으로 구조를 잡았기 때문에 (FIFO) 구현체인 LinkedList<>()을 사용하였어요! 섞은 카드에 대해서 그대로 넣고, 넣은 순서대로 빼기에는 LinkedList가 적합하다고 판단하였습니다! 혹시 더 좋은 구조가 있을까요?

2023-03-06 02:44 UTC, Cl8D commented on src/main/java/controller/GamePrepareController.java
> +    }
넵! getter를 사용하지 않고, 어차피 Participants는 외부에서 생성된 그 상태 그대로 유지되기 때문에 굳이 getter를 사용해서 한 번 더 빼올 필요가 없다고 판단했어요!

2023-03-06 03:43 UTC, Cl8D commented on src/main/java/domain/game/GameResult.java
> +    }
혹시 왜 정적 팩터리 메서드로 빼시는지 여쭤봐도 괜찮을까요~?! 저는 static 메서드의 개수를 줄이기 위해서 생성자에서 하는 것을 선호했는데, 이렇게 말해놓고 일부 로직은 `create()`에서, 일부 로직은 생성자에서 한 것들이 있어서 우선은 `create()`에서 하는 구조로 통일했습니다! 👍

2023-03-06 03:46 UTC, Cl8D commented on src/main/java/controller/DrawCardCommand.java
> +            .collect(Collectors.toUnmodifiableMap(cardCommand -> cardCommand.command, Function.identity()));
우선 기본적으로 enum 타입에 대해서 CACHE를 두었는데요! 말씀해 주신 클래스에서는 카드를 한 장 더 받을지 말지에 대한 사용자 플래그를 관리하는 enum 타입인데, 사용자의 명령어와 enum 타입에 대한 매핑을 조금 더 원활하게 하기 위해서 CACHE를 두었어요. 만약 enum의 values를 통해서 매번 조회하는 방식을 둔다고 한다면, 한 번 조회할 때마다 계속 O(n)의 시간복잡도가 들기 때문에 성능 측면에서도 캐시를 통해 관리하는 게 더 좋다고 생각했어요!(한 번 저장한 것에 대해서 계속 재사용하는 것이니까요)

2023-03-06 04:54 UTC, Cl8D commented on src/main/java/controller/GameProcessController.java
> +        } while (canDrawCard(player, drawCardCommand));
초기화와 선언이 떨어져 있을 때 좋지 않은 건... 현재 로직에서는 그렇지 않지만, 선언부 이전에 어떠한 로직이 들어왔을 때 에러가 발생할 수 있기 때문에 (null이기 때문) 좋지 않은 구조로 볼 수 있을 것 같아요! (생각해본 적 없는 부분이었어서 이러한 이유가 맞는지는 모르겠지만 🥲) 또한, 만약 그렇다면 null인지 아닌지 체크를 해봐야 하기 때문에 코드의 복잡성이나 가독성이 안 좋아진다는 단점이 있을 것 같아요. 그래서 코드를 수정해서 재귀로 처리하도록 변경했습니다!

2023-03-06 05:49 UTC, Cl8D commented on src/main/java/controller/GamePrepareController.java
> +        final Dealer dealer = (Dealer) participants.getDealer();
제가 질문을 제대로 이해한 건지 모르겠는데, 현재 구조에서 명시적 형변환 없이 어떻게 처리해야 할지 감이 잘 잡히지 않아서 다시 질문드려요...! 현재는 '참가자들'이라는 집단으로 '딜러'와 '플레이어'를 묶어서 관리하고, 가장 첫 번째 인덱스에 존재하는 참가자가 딜러라는 의미로 딜러를 얻어오고 있는데요! 이는 딜러와 플레이어 사이에 생기는 중복 코드를 제거하기 위해서, 두 클래스가 동일한 기능을 할 경우 `Participant`에서 처리하도록 하기 위함이었어요! (근데 생각해보니까, 추상 메서드가 없어서 추상 클래스로 만들 필요도 없었네요...) 

제가 생각했을 때 명시적 형변환을 진행하지 않기 위해서는, `Participants`에서 `Dealer dealer` 필드와 `List<Participant> players` 필드를 따로 관리하는 방법, 혹은 형변환을 진행하기는 하지만 컨트롤러 단위에서 진행하지 않고 `participants.getDealer()` 내부에서 형변환 후 `Dealer`를 반환하는 방법 정도로 떠오르는데, 전자는 Participants가 일급 컬렉션이라는 의도가 사라지기도 하고, 로직상으로도 공통으로 관리한다는 점에서 맞지 않는 것 같아서 우선은 컨트롤러에서 그냥 명시적 형변환을 진행해주었습니다. 

혹시 명시적 형변환을 사용하지 않는 다른 방법이 있을까요...? 관련 레퍼런스나 힌트를 주시면 감사드리겠습니다 🙇‍♀️

2023-03-06 07:58 UTC, Cl8D commented
안녕하세요, 코일! 말씀해 주신 부분에 대해서 저도 간단히 의견을 드리고 싶어서 답글 남겨요 😎
우선, 리팩터링을 다음과 같은 부분을 진행하였습니다! 

페어 리뷰어님께 받았던 리뷰도 적용하다 보니까 수정 사항이 몇 가지 더 생겼네요 ㅎㅎ

- [ ]  분리했던 Controller에 대해서 다시 합치기
    - 이 부분은 페어 리뷰어님께서 말씀해 주신 부분인데요~! 상위 컨트롤러에서 `InputView`, `OutputView`를 주입해주고 이를 하위 컨트롤러까지 계속 전파시키는 구조가 너무 결합도를 높이는 것 같다는 의견을 받아서, 우선 단일 컨트롤러로 방향을 틀었습니다 :D
    - 물론, 이에 따라서 Controller의 길이가 길어지지만… public api를 기준으로 봤을 때 50줄 정도여서 괜찮다고 판단하였습니다! 다만, 인스턴스 필드 개수 제한으로 인해서, `makeDeck()` 외부에서 `CardRandomShuffler`를 주입하는 방식이 아닌, 내부에서 바로 생성해서 넣어주는데 이런 구조는 괜찮은 건지 고민이 드네요 🤔
- [ ]  생성자의 검증 로직을 정적 팩터리 메서드에서 진행하도록 통일
- [ ]  초기화-선언이 분리되어 있던 로직을 변경 (do-while → 재귀)
- [ ]  딜러의 결과를 카운트할 때, Collections.frequency → `Collectors.groupingBy`를 사용해서 stream을 3번 돌지 않고 처리할 수 있도록 코드 수정
- [ ]  컨트롤러의 명시적 형변환 코드 제거 (??)

---

### ✔️ 기능 다이어그램

헉 제가 지금 봤을 때는 안 깨져 있는데… 🥹 파일을 따로 디렉터리에 올려서 해당 경로를 참조하는 식으로 변경하겠습니다! 혹시 여전히 안 보이신다면 (`src/main/resources/blackjack-diagram.png`) 경로에 해당하는 파일을 봐주세요…!  ㅠㅠ

---

### ✔️ 생성자 대신 정적 팩터리 메서드를 사용한 이유

저는 기본적으로 객체를 생성할 때 생성자를 막아두고, 정적 팩터리 메서드를 사용하는 방법을 선호하는데요! 기본적으로 정적 팩터리 메서드를 사용했을 때 가질 수 있는 이점 (동일한 시그니처를 가지는 **생성자에 대해 이름 부여를 통하여 인스턴스 생성** 가능, 호출 시에 캐싱 등을 활용하여 무조건 인스턴스를 생성하지 않아도 된다는 점 등)을 얻고 싶기 위함이에요!

저는 보통 생성자의 역할을 대신하는 경우, .create()라는 네이밍으로 통일하기 때문에 코드 작성 시에도 어디서 객체를 생성하는지 바로 파악하기 쉬워서 더 사용하고 있는 것 같아요! 

---

### ✔️ 질문에 대한 답변에 대해서

우선 온전히 블랙잭을 위해 사용되는 클래스라고 생각하였기 때문에, 현재는 별도로 추가해두지 않고 나중에 요구사항이 추가된다면 두어도 괜찮을 것 같다고 판단하였습니다! 👍 bypass 메서드의 테스트에 대해서 고민했었는데 코일이 그렇게 말씀해 주시니 한결 마음이 편안해지네요 ㅎㅎ 감사합니다. 그리고 생각해보니, api를 못 믿으면 scanner도 사용 못하고 테스트하는 경우가 생기겠네요…! ㅎㅎ 이정도는 믿고 사용하는 것이 제 마음도 편하고(?) 코드에게도 더 좋을 것 같다는 생각이 들었어요! 

**💬 Collection.shuffle()에 대한 내용입니다!**

→ 저는 shuffle()이라는 메서드의 네이밍에 대해서 생각해봤을 때, 단순히 어떠한 것을 ‘셔플한다 = 섞는다’ 까지의 책임이 있을 것이라고 생각했어요.

```jsx
@Override
public List<Card> shuffle(final List<Card> cards) {
    Collections.shuffle(cards);
    return List.copyOf(cards);
}
```

하지만 제 구현체에서는 shuffle() 이후에 해당 셔플에 대한 결과를 List.copyOf을 통해서 반환까지 진행하는 구조예요. ‘섞는다’와 ‘섞고 나서 해당 결과에 대해 반환한다’ 는 하나의 일만 하는 구조에서 벗어나는 게 아닐까…? 라는 고민을 했었어요! 하지만, 반환하지 않는다면 아마 다음과 같은 구조일 거예요.

```java
List<Card> cards;
cardShuffler.shuffle(cards); // 반환 없이 그냥 셔플 진행
cards.XXX(); // 해당 카드에 대해 그대로 사용 (레퍼런스 타입의 특징)
```

객체에는 분명 ‘섞는다’라는 행위가 주어졌는데, 해당 객체에 대해서 마치 아무 변화가 없는 것처럼 기존의 cards를 사용하는 모습이 조금 어색하다고 생각이 들어서 저는 우선 명시적으로 반환하는 형태로 진행을 했어요.

```java
List<Card> cards;
cards = cardShuffler.shuffle(cards); // 반환된 카드 사용
cards.XXX(); // 명시적으로 '섞임'을 당한 카드임을 알 수 있음
```

또한, List.copyOf()을 통해서 불변성을 만족하려고 했어요! 
질문드리고 싶었던 것은, 2가지 구조 중에 어떤 게 더 객체지향적 설계에 맞는 로직인지 코일의 의견을 듣고 싶어서 여쭤봤어요 😎

---

사실 이번 리팩터링 때는 많이 변경하지 않아서, 오히려 질문이 더 많아진 느낌이네요 💦
명시적 형변환에 대한 부분을 말씀해 주셨었는데, 딜러의 책임인 `getFirstCard()`, `canGiveCard()`를 `Participant`의 메서드로 옮기는 작업을 진행하거나, 혹은 추상 메서드로 두어서 오버라이딩으로 Player에게도 해당 메서드를 상속받도록 하는 게 좋을까 싶은데, 두 가지 모두 좋은 방법은 아닌 것 같아서 우선 이렇게 두었습니다! 

```java
// Participants.java
        if (participant instanceof Dealer) {
            return (Dealer) participant;
        }
```
명시적 형변환을 했을 때 위험할 수 있는 요소를 방지하기 위해서 instanceof를 통해 타입을 체크하도록 진행을 했습니다! 혹시 이렇게 하더라도 명시적 형변환을 사용하는 게 좋지 않은 방법일까요? 

이번 리뷰도 잘 부탁드립니다! 🙇‍♀️

2023-03-06 14:11 UTC, iphwade commented on src/main/java/domain/card/Deck.java
> +                .collect(Collectors.toList());
세가지 방법을 모두 고민해주셨네요-! 
모두 좋은 방법으로 보입니다-!
코멘트에 남겼듯이 가독성면에서는 개인의 선호문제인 것 같아요-!
물론 그 전에 요소들의 사이즈가 크고 반복돼서 사용되는 경우에는 stream 학습해보셨다니 아시겠지만 성능 차이가 있을 수 있는 부분들이 있습니다-! 
그런 부분들을 고려했을 때 괜찮다면 굳이 수정하지 않으셔도 괜찮습니다-!

2023-03-06 14:16 UTC, iphwade commented on src/main/java/domain/card/Deck.java
> +        return new Deck(new LinkedList<>(shuffledCards));
넵! 자료 구조 선택에 근거가 있네요! 👍

2023-03-06 14:21 UTC, iphwade commented on src/main/java/controller/GamePrepareController.java
> +    }
이 흐름에서는 변화가 되지 않는 것이 사실입니다-! 그러나 다른 요구사항으로 코드가 바뀔 가능성이 존재해보입니다.
그럴 때에 져니가 아닌 다른 분께서도 participants의 변화가 없어서 두 인자를 전달한다는 것을 인지하실 수 있으실까요?
변화를 추적해야하는 매개변수의 수가 1개에서 2개로 늘어나지는 않을까요?! 
getter의 사용을 줄이라는 말은 무조건적인 getter를 지향하라는 의미이지 필요할 때 사용하지 않는다는 의미는 아닙니다-! 

도메인 로직에서 오더링으로 판단하지는 않을까 싶었는데 오더링은 잊어주세요-! :)

2023-03-06 14:28 UTC, iphwade commented on src/main/java/controller/GameProcessController.java
> +        } while (canDrawCard(player, drawCardCommand));
넵! 말씀하신 이유도 정답입니다-!
또, 가독성 면에서도 의미가 있는데요-! 
초기화와 선언을 동시에 하면 변수의 변화를 추적하기 좋습니다-! 
작성하시는 걸 보니 본능적으로 아시는 것 같은데요! 현업에서 많은 코드가 져니 코드처럼 깨끗하지만은 않습니다-!
지금은 잘 분리되어 작성되어 있어 크게 장점이 부각되어 보이지않으실껀데요!
굉장히 긴,,, 레거시 코드들을 만나게 되면 이점이 확실히 느껴지실 겁니다-!

2023-03-06 15:16 UTC, iphwade requested changes
안녕하세요-! 

모든 리뷰를 반영하실 필요는 없습니다-!
충분히 고민해보시고 답변 해주시는 모습이 멋집니다-! 👍 

Controller에 도메인 로직으로 보여지는 로직들이 많이 존재합니다-! 
계층을 하나 더 두거나 기존 계층으로 로직을 옮겨보는 것은 어떨까요? 

질문에 대한 답변은 달았습니다-! 
또, 지금은 아래와 
 1. Index가 아닌 다른 기준으로 Dealer, Player 구별해보기
 2. Controller에 도메인 로직 제거하기 
 3. instanceof 제거하기 -> 제거가 어렵다면 차라리 우선은 명시적 형변환으로!
 4. 명시적 형변환을 한번에 제거하는 것이 어렵다면 컨트롤러 로직을 분리해본 뒤 생각해보시죠-! 
키워드들에 집중해보실까요?!

2023-03-06 15:16 UTC, iphwade commented on src/main/java/domain/card/Card.java
> +        if (!(target instanceof Card)) {
https://tecoble.techcourse.co.kr/post/2021-04-26-instanceof/

instanceof는 SOLID를 여러 방면으로 무시하는 코드를 작성하기 쉽습니다-!

2023-03-07 05:19 UTC, Cl8D commented on src/main/java/domain/game/GameResult.java
> +    }
아하! 무슨 말씀인지 이해했습니다 ㅎㅎ 다만, 테스트가 쉬워진다는 부분에서 한 가지 궁금증이 있는데요! 보통 정적 팩터리 메서드를 사용하면 생성자는 private로 접근제어자를 막기 때문에 온전히 '생성자 하나만' 테스트를 하는 경우는 없을 것 같은데, 이런 부분에서 테스트가 쉬워진다고 말하기는 어렵지 않을까요?? `create()` 메서드를 테스트했을 때 객체의 생성뿐만 아니라, 별다른 검증 로직을 수행하는 로직까지 함께 테스트하면서 다른 메서드의 변화 (ex. 검증 로직)가 '생성에 대한 테스트'를 깨트릴 수도 있다고 이해하면 될까요? (근데 이것도 사실 객체의 생성 자체만 테스트하기 위해서는 생성자가 열려 있어야 하는데, 그게 아닐 테니까요...)

그 외에 네이밍을 통한 가독성, 전략 선택 등에서 조금 더 유연함을 가져갈 수 있다는 점은 이해가 되네요! 말씀해 주신 부분을 보니 이전에 진행한 리팩터링은 의미있는 리팩터링이 아니었다고 생각이 드네요... ㅎㅎ 그래서 로직을 아래처럼 수정해봤어요!

<Before>
```java
   private GameResult(Participant dealer, List<Participant> players) {
        this.gameResults = new LinkedHashMap<>();
        players.forEach(player -> calculateResult(dealer, player));
    }

    public static GameResult create(final Participants participants) {
        final Participant dealer = participants.getDealer();
        final List<Participant> players = participants.getPlayer();
        return new GameResult(dealer, players);
    }
```

<After>
```java
  private GameResult(Map<Participant, Result> gameResults) {
        this.gameResults = gameResults;
    }

    public static GameResult create(final Participants participants) {
        final Participant dealer = participants.getDealer();
        final List<Participant> players = participants.getPlayer();
        final Map<Participant, Result> gameResults = makeGameResults(dealer, players);
        return new GameResult(gameResults);
    }

    private static Map<Participant, Result> makeGameResults(final Participant dealer, final List<Participant> players) {
        Map<Participant, Result> gameResults = new LinkedHashMap<>();
        for (Participant player : players) {
            Result playerResult = calculateResult(dealer, player);
            gameResults.put(player, playerResult);
        }
        return gameResults;
    }
```

2023-03-07 05:28 UTC, Cl8D commented on src/main/java/domain/participant/Participants.java
> +    }
아 그렇다면 trim은 콘솔의 입력 사항으로 인해 들어오는 것이니 도메인보다는 뷰에 존재하는 게 맞을 것 같네요!
뷰로 이동시켜두겠습니다 🙇‍♀️

2023-03-07 10:05 UTC, Cl8D commented
안녕하세요, 코일! 이번 리팩토링은 구조 변경에 조금 더 힘썼어요.
다음과 같은 사항을 수정했습니다 ✔️

- [ ]  점수와 관련된 상수를 ‘Score’ 클래스를 통해 관리하도록 변경하기
    - 오늘 네오 수업을 들으면서 점수에 대해서도 객체로 관리하는 게 객체지향적인 관점에서 더 좋을 것 같다는 생각이 들어서 이렇게 진행하였어요!
- [ ]  카드 생성 시 캐시 적용하기
- [ ]  GameResult 생성 로직을 정적 팩터리 메서드에서 관리하도록 변경하기
- [ ]  참여자 이름에 대해 trim하는 메서드를 뷰로 이동하기
- [ ]  Controller에서 존재했던 도메인 관련 상수들을 도메인 내부에서 관리하도록 변경하기
    - 기존에는 도메인에서 상수를 건네줘서 해당 횟수만큼 카드를 건네주도록 했지만, 이번에는 메서드를 분리시켜 도메인 내부에서 관리할 수 있도록 진행하였습니다! (가변인자를 이번 기회에 사용해보았어요 🙇‍♀️)
- [ ]  모든 클래스에 final / abstract 키워드 붙이기
- [ ]  명시적 형변환을 사용하지 않도록 구조 변경하기

이번 리팩터링의 핵심은 구조 자체를 꽤 많이 변경했다는 점인데요!

‘참가자’에 대한 일급 컬렉션을 관리하면서 인덱스를 사용하지 않으면서, 명시적 형변환을 사용하지 않고 딜러와 플레이어를 관리하는 것은 별도의 필드를 선언하지 않는 이상 불가능할 것 같다고 생각이 들어서 (방법이 있을 수도 있겠지만, 최대한 생각해본 결과 저는 잘 모르겠습니다 🥲) **기존의 `Participants`를 플레이어에 대한 일급 컬렉션인 `Players`로 역할을 변경**하고, 컨트롤러에서 생성한 `Dealer` 객체를 계속 사용하도록 진행하였습니다. 

다만, `Dealer`를 생성할 때 `Dealer` 자체에서 `create()` 하지 않고, 부모인 **`Participant`의 `createDealer()` 메서드를 통해서 딜러를 생성**하도록 만들었어요. 사실 컨트롤러에서 ‘Dealer’에 대한 정보를 아예 모르도록 하고 싶었는데, 그러면 별도의 서비스 계층을 두거나 해야 할 것 같아서, 너무 애플리케이션이 커진다는 생각이 들었어요. 

또한, 블랙잭 게임에 대해서는 `GameManager`에서 관리하고 있기 때문에, 딜러와 플레이어에 대한 정보는 참가자들 리스트를 내부에서 생성하는 책임을 두어서 게임 관리자는 참가자와 카드 (덱) 정보만 알고 있도록 진행했어요. 나름대로 책임을 분리한다고 해서 둔 것이기는 하지만, 현재 이 구조가 깔끔하다는 생각이 들지 않아서 고민이 많이 드네요 💦 (뭔가 참가자의 정보가 너무 분할되어 있는 느낌이 들기도 하고, 컨트롤러에서 플레이어 - 딜러 - 그리고 게임 매니저, 이렇게 3개를 인자로 넘겨주는 경우가 많아서 잘못된 분리를 한 것인가… 같은 고민도 드는 것 같습니다… ㅎㅎ)

피드백은 항상 환영이에요! 이번 리뷰도 잘 부탁드립니다 🙇‍♀️

2023-03-07 10:08 UTC, Cl8D commented on src/main/java/domain/card/Card.java
> +        if (!(target instanceof Card)) {
캡슐화 깨짐 (하위 객체에 대해 상세하게 알게 된다는 점), OCP 위반 (확장이 어려어지고, 변화에 열려있는 상태), SRP 위반 (상세 타입을 알고 있기 때문에, 해당 타입의 구현체를 다 알고 있어야 함), 성능 문제까지... 여러모로 지양해야 하는 이유가 정말 많네요 💦 좋은 레퍼런스 감사드립니다.

2023-03-08 15:30 UTC, iphwade approved these changes
리뷰 반영해주시느라 고생하셨습니다-! 

고민해보시면 좋을 법한 것들을 리뷰로 남겼습니다-! step2 진행하시면서 고민해보시면 좋을 것 같아요-! :)

2023-03-08 15:30 UTC, iphwade commented on src/main/java/domain/card/Deck.java
> +    }
메서드의 위치가 아래와 바뀌어야될 것 같아요-! 메서드는 사용되는 곳에 최대한 가깝게 배치하는 것이 읽기 좋습니다-!

2023-03-08 15:30 UTC, iphwade commented on src/main/java/domain/game/GameManager.java
> +    private final List<Participant> participants;
일급 컬렉션으로 나누면 분리할 수 있는 로직들이 보이는데요-! 혹시 이유가 있으실까요-?

2023-03-08 15:30 UTC, iphwade commented on src/main/java/domain/game/GameManager.java
> +    }
메서드는 사용되는 곳에 가깝게 배치하는 것이 좋습니다-! 

https://dodop-blog.tistory.com/277

2023-03-08 15:30 UTC, iphwade commented on src/main/java/domain/game/GameManager.java
> +        participants.add(DEALER_INDEX, dealer);
인덱스로 구분하는 것은 많은 사이드 이펙트를 만들 수 있어보입니다.
인덱스로 딜러를 구분하는 방법 말고 다른 방법에 대해 고민해보는 것은 어떨까요-?

2023-03-08 15:30 UTC, iphwade commented on src/main/java/domain/participant/Participant.java
> +    }
오 재밌는 방법이네요-! 👍

2023-03-08 15:30 UTC, iphwade commented on src/main/java/domain/participant/Participant.java
> +    protected final ParticipantCard card;
호... 이건 참 애매하네요-! card라는 워딩이 너무 많아서 가독성을 해치는 느낌이 드네요 ㅠ 오히려 hand라던가... 요론 네이밍은 어떨까요? (의견입니다. 반영안하셔도되어요-!)

2023-03-08 15:30 UTC, iphwade commented on src/main/java/view/message/Message.java
> +public enum Message {
static final로 관리하는 것과 enum으로 관리하는 것은 성능상으로는 큰 차이는 없습니다.

그러면 왜 enum으로 처리하셨을까요?
저는 enum으로 구현할 때는 그 객체가 나름의 로직을 지닐 때 선택하는데요-!
져니께서 enum을 선택하신 이유는 무엇일까요-?!

2023-03-08 15:30 UTC, iphwade commented on src/main/java/view/message/Message.java
> +    PARTICIPANT_CARD_RESULT("%s 카드: %s - 결과: %d"),
크게 중요한 것은 아니지만 요론 케이스는 FORMAT 을 위한 STRING인 것을 나타내는 것이 좋지않을까 싶습니다-!

2023-03-08 15:30 UTC, iphwade commented on src/main/java/domain/participant/ParticipantCard.java
> +    }
요 메서드들은 왜 기본 접근지정자로 설정하셨나요-?!

2023-03-08 15:30 UTC, iphwade commented on src/main/java/controller/GameController.java
> +        return isBust(player) || isBlackJack(player) || drawCardCommand.isDrawStop();
아마 인지하고 있을 것 같은데 다중 조건이 포함된 조건문은 조건의 순서가 성능에 영향을 끼치기도 합니다-! 👍

2023-03-08 15:30 UTC, iphwade commented on src/main/java/controller/GameController.java
> +        OutputView.print(System.lineSeparator().trim());
System.lineSeparator() 👍

2023-03-08 15:30 UTC, iphwade commented on src/main/java/domain/participant/ParticipantCard.java
> +    }
ACE가 여러개인 상황에도 대응할 수 있을까요-?

2023-03-08 15:30 UTC, merged

2023-03-09 01:56 UTC, Cl8D commented on src/main/java/domain/participant/Participant.java
> +    }
저는 Dealer가 Participant를 상속받고 있기 때문에, 상위 클래스에서 하위 클래스를 반환하도록 하는 구조를 생각해서 이런 식으로 반환하도록 만들었어요! 의미적으로도 '딜러'는 일종의 '참가자'이기 때문에 이런 식으로 반환해도 괜찮다고 생각했는데, 아무래도 두 도메인이 의존을 하게 되면 결합도가 높아진다는 단점은 생길 것 같아요!

2023-03-09 01:59 UTC, Cl8D commented on src/main/java/controller/GameController.java
> +        final List<Player> players = getPlayers();
컨트롤러에서 실질적으로 사용하는 값이 모두 Players에 존재하는 List<Player>이기 때문에, 각 메서드에서 계속 getter를 호출하지 않고 한 번만 호출해서 계속 사용하도록 하고 싶어서 그렇게 진행했어요! 

```java
public void a(Players playerInfo) {
  List<Player> players = playerInfo.getPlayers();
}
```

Players를 반환하게 되면, 각각을 사용하는 메서드에서 계속 위와 같이 getter를 호출해주는 게 불필요하다고 느꼈던 것 같아요. 추가적으로, 변수에 대한 네이밍도 애매해져서 (players를 다른 의미로 어떻게 두어야 할지 고민이라... 🥲) 이렇게 구현했습니다!

2023-03-09 02:16 UTC, Cl8D commented on src/main/java/domain/participant/Players.java
> +        validatePlayerCount(playerNames);
엇 그러면... 전에 생성자를 최대한 간단하게 가져가는 편이라고 말씀해주셨었는데, 어떤 로직은 정적 팩터리 메서드로, 어떤 로직은 생성자로 구분하면 좋을지 코일만의 규칙이 있으신가요? 저는 생성자를 최대한 간단하게 가져가기 위해서 검증 로직을 팩터리 메서드로 뺐던 거였는데, 다른 메서드로 치환될 수 있다는 게 잘 와닿지 않아서요...! 새로운 기능을 위한 것이라면 별도의 메서드를 추가할 것이고, 사용되는 팩터리 메서드는 '생성을 위해 - 메서드 이름도 같은 맥락으로 `create()`로 지은 것이구요!' 사용될 텐데, 다른 기능으로 치환될 수 있을까 싶어서 질문드립니다!

2023-03-09 02:21 UTC, Cl8D commented on src/main/java/domain/card/Deck.java
> +    }
엇 혹시 코일은 public 메서드 사이에 private를 두는 편이신가요??

저는 개인적으로 public 메서드를 위에 두고, private를 아래에 모아두는 것을 선호하는 편이에요! public 메서드를 통해서 해당 클래스에 대해 외부에 공개된 메서드를 한눈에 파악하고, 이는 곧 해당 클래스가 어떤 일을 하는지 알 수 있기 때문에 행위에 대해서 제대로 파악할 수 있더라구요...! (테스트 코드를 추가로 작성할 때도 외부에 선언되어 있는 행위들을 보고 작성할 수 있기 때문에 더 편하기도 하구요! - 물론 지금은 TDD를 통한 구현이라 프로덕션 -> 테스트 코드를 작성하는 구조는 아니지만요!) 

또한, 사용되는 메서드의 경우 Intellij 같은 IDE를 사용하면 해당 메서드가 선언된 위치로 갈 수 있고, 기본적으로 메서드는 재사용성을 엄두해두고 만드는 것이기 때문에 여러 public api, 혹은 private 메서드가 참조한다면 사이에 두는 게 애매해지는 경우가 많더라구요! 혹시 이런 경우에는 어떻게 배치하시는 편이신가요?

2023-03-09 02:22 UTC, Cl8D commented on src/main/java/domain/game/GameManager.java
> +    }
앞서 얘기한 주제랑 동일한 이야기인 것 같아서 링크만 걸어두겠습니다 🙇‍♀️ [제 의견입니다!](https://github.com/woowacourse/java-blackjack/pull/452#discussion_r1130309920)

2023-03-09 02:23 UTC, Cl8D commented on src/main/java/controller/GameController.java
> +        return isBust(player) || isBlackJack(player) || drawCardCommand.isDrawStop();
앗 이거는 수정해두겠습니다! 사용자가 입력한 커멘드 > 버스트 > 블랙잭 순으로 더 많이 발생할 것 같네요! 감사합니다 ㅎㅎ

2023-03-09 02:38 UTC, Cl8D commented on src/main/java/domain/game/GameManager.java
> +    private final List<Participant> participants;
엇 아뇨!! 이거는 제가 놓친 부분인 것 같습니다 ㅎㅎ 당시에는 그냥 감싸는 역할밖에 없다고 생각해서 안 만들었던 것 같은데, 막상 리팩터링을 하려고 보니까 수정할만한 부분이 꽤나 보이네요...!! 일급 컬렉션으로 만들어두겠습니다. 감사합니다 🤗

2023-03-09 04:14 UTC, Cl8D commented on src/main/java/domain/participant/Participant.java
> +    protected final ParticipantCard card;
앗 그런가요?? 그러면 hand로 변경해두겠습니다! 확실히 여기저기서 card가 나오니까 헷갈릴 것 같아요 ㅎㅎ

2023-03-09 04:15 UTC, Cl8D commented on src/main/java/view/message/Message.java
> +public enum Message {
앗 이번 미션에서는 다른 출력 메시지들도 전부 enum으로 관리하고 있기 때문에 여기서도 enum으로 진행해두었는데, 생각해보니 다른 출력 메시지들은 각각의 로직이 있네요 ㅎㅎ 너무 생각없이 enum으로 잡아버린 것 같네요! 이 부분은 static final로 처리하도록 변경해두겠습니다!

2023-03-09 04:16 UTC, Cl8D commented on src/main/java/view/message/Message.java
> +    PARTICIPANT_CARD_RESULT("%s 카드: %s - 결과: %d"),
넵! 끝부분에 `_FORMAT`을 통해서 포맷팅을 위한 메시지임을 표시해두겠습니다 ㅎㅎ

2023-03-09 04:42 UTC, Cl8D commented on src/main/java/domain/participant/ParticipantCard.java
> +    }
해당 메서드들은 대부분 Participant, 혹은 Dealer로부터 호출되는 메서드이기 때문에, 굳이 public으로 열 필요가 없다고 판단했어요! 접근제어자는 최대한 작게 하여 불필요한 외부에서의 접근을 막는 게 좋다고 생각하기 때문에, 같은 패키지 내의 클래스만 접근할 수 있도록 디폴트 접근제어자를 사용하여 막아두었습니다 :D

2023-03-09 04:46 UTC, Cl8D commented on src/main/java/domain/participant/ParticipantCard.java
> +    }
제가 질문을 잘못 이해한 것 같은데, 혹시 ACE가 여러 개인 상황이 어떤 걸 말씀하시는 것일까요?? 본 프로그램의 요구사항이 '블랙잭 게임'이라면 카드의 경우의 수는 정해져 있다고 생각해서 'ACE'를 표현하는 다른 값이 생길 수는 없을 것 같은데... 'ACE가 여러 개인 상황'이라는 게 어떤 것을 말씀하시는 건지 궁금합니다...!

2023-03-12 15:58 UTC, iphwade commented on src/main/java/domain/game/GameResult.java
> +    }
@Cl8D 
```
생성자를 raw하게 만들면 우선 테스트가 쉬워집니다. 위와 같이 작성되어 있다면 GameResult 클래스에 다른 메서드들이 생겨 테스트하게 된다면 그 메서드 테스트에서 GameResult 객체 생성 와중에 calculateResult 메서드의 로직까지 포함하여 테스트를 해야합니다.
```

요 부분은 제가 적절치 않은 예를 들었네요-! 

`생성자를 raw하게 만들면 우선 테스트가 쉬워집니다.`
 -> 이 말은 public하게 생성된 생성자와 정적 팩토리 메서드가 사용되지 않은 케이스에 적용되는 말입니다!
 -> 답변할 때 생성자를 raw 하게 만들면 뭐가 좋지 ? 라는 맥락으로 전달하다보니,,,! 
 -> 의뭉스럽게 답변하여 죄송합니다ㅠ 이렇게 이해가 가지 않는 케이스에 대해서는 더 질문해주시면 감사하겠습니다-!

2023-03-12 16:23 UTC, iphwade reviewed
리뷰 요청이 안오니까 질문을 해놓고 답변을 확인할 생각을 못했네요ㅠ
다음에는 조금 더 챙겨보도록 하겠씁니다-!

2023-03-12 16:23 UTC, iphwade commented on src/main/java/controller/GameController.java
> +        final List<Player> players = getPlayers();
@Cl8D 
좋은 근거가 되는 말씀이네요-! 

그치만 객체의 상태를 캡슐화하고 행동을 메서드화 하는 이유는 무엇일까요-?
위처럼 값을 getter 메서드로 반환하여 사용하게 되고 후에 요구사항에 변화가 있어 반환된 List<Player> players에 로직을 다시 추가해야하면 어떨까요? 다시 추적하여 getter로 반환되었음을 인지하고 코드를 고쳐 Players로 반환하게 한 뒤 변경이 필요한 곳에 다시 적용하는 과정이 필요하겠네요!
혹시 그 과정에서 getter로 반환되었다는 것을 인지하지 못하면 다시 Players로 생성할 수도 있겠군요-!

(물론 지금읜 져니의 방법이 잘못되었다는 것은 아닙니다-! 그냥 이렇게 생각을 해보면 어떨까 정도의 코멘트입니다-!)

2023-03-12 16:23 UTC, iphwade commented on src/main/java/domain/card/Deck.java
> +    }
https://dodop-blog.tistory.com/277

저는 대부분 요렇게 사용합니다.
주변에서는 어떻게 사용하시나요-?!

2023-03-12 16:23 UTC, iphwade commented on src/main/java/domain/participant/Participant.java
> +    }
넵!

우선 연결된 클래스의 단방향성은 항상 중요합니다.
클래스를 넘어서서 모듈로 봐도 컴포넌트로 봐도 의존성이 순환되고 있으면 많은 경우 문제를 발생시키기 좋습니다-!
아마 앞으로 미션을 하시면서 분명히 겪을 문제로 보여 지금은 그렇구나 하고 넘어가시면 후에 체감하시는 날이 있어보입니다-!

2023-03-12 16:23 UTC, iphwade commented on src/main/java/domain/participant/ParticipantCard.java
> +    }
A가 여러개인 상황도 존재할 수 있지않나요-?!

2023-03-12 16:23 UTC, iphwade commented on src/main/java/domain/participant/Players.java
> +        validatePlayerCount(playerNames);
생성자 -> 객체 전체가 공통적으로 지켜야할 규칙
정적 팩토리 메서드 -> 특정 입력과 함께 특수한 로직, 규칙이 필요할 때

저는 이런 기준을 두고 판단하긴합니다.