[1단계 - 블랙잭 게임 실행] 누누(송은우) 미션 제출합니다.
woowacourse/java-blackjack pull request #456
Opened 2023-03-03 08:45 UTC by be-student

안녕하세요 디디

1. view 에 필요한 데이터 형태가 복잡하고, 다양한 형태가 필요하기에, 이를 dto 형태로 전달해주려는 방식을 사용했는데, 생각보다 다양한 형식의 데이터가 필요했기에, 그 결과로 Players 안에 너무 다양한 형태의 getter 들이 존재하게 된 것 같은데요. 이 부분을 어떤 방향으로 개선해보면 좋을지 좋은 아이디어가 있으시면 말씀해주시면 감사하겠습니다
2. OutputViewSymbol 같은 경우에는 Result 타입과 1:1로 매칭해서, 그 결과를 String 형태로 반환해주는 기능을 하고 있는데요
view 를 통해 출력하기 위한 방식이 필요하기에, 당연히 변환해주는 장치가 필요한데, 현재 방식에 대해서는 어떤 식으로 생각하시는지가 궁금합니다
3. Controller 쪽에서 현재는 너무 많은 비즈니스로직을 알고 있는 느낌이 들어서, 이를 서비스 객체인 BlackJackGame 같은 방식으로 해결해보려고 했는데요. 이 방식을 사용했을 때, view 로 출력해주는 과정이 필요한 경우가 많아서, 제대로 사용하기 힘들었던 부분이 있었습니다. 컨트롤러에 있는 비즈니스 로직을 조금 분담해주는 비즈니스 객체를 만들 때, 출력이 얽혀있는 경우를 어떤 식으로 풀어가면 좋을지가 궁금합니다
![image](https://user-images.githubusercontent.com/80899085/222671477-79d32014-920e-4f11-a1ed-f66f0a1b8fd6.png)
4. 데이터를 넘겨주는 방식을 고민하다, dto 를 통해서 전달하는 방식을 사용했는데요 이때 dto 들에 네이밍이 적절하지 않았던 것 같은 부분이 있습니다. dto 에 적절한 네이밍을 하는 규칙이나, 그런 것들이 혹시 있나요?
5. dto 에다가 출력의 편를을 위해서 변환하는 작업을 했던 경우가 있는데요 이런 과정을 넣는 것에 대해서 어떻게 생각하시는지에 대해서 궁금합니다
ex) FinalResultDto
6.Players 객체에서 조회의 성능을 위해서는 현재 방식인 List<Player> 보다, Map<PlayerName(혹은 String), Player> 형태로 저장하는 방식이 더 효율적이라고 생각되는데요, Player가 자체적으로 PlayerName 을 가지고 있다고 생각했을 때, 조회의 성능만을 위해서 이런 방식으로 바꾸는 것은 어떻게 생각하시는지 궁금합니다

2023-03-04 09:27 UTC, fucct requested changes
안녕하세요 누누.

어려운 미션임에도 훌륭하게 구현해주셨습니다 :) 
전체적으로 package private 접근제어자를 많이 사용하셨는데, 과연 패키지 구조가 변경되었을때도 유효할지도 고민해보시면 좋을것 같아요. 

질문주신 부분을 순서대로 살펴보자면, 

1. Players가 결과 출력을 위한(Dto를 위한) 메서드를 가지지 않아야 된다고 생각합니다. 응답을 위해 가지고 있는 상태를 get할수는 있어야하나, 도메인의 상태값을 가지고 응답의 형태로 만들어주는역할을 두번째 질문에서 말씀하신 서비스 객체에게 맡길 수 있겠네요.

2. 말씀해주신 Symbol이나 Shape같은 Type들에 대해서는 업무환경에서도 의견이 분분합니다. Enum같은 Type에 한해서는 View와 Domain이 공유하도록 사용하자는 의견이 있고, 응답과 Domain Type 에 대해서는 1:1이라 하더라도 변환을 해줘야한다는 의견도 있습니다. 저는 개인적으로 누누께서 만들어주신대로 Output타입을 별도로 정의해주신 방식도 괜찮다고 생각해요. 다만 Output Type이 Domain Type을 필드로 가지기보단, 파라미터로 건네받아서  변환해주는 방식을 선택할 것 같습니다 :)

3. Service 계층에 대해서 좀 더 고민해보시면 좋을것 같습니다. Service 계층은 어떤역할을 해야할까요? Domain -> View 사이에 존재하는 중간 계층인 만큼 양 레이어간의 Context 변환이 주 담당일것입니다. 누누가 말씀하신것처럼 View로 출력하기 위한 Dto 생성 역할도 포함일테고, 각 도메인들을 비즈니스 흐름에 맞게 나열하는 역할도 하게 될거에요. 이런부분은 백번 듣는것보다, 한번 Service 계층을 개발해보시면서, 누누가 필요하다고 느끼는 역할들을 집어넣어보는걸 추천드립니다. 

4. 네이밍은 자유라고 생각해요 :) 다만 개인적으로는 Dto를 클래스 네임에 포함시키지는 않는 편입니다. 

5. DTO에 변환 로직이 있는건 자연스럽다고 생각해요. 다만 필드로 도메인을 가지고있지 않아야한다고 생각합니다. 왜 그래야하는지도 한번 생각해보시면 좋을것 같아요.

6. Map 형태가 필요하다고 느껴지신다고 객체의 구조를 바꾸기보단, Stream API를 이용해서 비즈니스에서 원하는 형태로 변환하여 사용할것 같아요. 상황에 따라 변환해주는 메서드를 Players 내에 위치시킬수도 있을것 같긴 합니다.

전체적으로 구현 잘해주시고, 고민도 많이 해주신것 같아서 디테일한 부분만 피드백 드렸어요! 반영해주시고, 모르겠는 부분은 코멘트 혹은 DM 부탁드리겠습니다.

2023-03-04 09:27 UTC, fucct commented on src/main/java/blackjack/domain/ParticipantResults.java
> +class ParticipantResults {
이 클래스가 도메인이 맞을까요? 어떤 역할을 가지고 있나요?

2023-03-04 09:27 UTC, fucct commented on src/main/java/blackjack/domain/ShuffledDeckFactory.java
> +        return new Deck(new ArrayDeque<>(cards));
Deque를 사용하신 이유가 있나요?

2023-03-04 09:27 UTC, fucct commented on src/main/java/blackjack/domain/Players.java
> +                .orElseThrow(() -> new IllegalArgumentException("없는 사용자 입니다"));
없는 사용자 예외가 반복된다면 커스텀 예외를 정의해보는것도 좋을것 같습니다 :)

2023-03-04 09:27 UTC, fucct commented on src/main/java/blackjack/domain/Deck.java
> +        return cards.remove();
cards가 비어있다면 어떻게 동작해야할까요?

2023-03-04 09:27 UTC, fucct commented on src/main/java/blackjack/dto/CardsScoreDto.java
> +public class CardsScoreDto {
Dto라는 네이밍은 레이어드 아키텍처의 전역에서 사용될 수 있기 때문에, 개인적으로 선호하지 않는것 같아요.   
도메인 - 서비스 간, 서비스 - 컨트롤러 간 등 어디서 사용되는지 혼란스러울 수 있기 때문이에요.
View를 위한 응답 객체라면 Response라는 네이밍을 주로 사용하는것 같습니다 :)

2023-03-04 09:27 UTC, fucct commented on src/main/java/blackjack/dto/CardsScoreDto.java
> +    private final List<Card> cards;
Dto가 도메인 모델인 Card를 가지고 있어도 괜찮을까요? 무슨 문제가 있을까요?

2023-03-04 09:27 UTC, fucct commented on src/main/java/blackjack/domain/CardPocket.java
> +        if (cards == null) {
empty인경우도 검증해줘야하지 않나요?

2023-03-04 09:27 UTC, fucct commented on src/test/java/blackjack/domain/CardPocketTest.java
> +class CardPocketTest {
CardPocket은 핵심 기능인 점수 계산 기능을 가지고 있어요. Ace 개수에 따른 점수를 검증하는 테스트가 필요해보입니다.

2023-03-04 09:27 UTC, fucct commented on src/test/java/blackjack/domain/PlayersTest.java
> +class PlayersTest {
최초 카드 제공 등 public 메서드 테스트를 추가해주세요!

2023-03-04 09:27 UTC, fucct commented on src/test/java/blackjack/domain/DeckTest.java
> +class DeckTest {
pop card 테스트도 필요해보이네요

2023-03-04 09:27 UTC, fucct commented on src/main/java/blackjack/controller/Repeater.java
> +class Repeater {
요 클래스가 정말 필요할까요?

2023-03-05 00:08 UTC, be-student commented on src/main/java/blackjack/controller/Repeater.java
> +class Repeater {
컨트롤러에서 사용하는 로직과는 약간 별개의 느낌이라서 분리하려고 해보았는데요
컨트롤러에 꼭 있어야 되는 로직은 아니라고 생각 했어요

2023-03-05 00:10 UTC, be-student commented on src/main/java/blackjack/dto/CardsScoreDto.java
> +    private final List<Card> cards;
항상 고민인 부분이었는데요
Card 까지는 아무것도 데이터가 없는 불변인 상태이기에, 이렇게 했던 것 같은데요
아무 로직이 없는 값객체 느낌이어도 dto 에 포함시키면 안되는 걸까요?

2023-03-05 00:11 UTC, be-student commented on src/main/java/blackjack/domain/CardPocket.java
> +        if (cards == null) {
그렇네요 감사합니다

2023-03-05 00:12 UTC, be-student commented on src/main/java/blackjack/dto/CardsScoreDto.java
> +public class CardsScoreDto {
아하 감사합니다 Response로 바꿔볼게요

2023-03-05 00:38 UTC, be-student commented on src/main/java/blackjack/domain/BlackJackConstant.java
> +class BlackJackConstant {
그것도 그렇네요
지금 사용하는 곳을 보면
1. 사용자가 드로우 할 수 있는 조건
2. 카드 포켓에서 점수를 계산하는 과정
3. 누가 이겼는지를 검사하는 과정

이렇게 3가지가 있는데요 이런 것을 생각해보면 각자 상수로 내부에서 가지고 있어도 괜찮아보이기도 하고, 아닌 것 같아보이기도 하네요
위 3가지 경우를 봤을 때, 이 클래스들이 각자 따로 가지고 있는 부분이 좋은지는 잘 모르겠어서 어떤 방향으로 바꾸어봐야 할지 고민이 되네요 
각자로 바꾸면, 각자 바꿔야 된다는 점이 단점이지만, 확실하게 하나의 역할만 한다는 장점이 있고
지금 방식으로 가면, 모두 하나의 상수를 가지고 공유할 수 있으니까요

2023-03-05 00:39 UTC, be-student commented on src/main/java/blackjack/domain/ShuffledDeckFactory.java
> +}
이 부분은 밑과 동일하게 for문의 2중 형태로 바꾸다보니 그렇게 된 것 같네요
그렇게 해볼게요

2023-03-05 00:40 UTC, be-student commented on src/main/java/blackjack/domain/ShuffledDeckFactory.java
> +        return cards;
그렇게 만들었을 때, 가독성이 생각보다 되게 안좋아 지는 느낌이 들어서 사용하지 않았는데요 
side effect를 만드는 함수를 만드는 것보다는 나을것 같아보이기도 하네요 감사합니다

2023-03-06 10:50 UTC, be-student commented on src/main/java/blackjack/domain/Players.java
> +        if (Set.copyOf(playerNames)
감사합니다

2023-03-06 10:53 UTC, be-student commented on src/main/java/blackjack/domain/ShuffledDeckFactory.java
> +        return new Deck(new ArrayDeque<>(cards));
Queue 를 구현하는 구현체 중에서, LinkedList 와 ArrayDeque 를 생각했는데요
이중에서 Queue 라는 것을 명시하기 위해서 생각하면 ArrayDeque 쪽이 더 좋아보였어요

2023-03-06 10:53 UTC, be-student commented on src/main/java/blackjack/domain/ParticipantResults.java
> +class ParticipantResults {
결과를 저장하고 있는 클래스라고 생각하는데요
결과를 저장만 하는 클래스는 도메인으로서는 애매한가요?

2023-03-06 10:54 UTC, be-student commented on src/main/java/blackjack/domain/Players.java
> +                .orElseThrow(() -> new IllegalArgumentException("없는 사용자 입니다"));
아하 감사합니다!

2023-03-06 10:54 UTC, be-student commented on src/main/java/blackjack/domain/Deck.java
> +        return cards.remove();
NoSuchElementException 이 발생하겠지만, 확실히 isEmpty() 로 메시지를 넣어주는 쪽이 적절해보이네요
감사합니다

2023-03-06 10:54 UTC, be-student commented on src/test/java/blackjack/domain/CardPocketTest.java
> +class CardPocketTest {
아하 넵 감사합니다

2023-03-06 10:54 UTC, be-student commented on src/test/java/blackjack/domain/PlayersTest.java
> +class PlayersTest {
넵 감사합니다 추가하겠습니다!

2023-03-06 10:55 UTC, be-student commented on src/test/java/blackjack/domain/DeckTest.java
> +class DeckTest {
네 여기도 추가해두겠습니다

2023-03-06 12:31 UTC, be-student commented
디디 2번째 요청드려요
되게 고민인 부분인데요 
1. 도메인이라는 패키지가 너무 많은 클래스가 존재하는 것 같아서 같이 쓰이는 클래스들끼리 묶어두려고 하는데요 패키지를 어떤 기준으로 나누면 좋을지가 고민이 되었습니다.
패키지를 나눌 때 어떤 기준으로 나누면 될지 좋은 아이디어를 주실 수 있으신가요?
2.  도메인과 view 간에 연결을 아얘 끊기 위해서 이상하게 했던 것 같은데요 이 부분을 어떻게 해야 더 좋은 결과가 나올지 궁금합니다

2023-03-06 15:23 UTC, fucct requested changes
안녕하세요 누누. 

전체적으로 제가 전달드린 피드백을 잘 이해하신것 같아요.
다만 일부 너무 복잡하게 생각하신 부분이 있어서 간단한 피드백 드렸습니다. 

그리고 질문주신 부분을 살펴보자면, 
1. 패키지 구조는 잘 작성해주신것 같아요. 도메인이라 함은 해결하고자 하는 문제이므로, 해결하고자 하는 문제가 다른경우 별도의 패키지를 정의하시면 좋을것 같다고 생각합니다. domain 패키지 하위에 Card, Participants를 분리하신것 좋은것 같습니다. Deck 같은것도 Card 패키지에 포함될 수 있을것 같다는 생각이 드네요.
여기서 한번 고민해봐야할 부분은 BlackJackGame은 어디에 들어가야하는가 입니다. 과연 이게 Domain일지도 한번 생각해보세요!

2. Domain과 View를 구현해주신 방법도 괜찮다고 생각합니다. 다만 변환로직이 Response객체가 Domain 객체를 받아서 수행하고 있고, Referee가 해주고 있는데, 이런걸 BlackJackGame으로 옮겨보시면 어떨까 생각이 들었습니다. 
또한 Controller에서 privae메서드로 View와 Domain생성 부분을 묶어놓으니 이해하기 쉽지 않은 부분도 있었습니다. 이런부분만 조심하시면 좋을것 같아요.

디테일한 부분들은 피드백으로 남겨드렸으니 확인부탁드립니다 :)

2023-03-06 15:23 UTC, fucct commented on src/main/java/blackjack/controller/BlackJackController.java
> +    }
Controller의 private 메서드가 아닌 blackJackGame의 역할이 아닐까 싶네요.

1. blackJackGame 에게 카드 분배를 시키고
2. blackJackGame 으로부터 초기 카드 상태를 리턴받아서 View에게 전달하고 
3. blackJackGame 에게 참가자들의 카드 draw를 시키고
4. blackJackGame 에게 dealer의 카드 draw를 시키고
5. blackJackGame 으로부터 최종 결과를 리턴받아 View에 전달한다

로 생각해볼 수 있을것 같아요.
전체적으로 View의 영역과 Domain의 영역이 private 메서드로 숨어있으니 이해하기 쉽지 않은것 같습니다.

2023-03-06 15:23 UTC, fucct commented on src/main/java/blackjack/domain/Deck.java
> +    public Card removeCard() {
메서드명이 어색한것 같네요. 기존 네이밍을 바꾸신 이유가 궁금합니다

2023-03-06 15:23 UTC, fucct commented on src/main/java/blackjack/domain/participant/exception/PlayerNotFoundException.java
> +public class PlayerNotFoundException extends RuntimeException {
👍♂️

2023-03-06 15:23 UTC, fucct commented on src/main/java/blackjack/domain/participant/Participants.java
> +
Referee 개념이 왜 생겼는지 설명해주실 수 있나요? BlackJackGame에서 충분히 담당할 수 있는 부분이라고 생각합니다 :)

2023-03-06 15:23 UTC, fucct commented on src/main/java/blackjack/response/CardConvertStrategy.java
> +public interface CardConvertStrategy {
인터페이스로 분리된 이유가 있을까요? 어떤식으로 확장될거라고 예상하셨나요?

2023-03-06 15:23 UTC, fucct commented on src/main/java/blackjack/response/ResultConvertStrategy.java
> +public interface ResultConvertStrategy {
이것도 인터페이스로 확장될 이유가 있나요?

2023-03-06 15:23 UTC, fucct commented on src/main/java/blackjack/response/ResultTypeResponse.java
> +public class ResultTypeResponse {
전체적으로 Shape, Symbol, ResultType같은 enum에 대해서 중복코드, 변환코드가 발생하고 있습니다.
이런부분이 번거로우시다면 정의해놓은 Shape, Symbol, ResultType의 field로 응답으로 적절한 값을 넣어주는걸 고려할 수 있을것 같아요.

2023-03-06 15:23 UTC, fucct commented on src/main/java/blackjack/domain/BlackJackRule.java
> +public class BlackJackRule {
Referee 개념과 BlackJackRule 개념이 합쳐지면 좋을것 같다는 생각이 들어요. 
또한 규칙같은 경우는 변경이 많은 부분이기 때문에, interface로 분리한다면 확장성 있는 설계가 될 수 있을것 같습니다.

2023-03-06 15:23 UTC, fucct commented on src/main/java/blackjack/domain/BlackJackRule.java
> +    public BlackJackRule(final int dealerScore) {
Rule이라는 규칙이 dealerScore를 필드로 받는건 좀 어색하다는 생각이 드네요. 오히려 승부를 계산하는 메서드의 파라미터로 받아야하지 않을까요?

2023-03-06 15:23 UTC, fucct commented on src/main/java/blackjack/response/FinalResultResponse.java
> +
굳이 Map을 응답받아서 한번 더 변환해주기보단, 애초에 파라미터로 변환된 값을 받는건 어떨까 싶네요

2023-03-06 15:55 UTC, be-student commented on src/main/java/blackjack/response/CardConvertStrategy.java
> +public interface CardConvertStrategy {
제이슨이 말한
블랙잭 미션에서 이모지(:스페이드:, :클럽:, :다이아몬드:, :하트1:)를 사용하면 미션의 난도가 더 높아지고 새로운 고민거리가 생길 거예요. :윙크:

라는 글을 보고서, 어떤 상황에서는 "스페이드" 라고 쓰고, 어떤 상황에서는 ♠️ 를 사용하도록도 변경할 수 있다고 생각했는데요
그렇게 했을 때, 변경을 편하게 할 방법을 생각해본 결과, 전략패턴으로 갈아끼우는 방식이 가장 편해보였습니다
i18n 처럼, 선택한 내용에 따라서 다른 방식으로 출력해주는 것이 가능해보였습니다

2023-03-06 15:56 UTC, be-student commented on src/main/java/blackjack/response/CardResponse.java
> + * 대부분의 Response 가 이 클래스를 통해서 symbol 과 shape 를 변경하는 구조로 되어있는데
이 부분도 고민이었는데요
리뷰하시는 입장에서는, 클래스마다 왜 이 클래스가 생겼고, 이 클래스가 가지고 있는 책임은 무엇인지에 대해서 적어주는 것이 편하지 않을까? 하는 생각이 들었는데 빼는게 좋은가요?

2023-03-06 15:56 UTC, be-student commented on src/main/java/blackjack/response/ResultConvertStrategy.java
> +public interface ResultConvertStrategy {
이것도 위에 있는 것처럼, 승무패 대신 WIN, TIE 같은 영어로도 바꿀 수 있도록 해보려고 했어요

2023-03-06 15:57 UTC, be-student commented on src/main/java/blackjack/response/ResultTypeResponse.java
> +public class ResultTypeResponse {
근데 그렇게 되면, 사실상 도메인 코드에 view 에 출력될 내용이 그대로 있는 것 같아서 마음에 걸렸는데, 이런 방식으로 해도 괜찮은가요?

2023-03-06 15:57 UTC, be-student commented on src/main/java/blackjack/domain/BlackJackRule.java
> +    public BlackJackRule(final int dealerScore) {
아하 그것도 확실히 그렇네요
파라미터로 받고 관리하도록 하겠습니다

2023-03-06 15:57 UTC, be-student commented on src/main/java/blackjack/response/FinalResultResponse.java
> +
아하 blackJackGame 에서 전부 변환하도록 변경하겠습니다

2023-03-06 15:59 UTC, be-student commented on src/main/java/blackjack/domain/Deck.java
> +    public Card removeCard() {
popCard 라는 쪽이, 너무 자료구조에서 사용되는 명칭이라는 느낌이 들어서, 다른 명칭으로 바꿔보자라는 생각을 했는데요
애매했던 것 같네요 다시 돌려놓겠습니다

2023-03-06 16:06 UTC, be-student commented on src/main/java/blackjack/domain/BlackJackRule.java
> +public class BlackJackRule {
아하 그것도 그렇네요 바꿔볼게요

2023-03-06 16:12 UTC, be-student commented on src/main/java/blackjack/controller/BlackJackController.java
> +    }
![image](https://user-images.githubusercontent.com/80899085/223166614-c7814d6b-669a-412c-81e0-260df425230d.png)
실제로 구현을 보게 되면 거의 대부분이 직접 blackJackGame 을 호출하는 부분이 많은데요
이 부분도 앞에 있는 것처럼 view 와 domain 의 부분이 한 메서드에 2개가 동시에 있는 문제이려나요...?

2023-03-06 16:15 UTC, be-student commented on src/main/java/blackjack/domain/participant/Participants.java
> +
이 부분도 조금 고민이었는데요
BlackJackGame 에서 점수 계산까지 처리하게 되면 한 객체에서, 
1. 점수 계산
2. 적절한 dto 형태로 변환
3. 컨트롤러에서 받는 메시지를 적절한 객체로 전달
이렇게 3가지 역할이나 하게되는 것 같아서 너무 책임이 많아보였떤 것 같아요

2023-03-07 10:00 UTC, be-student commented
안녕하세요 디디
이번에는 최대한 피드백을 반영해보려고 했는데요
아직도 controller 에서 view와 domain 간의 연결부분이 애매한 것 같네요
혹시 이 부분에 대해서 어떤 방향으로 해보면 좋을지 아이디어나, 참고 자료를 조금만 더 주실 수 있으신가요?

2023-03-07 15:59 UTC, fucct approved these changes
안녕하세요 누누

2번째 피드백중 반영안된 부분이 있는것 같아요.

View와 관련된 Strategy는 불필요하다고 생각이 듭니다.
Response 종류도 많다고 느껴지는데, DealerScoreResponse, InitialCardResponse, PlayerCardsResponse, PlayersCardsResponse등등 모두 Participant의 Card상태에 대한 응답이 아닐까 싶네요. 이런 부분은 공통화 해볼 수 있을것 같아요 :) 

나머지부분은 모두 확인했는데 크게 문제될 부분은 없는것 같습니다. 
Merge할테니 말씀드린 부분 2단계에서 모두 반영해주시면 좋겠습니다 :) 
수고많으셨습니다!

2023-03-07 15:59 UTC, fucct commented on src/main/java/blackjack/controller/BlackJackController.java
> +        drawDealerCards(blackJackGame);
draw하는 부분도 blackJackGame을 parameter로 보내기보단 blackJackGame을 호출하도록 하면 좋을것 같네요.

2023-03-07 15:59 UTC, fucct commented on src/main/java/blackjack/service/BlackJackGame.java
> +        final BlackJackRule blackJackRule = new BlackJackRuleImpl();
BlackJackRuleImpl을 메서드에서 생성하기보단 BlackJackGame 생성시 주입받아서 필드로 가지고 있으면 좋을것 같네요!

2023-03-07 15:59 UTC, merged

2023-03-08 03:17 UTC, be-student commented on src/main/java/blackjack/service/BlackJackGame.java
> +        final BlackJackRule blackJackRule = new BlackJackRuleImpl();
이 부분도 미션 요구사항인 인자 2개를 지키려다보니 어쩔 수 없이 된 것 같은데요
미션 요구사항을 준수하려다보니 이런 결과가 나왔던 것 같아요
메서드 파라미터로 넘겨주는 방향과, 필드로 가지고 있는 것을 비교해보고 선택해보겠습니다! 감사합니다

2023-03-08 03:17 UTC, be-student commented
진짜 많이 배운 순간이었어요
다양한 부분에 있어서 고민해볼 기회를 주셔서 되게 감사했습니다
2단계에서도 잘 부탁드려요!