[1단계 - 블랙잭 게임 실행] 엔초(권예진) 미션 제출합니다.
woowacourse/java-blackjack pull request #458
Opened 2023-03-03 08:45 UTC by kwonyj1022

안녕하세요 배럴! 리뷰 잘 부탁드립니다.

2023-03-05 01:42 UTC, knae11 requested changes
안녕하세요. 엔초!

작성해주신 내용 보고 코멘트 남겨보았습니다 :)

2023-03-05 01:42 UTC, knae11 commented on .gitmessage.txt
> +Co-authored-by: kwonyj1022 <kwonyj1022@naver.com>
커밋에서 제외될 수 있도록 해보면 좋겠네요 :)

2023-03-05 01:42 UTC, knae11 commented on README.md
> +    - [X] 이름이 `딜러`이면 `IllegalArugmentException`을 던진다.
어떤 예외를 던질지는 변경될 수 있는 부분이므로 문서에 구체적인 예외까지는 표현하지 않으셔도 될 듯 싶습니닿ㅎㅎㅎ

2023-03-05 01:42 UTC, knae11 commented on src/test/java/blackjack/domain/PlayerTest.java
> +    @ParameterizedTest
ParameterizedTest의 name 속성을 이용하면 테스트 네이밍을 좀 더 가독성 있게 만들 수 있습니다 :)

2023-03-05 01:42 UTC, knae11 commented on src/main/java/blackjack/controller/BlackJackController.java
> +import blackjack.domain.Suit;
최대한 controller에 도메인이 노출되지 않도록 `게임을 진행하는 객체`를 만들어보는건 어떨까요~?

2023-03-05 01:42 UTC, knae11 commented on src/main/java/blackjack/view/InputView.java
> +    private static final Scanner scanner = new Scanner(System.in);
사용한 스캐너에 대한 자원정리도 해주세요 :)

2023-03-05 01:42 UTC, knae11 commented on src/main/java/blackjack/domain/Cards.java
> +    }
각 People이 가지고 있는 것도 Cards 이고, 게임판에서 사용되는 전체 카드도 Cards 인가요? 둘을 구분해 보면 좋지 않을까요? 어떤게 사용자들의 손에 들어가지 않은 카드이고, 어떤게 사용자들이 가지고 있는 Cards인지 구분하면 역할도 좀 더 분명하게 나뉠 수 있을 것으로 생각되네요. :)

2023-03-05 01:42 UTC, knae11 commented on src/main/java/blackjack/domain/People.java
> +public class People {
다소 광범위한 네이밍 같습니다. 여기서 의미하는 내용은 게임에 참여하는 사람들을 의도했다고 생각하는데요. 사람들이라고 하면 게임에 참여하는 사람들이라는 인식이 잘 안 드네요.

2023-03-06 05:48 UTC, kwonyj1022 commented on .gitmessage.txt
> +Co-authored-by: kwonyj1022 <kwonyj1022@naver.com>
.gitignore에 추가하였습니다!

2023-03-06 05:49 UTC, kwonyj1022 commented on README.md
> +    - [X] 이름이 `딜러`이면 `IllegalArugmentException`을 던진다.
넵 어떤 예외를 던질지 적지 않고 `예외가 발생한다`라고 수정하였습니다.

2023-03-06 06:00 UTC, kwonyj1022 commented on src/main/java/blackjack/domain/People.java
> +public class People {
People 대신 Participants로 수정하였습니다!

2023-03-06 06:17 UTC, kwonyj1022 commented on src/main/java/blackjack/domain/Cards.java
> +    }
각 참가자들이 가지고 있는 것은 Cards로 하고, 게임에 사용되는 전체 카드는 Deck으로 나누어보았습니다!

2023-03-06 06:23 UTC, kwonyj1022 commented on src/main/java/blackjack/view/InputView.java
> +    private static final Scanner scanner = new Scanner(System.in);
InputView에 스캐너를 close하는 메서드를 만든 후 controller에서 입력 받는 로직이 다 끝난 후 해당 메서드를 호출하도록 수정하였습니다!

2023-03-06 08:23 UTC, kwonyj1022 commented on src/test/java/blackjack/domain/PlayerTest.java
> +    @ParameterizedTest
몰랐던 개념이었는데 좋은 방법인 것 같습니다!

2023-03-07 06:26 UTC, kwonyj1022 commented on src/main/java/blackjack/controller/BlackJackController.java
> +import blackjack.domain.Suit;
`BlackjackGame` 객체를 만들어서 `controller`에는 `BlackjackGame`만 노출되고, 데이터 전달에는 dto를 사용하는 것으로 수정했습니다!

2023-03-07 08:57 UTC, kwonyj1022 commented
`controller`에 있던 메서드 일부를 `BlackjackGame`으로 옮기는 과정이 어려웠습니다.
게임 진행 상 중간중간 입력을 받고 출력을 하기 때문에 `controller`와 `BlackjackGame`을 왔다갔다하는데다가, 중간에 `dto`가 필요하면 `dto` 구현하고 돌아오고 하다보니 저도 헷갈렸습니다. 두 번정도 이전 커밋으로 되돌리고 다시 구현했는데, 그러다보니 오래걸렸습니다.
제대로 구현했는지도 잘 모르겠습니다.

구현하면서 궁금한 점이 하나 있습니다.
`OutputView`에서도 `domain`을 모르게 하기 위해 `dto`의 `getter`는 `String`을 반환하도록 구현했는데, 괜찮은지 궁금합니다.

`dto`의 목적은 도메인 로직 없이 필요한 데이터만을 전달하기 위한 것으로 알고 있습니다.
지금은 `dto`를 전달 받는 곳이 `OutputView`이기에 출력을 위해서만 사용되므로 `String`으로 전달받아도 문제가 발생하지 않습니다. 

그런데 만약 이렇게 구현한다면, `dto`를 출력을 위한 객체가 아닌, 다른 객체로 넘기는 경우 `getter` 가 `String`을 반환한다면 `dto`에 있는 객체를 사용할 수 없기 때문에 문제가 생길 수 있다고 생각합니다.

`dto`의 `getter`가 `String`을 반환하는 것이 적절하지 않다면, `OutputView`에서 `domain`을 모르게 하기 위해 어떤 방법을 사용해야 할까요?
`controller`에서 값을 `String`으로 변환하려면 결국 `controller`가 `domain`을 알아야 하기 때문에 어떤 방법을 사용해야할지 고민이 됩니다.

2023-03-08 21:49 UTC, knae11 commented
안녕하세요 엔초!
view에서는 도메인을 모르는 것이 좋습니다. 다만 getter에서 String으로 변환하는 것이 아니라, view 용 객체들을 dto측에 만들어주고 해당 객체를 필드로 가져보는건 어떨까요? 그러면 getter에도 변환로직없이 가능할 것 같습니다! :)

2023-03-08 21:51 UTC, knae11 commented
![image](https://user-images.githubusercontent.com/66905013/223858514-07d79970-2294-4511-a8e3-159d2346b874.png)

도메인이 어떤 역할을 하는지 테스트코드를 통해 깔끔하게 보이네요! 💯 👍 👏

2023-03-08 21:53 UTC, knae11 approved these changes
안녕하세요! 엔초!

리팩터링 작업은 어땠나요? 1단계 미션 잘 수행해 주셔서 merge 하겠습니다!
2단계도 화이팅이에요~~! :D

2023-03-08 21:54 UTC, merged