[1단계 - 블랙잭 게임 실행] 이오(이지우) 미션 제출합니다.
woowacourse/java-blackjack pull request #460
Opened 2023-03-03 08:46 UTC by LJW25

안녕하세요 바다, 이오입니다!

이번 미션의 주제인 클린코드를 위해 노력했지만, 몇가지 요구사항으로 인해 부족한 코드를 보여드리게 된 것 같네요 😂
리뷰 감사드리고, 여유가 되실 때 질문을 읽어주시면 감사하겠습니다!

2023-03-05 04:30 UTC, xrabcde requested changes
안녕하세요 이오 ~ 바다입니다 🌊
블랙잭 미션을 함께 하게 되어 반갑습니다 ㅎㅎ
어려운 미션인데도 요구사항에 맞게 잘 구현해주셨네요 👍🏻
몇 가지 리뷰 남겼는데 확인해보시고 궁금한 점은 언제든 코멘트나 DM으로 알려주세요~

추가적으로 현재는 입력값 검증을 실패하면 바로 게임이 종료되어버리는데 
재입력 기회를 주도록 개선해보면 좋을 것 같아요 :)

<img width="400" alt="image" src="https://user-images.githubusercontent.com/56033755/222941479-0b51ab47-0247-4bb5-aedd-1a45b8702fcd.png">

<img width="400" alt="image" src="https://user-images.githubusercontent.com/56033755/222941906-e857c853-d238-4fdd-a775-200756553a71.png">

참여자의 이름으로 "딜러" 를 사용하려는 경우에 대한 예외처리도 필요해보여요 ~

<img width="400" alt="image" src="https://user-images.githubusercontent.com/56033755/222941867-83543c9a-4e0c-4df3-9173-482bf1ea6bd7.png">

2023-03-05 04:30 UTC, xrabcde commented on src/main/java/blackjack/domain/Participant.java
> +    }
비슷한 동작을 하는 함수는 이름을 통일해주면 좋을 것 같아요 ~!

2023-03-05 04:30 UTC, xrabcde commented on src/main/java/blackjack/domain/GameResult.java
> +    private final Map<Result, Integer> dealerResults = new HashMap<>();
`EnumMap` 을 적용하기 좋아보이네요 ㅎㅎ

2023-03-05 04:30 UTC, xrabcde commented on src/main/java/blackjack/domain/Name.java
> +        }
이름에 들어간 공백을 꼼꼼하게 처리해주셨네요 👍🏻
[String.trim](https://learn.microsoft.com/ko-kr/dotnet/api/system.string.trim?view=net-7.0) 에 대해서도 학습해보시면 좋을 것 같아요 ~

2023-03-05 04:30 UTC, xrabcde commented on src/main/java/blackjack/domain/Name.java
> +        validate(name);
무엇을 validate 하는 걸까요? 더 친절한 이름을 지어주세요 ~

2023-03-05 04:30 UTC, xrabcde commented on src/main/java/blackjack/view/InputView.java
> +    private InputView() {}
생성자가 생략되면 기본 생성자가 존재하게돼서 따로 만들어 주실 필요는 없습니다!

2023-03-06 05:34 UTC, LJW25 commented on src/main/java/blackjack/controller/BlackJackController.java
> +            closeGame(dealer, players);
저 또한 처음에 BlackjackGame을 만들려고 계획하였으나 인스턴스 변수가 2개로 제한되어 있어 Game 내에서 카드, 딜러, 플레이어를 변수로 가질 수 없다는 한계로 현재의 형태로 구현했습니다!
딜러, 플레이어를 하나로 묶어 Participants 리스트의 형태로 변형하여 리팩토링 해보겠습니다 :)

2023-03-06 06:10 UTC, LJW25 commented on src/main/java/blackjack/controller/BlackJackController.java
> +        Validator.getInstance().validatePlayerNames(playerNames);
playerName의 중복을 검증해주기 위함이었습니다! 일급컬렉션인 Players의 불변성을 보장해주기 위해, 만들어진 List<Player>를 할당해주기 때문에 그 전 단계에서 미리 중복을 검증해줘야했기 때문입니다.
구조를 변경한다면 Participants 클래스를 생성 후 해당 클래스 내에서 Player 이름의 중복을 검증하도록 구현할 수 있을 것 같습니다.

2023-03-06 07:08 UTC, xrabcde commented on src/main/java/blackjack/domain/Trump.java
> +    }
블랙잭 게임은 무작위로 셔플된 카드덱 안에서 랜덤한 카드를 뽑는 로직인데 
"올바른 카드"를 전달한다는 게 어떤 이유에서 필요한가요? 
단순히 테스트 편의성 때문이라면 테스트 방식을 바꾸는 방법도 고려해 볼 수 있겠네요 ☺️

랜덤한 카드를 뽑기 위해 numberGenerator를 생성하는 것보다
자바의 컬렉션을 잘 활용하면 셔플된 카드에서 첫번째 카드만 뽑는 행위를 더 직관적으로 구현할 수 있을 것 같아요 :)

2023-03-07 16:39 UTC, LJW25 commented
안녕하세요 바다! 이오입니다.
말씀해주신 내용 반영하여 리팩토링 완료하였습니다 😊
상당히 많은 부분이 바뀌어..ㅎㅎ 아래에 따로 변경된 사항을 목록으로 정리하였습니다!
구현을 하면서 몇가지 질문드리고 싶은 내용이 있었는데, 해당 부분에 코멘트로 남기도록 하겠습니다. 
시간내어 리뷰해주셔서 감사합니다 :)

---
### 변경 사항
- 도메인 내부 패키지 분리
    - card, participant, result
- 카드 관련 클래스 이름 변경
    - Trump → Deck
    - TrumpNumber →CardNumber
    - TrumpShape→CardShape
- Participants 클래스 생성
    - 딜러와 플레이어를 포함
    - 플레이어 이름 중복 예외 처리
- BlackJackGame 클래스 생성
    - Deck, Participants 포함
    - 기존에 Controller에 있던 기능 중 View를 필요로 하지 않는 기능을 옮김.
- 예외 발생시 재입력 기능 구현
    - Retryable 인터페이스 생성 ([참고출처](https://dev-dongmoo.tistory.com/14))
    - 입력 요청 메세지 출력 위치 변경(OutputView→InputVIew)
- Hit 여부를 입력받는 방식 변경
    - String → Boolean
- 카드 뽑는 방식 변경(랜덤 인덱스 → 셔플)
- 플레이어의 이름이 딜러인 경우 예외 처리
- dealResults를 EnumMap으로 변경
- 이름 공백 검증 방식 변경(trim)
- 그 외 기타 메소드 분리 및 메소드명 변경, 불필요한 코드 삭제

2023-03-07 16:48 UTC, LJW25 commented on src/main/java/blackjack/domain/participant/Participant.java
> +    }
해당 메소드를 구현 할 때에 getCardNames가 Participant 내에 있어도 될까?라는 고민을 많이 했었습니다.
현재 이 메소드는 participant가 가진 카드를 출력 할 때, 해당 카드의 이름을 알려주기 위해 만든 메소드인데요

    1. 참여자가 가지고있는 정보를 넘겨주는 것일 뿐이기 때문에 괜찮다.
    2. 참여자의 책임이 아닌 메소드가 잘못된 위치에 있는 것인다.
      
라는 두가지 방향 중에서 고민했었습니다. 혹시 바다는 어느 쪽이라고 생각하시나요?

2023-03-07 17:06 UTC, LJW25 commented on src/main/java/blackjack/domain/participant/Dealer.java
> +    private static final int MAX_SCORE_TO_RECEIVE = 16;
이번 블랙잭 미션에서는 게임의 룰과 관련된 많은 상수들을 사용하였습니다.
이러한 (룰에 관한) 상수들은 각각 적용되는 부분이 다르지만 어떻게 보면 블랙잭 게임이라는 전체의 룰이기도 해서, 상수를 관리하는 별도의 클래스가 필요할 지에 대하여 고민중에 있습니다.

1. 적용되는 클래스에 각각 선언해 준다면: 관련된 상수를 바로 확인할 수 있다는 장점이 있을 것 같습니다.
2. 별도의 클래스를 만들어 룰에 관한 모든 상수를 관리한다면: 게임의 규칙이 변경되는 상황이 발생했을 때 수정이 쉬울 것 같습니다. 또한, 반복적으로 사용되는 숫자(21)를 매번 선언 할 필요가 없어집니다.

현재는 블랙잭의 룰이 변경 될 가능성이 없다고 보았기 때문에 1번의 방법을 사용하였지만, 상수를 한번에 관리할 수 있다는 장점 탓에 2번으로 변경하는 방향도 고민 중에 있습니다. 혹시 추가로 고려해야 할 사항이 있을까요?

2023-03-07 17:22 UTC, LJW25 commented on src/main/java/blackjack/view/InputView.java
> +    }
바다가 남겨주신 내용과 이전 사다리 미션에서 리뷰어님께 받았던 [리뷰](https://github.com/woowacourse/java-ladder/pull/175#discussion_r1116873327)를 함께 고려하여, view에서 명령어를 판단하여 boolean을 반환하는 형식으로 구현하였습니다!

2023-03-08 08:27 UTC, Combi153 reviewed
코드 잘 보고 갑니다! 정말 잘하시는 것 같아요 앞으로 같이 더 성장해봐요! 😀😀😀

2023-03-08 08:27 UTC, Combi153 commented on src/main/java/blackjack/controller/BlackJackGameController.java
> +        closeGame(blackJackGame);
메서드 이름이 참 깔끔해서 눈에 잘 들어와요 👍

2023-03-08 08:27 UTC, Combi153 commented on src/main/java/blackjack/domain/card/Deck.java
> +    private final List<Card> cards = new ArrayList<>();
카드 덱 개념이라면 Stack 자료구조를 사용하는 게 더 어울리지 않을까요? List를 사용하신 이유가 궁금합니다!

2023-03-08 08:27 UTC, Combi153 commented on src/main/java/blackjack/domain/participant/Score.java
> +    private void handleBust(List<CardNumber> cardNumbers) {
신선한 방법인 것 같아요 많이 배워갑니다! 🙂

2023-03-08 08:27 UTC, Combi153 commented on src/main/java/mission/SimpleLinkedList.java
> +public class SimpleLinkedList<TYPE> implements SimpleList<TYPE> {
멋있습니다!

2023-03-09 14:58 UTC, xrabcde approved these changes
안녕하세요 이오 ~ 바다입니다 🌊
코멘트를 꼼꼼히 반영해주셨네요 ㅎㅎ 변경내용을 정리해주셔서 리뷰가 수월했어요 :)
추가 코멘트 몇 가지 남겼으니 확인해보시고 
다음 단계 진행하시면서 같이 반영해주세요 ~ !
2단계에서 만나요 🙌

2023-03-09 14:58 UTC, xrabcde commented on src/main/java/blackjack/domain/participant/Player.java
>          return score.getScore() <= MAX_SCORE_TO_RECEIVE;
able 검사 조건이 21 이하인가요 미만인가요?

<img width="330" alt="image" src="https://user-images.githubusercontent.com/56033755/224055847-0f75c7f0-475c-469f-b8b1-1064a2e6fc11.png">

2023-03-09 14:58 UTC, xrabcde commented on src/main/java/blackjack/util/Retryable.java
> +    }
옹 재입력 기회를 주기 위해 새로운 방법을 시도해주셨네요 ! 
아래 요구사항도 챙겨볼까요?

- indent(인덴트, 들여쓰기) depth를 2를 넘지 않도록 구현한다. 1까지만 허용한다.

2023-03-09 14:58 UTC, xrabcde commented on src/main/java/blackjack/view/InputView.java
> +        throw new IllegalArgumentException(PLAYER_INTENTION_ERROR_MESSAGE);
예외케이스를 먼저 검증하고 `return input.equals(HIT_COMMAND);` 와 같은 형태로 구조를 바꾸면
분기문을 개선할 수 있을 것 같아요 ㅎㅎ

2023-03-09 14:58 UTC, xrabcde commented on src/test/java/blackjack/domain/BlackJackGameTest.java
> +        Participants participants = new Participants(List.of("IO", "Bada"));
💙

2023-03-09 14:58 UTC, xrabcde commented on src/test/java/blackjack/domain/BlackJackGameTest.java
> +    static BlackJackGame blackJackGame;
접근제어자 확인해주세요 ~!

2023-03-09 14:58 UTC, xrabcde commented on src/test/java/blackjack/domain/participant/PlayerTest.java
> +}
이런 테스트에서 카드를 뽑는 기준이 되는 경곗값을 테스트하면
실수를 줄일 수 있겠네요 ㅎㅎ

2023-03-09 14:58 UTC, xrabcde commented on src/main/java/blackjack/domain/BlackJackGame.java
> +    public static final int INITIAL_CARD_COUNT = 2;
접근제어자 확인해주세요 ~!

2023-03-09 14:58 UTC, xrabcde commented on src/main/java/blackjack/domain/participant/Dealer.java
> +    private static final int MAX_SCORE_TO_RECEIVE = 16;
개인적으로 상수를 별도의 클래스로 분리하는 것보다는 
해당 상수를 사용하는 클래스의 상위에 그때 그때 선언해주는 것을 선호하는 편입니다 
[이 글](https://www.baeldung.com/java-constants-good-practices)의 3.2 부분을 읽어보시면 좋을 것 같아요 :)

2023-03-09 14:58 UTC, xrabcde commented on src/main/java/blackjack/domain/participant/Participant.java
> +    }
코멘트를 남겨주신 부분은 참여자가 자신의 카드 리스트들을 넘겨주고 있기 때문에 크게 문제가 된다고 느껴지진 않아요 

여기서 좀 더 개선을 해본다면, 현재 Card 의 getCardName 이라는 함수는 출력형태로 바꿔주기 위해 작성하신 것 같아요. 
출력 형태가 바뀐다면 domain 패키지를 수정하는 상황이 생길 것 같은데 이오는 어떻게 생각하시나요~?

2023-03-09 14:58 UTC, merged

2023-03-10 00:40 UTC, LJW25 commented on src/main/java/blackjack/domain/participant/Player.java
>          return score.getScore() <= MAX_SCORE_TO_RECEIVE;
미션 요구사항에 따른 21 이하입니다! 
> 게임을 시작하면 플레이어는 두 장의 카드를 지급 받으며, 두 장의 카드 숫자를 합쳐 21을 초과하지 않으면서 21에 가깝게 만들면 이긴다. 21을 넘지 않을 경우 원한다면 얼마든지 카드를 계속 뽑을 수 있다.