[1단계 - 블랙잭 게임 실행] 도기(김동호) 미션 제출합니다.
woowacourse/java-blackjack pull request #475
Opened 2023-03-03 08:54 UTC by kdkdhoho

2023-03-04 13:56 UTC, sihyung92 requested changes
안녕하세요 도기! 지금 시기에 테코톡은 매우 초반일 것 같은데, 잘 발표하셨나요? ☺️ 바쁜 와중에 미션도 하시느라 고생하셨어요!
커밋을 잘게 쪼개주시기 위해 노력하신게 보이네요 :) 
다만 말씀처럼 마감에 쫓겼다는게 느껴지는 부분도 더러 있었는데요, 그래도 어려운 게임을 제한된 시간에 만드신 것에 박수를 보냅니다 ㅎㅎ

질문에 대한 답변입니다!

### 일급 컬렉션 캡슐화
오 리뷰에서도 남긴 부분인데요, `dealer.getPlayers().getPlayers()` 가 캡슐화를 지키는 것 같다고 말씀해주셨네요. 저는 반대로 캡슐화가 깨진다고 생각하는데요, dealer를 사용하는 객체 입장에서는 가지고 있던 선수들이 `Players` 타입이었단 건 TMI일 수 있습니다. 디미터의 법칙을 학습 및 적용해보시고 또 질문해주셔요 ㅎㅎ

### MVC 패턴 위배?
MVC 패턴을 지켜야 한다는 요구사항이 있었나욥?
디자인 패턴들은 특정한 문제를 해결하기 위한 선배들의 노하우입니다. 그러므로 집중해야할 건 해당 패턴이 해결하고자 하는 문제와 내 시스템이 연관이 있는가? 입니다.

블랙잭 게임을 만드셨는데, 해당 게임은 현재 콘솔을 통해서만 동작하네요. InputView와 OutputView같은 객체 없이 각 도메인 객체 내에서 그때그때 System.out.println()을 해주시면 훨씬 깔끔한 코드가 됩니다.

다만 요즘 dos 시대는 지나서 콘솔환경에서 게임할 일이 거의 없죠..^^; 모바일이나 웹 환경도 지원 가능해야 할 가능성이 높습니다. 그러면 콘솔 의존적인 코드를 짜면 안 되겠죠. 

반대로 콘솔 출력에서 블랙잭 게임 객체들을 의존하는 건 문제 없습니다. (매우 개인적 견해입니다 👍) 해당 콘솔이 블랙잭 게임 외에 재사용될 가능성이 없기 때문입니다. 저라면 블랙잭 도메인 패키지에 있는거 다 갖다가 붙여서 controller에서 복잡한 convert 로직을 안 거치게 했을 것 같아요.

만약 콘솔 출력이 여러 게임을 출력할 수 있어야 했다면 도메인과 분리하고자 노력했을 것 같습니다 :) 
구현하고자 하는 시스템이 어떤 특징이 있는지, 특정 패턴을 적용했을 때 가져갈 수 있는 이득은 어떤 게 있는지 판단해보시고 적용하는 연습을 많이많이 해보셨으면 좋겠네요~!

### enum객체의 출력용 기능
enum은 미리 정의된 객체 인스턴스의 모임인데요, 해당 객체가 무엇을 위한 객체였느냐에 따라 답변이 달라질거 같습니다 :) 출력용 enum이면 출력용 로직이 온당하겠지요

### Java SDK에 대한 테스트
저도 SDK 자체 에 대한 테스트는 안 하는 것 같아요. (Java Random이 진짜 Random인지 확인해본다던지)
다만 잘 모르던 클래스의 동작을 활용해보기 위한 학습테스트는 합니다 :) 

### PlayersFactory의 필요성
Factory 패턴은 생성 자체가 복잡할 때 한번씩 쓰는데요, 저는 두 방법 모두 상관없다고 생각해요 ㅎㅎ
다만 Players Factory로 생성하기로 의논하셨다면 Players의 생성자는 Factory를 통해서만 가능하도록 수정하셨어야 할 것 같습니다. 현재는 생성자를 통해 validate를 거치지 않고 바로 생성할 수 있네요~!

조금 리뷰가 늦고 말았습니다~! 리뷰 확인해보시고 질문있으면 DM이나 다음번 리뷰에 코멘트로 남겨주세요~~ 화이팅~~~

2023-03-04 13:56 UTC, sihyung92 commented on src/main/java/blackjack/view/OutputView.java
> +        System.out.println("딜러는 16이하라 한장의 카드를 더 받았습니다.");
딜러의 상한선이 16이 아니라 다른 값으로 변경되면 깜박 놓칠수도 있을것 같습니다 :)

2023-03-04 13:56 UTC, sihyung92 commented on src/main/java/blackjack/controller/BlackjackController.java
> +        return scores;
여기도 즉시 반환이 가능해보이네요 :) 
```suggestion
       return players.stream()
                .map(Player::calculateTotalScore)
                .collect(Collectors.toList());
```

2023-03-04 13:56 UTC, sihyung92 commented on src/main/java/blackjack/view/OutputView.java
> +        System.out.println("딜러: " + dealerResult.get(0) + "승 " + dealerResult.get(1) + "무 " + dealerResult.get(2) + "패 ");
매직넘버 모두 수정해주세요!

2023-03-04 13:56 UTC, sihyung92 commented on src/main/java/blackjack/view/OutputView.java
> +    }
이 부분은 눈으로 읽었을 때 어떤 결과를 출력할지 예상하기가 매우 어렵습니다 😢
가독성 좋게 수정해볼까요?

2023-03-04 13:56 UTC, sihyung92 commented on src/main/java/blackjack/domain/participant/Dealer.java
> +    }
List<Integer>가 승무패 순서로 이루어져있다는 걸 해당 코드를 이용하는 사람이 어떻게 알 수 있을까요?

2023-03-04 13:56 UTC, sihyung92 commented on src/main/java/blackjack/domain/card/Cards.java
> +        if (score + MAKE_ACE_BIGGER_SCORE <= BLACKJACK_SCORE_CONDITION) {
BLACKJACK_SCORE_CONDITION - MAKE_ACE_BIGGER_SCORE의 결과물인 11을 상수로 만들어 비교해주는 게 낫지 않을까요? 상수를 확인하고 머릿속으로 연산을 해야 했습니다!

2023-03-04 13:56 UTC, sihyung92 commented on src/main/java/blackjack/domain/card/Deck.java
> +            card = new Card(number, pattern);
잘하면 A 에이스가 21장 나올수도...!?

2023-03-04 13:56 UTC, sihyung92 commented on src/main/java/blackjack/domain/participant/Players.java
> +    public void receiveSettingCards(List<Card> settingCards) {
해당 코드는 Player의 2배 이상의 size를 받는 것이 가정된 코드입니다. 하지만 방어코드가 없기 때문에 더 작은 사이즈의 카드가 들어오면 IndexOutOfException이 발생하겠네요 :)

2023-03-06 06:26 UTC, kdkdhoho commented on src/main/java/blackjack/domain/card/Number.java
> +    public static int convertNumberToScore(Number number) {
구현 당시엔 카드의 숫자도 가지고, 점수 계산에 대한 메서드를 따로 만들자는 쪽으로 얘기가 나와서 number라는 필드를 가지게 됐습니다.
하지만, 객체가 꼭 현실 세계를 100% 반영하지 않고 필요한 내용만 담겨져 있는 것이 더 좋다고 생각되네요 🙂

2023-03-06 06:32 UTC, kdkdhoho commented on src/main/java/blackjack/domain/card/Number.java
> +    private final int number;
그럴 필요는 없었지만 현실 세계를 반영하고자는 목적이 있어서 number 필드를 추가했습니다. 그리고 number를 통해 카드의 번호를 파악하기 위해 생성하였는데요. 막상 구현하고 보니 number보다 score가 주된 관심사더라고요 🥲
score로서 이용하도록 수정해보겠습니다 !

2023-03-06 07:38 UTC, kdkdhoho commented on src/main/java/blackjack/domain/participant/Players.java
> +    public Map<Player, Result> decideResults(int dealerScore) {
혹시 좋다고 하신 이유에 대해 말씀해주실 수 있으실까요?? 궁금해요!

2023-03-06 07:50 UTC, kdkdhoho commented on src/main/java/blackjack/domain/participant/Participant.java
> +public class Participant {
추상 클래스에 대한 지식이 부족했던 것 같아요. 꼭 공부해보겠습니다!

2023-03-07 05:44 UTC, kdkdhoho commented
안녕하세요 웨지 🥔
남겨놓은 기술부채와 Garbage Code들 덕분에 리팩터링이 다소 오래 걸렸네요 😅
게다가 기존에 시도해보지 않은 다양한 시도들을 해보려는 노력에 시간이 조금 더 걸렸던 것 같아요.

이번 리팩터링에는 읽기 좋은 코드는 당연시하며 **예측 가능한 코드**가 되도록 노력 (불변)했습니다.
또, 약간의 성능의 이점을 고려하여 **`Deck`을 싱글톤**으로 구현해보았습니다.

중간중간 수정 할 요소들이 많아지다보니 커밋 단위가 다소 이상하게 되었어요.. 이 부분은 반성하겠습니다 😭

2023-03-07 16:04 UTC, sihyung92 requested changes
테스트가 실패하고 있어요 도기!! 🥺
원래는 테스트 수정 요청을 먼저 드리는데 실수로 리뷰를 먼저 해버렸습니다(?)
리뷰 반영 및 테스트 수정 후 재 요청해주셔요!

그리고 추가 질문이 생기면 코멘트로도 달아주시면 감사하겠습니다~!

### 서비스 규모가 커지거나 도메인 변경 가능성이 많은 경우
네 서비스 규모가 커지면 자연스럽게 view과 domain의 변경 사항이 많아지는데요, 이런 경우 중간계층들이 있으면 양쪽의 변경사항 여파를 절충할 수 있다고 생각합니다 :>

2023-03-08 03:00 UTC, kdkdhoho commented on src/main/java/blackjack/domain/card/Cards.java
> +        return cards.size() == BLACKJACK_SIZE_CONDITION
네! 조사해보길, 처음 받은 2장의 카드의 총점이 21점인 경우에 **블랙잭**이라고 한다는 것을 알게 되어서 추가했습니다.

하지만 현재 단계의 요구사항에서는 필요없는 조건이라서 삭제했습니다 !!

2023-03-08 03:09 UTC, kdkdhoho commented on src/main/java/blackjack/domain/card/Deck.java
> +    private static Deck instance;
헉.... 이런 문제가 발생할거라곤 생각하지 못했네요.. 😭
싱글톤 패턴에 대해 깊게 알지 못하고 사용하다보니 이런 문제가 발생한 것 같아요..
해결하고 싱글톤 패턴에 대해 공부하겠습니다 !!!

2023-03-08 11:55 UTC, kdkdhoho commented
리팩터링을 해도해도 코드가 제 맘에 들지 않네요...🥲

# 주요 리팩터링
이번에는 리뷰 남겨주신 내용들과 개인적으로 조합을 적용해보고 싶어서 구조를 변경해보았습니다. (하지만 하면서 의문점이 있었습니다.)
구조를 변경하다보니, `3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.` 는 요구사항을 만족시키기 위해 Players의 위치를 Dealer에서 Controller로 옮기게 되었고, 그러다보니 View도 static으로 하게 되었습니다.

# 새롭게 궁금한 점
## 상속? 조합?
상속이 가지는 많은 문제점들 때문에 조합으로 구현해보았습니다. 하지만, 막상 구현하고 보니 요구사항 중에 `딜러와 플레이어에서 발생하는 중복 코드를 제거해야 한다.`를 지키지 못하는 것 같았어요. 왜냐하면 같은 로직의 메서드가 존재하기 떄문이에요.
그리고 코드 재사용을 목적으로 상속을 사용하게 되면 부모와 자식 클래스 간의 강한 결합도가 생겨서 변경 및 확장성이 매우 안좋아지기에 조합을 쓴다고 공부했는데요. 현재 코드에서 조합으로 구현해도 이 부분에 대한 이점을 느끼지 못했습니다. 어떤 부분에서는 상속으로 했으면 더 편하고 깔끔했겠다는 느낌도 받게 되는데요.
이에 관련하여 페어와 많은 이야기를 나눠봤지만, 페어도 어떤 점이 좋아서 조합을 쓰라고 하는 지 모르겠다고 합니다. 혹시 알려주실 수 있으실까요 😢

## 상수가 public 이어도 괜찮나요?
`Participant`가 가지는 `INIT_CARD_COUNT`가 `OutputView`, `Dealer`, `Player`에서 모두 쓰이다보니, 접근지정자를 `public`으로 열어주었습니다. 상수가 public으로 열려져 있어도 무방한지 여쭤보고 싶습니다.

2023-03-08 14:52 UTC, sihyung92 approved these changes
안녕하세요 도기~~ 

1단계 수고하셨어요 ㅎㅎ 질문에 대한 답변은 코멘트로 남겨두었으니 확인해보셔요. 전 이전 모델이 더 낫다고 생각해서 이전 방식대로 2단계를 진행하셨으면 하는 마음이 있네요 :> 
2단계에 뵐게요~~

2023-03-08 14:52 UTC, sihyung92 commented on README.md
> +7. 상속이 가지는 많은 문제점들 때문에 조합으로 구현해보았습니다. 하지만, 막상 구현하고 보니 요구사항 중에 `딜러와 플레이어에서 발생하는 중복 코드를 제거해야 한다.`를 지키지 못하는 것 같았어요. 왜냐하면 같은 로직의 메서드가 존재하기 떄문이에요. 그리고 코드 재사용을 목적으로 상속을 사용하게 되면 부모와 자식 클래스 간의 강한 결합도가 생겨서 변경
`상속이 가지는 많은 문제점들 때문에 조합으로 구현해보았습니다.` 이건 어떤 문제점 때문일까요? 

질문해 주신 내용을 보면 코드 구현 중 상속으로 인해 불편한 걸 느껴서 대안으로 조합을 적용해보신 것 보다는 학습해 본 김에 한 번 적용해보신걸로 보이네요 :> 짗궃은 질문 한번 드렸습니다

조합의 장점은 이펙티브 자바 3.0 (루터회관에 잇죵?) item 18을 보셔도 되고, [테코블](https://tecoble.techcourse.co.kr/post/2020-05-18-inheritance-vs-composition/)에도 조합이 상속에 비해 가지는 장점에 대해 상세히 나와 있습니다. 위 레퍼런스들 참고해주셔요.

아마 요번에 효과를 못 보신 이유는 abstract class와 class의 차이에서 왔다고 생각해요. 저는 abstract 클래스는 인터페이스(추상형태)의 일종이라고 생각합니다. 
순수하게 계약 정의(메서드 정의)만 필요한 경우 => 인터페이스
계약 정의에 공통된 부분이 존재하는 경우 (필드와 메서드) => 추상 클래스
( 물논 다중 상속 불가 등의 언어적 한계가 있어서 전 자주 쓰진 않습니다 :> )

사실 "참가자"와 "딜러"는 상속을 활용할 수 있는 is-a 관계에 아주 잘 맞는 모델은 아니라고 생각합니다.
is-a 관계는 상하관계도 포함하고 있는데, "딜러는 참가자다"라는 명제는 "포유류는 척추동물이다"이나 "집은 건물이다" 같은 명제에 비해 상하관계 개념이 성립 안하는 것 같거든요 :> 

그보단 딜러가 블랙잭 게임에서 참가자 역할을 한다, 라는 게 조금 더 어울리고 이 때 Java에서 활용할 수 있는 키워드는 인터페이스 입니다. interface로 `카드를 받는다`,` 점수를 계산한다`, `버스트 여부를 판단한다` 같은 책임을 부여하다 보면 어라, 겹치는 부분이 있네.. 추상 객체로 가도 되겠다. 

저라면 위같은 사고 경로로 추상 클래스로 도달했을 거 같긴 하네요. (사실 다르게 짤 것 같긴해요 :> 그 부분은 비밀입니다)

그래서 제겐 요 상황은 `상속보다는 조합이 장점이 있어서` 대체된 상황 보다는 기존 추상화를 포기하고 새로운 구현체들을 만든걸로 보입니당 ㅎ_ㅎ

사실 조합(has-a, composition)은 상속의 대체제는 아닙니다. 기존에도 Dealer객체는 Players라는 객체를 "조합"하고 있었죠.
그래서 해당 객체에게 "위임" (메서드 호출)하고 있었는데요, 이 모델이 지금보다 훨씬 낫다고 생각합니다.

이 전에는 딜러라는 도메인 모델이 게임 진행에 대한 역할을 가지고 있는 정보(플레이어들)을 가지고 잘 수행해주고 있었는데 정보를 컨트롤러로 나눠줘버리면서 게임 진행은 본인이 하는데 정보는 남한테서 얻어서 진행해야되는 어정쩡한 객체가 되버렸습니다. 
객체지향를 저한테 한 줄로 표현하라고 하면 `"프로세스"를 가장 어울리는 객체에게 부여하고, 해당 프로세스에 필요한 정보도 함께 가지고 있는 것`라고 말하겠습니다. 

카드 돌리기 라는 프로세스를 딜러가 진행하려면 프로세스에 어울리는 정보(유저목록)을 가지고 있어야겠죠, 혹은 유저 목록을 가장 잘 아는 객체요(Players). 고런 느낌..

주저리 주저리 적어봤는데 한번 읽어보시고 이해가 안 되는 부분이나 깨달은 부분이 있다면 알려주셔요 :>
전 이전 버전이 더 좋습니다. 학습하면 지금처럼 적용해 보시고 이게 아니다 싶으면 돌아가시고, 좋다고 말하는 사람들에게 상황을 설명해주시고 이 부분에는 어떻게 적용할 수 있을지 여쭤보시는 식으로 학습하시면 좋은 효과가 있었던 것 같습니다 (지금처럼 👍) 제 말을 비롯해 무조건 맞는 말은 없으니 항상 걸러들으시고요 ㅎㅎ

2023-03-08 14:52 UTC, sihyung92 commented on README.md
> +8. `Participant`가 가지는 `INIT_CARD_COUNT`가 `OutputView`, `Dealer`, `Player`에서 모두 쓰이다보니, 접근지정자를 `public`으로 열어주었습니다. 상수가 public으로 열려져 있어도 무방한지 여쭤보고 싶습니다.
넵 가급적 잠궈주는게 좋지만요 충분히 타당한 이유가 있으면 열어줘도 된다고 생각해요. 다만 "이 패키지가 저 패키지를 알아도 되나?" 하는 부분은 고려해 주세용! (의존 흐름은 단방향이 좋습니다)

2023-03-08 14:52 UTC, sihyung92 commented on src/main/java/blackjack/domain/participant/Participant.java
> +final public class Participant {
public과 final 순서가 바뀌었네요 ㅎㅎ

2023-03-08 14:53 UTC, merged

2023-03-09 06:44 UTC, kdkdhoho commented on README.md
> +7. 상속이 가지는 많은 문제점들 때문에 조합으로 구현해보았습니다. 하지만, 막상 구현하고 보니 요구사항 중에 `딜러와 플레이어에서 발생하는 중복 코드를 제거해야 한다.`를 지키지 못하는 것 같았어요. 왜냐하면 같은 로직의 메서드가 존재하기 떄문이에요. 그리고 코드 재사용을 목적으로 상속을 사용하게 되면 부모와 자식 클래스 간의 강한 결합도가 생겨서 변경
> 상속이 가지는 많은 문제점들 때문에 조합으로 구현해보았습니다. 이건 어떤 문제점 때문일까요?

 상속을 하면 부모와 자식 클래스의 강한 결합이 생김으로서 생기는 **변경의 어려움**이나, **캡슐화 약화**, **메서드 오버라이딩 오작용 문제**, **성능과 구현이 부모 클래스에 의존적** 들을 이야기했습니다. 물론 제 코드에서는 **캡슐화 약화**의 문제 말고는 와닿지는 않았어요.
 하지만, 다양한 곳에서 상속보다 조합을 사용하라는 말들 때문에 상속의 불편함때문에 조합을 적용했다기보다, 말씀하신대로 **학습**의 느낌으로 적용해보았습니다.

 말씀해주신 **인터페이스**와 **추상 클래스**의 차이를, 인터페이스는 구현 클래스가 구현해야 할 **메서드**만을 추상하기 위해 사용하고, 추상 클래스는 구현 클래스들이 공통으로 가질 **필드와 메서드**를 선언하기 위해 사용한다고 이해했습니다. 제가 충분히 이해했을까요?
 여기서 궁금한 것이 있습니다. 추상 클래스에서 공통된 메서드를 구현을 모두 한 채로 선언해도 되나요? 추가로 말씀하신 **계약 정의**가 정확히 무엇을 의미하는 지 잘 모르겠습니다.

---

 > 사실 조합(has-a, composition)은 상속의 대체제는 아닙니다. 기존에도 Dealer객체는 Players라는 객체를 "조합"하고 있었죠.
그래서 해당 객체에게 "위임" (메서드 호출)하고 있었는데요, 이 모델이 지금보다 훨씬 낫다고 생각합니다.

상속과 조합을 이번에 처음 접하게 되면서, **조합이 상속의 단점을 극복하기 위한 대안인가?** 라는 의문점이 들었는데 덕분에 이 질문에 대한 답도 얻었네요 ㅎㅎ 감사합니다.

---

 조합으로 하다보니 필드가 늘어나고, 그러다보니 요구사항을 지키지 못해 Dealer가 자연스레 게임을 진행하는 방식을 변경하게 되었어요. 사실 저도 이 전 구조가 더 괜찮게 느껴졌습니다. 지금은 Controller와 Dealer가 같이 게임 진행에 영향을 주는 구조로 느껴져요 !!

 덕분에 어느정도 상속과 조합에 대한 고민이 정리가 된 기분이에요. 물론 더 공부하고 고민해봐야겠지만, 상속과 조합에 대한 느낌을 조금은 받았습니다. 감사해요 웨지 ☺️

2023-03-09 07:49 UTC, sihyung92 commented on README.md
> +7. 상속이 가지는 많은 문제점들 때문에 조합으로 구현해보았습니다. 하지만, 막상 구현하고 보니 요구사항 중에 `딜러와 플레이어에서 발생하는 중복 코드를 제거해야 한다.`를 지키지 못하는 것 같았어요. 왜냐하면 같은 로직의 메서드가 존재하기 떄문이에요. 그리고 코드 재사용을 목적으로 상속을 사용하게 되면 부모와 자식 클래스 간의 강한 결합도가 생겨서 변경
안녕하세요 도기~~ 행복한 하루 보내고 계신가요?

> 말씀해주신 인터페이스와 추상 클래스의 차이를, 인터페이스는 구현 클래스가 구현해야 할 메서드만을 추상하기 위해 사용하고, 추상 클래스는 구현 클래스들이 공통으로 가질 필드와 메서드를 선언하기 위해 사용한다고 이해했습니다. 제가 충분히 이해했을까요?

네 이해하신 바가 맞습니다! (사람마다 의견이 다를 수 있습니다.) 
다중 정의가 가능하고 코드 계약으로써 동작하는 인터페이스를 먼저 선언하고, 해당 인터페이스를 공통부분을 구현한 추상클래스를 구현하고, 진짜 구현체들은 추상클래스를 extends하는 방법도 있지만 현재 구조에선 과설계라고 생각합니다.
```mermaid
classDiagram
ParticipantInterface ..|> ParticipantAbstractClass
ParticipantAbstractClass <|-- Dealer
ParticipantAbstractClass <|-- Player

ParticipantInterface : +필요한_메서드()
ParticipantAbstractClass : +필요한_메서드_중_공통_메서드_만_구현()
ParticipantAbstractClass : +String 모두_필요한_필드
```

> 추상 클래스에서 공통된 메서드를 구현을 모두 한 채로 선언해도 되나요? 추가로 말씀하신 계약 정의가 정확히 무엇을 의미하는 지 잘 모르겠습니다.

저는 클래스의 메서드를 코드 계약이라고 부릅니다. 자바에선 다른 클래스가 수행하는 역할은 public API의 메서드 시그니처 (메서드명, 파라미터, 응답 타입)을 통해 확인할 수 밖에 없습니다. 달리 말해 메서드 시그니처는 `메서드명에 명시된 행위를 파라미터로 입력받아서 응답타입으로 출력할 것`이라는 다른 클래스와의 계약(약속)인 겁니다. 이해하기 쉽고 버그가 없는 코드는 명료한 약속을 해주고, 약속한 행위를 잘 수행하면 됩니다.

위 내용에서 비롯되어 계약정의라고 말했는데, 그냥 인터페이스 정의입니다! ^_^ 
PR 첫 코멘트에서 남겨주신 "주요 도메인 객체를 생각하고 객체의 속성과 역할에 집중하여 요구사항을 분석해보았습니다." 중 객체의 역할에 집중한 것과 같은 내용입니다