[1단계 - 블랙잭 게임 실행] 모디(전제희) 미션 제출합니다.
woowacourse/java-blackjack pull request #481
Opened 2023-03-06 08:10 UTC by jaehee329

https://github.com/woowacourse/java-blackjack/pull/403

2023-03-06 16:38 UTC, jaehee329 commented
안녕하세요 다니...!   
말씀주신 부분들에 대해 수정했습니다!  
우선 제 원격 레포에 force 푸쉬를 했었는데 강제로 PR이 닫히고 기존 PR과 해시가 달라져 다시 열 수가 없어 PR을 새로 생성하게 되었습니다..  
<br>

<br>
https://github.com/woowacourse/java-blackjack/pull/403#discussion_r1125599295

2023-03-06 17:49 UTC, jaehee329 commented on src/main/java/controller/BlackJackController.java
> +        while (!player.isBust() && (hit = getPlayerHitOrStand(player))) {
이 부분의 반복문이 사용자의 입력과 동시에 도메인의 상태를 동시에 검사하며 수행되어야 해서 상당히 고민이 많이 되었는데요,  
결국 개선한다면 controller가 bust라는 비즈니스 로직을 몰라도 되도록 같은 기능이지만 다르게 명명된 메서드를 호출하는 정도..?  
isBust()를 호출하는 새로운 메서드를 `CardDistributer`정도에 넣을 순 있을 것 같은데 이 이상으로 좋은 방법이 있을까요..

2023-03-06 17:56 UTC, jaehee329 commented on src/main/java/domain/model/Player.java
> +        return score;
이 부분은 질문을 드리고 싶은데요,  
현재 Player가 Score를 가진 상태에서 getScore()의 반환을 Score 그대로 해주어야 할 지 아니면 Score의 값을 score.getValue()로 벗겨 넘겨주는 것이 맞는지 고민입니다. 후자라면 과연 getScore()라는 명명을 해도 될 지도요.  
현재는 그대로 Score를 넘겨주면서 특히 View나 테스트 과정에서 디미터의 법칙을 어기고 getter를 연쇄적으로 사용하는 부분이 나오게 되는데 이것을 좀 개선하고 싶습니다..!

2023-03-08 08:25 UTC, jaehee329 commented
<img width="644" alt="image" src="https://user-images.githubusercontent.com/77962265/223660294-e0299f2c-a131-4e0e-8a6e-7258d2ac6789.png">
대략 이런 느낌으로 수정중에 있는데 리뷰해주시기 전에 완성하기 어려울 수 있을 것 같아서요..!  
DTO를 사용하고 `Controller`가 `DtoMaker`와 `BlackJackGame`만 의존하고 Player와 Dealer에 대해 모르도록 하려고 합니다.  
플레이어의 상태를 확인하는 동시에 hit 의사를 입력으로 받아서 처리하는 조건 때문에 컨트롤러와 플레이어의 의존을 완벽히 분리하는게 쉽지가 않네요 ㅠㅠ

2023-03-08 15:51 UTC, da-nyee commented on src/main/java/domain/model/Player.java
> +        return score;
> 현재 Player가 Score를 가진 상태에서 getScore()의 반환을 Score 그대로 해주어야 할 지 아니면 Score의 값을 score.getValue()로 벗겨 넘겨주는 것이 맞는지 고민입니다.

player.getScore()에서 score를 반환하면, 모디가 말한 것처럼 디미터의 법칙을 어기기 때문에 int를 반환하는 게 좋은 것 같아요.
다음 코드처럼요.

```java
class Score {

    private int value;

    public int getValue() {
        return value;
    }
}

class Player {

    private Score score;

    public int getScore() {
        return score.getValue();
    }
}
```

<br/>

> 후자라면 과연 getScore()라는 명명을 해도 될 지도요.

Score 그 자체가 아닌 int 값이어도 Score의 값이니까 getScore()로 네이밍해도 괜찮다고 생각해요.
getValue()나 getScoreValue()로 네이밍할 수도 있는데, 전자는 이름의 의미가 모호하고 후자는 이름이 불필요하게 길어지는 것 같네요.

2023-03-08 15:56 UTC, da-nyee commented on src/main/java/domain/model/Player.java
> +        return score;
> 현재 Player가 Score를 가진 상태에서 getScore()의 반환을 Score 그대로 해주어야 할 지 아니면 Score의 값을 score.getValue()로 벗겨 넘겨주는 것이 맞는지 고민입니다.

player.getScore()에서 score를 반환하면, 모디가 말한 것처럼 디미터의 법칙을 어기기 때문에 int를 반환하는 게 좋은 것 같아요.
다음 코드처럼요.

```java
class Score {

    private int value;

    public int getValue() {
        return value;
    }
}

class Player {

    private Score score;

    public int getScore() {
        return score.getValue();
    }
}
```

<br/>

> 후자라면 과연 getScore()라는 명명을 해도 될 지도요.

Score 그 자체가 아닌 int 값이어도 Score의 값이니까 getScore()로 네이밍해도 괜찮다고 생각해요.
getValue()나 getScoreValue()로 네이밍할 수도 있는데, 전자는 이름의 의미가 모호하고 후자는 불필요하게 길어지는 것 같네요.

2023-03-08 16:09 UTC, da-nyee commented
> 아직 부족하다고 생각하는 점은 별도의 DTO를 사용하지 않아서인지 뷰에서 입력받은 도메인 객체를 너무 자세히 알고 있도록 설계하는 부분인데요.. 도메인 - DTO 변환에 대한 책임을 가지는 클래스를 하나 두고 컨트롤러에서 이를 사용하도록 하면 비교적 깔끔해질 것 같은데 이런 방법은 어떨까요? 리뷰어분들께서 DTO 사용에 대해 의견들이 다양하신 듯 하여 먼저 적용해보기가 조심스럽네요 😅

2023-03-08 16:20 UTC, da-nyee commented
> 아직 부족하다고 생각하는 점은 별도의 DTO를 사용하지 않아서인지 뷰에서 입력받은 도메인 객체를 너무 자세히 알고 있도록 설계하는 부분인데요.. 도메인 - DTO 변환에 대한 책임을 가지는 클래스를 하나 두고 컨트롤러에서 이를 사용하도록 하면 비교적 깔끔해질 것 같은데 이런 방법은 어떨까요? 리뷰어분들께서 DTO 사용에 대해 의견들이 다양하신 듯 하여 먼저 적용해보기가 조심스럽네요 😅

지금은 간단한 콘솔 프로그램이어서 Dto/DtoMapper(Maker)까지 만들어야 할까 싶지만.. 있으면 모디 말씀대로 깔끔해지겠네요 ㅎㅎ
학습 목적으로 활용해봐도 좋을 것 같아요!

+) 만약 Dto가 없다면, 어떤 방식으로 Domain(Model) - View 의존성을 제거할 수 있을까요?

2023-03-08 17:30 UTC, da-nyee requested changes
모디~~ 다니입니다 🙌

어프루브 & 머지를 드리고 싶었지만..
프로그램이 일부 오작동해서 수정하고 가는 게 좋을 것 같아 리퀘스트 체인지를 드립니다 🥲

코드리뷰 확인하고 재리뷰 요청해주세요!

조금만 더 힘내봅시다 💪💪💪

2023-03-08 17:30 UTC, da-nyee commented on src/main/java/view/OutputView.java
> +    private static String stringifyResult(final Result result) {
지난번에 봤을 때는 domain에서 처리해도 되지 않나 싶었는데, 다시 보니까 조금 애매하네요...? ㅎㅅㅎ
비즈니스 로직보단 출력 로직에 가까운 것 같아요.
stringifyResultHistory()에서 출력 형식 때문에 `" "`을 맨 앞에 추가하기도 하니까요.
이 부분은 수정 없이 이대로 유지하시죠 !

2023-03-09 02:11 UTC, jaehee329 commented on src/main/java/Application.java
> +    public static void main(String[] args) {
<img width="972" alt="스크린샷 2023-03-09 오전 11 03 31" src="https://user-images.githubusercontent.com/77962265/223896919-13ce1c0c-efd2-4e1c-983a-b4ca4507b767.png">

해당 부분은 의도한 바가 맞기는 합니다!  
저희 요구사항이나 위키에서는 한 장만 추가 수령하는 듯 하게 되어있는데 게임에서는 16 이하에 계속 받는 것 같더라구요. <br>
그래서 위의 상황에서는 딜러가 처음 A, 5를 받아 점수는 16이고 한 장만 공개한 상태에서,  
16 이하이므로 J를 더 받아 26이 된 상태에서 Bust이므로 다시 A를 11->1로 고려해 16이 되고,  
마지막으로 Q를 받아 26이 된 상태네요  <br>
  
크루들에게도 물어보니 16 이하에서 무한히 받을지는 요구사항이 애매해 갈리는 듯 한데, 저의 경우에는 무한히 받도록 했으니 기능 정리 목록에 그 부분을 좀 더 명시하도록 하겠습니다 ~ 😄

2023-03-09 05:45 UTC, jaehee329 commented on src/main/java/domain/model/Player.java
> +        return score;
말씀해주신 내용을 반영해서 int를 반환하도록 처리하려고 해보았습니다.  
Score가 단순 점수라는 상태만을 들고 있는 클래스가 아니라 상태에 따라 isBust()같은 기능들도 내재시킨 객체로 설계하였다보니  
- 기존 Score를 그대로 반환하는 설계에서는 Player간의 점수 계산을 외부의 Result 클래스에서 수행할 때 가진 Score를 가져와 내장된 isBust()등을 사용하면 되었다면
- 새로 int를 반환하는 설계에서는 Result 클래스에서 Player의 점수(int)를 가져오고, isBust()를 새로 정의해 사용해야 하네요 ㅠㅠ  <br>
Bust여부 확인에 대한 책임은 원시값을 포장한 Score 클래스에서 알아서 확인하도록 하는 것이 가장 좋은 책임의 분배라 생각하는데  
오히려 이런 설계가 디미터의 법칙을 어기게 하네요ㅠ Player 간 점수 계산은 별도의 클래스에서 하는 방식은 맞다 생각하는데 뭐가 잘못된 걸까요?  
당장은 디미터의 법칙을 어기는.. 기존의 방법으로 두었습니다.

2023-03-10 10:51 UTC, jaehee329 commented
안녕하세요 다니! 😄
컨트롤러 책임을 분산시키기가 쉽지 않아서 조금 오래 걸렸습니다...ㅎㅎ..<br>
큰 변경점은 아래 적어둘게요  
- - - -
- 기존: Controller에서 게임 흐름을 관리 -> 변경 후: CardDistributor를 변경한 BlackJackGameRunner에서 흐름을 관리
- 기존: Dealer와 Player가 같은 Result 클래스를 통해 결과 관리, View에서 알아서 결과를 처리 -> 변경 후: Dealer와 Player가 다른 Result 클래스를 통해 결과 관리.
- 도메인 내부에 있던 View 관련 요소들(카드 끝수, 문양의 String, 승패 관련)를 별도의 클래스 ViewRenderer를 통해 처리.

- - - -

2023-03-11 17:38 UTC, da-nyee commented on src/main/java/Application.java
> +    public static void main(String[] args) {
아하 잘못된 구현이 아니었군요!
좋습니다 👍👍👍

2023-03-11 19:08 UTC, da-nyee approved these changes
모디~~ 다니입니다 🙌

기존에 Controller에 몰려있던 책임을 BlackJackGameRunner로 적절히 분배하니까 훨씬 객체지향적인 코드가 되었네요 💯

PR 코멘트로 주요 변경점 정리해주셔서 감사합니다 ㅎㅎ
어떤 부분을 중점적으로 봐야 하는지 알 수 있어서 좋았어요 👍

1단계는 이 정도면 충분한 것 같아서 어프루브 & 머지할게요!
추가 코멘트 몇 개 남겼으니 한번 확인하고 2단계 진행해주세요

다음 단계에서 만나요 ~~!

2023-03-11 19:08 UTC, merged

2023-03-12 17:28 UTC, jaehee329 commented on src/test/java/view/ViewRendererTest.java
> +		assertThat(multiResults.getResults().size()).isEqualTo(2);
Junit 기능이 정말 많아서 찾아보지 않고 익숙한 방법을 먼저 사용하게 되네요..ㅠㅠ
감사합니다!

2023-03-12 17:34 UTC, jaehee329 commented on src/main/java/view/ViewRenderer.java
> +	private static final Map<ResultState, String> RESULT_TO_STRING = new HashMap<>();
오...!!!!   
항상 사용하던 HashMap을 관성적으로 사용했는데 EnumMap이라는 구현체가 있었군요!!!  
Enum이 유일한 상수라는 장점을 가져가면서 순서까지 고정되어있는 장점을 모두 취할 수 있네요!  
<br>
덕분에 정말 기분 좋게 새로운 지식을 하나 배웠습니다~~~ 감사합니다!!