[2단계 - 블랙잭 베팅] 말랑(신동훈) 미션 제출합니다.
woowacourse/java-blackjack pull request #485
Opened 2023-03-08 08:33 UTC by shin-mallang

많이 부족한 코드지만, 이번에도 잘 부탁드립니다 😊

2023-03-08 11:34 UTC, shin-mallang reviewed
감사합니다 코다 😊
저의 이런 저런 고민들과 생각들에 대해 코다와 대화하다보니 덕분에 정말 많은 고민들이 해결되었고, 또 너무 즐거웠습니다.
2단계 미션도 많이 부족하지만 잘 봐주시면 감사하겠습니다 :)🙇‍♂️

2023-03-08 11:34 UTC, shin-mallang commented on src/test/java/domain/game/BlackJackGameTest.java
> +        assertThat(blackJackGame.dealer()).isNotNull();
코다의 말씀들 듣고 위와 같이 테스트 코드를 변경해 보았습니다.
CardArea에 존재하는 생성자가 Card 2개를 받아 생성되는 생성자밖에 존재하지 않기 때문에  `CardArea.initial()`등의 메서드를 따로 추가하지는 않았습니다.
혹시 위 구조에서 더 개선할 수 있는 점이 있을까요?

2023-03-09 04:55 UTC, shin-mallang commented on src/main/java/domain/player/Dealer.java
> +    private static final BlackJackScore DEALER_DONT_HIT_SCORE = BlackJackScore.of(17);
기존에는 BlackJackScore 가 딜러가 더 받아야 하는 점수를 알고 있는 구조였습니다.
16점 이하일 때, 딜러는 무조건 HIT을 해야 한다는 것을 점수의 입장에서 보느냐, Dealer의 입장에서 보느냐의 차이인 것 같다고 생각해요.
처음에는 블랙잭 점수가 알고 있는 것이 더 낫다고 생각했습니다.
점수와 관련된 것이기 때문에, 자신이 책임지는 것이 더 낫다고 생각했어요.

그러나 딜러의 HIT해야하는 점수가 바뀔 때, BlackJackScore 와 Dealer 중 어느 클래스를 먼저 찾을가 고민해 보니, 아무래도 Dealer를 먼저 찾을 것 같았고,
따라서 구조를 변경하게 되었습니다.

코다는 이에 대해서 어떻게 생각하시나요?

2023-03-10 07:27 UTC, yjksw requested changes
안녕하세요 말랑 ~ 코다 입니다 🙇‍♀️

리뷰가 조금 늦었는데 죄송해요 ! 
2단계 요구사항 적용해주신 것과 리뷰 적용해주신 것 잘 확인했어요 ㅎㅎ

DM으로 주신 질문도 제가 확인을 못하고 있는데 
오늘 저녁 전까지 꼭! 답변 드릴게요. 

추가 코멘트 남겼으니 참고해주세요 ~ 😊

2023-03-10 07:29 UTC, shin-mallang commented on src/main/java/domain/card/CardValue.java
> +    ;
오 코다도 이거 아시는군요!!!!

2023-03-10 07:30 UTC, shin-mallang commented on src/main/java/controller/BlackJackController.java
> +        );
감사합니다:)

2023-03-10 07:31 UTC, shin-mallang commented on src/main/java/domain/card/BlackJackScore.java
> +        return BlackJackScore.of(value + ADDITIONAL_ACE_VALUE);
생각도 못 하고 있었습니다..😭

2023-03-10 07:41 UTC, shin-mallang commented on src/main/java/domain/card/CardArea.java
>      }
주석을 달던지, 혹은 정적 팩터리 메서드를 반환하는 방법이 있다고 생각합니다.

정적 팩터리 메서드에 대한 장단점은 다음과 같을 것 같아요.

## 정적 팩터리 메서드
### 장점
 - 의미 있는 네이밍을 통해 의도를 드러낼 수 있습니다.
### 단점
 - 하위 클래스를 생성할 수 없게 됩니다. 즉 유연성이 떨어집니다.
 - 정적 팩터리를 찾기 위한 수고가 추가로 들어갑니다.
 
생성자에 주석을 제공하는 것은, 위와 반대되지만, 주석을 추가로 작성해야 하고, 만약 상황이 달라진다면 주석 역시 변경해 주어야 한다는 단점이 있을 것 같습니다.

저는 정적 팩터리를 선택한 이유로, 굳이 하위 클래스를 생성할 필요 없으며, 또한 현재 상황에서는 정적 팩터리를 찾는 것이 어렵지 않을 것이라 판단하였기 때문인데요, 코다가 의도하신 방향에 맞게 수정하였을까요?

2023-03-10 07:48 UTC, shin-mallang commented on src/main/java/domain/player/Revenue.java
> +    }
이 부분에서 저도 고민이 조금 있었는데요,

현재 draw는 수익이 0원이지만, 만약 수익을 계산하는 규칙이 바뀐다면 BettingMoney가 필요해 질 것 같아서 넣었습니다.

발생하지 않을 미래의 일을 너무 예상하는 것은 좋지 않다고 생각하지만 매개변수로 BettingMoney를 받는 것에 많은 노력이 발생하지 않으며 또한 통일성도 있어보여서..? 이렇게 구현했습니다..!!

사용하지 않는 것은 지우는게 나을까요?

2023-03-10 07:49 UTC, shin-mallang commented on src/main/java/domain/game/BlackJackGame.java
>      }
와 진짜 너무 좋은 생각인 것 같습니다...!!
실시간으로 감탄했습니다👍👍

2023-03-10 08:59 UTC, shin-mallang commented on src/main/java/domain/player/Revenue.java
> +public class Revenue {
배팅 금액에 대해 각각의 상황에 대한 수익을 정적 팩터리로 의미 있게끔 반환하고 싶어서 위와 같이 구현하였습니다.
좀 더 나은 개선 방향이 있을까요?

2023-03-10 09:10 UTC, shin-mallang commented on src/test/java/domain/card/CardDeckTest.java
> +        assertThat(draw.cardValue()).isEqualTo(JACK);
필요 없었던 것 같습니다!!
처음 생각했을 때에는, 테스트를 좀 더 편하게 할 수 있지 않을까? 해서 구현하였는데, 막상 보니 해당 부분 말고는 필요한 부분이 없었더라구요!
제거했습니다. 감사합니다

2023-03-10 09:40 UTC, shin-mallang commented on src/main/java/controller/BlackJackController.java
> +                        (a, b) -> b,
API를 보면 다음과 같이 나와있습니다.

> mergeFunction – a merge function, used to resolve collisions between values associated with the same key, as supplied to Map.merge(Object, Object, BiFunction)

stream에서 map으로 합치는 경우, 동일한 키가 존재할 수 있는데요,
map에서는 키의 중복이 불가능하기 때문에, 이러한 경우 충돌(collision)이 발생하게 됩니다.

이때 충돌하는 Key에 대해서 어떠한 Value를 반환할 지를 정해주는 함수가 mergeFunction 입니다.
저의 경우에는 Person의 equals와 HashCode를 정의하지 않았기 때문에, 주소값이 다른 Person은 모두 다르므로, 
Collistion이 발생하지 않아 위와 같이 대충,,? 구현하였습니다...!

관련 학습 테스트를 작성해서 커밋하도록 하겠습니다.

2023-03-10 09:47 UTC, shin-mallang commented on src/main/java/domain/game/BlackJackGame.java
> +                .reduce(Revenue.zero(), Revenue::minus);
굳이 Revenue 의 메서드에 dealer를 명시하며, Participant에 대한 의존성을 추가하는 것 보다, `Collaction<Revenue>`의 총 합을 구한 뒤, 부호를 바꾸는 식으로 작성하도록 하는 것이 더 낫다고 생각되는데, 어떨까요?

2023-03-11 14:14 UTC, yjksw approved these changes
안녕하세요 말랑 ~! 코다 입니다 🙇‍♀️

마지막 리뷰도 정말 빠르게 잘 적용해주셨어요 👍
여러모로 저도 새로운 고민을 많이 하게 되어서 즐거웠던 리뷰였습니다. 

리뷰 하나하나 깊이 고민하시는 것이 느껴졌어요 ㅎㅎ
정말 깊이 학습하시는 것 같아요 💯

이번 미션으로 말랑도 많은 것을 얻어가셨으면 좋겠네요
잘 해주셔서 이만 머지해도 충분한 것 같아요! 
앞으로도 화이팅 입니다 🙌

2023-03-11 14:14 UTC, yjksw commented on src/main/java/domain/player/Revenue.java
> +    }
그랬군요 !  말랑이 해주신 것도 이해가 잘 갑니다. 저도 통일성을 굉장히 중요하게 생각하는 편이라서요 ㅎㅎ 
그런데 제가 의문을 가졌던 것처럼 다른 사람이 이 코드를 볼 때 사용하지 않는 매개변수를 보며 많은 상상(?)을 할 수 있을 것 같아요! (제가 현업에서 많이 경험하는 상황인데요)
코드가 시간이 많이 지나거나 만든 사람이 더 이상 팀에 있지 않을 때 남아있는 코드를 보고 의도를 추측하기 위해서 깊이 토론을 하는 경우가 많은데요, 많은 경우 코드 작성자는 별다른 의도 없이 구현한 경우도 많더라구요. 

예를 들어서, 사용하지 않는 매개변수를 보면 혹시 사용해야하는데 로직이 잘못 삭제된 것은 아닐까, 혹시 IDE에 오류가 있는 것은 아닐까 많은 상상을 하게 될 수도 있지 않을까요? 

> 자동차 헤드라이트로 비출 수 있는 거리에 한계가 있는 것처럼 우리도 한두 단계 앞의 미래만 내다볼 수 있다. 끽해야 몇 시간이나 며칠 정도일 것이다. 그 너머는 경험에 기반한 추측을 벗어난 무모한 억측의 영역이다. .... 우리는 미래의 유지 보수를 고려해서 설계해야 하지 않느냐고? 맞다. 하지만 여러분이 볼 수 있는 미래까지만 고려해야 한다. (실용주의 프로그래머 p.178 - 179)

개인적으로 매우 강추하는 책인데, 저도 이 부분을 읽고 좀 정리가 되었어서 첨부합니다 😊

2023-03-11 14:14 UTC, yjksw commented on src/main/java/domain/game/BlackJackGame.java
> +                .reduce(Revenue.zero(), Revenue::minus);
그것도 좋은 방법이네요 😊

2023-03-11 14:14 UTC, yjksw commented on src/main/java/domain/player/Revenue.java
> +public class Revenue {
아하 ! 모두 `Revenue` 생성을 할 때 중요한 의미를 가지는 네이밍을 표현하는군요 ㅎㅎ 
의도를 이해하니 적합한 것 같아요 ㅎㅎ 

제가 좀 어색하게 느꼈던 이유는 [정적 팩터리 메서드](https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/)는 생성의 책임만을 지는데, `total()` 같은 경우 로직을 수행해서 가공을 하고 있기 때문이었던 것 같아요. 

그런데 말랑이 말씀해주신대로 의미있는 네이밍으로 반환하는 역할을 한다고 생각하니 문제가 없어 보이기도 하네요 ! (저도 조금 더 고민이 필요한 문제인 것 같아 결론보다는 의견만 전달합니다)

2023-03-11 14:14 UTC, merged

2023-03-11 14:45 UTC, shin-mallang commented on src/main/java/controller/BlackJackController.java
> +                        (a, b) -> b,
collect 시에 LinkedHashMap으로 변환하기 위해서는 keyMapper, valueMapper만 있는 것으로는 바꿀 수가 없어서 위와 같이 구현했습니다~!