[2단계 - 블랙잭 베팅] 지토(김지민) 미션 제출합니다.
woowacourse/java-blackjack pull request #486
Opened 2023-03-08 08:48 UTC by apptie

안녕하세요, 라빈!

말씀해주신 피드백과 페어의 리뷰를 참고하면서 1단계 리펙토링을 진행하고, 2단계를 수행했습니다.
프론트 컨트롤러 패턴은...도입에 실패했습니다..ㅜㅜ
아래에 리펙토링 내용 및 질문 사항에 대해 정리해놓도록 하겠습니다.

이번에도 리뷰 잘 부탁드립니다!     

---

## 리펙토링

### 1단계 피드백 반영

`CardSelector` 인터페이스를 `card 패키지`로 변경하고, 
역할에 어울리지 않던 이름을 가진 `ExceptionHandler`를 `InputProcessHandler`로 변경하고, 
도메인과 직접적인 역할이 없는 의존성은 최상위 `Application`이 관리하도록 변경했습니다.

### Controller에서 직접 도메인으로 변경해 로직을 수행하던 코드를 변경

```java
// GameController

private static final int START_GIVEN_COUNT = 2;
private static final int PARTICIPANT_GIVEN_COUNT = 1;
private static final int PLAYER_ORDER_OFFSET = 1;
private static final int DEALER_ORDER = 0;

private void handleDealerCards(final Participants participants, final CardManager cardManager) {
    final Dealer dealer = (Dealer) participants.findDealer();
    final String name = dealer.getName();

    while (dealer.canDraw()) {
        cardManager.giveCards(DEALER_ORDER, PARTICIPANT_GIVEN_COUNT);
        outputView.guideDealerGivenCard(name);
    }
}
```

위와 같은 방식으로 `Controller` 내부에 `Dealer`나 `Player`에 대해 너무 자세히 알고 있다고 생각해, 블랙잭 게임을 수행하는 기능을 `GameManager`에서 수행하도록 변경했습니다.

### 딜러, 혹은 플레이어가 가지고 있던 구체적인 기능을 추상 클래스의 추상 메소드로 정의

`Dealer.calculateResult()`와 같이 구체적인 기능을 추상 클래스의 추상 메소드로 정의하고, 이러한 메소드를 사용해서는 안 되는 플레이어에는 `UnsupportedOperationException` 예외를 던지는 방식으로 변경했습니다.

---

## 질문

### 상속 관계의 동일한 레벨의 도메인에서 수행하는 구체적인 기능을 정의하는 방법?

이전에 했던 질문(상속 관련된...)과 유사한 내용입니다.
이전 1단계에서의 제가 질문을 드린 의도는 '추상 클래스를 사용했는데 추상 메소드 등 상속을 통해 얻을 수 있는 다형성과 같은 이점을 제대로 얻지 못했고, 너무 코드 중복을 줄이기 위해서만 사용한 것 같다`라고 생각해서 드렸던 내용이었습니다.

그래서 제 질문에 답변해주신 부분과 리펙토링 하면서 추상 메소드를 정의해 어느 정도 이러한 부분에 대해서는 개선을 했다고 판단했었습니다.

그런데 `Dealer.calculateResult()`나 2단계를 진행하면서 추가한, `Player.calculateBenefit()`과 같이 동일하게 `Participant`를 상속하지만, `Dealer`에서만 사용하거나 `Player`에서만 사용하는 기능을 사용하기 위해서는 명시적 형변환을 한다는 것이 상속을 사용한 의미가 없다는 생각이 들었습니다.
일급 컬렉션에서는 `List<Participant>`로 관리하는데, 블랙잭 게임을 진행하기 위해 구체적인 타입인 `Dealer`나 `Player`를 알아야 하고, 명시적 형변환을 해야 한다는 것이 개인적으로는 납득이 되질 않았습니다.
그래서 이번에 `Participant` 추상 클래스에 `calculateResult()`와 `calculateBenefit()`를 추상 메소드로 정의하고, 이 메소드를 사용하지 않는 도메인은 `UnsupportedOperationException` 예외를 발생하도록 했습니다.

그런데 이렇게 구현하고 보니 또 `Delaer`나 `Player`에서 절대 사용하지 않을 메소드를 정의하는 것이 맞는가 싶기도 하고....그래서 라빈은 어떤 방식을 선호하시는지 궁금합니다!

### Controller에서 예외 처리를 분리하는 방법?

저는 `Controller`가 예외 처리까지 담당하게 된다면 너무 많은 책임을 가지고 있다고 판단해서, 이전 미션에서부터 계속 `Controller`에서 예외 처리 로직을 분리하고자 했었습니다.
그래서 이전 `ExceptionHandler`, 지금의 `InputProcessHandler`를 사용해 예외 처리를 `Controller`에서 분리하고자 했습니다.
이전에는 `JDK Dynamic Proxy`도 써봤는데 너무 신경써야 하는 부분이 많기도 하고, 제가 잘 알지 못하는 것을 사용하는 게 좋지 않다고 느껴 포기했었습니다. 
그래서 지금과 같은 형식을 사용해봤는데...메소드의 파라미터가 너무 많기도 하고, 복잡하기도 해서 이러한 접근 방식이 맞는지...확신이 들지가 않았습니다.

이전에 `다른 구조를 생각해보라`고 말씀해주셨는데 제가 사용한 방식 말고 다른 구조로는 어떤게 있을지, 라빈이라면 어떤 식으로 구현할 것인지 궁금합니다!

---

감사합니다!

2023-03-11 06:49 UTC, giantim requested changes
지토 안녕하세요. 리뷰어 라빈입니다!
이번 단계도 리팩토링 빠르게 구현해주셨네요 👏 제가 리뷰를 너무 늦게 드려 죄송합니다 🥲
질문 주신 내용 이외에는 크게 드릴만한 내용이 없었던거 같은데요...!

#### 상속 관계의 동일한 레벨의 도메인에서 수행하는 구체적인 기능을 정의하는 방법?
구현체에 따라서 UnsupportedOperationException을 던지도록 구현하는 경우는 많은거 같아요. 지금 같은 경우에 Participant의 구현체가 Dealer / Player 두 경우인데 구현체가 늘어나게 된다면 충분히 가능한 경우라고 생각합니다. 블랙잭이라는 요구사항 특성상 더이상 구현체가 늘어나지는 않겠지만요! 
만약 지금과 같은 경우에 공통으로 추상화한 메서드가 어색하게 느껴진다면 다른 객체에게 결과, 배당률을 계산하는 책임을 위임해보는 방법도 생각해볼 수 있지 않을까요?

#### Controller에서 예외 처리를 분리하는 방법?
저는 뷰의 예외처리는 정말 단순하게 구현했을것 같아요 😂 현재 정의하신 InputProcessHandler의 경우 Supplier, Runnable, Function, Consumer 등 자바에서 제공하는 기능을 적극적으로 사용하시면서 작성을 해주셨는데요. 작성하시면서 파라미터 수도 많고 복잡해보이는 고민을 갖고 계신거 같아요. 저는 추가적으로 각 repeat() 메서드들의 재사용성도 고민인데요. repeat() 메서드가 오버로딩 되어있는데 내부 구현이 달라서 호출할 때 다른 부분을 구체적으로 확인해야하고 실수할 여지가 있다고 생각이 드네요! 그래도 자바에서 제공하는 기능들을 직접 공부하고 연습해보는 것에서는 의미가 있다고 생각합니다!

질문주신 내용과 소소한 리뷰 남겨드렸는데 확인 부탁드릴께요

2023-03-11 06:49 UTC, giantim commented on src/main/java/domain/participant/PlayerInfo.java
> +
플레이어의 이름, 베팅 정보 등을 묶는 객체를 정의해주셨네요.
객체 이름에 Information과 같은 용어가 들어가면 다른 개발자가 봤을 때 책임과 역할을 모호하게 생각할 수 있을거 같은데요.
해당 객체를 정의하는 대신 Player가 필드를 갖으면 어떨까요?

2023-03-11 06:49 UTC, giantim commented on src/main/java/domain/participant/Participants.java
> +        final int totalParticipantSize = participants.size();
Participants 일급 컬렉션은 참여자들에 대한 정보를 담당하고 있는 도메인 객체인데요.
그럼 bet() 메서드처럼 구체 타입으로 변환해서 로직을 명확하게 작성해도 좋다고 생각해요! 다른 메서드들도 일관성있게 수정해보면 어떨까요?

2023-03-11 08:27 UTC, apptie commented on src/main/java/domain/participant/PlayerInfo.java
> +
말씀하신 대로 `Player`가 필드로 배팅과 관련된 내용인 `PlayerBet`을 가지게 하고 싶었는데, 요구 사항 중 `3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.`를 억지로 지키려다 보니 이런 모호한 상황이 발생한 것 같습니다.

일단 `getName()`을 공통 처리하고 `PlayerInfo`를 둔 상태에서 라빈의 의견을 구하고 싶었는데, 피드백 해 주신 내용도 그렇고, 계속 생각하면 할수록 애매하네요..

조금 더 고민해보고 피드백 반영하겠습니다. 감사합니다!

2023-03-11 08:29 UTC, apptie commented on src/main/java/domain/participant/Participants.java
> +        final int totalParticipantSize = participants.size();
피드백 감사합니다! 확실히 지금 보니 일관성이 좀 많이 없네요...

2023-03-11 14:39 UTC, apptie commented
안녕하세요, 라빈!
생각보다 빠르게 리펙토링을 진행할 수 있었는데, 또다시 새로운 고민이 생겨 빠르게 라빈과 공유해보고 싶어 다시 리뷰를 부탁드립니다 ㅎㅎ..
리펙토링과 고민 내용은 아래에 정리하겠습니다!

## 리펙토링

### 명시적인 형변환 및 `Participant`의 추상 메소드 삭제

일관성을 위해 `Player`에 특화된 메소드를 호출할 때 명시적은 형변환을 적용했습니다.
이렇게 변경하자 `Participants 일급 컬렉션`이 아닌 외부 `GameManager`에서 `Player.calculateBenefit()`만을 호출하게 되었습니다.
그래서 `Participant 추상 클래스`에서 굳이 `Dealer`나 `Player`만을 위한 메소드를 추상 메소드로 표현해 구현을 강제하도록 할 필요가 없다고 판단했습니다. 

결과적으로는 추상 메소드를 없애고, `GameManager`에서도 명시적인 형변환으로 `Player.calculateBenefit()`을 호출하도록 변경했습니다.

### 예외 처리 방식 변경

이전에도 `InputProcessHandler`가 너무 복잡하다고 생각했었는데, 라빈이 제 질문에 답변해주신걸 보고 최대한 간단하게 가는 방향으로 수정했습니다.

`Controller`에서 분리하고는 싶지만, 지금까지 떠올린 방법보다는 차라리 `Controller`에서 예외 처리까지 담당하는게 낫겠다 싶어서 다시 `Controller`에서 예외를 공통 처리하도록 설정했습니다.

그리고 다른 크루분들에게 제 코드 리뷰를 부탁드려본 결과 `너무 복잡하고 길어서 보고 싶지 않다`라는 의견이 대다수었기 때문에 가독성도 고려해서 재귀로 처리했습니다.

### `Player`가 `PlayerBet`을 지니도록 변경

피드백 해 주신 대로 `Player`가 `PlayerBet`을 지닐 수 있도록 설정했습니다.

--- 

이 외에도 자잘하게 `enum` 이름 변경, 상수 이름 변경, 불변 적용 등의 리펙토링을 진행했습니다.

## 고민거리

지금 주로 하고 있는 고민거리는 `Player`와 `Dealer`의 관계를 어떤 식으로 표현할지에 대한 내용입니다.

`다른 객체에게 결과, 배당률을 계산하는 책임을 위임해보는 방법도 생각해볼 수 있지 않을까요?`라는 답변을 보고, 계속 고민해본 결과 그래도 `Dealer`가 게임의 승패를 계산하는 것이 조금 더 자연스럽고 이해하기 편할 것이라고 판단했습니다.

그래서 이를 그대로 유지한 채 계속 느끼고 있는 어색함을 어떤 방식으로 해결할 수 있을지 고민하다가 몇 가지 아이디어를 떠올렸습니다.

다만 이게 맞나... 싶기도 하고, 구조를 좀 많이 바꿔야 할 것 같아 리펙토링 전에 한 번 라빈의 평가를 부탁드리고 싶습니다.

### Participants의 일급 컬렉션을 포기하는 방식

명시적 형변환으로 `Dealer`나 `Player`만의 메소드를 호출하고 있다 보니, 굳이 `Participants`를 일급 컬렉션으로 관리해야 할까 싶은 생각이 들었습니다.

```java
// 이전
public class Participants {
    private final List<Participant> participants;
}

// 이후
public class Participants {
    private final Dealer dealer;
    private final List<Player> players;
}
```

이렇게 한다면 명시적 형변환을 생략할 수 있고, 현재 `Controller`에서 플레이어 순서(`첫 번째 플레이어`)로 접근하면 이를 인덱스로 변환(`List<Participant> participants`의 `0번째 인덱스`)할 필요가 없어지게 됩니다.

그렇다면 `ParticipantOffset`과 같은 부가적인 클래스를 생략할 수 있을 것 같습니다.

```java
public class Participants {
    private final Dealer dealer;
    private final Map<Player, PlayerBet> players;
}
```

또는 `Player`가 `PlayerBet`을 갖지 않도록 하고, `Map`을 통해 `Player`와 `PlayerBet`을 매핑하는 방법도 생각해봤습니다.
이 경우 `Controller`에서 입력받은 `List<String> playersName`을 계속 사용해 플레이어의 순서를 관리하면서, 
`Player`의 순이익을 계산하는 로직을 `Player` 외부로 분리할 수 있을 것 같습니다.

이런 방식에 대해서 어떻게 생각하시나요?

### 구현 및 조합을 활용한 방식

`PlayerInfo`라는 객체는 이름도 애매하고 역할도 애매한 만큼 차라리 이를 `Dealer`에게도, `Player`에게도 동일하게 참가자 정보 관련 객체를 적용하면 일관성 있게 공통된 객체들을 하나로 묶을 수 있지 않을까 생각했습니다.

```java
public class Participant {
    private final ParticipantName participantName;
    private ParticipantCard participantCard;

    // 이름, 카드와 관련된 기능 제공
}

public interface Playable {
    // Participant를 조합으로 가지게 되면서 위임해야 할 기능을 강제하기 위한 인터페이스
}

public class Dealer implements Playable {

    private final Participant participant;

    // Playable에 명시한 위임 메소드 & Dealer에서 게임의 승패를 계산하는 메소드
}

public class Player implements Playable {
    
    private final Participant participant;
    private final PlayerBet playerBet;

    // Playable에 명시한 위임 메소드 & Player에서 게임의 승패를 계산하는 메소드
}
```

이런 식으로 한다면 조금 더 명확하게 객체의 책임을 표현할 수 있지 않을까...? 하는 생각이 들었습니다. 
이런 방식은 어떻게 생각하시나요?

---

이번 리뷰도 잘 부탁드립니다.
감사합니다!

2023-03-14 00:29 UTC, giantim requested changes
지토 안녕하세요. 리뷰어 라빈입니다 👋
정말 빠르게 피드백 받으신 내용에 대해 이것저것 고민해보시면서 개선해 주시는데 제가 리뷰가 늦어져 죄송하네요 🥲

고민거리에 대해서 같이 의견 나눠보면요!
Dealer가 게임의 승무패를 판단하는 방식은 현실의 상황을 반영한 모습인거 같네요 ☺️ 그리고 이제 계속 느끼고 계신 어색함이라 하면 Participant 객체에 Dealer와 Player를 위한 추상화인것 같네요! 그래서 생각해 주신 두 가지 방법 중 제가 봤을 때는 조합을 사용하는 방식이 다른 사람들이 코드를 봤을 때 더 이해하기 괜찮아 보여요. 일급 컬렉션으로 정의하진 Participants 내부에 Map 형태로 Player와 PlayerBet을 갖는 것이 어색해 보였어요. PlayerBet 이라고 구체적으로 Player의 베팅 현황을 알 수 있는 객체를 정의했는데 현재 구조처럼 Player가 갖고 있는게 더 응집성 높아 보이네요! 그래서 조합을 이용하여 Participants를 재구성해보는게 괜찮아 보입니다. 대신 생각하신것처럼 Playable 인터페이스에 어떤 공통 기능을 넣을지 잘 고민해봐주세요! Participant 추상 클래스를 정의했을때와 비슷한 문제가 발생하지는 않을까요? 😉

2023-03-14 00:29 UTC, giantim commented on src/main/java/domain/participant/Player.java
> +    }
setter의 역할을 하는 메서드처럼 보이는데요.
Player가 생성될 때 완전한 상태를 갖도록 생성자에서 초기화해주면 어떨까요? 다른 클라이언트 입장에서 베팅 결과 계산 전에 해당 메서드 호출을 반드시 선행해야함을 알지 않아도 될것 같아서요!

2023-03-14 03:12 UTC, apptie commented on src/main/java/domain/participant/Player.java
> +    }
이름을 입력받을 때와 배팅 금액을 입력받을 때가 달라서 `set`이랑 비슷한 느낌으로 작성했었습니다!

한 번에 초기화하는 방법...조금 더 고민해서 피드백 반영하겠습니다! 감사합니다!

2023-03-18 12:16 UTC, apptie commented
안녕하세요, 라빈!
체스 미션...너무 어려워서 한참 시간을 쓰느라 리펙토링이 늦어졌습니다..죄송합니다..

리펙토링 한 내용에 대해 정리해보겠습니다!
리뷰 잘 부탁드립니다!

---

## 리펙토링

### `Dealer`와 `Player`를 조합을 활용한 방식으로 변경

피드백 주신 내용 중 `Playable 인터페이스`와 관련된 부분을 보고, 인터페이스를 적용하면 결과적으로는 상속을 사용한 이전과 동일하게 변경될 것이라고 판단했습니다.

그래서 `Dealer`와 `Player`에 다형성을 적용할 여지를 주지 않도록 처리했습니다.

### 인덱스 대신 플레이어의 이름으로 플레이어에게 접근할 수 있도록 변경

기존에는 `List<Participant>` 컬렉션에 인덱스로 접근해 플레이어에 접근했지만, 이러한 방식은 너무 자료구조에 의존한다고 판단해 이름으로 찾을 수 있도록 변경했습니다.

### `Player` 생성 시 이름과 배팅 금액을 가질 수 있도록 한 번에 초기화

피드백 주신 내용대로 `Player` 생성 시 이름 뿐만 아니라 배팅 금액까지 가질 수 있도록 한 번에 초기화했습니다.

---

감사합니다!

2023-03-20 11:35 UTC, giantim approved these changes
지토 안녕하세요! 리뷰어 라빈입니다 👋
이번 미션에서 피드백을 서로 주고 받으며 생각을 발전시켜가는 과정이 매우 인상깊었습니다 👍
체스 미션과 병행하시면서 리팩터링 과정 진행하시느라 정말 고생 많으셨습니다. 다음 미션에 집중하셔서 좋은 결과 얻어가시길 바랄께요!

2023-03-20 11:35 UTC, giantim commented on src/test/java/domain/participant/ParticipantsTest.java
> +        participants = Participants.create(playerNames, ignored -> 1000);
Participants의 정적 팩터리 메소드에 Consumer를 넘겨주지 않아 실패하는 테스트가 있네요 😉

2023-03-20 11:35 UTC, merged

2023-03-20 13:20 UTC, apptie commented on src/test/java/domain/participant/ParticipantsTest.java
> +        participants = Participants.create(playerNames, ignored -> 1000);
이걸 놓치다니...감사합니다 ㅜㅜ