[2단계 - 블랙잭 베팅] 글렌(전석진) 미션 제출합니다.
woowacourse/java-blackjack pull request #492
Opened 2023-03-08 15:57 UTC by seokjin8678

안녕하세요 오즈!
블랙잭 미션 2단계 제출합니다!
이전에 피드백 주셨던 Service 제거와 메서드명 수정, Name 클래스 eqauls로 동등성 비교 등 피드백 적용도 해봤어요!

이번 단계에선 1단계에서 구현했던 로직들을 재사용하고 변화를 최소화 하는 방향으로 만들어봤네요!
그에 따라서 사용하지 않는 메서드들이 public으로 열려있는데 이에 따른 피드백 부탁드려도 될까요? (ex: Player - matchGame)

리뷰 기다리겠습니다! 감사합니다.

2023-03-10 08:42 UTC, ohjoohyung requested changes
안녕하세요 글렌
1단계 미션을 잘 진행해주셨다보니 2단계 미션도 금방 구현해주셨군요 👍
말씀해주셨던 부분이랑 더해서 몇가지 코멘트 남겼으니 확인 부탁드릴게요.
궁금하신 부분이 있으면 편히 DM 주셔도 괜찮습니다.
수고하셨습니다~

2023-03-10 08:42 UTC, ohjoohyung commented on src/main/java/blackjack/domain/Score.java
> +    private final boolean isBlackjack;
blackjack인지 아닌지를 알고 있는게 score의 책임일까요?
저는 몰라도 된다고 생각합니다ㅎㅎ

2023-03-10 08:42 UTC, ohjoohyung commented on src/main/java/blackjack/dto/TotalGameResult.java
> +                .sum() * -1;
개인적으로 이런 부분은 비즈니스 로직 아닐까요?
딜러 최종 수익 계산은 도메인에서 가지고 있어야할 로직 같아요.

2023-03-10 08:42 UTC, ohjoohyung commented on src/test/java/blackjack/domain/BetTest.java
> +                .doesNotThrowAnyException();
개인적으로 생성 테스트에서 적절한 값으로 객체가 생성 되었는지 값을 검증해주는게 좋다고 생각하는데요.
글렌은 어떻게 생각하시나요?

2023-03-10 08:42 UTC, ohjoohyung commented on src/main/java/blackjack/domain/Player.java
>      public GameResult matchGame(Dealer dealer) {
글렌이 말씀해주신 메서드 같아요.
matchGameWithBet이 추가됨에 따라 외부에서 사용되지 않으며 private으로 수정도 가능해졌네요.
대신 테스트에서 사용하고 있다보니 public으로 그대로 남겨두신 것 같은데, 제 생각에는 기존 테스트 삭제하고 private으로 수정해도 될 것 같습니다.
matchGameWithBet에서 같이 사용되어 테스트되고 있으니까요!

2023-03-10 08:42 UTC, ohjoohyung commented on src/main/java/blackjack/controller/DeckGenerator.java
> +package blackjack.controller;
DeckGenerator가 controller 패키지에 있는 이유가 있을까요?

2023-03-10 08:42 UTC, ohjoohyung commented on src/main/java/blackjack/view/InputView.java
> +        System.out.println(LINE_SEPARATOR + playerName + "의 배팅 금액은?");
베팅 금액으로 범위를 벗어나는 숫자(0~100,000,000)를 입력했을 때 다시 플레이어 입력으로 돌아가던데 의도하신 걸까요?

2023-03-10 08:46 UTC, ohjoohyung commented on README.md
> +```mermaid
코멘트 남기고 누르는거 깜빡해서 사라졌는데 이런게 있는지 몰랐네요.
하나 배우고 가네요.. 👍

2023-03-10 10:20 UTC, seokjin8678 commented on src/main/java/blackjack/domain/Score.java
> +    private final boolean isBlackjack;
안그래도 이 부분에 대해 SRP 원칙을 지키지 않은 것 같아 다른 객체가 책임을 갖도록 해보겠습니다!

2023-03-10 11:26 UTC, seokjin8678 commented on src/main/java/blackjack/dto/TotalGameResult.java
> +                .sum() * -1;
Controller의 비즈니스 로직을 옮기는 과정에서 수정해보겠습니다!

2023-03-10 11:32 UTC, seokjin8678 commented on src/test/java/blackjack/domain/BetTest.java
> +                .doesNotThrowAnyException();
예외가 발생하지 않으면 정상적으로 생성이 되었다 판단하여 `assertThatCode`를 사용했습니다! 
Bet의 필드로 검증하도록 변경해보겠습니다!

2023-03-10 11:33 UTC, seokjin8678 commented on src/main/java/blackjack/domain/Player.java
>      public GameResult matchGame(Dealer dealer) {
이미 커밋된 코드니 그대로 놔둘 필요는 없을 것 같네요!
테스트 코드도 중복이 되고 있으니, private 접근자로 변경해보겠습니다!

2023-03-10 11:34 UTC, seokjin8678 commented on src/main/java/blackjack/controller/DeckGenerator.java
> +package blackjack.controller;
controller만 사용해서 controller에 두었는데, domain 패키지에 두는게 적절할까요?
이 부분은 헷갈리네요 😂

2023-03-10 11:35 UTC, seokjin8678 commented on src/main/java/blackjack/view/InputView.java
> +        System.out.println(LINE_SEPARATOR + playerName + "의 배팅 금액은?");
예외 발생 시 다시 해당 플레이어의 배팅금을 입력하도록 수정해보겠습니다!

2023-03-10 13:27 UTC, seokjin8678 commented
안녕하세요 오즈!
피드백 반영하여 다시 리뷰 요청 보냈습니다!

피드백 기다리겠습니다! 감사합니다

2023-03-11 15:22 UTC, ohjoohyung commented on src/main/java/blackjack/domain/participant/Participant.java
> +        return cards.isBlackjack();
딜러, 플레이어에게 블랙잭인지 묻는 걸로 변경하셨군요 👍

2023-03-11 15:22 UTC, ohjoohyung commented on src/main/java/blackjack/domain/participant/Player.java
> +    }
메서드 순서도 변경해주셨으면 해요.
메서드는 쓰이는 순서대로 위에서 아래로 작성하는게 코드를 읽는데 도움이 됩니다.
[3번 항목](https://itdar.tistory.com/entry/%ED%81%B4%EB%A6%B0%EC%BD%94%EB%94%A9%EB%8D%94-%EB%82%98%EC%9D%80-%EC%BD%94%EB%94%A9%EC%9D%84-%ED%95%98%EB%8A%94-10%EA%B0%80%EC%A7%80-%EB%B0%A9%EB%B2%95-10-Tips-for-clean-code-better-code-quality-code)을 참고해주세요

2023-03-11 15:22 UTC, ohjoohyung commented on src/main/java/blackjack/controller/DeckGenerator.java
> +package blackjack.controller;
저는 deck을 생성해주는 비즈니스 로직이 담겨있다보니 domain 패키지에 두는게 더 적절하다고 봅니다.

2023-03-11 15:25 UTC, ohjoohyung requested changes
안녕하세요 글렌
빠르게 리뷰 반영 잘 해주셨습니다. 💯
미션 마무리 하기 전에 마지막으로 코멘트 몇개 남겼는데요.
한번 확인하고 반영해주시면 좋을 것 같습니다.
수고하셨습니다!

2023-03-11 15:31 UTC, seokjin8678 commented on README.md
> +```mermaid
저도 크루들이 사용하길래 새로 배웠네요 ㅋㅋ

2023-03-11 16:59 UTC, seokjin8678 commented on src/main/java/blackjack/domain/BlackJackGame.java
> +    }
자료구조로 `Map`을 사용할 때 참여할 사람의 순서대로 출력해야 하므로 `LinkedHashMap` 사용을 고려했지만 출력 요구 사항 중 딜러의 수익을 첫 번째로 출력해야 하므로
1. 딜러의 수익을 알기위해 모든 플레이어의 수익을 계산
2. 새로운 LinkedHashMap을 만들어 딜러의 수익을 먼저 넣고, 이전 플레이어의 수익을 전부 넣음

위와 같은 곤란한 상황이 생겨, `ParticipantProfit`과 `ParticipantProfit`의 일급 컬렉션인 `ParticipantProfits`를 만들어 봤습니다.
그런데 만들고 사용해보니 단순히 DTO가 도메인을 필드로 가지게 된 것 뿐, 기존의 방식과 큰 차이를 못느끼겠네요.
오히려 관리해야할 도메인의 갯수가 늘어 과연 좋은 설계로 바뀌게 됬는지는 잘 모르겠습니다 ㅠㅠ

2023-03-11 17:00 UTC, seokjin8678 commented on src/main/java/blackjack/domain/BlackJackGame.java
> +    }
DTO의 변경이 있거나, View가 바뀌면 도메인까지 수정해야할 일이 생기겠군요!

2023-03-11 17:03 UTC, seokjin8678 commented
안녕하세요 오즈!
수정할 내용이 많은 피드백은 아니라 바로 수정했어요.
하지만 수정하며 고민이 생겼는데 밑과 같습니다! (코멘트에도 있어요)

---

자료구조로 `Map`을 사용할 때 참여할 사람의 순서대로 출력해야 하므로 `LinkedHashMap` 사용을 고려했지만 출력 요구 사항 중 딜러의 수익을 첫 번째로 출력해야 하므로
1. 딜러의 수익을 알기위해 모든 플레이어의 수익을 계산
2. 새로운 LinkedHashMap을 만들어 딜러의 수익을 먼저 넣고, 이전 플레이어의 수익을 전부 넣음

위와 같은 곤란한 상황이 생겨, `ParticipantProfit`과 `ParticipantProfit`의 일급 컬렉션인 `ParticipantProfits`를 만들어 봤습니다.
그런데 만들고 사용해보니 단순히 DTO가 도메인을 필드로 가지게 된 것 뿐, 기존의 방식과 큰 차이를 못느끼겠네요.
도메인 객체라 테스트가 가능하지만 오히려 관리해야할 도메인의 갯수가 늘어 과연 좋은 설계로 바뀌게 됬는지는 잘 모르겠습니다 ㅠㅠ

2023-03-12 07:56 UTC, ohjoohyung approved these changes
안녕하세요 글렌
피드백 반영 속도가 정말 빠르시군요.. 👍👍
충분히 잘 구현해주셨다고 생각해서 이번 블랙잭 미션은 여기서 마치도록 하겠습니다.
고생 많으셨습니다.
다음 미션도 응원할게요. 화이팅입니다~

2023-03-12 07:56 UTC, ohjoohyung commented on src/main/java/blackjack/domain/ParticipantProfits.java
> +    private final List<ParticipantProfit> participantProfits;
질문에 대한 답변은 여기 코멘트 해둘게요!
말씀해주신 것처럼 기존 DTO 구조랑 비슷한 도메인 객체가 만들어졌다고 생각합니다. 하지만, DTO에 비즈니스 로직이 있었기에 오히려 적절하게 도메인으로 바뀌었다고 생각해요. 모든 비즈니스 로직은 도메인에 두는 형태로 가야하는 거죠. 

대신 말씀해주신 것처럼 관리해야 할 도메인이 늘긴 했는데, 도메인이 책임에 맞게 적절하게 나눠졌으면 괜찮습니다. 그게 아니라면 필요 이상으로 많이 나눠진 것인가 의심해봐야겠죠. 언급해주신 LinkedHashMap을 사용해도 어떻게든 순서에 맞게 구현을 해볼 순 있긴 할 것 같네요. 다른 방법도 있겠지만 이런 식으로요ㅎㅎ
```java
Map<Participant, Integer> result = new LinkedHashMap<>();
result.put(dealer, 0);
int dealerProfit = 0;
for (Player player : players) {
  int playerProfit = player.matchGameWithBet(dealer).getBet();
  result.put(player, playerProfit);
  dealerProfit -= playerProfit;
}
result.put(dealer, dealerProfit);
```
다만, 지금 구현해주신 것도 충분히 괜찮다고 봅니다. 
제 생각에는 도메인보다는 오히려 DTO를 사용하지 않았으면 전체적인 구조가 더 심플해졌을 것 같아요. 사실 이정도 규모의 프로그램에서는 DTO는 고려하지 않아도 괜찮다고 생각하거든요 😄

2023-03-12 07:56 UTC, merged

2023-03-12 08:47 UTC, seokjin8678 commented on src/main/java/blackjack/domain/ParticipantProfits.java
> +    private final List<ParticipantProfit> participantProfits;
미리 딜러의 수익을 0으로 저장해두고 수익을 전부 계산한 다음 Map에 덮어 씌우면 됐었겠군요!
덕분에 다시 배우네요 👍

DTO를 사용하지 않아도 됐지만 여러 객체를 한 번에 묶어 보낼 수 있는 이점이 크다 판단하여 사용하게 되었네요!

좋은 피드백 주셔서 감사해요!!!