[2단계 - 블랙잭 베팅] 다즐(최우창) 미션 제출합니다.
woowacourse/java-blackjack pull request #494
Opened 2023-03-09 02:28 UTC by woo-chang

안녕하세요 토니 🥃 1단계 리뷰 내용을 바탕으로 2단계 미션도 진행해 보았습니다!

2단계 미션에서의 변화와 1단계와 같이 질문사항을 아래에 정리해 보았습니다. 잘 부탁드리겠습니다 :)

## 변화

1. 기존에는 블랙잭 게임 전체적인 관리를 컨트롤러에서 진행했습니다. 2단계 미션을 진행하면서 컨트롤러의 역할이 너무 커지는 것 같아 `BlackJackGame` 도메인을 추가하여 역할을 분리해 보았습니다!
2. 도메인 -> dto 변환 책임을 컨트롤러에서 dto로 이동하였습니다!
3. 베팅을 위한 베팅, 수익 도메인을 구현하였습니다!

위의 변화가 가장 큰 변화라고 생각합니다.

## 궁금한 점

도메인 내부에 도메인을 가지고 있고 하위 도메인의 정보가 필요할 때 어디서 변환이 발생해야 하는지 의문이 들었습니다. 예시는 아래와 같습니다.

```java
public class Order {

    private final String name;

    public Order(final String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
```

```java
public class Orders {

    private final List<Order> orders;

    public Orders(final List<Order> orders) {
        this.orders = orders;
    }

    public List<String> getOrderNames() {
        return orders.stream()
            .map(Order::getName)
            .collect(Collectors.toList());
    }

    public List<Order> getOrders() {
        return orders;
    }
}
```

```java
public class OrderService {

    private final Orders orders;

    public OrderService(final Orders orders) {
        this.orders = orders;
    }

    public List<String> getOrderNames() {
         //1번 방법
        return orders.getOrders().stream()
            .map(Order::getName)
            .collect(Collectors.toList());
        //2번 방법
        return orders.getOrderNames();
    }
}
```

OrderService에서 주문 목록의 이름이 필요할 때, 1번과 2번 방법 중 고민이 되었습니다. 2번이 메시지를 던지는 방법인 것 같아서 해당 방법이 맞는 것 같지만, OrderService의 getOrderName는 단순히 위임 메서드가 되어버리는 느낌이 들었습니다. OrderService에는 주문 목록 이름을 물어보는 상황이 있지만 Orders는 주문 목록 이름을 물어보는 상황이 발생하지 않는다면 1번 방법을 고려해도 괜찮지 않을까 하는 생각도 들었습니다.

이 부분에 대해서 토니의 의견이 궁금합니다!

그 외에도 보완하거나 수정이 필요한 부분에 대해서 말씀해주신다면 많이 고민하고 학습해 보겠습니다. 감사합니다 🍸

2023-03-09 11:47 UTC, toneyparky requested changes
안녕하세요 다즐~ 토니에요

2단계 미션도 깔끔하게 잘 구현해주셨네요. DTO로 변환 로직을 옮기니 컨트롤러가 더 깔끔해졌네요. 중첩된 테스트도 잘 적용해주셨구요..! 특히 코딩 컨벤션을 지키며 개발하려하신 점이 눈에 띄었습니다 👍 

몇가지 코멘트와 질문에 대한 답변을 남겼으니 확인 부탁드려요~

2023-03-09 11:47 UTC, toneyparky commented on README.md
>      - 딜러는 최대 3장의 카드만 받을 수 있다.
해당 부분에 대한 테스트나 로직은 어디에 있나요?

2023-03-09 11:47 UTC, toneyparky commented on README.md
> +    - 동시에 블랙잭이라면 플레이어는 베팅한 금액을 딜러에게 받는다.
딜러와 플레이어가 동시에 블랙잭인 부분에 대한 로직과 테스트는 있을까요?

2023-03-11 16:11 UTC, woo-chang commented on README.md
>      - 딜러는 최대 3장의 카드만 받을 수 있다.
리팩토링을 진행하며 테스트 코드를 추가로 작성하였습니다!

2023-03-11 16:12 UTC, woo-chang commented on README.md
> +    - 동시에 블랙잭이라면 플레이어는 베팅한 금액을 딜러에게 받는다.
이 부분도 위와 마찬가지로 추가로 작성하였습니다!

2023-03-11 16:14 UTC, woo-chang commented on src/main/java/blackjack/controller/BlackJackController.java
> +    private List<ParticipantResultResponse> createPlayerResultResponses(final BlackJackGame blackJackGame) {
말씀해주신대로 해당 역할을 담당하는 `dto`를 생성하였더니 컨트롤러가 조금 더 깔끔해진 것을 직접 느낄 수 있었습니다.

`ParticipantResultResponse`에 `List`를 반환하게 하는 `listOf`와 같은 정적 팩터리 메서드를 생성하는 건 어떤지도 궁금합니다!

2023-03-11 16:15 UTC, woo-chang commented on src/main/java/blackjack/domain/betting/Betting.java
> +public class Betting {
좋은 의견 감사합니다 👍 훨씬 의미있는 도메인이 된 것 같습니다 ㅎㅎ

2023-03-11 16:16 UTC, woo-chang commented on src/main/java/blackjack/controller/BlackJackController.java
> +        final ParticipantResponse dealer = ParticipantResponse.hiddenForDealer(blackJackGame.getDealer());
저도 이번에 블랙잭 게임을 처음 알게 되었습니다! 딜러는 처음 2장을 뽑고 한장을 플레이어에게 공개하지 않는 것 같습니다. 2장을 플레이어가 알고 시작하면 플레이어의 승률이 높아져서 해당 룰이 존재하는 것 같습니다 👾

2023-03-11 16:24 UTC, woo-chang commented on src/main/java/blackjack/domain/BlackJackGame.java
> +    }
모든 코드에 절대적인 기준이 없다는 것을 다시 한번 생각해보게 되었습니다!

지금은 학습하는 단계인만큼 최대한 제약을 걸어 진행하였습니다. 따라서 내부 필드에 대한 게터는 `dto`에서만 사용하도록 스스로 제약사항을 걸어보았습니다. 그로 인해 중첩 메서드가 많아지는 것을 직접 확인할 수 있었습니다.

실제 서비스 도메인에서도 도메인안에 도메인을 가지고 있어 중첩적인 메서드가 많이 발생하는지 궁금합니다 🤔

2023-03-13 01:11 UTC, toneyparky commented on src/main/java/blackjack/domain/card/Hand.java
>      }
DM을 통해 말씀해주신 리팩터링 부분이네요~!
기존 Cards 객체에서 가지고 있던 addCard와 같은 상태 변화 행위를 제거하여 불변 객체를 지향하도록 수정해주셨군요.

이렇게 수정하신 이유와 장점이 있을까요~?

2023-03-13 01:11 UTC, toneyparky commented on src/main/java/blackjack/domain/BlackJackGame.java
> +    }
크... 해당 책임은 `Score`, `Dealer` 을 거쳐 `BlackJackGame`에 도착했군요. `BlackJackGame`이 `Dealer`를 알고 있으니 딜러에게 물어봐서 해당 결과를 구할 수도 있었는데 `BlackJackGame` 내부 구현으로 옮기신데에는 어떤 이유가 있나요~?

2023-03-13 01:11 UTC, toneyparky commented on README.md
>      - 딜러는 최대 3장의 카드만 받을 수 있다.
네, 테스트 코드가 추가되니 훨씬 좋아졌어요! 

중첩된 테스트를 활용하여 복잡한 요구 사항을 잘 풀어내주셨네요...! 테스트 코드를 통해 테스트하려는 객체가 어떤 행위를 수행하는지 쉽게 확인할 수 있어요! 다음 미션인 체스도 코드 양이 많을텐데 테스트를 꼼꼼하게 작성하시면 리팩터링하실 때에 이해하기도 쉽고 버그 발생 여지가 줄어들거에요..! 고생 많으셨습니다 😉

2023-03-13 01:11 UTC, toneyparky commented on src/main/java/blackjack/controller/BlackJackController.java
> +    private List<ParticipantResultResponse> createPlayerResultResponses(final BlackJackGame blackJackGame) {
`ParticipantResultResponse.listOf()` 를 만들어서 여러개의 `ParticipantResultResponse`를 반환할 수 있도록 하는거에요. 제가 말을 조금 어렵게 적었네요. 

작성해주신 `ParticipantResultResponses#listOfParticipants()`를 굳이 `ParticipantResultResponses` 객체에 두지 않고 `ParticipantResultResponse`객체에 두되 `listOf()`라는 메서드로 복수의 DTO가 반환됨을 표현할 수 있다는 의미였어요. 

크게 중요한 부분이 아니고 취향의 영역이라 생각됩니다~

2023-03-13 01:11 UTC, toneyparky commented on src/main/java/blackjack/domain/betting/Betting.java
> +public class Betting {
굳굳~ 수정해주신 덕에 `Profit`도 보다 의미있는 이름인 `Betting`으로 바뀌었군요!

2023-03-13 01:11 UTC, toneyparky commented on src/main/java/blackjack/domain/BlackJackGame.java
> +    }
굳굳 학습을 목적으로 경험해보시는거 좋네요 👍 

이것도 실제 서비스의 팀, 프로젝트마다 다를 것 같아요. 저희 팀은 상위의 객체에서 반환할 때 하위 객체의 게터를 꼬리를 물며 사용하는 편이에요. 

다만 이는 저희 팀에서 코틀린을 사용하여 게터를 이용한 자바보다 프로퍼티 형식으로 값을 가져오기에 깔끔하게 보이는 장점이 있어요. 프로퍼티 형식이라함은 굳이 게터를 생성하지 않아도 프로퍼티의 값을 가져올 수 있답니다. 그리고 코틀린은 가독성 향상을 위한 여러가지 추가 문법들이 있어서 더 가독성이 좋구요.

더 궁금하신 부분은 [코틀린 공식 문서](https://kotlinlang.org/docs/properties.html)를 읽어보시고 질문 주셔도 좋겠네요!

2023-03-13 01:11 UTC, toneyparky commented on src/main/java/blackjack/controller/BlackJackController.java
> +        final ParticipantResponse dealer = ParticipantResponse.hiddenForDealer(blackJackGame.getDealer());
크.. 좋네요! 다즐의 코드만으로 이해할 수 있었어요. 해당 도메인/요구사항에 대해 고민하시고 명확하게 표현하려하셨기에 제가 이해할 수 있었네요!

2023-03-13 01:13 UTC, toneyparky requested changes
안녕하세요 다즐~! 토니입니다!

이야기 나눴던 부분에 대해 초점을 맞춰 리팩터링해주셨군요...! 전체적으로 잘 적용되었네요!
궁금한 사항에 대해 추가로 질문을 남겼으니 답변 해주시면 감사하겠습니다.
리뷰로 인한 코드 변경사항은 별로 없을테지만 이야기를 더 나누면 좋겠어서 머지는 아직 하지 않을게요~

이번주도 화이팅이에요!

2023-03-13 03:34 UTC, woo-chang commented on src/main/java/blackjack/controller/BlackJackController.java
> +    private List<ParticipantResultResponse> createPlayerResultResponses(final BlackJackGame blackJackGame) {
`3`이라는 숫자를 보고 내용을 착각하게 되었던 것 같습니다 ㅎㅎ..

결국 `ParticipantResultResponse`를 만드는 것이기에 `ParticipantResultResponse`에 메서드를 두는게 맞는 것 같습니다 👍

2023-03-13 03:43 UTC, woo-chang commented on src/main/java/blackjack/domain/BlackJackGame.java
> +    }
토니의 팀은 코틀린을 사용하는군요! 꼬리를 물며 사용한다는 팀 규칙도 흥미로운 것 같습니다~

자바에 대해 조금 더 숙련도가 올라가면, 코틀린도 공부해보고 싶어지네요 감사합니다 ⛄️

2023-03-13 04:01 UTC, woo-chang commented on src/test/java/blackjack/domain/BlackJackGameTest.java
> +                );
중복으로 동작하는 설정은 상위 컨텍스트에서 수행하여 반복을 줄이는 방법도 있네요 감사합니다 👍

2023-03-13 04:08 UTC, woo-chang commented on src/main/java/blackjack/domain/card/Hand.java
>      }
불변 객체의 장점과 연결된다고 생각합니다. 현재 미션에는 적용되지 않지만 멀티 쓰레드 환경에서 `thread-safe`한 동작을 수행할 수 있고, 내부 상태가 변하지 않기에 객체를 예측 가능한 상태로 사용할 수 있다고 생각합니다.

객체를 새로이 생성하는 비용이 추가로 발생하지만, 불변을 지킴으로 얻을 수 있는 장점이 더욱 크다고 생각했습니다.

2023-03-13 05:04 UTC, woo-chang commented on src/main/java/blackjack/domain/BlackJackGame.java
> +    }
`BlackJackGame` 도메인을 생성하면서 결과를 확인하는 역할은 `BlackJackGame`이 관리하는 것이 자연스러워 보였습니다. `BlackJackGame`의 결과를 확인하는 로직이 변경되었을 때, `Dealer`의 코드를 확인하기보다는 `BlackJackGame`을 확인할 것 같았습니다!

결과를 생성하고 `BettingTable`로부터 베팅 금액을 확인해 자연스럽게 수익계산까지 가능해져서 옮기게 되었던 것 같습니다.

하지만 지금 다시 확인하니 `BlackJackGame`이 가지는 역할이 조금 커지는 느낌도 드는 것 같은데 토니의 생각도 궁금합니다!

2023-03-13 09:11 UTC, toneyparky commented on src/main/java/blackjack/controller/BlackJackController.java
> +    private List<ParticipantResultResponse> createPlayerResultResponses(final BlackJackGame blackJackGame) {
넹 요 부분은 저도 신기하군요.. 마크다운 문법 오류인가 싶어요

저도 `ParticipantResultResponse`로 두는거 괜찮다 생각합니다.

2023-03-13 09:11 UTC, toneyparky commented on src/test/java/blackjack/domain/BlackJackGameTest.java
> +                );
네 DCI 패턴의 단점인 중복을 개선할 수 있는 방법이에요!

2023-03-13 09:15 UTC, toneyparky commented on src/main/java/blackjack/domain/card/Hand.java
>      }
불변 객체의 장점에 대해 이미 학습하셨군요. 말씀하신대로 객체가 변경되어 발생할 수 있는 사이드 이펙트를 최소화할 수 있다는 장점이 있어요. 불변 객체는 일반 객체보다 신경써야할 부분이 많아서 구현하기가 까다롭죠. 그렇기에 놓칠 수 있지만 지금처럼 도메인 레이어와 같이 사이드 이펙트를 최소화해야하는 부분에 적용해보며 학습해보면 좋겠네요.
[관련 테코톡 영상](https://www.youtube.com/watch?v=ej-bnXlHk-E)도 첨부드려요~

2023-03-13 09:22 UTC, toneyparky commented on src/main/java/blackjack/domain/BlackJackGame.java
> +    }
음.. 이 코멘트를 남긴 데에도 다즐이 인지하셨듯 `BlackJackGame`의 역할이 커진다는 느낌을 받아서에요.

개선에 대한 방법은 1단계에서도 여쭤봤던 부분 같네요. 다즐의 코멘트를 보면 `결과`라는 단어가 많이 나오고 있어요. 그렇기에 저라면 결과를 담당하는 `Result` 객체로 옮기지 않을까해요. 기존에 `Dealer`에서 구현하셨을 때에 우려하셨던 인자가 뒤섞이는 우려는 지금도 충분히 발생할 수 있구요. `Result` 객체에서는 딜러, 플레이어라는 개념을 알릴 필요 없이 `Participant`, `opponentParticipant` 정도의 개념으로 구현할 것 같네요.

그 이외의 `BlackJackGame` 로직은 게터가 많고 지금의 구조에서는 그럴 수 밖에 없는지라 괜찮아보여요. 만일 게터를 제거하기 위해서 `Participants`를 외부로 노출한다면 그만큼 컨트롤러에 맞닿는 도메인 객체가 많아지는거라 도메인이 변경에 취약해질거에요. 잘 해주셨어요 👍

2023-03-13 09:29 UTC, toneyparky commented on src/main/java/blackjack/controller/dto/ParticipantResponse.java
> +public class ParticipantResponse {
DTO는 레이어간의 정보를 이동하기 위한 객체죠. 지금은 도메인의 정보를 받아서 뷰로 이동시켜주고 있구요. 이말은 DTO는 사용되는 곳의 요구사항에 따라 생성되고 변경된다는 점을 의미해요. 예를 들면 지금 `DealerStateResponse`에서는 `limit`, `isDrawn` 값을 뷰에 반환하고 있죠. 하지만 요구사항이 바뀌어 뷰에서 추가로 정보를 요할 경우 `DealerStateResponse`는 다른 값도 반환할 필요가 생겨요. 즉 DTO를 사용하는 뷰의 요구사항에 따라 DTO가 변경되었음을 의미합니다.

이런 관점에서 현재의 `ParticipantResponse`는 범용적인 DTO일 수도 있겠다는 생각이 들어요. 정말 딜러와 플레이어에 대한 정보를 뷰에서 보여줄 때에 같은 내용으로 보여줄 것인가에 대한 고민이에요. 현재로서는 같고 변화할 가능성이 적다면 지금처럼 구현하는 것도 좋아요. 하지만 뷰 레이어는 수정이 빈번할 수 있기에 각 정보가 사용되는 곳에 맞게 DTO를 생성해주면 좋습니다.

예를 들면 `ParticipantResponse` 객체는 `OutputView`의 `printCardsWithScore`와 `formattedPlayerNames`라는 부분에서 값을 출력해주기 위해 사용되고 있어요. 즉 사용처가 두 군데라는 거죠. 이럴 경우 `formattedPlayerNames`의 요구사항만 변한다면 이를 반영하기 위해 `ParticipantResponse`를 수정하겠죠. 하지만 `printCardsWithScore`와 `ParticipantResponse`를 공유하고 있기에 `printCardsWithScore`입장에서는 필요 없는 게터까지 존재하게 되어요. 즉 범용적인 DTO가 되어버렸어요.

그렇기에 DTO를 생성하실 때에 형태적인 측면보다 유즈케이스의 측면으로 접근하시는 편이 좋다고 생각합니다.

2023-03-13 12:09 UTC, woo-chang commented on src/main/java/blackjack/domain/BlackJackGame.java
> +    }
`Dealer`의 점수와 `Player`의 점수, `pivot(blackjack score)` 점수를 받아 `Result`에서 결과를 계산하도록 역할을 수정하였습니다!

> 그 이외의 BlackJackGame 로직은 게터가 많고 지금의 구조에서는 그럴 수 밖에 없는지라 괜찮아보여요. 만일 게터를 제거하기 위해서 Participants를 외부로 노출한다면 그만큼 컨트롤러에 맞닿는 도메인 객체가 많아지는거라 도메인이 변경에 취약해질거에요. 잘 해주셨어요 👍

위임 메서드가 너무 많아 `BlackJackGame`이 정말 필요한가라는 고민도 들었는데 참가자들, 덱, 베팅을 관리하고 해당 도메인에 접근하기 위한 필터로 필요하다는 결론에 도달했습니다. 이번 미션을 통해 좋은 인사이트를 많이 얻어가는 것 같습니다 😆

2023-03-13 12:17 UTC, woo-chang commented on src/main/java/blackjack/controller/dto/ParticipantResponse.java
> +public class ParticipantResponse {
토니가 말한대로 출력의 형태가 같다는 이유로 딜러와 플레이어의 `DTO`를 범용적으로 사용하고 있었습니다. 하지만 이런 방법은 말씀해주신대로 변경에 유연하지 못한 구조라고 생각합니다!

> 그렇기에 DTO를 생성하실 때에 형태적인 측면보다 유즈케이스의 측면으로 접근하시는 편이 좋다고 생각합니다.

한 줄로 모든 의미를 담고 있는 말이라고 생각합니다. 마지막까지 꼼꼼하게 리뷰해주셔서 너무너무 감사합니다 👍🏻👍🏻

2023-03-14 00:42 UTC, toneyparky commented on src/main/java/blackjack/domain/participant/Result.java
> +    public static Result show(final int targetScore, final int compareScore, final int pivot) {
테스트까지 작성되었다면 더 완벽했겠군요~!

2023-03-14 00:42 UTC, toneyparky commented on src/main/java/blackjack/domain/BlackJackGame.java
> +    }
넹~ 해당 역할을 컨트롤러가 할 수도 있지만 도메인 객체의 노출을 최소화하기 위해 `BlackJackGame` 객체에서 책임을 담당하고 있다고 봐주시면 좋겠네요!

2023-03-14 00:44 UTC, toneyparky commented on src/main/java/blackjack/controller/dto/ParticipantResponse.java
> +public class ParticipantResponse {
넵 조금은 어려울 수 있는 내용인데 잘 이해해주셨군요. 추후 웹 서버를 만들게 되면 이 부분이 더 와닿을거에요. Post API의 경우 Body를 통해 정보를 받을텐데 이 정보는 DTO에 담기게 되죠. Get API에서 정보를 응답할 때도 마찬가지구요. 각 API는 유즈케이스를 의미하므로 DTO를 분리하는 경험을 하실겁니다 😊

2023-03-14 00:46 UTC, toneyparky approved these changes
안녕하세요 다즐~ 좋은 아침이에요! 

리뷰와 DM으로 충분히 이야기를 나눈 것 같네요~ 까다로운 코멘트도 있었을텐데 잘 학습해주셨어요 👍 
블랙잭 미션 고생 많으셨고 산뜻한 기분으로 다음 미션인 체스를 맞이하시죠~!

머지하도록 하겠습니다~

2023-03-14 00:46 UTC, merged