[2단계 - 블랙잭 베팅] 오리(오현서) 미션 제출합니다.
woowacourse/java-blackjack pull request #495
Opened 2023-03-09 07:35 UTC by carsago

안녕하세요 제이온 2단계 리뷰도 잘 부탁드립니다. !!

2단계 미션을 진행하면서 요구사항의 추가도 있었지만 어느정도 리팩터링도 어느정도 진행했던 것 같아요.

제가 주로 수정했던, 혹은 고민했던 부분은 하단 혹은 코드 블럭에 작성해놓을게요!

우선 리팩토링을 하면서 DTO 생성 로직을 BlackJackGame 에서 BlackJackApplication으로 옮겼어요. 

좋았던 점은 확실히 BlackJackGame에서 로직을 제외한 View에 의존하는 부분을 제거할 수 있었어요.

하지만 BlackJackApplication의 코드가 너무 비대해졌네요. 코드를 줄이기 위해 DTO 매핑 관련된 역할을 하는 클래스를 만들까도 고민해봤지만, 그 객체가 BlackJackGame에 의존하는게 아닌 이상(그렇게 하는것도 좋은 방법은 아니라고 생각해요.) 딱히 코드가 많이 분리될 것 같단 생각은 안들었습니다. application이 하나의 메소드로 전체 로직을 진행하기에 코드가 많아지는 건 어쩔 수 없다는 생각도 들었습니다.

2023-03-09 07:44 UTC, carsago commented on src/main/java/domain/BlackJackBettingDeposit.java
> +}
플레이어 마다 배팅하는 금액을 저장하기 위해 BlackJackBettingDeposit을 만들어 역할을 할당했어요. 하지만 이 객체가 하는 일이 단순히 put and get 밖에 없어서 조금 애매하다는 느낌도 들고 Application에서 생성되서 돈을 찾기 위해 왔다갔다 하는 로직이 별로였습니다.

다만 다른 방법들 보다 이 방법이 그나마 더 괜찮다고 느꼈어요. 제가 생각해 본 방법은 다음과 같아요.

1. BlackJackGame에서 이 객체를 필드로 가지게한다.

로직을 좀 더 캡슐화 할 수 있겠지만, 지금도 BlackJackGame은 Players, Dealer, CardDeck을 가지고 있기 때문에 이 객체 까지 가진다면 생성을 하기가 너무 무거워지고, 이에 따라 테스트가 너무 어려워진다고 판단했어요. 

지금도 의존이 많아서 테스트가 부담스럽다 보니, 추가적인 의존을 만들고 싶지 않았어요.

2. Player가 돈을 가진다.

우선 위와 같이 BlackJackGame이 Player도 가지기 때문에 Player가 돈을 가지면 마찬가지로 BlackJackGame의 테스트가 너무 어려워진다고 여겼습니다.

또한 Player의 내부로 갖는것에 대해 고민한건 다음과 같아요.

2.1 생성자로 배팅 금액을 넣어주는 경우

요구사항 상, 여러 이름을 받은 다음, 각 이름(플레이어)들이 배팅 금액을 할당합니다. 그런데 만약 배팅 금액을 할당한 후 Players에 대한 예외가 존재하는 경우 문제가 생겨요. 

이름 입력 -> 순회하여 배팅 금액 할당 -> Players 생성 이런 순서로 로직이 진행되기 때문에

만약 Players에서 중복된 이름, 혹은 size 예외가 발생한다면 처음부터 이름 입력으로 돌아가야 합니다.


2.2 Players에게 setter와 유사한 메소드(명칭은 setter가 아니겠지만)로 배팅 금액을 할당하는 경우

- 이 부분에 대한 불호는 setter를 안쓰는 이유와 같아요. 이름만 다른 뿐 똑같은 문제점을 야기할 수 있다고 여겼어요

이런 이유로 전 이 객체를 Application에서 생성하고, 사용했습니다.

2023-03-09 07:49 UTC, carsago commented on src/main/java/domain/card/CardDeckGenerator.java
>          return CardDeck.createShuffled(cards);
이 부분의 테스트에 대한 질문을 ```제이온이 CardDeck.createShuffled mocking 하는것이 그나마 최선이다.``` 라고 말씀해주셨는데요. 이건 Mockito와 같은 라이브러링 활용한 mocking을 말씀 하신걸까요 ?_?

2023-03-10 14:47 UTC, pjy1368 requested changes
안녕하세요 오리!
2단계 미션도 빠르게 잘 진행해 주셨네요 👍
1단계 코드 자체가 구조도 잘 잡혀있고 깔끔해서 적은 변경만으로도 필요한 요구 사항을 만족한 것 같습니다. 간단한 피드백 위주지만 구조 변경이 있을 수 있는 부분이 있어서, 반영해 보시고 리뷰 요청 부탁드릴게요~

2023-03-10 14:47 UTC, pjy1368 commented on src/main/java/domain/BlackJackResult.java
> +    EACH_BLACKJACK(money -> 0);
enum을 잘 사용해 주셨네요!
특히 함수형 인터페이스도 적절합니다 👍

2023-03-10 14:47 UTC, pjy1368 commented on src/main/java/domain/BlackJackResult.java
> +    private IntUnaryOperator expression;
요건 final로 설정해도 될 것 같습니다~

2023-03-10 14:47 UTC, pjy1368 commented on src/main/java/domain/card/CardDeckGenerator.java
>          return CardDeck.createShuffled(cards);
넵 그렇습니다~ Mockito를 통해 테스트하기 어려운 `CardDeck.createShuffled`를 mock시킬 수도 있고, 자동차 경주 게임을 했던 것처럼 create() 메서드에다가 인터페이스(카드를 셔플하는 방식)를 파라미터로 넣는 방법도 있습니다.

2023-03-10 14:47 UTC, pjy1368 commented on src/main/java/dto/response/ParticipantResult.java
> +        for (Card drawnCard : drawnCards) {
이 로직 스트림 써서 아래처럼 바꿔보면 어떨까요?
```java
drawnCards.stream()
    .map(ParticipantResult::renderCardName)
    .collect(Collectors.toList())
```

그리고 또 생각나는 부분이 현재 renderCardName static method가 ParticipantResult에도 정의되어 있고, DrawnCardsInfo에도 정의되어이는데, renderCardName static method를 CardNameRender에 정의하고 공통으로 쓰는건 어떻게 생각하시나요?

2023-03-10 14:47 UTC, pjy1368 commented on src/main/java/domain/BlackJackBettingDeposit.java
> +}
저는 Player가 Money를 가지고 있는 것이 코드를 이해함에 있어서 더 자연스럽다고 생각합니다.
Player가 Money를 갖게 하지 않은 이유는 객체의 관점이 아닌 단순히 재입력의 순서때문인데, 이것은 재입력의 순서를 올바르게 맞출 수 있도록 수정해야 하는 신호이기도 합니다. Players에서 이름의 중복을 검사하는 것이 아니라 Names 객체에서 먼저 검사하고 Players에게 넘겨주는 방식으로 수정해 보면 어떨까요?

2023-03-10 14:47 UTC, pjy1368 commented on src/main/java/application/BlackJackApplication.java
> +    }
잘 반영해주셨네요~
저도 이런 식으로 Application에서 DTO를 조립하기를 의도했습니다.
추가로, PR 본문에서 애플리케이션의 로직이 방대해졌다고하였는데 말씀 주신대로 DTO 조립용 레이어를 하나 더 둘 수도 있고, 아니면 컨트롤러 레이어를 두고 여러 컨트롤러로 쪼개면 어느 정도 해소가 가능합니다.
스프링 미션을 진행하시면서 자연스럽게 습득이 가능한 부분이라 지금 단계에서는 이대로 두셔도 훌륭합니다!

2023-03-11 04:37 UTC, carsago commented on src/main/java/dto/response/ParticipantResult.java
> +        for (Card drawnCard : drawnCards) {
훨씬 깔끔하게 중복을 제거하고 가독성을 개선할 수 있었네요 !!

아무래도 도메인 객체 위주로 신경쓰다보니 이런 부분을 놓쳤었습니다 T_T

2023-03-11 07:09 UTC, carsago commented on src/main/java/domain/BlackJackGameGenerator.java
> +}
비대해진 BlackJackApplication의 책임을 줄이기 위해 BlackJacGame을 생성하는 역할을 아예 뺐습니다

이 클래스를 인터페이스로 할려고도 했지만, 이미 Application 자체가 InputView 와 OutputView에 의존 하는 상태이기 때문에 그렇다고 큰 장점은 없다고 여겼어요

2023-03-11 07:44 UTC, carsago commented
안녕하세요 제이온 !

이번에는 말씀해주신 부분 위주로 리팩터링을 진행했습니다.

블랙잭 미션을 통해서 구체적으로 ~~를 배웠다기 보다는 객체의 역할과 책임 할당이라는 부분에 대해서 말로 설명은 못하겠지만(애초에 수학처럼 명확하게 떨어지는게 아니다 보니 ㅎㅎ;) 조금씩 감을 잡고 저만의 기준을 하나씩 익혀나갈 수 있었어요. 

아직은 많이 부족하지만 다음 미션,  나아가 Level 2  까지 진행하다보면 그래도 주변 크루들이 납득할만한 설명을 할 수 있을만큼 늘 수 있을거라 기대하고 있어요 !!

2023-03-11 13:16 UTC, pjy1368 approved these changes
안녕하세요 오리!
1차 피드백을 잘 반영해 주셔서 크게 수정이 필요한 부분은 보이지 않았습니다 👍
나머지는 생각해볼 만한 피드백을 남겨뒀는데, 이번 미션에 추가로 반영해 보거나 다음 미션부터 반영해 보면 어떨까 합니다.
고생 많으셨고 이만 머지할게요~

2023-03-11 13:16 UTC, pjy1368 commented on src/test/java/domain/participant/DealerTest.java
> +
요런 Card 객체들이 다른 테스트 클래스에서도 쓰이고 있는 것 같은데, TestFixture에 대해 학습하셔서 공용 테스트 객체를 분리해보면 어떨까요? TestFixture를 쓰지 않더라도 해당 테스트 클래스에서 반복되는 객체는 필드로 빼시면 중복 코드를 줄일 수 있습니다~
https://thalals.tistory.com/375

2023-03-11 13:16 UTC, pjy1368 commented on src/main/java/domain/BlackJackGameGenerator.java
> +}
분리한 덕분에 BlackJackApplication의 책임은 줄었네요!
하지만 BlackJackGameGenerator가 도메인 패키지 안에 있는 만큼 가능한 View에 의존하는 것은 지양해야하는데, InputView에 의존을 하고 있네요 😥
개인적으로 현재는 비대하더라도 Application에 검증 로직들을 넣어 주거나, BlackJackGameGenerator를 application 패키지로 옮기는 방법을 선택하면 어떨까 합니다~

2023-03-11 13:16 UTC, pjy1368 commented on src/main/java/domain/participant/Player.java
> +    private final BettingMoney bettingMoney;
BettingMoney를 Player가 의존하게 되면서 코드를 이해하기 더 쉬워진 것 같네요 👍

2023-03-11 13:16 UTC, pjy1368 commented on src/main/java/domain/BlackJackGame.java
> -                .forEach(player -> splitEachParticipant(player, cardDeck));
가능한 스트림 API에서 forEach를 사용할 때, 외부 객체의 상태를 조작하는 것은 지양하시길 권장드립니다!
스트림 API는 함수형 프로그래밍을 받아들이기 위해 탄생하였고, 함수형 프로그래밍이 여러 특징 중 대표적인 것이 순수 함수를 사용한다는 것입니다. 이 순수 함수는 동일한 input이 들어왔을 때 동일한 output이 나오길 의도합니다. 하지만 forEach 내부에서 스트림과 상관없는 외부 객체를 건드리게 된다면, 동일한 input이 들어왔음에도 예외가 발생할 수가 있습니다. 또한, forEach는 병렬 처리가 불가하여 성능이 좋지 않다는 점도 있어서 forEach는 가능한 로깅을 위해 사용하라고 권장하고 있습니다.
따라서 forEach 안에 로직을 넣기 보다는 스트림의 풍부한 API를 더 활용하시거나, 일반 for문을 사용하는 것을 추천드립니다! 어려운 내용이지만, 일찍 머지하는 만큼 학습하시면 좋을 것 같아서 코멘트 남겼습니다 😊

2023-03-11 13:16 UTC, merged