[2단계 - 사다리 게임 실행] 연어(황재현) 미션 제출합니다.
woowacourse/java-blackjack pull request #502
Opened 2023-03-10 03:27 UTC by nuyh99

럿고 안녕하세요!
1단계 피드백은 최대한 적용해봤습니다. 잘 부탁드려요😃

이전 피드백에서 `Player` 클래스에서 `stand` 필드를 두어야 하냐고 하셨는데, 이를 두지 않기 위해서 상태 패턴을 사용하면 좋을 것 같습니다.
다만 상태 패턴을 사용한다면 어떤 상태에서는 사용할 수 없는 메서드도 받게 되어 `UnsupportedException` 등의 예외를 던지도록 구현하는데, 이 또한 별로 맘에 들지 않습니다ㅠㅠ

중복 코드를 제거하는 것과 리스코프 치환 법칙 사이에서 trade off가 발생하는데, 혹시 럿고 만의 기준이 있을 지 궁금합니다...!

2023-03-11 10:20 UTC, ksy90101 commented on src/main/java/domain/participant/Participant.java
> +    public static final int INITIAL_HAND_SIZE = 2;
public인 이유가 있을까요?

2023-03-11 10:21 UTC, ksy90101 commented on src/main/java/domain/participant/Participant.java
> +        return calculateScore() == BLACKJACK;
```suggestion
     return getCards().size() != INITIAL_HAND_SIZE && calculateScore() == BLACKJACK;
```
이런식으로 가능하지 않을까요?

2023-03-11 10:22 UTC, ksy90101 commented on src/main/java/domain/participant/Participants.java
> +    private final List<Player> players;
구현체로 변경하신 이유가 있을까요? (단순 궁금증!)

2023-03-11 10:22 UTC, ksy90101 commented on src/main/java/domain/participant/Participants.java
> +        return player.getBettingAmount() * LOSE_RATE;
player의 결과이기 때문에 여기가 아니라 Player에 있는게 어울리지 않을까요?

2023-03-11 10:23 UTC, ksy90101 commented on src/main/java/domain/participant/Participants.java
> +    private int getPlayerResult(Player player, int dealerScore) {
단순히 여기선 전체 결과를 리턴하는게 좋을거 같네요 :)

2023-03-11 10:23 UTC, ksy90101 commented on src/main/java/domain/participant/Player.java
> +    public static final int UNIT_OF_BETTING_MONEY = 1000;
여기도 public인 이유가 따로 있을까요?

2023-03-11 10:24 UTC, ksy90101 commented on src/main/java/service/BlackjackService.java
> +    }
Delaer의 결과도 participants 해당 메서드에서 처리해야 하지 않을까요?

2023-03-11 10:25 UTC, ksy90101 commented on src/main/java/view/OutputView.java
> +        return card.getRank().getName() + card.getSuit().getName();
디미터의 법칙을 위반한거 같은데요.
Card의 한쌍의 Name을 리턴하는 방식이 어떠세요?

2023-03-11 10:26 UTC, ksy90101 commented on src/main/java/service/BlackjackService.java
>          return new BlackjackService(deck, participants);
Service는 View와 종속적이지 않기 때문에 충분히 테스트를 작성해볼수 있지 않을까요?

2023-03-11 10:27 UTC, ksy90101 commented on src/test/java/domain/participant/ParticipantsTest.java
> +    void 딜러가_버스트이면_스탠드_상태이다() throws Exception {
전체적으로 테스트에서 예외를 던지는건 안맞는거 같아요.
예외또한 테스트에 녹여야 합니다.
(모두다 붙어있는데...ㅎㅎ)

2023-03-11 10:28 UTC, ksy90101 commented on src/test/java/domain/participant/ParticipantsTest.java
> +        assertThat(participants.getPlayersResult().get("연어")).isEqualTo(1000);
containEntry를 사용해보면 어떨까요?

2023-03-11 10:31 UTC, ksy90101 requested changes
안녕하세요 연어 :) 
2단계도 고생 많으셨습니다!!
전체적으로 단위테스트가 조금 부족해 보여요.
예를들어 Hand, Cards, Service 등이요.
좀더 단위테스트를 작성해보면 어떨가 합니다

질문이 있다면 언제든 DM으로 연락주세요~

2023-03-11 10:32 UTC, ksy90101 commented
> 이전 피드백에서 Player 클래스에서 stand 필드를 두어야 하냐고 하셨는데, 이를 두지 않기 위해서 상태 패턴을 사용하면 좋을 것 같습니다.
다만 상태 패턴을 사용한다면 어떤 상태에서는 사용할 수 없는 메서드도 받게 되어 UnsupportedException 등의 예외를 던지도록 구현하는데, 이 또한 별로 맘에 들지 않습니다ㅠㅠ

혹시 `중복 코드를 제거하는 것과 리스코프 치환 법칙 사이에서 trade off가 발생하는데` 이거에 대한 이해가 조금 안되었어요.ㅠㅠㅠ
혹시 대화로 이야기 하고 싶다면 DM으로 이 질문에 대해서 이야기 해보면 좋을거 같습니다 ㅠㅠ

2023-03-12 04:18 UTC, nuyh99 commented on src/main/java/domain/participant/Participant.java
> +    public static final int INITIAL_HAND_SIZE = 2;
이유는 없습니다! 단축키 사용했는데 default가 public인 줄 몰랐어요...수정했습니다

2023-03-12 04:27 UTC, nuyh99 commented on src/main/java/domain/participant/Participant.java
> +        return calculateScore() == BLACKJACK;
기존 코드가 더 가독성이 좋아보여서 그랬습니다!
하지만 인라인으로 간결하게 쓰는 것도 코드가 짧아서 오히려 좋을 수 있겠네요😃

2023-03-12 04:34 UTC, nuyh99 commented on src/main/java/domain/participant/Participants.java
> +    private final List<Player> players;
처음에는 추상에 의존해서 사용하면 좋을 것 같아서 `Participant`에 의존했습니다!
하지만 다형성을 이용해서 하려고 하면 한 쪽에서는 사용하지 않는 메서드도 추상 클래스에 정의해야 했습니다.
이를 방지하기 위해서 구현체에만 메서드를 구현한다면, 사용할 때 다운캐스팅을 통해서 접근해야 하는데 이는 결국 추상에 의존하는 형태가 아니라고 생각이 들어요.

아직까지도 확실히 잘 모르겠습니다...딜러와 플레이어를 같은 류로 봐야할까? 하는 의문에 그냥 구현체로 변경하게 됐습니다.

2023-03-12 04:40 UTC, nuyh99 commented on src/main/java/domain/participant/Participants.java
> +        return player.getBettingAmount() * LOSE_RATE;
저도 동의합니다!

2023-03-12 05:12 UTC, nuyh99 commented on src/main/java/domain/participant/Participants.java
> +    private int getPlayerResult(Player player, int dealerScore) {
뷰에서 출력하기 쉽게 하려고 Player, Dealer 따로 했는데, 생각해보니 전혀 고려할 부분이 아니었던 것 같아요!
수정했습니다.

2023-03-12 05:18 UTC, nuyh99 commented on src/main/java/view/OutputView.java
> +        return card.getRank().getName() + card.getSuit().getName();
어떤 식으로 `String name`을 조합할 지는 Enum Card에서 자신이 어떻게 출력될 지 안다고 생각했습니다.
따라서 `OutputView`에서 만들었는데, 카드의 이름은 뷰에 의존되는 내용이 아니라고 봐도 될 것 같네요...!!
감사합니다

2023-03-12 05:21 UTC, nuyh99 commented on src/test/java/domain/participant/ParticipantsTest.java
> +    void 딜러가_버스트이면_스탠드_상태이다() throws Exception {
헉 감사합니다

2023-03-12 05:24 UTC, nuyh99 commented on src/test/java/domain/participant/ParticipantsTest.java
> +        assertThat(participants.getPlayersResult().get("연어")).isEqualTo(1000);
감사합니다!! 좋은 메서드가 있었네요

2023-03-12 06:06 UTC, nuyh99 commented
럿고 반가워요!! 2단계 피드백도 감사합니다.
이번에도 피드백 최대한 반영해보았습니다.

단위테스트 관련은 저는 충분히 작성했다고 생각했는데 아닌가 보군요ㅠㅠ
우선 제 생각은 아래와 같습니다!

---

**Hand를 예로 들면 Player와 생명 주기가 같고, Player의 VO라고 생각해서 Player 테스트에 모두 녹아 있다고 생각했습니다.**
나머지 부분도 마찬가지구요!

---

테스트를 어느 정도까지 작성해야 하는 지는 `스스로 불안하지 않을 때까지` 라고 생각하고 있습니다! 
그럼에도 불구하고 해당 단위 테스트들을 추가하는 게 좋을 지 궁금해요. 

추가로 서비스 계층의 경우, 대부분 메서드는 단순히 `Participants` 의 메서드를 전달해주는 역할만 하고 있습니다. 이런 부분이나 단순 `getter`, `setter` 등 기본 메서드도 검증이 필요할까요...?

다음 피드백도 미리 감사드립니다😃

2023-03-14 10:26 UTC, ksy90101 approved these changes
안녕하세요 연어 :)
전체적으로 잘 구현해주셨네요!!
Optional에 대해선 글을 하나 남겨봤습니다.
차후에 한번 고민해보셨으면 좋겠어요.

이만 블랙잭은 마무리 하도록 하겠습니다. 그동안 즐거웠어요!!

2023-03-14 10:26 UTC, merged