[2단계 - 블랙잭 베팅] 깃짱(조은기) 미션 제출합니다.
woowacourse/java-blackjack pull request #505
Opened 2023-03-10 05:22 UTC by eunkeeee

2023-03-11 12:44 UTC, KIMSIYOUNG requested changes
안녕하세요 깃짱.
2단계 잘 구현해주셨네요.
몇가지 코멘트 남겼는데 확인 부탁드립니다!

2023-03-11 12:44 UTC, KIMSIYOUNG commented on src/main/java/domain/card/CardDeck.java
> +    public CardDeck(List<Card> cards, CardsShuffler shuffler) {
프로덕션 코드에서 사용하지 않는 생성자를 추가한 이유는 무엇일까요?

테스트하기 용이하기 위함이라면 `CardShuffler`를 통해 랜덤하지 않은 `Deck` 을 이미 만들 수 있는 것 같아서요!

2023-03-11 12:44 UTC, KIMSIYOUNG commented on src/main/java/domain/card/Cards.java
> +    public Cards(final List<Card> cards) {
Cards 는 처음부터 `불변`이 아닌 카드를 관리하는 일급컬렉션인 것 같습니다. 불변으로 관리하고 매번 새로운 리스트를 할당해주는 이유가 있을까요?

2023-03-11 12:44 UTC, KIMSIYOUNG commented on src/main/java/domain/card/Cards.java
>      public Cards() {
블랙잭 게임이 시작되면 항상 모든 플레이어는 2장의 카드를 가지게 됩니다. `READY` 라는 상태를 두어서 가지고 있는 `Cards` 가 불완전한 상태를 만드는 것이 득이 되는게 있을까요?

2023-03-11 12:44 UTC, KIMSIYOUNG commented on src/main/java/domain/card/Cards.java
> +        throw new IllegalArgumentException("처음 받는 카드는 2장이어야 합니다.");
취향차이일 수 있지만, 잘못된 조건에 대해서 `Early return` 을 하는 것이 개인적으로 가독에 도움이 되는 것 같아요.

2023-03-11 12:44 UTC, KIMSIYOUNG commented on src/main/java/domain/game/BlackJackGame.java
>  public final class BlackJackGame {
전체적으로 해당 객체는 도메인을 호출해주는 창구로밖에 동작하지 않는 것 같아요.

`Controller`에서 직접 도메인을 호출해가며 게임을 진행해도 충분하지 않을까요?

2023-03-11 12:44 UTC, KIMSIYOUNG commented on src/main/java/domain/game/Money.java
> +    private final BigDecimal amount;
BigDecimal과 int 로 생성할 수 있지만 곱하는 것은 BigDecimal만 가능하고 반환되는 값은 int 인 것은 사용자가 편리하게 사용할 수 있게 만들어주었다기 보단 혼선을 주는 것 같아요.

2023-03-11 12:44 UTC, KIMSIYOUNG commented on README.md
> +    - [x] 베팅 금액이 0원 이하이면 예외 처리
해당 요구사항은 지켜지고 있지 않은 것 같아요.

2023-03-11 12:44 UTC, KIMSIYOUNG commented on src/main/java/domain/card/Cards.java
>  public class Cards {
잘 구현해주신 것 같아요. `Cards`에서 다른 `Cards`와 비교를 통해 승/무/패를 관리하는 것은 어떨까요?

2023-03-11 12:44 UTC, KIMSIYOUNG commented on src/main/java/domain/participant/Score.java
> +    public Score applyBonusScore() {
Score 객체를 수동적으로 만들었다면 도메인 로직을 최대한 넣지 않는 것이 가독에 도움이 되는 것 같아요. 객체의 역할을 결정할 때 어떤 바운더리로 역할을 끊어낼지도 같이 고민해주시면 좋을 것 같아요.

현재의 Score는 도메인의 룰을 알고 있으면서도 수동적인 것 같아요. 그렇기에 완전히 수동적인 형태로 변경해보면 어떨까요? 

add(Score score) 정도로요!

2023-03-11 12:44 UTC, KIMSIYOUNG commented on src/main/java/domain/game/Bets.java
> +            Money weightedBet = this.bets.get(player)
플레이어 각각이 자신의 배팅금액을 알고 있지 않고 별도의 객체가 해당 역할을 가져간 이유가 있을까요?

2023-03-11 12:44 UTC, KIMSIYOUNG commented on src/main/java/domain/game/Bets.java
> +            Money weightedBet = this.bets.get(player)
플레이어 각각이 베팅금액을 알고 있다면 해당 로직은 모두 사라지고 `WinningResult`에서 충분히 처리할 수 있는 로직이 아닐까 싶어요.

2023-03-11 12:44 UTC, KIMSIYOUNG commented on src/main/java/domain/participant/Score.java
>  public final class Score {
패키지는 어떤 기준으로 분리하시나요?

2023-03-11 12:44 UTC, KIMSIYOUNG commented on src/main/java/view/InputView.java
>      private static final Scanner scanner = new Scanner(System.in);
여기도 마찬가지로 수정해주시면 좋을 것 같습니다.

2023-03-11 12:44 UTC, KIMSIYOUNG commented on src/main/java/domain/status/Status.java
> +public interface Status {
상태패턴은 어떤 이유로 필요했고 어떻게 활용하고 계신가요?

2023-03-11 12:44 UTC, KIMSIYOUNG commented on src/main/java/domain/status/end/Bust.java
> +    public BigDecimal profitWeight() {
WinningStatus 와 역할은 어떻게 다른가요?

2023-03-11 12:44 UTC, KIMSIYOUNG commented on src/main/java/domain/status/end/Bust.java
> +public final class Bust extends EndStatus {
`플레이어가 버스트 되면 딜러가 무조건 이긴다는 규칙`이 반영되지 않은 것 같아요.

2023-03-12 07:16 UTC, eunkeeee commented on src/main/java/domain/card/CardDeck.java
> +    public CardDeck(List<Card> cards, CardsShuffler shuffler) {
@KIMSIYOUNG 

현재 프로덕션 코드로는 초기에 10의 값밖에 안나와서 테스트가 원활하지 못해 추가했습니다.. 
테스트 코드에서 초기 값으로 좀더 다양한 값을 받고 싶었거든요...!

저도 프로덕션 코드에서 사용하지 않는 생성자를 남겨두는 것은 안좋다고 생각해서 어떻게 해야할지 좀 더 고민해봐야 할 것 같아요

2023-03-12 07:17 UTC, eunkeeee commented on src/main/java/domain/card/Cards.java
>  public class Cards {
@KIMSIYOUNG 한번 시도해볼게요...!

2023-03-12 07:26 UTC, eunkeeee commented on src/main/java/domain/card/Cards.java
>      public Cards() {
@KIMSIYOUNG 

게임의 시작 전에 해야 할 일을 저는 `사용자의 이름 정하기`라고 보았습니다.

게임을 시작할 때에는 `READY` 상태에 있고, 초기 카드를 받은 후부터는 계속해서 `HIT`할 수 있는 상태나, `BlackJack` 상태로 넘어가도록 설계한 것도 같은 맥락이라고 이해해 주시면 좋을 것 같아요

상태를 정의해서 다음 행동을 통제할 수 있다면 더이상 불안정하지 않은 것 같습니다! 

만약에 `List<Card>`에 아무 것도 없는 상태에서 점수를 계산하라고 하면 문제가 되겠지만, 현재 상태를 정의하여 initial draw를 받기 전에는 점수 계산을 가능하게 하는 코드가 존재하지 않습니다. 

2장의 카드를 받은 상태가 완전한 상태라면, 만약에 한 장을 더 받는다면 그 메서드를 실행하기 전은 불안정한 상태가 아닐까요..? `BlackJackGame`과 `Controller`를 통해서 상태의 변화에 대해서는 관리가 되기 때문에 불완전하다고 생각하지 않고, 게임의 시작 당시의 상태라고 생각합니다!

2023-03-12 07:29 UTC, eunkeeee commented on src/main/java/domain/card/Cards.java
> +        throw new IllegalArgumentException("처음 받는 카드는 2장이어야 합니다.");
@KIMSIYOUNG 

그렇네요! 얼릉 수정하겠습니다!

2023-03-12 07:36 UTC, eunkeeee commented on src/main/java/domain/game/Bets.java
> +            Money weightedBet = this.bets.get(player)
@KIMSIYOUNG 

일단 이유는... 이미 `Player`에 필드가 2개로 추가하게 되면 요구사항에 맞지 않기 때문입니다....

플레이어가 각각 자신의 베팅금액을 안다면 좋겠지만, 생각해보면 현재 `Player`는 이름, 상태를 이미 가지기 때문에 저는 충분히 많은 역할을 하고 있는 것 같다고 생각했어요.

깃허브로 생각해보면 유저가 commit, push, pull request 등등 많은 역할을 하는데 이것을 모두 `User`에서 관리하지는 않을 테니깐 비슷하게 꼭 모든 정보를 `Player`에 넣기보다는 베팅 금액과 관련된 부분은 `Bets`로 별도로 관리한다고 생각해 주시면 좋을 것 같아요!

2023-03-12 07:40 UTC, eunkeeee commented on src/main/java/domain/game/BlackJackGame.java
>  public final class BlackJackGame {
@KIMSIYOUNG 

저는 현재 게임에서는 게임의 구체적인 로직을 `Game`에 모두 옮기기에는, `view`를 호출해야 하는 일이 잦아서 어쩔 수 없이 `Game` 객체가 하는 일이 줄어 버렸지만, 의미적으로 `Game` 객체는 필요할 것 같다고 생각해요 ! 

이번 미션에서 `Game`을 없애면 `Controller`에서의 메서드 분리를 어떻게 해야 할 지 모르겠다는 말에, 고민해 보고 답이 없으면 답변 주시겠다고 1단계에서 하셨는데, 이걸 없애면 컨트롤러에서 필드를 주지 않으면서 어떻게 관리해야 할지 아직도 잘 모르겠습니다. 이 부분 혹시 지금 답변 주실 수 있으띾요????

2023-03-12 07:41 UTC, eunkeeee commented on src/main/java/domain/game/Money.java
> +    private final BigDecimal amount;
@KIMSIYOUNG 

좀더 유연하게 생성할 수 있도록 하기 위해서 두 가지 생성자를 제공했는데, 
그럼 카일은 `multiply`에 대해서도 `int`를 파라미터로 받는 것을 오버로딩하는 것이 좋다고 생각하시나요?

2023-03-12 07:45 UTC, eunkeeee commented on src/main/java/domain/participant/Score.java
> +    public Score applyBonusScore() {
@KIMSIYOUNG 

넵 이 객체가 왜인지 좀 어색하게 느껴졌는데, 카일 말대로 능동적이지도 않으면서 애매하게 수동적이기 때문인 것 같아요. 완전 수동적인 값 객체로 수정하겠습니다 감사합니당!

2023-03-12 07:53 UTC, eunkeeee commented on src/main/java/domain/status/Status.java
> +public interface Status {
@KIMSIYOUNG 

제가 2단계를 너무 늦게 시작해서 피드백 강의부터 들어버렸는데, 네오 코치가 상태패턴을 통해 구현하는 것을 보고, 신기한 방법이라고 생각했고, 강의 때 마무리해주시지는 못해서 제가 한 번 마무리하고 싶어서 활용해보니, 장단점이 있는 것 같아요

제가 느낀 장점은
- if문에 크게 의존하지 않아도 된다
- 다음 상태가 무엇인지 반환해 주므로 게임에 대한 이해가 코드를 통해 좀더 명확하게 되는 것 같다
- 다음 상태로 가능한 후보가 많아지거나, 다음 상태로의 이동에 대한 조건이 세세해 질 수록 더 좋은 방법이 될 것 같다
- 개발자는 현 상태에서 할 수 있는 것과 없는 것을 명확하게 해서 잘못된 코드를 작성하거나, 호출해서 안되는 것이 호출되는 경우 예외가 발생하므로 빠르게 알아챌 수 있다

제가 느낀 단점은
- 특정 상태에서 사용되지 않는 메서드라도 다른 상태에서 사용된다면 그걸 모두 합집합한 인터페이스를 만들어야 하는데, 사용되지 않는 메서드를 일일이 예외 처리 해야하는 비용이 발생한다
- 사용자 입장에서는 사용할 수 없는 코드인 줄 모르고 실행했다가 예외가 발생해서 당황할 수 있다.

이번 미션에서 제가 느낀 바로는 장점이 좀 더 많을 것 같습니다 (물론 상태패턴을 안 사용해서 구현한 적이 아직 없어서 확신은 없습니다ㅠ) !

2023-03-12 07:58 UTC, eunkeeee commented on src/main/java/domain/status/end/Bust.java
> +    public BigDecimal profitWeight() {
@KIMSIYOUNG 

`WinningStatus`에서는 단지 이겼는지 졌는지만 알 수 있고 `BlackJack`인지는 알 수가 없습니다. `BlackJack`인 경우에 1.5배로 돈을 벌 수 있다는 부분을 이곳에서 처리하고, 나머지의 경우에는 가중치를 두지 않으며 승패여부에 대해서는 여기에서 알 수 없습니다

2023-03-13 10:51 UTC, KIMSIYOUNG commented on src/main/java/domain/game/Money.java
> +    private final BigDecimal amount;
네네 생성과 사용, 반환이 각각 다른 형태를 지원하기에 편의성보단 혼란을 더 주는 것 같아요.

2023-03-13 11:23 UTC, KIMSIYOUNG requested changes
안녕하세요 깃짱!
전체적으로 코드가 깔끔하게 잘 구현해주신 것 같습니다.
몇가지 코멘트 남겼는데 확인 부탁드립니다!
남긴 부분만 이야기해보고 머지하면 좋을 것 같습니다.

2023-03-13 11:23 UTC, KIMSIYOUNG commented on src/main/java/domain/card/Cards.java
>      public Cards() {
`완전한` 이라는 표현이 상대적이라 의도가 제대로 전달되지 않은 것 같아요. 깃짱이 이해한 완전한은 `더이상 수정이 필요하지 않은` 상태를 의미하는 것 같아요.

제가 말한 완전한은 `지역적인 의미에서 완전한`을 의미했습니다. 생성시점의 완전함, 한장을 더 뽑았을 때 각각의 완점함을 의미했어요.

2023-03-13 11:23 UTC, KIMSIYOUNG commented on src/main/java/domain/card/Cards.java
> +    public WinningStatus compete(final Cards dealerCards) {
Cards 입장에선 딜러와 비교한다는 로직은 알지 않아도 될 것 같아요.

2023-03-13 11:23 UTC, KIMSIYOUNG commented on src/main/java/domain/game/Bets.java
> +            Money weightedBet = this.bets.get(player)
넵넵 좋은 관점인 것 같습니다🙂

2023-03-13 11:23 UTC, KIMSIYOUNG commented on src/main/java/domain/result/WinningStatus.java
> +    WIN(1),
1, -1, 0 이라는 값이 상태와 중복되어 관리되고 있는 것 같아요.

EndStatus 에서 `Draw` 를 관리하지 않는 이유는 무엇일까요?

2023-03-13 11:23 UTC, KIMSIYOUNG commented on src/main/java/domain/participant/Player.java
> +        if (dealer.isBust()) {
딜러와 플레이어가 모두 Bust 인 경우 플레이어가 패배하는게 룰인 것 같아요!

2023-03-13 11:23 UTC, KIMSIYOUNG commented on src/main/java/domain/status/end/Bust.java
> +    public BigDecimal profitWeight() {
둘의 역할이 모호하게 경계에 걸쳐있는 것 같아요. 

왜 두가지가 분리되었는 것일까요?

2023-03-13 11:23 UTC, KIMSIYOUNG commented on src/main/java/domain/status/end/EndStatus.java
> +        throw new IllegalStateException("초기 상태에서만 가능합니다.");
지원하지 않는 상태일 때는 `UnsupportedOperationException` 도 주로 사용됩니다🙂

2023-03-13 11:23 UTC, KIMSIYOUNG commented on src/main/java/domain/status/Status.java
> +public interface Status {
시간이 된다면 상태패턴 없이 구현하시는 것도 해보시고 비교해보면 좋을 것 같아요🙂

개인적으로 상태패턴은 생각보다 `코드를 보고 흐름도를 파악`하는데 어려움이 있는 패턴인 것 같아요🙂
말씀하신대로 여러 상태에 대해서 분리하여 상태별로 가능한 것들을 정의하기에 더 가독이 용이해지는 부분도 있지만요!

잘 적용해주셨으니 적용되지 않은 버전과 비교해보시는 시간도 가지면 좋을 것 같아요.

2023-03-13 11:23 UTC, KIMSIYOUNG commented on src/main/java/domain/game/BlackJackGame.java
>  public final class BlackJackGame {
네네 필드로 관리하지 않고 컨트롤러의 하나의 메소드에서 처리하는 것을 기대했습니다. 

`run`이라는 메소드하나에서 이름을 입력 받고, 2장의 카드를 분배하고 하는 것들을 `private`으로 분리해가며 하나의 메소드로 모두 마무리할 수 있을 것 같았어요.

그렇기에 `필드`를 줄 필요는 없을 것 같았구요. 또한 `Controller`이기에 뷰에 의존하는 것은 당연한 것 같구요! (게임에 모두 넣어달라는 의도가 아니라 `Controller`의 하나의 메소드에서 모든 것을 진행해도 충분할 것 같다는 의도였어요)

2023-03-14 01:40 UTC, eunkeeee reviewed
리뷰에 대해 답변 남겼습니다!_!_!

2023-03-14 01:40 UTC, eunkeeee commented on src/main/java/domain/participant/Score.java
>  public final class Score {
@KIMSIYOUNG 

1단계에서 했던 분류랑 2단계가 섞여서 좀 혼란스러웠던 것 같아요 변경했습니다!

2023-03-14 01:40 UTC, eunkeeee commented on src/main/java/domain/status/end/Bust.java
> +    public BigDecimal profitWeight() {
@KIMSIYOUNG 

상태 패턴을 통해서는 게임 점수로만 알 수 있는 정보까지만 알 수 있고 상대방과 비교한 결과는 알 수 없어서 합치기가 어려웠던 것 같아요ㅜㅜ

2023-03-15 00:00 UTC, KIMSIYOUNG commented on src/main/java/domain/money/Money.java
> +        if (amount <= 0) {
네네! 역할을 최대한 끊어내려고 고민해보시는게 좋을 것 같아요. 말씀하신대로 음수 검증할 땐 이 생성자 / 아닐 땐 어떤 값이든 될 수 있음 이라는 것 자체가 해당 객체가 2가지 기능을 할 수 있게 하면서 역할을 모호하게 만드는 것 같아요. 배팅금액을 다루기 위한 클래스로 간주할건지 / 단순히 돈을 포장한 값객체로만 바라볼 것인지가 끊어져 있을 때 가독이 용이할 것 같아요. 

`순수한 값객체로 바라본다면 검증에 관한 부분을 Bets의 addBet()로 옮기면 되는 걸까요?`

2023-03-15 00:02 UTC, KIMSIYOUNG commented on src/main/java/domain/participant/Player.java
> +        if (dealer.isBust()) {
오 네네! 저는 블랙잭 룰을 찾아보고 말씀드렸었어요. 위 요구사항은 약간 모호하긴 하네요🙄 (둘다 버스트인 경우 딜러가 이기는 것으로 판정이 되어 판수가 누적되면 딜러한테 유리할 수 밖에 없다라고 알고 있었어요ㅎㅎ)

2023-03-15 00:04 UTC, KIMSIYOUNG commented on src/main/java/domain/result/WinningStatus.java
> +    WIN(1),
넵넵! 그렇다면 결국 `딜러와의 비교` 를 통해서 결과를 알아낼 수 있는 것 같아요. 
그런 의미에서 블랙잭이나 승 / 패 / 비김 등에 대해서는 `WinningStatus`에서 관리하는 건 어떨까요?
`일부상황에서` 확인 할 수 있다고 해서 해당 역할을 `BlackJackStatus` 로 주게 되면 역할의 경계가 모호해지는 것 같아요.

2023-03-15 00:06 UTC, KIMSIYOUNG commented on src/main/java/domain/status/end/BlackJack.java
> +    public BlackJack(final Cards cards) {
`package-private` 을 사용하는 방법도 있을 것 같아요. 

아무나 호출할 수 없게 하고 싶다는게 어떤 의미실까요?

2023-03-15 00:08 UTC, KIMSIYOUNG commented on src/main/java/domain/card/Cards.java
>      public Cards() {
넹 알겠습니당ㅎㅎ

2023-03-15 00:09 UTC, KIMSIYOUNG commented on src/main/java/domain/game/BlackJackGame.java
>  public final class BlackJackGame {
넵넵 `Game` 이라는 것을 이미 만들고 시작해서 `Game`에 무언가 역할을 부여하고 싶으신 것 같아요. `Game` 이라는게 있을 필요에 대한 고민도 다음 미션에선 같이 해보시면 좋을 것 같습니다.

2023-03-15 00:11 UTC, KIMSIYOUNG approved these changes
안녕하세요 깃짱!
리뷰 잘 반영해주셨네요.
깃짱이 고민하신 부분도 잘 설명해주셔서 이해하는데 도움이 되었습니다.
다음 미션도 화이팅하세요!
궁금하신 내용이나 이야기 나누고 싶은 것이 남아있다면 디엠 부탁드리겠습니다!

2023-03-15 00:11 UTC, merged

2023-03-15 00:59 UTC, eunkeeee commented on src/main/java/domain/result/WinningStatus.java
> +    WIN(1),
@KIMSIYOUNG 

적어놓고 마지막주에 한번 리팩터링 해볼게요...! 감사합니당

2023-03-15 00:59 UTC, eunkeeee commented on src/main/java/domain/status/end/BlackJack.java
> +    public BlackJack(final Cards cards) {
@KIMSIYOUNG 

블랙잭 게임의 결과는 도메인에서 제일 중요한 로직 중 하나인데, 누군가가 코드에서 `new BlackJack()`을 호출해, `READY` 상태부터 오지 않고 곧바로 이 상태를 만들 수 있다는 뜻이었슴니다!