[2단계 - 블랙잭 베팅] 하디(전동혁) 미션 제출합니다.
woowacourse/java-blackjack pull request #507
Opened 2023-03-10 05:54 UTC by jundonghyuk

안녕하세요 리뷰이 하디입니다.

리뷰어님이 남겨주신 코멘트와 디엠내용 잘봤습니다!

2단계에서 주요 변경점은 

1. 컨트롤러의 분리
- 게임진행이 총 3부분으로 나눠진다고 생각했습니다. 플레어어에 대한 정보를 입력받고 초기화하는 단계
-  더 뽑을 건지에 대한 입력을 받는 게임 진행 단계
-  게임 결과를 출력해주는 결과 단계
이렇게 3가지로 분리하여 구현하였습니다. 또한 저번에는 컨트롤러에서 블랙잭게임이라는 서비스격인 도메인만 접근을 하였는데, 블랙잭게임을 없애고 다른 도메인들에 접근하였습니다. 컨트롤러는 도메인을 알아도되니 이렇게 접근하였습니다.

2. 아웃풋뷰에서의 도메인을 인지
- 처음엔 Outputview에 최대한 프리미티브 타입과, 컬렉션을 위주로 넘겨주었는데 생각해보니 뷰가 도메인을 알고있어도 된다고 생각합니다. 도메인의 결과가 곧 뷰로 찍어야하는 정보니 알아도 된다고 생각합니다. 
반대로 도메인은 뷰를 알면 안된다고 생각합니다. 중요 프로덕션 로직이 영향을 받기 때문입니다.
중요도가 도메인이 훨씬 높기 때문입니다.

3. 상속구조의 변화
처음에는 Player를 설계하고 이를 Dealer가 상속받도록 하였습니다.
그런데 플레이어의 기능 중에 딜러가 사용하지 않는 기능도 있기에 이 메서드를 딜러가 호출할때마다 `UnsupportedOperationException`이나 `IllegalStateException`을 던지기엔 무리가 있어, Participant 추상클래스를 설계했습니다. 그래서 Player와 Dealer가 둘 다 써야되는 로직만 선언하고, 각자 필요한 로직은 따로 선언했습니다.
리뷰어님이 보내주신 조합패턴도 읽어봤는데 이번에 상속구조를 재정의하면서 상속구조가 확실하다고 생각해 상속을 선택하였습니다.
혹시 문제점이있다면 알려주시면 감사하겠습니다:)

4. 게임결과만드는 도메인 구현
GameResult라고 플레이와 딜러들의 정보를 받아서 맵으로 결과를 반환해주는 도메인을 설계했습니다.
처음엔 이게 뷰를위한 도메인이 아닐까라고 생각을했지만, 블랙잭게임을 함에 있어, 결과를 어떤식으로든 만들어주는 것이 필요하다 생각해 이런 도메인을 설계했습니다. 

항상 좋은 리뷰해주셔서 감사합니다:) 해주신 질문 덕분에 찾아보면서 많이 배웠습니다 !
오늘도 좋은 하루 되세요.

2023-03-13 00:49 UTC, jnsorn requested changes
안녕하세요 하디! 리뷰가 많이 늦어졌네요 😭
2단계도 잘 구현해주셨어요. 👏
간단한 코멘트 몇 개 남겼으니 확인해보시고, 다시 요청주세요 :)

2023-03-13 00:49 UTC, jnsorn commented on src/test/java/domain/bet/BetTest.java
> +    }
예외메세지를 통한 정확한 비교 💯
다만 메세지 비교가 의도한대로 되고 있지 않은 것 같아요.  
아래와 같이 예외메세지를 바꾸면 테스트는 통과할까요? 실패할까요?

```suggestion
    @DisplayName("최초의 배팅금액이 0이하이면 예외를 던진다.")
    @ParameterizedTest
    @ValueSource(ints = {-100, 0, -1})
    void constructBetTest(final int money) {
        assertThrows(IllegalArgumentException.class,
                () -> new Bet(money))
                .getMessage().equals("[ERROR]: 배팅금액은 0원 미만이어야 합니다.");
    }
```

2023-03-13 00:49 UTC, jnsorn commented on src/main/java/domain/bet/Bet.java
> +    }
매직넘버를 제거해볼까요?

2023-03-13 00:49 UTC, jnsorn commented on src/test/java/domain/bet/BetTest.java
> +    }
```suggestion
    void calculateBetByOutcomeWinWithBlackJackTest() {
        int bettingMoney = 1000;
        Bet bet = new Bet(bettingMoney);
        double expectedMoney = bettingMoney * 1.5;

        bet.calculateBetByOutcome(Outcome.WIN, true);
        
        assertEquals(expectedMoney, bet.getMoney());
    }
```

expectedMoney를 직접 작성하기 보다는 게임 규칙을 활용해서 선언할수 있을 것 같아요.

2023-03-13 00:49 UTC, jnsorn commented on src/main/java/domain/result/GameResult.java
> +public final class GameResult {
GameResult 객체가 단순히 결과를 계산하는 메서드만 제공하고 있는데요, `Map<Participant, Outcome>`의 일급컬렉션 형태로 만들어보면 어떨까요?

2023-03-13 00:49 UTC, jnsorn commented on src/main/java/controller/MainController.java
> +        players.hitTwice(deck);
> * 처음엔 다른 도메인 접근없이 서비스 도메인만 받아 그를 통해 흐름을 제어한다고 생각했는데, 생각이 바뀌었습니다..
> * 게임 결과를 출력해주는 결과 단계 이렇게 3가지로 분리하여 구현하였습니다. 또한 저번에는 컨트롤러에서 블랙잭게임이라는 서비스격인 도메인만 접근을 하였는데, 블랙잭게임을 없애고 다른 도메인들에 접근하였습니다. 컨트롤러는 도메인을 알아도되니 이렇게 접근하였습니다.

컨트롤러의 역할에 대해 많은 고민을 해주신 것 같아요! 알고계신것처럼 컨트롤러는 데이터를 사용자에게 보여주기 위해 도메인과 뷰 사이의 다리 역할을 하는데요, 지금 컨트롤러를 보면 단순히 뷰와 도메인의 연결보다는 더 큰 책임을 가지고 있는 것 같아요. 만약 게임이 인기가 많아져 다른 환경에서도 게임을 제공해야한다면 도메인 패키지에 있는 코드만으로 게임 진행이 가능할까요? 최대한 컨트롤러에서 도메인 로직을 제거할 수는 없을까요?

2023-03-13 00:49 UTC, jnsorn commented on src/test/java/domain/result/GameResultTest.java
> +        assertEquals(10000, ddoringMoney);
오예

2023-03-13 00:49 UTC, jnsorn commented on src/test/java/domain/result/GameResultTest.java
> +class GameResultTest {
테스트 짜느라 고생 많으셨겠네요 🤣
GameResult의 테스트는 DisplayName이 없는데 의도하신걸까요?

2023-03-13 03:06 UTC, jundonghyuk commented on src/test/java/domain/bet/BetTest.java
> +    }
당연히 된다고 생각했는데 수정하겠습니다..!!
원리를 알아보겠습니다

2023-03-13 03:11 UTC, jundonghyuk commented on src/main/java/domain/bet/Bet.java
> +    }
놓치고 있었네요 감사합니다 ㅎㅎ

2023-03-13 03:16 UTC, jundonghyuk commented on src/test/java/domain/bet/BetTest.java
> +    }
감사합니다 ㅎㅎ

2023-03-13 03:32 UTC, jundonghyuk commented on src/test/java/domain/result/GameResultTest.java
> +class GameResultTest {
아닙니다..!! 신경을 못썼네요 채워넣겠습니다 !

2023-03-13 05:44 UTC, jundonghyuk commented on src/main/java/domain/result/GameResult.java
> +public final class GameResult {
넵 해보겠습니다 !

2023-03-13 05:47 UTC, jundonghyuk commented on src/main/java/controller/MainController.java
> +        players.hitTwice(deck);
이런 상대적으로 간단한 프로그램에서 블랙잭게임이라는 서비스레이어를 만들면, 컨트롤러에서 도메인의 메서드를 호출해서 하는 일을 서비스 레이어를 통해서 단순 호출하여 레이어만 늘어나는 단점만 있는 것 같은데.. 어떻게 생각하시는지 궁금합니다.

2023-03-13 05:52 UTC, jundonghyuk commented on src/main/java/controller/MainController.java
> +        players.hitTwice(deck);
정리하자면, 블랙잭게임(서비스?)이라는 곳에서 의미있는 행동을 하는게 아직 도메인의 단순 호출만 진행하여 불필요한 레이어만 생기는 것 같다고 생각합니다.

2023-03-15 00:00 UTC, jnsorn approved these changes
안녕하세요, 하디! 피드백 잘 적용해주셨어요. 👍
처음에 비해 코드가 많이 깔끔해진것 같아요.
코멘트 몇개 남겨두었는데 확인해보시고 궁금한 부분은 DM주세요!
다음 미션을 위해 블랙잭 미션은 여기서 마무리하도록 할게요.
체스 화이팅! ♟️

2023-03-15 00:00 UTC, jnsorn commented on src/main/java/controller/ProgressController.java
> +        while (!player.isEqualOrLargerThanBlackJackNumber() && isHitAgain) {
isEqualOrLargerThanBlackJackNumber 와 같이 구체적인 로직을 이름으로 나타내기 보다는 카드를 뽑을 수 있다 정도의 이름으로 추상화시켜보면 어떨까요? 지금 상태는 게임 규칙이 변경되면 메서드 이름도 같이 변경되어, 해당 메서드를 사용하는 모든 곳에서 변경이 일어날 것 같아요.  

dealer.shouldHit()와 추상화 수준을 맞춰보면 좋겠네요!

2023-03-15 00:00 UTC, jnsorn commented on src/test/java/domain/bet/BetTest.java
> +
이제 정말 메세지까지 비교하여 더 정확한 테스트가 됐네요 👍

2023-03-15 00:00 UTC, jnsorn commented on src/main/java/domain/deck/Card.java
> +    public static Card of(final Suit suit, final Rank rank) {
카드들을 List가 아닌 Map에 저장해도 좋겠네요.

2023-03-15 00:00 UTC, jnsorn commented on src/main/java/domain/bet/Bet.java
> +
승패에 따른 수익률은 어떤 객체가 알고있어야할지 고민해봐도 재밌겠네요. 🤔
저는 승, 무, 패에 대한 책임을 담당하는 Outcome에서 가지고 있는 것도 괜찮을 것 같다는 생각인데요, 하디는 어떠신가요?
지금 Outcome이 변경되었을때 Bet도 무조건적인 변경이 일어날 것 같아요.

2023-03-15 00:00 UTC, jnsorn commented on src/main/java/domain/player/Players.java
> +        });
딜러와 동일한 행동을 하는 부분이네요!

2023-03-15 00:00 UTC, jnsorn commented on src/main/java/domain/player/Player.java
> +            throw new UnsupportedOperationException();
예외메세지를 입력해볼까요?

2023-03-15 00:00 UTC, jnsorn commented on src/main/java/domain/result/GameResult.java
> +    }
GameResult에서 플레이어들을 돌면서 작업하는 로직이 반복되고 있어요. 
Players 일급컬렉션을 이용하도록 변경해보면 어떨까요?

2023-03-15 00:00 UTC, merged