[2단계 - 블랙잭 베팅] 포이(김보준) 미션 제출합니다.
woowacourse/java-blackjack pull request #511
Opened 2023-03-10 08:29 UTC by bjk1649

시카 안녕하세요! 2단계 구현 완료했습니다!

최대한 1단계 마지막에 주신 피드백을 적용하려고 노력했는데 잘 했는지 모르겠네요.😭

잘부탁드립니다!

2023-03-12 07:31 UTC, dks301 requested changes
안녕하세요 포이, 리뷰어 시카입니다. 😄

2단계도 요구사항에 맞춰 잘 구현해주셨네요! 피드백을 적용에 많이 노력하신게 보이네요 👍👍
추가로 몇 가지 코멘트 남겨드렸으니 확인부탁드려요.

궁금한 점이 생기면 언제든지 DM 주세요 ㅎㅎ

2023-03-12 07:31 UTC, dks301 commented on src/main/java/domain/card/Number.java
> +package domain.card;
수정 라인이 아닌 곳의 코멘트는 좋지는 않지만, 1단계 코멘트와 연결되어 있어서요!

`public String value()`는 비즈니스 로직이라고 할 수 있지 않을까요??
테스트를 추가해보면 어떨까요 ㅎㅎ

2023-03-12 07:31 UTC, dks301 commented on src/test/java/domain/BlackjackGameTest.java
> +import static org.junit.jupiter.api.Assertions.assertAll;
<img width="472" alt="image" src="https://user-images.githubusercontent.com/32732560/224530604-46dfd88e-8f13-41d3-af63-6e115a8b2a6d.png">

블랙잭 게임 테스트가 많이 빠진 것 같아요!

전반적으로 테스트 with 커버리지 로 확인보면서 빠뜨린 테스트들을 추가해보면 어떨까요? ㅎㅎ

<img width="789" alt="image" src="https://user-images.githubusercontent.com/32732560/224530678-7546a8ce-fc7b-489d-87f9-5cf4f8966ac1.png">

2023-03-12 08:00 UTC, bjk1649 commented on src/main/java/domain/BlackjackGame.java
> +    private static int calculateDealerRevenue(Map<String, Integer> playersRevenues) {
cmd opt m 으로 메서드 분리기능을 이용하고 수정하는 것을 깜빡했네요.😢 static 키워드 제거했습니다!

2023-03-12 08:05 UTC, bjk1649 commented on src/main/java/controller/ParticipantDto.java
> +    public ParticipantDto(String name, List<String> cards) {
정적 팩터리 메소드를 만들 때 꼼꼼하게 확인하지 못했네요.. private으로 수정했습니다

2023-03-12 08:12 UTC, bjk1649 commented on src/main/java/controller/ParticipantDto.java
> +                .collect(Collectors.toUnmodifiableList());
한 줄에 `.`이 두 개 있는게 보기 싫어 줄을 바꿔보았는데, 말씀대로 한 가지 방식으로 통일 시키는 편이 더 좋을 것 같네요.
원래 사용하던 stream() 후 줄바꿈으로 통일했습니다!

2023-03-12 08:25 UTC, bjk1649 commented on src/main/java/domain/card/Card.java
> +    public Number number() {
모든 getter를 필드 이름으로만 표현한다면 굳이 get을 붙이지 않아도 **명사로 되어있는 메서드는 getter구나** 하고 자연스레 명확성도 가져갈 수 있다고 생각했습니다. 

다만 제 코드에서는 [위 피드백](https://github.com/woowacourse/java-blackjack/pull/511#discussion_r1133196406) 처럼 오히려 getter가 아닌 곳에 get이라는 이름을 붙이게 되어 더더욱 명확하지 못한 코드가 되어 버린 것 같습니다.
그래서 이번엔 get이 붙은 메서드의 이름을 전반적으로 수정해보았습니다.

2023-03-12 09:30 UTC, bjk1649 commented on src/main/java/domain/card/Number.java
> +package domain.card;
피드백을 보고 테스트를 작성하다가, 문득 이를 사용하는 곳이 어딜지 생각해보았습니다.
현재 이 메서드는 카드별로 view에서 출력되는 문자열을 결정해줍니다.

현재 상태에서 만약 `ACE`라는 카드의 요구사항이 변경되어 A 가 아니라 ACE 라고 출력되어야한다면,이는 명확한 view에 대한 요구사항 변화임에도 도메인 코드를 수정해주어야 합니다.

이는 명확하게 수정이 필요한 부분이라는 생각이 들었습니다.

그래서 dto로 변환하는 과정에서 도메인 객체를 직접 받아 출력 요구사항에 맞게 변환해주도록 코드를 수정해야겠다! 라고 생각했는데 이미 dto 안에 해당 코드가 있었네요.. 결국 value 는 아무데서도 사용되지 않고 있는 코드였습니다. 
그런데 ide에서 경고 메시지가 표시되지 않네요.🤔 혹시 왜 경고 메시지가 표시되지 않는지 시카는 알고 계신가요?

---
결론적으로 이 메서드는 삭제했습니다.

2023-03-13 08:45 UTC, bjk1649 commented on src/main/java/domain/BlackjackGame.java
> +    public Map<String, Integer> getRevenues() {
동의합니다.. getter의 원래 의미에서 벗어나서 쓴 탓에 오해를 불러 일으키는 코드가 되었네요😞

2023-03-13 08:48 UTC, bjk1649 commented on src/main/java/domain/BlackjackGame.java
> +                .sum() * -1;
-1 을 수정하기보단 player의 전체 수익의 역수를 취해준다 라는 의미를 전달하고싶어 .sum() 까지를 메서드로 추출해보았습니다. 혹시 이 방법도 괜찮을까요?🤔

2023-03-13 10:53 UTC, bjk1649 commented on src/test/java/domain/BlackjackGameTest.java
> +import static org.junit.jupiter.api.Assertions.assertAll;
<img width="915" alt="image" src="https://user-images.githubusercontent.com/74969077/224680242-325b80cd-7996-4d3a-aa59-bb1ac26eafd8.png">
처음 설계할 때, 컨트롤러에 가까운 역할이라고 생각해서 그런지 핵심 로직인데도 테스트가 없는 메서드가 있었네요...😥 테스트를 추가했습니다.

다만 사진처럼 단순히 상위 계층에 호출을 위임한 메서드의 경우 테스트를 작성 할 필요가 없다고 생각해 그대로 놔두었습니다.
혹시 이런 케이스의 경우도 테스트가 필요할까요?

2023-03-14 09:40 UTC, dks301 approved these changes
안녕하세요 포이, 리뷰어 시카입니다. 😄

이번 미션에서는 깊이 고민해볼 만한 내용을 중점적으로 코멘트 드렸는데요...!
많은 고민을 하면서 충분히 성장하신 것 같아요 💯👏
이번 미션은 이만 머지하겠습니다. 수고하셨습니다!

추가로 궁금한 점이 생기면 언제든지 DM 주세요 ㅎㅎ

2023-03-14 09:40 UTC, dks301 commented on src/main/java/domain/card/Card.java
> +    public Number number() {
페어와 합의하에 get을 제거하는 방식으로 통일하셨군요...! 😄
제너럴 컨벤션도 중요하지만 같이 개발하는 사람들의 동의가 제일 중요한 것 같아요 ㅎㅎ

추가로 컨벤션을 정할 때, getter에서 get 제거와 같이 일반적이지 않은 것들은 당장은 모두가 동의했지만, **_"미래에 개발에 합류할 동료들이 헷갈릴 수 있는 여지가 생긴다"_** 라는 점만 의식하면서 진행하면 더 좋을 것 같습니다 ㅎㅎ

2023-03-14 09:40 UTC, dks301 commented on src/main/java/domain/card/Number.java
> +package domain.card;
오.. 이 부분은 저도 처음 알았네요 ㅎㅎ

![image](https://user-images.githubusercontent.com/32732560/224955563-7c84dbd4-a5c0-4dd2-afb1-384f7c53a34e.png)

다른 라이브러리에서 사용하는 메서드와 겹쳐 인식(?)을 못하는 버그 아닐까요...?😅
실제로 어디든 `T value()` 로 메서드를 만들면 no usage가 안떠서요 ㅎㅎ 
저는 앞으로 value 네이밍 메서드는 지양하겠습니다

2023-03-14 09:40 UTC, dks301 commented on src/test/java/domain/BlackjackGameTest.java
> +import static org.junit.jupiter.api.Assertions.assertAll;
질문주신 부분에 대한 정답은 없는 것 같아요...!! ㅎㅎ
다만, 미션에서 TDD를 진행 중이기에 테스트 추가를 코멘트 드렸습니다.

테스트를 모두 추가하려고 노력하는 과정에서 포이가 생각하는 적정선이 생겼다면 의도한 부분은 모두 적용하셨다고 생각해요 💯

본인만의 적정선을 가지고 다음 미션이든, 그 이후든 계속해서 발전해 나가면 될 것 같습니다! 😄

2023-03-14 09:40 UTC, merged