[2단계 - 블랙잭(베팅)] 라온(문채원) 미션 제출합니다.
woowacourse/java-blackjack pull request #524
Opened 2023-03-11 03:17 UTC by mcodnjs

2023-03-11 05:12 UTC, mcodnjs commented on src/main/java/blackjack/domain/BlackJackGame.java
>          this.players = new Players(inputNames);
현재 로직은 inputNames를 String으로 받아서 Name 생성 후 Player를 생성하고 최종적으로 Players를 생성하는 형태로 구성되어 있습니다. **원래 생각하였던 구조는 Pariticpant에 Bet이라는 필드를 추가하려 했지만**, 
- 위와 같은 구조로 인해 Player, Players, BlackJackGame의 생성자가 모두 변경되는 상황이었고, 
- 받은 inputNames로 Name을 먼저 생성한 후, 유효한 이름인지 판단하고 베팅 금액을 받아야했습니다.

```
게임에 참여할 사람의 이름을 입력하세요.(쉼표 기준으로 분리)
pobi,jason

pobi의 배팅 금액은?
10000

jason의 배팅 금액은?
20000
```

위와 같은 로직을 따른다면, Controller에서 입력받은 String으로 모든 Name을 생성하고, 베팅 금액을 받은 후 Player를 생성하고, 생성한 Player를 리스트 형태로 만든 후 BlackJackGame에 Players를 주입해줘야 하는데, 이렇게 컨트롤러에서 모든 도메인을 생성해서 Players에 주입해주는 것이 맞는건지? 그렇다면, 현재 구조가 좋지 않은 구조라 하나의 필드 추가에도 다양한 클래스에 의존하여 생성되는 구조가 된건지? 잘 모르겠습니다 😭

 **언제 어디서 객체를 생성(및 유효성 처리)하고 다른 클래스에 넘겨줘야하는지** 궁금합니다 .. !

2023-03-11 05:13 UTC, mcodnjs commented on src/main/java/blackjack/domain/card/CardsFactory.java
> +public class CardsFactory {
> 기존 Deck과 ShufflingMachine의 문제점 ([1단계 PR 참고](https://github.com/woowacourse/java-blackjack/pull/469/files#r1128770380))
1. 현재 Deck클래스가 맨 앞장의 카드를 뽑기 위해 추가적인 count 필드를 가진다.
2. ShufflingMachine의 역할이 셔플과 뽑는 것을 모두 담당하고 있다

기존의 문제점을 다음과 같이 인지하였고, 해결 방법은 아래와 같습니다!
1. **`Queue<Card>` 형태로 생성하여 앞 장의 카드를 뽑는다.**
2. **클래스 네이밍 변경**
  2-1. 기존의 52장의 카드들을 저장하였던 `Deck` 클래스를 -> `CardsFactory`로 클래스 이름 변경
  2-2. 셔플과 카드를 뽑는 역할을 하였던 `ShufflingMachine` 클래스를 -> `Deck`으로 클래스 이름 변경
  2-3. 위와 같이 변경한 이유는, 블랙잭에서 Deck이 매 판마다 셔플되어 카드들을 의미하므로, 셔플 후 Deck에서 카드를 뽑는 형태가 더 명확할 것 같아 변경하였습니다!

2023-03-11 05:13 UTC, mcodnjs commented on src/main/java/blackjack/domain/participant/Participant.java
> +    }
기존에 요청 주셨던 Ace 계산 시점을 다시 생각해보고 블랙잭 게임의 룰을 다시 살펴봤는데
카프카께서 말씀해주신 것이 본래 블랙잭 룰이라고 생각되어 변경하였습니다 ㅎㅎ ..

2023-03-11 13:43 UTC, include42 commented
안녕하세요 라온, 리뷰어 카프카입니다.
리뷰 보내주신 내용 잘 확인하였습니다. 미리 dm 주신 점도 감사하고, 변경지점에 대해 코멘트로 잘 정리해주신 점도 감사하네요😃 리뷰시 해당 부분은 꼼꼼히 확인해 보겠습니다👍🏻

오늘 저도 개인 일정이 길어져서, 리뷰는 내일(일) 오전 10시 - 12시 사이에 가능할 것으로 생각합니다. 
그래도 이전 스텝에서 구조를 잘 작성해주셔서 큰 변경사항은 없을 것으로 보이니, 주말간에 푹 쉬시고 월요일에 천천히 확인해보시기를 권합니다.

작업하시느라 고생 많으셨습니다! 👏🏻

2023-03-12 02:39 UTC, include42 commented on src/main/java/blackjack/domain/BlackJackGame.java
>          this.players = new Players(inputNames);
베팅이 추가되면서 고민이 많이 되었겠네요. 
다만 현재 구조도 충분히 괜찮게 잘 구현되고 있다고 코멘트하고 싶습니다.

현재엔 컨트롤러에서 바로 도메인을 만들지만, MVC 구조대로 프로그래밍할때엔 서비스라는 레이어를 중간에 포함하기도 합니다.
컨트롤러는 외부 요청을 받아서 적절한 서비스로 넘기고, 서비스는 필요한 비즈니스 연산을 순서대로 수행합니다.
예를 들어 위와 같은 경우, 입력값을 컨트롤러가 모아서 서비스에 넘기고, 서비스는 players를 생성한 뒤 BlackJackGame에 주입해줄 수 있습니다.
이러한 구조는 레벨2 과정에서 보다 상세히 배우는 것으로 알고 있으니, 지금은 일단 컨트롤러가 서비스 역할까지 수행한다고 가정하고, 도메인을 주입하는 것에 대해 너무 부담가지시지는 않아도 됩니다.

다만, 베팅 값이 플레이어 이름 값 다음에 들어오므로 둘 사이의 시간차가 발생하는 문제가 있기는 합니다.
이에 대응하기 위해 Participant의 Bet 필드를 null로 두어서 나중에 setter로 주입할 수도 있고,
Bet을 수행하는 클래스를 분리해서 별도로 생성해 준 뒤 관리해 줄 수 도 있습니다.
저는 구조상으로도 후자가 좋다고 생각하는데, 이미 이렇게 구현해주셨네요 💯

2023-03-12 02:41 UTC, include42 commented on src/main/java/blackjack/domain/card/CardsFactory.java
> +public class CardsFactory {
이름을 변경하면서 적어주신 이유는 제가 코멘트한 이유와 동일합니다. 의도가 더 명확히 드러나므로 이해하기 좋다고 생각합니다.
Optional로 생성한 것은 52장을 모두 뽑는 경우 때문인 것 같은데, 해당 코드 확인해보고 코멘트 드리겠습니다.

2023-03-12 03:24 UTC, include42 requested changes
안녕하세요 라온, 리뷰어 카프카입니다.

이번 작업 깔끔하게 잘해주셨네요! 저번 리뷰때 이미 리팩토링을 잘 해주셔서,
개선할 부분이 많지 않았습니다. 현재 미션의 요구사항을 잘 충족하고 있는 것으로 생각되네요. 💯 
다만 optional과 DTO 관련해서 추가 개선을 해보고 싶다고 말씀해 주셨는데,
해당 부분 + 리뷰 개선사항 반영 해주시면 다시 한 번 리뷰를 진행하겠습니다.
작업하시느라 고생 많으셨습니다! 👍

2023-03-12 03:24 UTC, include42 commented on src/main/java/blackjack/domain/card/Deck.java
> +    public Deck() {
Deck으로 바꾸면서 구조적으로도 개선을 많이 해주셨네요! 매우 좋습니다 👍

2023-03-12 03:24 UTC, include42 commented on src/main/java/blackjack/domain/participant/DealerResult.java
> +public class DealerResult {
DealerResult 관련 연산이 이 클래스로 모여서 좋네요. 값을 포장해준 것이 좋은 선택이었다고 생각합니다. 😄

2023-03-12 03:24 UTC, include42 commented on src/main/java/blackjack/view/InputView.java
> +    private static final String NATURAL_NUMBER_REGEX = "^[1-9]+[0-9]*$";
정규식을 통해 검증을 잘 수행해 주셨네요!
이번 미션에서 사용해 보면서 학습한 내용을 잘 정리해두시면, 앞으로 validate 과정에서 많이 활용하실 수 있을 것입니다. 💯

2023-03-12 03:24 UTC, include42 commented on src/main/java/blackjack/view/OutputView.java
> +    public static void printFinalProfit(final Profit dealerProfit, final Map<Player, Profit> playerProfit) {
현재 DTO에 대해 학습을 해본 적이 없어서 적용이 많이 어려우실 것이라 생각됩니다.
그렇다면 본 메소드 (printFinalProfit) 호출 시에만 DTO를 써보는 것을 이번 미션 마무리에서 해보시는 걸 권합니다.
 - 물론 더 학습해 보고 다음 미션에서 진행해도 괜찮으므로, 이 부분의 선택은 라온의 자유입니다.

현재는 딜러의 Profit 객체와 플래이어들의 Profit 객체가 전달되고 있는데,
사실 OutputView에서 필요한 값은 딜러와 플레이어가 얻을 금액(int) 입니다. 
그렇다고 int로 전해주는 것은 좋지 않아 보이고, 값을 묶어서 하나로 포장하면 좋겠지요?
그래서 아래처럼 클래스를 만들고, 적절히 구조를 짠다고 생각해봅시다.
```
public class BlackJackProfitDTO {
    private final int dealerProfit;
    private final List<PlayerProfitDTO> playerProfit;
}
public PlayerProfitDTO {
    private final String name;
    private final int profit;
}
```
위 클래스는 순수하게 값 전달을 목표로 하는 클래스입니다.
내부적으로 비즈니스 로직은 없도록 하고, 생성자와 getter 정도만 두면 되겠네요.
이를 통해 값 전달시, OutputView에서는 getter를 통해 값을 꺼내는 것과 반복문 순회 만을 수행하며, 별도의 로직을 건드리는 등의 일은 없게 되겠습니다.

2023-03-12 03:24 UTC, include42 commented on src/test/java/blackjack/domain/ProfitTest.java
> +        assertDoesNotThrow(() -> Profit.of(input));
이 부분은 테스트의 수정이 필요해 보입니다. 생성 후 값이 잘 들어가는지 확인해야 잘 생성된다고 판단될 것 같습니다.

given에서 Profit.of를 통해 생성해주고, when/then에서 profit.getValue를 수행해 그 값이 주입해준 값이 맞는지 확인해보면 어떨까요?

2023-03-12 17:46 UTC, mcodnjs reviewed
안녕하세요, 카프카! 라온입니다 😊

이번 리뷰 반영 사항은 다음과 같습니다! 관련하여 고려한 사항들을 커멘트로 남겨놓았습니다 !!
1단계에서 주셨던 피드백은 모두 반영하였습니다 ~! 

- [Optional 사용 -> 그대로 유지하되 중복 로직만 메서드로 분리](https://github.com/woowacourse/java-blackjack/pull/524#discussion_r1133295167)
- Profit 출력에 DTO 사용
- Stay, Hit command enum 분리
- [수익과 베팅금액을 담당하는 클래스(Profit -> Money) 역할 명확히 ](https://github.com/woowacourse/java-blackjack/pull/524#discussion_r1133291163)

주말에도 빠른 피드백과 리뷰 감사드립니다 🙇

2023-03-12 17:46 UTC, mcodnjs commented on src/main/java/blackjack/domain/Profit.java
> +    }
Profit이라는 클래스가 **베팅금액**과 **수익금**의 역할을 모두 담당함에 따라 모호한 문제가 발생한 것 같아요. 

BettingMoney에서 베팅금액의 유효성 검사와 객체 생성을 담당하고, Profit에서 BettingMoney를 인스턴스 변수로 갖게 하려했는데, 아래와 같은 여러 고민 사항들로 두 객체를 나누는 것은 반영하지 못하였습니다.

- 입력을 받고 난 후에 Profit을 가지고 있어야하는지, BettingMoney를 가지고 있어야 하는지 / 언제 Profit을 생성하는게 좋을지 / 컨트롤러 혹은 게임 도메인은 BettingMoney를 알고 있어야하는지 Profit을 알고 있어야 하는지 혹은 둘다 알고 있어야하는지 등 ..

두 도메인 중 어떤 도메인으로 관리해야하는지가 가장 어려웠습니다.. 지금 드리는 커멘트가 이해하기 어려우실 수도 있는데, 넘어가셔도 괜찮습니다 ㅎㅎ 내일 다른 크루들한테도 물어보며 의견을 나눠보겠습니다 .. ! 

**대신, 기존의 로직은 그대로 유지하되, 조금 더 명확한 네이밍과 책임을 두었습니다!** 

- Profit → Money 클래스로 네이밍을 변경하였고
- 처음 플레이어에게 받는 베팅금액은 `forBetting` 의 정적 팩토리 메서드로 구체화하였고
- 처음 딜러의 베팅금액은 0으로 생성하였고,
- dealerProfit을 계산하기 위한 minus 메서드를 구현하였습니다.

2023-03-12 17:46 UTC, mcodnjs commented on src/main/java/blackjack/view/OutputView.java
> +    public static void printFinalProfit(final Profit dealerProfit, final Map<Player, Profit> playerProfit) {
넵 카프카가 말씀해주신 방법대로, Profit 부분만 DTO를 통해 출력해보았습니다!

2023-03-12 17:46 UTC, mcodnjs commented on src/main/java/blackjack/controller/BlackJackGameController.java
>      }
카프카께서 [1단계 리뷰](https://github.com/woowacourse/java-blackjack/pull/469#discussion_r1128788422) 때 말씀해주신 Optional의 목적에 동의합니다. 이번에 처음 Optional을 사용해보았는데, 저는 단순히 어떻게 null과 다른 객체를 반환할 수 있을까? 해서 나온 아이디어였습니다 ㅎㅎ 레퍼런스 해주신 이펙티브 자바 책에도 카프카와 동일한 의견을 비추고 있네요! 

- 결과가 없을 수 있으며, 클라이언트가 이 상황을 특별하게 처리해야 한다면 Optional<T>를 반환
- Optional<T>를 반환하는데의 대가: 객체이므로, 그 안에서 값을 꺼내려면 메서드 호출 필요

덕분에, Optional<T>의 사용 목적에 대해 알게 되었습니다 🙇‍♂️ 

다만, 카프카가 말씀해주신대로 
> checkValidGameCommand에서는 예외만 발생시키고 generateGameCommand에서 해당 예외를 try해주는게 더 자연스러울 수도 있습니다.

위 방식을 따르면서 + 재입력을 받으며 + 재귀함수를 사용하지 않고 + indent 1을 지킬 수는 없다고 생각되어 수정을 못하였습니다 ㅠㅠ 요구사항에 맞추기 위해 Optional을 억지로 사용한 코드같긴 하지만, 다른 방법(null return 외)이 떠오르지 않아 optional 사용을 유지하였습니다. 반복되는 코드가 있어 이 부분만 따로 함수로 빼서 작성하였습니다!

2023-03-12 17:46 UTC, mcodnjs commented on src/main/java/blackjack/domain/Command.java
> +public enum Command {
[1단계에서 말씀](https://github.com/woowacourse/java-blackjack/pull/469#discussion_r1125251311)주신 것처럼 Command 클래스를 분리하여 controller의 역할을 조금 덜어줬습니다 ~! 분리하기 잘한 것 같습니다 ㅎㅎ

2023-03-13 00:21 UTC, include42 approved these changes
안녕하세요 라온, 리뷰어 카프카입니다.

늦은 시간까지 작업해주시느라 고생 많으셨습니다.
구현 과정에서 어려움이 많았을 텐데, 고민되는 부분들을 잘 정리해주셔서
함께 논의하며 성장할 수 있었다고 생각합니다. 덕분에 저도 많이 고민해 볼 수 있는 시간들이었습니다 😄 

저번에 드린 피드백 바탕으로, 마무리까지 잘 해주셨습니다.
개선된 부분들에 대해 간단히 코멘트 남겨두었으니, 확인해보시면 좋겠습니다.
오늘은 이번 미션 내용을 정리하고 복기하며 휴식하는 시간이 되시길 바랍니다.

지금까지 고생 많으셨습니다! 미션 approve 하겠습니다 🚀

2023-03-13 00:21 UTC, include42 commented on src/main/java/blackjack/domain/Command.java
> +public enum Command {
이부분이 분리되니 코드가 많이 깔끔해졌네요!
그리고 CommandTest를 정석에 맞게 잘 작성해주셨어요 💯 💯 아주 좋습니다!

2023-03-13 00:21 UTC, include42 commented on src/main/java/blackjack/domain/Command.java
>                  .findFirst()
다만 여기서 생성자에 대한 접근 제어자가 필요할 것으로 보입니다 (여기서는 정적 팩토리 메소드를 썼으므로, private으로 해주면 되겠네요)
정적 팩토리 메소드를 잘 사용해 주셨는데, 시간이 날 때 이펙티브 자바의 Item1번을 따로 읽어보면 도움이 될 것으로 생각됩니다. 사용하는 이유와 활용 방법에 대해 이번 학습을 통해 정리해두면 좋겠습니다 👍

2023-03-13 00:21 UTC, include42 commented on src/main/java/blackjack/domain/Money.java
> +    }
이부분을 변경해두니 좀 더 흐름이 명확하게 느껴졌습니다. 😄 
앞서 논의한대로 판돈과 수익금이라는 두 개념을 어떻게 도메인으로 묶을지가 가장 어려운 부분이었고, 해당 클래스들을 어디서 관리할지도 고민이 많이 되는 부분이었어요.
어제 다른 크루들의 작업물을 살펴보니, 이 부분에서 다양한 의견이 나왔던 것으로 보여요.
제가 드리는 피드백도 정답은 아니니까요, 크루들과 많이 이야기해보고 더 좋은 방법이 무엇이었을지, 복기하는 시간을 가져보면 성장에 큰 도움이 될 것입니다. 💯

2023-03-13 00:21 UTC, include42 commented on src/main/java/blackjack/controller/BlackJackGameController.java
> +        }
이부분은 stream을 통해 생성해주는 방법도 고려해보면 좋겠네요. 😄 
DTO 클래스의 구현 잘 해주셨습니다. 해당 부분에 적용해보니, OutputView의 코드가 많이 간단해졌지요?
레벨2에서는 본격적으로 DTO를 다루게 될텐데, 그 전에 레벨 1에서 미리 학습해 둔 것이 도움이 될 것이라고 믿습니다. 👍 👍

2023-03-13 00:22 UTC, merged