[2단계 - 블랙잭(베팅)] 민트(유재민) 미션 제출합니다.
woowacourse/java-blackjack pull request #545
Opened 2023-03-11 19:03 UTC by yujamint

안녕하세요, 제이미! 리뷰이 민트입니다 :)
블랙잭 미션 2단계 구현 완료했습니다!
1단계에서 너무 좋은 리뷰들을 많이 해주셔서 정말 큰 도움이 되었습니다 ㅎㅎ 감사합니다!
이번 리뷰 역시 잘 부탁드리겠습니다.

2단계 진행하며 궁금했던 부분에 대해 질문 드리겠습니다!

### 역할이 적은 일급 컬렉션은 불필요할까요?
2단계에서 베팅 금액이 추가되면서 Player가 생성자에서 이름과 베팅 금액을 한 번에 주입받도록 수정했습니다. 그에 따라 이름의 리스트를 관리하는 일급 컬렉션 Names를 생성하였습니다. 이때, 원래 이름에 대한 검증을 진행하던 Players 컬렉션의 역할이 Names로 대부분 옮겨졌습니다.
현재는 Players 컬렉션이 이름과 베팅 금액의 리스트를 받아 Player들을 생성해주는 역할만 가지고 있습니다. 이는 컨트롤러에서도 충분히 해줄 수 있는 역할이라고 생각하여, Players 클래스가 불필요할 수도 있겠다는 생각을 했습니다.
이렇게 비즈니스적 로직은 아예 가지고 있지 않은 일급 컬렉션은 불필요할까요? 저는 괜히 만들어 놓았다가 관리의 대상만 늘어나는 것 같은 느낌을 받았습니다.

따로 궁금했던 점은 이상입니다. 그럼 이번 리뷰도 잘 부탁드리겠습니다 제이미! 감사합니다 :)

2023-03-12 05:12 UTC, jamie9504 requested changes
민트, 안녕하세요. 리뷰어 제이미입니다. 😄 

2단계 구현도 고생하셨습니다.

아래 코멘트에 대한 답변을 적어두도록 하겠습니다.

> **역할이 적은 일급 컬렉션은 불필요할까요?**
> 2단계에서 베팅 금액이 추가되면서 Player가 생성자에서 이름과 베팅 금액을 한 번에 주입받도록 수정했습니다. 그에 따라 이름의 리스트를 관리하는 일급 컬렉션 Names를 생성하였습니다. 이때, 원래 이름에 대한 검증을 진행하던 Players 컬렉션의 역할이 Names로 대부분 옮겨졌습니다.
> 현재는 Players 컬렉션이 이름과 베팅 금액의 리스트를 받아 Player들을 생성해주는 역할만 가지고 있습니다. 이는 컨트롤러에서도 충분히 해줄 수 있는 역할이라고 생각하여, Players 클래스가 불필요할 수도 있겠다는 생각을 했습니다.
> 이렇게 비즈니스적 로직은 아예 가지고 있지 않은 일급 컬렉션은 불필요할까요? 저는 괜히 만들어 놓았다가 관리의 대상만 늘어나는 것 같은 느낌을 받았습니다.

``` java
    private final Players players; // 인스턴스 변수

        // 사용처
        for (Player player : players.getPlayers()) {
            player.receiveCards(cards.drawCards(INITIAL_CARD_COUNT));
        }
```

위의 부분에서 `players.getPlayers()`를 해와서 player에게 각각 일을 시키고 있는데요.
로직을 수행할 때 getter를 사용해서 내부 변수를 바깥에서 직접 사용하게 되면 사실상 타겟 클래스의 역할은 getter 반환밖에 없겠죠?

도메인 로직에서는(View를 위한 DTO 로직 제외) 최대한 해당 도메인에게 역할을 위임해보는 것은 어떨까요?
`디미터의 법칙`에 대해서 조금 더 알아봐도 좋구요 😄

2023-03-12 05:12 UTC, jamie9504 commented on src/main/java/blackjackgame/domain/user/Players.java
> +    public Players(Names names, List<Bet> bets) {
해당 생성자만 봤을 땐, `names.getNames()`와 `bets`의 사이즈가 다른 경우 다음과 같은 두 경우가 있을 것 같은데요.

1. `names.getNames()`가 더 사이즈가 큰 경우, `bets`가 적으므로, 일부 player 생성되지 않음
2. `bets`가 더 사이즈가 큰 경우, 예외 발생

Players를 사용하는 입장에선, (현재 로직과 상관 없이)
2번인 경우엔 생성자에서 바로 예외가 발생하여, 알아차릴 수 있지만 (Runtime)
1번인 경우엔 예상치 못하게 동작할 수도 있을 것 같네요!

2023-03-12 05:12 UTC, jamie9504 commented on src/main/java/blackjackgame/domain/user/Score.java
> +    private static final int MAX_SCORE = 21;
MAX_SCORE는 뭔가, 게임의 기준 점수보다는 해당 Score라는 객체가 가질 수 있는 가장 큰 점수의 느낌이 나기도 하네요 😄

2023-03-12 05:12 UTC, jamie9504 commented on src/main/java/blackjackgame/domain/user/User.java
> +    public List<Card> cards() {
어째서 이 친구는 메서드명이 명사일까요?

2023-03-12 05:12 UTC, jamie9504 commented on src/main/java/blackjackgame/view/InputView.java
> +    }
😄 
<img width="398" alt="image" src="https://user-images.githubusercontent.com/59511689/224525382-8e7fdfab-8809-46ac-9549-8784b05f947c.png">

Player의 이름이 "딜러"가 될 수 없다는 것을 누가 아는 것이 가장 적절할지 고민해볼까요!

1. InputView
2. BlackJackController
3. BlackJackGame
4. Player
5. Name을 생성하기 위해 playerNames를 받을 때

2023-03-12 05:12 UTC, jamie9504 commented on src/main/java/blackjackgame/view/OutputView.java
> +        System.out.print(NEWLINE);
요건 그냥 `System.out.println()`을 사용해도 되지 않을까요? 😄

2023-03-12 05:12 UTC, jamie9504 commented on src/test/java/blackjackgame/domain/Fixtures.java
> +    public static final List<Card> jackKingNine = List.of(CloverCard.CLOVER_JACK, DiamondCard.DIAMOND_KING,
상수로 사용하려면 대문자여야겠죠?
`JACK_KING_NINE`만 보았을 땐, `List<Card>`를 리턴할 것이라는 것이 유추하기 쉽지 않으니
`JACK_KING_NINE_CARDS` 정도로 해주어도 좋겠네요 😄

2023-03-12 05:12 UTC, jamie9504 commented on src/test/java/blackjackgame/domain/user/BetTest.java
> +    }
실패 케이스가 있으면, 성공 케이스가 있어야 좋겠죠?
`vet`은 오타일까요~?

2023-03-12 05:12 UTC, jamie9504 commented on src/test/java/blackjackgame/domain/user/HandsTest.java
> +        assertThat(card).isSameAs(SpadeCard.SPADE_KING);
개인 취향이지만, `SpadeCard.SPADE_KING`를 한 변수로 묶어놔도 좋을 것 같긴 하네요.
테스트 메서드가 길어졌을 때, 가독성이 좋아질 것 같아요!

``` java
        Card 추가_카드 = SpadeCard.SPADE_KING;
        hands.add(추가_카드);
        Card card = hands.getCards().get(0);

        assertThat(hands.size()).isEqualTo(1);
        assertThat(card).isSameAs(추가_카드);
```

2023-03-12 05:12 UTC, jamie9504 commented on src/test/java/blackjackgame/domain/user/NamesTest.java
> +class NamesTest {
Name라는 용어를 사용할거라면,
아래 `@DisplayName`, 메서드명, 파라미터들의 이름들도 일관성있게 바꿔볼까요?

Test 코드 뿐만 아니라 Product 코드도 바꿔보아요~

2023-03-12 05:12 UTC, jamie9504 commented on src/test/java/blackjackgame/domain/user/PlayerTest.java
> +        player = new Player(new Name("플레이어"), new Bet(5000));
천단위 이상은 `5_000`로 언더바를 사용하는 습관을 들이면, 자릿수를 편하게 파악할 수 있어요!

2023-03-13 07:12 UTC, yujamint commented on src/main/java/blackjackgame/controller/BlackJackGameController.java
> +            blackJackGame.hit(player);
기존 DrawCommand.STAY가 그 어디에서도 쓰이지 않는 것을 보고 뭔가 찝찝하긴 했는데, 게임의 입장에서는 HIT에 대한 것만 아는 것이 문제였던 것 같네요..! Player의 입력값을 Game 클래스로 넘기고, Game 클래스에서 이를 처리하도록 수정했습니다!

2023-03-13 07:13 UTC, yujamint commented on src/main/java/blackjackgame/domain/game/BlackJackGame.java
>      private final Cards cards;
다른 클래스들에 대해서는 인스턴스 변수를 2개까지만 허용하도록 했는데, BlackJackGame 클래스는 어떻게 줄여야 될지 더 고민해봐야겠네요..😭 당장 마감 전까지 고민할 시간이 부족한 것 같아, BlackJackGame 클래스를 제외하고 개선했습니다!

2023-03-13 07:16 UTC, yujamint commented on src/main/java/blackjackgame/domain/game/BlackJackGame.java
> +        referee.judgeWinner();
수익 결과를 구하기 위해서 judgeWinner와 getBetResult가 하나의 세트로 동작하는 것을 인지하지 못 했네요..! 리뷰 감사합니다!
하나의 public 메서드를 통해서 두 동작이 함께 실행되도록 수정했습니다!

2023-03-13 07:18 UTC, yujamint commented on src/main/java/blackjackgame/domain/game/BlackJackGame.java
>      public Map<NameDto, List<Card>> getSetUpResult() {
DTO는 뷰의 요청사항에 따라 구현하게 될 것이고, 이는 즉 뷰 요청사항이 변경됨에 따라 DTO도 변경될 수 있습니다. 그렇기 때문에 도메인이 DTO를 알고 있는 것은 도메인이 뷰에 의존하는 꼴이 될 수 있을 것 같습니다.
도메인이 DTO를 알고 있지 않도록 수정했습니다 :)

2023-03-13 07:21 UTC, yujamint commented on src/main/java/blackjackgame/domain/user/Bet.java
> +    }
Profit 클래스를 따로 생성해서 해당 클래스 내에서 계산의 책임을 갖도록 수정했습니다. 이 방법이 최선인지에 대해서는 의문이 생겼습니다..! 승 / 무 / 패 / 블랙잭 승 각 상태에 대해 처리를 해주는 메서드를 갖는 것을 분기 없이 하나의 메서드가 해결할 수 있도록 바꾸고 싶네요.
이때 상태 패턴을 고민해보면 좋은 걸까요?

2023-03-13 07:23 UTC, yujamint commented on src/main/java/blackjackgame/domain/user/Hands.java
> +        this.cards = new ArrayList<>(Collections.emptyList());
Collections.emptyList() 는 **수정이 불가능한** 빈 리스트를 반환합니다. 하지만 위 코드처럼 생성자를 통해 emptyList를 전달할 경우에는 아무 것도 전달하지 않았을 때와 같은 결과를 반환합니다.
그러므로, 이 경우에는 굳이 emptyList를 전달할 필요가 없는 것 같습니다.

2023-03-13 07:25 UTC, yujamint commented on src/main/java/blackjackgame/domain/user/Players.java
> +    public Players(Names names, List<Bet> bets) {
```
private List<Bet> setUpPlayerBets(Names playerNames) {
    List<Bet> playerBetAmounts = new ArrayList<>();
    for (Name playerName : playerNames.getNames()) {
        playerBetAmounts.add(repeatForValidInput(() -> readPlayerBetAmount(playerName)));
    }
    return playerBetAmounts;
}
```
controller에서 위 메서드와 같이 `Names.getNames`의 사이즈만큼만 입력을 받도록 했습니다. 그래서 `bets`와 `names.getNames()`의 사이즈 검증이 따로 필요하지 않을 것이라 생각했습니다.
그럼에도 프로그램의 안정성을 위해 유효성 검증을 하는 게 좋을까요?

2023-03-13 07:27 UTC, yujamint commented on src/main/java/blackjackgame/view/InputView.java
> +    }
현재 코드의 경우에는 InputView에서 이름을 담은 `List<String>`을 반환할 때, strip을 통해 공백을 제거한 문자열 리스트를 반환하고 있습니다. 그렇기 때문에 Names 클래스에서 `List<String>`에 "딜러"가 포함돼 있는지 검증을 하면 " 딜러" 또는 "딜러 "와 같은 케이스까지 잡아낼 수 있을 것 같습니다.

2023-03-13 07:29 UTC, yujamint commented on src/main/java/blackjackgame/view/OutputView.java
> +        System.out.print(NEWLINE);
print(NEWLINE)을 사용하는 것이 개행한다는 것을 가시적으로 확인할 수 있다고 생각했습니다. 하지만, System.out.println() 내부에서 NEWLINE() 메서드를 호출하는 것을 확인했고, print(NEWLINE)을 통해 개행을 출력하는 것이 불필요하다는 것을 알게 됐습니다!

2023-03-13 07:30 UTC, yujamint commented on src/test/java/blackjackgame/domain/user/HandsTest.java
> +        assertThat(card).isSameAs(SpadeCard.SPADE_KING);
변수로 추출하는 것이 추가된 카드임을 확인하기에 좋을 것 같습니다! 좋은 리뷰 감사합니다 :)

2023-03-13 07:32 UTC, yujamint commented on src/test/java/blackjackgame/domain/user/PlayerTest.java
> +        player = new Player(new Name("플레이어"), new Bet(5000));
사소한 질문이 있습니다..! 음수를 표현할 때에도 `-5_000`과 같이 표현하면 될까요? 하이픈(`-`)과 언더바(`_`)를 함께 사용하니 괜히 어색한 느낌이 들어 여쭤봅니다😅

2023-03-13 07:34 UTC, yujamint reviewed
안녕하세요, 제이미! 리뷰이 민트입니다.😄
2단계 리팩토링 완료했습니다! 리팩토링 진행하며 궁금했던 부분은 코멘트에 남겼습니다.
블랙잭 미션 마지막 리뷰 잘 부탁드리겠습니다 :)

2023-03-14 13:20 UTC, jamie9504 commented on README.md
> +- [x] Dealer와 Player 모두 name을 가진다면 User에서 관리할 수 있지 않을까?
.

2023-03-14 13:20 UTC, jamie9504 commented on src/main/java/blackjackgame/domain/user/Bet.java
> +    }
// TODO

2023-03-14 13:20 UTC, jamie9504 commented on src/main/java/blackjackgame/domain/user/Players.java
> +    public Players(Names names, List<Bet> bets) {
// TODO

2023-03-14 13:20 UTC, jamie9504 commented on src/test/java/blackjackgame/domain/user/PlayerTest.java
> +        player = new Player(new Name("플레이어"), new Bet(5000));
네! 그냥 `,` 대신 `_`를 쓴다고 생각하면 될 것 같아요!
`-5,000` 를 `-5_000`로 쓰는건거죠!

2023-03-14 13:47 UTC, jamie9504 commented on src/main/java/blackjackgame/view/InputView.java
> +    }
Name은 플레이어와 딜러 이름을 모두 받을 수 있는데,
Names가 "딜러"라는 이름을 가지고 있는지 검증을 하는 게 맞을까요?

그럼 Player라는 도메인은 "딜러"라는 이름을 가질 수 있는게 되네요 😄 

현재 프로그램에선 정상적으로 동작하지만,
민트가 아닌 다른 개발자가 이 프로그램을 수정하거나 확장한다면 이 부분이 예상한대로 동작할 수 있을까요?

2023-03-14 13:47 UTC, jamie9504 commented on src/test/java/blackjackgame/domain/user/PlayerTest.java
> +        player = new Player(new Name("플레이어"), new Bet(5000));
네! 그냥 `,` 대신 `_`를 쓴다고 생각하면 될 것 같아요!
`-5,000` 를 `-5_000`로 쓰는건거죠!

2023-03-15 03:50 UTC, jamie9504 requested changes
민트, 안녕하세요. 리뷰어 제이미입니다 😄

피드백과 코멘트에 대한 답변을 남겨두었어요.

어제부터 체스 미션을 진행하고 계실텐데요, 이번 미션에 집중하는 것도 좋은 선택이라고 생각합니다.

리뷰 확인 후 수정하고 싶으신 부분이 있으면 수정하시고,
수정하고 싶은 부분이 없으시다면 바로 리뷰 보내주시면 될 것 같아요.

이번이 마지막 리뷰요청이었으므로,
다음번 리뷰 요청은 코드에 대한 별도의 코멘트나 리뷰 없이 바로 Merge 될 예정입니다 😄

2023-03-21 05:47 UTC, yujamint commented on src/main/java/blackjackgame/view/InputView.java
> +    }
> 그럼 Player라는 도메인은 "딜러"라는 이름을 가질 수 있는게 되네요 😄

Names에서 "딜러"라는 이름을 걸러내고, 이를 Players에 전달하며 Player 객체를 생성하고 있습니다.
하지만, 결국 Player가 전달 받는 객체는 **"딜러"라는 이름을 입력받을 수 있는** Name이기 때문에 "딜러"라는 이름을 가질 수 있다고 말씀하신 걸까요??
그런 관점에서 본다면, Player가 "딜러"라는 이름을 받지 않는 것은 결국 제가 개발했기 때문에 아는 내용이고 다른 개발자가 보기엔 Name에서 걸러주지 않는 게 이상하다고 느껴질 수 있을 것 같네요..!

결국, Names 클래스 이름을 PlayerNames로 바꿈으로써 Player의 이름에 대한 유효성을 검증한다는 의미를 더했습니다. 추가로, Player 도메인 내에서 이름에 대한 유효성 검증을 한 번 더 하는 것으로 수정했습니다.

2023-03-21 12:37 UTC, yujamint reviewed
안녕하세요 제이미, 리뷰이 민트입니다!
블랙잭 게임 미션 마지막 리팩토링 완료했습니다. 아직 만족스럽지 않은 부분도 있지만, 체스 게임을 통해 더 많은 내용을 학습하고자 이만 머지 요청 드립니다 ㅎㅎ
마지막 리뷰까지 열심히 해주셔서 감사합니다. 고생 많으셨습니다!!

2023-03-21 12:37 UTC, yujamint commented on src/main/java/blackjackgame/domain/user/Player.java
> +        this.profit = new Profit(bet);
인스턴스 변수 2개 제한 때문에 억지로 bet을 바로 Profit으로 만들어 버렸고, 맥락상 이상하게 느껴지는 것 같습니다😅

Bet과 Profit을 관리하는 BetResult 클래스를 생성했습니다. 플레이어는 BetResult 객체를 인스턴스 변수로 가지도록 했습니다. BetResult는 Bet과 Profit을 연결해 주는 역할만 하고 있어서, 이게 올바른 분리를 한 건지 잘 모르겠네요..

2023-03-23 00:26 UTC, jamie9504 approved these changes
민트, 안녕하세요. 리뷰어 제이미입니다. 😄 

리뷰 반영 고생하셨습니다.
체스 미션에서도 많은 걸 배우고 성장하시길 바랄게요! 💪 

저번에 코멘트 남겨두었던 것처럼,
마지막 리뷰요청 이후 요청이므로 코드에 대한 별도의 코멘트나 리뷰 없이 바로 Merge 하겠습니다.

2023-03-23 00:26 UTC, merged