[2단계 - 블랙잭(베팅)] 아벨(신준혁) 미션 제출합니다.
woowacourse/java-blackjack pull request #546
Opened 2023-03-11 19:38 UTC by tjdtls690

리뷰어님 피드백 보고 함수형 인터페이스를 이용해서 Application 에서 진행되던 '배팅 금액 입력 및 저장' 과 '카드 한 장씩 뽑거나 그만두는 로직' 을 도메인 객체로 위임할 수 있게 되었습니다. 좋은 인사이트를 알려주셔서 정말 감사합니다.

카드의 점수를 계산하고 서로 비교하는 로직을 Score라는 객체로 분리해서 위임했습니다.

각 플레이어의 관리를 상태 패턴을 통해 관리하게끔 구현했습니다. 배팅 금액까지 요구사항에 들어오면서 많은 분기점이 생겼습니다. 때문에 상태 패턴을 통해 개선하고자 했습니다.

그 외에 1단계의 피드백을 전부 적용해보았습니다. 리뷰 잘 부탁드립니다!

2023-03-12 10:29 UTC, lowoon requested changes
고생하셨어요. 아벨! 리뷰 반영 잘 해주셨어요! 😄 
몇 가지 코멘트 남겼으니 확인해주세요ㅎㅎ
궁금한 점은 언제든지 DM이나 코멘트 남겨주세요 :)

2023-03-12 10:29 UTC, lowoon commented on src/main/java/Application.java
> +                referee::saveParticipantBetAmount
function을 넘겨서 진행하는 경우에 대해서 사용하는 경우에 역할과 책임에 대해서 고민을 하고 사용하시라고 말씀드렸는데요.
이 메서드만 보더라도 처음에 보았을 때 로직을 파악하기 굉장히 힘들거에요.
아벨이 아닌 처음 보는 사람이 이해하기 쉬운 구조일까요??
1. outputView로직과 inputBetAmout는 하나의 메서드로 만들 수 없을까요?? 입력을 받기위해 하는 동작인데 분리하는 것이 맞을까요?? 만약 입력은 console로 하고 출력은 print, web등 다른 것으로 되는 경우에는 어떻게 될까요??
2. Referee의 역할이 돈에 대한 관리일까요 아니면 게임의 결과로써 베팅 결과를 만들어내는 걸까요???? 처음 입력받은 돈에 대해서는 players나 blackJackGame에서 관리할 수 있지 않을까요??

2023-03-12 10:29 UTC, lowoon commented on src/main/java/Application.java
> +        blackJackGame.giveCardToParticipantsBy(this::inputCommand, OutputView::printParticipantCardStatus);
입력은 매번 받아야하는 것이기 때문에 functional interface를 사용하는 것을 고려할 수 있는데요.
분배결과를 출력하는 것도 functional interfacr를 활용하는 방식을 사용해야하는 걸까요??
메서드의 return으로 결과를 받고 이 결과를 outputView에 넘기는 방식으로 진행하는 것이 더 명확하지 않을까요??

2023-03-12 10:29 UTC, lowoon commented on src/main/java/domain/game/BlackJackGame.java
> +        players.giveCardToDealerBy(deck, printGiveDealerCardMessage);
딜러의 경우 participant와 같은 메서드를 사용하는 것보다 딜러만의 메서드를 만드는 것이 더 파악하기 쉬울 수 있지 않을까요?
입력을 받지 않는다면 아래와 같이 하는것이 더 간단해보여서요.
```java
1. dealer 상태확인
2. 카드분배
3. 출력
```

2023-03-12 10:29 UTC, lowoon commented on src/main/java/domain/card/Score.java
> +    private final int score;
score를 만들었다면 Number에서 Score를 가질 수 있지 않을까요??

2023-03-12 10:29 UTC, lowoon commented on src/main/java/domain/card/Score.java
> +        this.score = score;
아무 검증이 없네요??
음수도 가질 수 있는걸까요??

2023-03-12 10:29 UTC, lowoon commented on src/main/java/domain/card/Score.java
> +    }
equals and hashCode를 만들 수 있을 것 같고요.
이 부분은 참고용인데 comparable를 상속받을 수도 있을것 같아요!

2023-03-12 10:29 UTC, lowoon commented on src/main/java/domain/player/Participant.java
> +        AddCardCommand command = supplyCommand.apply(this);
command가 서버 도메인에서 쓰이고 있는데 view pacakage에 잇는것이 맞나요??

2023-03-12 10:29 UTC, lowoon commented on src/main/java/domain/player/state/Hit.java
> +        return this;
this를 return하는 것이 좋은 방법일까요??
불변객체를 학습해보시면 좋을 것 같아요!

2023-03-12 10:29 UTC, lowoon commented on src/main/java/domain/player/state/Ready.java
> +        getHand().addCard(card);
ready 상태를 만드는 시점이 아니라 draw를 하는 시점에 inital card에 대해서 카드를 받는 것이 맞을까요?

2023-03-12 10:29 UTC, lowoon commented on src/main/java/view/OutputView.java
> +    private static String parsePlayersResult(BlackJackGame blackJackGame, Referee referee) {
view에 player가 넘어오는 것까지는 현재의 프로그램 구조에서 괜찮을것 같은데요.
주요 비지니스 로직을 담당하는 game이 넘어오는 것이 맞을까요??

2023-03-12 13:49 UTC, tjdtls690 commented on src/main/java/Application.java
> +                referee::saveParticipantBetAmount
1. 원래는 입력은 입력만, 출력은 출력만 철저하게 로직을 분리하고 싶어서 따로 두었습니다. 그런데 말씀해주신 케이스를 보고 다시 고민해보니 그럴수도 있겠다는 생각이 드네요. 리팩토링 해보겠습니다.
2. 이 부분에 대해서 고민이 좀 많았습니다. 배팅 금액을 저장만 해놓는 객체를 따로 만드려니, 뭔가 그 객체의 존재가 무의미하게 느껴졌던 것 같습니다. 어차피 계산은 Referee에서 하는데 아예 저장을 Referee가 하면 더 깔끔하지 않을까 생각했었습니다. 좀 더 역할을 철저하게 나눈다는 의미로 말씀해주신 것처럼 리팩토링 해보겠습니다!

2023-03-13 03:38 UTC, tjdtls690 commented on src/main/java/Application.java
> +        blackJackGame.giveCardToParticipantsBy(this::inputCommand, OutputView::printParticipantCardStatus);
메서드에 대해 공부하면서 2종류가 있다고 봤습니다.
1. 빌더 : 리턴 타입이 존재하는 메서드
2. 조정자 : 객체를 수정하는 메서드

해당 메서드는 BlackJAckGame 객체 안에서 배팅 금액을 저장하는 조정자 역할이라고 생각했습니다. 그래서 그에 관한 결과 값을 리턴까지 받게 되면, 너무 많은 책임을 해당 메서드가 가지게 되지 않을까하는 생각이 들었습니다.

그래도 리뷰어님의 의견을 보니, 어차피 하나의 리스트를 주고 출력하는 형식이기 때문에, 굳이 functional interface 까지는 사용하지 않아도 된다고 생각이 드네요. 위의 제 의견에 대한 리뷰어님의 의견이 궁금합니다.

일단 해당 메서드가 바로 리턴하게끔 리팩토링 해보겠습니다!

2023-03-13 04:15 UTC, tjdtls690 commented on src/main/java/domain/game/BlackJackGame.java
> +        players.giveCardToDealerBy(deck, printGiveDealerCardMessage);
아, 오늘 PR 날리면서 질문 드렸던 부분이 이 부분이었습니다! 그래서 딜러가 해당 메서드를 사용할 땐 입력을 받아주는 Functional interface 매개변수에 null을 대신 보내는 것으로 대체 했습니다.

Dealer 의 drawOrFinishBy 메서드 로직에서 이미 리뷰어님이 얘기해주신 것처럼
1. dealer 상태확인
2. 카드분배
3. 출력

와 같은 형식으로 구현 되어있습니다!

여기서 참가자와 딜러에게 카드를 나눠주는 메서드를 나누게 되면, Players 객체에서 Player라는 타입으로 각 플레이어를 조작하고 있기 때문에, 참가자와 딜러 모두 예외만 발생시키면서 안쓰는 메서드가 하나씩 늘어날 것 같았습니다. 그래서 최대한 중복을 줄이고자 이렇게 구현했습니다.

2023-03-13 05:19 UTC, tjdtls690 commented on src/main/java/Application.java
> +        blackJackGame.giveCardToParticipantsBy(this::inputCommand, OutputView::printParticipantCardStatus);
일단 각 플레이어의 순서가 돌아갈 때마다 현재 카드 상태를 출력해줘야 합니다. 그리고 이 메서드의 기능 안에서, 참가자가 어떤 카드를 받는지 그리고 어떤 상태가 되었는지에 따라 현재 카드의 상태를 출력하는 타이밍이 좀 다릅니다.

https://github.com/woowacourse/java-blackjack/pull/546/files#diff-0fc4d7e0b491114a7e5e908f7c0b1eb30ab83acd649728e1db1a9aeb74d226c4R30-R60

그래서 이 메서드로 현재 카드 상태를 리턴 받고 그걸로 OutpuView에 넘겨주는 식으로 리팩토링 하려면, 결국 처음의 로직처럼 다시 참가자들의 리스트를 Application 으로 get한 후, 해당 로직을 전부 Application으로 다시 꺼내야 된다고 생각합니다.

그리고 메서드에 대해 공부하면서 2종류가 있다고 봤습니다.
1. 빌더 : 리턴 타입이 존재하는 메서드
2. 조정자 : 객체를 수정하는 메서드

해당 메서드는 BlackJAckGame 객체 안에서 배팅 금액을 저장하는 조정자 역할이라고 생각했습니다. 그래서 그에 관한 결과 값을 리턴까지 받게 되면, 너무 많은 책임을 해당 메서드가 가지게 되지 않을까하는 생각이 들었습니다.

그래서 제 역량이 아직 부족해서인지, 리팩토링을 어떤 식으로 해야할지 감이 잘 잡히지가 않습니다. 이에 대한 리뷰어님의 의견이 궁금합니다.

2023-03-13 05:22 UTC, tjdtls690 commented on src/main/java/domain/game/BlackJackGame.java
> +        players.giveCardToDealerBy(deck, printGiveDealerCardMessage);
아, 오늘 PR 날리면서 질문 드렸던 부분이 이 부분이었습니다! 그래서 딜러가 해당 메서드를 사용할 땐 입력을 받아주는 Functional interface 매개변수에 null을 대신 보내는 것으로 대체 했습니다.

Dealer 의 drawOrFinishBy 메서드 로직에서 이미 리뷰어님이 얘기해주신 것처럼
1. dealer 상태확인
2. 카드분배
3. 출력

와 같은 형식으로 구현 되어있습니다!

여기서 참가자와 딜러에게 카드를 나눠주는 메서드를 나누게 되면, Players 객체에서는 Player라는 타입으로 각 플레이어를 조작하고 있기 때문에, 참가자와 딜러 모두 예외만 발생시키면서 안쓰는 메서드가 하나씩 늘어날 것 같았습니다. 그래서 최대한 중복을 줄이고자 이렇게 구현했습니다.

이 부분에 대한 리뷰어님의 의견이 궁금합니다.

일단 예외만 발생시키는 메서드가 하나씩 더 생기더라도, 리뷰어님 피드백처럼 딜러와 참가자의 메서드를 나누어서 구현하도록 해보겠습니다.

2023-03-13 05:32 UTC, tjdtls690 commented on src/main/java/domain/card/Score.java
> +    private final int score;
아 그러네요. Number 에서도 일관성있게 스코어 객체로 써줬으면 더 좋았겠네요. 리팩토링 해보겠습니다.

2023-03-13 05:34 UTC, tjdtls690 commented on src/main/java/domain/card/Score.java
> +        this.score = score;
사실 처음엔 음수는 들어올 일이 없다고 생각했어서 지나쳤던 것 같습니다. 근데 다른 사람이 이 메서드를 사용할 때 음수를 집어넣을 수도 있다고 생각한다면, 예외 처리가 꼭 필요하겠네요. 리팩토링 해보겠습니다.

2023-03-13 05:54 UTC, tjdtls690 commented on src/main/java/domain/card/Score.java
> +    }
getScore() 메서드는 출력할때 필요한 메서드입니다. 근데 생각해보니, isSame 메서드는 필요없었네요. 대신 equals를 오버라이딩 하면 되었네요. 그걸로 테스트 코드에서도 getScore()로 꺼내서 비교하는 것보다 isEqialTo 로 해서 객체끼리 비교시켜줘도 되었구요. 리팩토링 해보겠습니다.

comparable 상속해서 compareTo 메서드를 사용하는 것도 좋겠네요! Score안의 모든 비교 메서드를 하나의 메서드로 퉁칠 수도 있다는 생각이 드네요.

그런데 여기서 생각나는 1가지 단점은 compareTo 메서드는 결국 int를 반환해주니, 비교해야할 상황마다 숫자끼리 비교해서 boolean을 반환하는 로직이 한 번 더 필요하다는 것이겠네요.

2023-03-13 05:59 UTC, tjdtls690 commented on src/main/java/domain/player/Participant.java
> +        AddCardCommand command = supplyCommand.apply(this);
그러네요. Application에서만 쓸 땐, command는 입력 값을 매칭해주는 역할로 여겨 View쪽이 더 가까울 거라고 생각했는데, 이제는AddCardCommand의 command를 symbol로 여기고, 도메인에서도 의존해야하는 객체라면 도메인쪽이 더 가깝다고 여길 수 있겠네요.

리팩토링 해보겠습니다.

2023-03-13 06:04 UTC, tjdtls690 commented on src/main/java/domain/player/state/Hit.java
> +        return this;
불변 객체로 만들려면, 같은 클래스라고 해도 아예 다시 만들어줘야겠군요. Hit이랑 Ready 객체 모두 리팩토링 하겠습니다.

2023-03-13 06:46 UTC, tjdtls690 commented on src/main/java/domain/player/state/Ready.java
> +        getHand().addCard(card);
그러네요. 책임을 누구에게 줄지에 대한 고민보단, 로직의 깔끔함을 위해 이렇게 구현했던 것 같습니다. 고민의 방향성 자체가 잘못되었다는 생각이 드네요. 리팩토링 해보겠습니다!

2023-03-13 06:54 UTC, tjdtls690 commented on src/main/java/view/OutputView.java
> +    private static String parsePlayersResult(BlackJackGame blackJackGame, Referee referee) {
BlackJackGame과 Player의 비즈니스 로직 중요도가 다르기 때문이군요. 그러한 관점에선 생각해보지 못했었던 것 같습니다. 리팩토링 해보겠습니다!

2023-03-13 06:58 UTC, tjdtls690 commented on src/main/java/Application.java
> +        blackJackGame.giveCardToParticipantsBy(this::inputCommand, OutputView::printParticipantCardStatus);
일단 각 플레이어의 순서가 돌아갈 때마다 현재 카드 상태를 출력해줘야 합니다. 그리고 이 메서드의 기능 안에서, 참가자가 어떤 카드를 받는지 그리고 어떤 상태가 되었는지에 따라 현재 카드의 상태를 출력하는 타이밍이 좀 다릅니다.

https://github.com/woowacourse/java-blackjack/pull/546/files#diff-0fc4d7e0b491114a7e5e908f7c0b1eb30ab83acd649728e1db1a9aeb74d226c4R31-R66

그래서 이 메서드로 현재 카드 상태를 리턴 받고 그걸로 OutpuView에 넘겨주는 식으로 리팩토링 하려면, 결국 처음의 로직처럼 다시 참가자들의 리스트를 Application 으로 get한 후, 해당 로직을 전부 Application으로 다시 꺼내야 된다고 생각합니다.

그리고 메서드에 대해 공부하면서 2종류가 있다고 봤습니다.
1. 빌더 : 리턴 타입이 존재하는 메서드
2. 조정자 : 객체를 수정하는 메서드

해당 메서드는 BlackJAckGame 객체 안에서 배팅 금액을 저장하는 조정자 역할이라고 생각했습니다. 그래서 그에 관한 결과 값을 리턴까지 받게 되면, 너무 많은 책임을 해당 메서드가 가지게 되지 않을까하는 생각이 들었습니다.

그래서 제 역량이 아직 부족해서인지, 리팩토링을 어떤 식으로 해야할지 감이 잘 잡히지가 않습니다. 이에 대한 리뷰어님의 의견이 궁금합니다.

2023-03-13 07:00 UTC, tjdtls690 commented on src/main/java/Application.java
> +        blackJackGame.giveCardToParticipantsBy(this::inputCommand, OutputView::printParticipantCardStatus);
일단 각 플레이어의 순서가 돌아갈 때마다 현재 카드 상태를 출력해줘야 합니다. 그리고 이 메서드의 기능 안에서, 참가자가 어떤 카드를 받는지 그리고 어떤 상태가 되었는지에 따라 현재 카드의 상태를 출력하는 타이밍이 좀 다릅니다.

https://github.com/woowacourse/java-blackjack/pull/546/files#diff-0fc4d7e0b491114a7e5e908f7c0b1eb30ab83acd649728e1db1a9aeb74d226c4R31-R61

그래서 이 메서드로 현재 카드 상태를 리턴 받고 그걸로 OutpuView에 넘겨주는 식으로 리팩토링 하려면, 결국 처음의 로직처럼 다시 참가자들의 리스트를 Application 으로 get한 후, 해당 로직을 전부 Application으로 다시 꺼내야 된다고 생각합니다.

그리고 메서드에 대해 공부하면서 2종류가 있다고 봤습니다.
1. 빌더 : 리턴 타입이 존재하는 메서드
2. 조정자 : 객체를 수정하는 메서드

해당 메서드는 BlackJAckGame 객체 안에서 배팅 금액을 저장하는 조정자 역할이라고 생각했습니다. 그래서 그에 관한 결과 값을 리턴까지 받게 되면, 너무 많은 책임을 해당 메서드가 가지게 되지 않을까하는 생각이 들었습니다.

그래서 제 역량이 아직 부족해서인지, 리팩토링을 어떤 식으로 해야할지 감이 잘 잡히지가 않습니다. 이에 대한 리뷰어님의 의견이 궁금합니다.

2023-03-13 07:01 UTC, tjdtls690 commented on src/main/java/domain/player/Participant.java
> +        AddCardCommand command = supplyCommand.apply(this);
그러네요. Application에서만 쓸 땐, command는 입력 값을 매칭해주는 역할로 여겨 View쪽이 더 가까울 거라고 생각했는데, 이제는AddCardCommand의 command를 symbol로 여기고, 도메인에서도 의존해야하는 객체라면 도메인쪽이 더 가깝다고 여길 수 있겠네요.

위치를 Domain으로 옮기겠습니다.

2023-03-13 13:51 UTC, lowoon commented on src/main/java/domain/game/BlackJackGame.java
> +        players.giveCardToDealerBy(deck, printGiveDealerCardMessage);
딜러만의 기능, 플레이어만의 기능이 생겨난다면 같은 객체로 볼 수 있을지 고민해보면 될것 같구요.
해당 메서드를 abstract 메서드로 빼야하나요??

2023-03-13 14:02 UTC, lowoon commented on src/main/java/Application.java
> +        blackJackGame.giveCardToParticipantsBy(this::inputCommand, OutputView::printParticipantCardStatus);
말씀하신 것처럼 각각의 player마다 결과를 출력해야하기 때문에 넘길 수밖에 없겠네요...
그렇다고 한다면 list를 가지고 있는 players까지만 functional interface가 전달되도록 로직을 만들 수 있지 않을까요??
그래야 순회를 하면서 function들이 어떠한 순서로 동작하는지 파악이 쉬울 것 같아서요!
위에서 말씀드린 것처럼 이 방식을 통해 역할과 책임을 분리할 수 있겠지만 그만큼 로직의 복잡성은 올라갈 수 있습니다!
이 부분을 어떻게 잘 조율할 수 있을지 사용하시면서 고민해보시면 좋을것 같아요!

2023-03-13 14:02 UTC, lowoon commented on src/main/java/domain/card/Score.java
> +    }
네 맞습니다! comparable은 개발자의 취향차이 혹은 성향차이일 수 있어서 참고용으로만 말씀드렸어요~

2023-03-13 14:27 UTC, lowoon requested changes
고생하셨어요. 아벨! 리뷰 반영 잘 해주셨어요! 😄 
몇 가지 코멘트 남겼으니 확인해주세요ㅎㅎ
궁금한 점은 언제든지 DM이나 코멘트 남겨주세요 :)

2023-03-13 14:27 UTC, lowoon commented on src/main/java/Application.java
>      public void startGame() {
굳이 startGame으로 묶을 필요 없이 main 메서드에 넣어도 되지 않을까요??

2023-03-13 14:27 UTC, lowoon commented on src/main/java/domain/card/Hand.java
> +    private Score score() {
score라고 하면 get의 느낌인거 같은데 점수를 계산한다 라는게 더 명확하지 않을까요??

2023-03-13 14:27 UTC, lowoon commented on src/main/java/domain/player/Players.java
> +        return players.stream()
대부분의 로직이 딜러와 players가 따로 찾아서 돌게된다면 delaer와 participants를 따로 관리하는 것도 고려해볼 수 있을 것 같아요!

2023-03-13 14:27 UTC, lowoon commented on src/main/java/domain/card/Hand.java
> +    public boolean isNotEnoughInitCardsCount() {
테스트에서만 사용되는 메서드인데요.
production code에 테스트용 메서드가 있는 것은 괜찮을까요??

2023-03-13 14:27 UTC, lowoon commented on src/main/java/domain/player/state/Ready.java
> +        getHand().addAllCard(firstCard, secondCard);
getHand를 하기보다 state를 상속받는 모든 객체에서 hand가 필요하다면 hand 를 protected로 만들 수 있지 않을까요??

2023-03-13 14:27 UTC, lowoon commented on src/main/java/domain/player/state/Ready.java
> +    public State drawStart() {
drawStart라고 해서 draw하는 메서드인 줄 알았는데요.
play처럼 게임 시작의 메서드명이 더 명확하지 않을까요?

2023-03-13 14:27 UTC, lowoon commented on src/main/java/domain/card/Hand.java
> +    private static final Score BLACKJACK = new Score(21);
blackJackScore를 hand에서 관리하고 있는데요.
score에서 min,max로 값을 관리하는 것이 맞을까요??
현재는 블랙잭에서만 쓰이지만 다른 game들에서도 점수가 사용된다면 어떻게 될까요??

2023-03-13 14:27 UTC, lowoon commented on src/main/java/domain/game/Referee.java
> +    public void saveBattleResults(BlackJackGame blackJackGame) {
referee가 blackJackGame을 받는 것이 맞을까요??
players만 받으면 되지 않나요??
이전에도 blackJackGame을 넘기는 경우가 있었는데요.
게임의 흐름을 담당하는 blackJackGame이 중심을 잡고 이곳으로 다른 객체에서 요청을 보내는 형식이 맞지 않을까요??
객체의 역할과 책임, 메세지를 보내라, 비지니스 로직에 대해서 고민해보시면 좋을것 같아요!

2023-03-13 14:27 UTC, lowoon commented on src/main/java/domain/game/Referee.java
> +        if (participant.isBust() || dealer.isBust()) {
딜러와 participant 모두 bust인 경우 딜러의 승인데 해당 로직이 맞을까요??

2023-03-17 05:47 UTC, tjdtls690 commented on src/main/java/Application.java
>      public void startGame() {
뭔가 게임을 시작한다는 의미에서 저 메서드가 필요하겠다고 생각했었습니다. 근데 어차피 main메서드에서 시작하는 걸 안다면, 필요 없을 수도 있겠네요. 리팩토링 하겠습니다.

2023-03-17 05:58 UTC, tjdtls690 commented on src/main/java/domain/player/Players.java
> +    private final BetAmounts betAmounts;
일단 Player가 가지게 하기엔, 이미 Player는 2개의 인스턴스 필드를 가지고 있어서 하나 더 추가를 하기가 꺼려졌습니다. 그리고 Players 에서 최대한 배팅 금액 저장에 대한 책임을 일급 콜렉션으로 위임하려고 BetAmounts 객체로 포장한건데, 지금 다시 보니 Map의 역할과 다를바가 없네요.

그냥 Map을 가지고 있는 것으로 리팩토링 해보겠습니다!

2023-03-17 08:17 UTC, tjdtls690 commented on src/main/java/Application.java
> +        blackJackGame.giveCardToParticipantsBy(this::inputCommand, OutputView::printParticipantCardStatus);
Participant까지 들어가야 Player에서 구현한 메서드들을 바로 사용할 수 있어서 그렇게 구현했던 것 같습니다. 그러면 메서드의 파라미터 수 1개를 줄일 수 있기 때문입니다.

그런데 Players에서 돌게 되면, 각 private 메서드에 player도 넘겨줘야 하기 때문에 각 메서드의 파라미터 수가 4개가 됩니다. 이것을 구현했을 당시엔 이러한 생각때문에 Player까지 해당 로직을 넘겨줬던 것 같습니다.

이 부분에 대한 리뷰어님의 의견이 궁금합니다!

일단 Players에서 돌면서 해당 로직을 사용하도록 리팩토링 해보겠습니다.

2023-03-17 08:27 UTC, tjdtls690 commented on src/main/java/Application.java
> +        blackJackGame.settingBetAmountToParticipantsBy(this::inputBetAmount);
그러네요. '참가자들이 배팅한다' 라는 의미로 개선해보겠습니다.

2023-03-17 08:28 UTC, tjdtls690 commented on src/main/java/domain/card/Hand.java
> +    private Score score() {
그러네요. 어차피 score를 구하는 것이니, score로 개선했었는데, score를 그대로 반환하는 것이 아니기 때문에 계산한다 라는 뜻을 집어넣는게 더 낫겠네요. 리팩토링 해보겠습니다!

2023-03-18 05:34 UTC, tjdtls690 commented on src/main/java/domain/card/Hand.java
> +    public boolean isNotEnoughInitCardsCount() {
리팩토링 하면서 쓸모가 없어진 메서드를 알아채지 못했네요. 제거하겠습니다.

2023-03-18 05:39 UTC, tjdtls690 commented on src/main/java/domain/player/state/Ready.java
> +        getHand().addAllCard(firstCard, secondCard);
필드의 접근제한자는 무조건 private으로 해야 안전하다는 생각이 있었던 것 같습니다. protected는 같은 패키지 내에선 바로 접근이 가능하다는 점에서 사용하기가 좀 꺼려졌었습니다.

그런데 계속 고민해보니, 패키지 구조를 애초에 잘 나눠서 잡아둔다면, 안전성과 효율성 2가지를 전부 잡을 수도 있겠다는 생각이 드네요. 리팩토링 해보겠습니다.

2023-03-18 05:42 UTC, tjdtls690 commented on src/main/java/domain/player/state/Ready.java
> +    public State drawStart() {
이제부터 draw를 시작한다는 의미에서 사용한 건데, 오해가 생길 수 있는 메서드 명이겠네요. 개선해보겠습니다.

2023-03-18 12:56 UTC, tjdtls690 commented on src/main/java/domain/game/Referee.java
> +    public void saveBattleResults(BlackJackGame blackJackGame) {
OutputView에서 저번에 BlackJackGame을 넘겨줬던 것으로 기억합니다. Referee도 같이 리팩토링을 했었어야 했는데 놓쳤네요. 리팩토링 하겠습니다.

2023-03-18 13:13 UTC, tjdtls690 commented on src/main/java/domain/game/Referee.java
> +        if (participant.isBust() || dealer.isBust()) {
이 부분은 3가지의 경우에서 전부 맞게 로직이 돌아가고 있습니다.
참가자가 100원을 배팅했다고 가정해보면,

1. 딜러만 버스트인 경우
    - 참가자의 상태가 Stay인 상태이기 때문에, Player의 calculateProfit() 메서드에서 100원을 그대로 반환하도록 계산합니다. 따라서 100원이 참가자의 수익금으로 들어갑니다.
2. 참가자만 버스트인 경우
    - 참가자의 상태가 Bust인 상태이기 때문에, participant의 calculateProfit() 메서드에서 -100원을 반환하도록 계산합니다. 따라서 -100원이 참가자의 수익금으로 들어갑니다.
3. 참가자, 딜러 둘 다 버스트인 경우
     - 위의 2번의 경우와 똑같이 계산합니다. 참가자의 상태가 Bust인 상태이기 때문에, participant의 calculateProfit() 메서드에서 -100원을 반환하도록 계산합니다. 따라서 -100원이 참가자의 수익금으로 들어갑니다.

여기서 딜러는 참가자가 받은 수익금을 그대로 곱하기 -1을 해서 더하게 구현해놓았습니다.

2023-03-18 13:14 UTC, tjdtls690 commented on src/main/java/domain/game/Referee.java
> +        if (participant.isBust() || dealer.isBust()) {
이 부분은 3가지의 경우에서 전부 맞게 로직이 돌아가고 있습니다.
참가자가 100원을 배팅했다고 가정해보면,

1. 딜러만 버스트인 경우
    - 참가자의 상태가 Stay인 상태이기 때문에, Player의 calculateProfit() 메서드에서 100원을 그대로 반환하도록 계산합니다. 따라서 100원이 참가자의 수익금으로 들어갑니다.
2. 참가자만 버스트인 경우
    - 참가자의 상태가 Bust인 상태이기 때문에, participant의 calculateProfit() 메서드에서 -100원을 반환하도록 계산합니다. 따라서 -100원이 참가자의 수익금으로 들어갑니다.
3. 참가자, 딜러 둘 다 버스트인 경우
     - 위의 2번의 경우와 똑같이 계산합니다. 참가자의 상태가 Bust인 상태이기 때문에, participant의 calculateProfit() 메서드에서 -100원을 반환하도록 계산합니다. 따라서 -100원이 참가자의 수익금으로 들어갑니다.

여기서 딜러는 참가자가 받은 수익금을 그대로 마이너스를 해서 더하게 구현해놓았습니다.

2023-03-18 13:46 UTC, lowoon commented on src/main/java/Application.java
> +        blackJackGame.settingBetAmountToParticipantsBy(this::inputBetAmount);
객체를 정의함으로써 역할과 책임을 가지게 되고 그 역할과 책임에 맞게 행동(method)을 하게 되죠.
객체를 이야기 할 때 주도성과 의인화를 많이 얘기하는데요.
> 객체지향 세계에서는 모든 것이 능독적이고 자율적인 존재로 바뀐다.
레베카 워프스브록은 능동적이고 자율적인 존재로 소프트웨어 객체를 설계하는 원칙을 가리켜 의인화(anthropomorphism)라고 한다.
훌룡한 객체지향 설계란 소프트웨어를 구성하는 모든 객체들이 자율적으로 행동하는 설계를 가리킨다.

2023-03-18 14:33 UTC, lowoon approved these changes
안녕하세요 아벨!😄
이제 그만 블랙잭 미션을 마무리해도 될 것 같아요.
간단한 코멘트만 남겼으니 확인 부탁드려요.
미션은 끝났지만 궁금한점 있으면 DM이나 코멘트로 남겨주세요!

1, 2단계 블랙잭 미션 수고하셨습니다!

2023-03-18 14:33 UTC, lowoon commented on src/main/java/domain/player/Players.java
> +    public Player dealer() {
get을 안붙인 이유가 있나요??

2023-03-18 14:33 UTC, lowoon commented on src/main/java/domain/player/Players.java
> +        AddCardCommand command = supplyCommand.apply(player);
```java
        while(!player.isFinished() && supplyCommand.apply(player).isAddCardCommand()) {
            player.draw(deck.draw());
            printParticipantCardStatus.accept(List.of(player));
        }

        player.drawStop();

```
이렇게도 될거 같기는 하네요

2023-03-18 14:33 UTC, lowoon commented on src/main/java/Application.java
> +        blackJackGame.giveCardToParticipantsBy(this::inputCommand, OutputView::printParticipantCardStatus);
2가지가 생각나는데요.
1. 이 부분의 역할과 책임을 blackJackGame이 가지고 있다고 생각하여 blackJackGame에서 `Players.getPlayers()`해서 로직을 돌도록 할 수도 있을 것 같구요.
2. input과 output 부분을 객체로 묶을 수도 있을 것 같네요. 

저는 participants와 dealer의 기능이 다른 경우가 많아서 players로 묶어야하나라는 생각이 들어요.
오히려 participants만 묶을 수는 있을 것 같구요.
**개인적인 의견입니다~** 
저는 participants에게 안넘기고 blackJackGame에서 추가 분배한다라고 역할과 책임을 주어서 players까지 넘기지 않을 것 같아요!
비지니스 로직을 담당하기때문에 중간자 역할로써 위임한 동작을 받을 수 있지만 도메인까지 넘기는게 맞을까에 대해서 고민이라서요.
비지니스 로직을 담당하는 객체에서 생성한 도메인(전략패턴 등)이 아닌 상위의 객체에서 위임받은 동작이니까요.

2023-03-18 14:34 UTC, merged

2023-03-21 06:09 UTC, tjdtls690 commented on src/main/java/domain/game/BetAmounts.java
> +public class BetAmounts {
으아.. 놓쳤네요. 삭제하겠습니다!

2023-03-21 06:12 UTC, tjdtls690 commented on src/main/java/domain/player/BlackJackSystem.java
> +    private final Map<Player, Double> betAmounts;
리마인드 하기 위해 제가 알고있는 바를 다시 정리해보자면, 
3개 이상 인스턴스를 가지지 않도록 하는 이유는 하나의 클래스가 너무 많은 책임을 갖게 되는 것을 방지하고자 하는 것이고, 
getter를 쓰지 않는 이유는, 내부 데이터가 노출되어 값이 변경되거나, 내부의 로직과 동일한 중복 로직이 외부에도 생기는 것을 방지하고자 하는 것으로 알고 있습니다.

지금 리마인드 해보면서 다시 정리해보니, 위의 이유에 걸리는 지 안 걸리는지 먼저 합리적으로 판단한 후, 유연한 대처를 할 수도 있겠다는 생각이 드네요. 새로운 관점을 알려주셔서 감사합니다!!

2023-03-21 06:22 UTC, tjdtls690 commented on src/main/java/domain/player/Players.java
> +    public Player dealer() {
인텔리제이를 사용하면서 get 을 붙이는 대신, Records style 로 설정을 해서 get을 안붙이면서 사용하고 있습니다.

이렇게 쓰는 가장 큰 이유는, 솔직히 말장난처럼 느껴질 수도 있지만,

get을 붙이면 해당 객체의 필드를 그대로 가져온다는 느낌을 줍니다. 반면 get을 안붙이고 명사만으로 표현하게 된다면, 해당 메서드 안에서 어떤 로직을 거치고 가공되어서 나오는 데이터인지, 필드가 그대로 반환되어 나오는 데이터인지 알기 쉽지 않다고 생각되었습니다.

또한 get을 붙이면, 해당 객체를 너무 도구로만 보면서 "OO 가져와" 라는 의미가 강하게 느껴진다면, 명사만으로 표현을 하면, 객체를 주체적인 존재로 보면서 "OO가 필요한데, 너가 알아서 내가 원하는 데이터를 보내줘" 라는 의미가 좀 더 강하게 느껴졌습니다.

2023-03-21 06:33 UTC, tjdtls690 commented on src/main/java/domain/player/Players.java
> +        AddCardCommand command = supplyCommand.apply(player);
이것도 플레이어가 드로우 한 후, Bust 상태가 되면 drawStop() 사용 시 예외가 발생하게 되는 것 같습니다.

근데 이 부분이 확실히 가독성이 좀 많이 떨어진다는 느낌이 드네요... 최대한 깔끔하게 구현해보려 해도, 입력한 값과 draw 후의 상태 그리고 현재 Hand 상태를 출력해야할 타이밍, 이 3가지를 전부 고려하기가 좀 어렵게 느껴지는 것 같습니다.

리뷰어님이 작성해주신 것처럼 while문을 사용하는 것도 고려를 해봐야겠네요. while문을 쓰는 것에 대해 depth가 증가하면서 막연하게 가독성이 떨어진다고 인식하고 있었던 것 같습니다.

더 고민해보면서 리팩토링 해보겠습니다!

2023-03-21 07:03 UTC, tjdtls690 commented on src/main/java/Application.java
> +        blackJackGame.giveCardToParticipantsBy(this::inputCommand, OutputView::printParticipantCardStatus);
이 부분에서 저번에 DM으로 나눴던 내용인, 위임의 의도에 따라 합리적 판단을 해야하는 경우에 포함될 수 있겠네요. 그리고 로운의 의견을 보니, BlackJackGame의 역할과 책임에 대한 부분을 좀 더 고민해봐야겠다는 생각이 드네요.

의견 주셔서 정말 감사합니다!

2023-03-21 07:04 UTC, tjdtls690 commented on src/main/java/domain/player/Players.java
> +            drawOrFinishParticipantBy(participant, deck, supplyCommand, printParticipantCardStatus);
아 이 부분을 통일시켜주지 못했네요. 리팩토링 하겠습니다!

그런데 통일을 시켜주는 것이 좋을 것이란 생각은 들지만, 넘기는 변수명과 받는 파라미터명이 다르다고 오류가 발생하는 경우는 없었어서 잘 이해가 가지 않습니다.

혹시 간단하게라도 오류가 나는 케이스를 알려주실 수 있나요?? @lowoon

2023-03-21 07:05 UTC, tjdtls690 commented
블랙잭 미션 꼼꼼하게 리뷰해주셔서 정말 감사합니다! 덕분에 선입견 몇 개를 버리면서 새로운 관점을 넓힐 수 있는 계기가 되었습니다. @lowoon