[2단계 - 블랙잭(베팅)] 로지(윤가영) 미션 제출합니다.
woowacourse/java-blackjack pull request #550
Opened 2023-03-12 02:05 UTC by kyY00n

안녕하세요 소니!
1단계 피드백 주신 부분을 마저 수정하고 2단계 기능 구현을 해봤습니다.
다음은 구현하면서 드리고 싶었던 질문들입니다.
부족한 부분이 많을텐데 따끔하게 짚어주세요.
감사합니다!

1. 2단계에서는 승패 결과를 보여주는 기능이 제거됐는데, 이럴 경우 없어진 기능을 구현한 부분을 다 삭제하고 기능 구현을 시작하는 게 좋을 지 궁금했습니다.
  - 저는 먼저 삭제하지 않고 추가된 기능을 구현했는데, 승패 결과 기능을 지울 때 제가 확실히 지웠는지 헷갈렸습니다.
  - 저는 컨트롤러에서부터 기능을 지워 사용하지 않는 도메인의 로직이더라도 테스트 코드가 있기 때문에 ide에서 쓰이지 않는 로직을 쉽게 찾는 것이 헷갈렸습니다.
  - 만약 다른 사람이 작성한 코드가 있었다면 분명히 놓치고 삭제하지 못한 부분이 있었을 것 같기도 합니다.
2. 이제 사라진 기능이긴 하지만, 승패 결과를 계산하는 기능에 질문이 있어 1단계 PR에 [커멘트를](https://github.com/woowacourse/java-blackjack/pull/471#discussion_r1130397265) 남겨놓았습니다. 
3. Controller에서 카드를 더 받는 기능을 구현하며 Players를 통하지 않고 직접 Player에 접근하는 원래의 로직에서 인덱스를 사용하지 않는 방법으로 동작 파라미터화를 사용했습니다. 카드를 더 받을지 결정하는 동작과 현재 패를 보여주는 동작을 컨트롤러에서 정의해서 넘겨주는 방식을 사용했고 문제를 해결했어요. 하지만 이를 위해 Player까지 동작을 전달해주는 것 자체가 복잡해 이 방법이 맞는 것일까 고민을 시작하게 되었습니다. 또한 도메인에서 해당 방식을 받는것이 MVC 패턴에 위배되는 것일까라는 생각이 들었습니다. 소니의 생각이 궁금합니다.
  **수정 전**
    ```java
    class Controller {
        private void playersHit() {
            for (int i = 0; i < blackjackGame.countPlayer(); i++) {
                Name userName = blackjackGame.findUserNameByIndex(i);
                playerHit(i, userName);
            }
        }
        private void playerHit(int i, Name userName) {
            String command = inputView.readCommandToAddCardOrNot(userName);
    
            while (AddCardOrNot.of(command).equals(YES) && !blackjackGame.isBust(i)) {
                blackjackGame.supplyAdditionalCard(i);
                ParticipantCardsDto playerCard = blackjackGame.getPlayerCardsByIndex(i);
                outputView.printPlayerCard(playerCard);
                if (blackjackGame.isBust(i)) {
                    break;
                }
                command = inputView.readCommandToAddCardOrNot(userName);
            }
        }
    }
    ```
    **수정 후**
    ```java
    class Controller {
        private void supplyAdditionalCards() {
            blackjackGame.supplyAdditionalCardToPlayersBy(this::readAddOrNot, this::showCurrentCards);
            blackjackGame.supplyAdditionalCardToDealerAnd(ignore -> outputView.printDealerHitMessage());
        }
    }
    ```
    ```java
    class Player {
        // 컨트롤러 -> BlackjackGame -> Players 를 거쳐 동작을 전달받아야 함
        public void hitAdditionalCardFrom(Deck deck, CardDecisionStrategy cardDecisionStrategy,
                                      CardDisplayStrategy cardDisplayStrategy) {
        while (!isBust()) {
            AddCardOrNot addCardOrNot = cardDecisionStrategy.decide(this);
            if (addCardOrNot.equals(NO)) {
                break;
            }
            hit(deck.drawCard());
            cardDisplayStrategy.display(this);
        }
    }
    }
    ```

2023-03-12 13:59 UTC, sonypark requested changes
안녕하세요 로지, 리뷰어 소니 입니다.😊
배팅금액 기능 추가까지 잘 적용된것 확인했습니다.
질문 주신 부분과 함께 코드상에 개선포인트 코멘트 남겼으니 확인부탁드려요~

> 없어진 기능을 구현한 부분을 다 삭제하고 기능 구현을 시작하는 게 좋을 지

네 필요하지 않은 코드라면 삭제해주시면 됩니다. 게임 결과를 출력하는게 승/패 -> 상금 으로 변경되어 승/패 로직은 삭제해주시면 될 것 같습니다. 로지의 질문 의도는 사용하지 않는 코드가 삭제되지 않고 남아있는 경우에 대한 우려와 어떻게 사용유무를 확인하고 삭제할지를 말씀하신것 같기도 해서 추가 코멘트 드리자면, IDE에서 제공하는 Find Usage 기능을 사용하면 해당 클래스/메서드를 사용하는 곳을 알 수 있습니다. (단축키: (`option+F7` 또는 `option+cmd+F7`) 이렇게 확인후 사용하는 곳이 없는 걸 확인 후 삭제해주는것도 방법입니다.

2023-03-12 13:59 UTC, sonypark commented on src/main/java/blackjack/controller/Controller.java
> +        showPrize();
아래 역할을 Player 도메인까지 전달해주는 것에 대한 고민을 말씀주셨는데요.
- 카드를 더 받을지 결정하는 동작
- 현재 패를 보여주는 동작

로지가 이상하다고 생각한 부분이 맞습니다. 위 역할은 모두 view와 관련된 역할이라 도메인 로직까지 넘어갈 이유는 없다고 생각합니다. 아래 코드 참고하여 리팩토링 할 수 있을까요?

```java
	private void continueAddIfPlayersWantCard() {
		players.forEach(this::addCardIfWant);
	}

	private void addCardIfWant(Player player) {
		while (player.canAddCard(AddCardOrNot.of(입력값).isYes()) {
                          // deck에서 player에게 카드 전달
                         // OutputView.printCards();  플레이어의 카드 출력
		}
	}
```

2023-03-12 13:59 UTC, sonypark commented on src/main/java/blackjack/domain/participant/PlayerFinalState.java
> +        }
숫자만 코드에 그대로 넣는 '매직넘버'는 최대한 지양해주세요. 상수로 빼서 어떤 숫자인지 네이밍을 붙여주시면 좋을 것 같습니다. :)

2023-03-12 13:59 UTC, sonypark commented on src/main/java/blackjack/domain/Money.java
> +
Money 객체를 만드시 이유가 있을까요?
현재로서는 따로 검증로직이 없고 원시값을 사용하는것과 차이점이 없는것 같아 질문드립니다 :)

2023-03-13 06:16 UTC, kyY00n commented on src/main/java/blackjack/controller/Controller.java
> +        showPrize();
소니 제가 지금 Player 의 일급 컬렉션인 Players 를 정의하고 있고, player 각각의 동작을 처리하는 책임을 Players에 부여하고 있습니다.
그런데 Players도 BlackjackGame이라는 도메인 클래스에 속하고 있어요. 지금 구조에서 컨트롤러가 Players에도 접근하지 못합니다.

따라서 소니가 작성해주신 코드와 같이 작성을 하기 위해서는 Players에서 Player 리스트를 가져오고, Game에게 전달을 하고 Game이 그것을 컨트롤러에게 전달을 하는 코드를 만들어야합니다.
그런데 제가 지금까지 Player의 모든 동작을 그 스스로가 할 수 있게 만들기 위해 getter를 만들지 않고 다른 객체를 통해서(Controller->Game->Players->Player) 메시지를 보내는 방법을 택했는데, 이 기능은 그럴 수 없는걸까요?

다시 생각해보면, player에게 컨트롤러가 직접 메시지를 보낼 수도 있는 건데 제가 편협한 사고를 가지고 있는걸까요?

처음에는 Game안에 있는 Deck, Dealer, Player 의 모든 행동이 컨트롤러에서 직접 호출이 되면 안된다는 생각을 했어요.
Deck, Dealer, Player가 게임의 진행과 상관없이 어느 동작이나 할 수 있으면 안된다고 생각했기 때문입니다.
그런데 정작 Game도 도메인 객체인데 그건 컨트롤러가 실행하는게 당연한 것처럼 여기고 진행했어요.

그렇다면 Player를 컨트롤러에 노출 시키는 건 Game 을 다루듯 당연한 것인가? 라는 궁금증이 듭니다.
또한 Player를 그렇게 컨트롤러에서 직접 다루었을 때 생기는 단점은 없을지 어떤 키워드로 찾아봐야할지 모르겠다는 생각이 들었습니다.

이 과정에서 Game과 Player가 정말 같은 도메인 모델의 역할을 하고 있는 것인가에 대한 의문도 들었어요...
질문이 너무 많은 것 같아 죄송해요. 제가 어떤 부분을 잘못생각하고 있는지 정확히 알지 못해서 그런 것같습니다. 

이번 미션을 하는 내내 오개념을 가지고 있었던 것 같아 혼란스럽고 많이 아쉽습니다..ㅜ

일단은 게터를 가지고 고쳐보겠습니다..! 의견 주시면 감사하겠습니다.

2023-03-13 06:23 UTC, kyY00n commented on src/main/java/blackjack/domain/Money.java
> +
다시 생각해보니, 지금 코드에선 Money를 정의할 필요가 없는 것 같습니다.
처음 요구사항을 보고 Money를 검증할 로직이 필요하다 생각해(음수이면 안된다 생각했어요.) 값객체로 정의했지만, 요구사항을 잘못 파악했다는 걸 알고 검증로직을 지우게되었고 지금 상태가 된것 같습니다.
필요 없는 객체라는 생각이 들어 이번에 제거해보겠습니다. 짚어주셔서 감사합니다😃

2023-03-13 06:32 UTC, kyY00n commented on src/main/java/blackjack/domain/Money.java
> +
앗 그런데 모든 원시값을 포장하라는 요구사항 때문에 남겨놓는 것이 좋을 것 같습니다!! 하지만 원시값을 사용하는 것과 큰 차이가 없다는걸 인지하도록 하겠습니다!

2023-03-13 07:49 UTC, kyY00n commented on src/main/java/blackjack/controller/Controller.java
> +        showPrize();
소니, 제가 고민을 해봤는데 좋은 방법이 떠오르지 않습니다.
소니가 주신 힌트를 구현하기 위해서 게터를 사용하는 것 외에는 어떤 걸 사용해야할지 모르겠습니다.

게터를 사용하는 것은 고민을 해봤지만 새로운 문제가 발생하는 것 같다는 생각이 들었습니다.

- 컨트롤러에서 플레이어에게 카드를 더 받을 수 있는지 물어보고, 카드를 받도록 하는 모든 로직이 블랙잭게임의 규칙입니다. 따라서 컨트롤러가 도메인로직을 수행하게 되는 것이라고 생각합니다.
  - 비슷하게, player 리스트의 게터를 만드는 순간 player에 대한 모든 기능을 컨트롤러에서 수행할수 있는 것이라 생각했습니다.

소니의 의견에는 공감이 되지만 제가 느끼기에 올바르지 않은 방향으로 무작정 리팩터링을 하는 것도 좋지 않은 것 같아 질문을 먼저 드리게 되었습니다.

2023-03-13 15:35 UTC, sonypark approved these changes
안녕하세요 로지, 리뷰어 소니 입니다.😊
고민 남겨주신 부분에 대해 저의 생각도 남겨보았습니다.
읽어보시고 의견 주시면 감사하겠습니다!
2단계는 여기서 approve할게요. 고생 많으셨어요!

2023-03-13 15:35 UTC, sonypark commented on src/main/java/blackjack/controller/Controller.java
> +        showPrize();
`Player의 모든 동작을 그 스스로가 할 수 있게 만들기 위해 getter를 만들지 않고 다른 객체를 통해서(Controller->Game->Players->Player) 메시지를 보내는 방법` -> 현재 Player가 하는 모든 동작이 정말 Player의 역할인지 생각해보면 좋을 것 같아요. "카드를 더 받는다"라는 행위를 하기 위해서 현재는 다음과 같은 동작을 하고 있네요.

1. 입력값이 Y/N인지 판단한다
2. Y일 경우 deck에서 카드를 받고 N일 경우 받지 않는다.
3. 카드를 출력한다.

위 세개의 동작이 모두 Player라는 객체에 종속되어 있습니다. 위 동작 중 2번은 Player의 역할이지만 1,3번은 Player가 수행해야할 역할일까요? 1번과 3번은 컨트롤러에서 수행하고 Player는 2번만 수행해도 되지 않을까싶어서 코멘트를 남겼었습니다. :) 

컨트롤러에서 할 수 있는 동작이 Game->Players->Player 를 타고 도메인까지 넘어갈 필요가 있을지, 이 부분은 한 번 고민해보시면 좋을 것 같습니다. 아마 현재 구조에서 변경을 하려면 수정범위가 꽤 있을 것 같은데요. 다음 미션도 진행하셔야 하니 리팩토링을 하지 않으셔도 괜찮습니다. 로지가 고민하는 부분은 충분히 가치있는 고민이고 앞으로도 계속 필요한 고민이기 때문에 다음 미션을 진행하며 적용해주셔도 좋을 것 같습니다. (이렇게 하는게 꼭 맞다라는건 아닙니다. 로지가 구현하신 것도 잘하셨어요. 어떤게 조금 더 객체지향적인 코드일까, 역할과 책임을 분리하고 유지보수가 용이한 코드를 만들 수 있을까에 대한 고민이 중요할 것 같아요. 앞으로도 이러한 생각을 유지하고 공부하며 더 나은 코드를 작성하기 위해 노력하면 좋을 것 같습니다. 저도 로지 덕분에 한 번 더 생각해보게 되었어요. 고마워요!)

```java
	private void continueAddIfPlayersWantCard() {
		players.forEach(this::addCardIfWant);
	}

	private void addCardIfWant(Player player) {
		while (player.canAddCard(AddCardOrNot.of(입력값).isYes()) {
                          // deck에서 player에게 카드 전달
                         // OutputView.printCards(player.getName(), player.getCards()); 플레이어의 카드 출력
		}
	}
```

2023-03-16 02:46 UTC, merged

2023-03-20 15:57 UTC, kyY00n commented on src/main/java/blackjack/controller/Controller.java
> +        showPrize();
소니.. 제가 정말 늦었는데요,
저의 고민에 공감해주시고 다시 풀어서 설명해주셔서 감사합니다.
아쉬운 점이 너무 많은 미션인데도 소니 덕분에 이런 고민 할 수 있어서 재밌었던 것 같아요.

설명해주신 부분은, 저도 소니 의견에 공감하고 그게 맞는 것 같습니다. **꼭 시간 내서 리팩터링 해보겠습니다!** 리뷰 수고하셨습니다 감사해요🥹♥️