[2단계 - 블랙잭(베팅)] 그레이(김동욱) 미션 제출합니다.
woowacourse/java-blackjack pull request #559
Opened 2023-03-12 11:01 UTC by Kim0914

안녕하세요, 바다 🌊
그레이입니다 😀

주말은 잘 보내셨나요?!

1단계에서 받은 피드백을 바탕으로 2단계 미션을 진행했습니다 !

부족한 부분 말씀해주시면 개선하도록 하겠습니다 ~~

감사합니다 ㅎㅎ

## 개선사항

### 컨트롤러에 존재하던 게임 로직 -> BlackJackGame 내부로 이동

바다가 말씀해주신 `현재 코드에서 컨트롤러가 없다면 Game 혼자서 블랙잭 게임을 진행할 수 있을까요?`에 대해 고민을 많이 했습니다..!

그래서 컨트롤러에서 딜러와 플레이어를 가져와서 처리했던 부분을 

컨트롤러에서 메세지를 던져 `BlackJackGame`이 직접할 수 있도록 변경해보았습니다.

바다가 말씀해주신 의도가 이런 방향이 맞는지 궁금합니다 !!!

2023-03-13 05:45 UTC, kong-hana01 reviewed
잘보고 갑니다~

2023-03-13 05:45 UTC, kong-hana01 commented on src/main/java/blackjack/domain/game/BlackJackGame.java
>      private final Participants participants;
BlackJackGame 내에서 'Participants'로 딜러와 플레이어를 묶어주고 있는데, 

메서드 내에서는 Participants 내의 딜러와 플레이어를 각각 getter로 반환해서 사용하고 있네요!

Participants는 `인스턴스 변수는 최대 2개까지만 가질 수 있다`는 요구사항을 지키기 위해서 존재하는 객체인 것 같은데,



딜러와 플레이어를 각각 인스턴스 변수로 뒀을 때의 장단점과 

그레이가 작성했던 것처럼 블랙잭 게임 내에서 participants를 뒀을 때의 장단점으로는 어떤 게 있을까요?

그레이의 생각이 궁금합니다!!!!!😄

2023-03-13 05:45 UTC, kong-hana01 commented on src/main/java/blackjack/domain/game/Result.java
> +    private static Result checkBlackJack(Dealer dealer) {
checkBlackJack이라는 메서드명은 플레이어와 딜러 모두 사용할 수 있을 것처럼 느껴질 것 같아요!

`어떤 상황`에서 `누가 블랙잭인지` 확인하는 로직인지 메서드명에 들어가면 좋을 것 같아요!

아니면 checkBlackJack은 participant 타입을 파라미터로 받고, 

해당 메서드를 조금 더 제너럴하게 사용해보는 건 어떨까요?

그러면 현재 checkBlackJack 메서드가 담당하는 기능을 다른 메서드가 해야겠네요!

2023-03-13 05:45 UTC, kong-hana01 commented on src/main/java/blackjack/controller/BlackJackController.java
> +        List<Name> playerNames = blackJackGame.getPlayerNames();
오호 저는 그레이가 이전에 했던 방법처럼 players를 for-each에서 사용했는데

이름만 전달받아서 사용하는 방법도 있겠군요!

어떤 과정으로 해당 방법을 생각해내셨는지 궁금합니다!

2023-03-13 05:45 UTC, kong-hana01 commented on src/main/java/blackjack/domain/card/Hand.java
> +                .filter(Card::isAce)
직관적이고 좋아요!

2023-03-13 05:45 UTC, kong-hana01 commented on src/main/java/blackjack/domain/game/BettingTable.java
> +        if (!bettingTable.containsKey(name)) {
예외 처리 👍

2023-03-13 05:45 UTC, kong-hana01 commented on src/main/java/blackjack/domain/game/BlackJackGame.java
> +    public Map<Name, Integer> calculatePlayersProfit() {
배팅 결과를 전달할 때 일급 컬렉션으로 전달하지 않은 이유가 있나용?

2023-03-13 05:45 UTC, kong-hana01 commented on src/main/java/blackjack/domain/game/BlackJackGame.java
> +                .collect(Collectors.toUnmodifiableList());
세심한 불변처리 👍 

저도 한번 stream을 사용할 때 그냥 전달하지는 않았는지 점검해야겠어요!

2023-03-13 05:45 UTC, kong-hana01 commented on src/main/java/blackjack/domain/participant/Dealer.java
> +        if (hand.getCount() == 0) {
hand에게 물어보는 건 어떨까요❓

2023-03-13 05:45 UTC, kong-hana01 commented on src/test/java/blackjack/domain/game/BettingTableTest.java
> +                Arguments.of("kong", new Betting(50_000)),
💯

2023-03-13 05:56 UTC, Kim0914 commented on src/main/java/blackjack/domain/game/Result.java
> +    private static Result checkBlackJack(Dealer dealer) {
그렇네요..!
네이밍이 애매한 것 같슴다 😅
반영해볼게요 !

2023-03-13 06:09 UTC, Kim0914 commented on src/main/java/blackjack/controller/BlackJackController.java
> +        List<Name> playerNames = blackJackGame.getPlayerNames();
최대한 블랙잭 게임에게 게임을 관리하는 책임을 주려고 했습니다.

불가피하게 Player와 Dealer를 getter로 사용할 수 밖에 없는 부분만 놔두고, 모두 blackJackGame이 직접 게임에 관여하도록 하자 ! 라는 의도였습니다 !

2023-03-13 06:10 UTC, Kim0914 commented on src/main/java/blackjack/domain/game/BlackJackGame.java
> +    public Map<Name, Integer> calculatePlayersProfit() {
딱히 이유는 없었던 것 같아요...😅

getter로 꺼내서 쓸 것이냐, 불변 객체 betting을 담을 것이냐 고민을 했었는데, key 값을 불변 객체로 담았으니 일관성있게 가는 것이 좋을 것 같네요 !

2023-03-13 06:19 UTC, kong-hana01 commented on src/main/java/blackjack/domain/game/BlackJackGame.java
> +    public Map<Name, Integer> calculatePlayersProfit() {
저도 사실 일급 컬렉션이 아닙니다 👍

2023-03-13 12:09 UTC, xrabcde requested changes
안녕하세요 그레이 ~ 바다입니다 🌊
벌써 누군가가 리뷰를 다녀갔군요 (???!) 
프로그램을 실행해보니 블랙잭인 경우 추가 턴 없이 다음 순서가 진행되도록 잘 구현해주셨네요 💯
몇 가지 리뷰 남겼는데 확인해보시고 궁금한 점은 언제든 코멘트나 DM으로 알려주세요~

2023-03-13 12:09 UTC, xrabcde commented on src/test/java/blackjack/domain/game/BettingTest.java
> +    @DisplayName("배팅 금액 허용 범위와 다르면 예외가 발생한다.")
경곗값을 테스트해주면 좋을 것 같아요 😉

2023-03-13 12:09 UTC, xrabcde commented on src/test/java/blackjack/domain/game/BlackJackGameTest.java
> +        Player bada = players.get(2);
💙

2023-03-13 12:15 UTC, xrabcde commented on src/main/java/blackjack/controller/BlackJackController.java
> +            outputView.showPlayer(blackJackGame.getPlayer(name));
> 바다가 말씀해주신 현재 코드에서 컨트롤러가 없다면 Game 혼자서 블랙잭 게임을 진행할 수 있을까요?에 대해 고민을 많이 했습니다..!
그래서 컨트롤러에서 딜러와 플레이어를 가져와서 처리했던 부분을 컨트롤러에서 메세지를 던져 BlackJackGame이 직접할 수 있도록 변경해보았습니다. 바다가 말씀해주신 의도가 이런 방향이 맞는지 궁금합니다 !!!

네!! 너무 훌륭하네요!! 
사소할지 몰라도 Game이 players 와 cardDeck 을 가지고 있는 만큼
직접 진행할 수 있는 게임 로직은 최대한 Game 에서 진행할 수 있도록 하고 싶었어요 

사실 블랙잭 게임의 경우 계속해서 사용자의 입력을 받는 과정을 통해 게임이 진행되기 때문에
게임과 뷰의 분리가 쉽지 않은 것이 맞습니다
하지만, 이번 미션을 통해 이렇게 분리가 쉽지 않은 경우에 어떤 방법을 이용할 수 있을지
고민해보는 시간이 되었을거라 생각합니다 :)
어려울 수 있지만 시도해봤으면 해서 남겼던 코멘트였는데 잘 반영해주셨네요 💯💯

2023-03-13 15:41 UTC, Kim0914 commented on src/main/java/blackjack/controller/BlackJackController.java
> +        BettingTable bettingTable = generateBettingTable(players.getNames());
BettingTable 네이밍을 엄청 고민했는데..!!

감사합니다 😀

2023-03-13 15:47 UTC, Kim0914 commented on src/main/java/blackjack/domain/game/Betting.java
> +public class Betting {
반영하겠습니당

2023-03-13 15:51 UTC, Kim0914 commented on src/main/java/blackjack/controller/BlackJackController.java
> +    private void setUp(BlackJackGame blackJackGame) {
넵 ! 반영하겠습니다 ㅎㅎ

메서드 순서에 대해 궁금한게 있습니다 ~
한 클래스 내에 private 메서드와 public 메서드가 같이 존재하는 경우

public 메서드를 우선 배치한 후 private 메서드는 따로 아래로 내려서 관리하시는지
또는
public 메서드에서 호출하는(관련된) private 메서드는 public 메서드 아래에 두면서 관리하시는지 궁금합니다 😎

2023-03-13 16:04 UTC, Kim0914 commented on src/test/java/blackjack/domain/game/BettingTest.java
> +    @DisplayName("배팅 금액 허용 범위와 다르면 예외가 발생한다.")
넵 !!

배팅 금액이 1원 단위나 10원 단위로 들어오는 경우를 제외하는 것이 좋을 것 같아. 
작은 요구사항(`금액은 백원 단위로 입력할 수 있다`)까지 더해서 함께 반영하겠습니다 !

2023-03-14 01:55 UTC, Kim0914 commented on src/main/java/blackjack/domain/game/Result.java
> +    }
반영하겠습니다 !! 😅

2023-03-14 01:58 UTC, Kim0914 commented on src/main/java/blackjack/controller/BlackJackController.java
> +            outputView.showPlayer(blackJackGame.getPlayer(name));
말씀해 주신 부분을 고민 많이 하면서 최대한 컨트롤러에서 서비스 로직을 걷어내려고 했는데, 
바다가 말씀해주신 의도와 부합한다고 하니 뿌듯한 것 같아요 !!

바다 덕분에 컨트롤러의 역할과 서비스 로직에 대해 다시 한번 생각해볼 수 있는 좋은 기회였던 것 같습니다 🙇🏻

2023-03-14 02:00 UTC, Kim0914 commented
안녕하세요 바다 ~~  🌊 
그레이입니다 !

말씀해주신 피드백을 바탕으로 리팩토링을 진행했습니다 !!

감사합니다 😀

2023-03-14 11:30 UTC, xrabcde commented on src/main/java/blackjack/domain/game/BettingMoney.java
> +public class BettingMoney {
👍🏻👍🏻

2023-03-14 11:30 UTC, xrabcde commented on src/main/java/blackjack/domain/participant/Participant.java
> +    }
참가자가 점수를 직접 비교하도록 개선해주었네요 💯

2023-03-14 11:30 UTC, xrabcde commented on src/test/java/blackjack/domain/game/BettingMoneyTest.java
> +    @DisplayName("배팅 금액 허용 범위와 다르면 예외가 발생한다.")
경곗값테스트 💯

2023-03-14 11:30 UTC, xrabcde commented on src/main/java/blackjack/controller/BlackJackController.java
> +    private void setUp(BlackJackGame blackJackGame) {
메서드 순서는 범위나 접근성으로 기준을 나누기 보다는 기능성에 의해 구성하는 게 좋다고 생각해요 ☺️
실행 순서나 동작내용에 따라 잘 그룹핑만 해주신다면 순서는 크게 상관없어 보입니다 !

2023-03-14 11:43 UTC, xrabcde approved these changes
안녕하세요 그레이 ~ 바다입니다 🌊
피드백을 꼼꼼히 반영해주셨네요 ㅎㅎ
이 정도면 이번 미션을 통해 경험할 수 있는 내용을 충분히 하신 것 같아 merge 하겠습니다

블랙잭 미션 완수하신 것 축하드리고 앞으로 남은 과정도 화이팅입니다 !! 🎉

2023-03-14 11:43 UTC, merged