[2단계 - 블랙잭(베팅)] 마코(이규성) 미션 제출합니다.
woowacourse/java-blackjack pull request #567
Opened 2023-03-13 02:34 UTC by aak2075

안녕하세요 에단!

리팩토링을 어떻게 할까 고민을 하면서 테코톡을 준비하다 보니 2단계 시작하기 전에 피드백 강의를 듣게 되었습니다.

너무 신기해서 직접 경험해보기 위해 강의에서 나왔던 상태 패턴을 적용해 보았습니다.

## 주요 리팩토링 사항

- 상태 패턴

기존에는 Enum에서 결과를 계산하였습니다. Enum에게 많은 책임을 부여하는 것 보다는 객체로 만들어 객체에게 책임을 부여하는 것이 낫다고 판단했습니다.
상태 패턴으로 참여자들의 상태(Hit, Bust, Blackjack, Stay 등)를 관리하여 분기를 줄이고 상태를 관리할 수 있었습니다.
하지만 딜러는 숫자가 16 이하일 때 한 번만 hit 하고 stay를 하기 때문에 플레이어와 State가 조금 다릅니다.
이를 해결하기 위해 State 클래스 외부인 Dealer 클래스에서 State를 수정하도록 했습니다. 
Dealer만의 State를 추가할 수도 있지만 이는 인터페이스가 구현에 의존하는 것 같다는 느낌이 들었습니다. 에단의 생각은 어떠신가요?

- 딜러와 참여자

기존에는 Dealer가 Player를 상속한 구조였으나 역할이 많이 달라지는 것을 느꼈습니다.
과연 상속이 필요할까 라는 것을 계속 고민했습니다. 
상속은 캡슐화가 쉽게 깨지고, 상위 클래스가 변경이 생기면 수정이 많이 일어난다는 생각에 컴포지션을 사용했습니다.

2023-03-13 12:18 UTC, Laterality requested changes
안녕하세요 마코.

2단계도 잘 구현해주셨어요. 테스트를 꼼꼼하게 작성하신 게 눈에 띄네요 👍 

몇가지 코멘트 남겨드렸어요.

그리고 실행중에 아래처럼 예외가 발생하는 경우가 있는데, 함께 확인해주세요.

```
게임에 참여할 사람의 이름을 입력하세요.(쉼표 기준으로 분리)
A,A,B
A의 배팅 금액은?
1000
A의 배팅 금액은?
1500
B의 배팅 금액은?
2000
딜러, A, B에게 2장을 나누었습니다.
딜러카드 : A스페이드, 6하트
A카드 : 4하트, 4클로버
B카드 : 8하트, 5다이아몬드
A는 한장의 카드를 더 받겠습니까?(예는 y, 아니오는 n)
y
A카드 : 5하트, 6다이아몬드, 7스페이드
A는 한장의 카드를 더 받겠습니까?(예는 y, 아니오는 n)
n
A카드 : 5하트, 6다이아몬드, 7스페이드
B는 한장의 카드를 더 받겠습니까?(예는 y, 아니오는 n)
y
B카드 : 8하트, 5다이아몬드, J다이아몬드
딜러카드 : A스페이드, 6하트 - 결과: 17
A카드 : 5하트, 6다이아몬드, 7스페이드 - 결과: 18
A카드 : 4하트, 4클로버 - 결과: 8
B카드 : 8하트, 5다이아몬드, J다이아몬드 - 결과: 23
Exception in thread "main" domain.state.exceptions.ProfitException: 수익을 계산할 수 없는 상태입니다.
	at domain.state.Running.profit(Running.java:38)
	at domain.user.Player.calculate(Player.java:29)
	at domain.user.Participants.profit(Participants.java:67)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:553)
	at domain.user.Participants.dealerProfit(Participants.java:60)
	at domain.game.BlackjackGame.dealerProfit(BlackjackGame.java:40)
	at controller.BlackjackController.printProfit(BlackjackController.java:124)
	at controller.BlackjackController.play(BlackjackController.java:38)
	at Application.main(Application.java:14)
```

2023-03-13 12:18 UTC, Laterality commented on src/main/java/domain/card/Hand.java
> +        return score().isMax() && cards.size() == 2;
매직 넘버는 상수로 만들면 어떨까요?

2023-03-13 12:18 UTC, Laterality commented on src/main/java/domain/card/Score.java
> +    private static final Score max = new Score(21);
점수가 실제로는 21점을 초과할 수도 있는데, 적절한 이름일까요?

2023-03-13 12:18 UTC, Laterality commented on src/main/java/domain/card/Score.java
> +    private static final Score min = new Score(0);
상수에 맞는 네이밍 규칙을 적용하면 어떨까요? [참고](https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names)

2023-03-13 12:18 UTC, Laterality commented on src/main/java/domain/game/Command.java
> +public enum Command {
뷰와 컨트롤러에서만 쓰이고 내부에 특별히 도메인과 관련된 로직은 없는 걸로 보이는데, 도메인 영역에 위치하는 것이 맞을까요?

2023-03-13 12:18 UTC, Laterality commented on src/main/java/domain/state/Hit.java
> +    Hit(final Card card) {
적절한 접근제어자를 추가하면 어떨까요?

2023-03-13 16:15 UTC, aak2075 commented on src/main/java/domain/card/Hand.java
> +        return score().isMax() && cards.size() == 2;
빠뜨렸네요! 😲

2023-03-13 16:15 UTC, aak2075 commented on src/main/java/domain/game/Command.java
> +public enum Command {
뷰 패키지로 이동시켰습니다.

2023-03-13 16:15 UTC, aak2075 commented on src/main/java/domain/state/Hit.java
> +    Hit(final Card card) {
Ready만 public으로 열어 놓고 다른 State를 Ready에서만 시작할 수 있도록 default 접근제어자로 설정했습니다.

접근제어를 패키지에 의존하는 default를 사용하는 것은 저도 조금은 불안하기는 합니다.

그래도 모든 State를 public으로 열어서 잘못 사용되는 것 보다는 default로 설정하고 패키지가 수정되면 그 때 접근제어자를 수정해도 괜찮지 않을까요?

2023-03-13 16:25 UTC, aak2075 commented
> 그리고 실행중에 아래처럼 예외가 발생하는 경우가 있는데, 함께 확인해주세요.

이름이 중복됐을 경우에 발생하는 예외를 처리해주지 않았네요.

뷰에서 중복된 이름을 입력받으면 재입력을 받도록 1차적으로 처리해 주고,

도메인에서도 한번 더 검증하여 인스턴스를 생성하지 않고 예외를 발생시키도록 수정했습니다.

2023-03-14 11:33 UTC, Laterality approved these changes
안녕하세요 마코.

피드백 잘 반영해주셨습니다.

이번 미션은 이만 머지하도록 할게요.

남겨드린 코멘트는 참고만 해주세요.

고생 많으셨습니다. 다음 미션도 화이팅하세요 :)

2023-03-14 11:33 UTC, Laterality commented on src/main/java/domain/state/Hit.java
> +    Hit(final Card card) {
의도적으로 default 접근 제어자를 사용하신 거라면 괜찮습니다. 그렇다면 바로 아래에 있는 생성자도 수정이 필요할까요?

2023-03-14 11:33 UTC, Laterality commented on src/main/java/domain/card/Score.java
> +    }
객체를 직접 노출하는 대신 메서드를 통해 제공하신 이유가 있을까요?

2023-03-14 11:33 UTC, Laterality commented on src/main/java/domain/state/Running.java
> +        return new Hit(hand);
`Running`을 상속받은 `Hit`를 다시 `Running`에서 참조한다는 건 DIP 위반 아닐까요?

2023-03-14 11:33 UTC, merged

2023-03-15 00:19 UTC, aak2075 commented on src/main/java/domain/card/Score.java
> +    }
지금 상황에서는 직접 노출해도 상관 없지만 습관적으로 직접 노출하지 않는 편입니다.
변경이 생기면 다른 객체를 사용하게 될 수 있고, 이 때 해당 객체를 사용하는 모든 코드를 수정해야 합니다.
메서드로 제공하면 메서드만 수정하면 되기 때문에 습관적으로 메서드를 통해 제공하고 있습니다.

2023-03-15 00:29 UTC, aak2075 commented on src/main/java/domain/state/Running.java
> +        return new Hit(hand);
듣고보니 이 부분 뿐만 아니라 `State`의 `isHit()` `isStay()`같은 메서드도 DIP를 위반한 것 같습니다. 다시 고민을 해봐야 겠네요