[2단계 - 블랙잭(베팅)] 호이(이건호) 미션 제출합니다.
woowacourse/java-blackjack pull request #568
Opened 2023-03-13 05:02 UTC by This2sho

안녕하세요 춘식 😊

2단계 미션 구현 완료하였습니다..

현재는 기능 구현만 완료한 상태이고..
리팩토링 후 업데이트 하도록 하겠습니다!

2023-03-16 13:46 UTC, bimppap requested changes
안녕하세요 호이! 춘식입니다!
최근 일이 많아져서 리뷰가 늦었네요ㅠㅠ
코드를 깔끔히 짜주셔서 세부적인 사항들에 대해 주로 리뷰 달아봤어요. 💪💪
확인해주시고 리팩토링 후 재요청 주시길 바랍니다.
궁금한 점은 편하게 DM 주세요. 😉

2023-03-16 13:46 UTC, bimppap commented on src/test/java/domain/participant/PlayerTest.java
>              .hasMessage("이름은 5자 이하여야 합니다.");
에러 메세지명이 달라지게 되면 유지보수가 어려울 것 같습니다. 에러메세지를 관리하는 객체가 있으면 좋을 것 같아요!

2023-03-16 13:46 UTC, bimppap commented on src/main/java/view/InputView.java
> +        System.out.printf("%n%s의 배팅 금액은?%n", personName);
View에서 입출력할때 안내용으로 쓰인는 문자열들은 상수화해주세요!

2023-03-16 13:46 UTC, bimppap commented on src/test/java/domain/participant/PlayerTest.java
>  public class PlayerTest {
PlayersTest에서 플레이어들이 제대로 만들어지는 것에 대한 테스트가 빠져있는 것 같습니다! 해당 클래스에 달 수 없어 여기에 달고 갑니다 🙂

2023-03-16 13:46 UTC, bimppap commented on src/main/java/domain/card/Cards.java
> +        return cards.get(0);
상수화!

2023-03-16 13:46 UTC, bimppap commented on src/main/java/domain/card/Cards.java
>      public int getScore() {
getter은 어떤 오브젝트 혹은 필드 변수의 값을 가져오는 역할을 가진 메서드를 통칭합니다. 다른 메서드명을 고민해보면 좋을 것 같아요!

2023-03-16 13:46 UTC, bimppap commented on src/main/java/domain/card/Card.java
>      public Suit getSuit() {
클래스내 배치 순서를 아래와 같이 해주신다면 가독성이 좋아질 것 같습니다 :)

```shell
class A {
    상수(static final) 또는 클래스 변수
    인스턴스 변수
    생성자
    팩토리 메소드
    메소드
    getter/setter
    기본 메소드 (equals, hashCode, toString)
}
```

2023-03-16 13:46 UTC, bimppap commented on src/main/java/domain/card/Cards.java
> +            .anyMatch(Card::isA);
람다 👍

2023-03-16 13:46 UTC, bimppap commented on src/main/java/view/Gains.java
> +    public Gain getDealerGain() {
view에 있는 도메인인데 비즈니스 로직을 가지고 있군요? 👀

2023-03-16 13:46 UTC, bimppap commented on src/main/java/domain/Judge.java
> +    private static GameState isBlackJackWin(Player player) {
메서드명을 보면 boolean 값이 리턴되길 기대하는데 GameState가 리턴되고 있습니다. checkBlackJackState 와 같은 방식으로 바꿔보는 건 어떨까요?

2023-03-16 13:46 UTC, bimppap commented on src/main/java/domain/BetAmount.java
> +    private static final int MIN_AMOUNT = 1000;
static이어야 할 이유가 있나요?

2023-03-16 13:46 UTC, bimppap commented on src/main/java/Application.java
>          Dealer dealer = new Dealer(getInitCards(cardDeck));
getInitCards이 static이 아니어도 될 것 같습니다!

2023-03-17 04:15 UTC, This2sho commented on src/main/java/domain/gamestate/GameState.java
> +public interface GameState {
Interface로 `Win` 과 `BlackJack`의 관계를 표현하고 싶었는데
Enum으로 만들면 블랙잭이면서 이긴다? 이 부분을 표현하기가 힘들어서 Interface로 관리했던거 같습니다.

2023-03-20 15:46 UTC, This2sho commented on src/main/java/Application.java
>  public class Application {
생각처럼 입력 /로직/ 결과 이 세개를 분할하기가 쉽지 않네요 ㅠㅠ

2023-03-20 16:12 UTC, This2sho commented on src/test/java/domain/participant/PlayerTest.java
>              .hasMessage("이름은 5자 이하여야 합니다.");
에러 메시지를 보내는 객체에 상수로 정의 했습니다!

2023-03-20 16:15 UTC, This2sho commented on src/main/java/domain/Judge.java
> +    private static GameState isBlackJackWin(Player player) {
좋은거 같습니다!!

2023-03-20 16:19 UTC, This2sho commented on src/main/java/view/Gains.java
> +    public Gain getDealerGain() {
간단한 로직도 있으면 안되는걸까요?!

2023-03-21 16:10 UTC, bimppap commented on src/main/java/view/Gains.java
> +    public Gain getDealerGain() {
간단하더라도 비즈니스 로직은 비즈니스 로직입니다. 이 정도는 괜찮지 않을까? 싶어 패턴을 벗어나기 시작하면 프로젝트 스케일이 커질수록 유지보수가 어려워질 수 있습니다. 🥲 view에 비즈니스 로직을 두는 대신 Gains를 지우고 Gain에서 calculateDealerGain 메서드를 넣은 후 Gain을 도메인으로 옮기는 게 좋을 것 같습니다!

2023-03-21 16:11 UTC, bimppap commented on src/main/java/domain/gamestate/GameState.java
> +public interface GameState {
지금은 enum으로 리팩토링되었군요 👍

2023-03-21 16:26 UTC, bimppap commented on src/main/java/Application.java
>  public class Application {
어려움이 많이 있었던 것 같네요. 🥲 아마 Player가 BetAmount를 들도록 했다면 좀 더 분리가 쉽지 않았을까 생각됩니다! 머지는 지금 하되 혹시 방학 중에 리팩토링을 좀 더 해보고 싶다면 DM 주세요. 호이의 개인 레포에서 좀 더 봐주도록 할게요ㅎㅎ

2023-03-21 16:42 UTC, bimppap commented on src/main/java/Application.java
> +    private void end(Dealer dealer, Players players, BettingTable bettingTable) {
원래 개발할 때 제일 시간을 많이 쓰는 시간이 변수/메서드 네이밍 짓기입니다ㅋㅋ 
저는 가끔 [자바 네이밍 가이드라인](http://devlsh.tistory.com/entry/Java-Naming-Convention)를 참고하는데, 여기선 void 에 대해 이렇게 서술하고 있네요.

> 리턴 타입이 void인 메서드(procedures)의 경우에는 "무엇을 처리하는 지"를 이름에 쓰는 것이 좋으며, object 타입이나 일반 자료형과 같이 리턴 타입이 있는 메서드(functions)의 경우에는 "처리 후 무엇을 리턴하는 지"를 이름에 쓰는 것이 좋습니다.

2023-03-21 16:49 UTC, bimppap approved these changes
안녕하세요 호이, 춘식입니다!
피드백 반영 확인했습니다. 정말 수고 많았습니다!! 💪💪
블랙잭 미션은 여기서 마무리하도록 할게요. 코멘트를 조금 추가해봤으니 한번 확인해주세요. 😊
체스 미션도 파이팅입니다!! 응원합니다ㅎㅎ

2023-03-21 16:49 UTC, merged

2023-03-22 00:21 UTC, This2sho commented on src/main/java/Application.java
>  public class Application {
헉 감사합니다…!!

2023-03-22 00:21 UTC, This2sho commented on src/main/java/Application.java
> +    private void end(Dealer dealer, Players players, BettingTable bettingTable) {
좋은 자료 감사합니다!!