[2단계 - 블랙잭(베팅) 블랙캣(송우석) 미션 제출합니다.
woowacourse/java-blackjack pull request #573
Opened 2023-03-13 06:48 UTC by Songusika

안녕하세요 파즈님!

STEP2 PR 늦어서 죄송합니다 😭

STEP1 대비 `Money` 클래스와 `Bets` 클래스를 추가하여서 추가된 요구사항을 구현하였습니다.

2023-03-13 13:26 UTC, Be-poz requested changes
안녕하세요 블랙캣 2차 미션해주신 부분 잘 봤습니다. 이번 2차 미션 자체가 기존 코드의 구조를 크게 비트는 미션이 아니다보니 크게 터치할 곳이 없던 것 같습니다. 굳이 한다면 코멘트 중에  '-1' 출력에 대한 리팩토링을 하면 좋을 것 같긴합니다!

2023-03-13 13:26 UTC, Be-poz commented on src/main/java/blackjack/domain/card/Card.java
> +    }
👍

2023-03-13 13:26 UTC, Be-poz commented on src/main/java/blackjack/domain/game/Money.java
> +    }
사용되는 곳이 있나요 ?

2023-03-13 13:26 UTC, Be-poz commented on src/main/java/blackjack/domain/user/Dealer.java
>      private static final Score minScore = new Score(16);
Score 자체가 불변 클래스라 상수라고 봐도 될 것 같습니다.

2023-03-13 13:26 UTC, Be-poz commented on src/main/java/blackjack/view/OutputView.java
> +        System.out.println(" - 결과: " + user.getScore().getScore());
버스트된 경우에 -1 이 아니라 버스트된 값이 출력되거나 차라리 '버스트' 라고 적어주는 것이 좋을 것 같습니다.
출력되는 안내문구는 '결과' 인데 -1 은 오류라고 생각할 수도 있고 수 계산을 해보게 되는 단점이 있는 것 같아요. 
-1이 아니라 버스트된 값 출력을 채택하게 된다면 꽤나 많은 양의 코드 리팩토링이 필요할 것 같긴 하네요.

2023-03-13 13:26 UTC, Be-poz commented on src/main/java/blackjack/controller/BlackjackController.java
> +        players.getPlayers().forEach((outputView::printCardResult));
outputView 감싸는 괄호 하나 빼도 될 것 같습니다!

2023-03-15 19:03 UTC, Songusika commented on src/main/java/blackjack/domain/game/Money.java
> +    }
사용되는 곳이 없어서 삭제하였습니다!

2023-03-15 19:04 UTC, Songusika commented on src/main/java/blackjack/view/OutputView.java
> +        System.out.println(" - 결과: " + user.getScore().getScore());
버스트된 값 (21 이상의 값)이 출력되도록 리팩터링하였습니다!

2023-03-15 19:08 UTC, Songusika commented
안녕하세요 파즈님!

기존 딜러 객체가 유저 리스트를 받아서 딜러 자신과 모든 유저의 게임 결과를 결정하는 방법에서 

각 유저가 상대 유저를 받아 상대 유저 대비 자신의 게임 결과를 결정하는 방법으로 리팩터링하였습니다!

2023-03-18 00:44 UTC, Be-poz approved these changes
안녕하세요 블랙캣 반영해주신 것 잘 봤습니다. 생각보다 크게 코드가 변경되지 않고 리팩토링이 가능했네요! 
지금까지 블랙잭 수행하시느라 수고하셨습니다. 체스도 잘 마무리하시길 바랄게요~!

2023-03-18 00:44 UTC, Be-poz commented on src/main/java/blackjack/domain/user/User.java
> +//        return hand.getScore().isBust();
👀

2023-03-18 00:44 UTC, merged