[2단계 - 블랙잭(베팅)] 홍고(홍여진) 미션 제출합니다.
woowacourse/java-blackjack pull request #583
Opened 2023-03-13 08:14 UTC by hgo641

안녕하세요, 조앤! 홍고입니다. 😃😃
이번에도 변경된 부분과 궁금한 것을 정리해서 작성해봤어요!
마지막까지 리뷰 잘 부탁드립니다! 🙇‍♀️🙇‍♂️
요즘 날씨가 다시 추워지고 있는데 감기 조심하세요! 

## 변경된 부분

* 📌 `BettingMoneyTable` 생성

플레이어의 베팅 금액을 저장하기 위해 `Map<Player, Money>` 를 가지는 클래스를 생성했습니다.

<br/>

* 📌 `Exchanger` 생성

플레이어와 딜러의 수익을 계산하는 `Exchanger`클래스를 생성했습니다.

<br/>

* 📌 `Referee`의 static 메소드 제거

> #### 📌 Referee의 static 메소드 사용 괜찮은가요?
>
> `BlackJack` 클래스에서 유저의 게임 결과를 판단하는 로직을 분리해 `Referee` 클래스를 생성했습니다. `Referee`클래스는 static 메소드만 지니고 있습니다. static 메소드로 선언한 이유는 아래와 같습니다.
>
> - `Referee` 클래스는 인스턴스 변수가 없기에 객체화를 했을 때 큰 이점이 없다고 생각
> - 요구 사항의 인스턴스 변수 개수 제한 - `Referee` 클래스를 객체로 사용한다면 `BlackJack` 이 `Referee`를 객체로 가져야한다고 생각하는데, `BlackJack`은 이미 2개의 인스턴스 변수를 사용중이기에 변수를 추가할 수 없었습니다.
>
> 그런데, `Referee` 클래스는 `BlackJack` 객체에서만 사용되는데 모든 메서드들을 static으로 하는게 맞을지 잘 모르겠습니다.😭 혹시 더 좋은 방법이 있을까요?
>
> A. 홍고만의 기준을 갖고 Referee 클래스를 유틸 클래스로 생성해주신 것은 좋아보여요! 다만 말씀해주신 것처럼 `Referee` 클래스는 `BlackJack` 객체에서만 사용된다면, 이건 기존처럼 블랙잭이 가져야하는 로직이 아닐까 싶기도 하구요!ㅎㅎ `public static`으로 선언하게 되는 순간 인스턴스화 하지 않아도 모든 곳에서 사용가능해지기 때문에 이렇게 어느 곳에서든 접근되어도 괜찮은 메서드들일지, 아니면 블랙잭 내부에서 관리되는게 오히려 응집도가 높을 지 고민해보시면 좋을 것 같아요~!

이전에 이런 질문을 드렸었는데, 조언의 답변을 듣고 고민해본뒤 `Referee`의 `static` 메소드들을 제거하고 인스턴스화해서 사용하기로 했습니다. `Referee` 클래스가 `Exchanger` 객체에서만 사용되기에 `Referee` 클래스의 로직을 `Exchanger`에 옮겨 응집도를 높일까도 생각해봤지만, 기존 `Referee` 테스트를 수정하는 비용이 들어서 고민 끝에 `Referee` 클래스를 남기고 `Exchanger`에서 인스턴스 변수로 사용하게 되었습니다.

## 궁금한 점

1

초기에 플레이어가 베팅 금액을 인스턴스 변수로 가지게 설계했습니다. 그러나 플레이어의 인스턴스 변수가 늘어나면서 플레이어의 생성자가 변경되고, 플레이어의 생성자가 변경되면서 플레이어를 생성하는 모든 로직들을 수정해야하는 상황이 벌어졌습니다. 

결국 `BettingMoneyTable`이라는 객체를 만들어 `Map`객체에 플레이어를 key로 베팅 금액을 저장했습니다... 객체에 인스턴스 변수가 추가적으로 필요해지는 경우에 유연하게 대처하려면 어떻게 해야할까요?  

2

이전 리뷰를 통해 `instanceof` 대신 다형성을 사용했을 때의 장점에 대해 알게되었습니다! 그런데 다형성이 항상  `instanceof`보다 더 장점이 많은지 궁금해졌습니다... 그런 경우를 찾아보려고 노력했지만 찾을 수 없었습니다. 혹시 조앤은 다형성 대신  `instanceof`를 사용하면 더 좋은 상황을 아시나요?

<br/>

\+

> 별다른 코멘트 없이 반영해주신 것 같은데 홍고는 제가 남긴 답변에 어떻게 생각하셨는지 궁금해요!
> [[#409 (comment)](https://github.com/woowacourse/java-blackjack/pull/409#discussion_r1125228147)](https://github.com/woowacourse/java-blackjack/pull/409#discussion_r1125228147)

이 부분에 대해 답변을 적지 않아서 추가적으로 남깁니다!

<br/>

* 1️⃣ `Users`에서 stream을 통해 계속 확인하지 않아도 됨

조앤이 말씀해주신것처럼  `List<User>`를 `Players`와 `Dealer`로 나누면 `Users` 객체에서 로직을 수행할 때마다 플레이어인지 딜러인지 확인하는 절차가 없어져서 좋은 방법이라고 생각해서 코드를 변경했습니다!

<br/>

* 2️⃣ `Users`에서 타입 추론 로직 제거

조앤이 코멘트로 남겨주신 포스팅을 보고(https://tecoble.techcourse.co.kr/post/2021-04-26-instanceof/), `instanceof`를 사용해 타입을 추론할 경우, SRP원칙에 위배된다는 것을 알게 되었습니다.

`instanceof`를  `isDealer()`, `isPlayer()` 라는 추상메소드를 통해 다형성을 사용하는 방식으로 변경한다고 해도,  `Users`클래스가 객체의 타입을 추론하고있다는 것은 변하지 않는다고 생각했습니다. 

물론 `Users`의 경우 단순히 `getter`를 사용하는데 타입을 추론하고 있지만 `Users` 클래스가 하위 객체의 타입을 직접 검사하는 것이 객체 지향적이지 않다고 생각해, `List<User>`를 `Players`와 `Dealer`로 분리했습니다.

<br/>

* 3️⃣ `Users`에 `Players`와 `Dealer`에 공통적으로 사용되는 로직이 존재하지 않음

현재 `Users`에는 `Players`와 `Dealer`에게 공통적으로 사용되는 로직이 존재하지 않습니다. 😭😭

둘은 게임에 참여하는 유저라는 점에서 의미적으로 연관성은 있지만, 막상 `Users`의 로직들을 보면 `Players`와 `Dealer`에게 공통적으로 사용되는 로직이 없어 `List<User>`를 분리해도 큰 타격이 없겠다고 생각했습니다...

2023-03-13 15:27 UTC, seovalue requested changes
안녕하세요, 홍고! 
전반적으로 깔끔하게 잘 구현해주셨네요 👍 몇가지 코멘트 남겼는데 확인하신 후 다시 리뷰 요청 주세요~

2023-03-13 15:27 UTC, seovalue commented on docs/README.md
> +- [x] 유저(User)
1

초기에 플레이어가 베팅 금액을 인스턴스 변수로 가지게 설계했습니다. 그러나 플레이어의 인스턴스 변수가 늘어나면서 플레이어의 생성자가 변경되고, 플레이어의 생성자가 변경되면서 플레이어를 생성하는 모든 로직들을 수정해야하는 상황이 벌어졌습니다.

결국 BettingMoneyTable이라는 객체를 만들어 Map객체에 플레이어를 key로 베팅 금액을 저장했습니다... 객체에 인스턴스 변수가 추가적으로 필요해지는 경우에 유연하게 대처하려면 어떻게 해야할까요?


A1.

음.. 예를 들어 Player 는 기존에 name 만을 갖고 있었는데, money를 추가로 갖게 된다고 가정 해 볼게요. 그럼 new Player("조앤")은 모두 new Player("조앤", 1000)으로 변경되어야할거예요. 유연한 구조를 가져가려면 추가되는 값에 대해 디폴트값을 주는 방법 밖엔 떠오르지 않는데, 이 경우가 아니라면 인스턴스 변수의 추가는 크리티컬한 변화이기 때문에 전반적으로 대응할 수 밖에 없는 것 같아요ㅠ 

2

이전 리뷰를 통해 instanceof 대신 다형성을 사용했을 때의 장점에 대해 알게되었습니다! 그런데 다형성이 항상 instanceof보다 더 장점이 많은지 궁금해졌습니다... 그런 경우를 찾아보려고 노력했지만 찾을 수 없었습니다. 혹시 조앤은 다형성 대신 instanceof를 사용하면 더 좋은 상황을 아시나요?

A2

흠.. 장점일진 모르겠지만 생각나는 한가지 예시는 `instanceof`는 컴파일 타임에 타입 에러를 체크해요. 하지만 다형성을 사용하게 되면 주로 런타임에 예외를 발생시킬 수 있으니 컴파일때부터 강력하게 타입 체크가 필요하다면 `instanceof`를 사용할 수도 있지 않을까 싶네요!

2023-03-13 15:27 UTC, seovalue commented on src/main/java/domain/game/Exchanger.java
> +    }
if문의 반복을 줄이면서 Result에 따라 적절한 ExchangeRate을 반환할 수 방법엔 어떤게 있을까요? 🤔

2023-03-13 15:27 UTC, seovalue commented on src/main/java/domain/money/BettingMoney.java
> +public class BettingMoney extends Money {
구체 클래스인 Money를 상속하신 이유가 있나요?

2023-03-13 15:27 UTC, seovalue commented on src/main/java/domain/game/Blackjack.java
> +        return exchanger.getWinningMoneyOfDealer(playerMonies);
```suggestion
    public Money calculateWinningMoneyOfDealer(Map<String, Money> winningMoneyOfPlayers) {
        List<Money> playerMonies = new ArrayList<>(winningMoneyOfPlayers.values());
        return exchanger.getWinningMoneyOfDealer(playerMonies);
    }
```

2023-03-13 15:27 UTC, seovalue commented on src/main/java/domain/money/Money.java
> +    }
'equals()' should check the class of its parameter 라는 권고가 있어요 
```suggestion
        @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Money money = (Money) o;
        return value == money.value;
    }
```

2023-03-13 15:27 UTC, seovalue commented on src/main/java/domain/money/Money.java
> +    }
그리고 equals와 hashCode는 함께 재정의하길 권장해요!

https://tecoble.techcourse.co.kr/post/2020-07-29-equals-and-hashCode/

2023-03-14 03:59 UTC, hgo641 commented on docs/README.md
> +  - [x] 베팅 금액은 10,000,000원 이하만 생성이 가능하다
아이고... max값만 생각하고 바보 처럼 음수는 처리를 안했네요 ㅠㅠ 예외 메시지도 만들겠습니다!

2023-03-14 04:14 UTC, hgo641 commented on docs/README.md
> +    - [x] 카드의 합계가 16 이하면 카드를 받을 수 있다
구현할 때 딜러 점수가 16이하이면 계속 카드를 받는 것을 의도했어요!  기능 목록에서 설명이 부족했던 것 같아요 업데이트 하겠습니다😃👍

2023-03-14 04:20 UTC, hgo641 commented on docs/README.md
> +- [x] 유저(User)
답변 감사합니다!!😃😃

1. 그럼 이번에 생성한 `BettingMoneyTable`처럼 player를 key로 money를 저장하는게 최선의 방법일까요?

2. `instanceof`와 다형성을 사용했을 때 예외가 발생하는 타임이 다른 걸 이용해볼 수 있겠네요! 감사합니당

2023-03-14 04:22 UTC, hgo641 commented on src/main/java/domain/game/Blackjack.java
> +    private final Exchanger exchanger;
헉... 분리해오겠습니다 ㅠㅠ

2023-03-14 04:25 UTC, hgo641 commented on src/main/java/domain/money/BettingMoney.java
> +public class BettingMoney extends Money {
`Money` 클래스를 
1. 플레이어의 베팅 금액
2. 유저의 수익 금액 
이렇게 두 가지 방법으로 사용하고 있었습니다.

그런데 베팅 금액의 MAX값과 수익의 MAX값이 같을 경우, 오버플로우가 발생할거라 생각해 베팅 금액은 MAX값이 제한된 Money가 필요하겠다고 생각했습니다!

그래서 `Money`를 상속한 `BettingMoney`클래스를 생성했습니다.

2023-03-14 04:27 UTC, hgo641 commented on src/main/java/domain/game/Exchanger.java
> +    }
`Result`를 인터페이스로 만들고 이를 구현한 클래스들에서 ExchangeRate를 반환하는 메소드를 작성하는 방식이 좋을 것 같네요ㅎ.ㅎ 혹시 다른 방법도 있을까요?😃

2023-03-15 00:40 UTC, hgo641 commented on src/main/java/domain/money/BettingMoneyTable.java
> +    }
처음에 `Player`를 일급컬렉션으로 감싸지 않아서 `Users`의 `getPlayers` 메소드가  `List<Player>`를 반환하게 했습니다.
나중에 `Players`를 생성하면서, `getPlayers`의 반환 형태를 `Players`로 바꿀까 생각했는데 시간이 좀 걸릴 것 같아 그대로 `List<Player>`를 반환하게 했습니다. 😭

실제 코드에서는 `Users`의 `getPlayers`를 사용해서 `BettingMoneyTable`을 사용하기에 `List<Player>` 를 정적 팩토리 메소드 인자로 받게 했고, `Players`보다 나중에 생긴 `BettingMoneyTableTest`에서는 편의상 `Players`를 받아 생성하게 했는데... 정확한 테스트를 위해 실제코드와 테스트의 인자 타입을 통일시키는게 좋을까요? 😂

2023-03-15 00:57 UTC, hgo641 commented on src/test/java/domain/user/UserTest.java
> +    void test() {
앗 지우고 푸쉬하려고 했는데 잊었습니다 ㅠㅠ

2023-03-15 01:44 UTC, hgo641 commented on src/main/java/domain/money/Money.java
> +    }
감사합니다!!

2023-03-15 01:47 UTC, hgo641 commented on src/main/java/domain/game/Blackjack.java
> +        return exchanger.getWinningMoneyOfDealer(playerMonies);
훨씬 깔끔하네요!! 감사합니다 👍👍

2023-03-15 14:35 UTC, seovalue commented on src/main/java/domain/game/Exchanger.java
> +    }
저는 상태패턴을 이용해보는 것을 추천드리는데요, Result에서도 단순히 rate만 반환하기 보다는 input인 bettingMoney를 받아 결과값까지 계산할 수도 있을 것 같아요. 

```
public enum Result {
    WIN(bettingMoney -> bettingMoney),
    LOSE(bettingMoney -> bettingMoney * -1),
    DRAW(bettingMoney -> 0),
    BLACKJACK(bettingMoney -> (int) (bettingMoney * 1.5));

    private final IntUnaryOperator operator;

    Result(IntUnaryOperator operator) {
        this.operator = operator;
    }

    public int calculate(int bettingMoney) {
        return operator.applyAsInt(bettingMoney);
    }
}
```

2023-03-15 14:43 UTC, seovalue approved these changes
안녕하세요, 홍고. 조앤이에요.
남겨주신 코멘트에 대해 답변 달아두었고 첫번째 제출 때에도 구현을 잘 해주셔서 변경사항에 대해 이 정도면 머지해도 될 것 같아요.
체스 미션도 화이팅이에요ㅎㅎ 시간나실 때 상태패턴에 대해서도 꼭 학습해보시길 바라요.

2023-03-15 14:43 UTC, seovalue commented on src/main/java/domain/game/Exchanger.java
> +        return bettingMoney.multiply(result.getExchangeRate());
확실히 전에 비해서 깔끔해졌네요ㅎㅎ

2023-03-15 14:43 UTC, seovalue commented on src/main/java/domain/game/Referee.java
> +    public Result judgePlayerResult(final Hand playerHand, final Hand dealerHand) {
홍고도 나중에 상태패턴에 대해 꼭 학습해보시고 적용해보시길 바라요.

2023-03-15 14:43 UTC, seovalue commented on docs/README.md
> +- [x] 유저(User)
1. 사실 베스트는 각 player당 money를 갖도록 하고, 그 player의 상태에 따라 알맞은 수익 값을 반환할 수 있도록 하는 상태를 player가 갖고 있게 하는게 베스트라고 생각해요.

2023-03-15 14:43 UTC, seovalue commented on src/main/java/domain/money/BettingMoneyTable.java
> +    }
홍고는 어떻게 생각하시나요? 
테스트는 비즈니스 코드의 신뢰를 높이기 위해 작성하는 건데, 비즈니스 코드와 전혀 다른 생성자를 사용해서 테스트를 작성하게 된다면 신뢰를 보장할 수 있을까요?

2023-03-15 14:43 UTC, merged

2023-03-16 00:18 UTC, hgo641 commented on docs/README.md
> +    - [x] 카드의 합계가 16 이하면 카드를 받을 수 있다
@seovalue 저도... 룰을 잘 몰라서 온라인 게임 사이트에서 블랙잭 룰을 확인했는데, 딜러는 17이상이 될 때까지 계속해서 hit을 해야한다는 룰이 있어서 미션에 적용해봤습니다! 다른 크루분들에게도 딜러의 hit룰을 어떻게 했는지 여쭤봤는데, 크루마다 구현이 다른걸 보아 딜러 hit룰이 유연한 것 같기도 해요...ㅎㅎ

[The dealer must continue to take cards until the total is 17 or more, at which point the dealer must stand.](https://bicyclecards.com/how-to-play/blackjack/)
[이때부터 딜러는 자신의 핸드가 17점 이상이 될 때까지 힛해야 합니다](https://www.pinnacle.com/ko/betting-articles/casino/how-to-play-blackjack/APN24F8ARK6VLKZN)

2023-03-16 00:20 UTC, hgo641 commented on docs/README.md
> +- [x] 유저(User)
@seovalue 그렇군요 저도 player가 자신의 money를 가지고 있는게 좋은 것 같아요 이 부분은 레벨1끝나고 방학식때 다시 리팩토링해봐야겠네요! 감사합니다

2023-03-16 00:26 UTC, hgo641 commented on src/main/java/domain/game/Exchanger.java
> +    }
@seovalue Result에서 rate를 반영한 winningMoney를 바로 반환해주는게 깔끔하고 좋은 것 같아요!!
상태 패턴을 한 번도 사용해본 적이 없는데 이번 기회에 시도해보고 싶네요ㅎㅎ 감사합니다!

2023-03-16 00:30 UTC, hgo641 commented on src/main/java/domain/money/BettingMoney.java
> +public class BettingMoney extends Money {
@seovalue 네 맞습니다ㅎㅎ... 베팅 금액으로 int형의 max값이 들어온다면 플레이어가 블랙잭 승리를 했을 때  int_max * 1.5인 수익을 얻기 때문에 오버플로우가 생길거라고 생각했어요

이외에도 베팅 금액의 범위가 너무 크지 않게 제한하고 싶어서 validate로직을 추가한 `BettingMoney`클래스를 따로 만들었습니다

2023-03-16 00:33 UTC, hgo641 commented on src/main/java/domain/money/BettingMoneyTable.java
> +    }
@seovalue 비즈니스 코드의 생성자와 테스트 코드의 생성자 인자 타입이 다르면 신뢰가 떨어질 것 같습니다 ㅠㅠ
이 부분은 수정하는게 좋을 것 같네요

2023-03-16 00:34 UTC, hgo641 commented on src/main/java/domain/game/Referee.java
> +    public Result judgePlayerResult(final Hand playerHand, final Hand dealerHand) {
네ㅎㅎ 조언해주셔서 감사합니다!! 레벨1 방학하고 재구현을 해보겠습니다