[블랙잭 Step1] 명오(김형호) 미션 제출합니다.
woowacourse/java-blackjack pull request #596
Opened 2024-03-08 06:04 UTC by HyungHoKim00

안녕하세요 오리!! 제 코드를 봐주셔서 감사합니다.

미션을 진행하면서 의문점이 생겨서, 의견을 여쭤보고 싶습니다.

1. enum에서 문자열 값을 resultView에 가져오는 것이 domain이 view에 대해 알고 있는(의존하는) 형태인가요?

현재 저의 코드에선 Shape, Number 등등의 enum 객체들이 이름을 가지고 있습니다.
이러한 이름들은 출력에 그대로 사용되고 있습니다.

이 과정에서, "Domain이 View를 알고 있는 것"처럼 보이기도 합니다.
어떻게 출력되는 지 Domain이 알고 있는 형태이니까요.

하지만, 이를 ResultView에서 관리하는 것은 Enum 형태가 많이 존재할 때 단점이 있을 것이라고 생각했습니다.

ResultView가 불필요하게 커지게 만들 것이라고 생각했고,
출력 형식을 변경하는 것이 더 불편해 질 것이라고 생각했습니다.

이에 대해 어떻게 생각하시는지 궁금합니다.

2. 단순히 하위 클래스의 함수를 불러오는 메서드도 테스트를 해야 하나요?

현재 저의 코드에는 이러한 형식의 코드들이 있습니다.
```java
public class UserDeck {
    public int sumCard() {
        int sum = cards.stream()
                .mapToInt(Card::getNumberValue)
                .sum();
        return addSumByAce(sum);
    }
}

public class User {
    private final UserDeck userDeck;
    public int sumCard() { return userDeck.sumCard(); }
```
이 코드는 User에서 UserDeck의 메서드를 그대로 가져오는 메서드가 존재합니다.

이 경우, User의 sumCard에 대한 테스트도 존재해야 하나요?

존재해야 하는 근거는,
이후 sumCard의 로직이 변경되었을 때를 위해 테스트는 존재해야 한다고 생각했습니다.

필요없는 근거는,
변경 가능성이 거의 존재하지 않는데 중복된 테스트코드를 작성하는 것이 비효율적이라고 느꼈습니다.

이에 대해 어떻게 생각하시는지 궁금합니다.

2024-03-08 09:09 UTC, jinyoungchoi95 requested changes
안녕하세요 명오 😄

블랙잭 미션의 리뷰어를 맡은 오리입니다.

벌써 1레벨의 반틈이 왔네요 :) 몇가지 코멘트 남겨두었으니 확인 부탁드려요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-03-08 09:09 UTC, jinyoungchoi95 commented on src/test/java/domain/user/UserTest.java
> +    }
abstract 상속의 사용에 대해서 안좋은 이야기를 했지만 😅 만약 abstract로 구현된 케이스에서 해당 테스트는 각각 `PlayerTest`, `DealerTest`에서 수행되어야하지 않을까요?

2024-03-08 09:09 UTC, jinyoungchoi95 commented on src/main/java/domain/user/Users.java
> +    private User currentUser;
`Users`가 가지는 책임이 무엇일까요? 일급컬랙션으로 보이는데 `currentUser`까지 가지고 있어야할까요?

2024-03-08 09:09 UTC, jinyoungchoi95 commented on src/main/java/controller/Controller.java
> +public class Controller {
Controller라는 이름이 적절한가요?

MVC 혹은 spring에서 사용하는 controller를 생각하셨다면 1레벨 미션은 "자바만을 사용하는 어플리케이션 만들기"이기 때문에 특정 패턴에 종속적인 네이밍을 사용하지 않아도 됩니다. 패턴은 이론적으로 학습하고 강제로 적용할거리를 찾기보다는 자연스럽게 미션을 통해서 적절한 상황에 발견하는 재미를 느끼셨으면 좋을 것 같아요 :)

그럼 이제 그렇게 되었을 때 "컨트롤러"라는 이름은 이 객체의 역할을 드러내기에 충분한 네이밍을 가지고 있을까요? 컨트롤러는 보통 조이스틱과 같은 게임 컨트롤러를 뜻한다고 생각하는데요. 조이스틱이 게임을 실행시키고 화면을 출력하지 않듯 컨트롤러보다는 이 객체를 표현해줄 더 좋은 네이밍을 고려해보시면 좋을 것 같습니다.

2024-03-11 04:45 UTC, HyungHoKim00 commented on src/main/java/domain/card/Number.java
> +    }
제가 캐치하지 못한 부분이네요!!

2024-03-11 05:11 UTC, HyungHoKim00 commented on src/main/java/domain/card/Number.java
> +    }
values()는 Array 형태로 반환하기 때문에, List 형태로 사용하고 싶어서 새로운 메서드를 만들었습니다.

하지만, 지금 보니 stream 형태로만 사용하고 있기 때문에, 불필요한 메서드인 것 같네요.

감사합니다!!

2024-03-11 05:16 UTC, HyungHoKim00 commented on src/main/java/domain/deck/PlayerDeck.java
> +public class PlayerDeck extends UserDeck {
PlayerDeck을 따로 만든 이유는, Player가 사용하는 덱이라고 명시하고 싶었기 때문입니다.

생각해 보니, UserDeck을 사용하는 User가 여러 명 생성되었을 때 항상 새로운 클래스를 생성한다면, 중복을 제거하는 의미가 크게 없을 것 같다는 생각이 드네요.

감사합니다!!

2024-03-11 05:35 UTC, HyungHoKim00 commented on src/main/java/domain/deck/UserDeck.java
> +    }
원래 hasAce()가 Users에서 사용되었어서 로직을 바꾸는 과정에서 놓친 부분인 것 같습니다!

추가적으로, 테스트를 위해 public으로 열어놓는 것은 잘못된 코드라고 생각합니다 ㅎㅎ.

감사합니다!!

2024-03-11 05:44 UTC, HyungHoKim00 commented on src/main/java/domain/deck/DealerDeck.java
> +    }
덱이 존재하지 않기 때문에 IndexOutOfBounds 에러가 생기겠네요!! 

getVisibleCard가 불러졌을 때 카드가 없다면, IllegalStateException을 발생시키도록 수정하거나 다른 카드를 불러오도록 할 수 있겠네요.

감사합니다!!

2024-03-11 05:52 UTC, HyungHoKim00 commented on src/test/java/domain/user/NameTest.java
> +    @MethodSource("invalidNamesAndReason")
제가 느낀 단점은, ValueSource와 CsvSource에 비해 테스트에 어떤 값이 들어가는 지 한번에 확인하기 어렵다는 것입니다. (확인하기 위해 테스트에 사용된 메서드의 위치를 찾아야 합니다.)

이를 해결하기 위해, 테스트 코드 바로 위에 사용된 메서드를 작성하려 했습니다.

그 외의 단점은 아직은 느끼지 못했습니다!!

2024-03-11 05:53 UTC, HyungHoKim00 commented on src/main/java/domain/user/Dealer.java
> +        super(new DealerDeck(), new Name("딜러"));
딜러라는 이름도 View에서 해야 옳은 책임이라고 느껴지네요!

해당 부분도 View에서 하도록 변경했습니다.

2024-03-11 09:28 UTC, HyungHoKim00 commented on src/main/java/domain/user/Dealer.java
> +        DealerDeck dealerDeck = (DealerDeck) userDeck;
다운캐스팅의 단점은 오류가 있을 시 컴파일 단계에서 찾을 수 없다는 점입니다.

2024-03-11 09:39 UTC, HyungHoKim00 commented on src/main/java/domain/deck/UserDeck.java
> +    }
그러한 구현이 가능한 것은 맞습니다.

하지만, 현재 퍼블릭으로 열려 있는 메서드 중 오용 가능한 메서드들은 다수 존재하고(game의 addDealerCard 등), 아예 없애는 것은 힘들 것 같다고 느꼈습니다.

오용의 가능성을 줄이기 위해 getVisibleCard가 상속 가능하게 만들어 Player에도 구현을 하고,
ResultView에서 게임 실행 전에는 getVisibleCard를 Player와 Dealer가 같이 사용하도록 했습니다.

2024-03-11 10:22 UTC, HyungHoKim00 commented on src/main/java/controller/Controller.java
> +public class Controller {
지금까지는 MVC에서 사용하는 컨트롤러처럼 사용했었습니다.

역할을 나누고 더 적절한 메서드명을 갖도록 변경했습니다!

2024-03-11 10:24 UTC, HyungHoKim00 commented on src/main/java/domain/user/Users.java
> +    private User currentUser;
Users가 currentUser를 가지고 있던 것은, 설계 자체의 문제였던 것 같습니다.

currentUser라는 개념은, 블랙잭을 play하는 동안에만 사용되는 개념입니다.

Users는 Players와 Dealer에 대한 로직만 책임지는 것이 맞다고 생각합니다.

수정했습니다. 감사합니다!

2024-03-11 10:30 UTC, HyungHoKim00 commented on src/main/java/domain/deck/UserDeck.java
> +public class UserDeck {
이 문제는 Game이라는 클래스가 불필요하게 깊이를 증가시킨다고 생각하여 느낀 문제였습니다.

깊이가 너무 깊으면, 캡슐화를 하는 의미가 퇴색되는 것 처럼 느껴졌습니다.

이번에 MVC 패턴 관련 피드백을 보면서, Game 클래스가 불필요하다고 느낀 부분이 어디인지 깨달았습니다.

Game과 Controller는 하는 일이 비슷했지만, Controller가 뷰 로직을 담당하는 것이 맞다고 느껴져 Controller를 사용했습니다.

Controller를 단순히 Domain의 정보를 View로 전달하는 용도로 사용하지도 않고, 애매한 스탠스가 취해졌었습니다.

이번에 currentUser를 삭제하며, Game 클래스 자체의 역할을 Controller에서 부담하더라도 괜찮을 것이라는 생각이 들었습니다.

덕분에 더 좋은 코드에 가까워 진 것 같았고, 많은 의문이 한번에 해결된 느낌이 드네요!!

감사합니다.

2024-03-11 10:30 UTC, HyungHoKim00 commented on src/main/java/domain/card/Card.java
> +    }
화면전환용 클래스를 만드는 방법이 있네요!! 감사합니다.

2024-03-11 10:58 UTC, HyungHoKim00 commented on src/main/java/domain/deck/UserDeck.java
> +        if (sum + ACE_CONVERT_VALUE <= BLACK_JACK_CONDITION && hasAce()) {
저도 Number가 점수를 정하는 것이 더 올바르다고는 생각했지만, 어떤 방식이 좋을 지 생각하지 못하여 반영하지 않았습니다.

새로 방법이 떠올라 반영해보았습니다!!

2024-03-11 12:19 UTC, HyungHoKim00 commented
안녕하세요 오리!!

꼼꼼한 리뷰 덕분에 잘 공부할 수 있었습니다!!

이번에 코드를 작성하면서 느꼈던 의문에 대해서 어떻게 생각하시는 지 궁금합니다.

---
1. Users에서 Dealer 관리?

현재 저는 Users에서 Dealer를 생성하여, 0번 인덱스에 넣어주고 있습니다.

하지만, 불편한 점이 두가지 있습니다.
1. 인덱스 상수를 두개 사용해야 한다.
3. Dealer에서만 사용하는 메서드(isAddable())를 사용할 수 없다.

특히, List에 넣었기 때문에 User의 메서드만 사용할 수 있게 되어 Player에 불필요한 메서드인 isAddable(busted의 반대입니다.)가 Override된 것이 바람직하지 않게 느껴졌습니다.

중복을 제거하기 위해 상속을 사용했는데, 불필요한 메서드가 추가가 된거니까요.

Users가 Dealer를 따로 가지게 한다면, 기껏 없앤 currentUser의 단점이 다시 부활하는 것으로 느껴졌습니다.

List<Player>를 보유한 Players라는 클래스를 만들어 Users가 Players, Dealer를 가지게 한다면, 추상화의 의미가 퇴색되는 것으로 느껴졌습니다.

또한, 앞서 말한 객체가 깊어진다는 단점도 있습니다. (이 경우, 중복된 메서드가 많이 생성될 것 같았습니다.)

이에 대한 생각을 여쭙고 싶습니다!!

---
오리가 리뷰를 되게 빠르게 고퀄리티로 해준 것에 비해, 주말 내내 코드를 보지 못해 이제야 리뷰요청 보내네요.

다시 열심히 달려보겠습니다!!

2024-03-12 03:00 UTC, jinyoungchoi95 commented on src/main/java/domain/deck/PlayerDeck.java
> +public class PlayerDeck extends UserDeck {
말씀하신대로 `Player`가 사용하는 `UserDeck`이라기에는 과하게 wrapping하지 않는가를 고민해보셨으면 좋겠어요.

`PlayerDeck`에 복잡한 도메인 로직이 있는 것이 아니고, 그렇다고 `Player`자체도 과한 도메인 책임을 가지고 있지 않아요. 단순히 `PlayerDeck.isAddable`을 호출하는 정도라면 `Player`에 담겨있어도 되는 것처럼 보이는거죠. `UserDeck`을 abstract가 아닌 `cards`를 관리하는 일급컬랙션으로 두어도 되지 않을까요?

2024-03-12 03:37 UTC, jinyoungchoi95 requested changes
안녕하세요 명오 😄

피드백 잘 반영해주셨네요. 몇가지 코멘트 추가로 남겨두었으니 확인부탁드려요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-03-12 03:37 UTC, jinyoungchoi95 commented on src/main/java/domain/user/Users.java
> Users에서 Dealer 관리?

먼저 `currentUser`에 대한 코멘트는 쓰지말라기보다는 일급컬랙션의 용도를 분리해서 사용하셨으면 하는 생각에 드린 코멘트였어요.

> Users가 Dealer를 따로 가지게 한다면, 기껏 없앤 currentUser의 단점이 다시 부활하는 것으로 느껴졌습니다.
> List를 보유한 Players라는 클래스를 만들어 Users가 Players, Dealer를 가지게 한다면, 추상화의 의미가 퇴색되는 것으로 느껴졌습니다.

추상하의 의미가 퇴색된다고 하셨는데 그럼 `Player`와 `Dealer`를 잘못 추상화하지는 않았는지를 먼저 고려해보시면 좋을 것 같아요. 둘의 동작이 각각 따로 돌아가고 결과적으로는 그 구현체를 통한 (플레이어는 플레이어의 행위, 딜러는 딜러의 행위)로 동작할텐데 이 둘을 같은 추상화레벨로 두는 것이 맞을까요? 

`UserDeck`에서 이어오는 이야기이지만, 중복을 제거하는 방법은 상속이 아니에요. 중복을 제거하는 방법은 여러가지가 있고, 상속은 엄밀히 따지면 온전히 중복을 제거하기 위한 개념은 아니에요. 자바에서 상속을 하려면 `extends` 키워드를 사용하는 것처럼 상속은 "확장"을 위한 개념이기 때문이에요.

`Player`, `Dealer`를 같은 추상화레벨에서 제거하고 그럼 `Players`, ` Dealer`를 가지는 `GameUsers`를 만들면 되지 않을까요?
```java
public Players {
    private final List<Player> values;
// ...
}

public Dealer {
    private final Deck deck;
// ....
}

public GameUsers {
    private final Players players;
    private final Dealer dealer;
}
```

2024-03-12 03:37 UTC, jinyoungchoi95 commented on src/main/java/domain/card/Number.java
> +    }
11이하일때만 10을 더하는 것이 의미가 있는 규칙을 잘 활용해주신 것 같네요 👍 

readme 기능 사항에는 이런 디테일한 부분도 적어주시면 좋을 것 같아요.

2024-03-12 03:37 UTC, jinyoungchoi95 commented on src/main/java/domain/deck/UserDeck.java
> +    public void addCard(Card card) {
공통된 것을 묶는 것으로 `UserDeck`이 만들어진 것인데, 하위에서 상속시에 메소드 변경이 일어난다면 캡슐화가 깨지지 않나요?

2024-03-12 03:37 UTC, jinyoungchoi95 commented on src/main/java/domain/deck/DealerDeck.java
> +    private final static int ADD_CONDITION = 16;
```suggestion
    private static final int ADD_CONDITION = 16;
```

2024-03-12 03:37 UTC, jinyoungchoi95 commented on src/main/java/domain/deck/UserDeck.java
> +    protected final List<Card> cards;
public field로 외부 노출 지양하고, private을 통해서 외부의 호출을 막는데 protected 도 상속과 패키지 한정이긴 하지만 외부 노출이 되는 것 아닌가요?

2024-03-12 03:37 UTC, jinyoungchoi95 commented on src/main/java/domain/user/Dealer.java
> +        throw new IllegalStateException("딜러 이름을 불러오는 방식이 잘못되었습니다.");
👍

2024-03-12 03:37 UTC, jinyoungchoi95 commented on src/main/java/domain/user/User.java
> +    public abstract boolean isPlayer();
전반적으로 abstract의 위치가 일관성있지가 않는데 명오의 메소드 배치 기준이 있을까요?

2024-03-12 03:37 UTC, jinyoungchoi95 commented on src/main/java/domain/user/Users.java
> +        });
(반영하지 않으셔도 됩니다.) 개인적으로 이런 형태라면 for문을 그냥 써도 되지 않을까 싶어요.

2024-03-12 03:37 UTC, jinyoungchoi95 commented on src/main/java/domain/user/Users.java
> +    }
```suggestion
    private void throwExceptionIfContains(List<Player> distinctPlayers, Player player) {
        if (distinctPlayers.contains(player)) {
            throw new IllegalArgumentException("중복된 이름은 입력할 수 없습니다: %s".formatted(player.getNameValue()));
        }
    }
```
한칸을 띄우지 않아도 line이 벗어나지 않는데 띄운 이유가 있을까요? 보통은 이렇게 괄호를 통으로 내리진 않아요.

2024-03-12 03:37 UTC, jinyoungchoi95 commented on src/main/java/domain/game/Result.java
> +    DRAW(Integer::equals);
`BiPredicate`를 잘 활용해주셨네요 :)

2024-03-12 03:37 UTC, jinyoungchoi95 commented on src/main/java/domain/game/Result.java
> +        };
> else 예약어를 쓰지 않는다.
> else 예약어를 쓰지 말라고 하니 switch/case로 구현하는 경우가 있는데 switch/case도 허용하지 않는다.
> 힌트: if문에서 값을 반환하는 방식으로 구현하면 else 예약어를 사용하지 않아도 된다.

2024-03-12 03:37 UTC, jinyoungchoi95 commented on src/main/java/domain/game/Result.java
> +                        new IllegalStateException("Result의 BiPredicate가 모든 경우의 수를 포함하지 않습니다."));
메세지에 도메인 지식이 담기면 좋을 것 같아요.

`IllegalStateException`을 어떤 경우에 활용하시나요?

2024-03-12 03:37 UTC, jinyoungchoi95 commented on src/main/java/domain/game/Result.java
> +public enum Result {
무슨 결과인지 이름만으로 확인할 수 있도록 변경해주세요.

2024-03-12 03:37 UTC, jinyoungchoi95 commented on src/main/java/domain/game/PlayerResults.java
> +    private final Map<Player, Result> playerResults;
Map 활용 좋네요 👍

2024-03-12 03:37 UTC, jinyoungchoi95 commented on src/main/java/domain/TotalDeck.java
> +    }
```suggestion
    public TotalDeck(List<Card> cards) {
        totalDeck = new ArrayDeque<>(cards);
    }
```
로 표현될 수 도 있겠네요.

2024-03-12 03:37 UTC, jinyoungchoi95 commented on src/main/java/domain/TotalDeckGenerator.java
> +                        .map(number -> new Card(shape, number)))
한칸에 점을 한개만 찍는다라는 규칙이 무엇때문에 요구하는지 명오는 어떻게 생각하시나요?

1. flatMap의 내부 함수는 별도의 메소드로 분리하면 좋을 것 같아요. stream을 활용하는 근본적인 이유가 무엇이라고 생각하시나요?
2. static은 객체지향과 멀지 않나요? 그런 관점에서 `TotakDeckGenerator`은 객체지향을 벗어나는 설계인 것 같은데 어떻게 생각하시나요?

2024-03-12 03:37 UTC, jinyoungchoi95 commented on src/main/java/domain/Command.java
> +public enum Command {
domain보다는 view에 있어야하지 않을까요?

2024-03-12 03:37 UTC, jinyoungchoi95 commented on src/main/java/domain/Command.java
> +                .filter(command -> command.command.equals(input))
`command.command`와 같은 호출때문에 class 네임과 필드 네임은 보통 다르게 가져가는편이에요.

2024-03-12 03:37 UTC, jinyoungchoi95 commented on README.md
> +### 기능
요구사항 잘 작성해주셨는데 잘 설계해주신 현재의 객체들을 기준으로 구체적으로 요구사항을 작성해보는건 어떨까요?

2024-03-12 03:37 UTC, jinyoungchoi95 commented on src/main/java/controller/BlackjackRunner.java
> +                ));
👍 👍

2024-03-12 04:24 UTC, HyungHoKim00 commented on src/main/java/domain/user/User.java
> +    public abstract boolean isPlayer();
저의 기준은

1. getter를 하단에 둔다.
2. abstract를 마지막에 둔다.
3. private 메서드의 경우 사용되는 public 메서드의 하단에 둔다.

의 순서를 지키려고 하고 있습니다.

그래서 우선 getter를 하단으로 분류하고, 그 중 abstract를 하단으로 두었습니다!

2024-03-12 04:28 UTC, HyungHoKim00 commented on src/main/java/domain/user/Users.java
> +        });
맞는 말씀입니다!!

코드가 한줄일 때는, 람다식으로 forEach를 활용하면 한 줄로 작성할 수 있기 때문에 가독성도 좋지만, 그것이 아니라면 오히려 향상된 for문이 더 가독성이 좋을수도 있겠네요~~

2024-03-12 04:35 UTC, HyungHoKim00 commented on src/main/java/domain/game/Result.java
> +        };
switch/case를 사용하지 말라고 하는 이유는, else 예약어 사용을 방지하기 위함이라고 적혀있었습니다.

개선된 switch문은 else와 같은 로직을 사용하지 않기 때문에, 사용하여도 된다고 생각하여 사용했습니다.

추가적으로, 모든 Enum 케이스가 들어가지 않으면 컴파일 단계에서 오류가 발생하기 때문에, 실수를 줄이기에 용이하다고 느꼈고,

가독성 또한 굉장히 직관적이라 느껴 개선된 switch문을 사용하게 되었습니다!

2024-03-12 04:38 UTC, HyungHoKim00 commented on src/main/java/domain/game/Result.java
> +                        new IllegalStateException("Result의 BiPredicate가 모든 경우의 수를 포함하지 않습니다."));
IllegalStateException을 사용하는 경우는, 개발자가 의도치 않은 실수를 발생시킨 경우입니다.

그렇기 때문에, 에러 메세지에 코드 관련된 문구를 삽입하는 경우가 많았습니다.

메시지에 도메인 지식이 담기면 좋다는 것이, 코드에 대한 설명을 하라는 것이 아니라 로직 상에 어떤 문제가 발생했는 지 설명하라는 말씀이신가요?

2024-03-12 04:44 UTC, HyungHoKim00 commented on src/main/java/domain/Command.java
> +public enum Command {
맞는 말씀입니다!!

저는 지금까지 항상 View에 inputView, OutputView만 존재했어서, 도메인을 단순히 '인풋,아웃풋뷰,컨트롤러가 아닌 애들의 집합' 정도로 사용했던 것 같습니다.

감사합니다!

2024-03-12 05:15 UTC, HyungHoKim00 commented on src/main/java/domain/TotalDeckGenerator.java
> +                        .map(number -> new Card(shape, number)))
한칸에 점을 한개만 찍는다라는 규칙은, 가독성 때문이라고 생각합니다.

동작 순서와 동작 방식을 보기가 편하기 때문이죠!!

---
1. stream을 활용하는 근본적인 이유 역시 가독성이라고 생각합니다 하지만, flatMap 내부 함수까지 같이 넣어놓는 방식이 가독성을 해치는 것 같네요!

---
2. static에 대한 공부가 조금 부족했던 것 같습니다.

TotalDeckGenerator를 static으로 사용한 이유는, 메서드를 불러올 때마다 52장의 카드를 불러와주는 기능 하나만 잘 수행하길 바랬기 때문에, 굳이 객체를 생성할 필요가 없다고 생각했습니다.

오리의 질문을 보고 자료를 찾아봤는데, 제가 static을 사용한 이유가 전부 반박당한 기분이었습니다.

1. 객체를 생성하지 않기 때문에 메모리적으로 유리하지 않을까?
오히려 static 메서드가 프로그램이 사라질 때 까지 메모리를 차지하기 때문에, 이는 잘못된 생각이었습니다.

2. 다형성이 필요 없는데, 객체일 필요가 있을까?
역으로, 다형성이 필요 없는 클래스가 설계된 것이 객체 지향 위반임을 느꼈습니다.

이를 통해, 저의 설계가 객체 지향적이지 않다는 것을 배우게 되었습니다.

감사합니다!!

2024-03-12 05:22 UTC, HyungHoKim00 commented on src/main/java/domain/user/Users.java
> +    }
한줄을 띄우지 않아도 라인 컨벤션을 벗어나진 않지만, 에러 메세지가 긴 상황에서 줄을 나누는 것이 더 보기 편하게 느껴졌습니다.

하지만, 저 괄호 하나만 내려진 부분은 불필요한 개행이라는 생각이 드네요.

수정했습니다!

2024-03-12 09:54 UTC, HyungHoKim00 commented on src/main/java/domain/user/Users.java
제가 추상화에 몰두하고 있었다고 느꼈습니다.

Player와 Dealer에 중복된 로직이 많으니까, 추상화를 하는 것이 중복 코드를 제거하기 가장 좋은 방법이라 생각했습니다.

추상화를 없애면 어떻게 될지는 짐작하기 어려웠지만, 일단 해봤습니다. 하면서도 맞는지는 의문이 좀 들었던 것 같습니다.

결과적으로는, 오히려 중복된 코드도 줄고 어느 정도 책임이 분배되었다고 느꼈습니다.

Player와 Dealer에 있는 똑같이 생긴 몇몇 메서드는 아직 신경이 쓰이지만, 이를 추상화를 사용하지 않고 어떻게 없애야할지는 잘 모르겠습니다.

또한, 현재 Users에게 책임이 너무 없는것은 아닌가? 하는 느낌도 듭니다.

어떻게 생각하시는 지 궁금합니다!!

2024-03-12 09:55 UTC, HyungHoKim00 commented on README.md
> +### 기능
허걱 리뷰 요청 남기고 나니 이 부분을 안한 것을 확인했네요 ㅜㅜ

다음엔 반드시 반영하겠습니다!!

2024-03-12 15:54 UTC, jinyoungchoi95 commented on src/main/java/domain/TotalDeckGenerator.java
> +                        .map(number -> new Card(shape, number)))
> stream을 활용하는 근본적인 이유 역시 가독성이라고 생각합니다 하지만, flatMap 내부 함수까지 같이 넣어놓는 방식이 가독성을 해치는 것 같네요!

stream이 java 8에서 처음 등장했던 이유와 java 8에서 어떤 기능들이 함께 추가되었는지를 공부해보시면 좋을 것 같아요. stream은 기본적으로 가독성을 위함이 아닌 함수형프로그래밍을 위해서 나왔어요. 이부분은 제가 알려드리기보다는 직접 학습해보시는 것이 좋을것 같아요. 레벨 1에서는 다른책들보다는 모던 자바 인액션을 완주해보는걸 추천드려요.

> static

static이 필요한 부분에서 잘 사용될 때도 있어서 사용하면 물론 좋은점은 있겠지만 말씀하신대로 객체지향과는 멀어요. 레벨 1 미션기간은 온전히 자바를 활용한 객체지향을 배울수 있는 좋은 시기이기 때문에 최대한 사용하지 않은채로 레벨1을 마무리하시면 좋은 경험들을 얻어가실거에요.

2024-03-12 15:56 UTC, jinyoungchoi95 commented on src/main/java/domain/game/Result.java
> +                        new IllegalStateException("Result의 BiPredicate가 모든 경우의 수를 포함하지 않습니다."));
> IllegalStateException을 사용하는 경우는, 개발자가 의도치 않은 실수를 발생시킨 경우입니다.

IllegalStateException은 표준 예외로 개발자의 의도치 않은 실수보다는 현재의 상황에서 그 input값을 처리하지 못할때에요. (정상적인 케이스였다면 해당 값을 처리할 수 있지만 특정 상황으로 인하여 처리를 못하는거죠)

> 메시지에 도메인 지식이 담기면 좋다는 것이, 코드에 대한 설명을 하라는 것이 아니라 로직 상에 어떤 문제가 발생했는 지 설명하라는 말씀이신가요?

네 예외 메시지에는 BiPredicate의 실행내용보다는 블랙잭 도메인의 문제상황에 대해서 설명해주는 것이 좋을 것 같아요.

2024-03-12 16:16 UTC, jinyoungchoi95 commented on src/main/java/domain/user/Users.java
`같은(중복된) 코드 제거 == 상속`이라는 명제가 어느정도 들어가있어 헷갈리는 것도 없지않아 있는 것 같아요. (아니라면 넘어가주셔도 되어요.) 개인적으로 핵심은 단순히 똑같은 코드 2개를 무조건 1개로 만들라가 아니라 어떤 중복을 이야기하느냐, 그걸 어떻게 제거하느냐라고 생각해요.

> Player와 Dealer에 중복된 로직이 많으니까, 추상화를 하는 것이 중복 코드를 제거하기 가장 좋은 방법이라 생각했습니다.

추상화의 목적을 한번 다시 생각해보면 추상화가 "중복"을 위한 것일까요? 단어 그자체만을 바라보면 구체적이지 않고 추상적이다에요. 이건 중복된 똑같은 코드 그 자체를 없애는 것이 목적이 아닌 추상적으로 표현하기 위한 것이에요. (추상을 다르게 표현할 말이 더 안떠오르네요. 이해가 안된다면 뭉뚱거리다정도로 이해해주세요.)

그래서 자동차미션에서 추상화를 통해 "랜덤한 움직임"이라는 구현체를 "움직임"으로 추상화한것이구요.

> Player와 Dealer에 있는 똑같이 생긴 몇몇 메서드는 아직 신경이 쓰이지만, 이를 추상화를 사용하지 않고 어떻게 없애야할지는 잘 모르겠습니다.

처음이야기한대로 똑같이 생긴 코드는 맞지만 문제될 건 없어보여요. `Hand`에서 `Player`나 `Dealer`가 똑같이 가졌어야할 로직을 충분히 중복을 제거해주고 있구요. "클린 코드", "좋은 코드"의 기준은 사람마다 다를 수 있지만 제가 생각하기에는 같은 코드가 무조건 없는 코드는 아니에요. 중복 코드만 단순히 제거한 코드보단 설계를 통한 변경의 여파가 적은 코드가 오히려 더 좋은 코드가 아닐까요?

> 현재 Users에게 책임이 너무 없는것은 아닌가? 하는 느낌도 듭니다.

`GameUsers`가 책임이 너무 없어보인다면 블랙잭 게임을 실행하는 최상위에서 `Players`와 `Dealer`를 각각 사용하도록 해도 무방할 것 같아요. 근데 개인적으로 지금도 `generatePlayerResults`와 같은 책임을 잘 가지고 있는데 어떻게 생각하시나요?

2024-03-12 16:29 UTC, jinyoungchoi95 approved these changes
안녕하세요 명오 😄

추가 피드백도 잘 반영해주셨네요. 질문주신 내용과 코드에 몇가지 코멘트 달아두었으니 다음 단계 진행하면서 함께 확인부탁드려요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-03-12 16:29 UTC, jinyoungchoi95 commented on src/main/java/domain/DeckGenerator.java
> +                .collect(Collectors.toList());
```suggestion
        this.cards = Arrays.stream(Shape.values())
                .flatMap(this::makeCardsByShape)
                .collect(Collectors.toList());
```
(반영하지 않으셔도 됩니다.) 생성자에서는 this를 붙여주는 것이 좀 더 명시적이긴해요.

2024-03-12 16:29 UTC, jinyoungchoi95 commented on src/test/java/domain/DeckGeneratorTest.java
> +    }
`generate()`는 shuffle도 하기 때문에 shuffle에 대한 부분도 테스트되면 좋을 것 같아요.

2024-03-12 16:29 UTC, jinyoungchoi95 commented on src/main/java/domain/user/Dealer.java
> +    void putStartCards(Deck deck) {
default 접근 제어자는 의도된 부분일까요?

2024-03-12 16:29 UTC, jinyoungchoi95 commented on src/main/java/domain/user/Hand.java
> +    protected final List<Card> cards;
```suggestion
    private final List<Card> cards;
```
👀

2024-03-12 16:29 UTC, jinyoungchoi95 commented on src/main/java/domain/user/Players.java
> +    private static void throwExceptionIfContains(List<Player> distinctPlayers, Player player) {
```suggestion
    private void throwExceptionIfContains(List<Player> distinctPlayers, Player player) {
```
제거되어도 될 것 같아요.

2024-03-12 16:29 UTC, jinyoungchoi95 commented on src/main/java/view/InputView.java
> +public class InputView {
사용하지 않는 생성자는 private으로 막아주세요 :)
```java
private InputView() {
}
```

2024-03-12 16:29 UTC, jinyoungchoi95 commented on src/main/java/view/viewer/card/NumberViewer.java
> +            case ACE -> "A";
enum으로 view string 정보와 매칭되는 number를 가진 객체를 만들어도 되지 않을까요?

2024-03-12 16:30 UTC, merged

2024-03-13 00:42 UTC, HyungHoKim00 commented on src/main/java/domain/DeckGenerator.java
> +                .collect(Collectors.toList());
동의합니다!! 놓쳤던 부분이네요..ㅎㅎ 꼼꼼하게 검수하겠습니다.

2024-03-13 00:43 UTC, HyungHoKim00 commented on src/main/java/domain/user/Dealer.java
> +    void putStartCards(Deck deck) {
맞습니다! 사실, putStartCards가 public으로 사용되어 controller에서 불러와지는 것을 방지하고 싶었습니다.

하지만, addCard가 public인 이상 의미가 있나 하는 생각은 드네요..

2024-03-13 00:45 UTC, HyungHoKim00 commented on src/main/java/domain/user/Hand.java
> +    protected final List<Card> cards;
기존에 protected로 사용한 이유는, DealerDeck에서 불러오고 싶기 때문이었습니다.

하지만, Hand가 사라진 이상 private으로 바꾸는게 맞겠네요!!

추가적으로, DealerDeck에서 불러오기 위해 protected로 사용하는 방법 역시 잘못된 상속이 아닐까? 라는 의문도 들었습니다.

2024-03-13 10:43 UTC, HyungHoKim00 commented on src/main/java/domain/user/Users.java
맞는 말씀인 것 같습니다!

오히려 제가 GameUsers에게 책임을 많이 넣어주고싶지 않았나 싶네요.

클래스가 늘어나는 것을 두려워하지 않아야 할 것 같습니다 ㅎㅎ