[1단계 - 블랙잭 게임 실행] 테드(김규태) 미션 제출합니다.
woowacourse/java-blackjack pull request #604
Opened 2024-03-08 06:46 UTC by Kimprodp

안녕하세요, 제이😊

블랙잭  1단계 블랙잭 게임 실행 미션 진행하여 리뷰 요청 드립니다.

미션을 진행하면서 궁금한 점 코멘트 같이 남깁니다.

이번 미션에서는 추가된 요구사항 중 `딜러와 플레이어에서 발생하는 중복 코드를 제거해야 한다.` 와 `3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.` 와 같은 내용이 있습니다.

중복 코드를 제거하기 위해서 상속을 사용하면서 두 번째 요구 사항을 지키기 위한 필드 개수에 대해 의문점이 생겼습니다.
부모 클래스에서 정의된 인스턴스 변수는 자식 클래스에서도 상속받아 사용할 수 있습니다. 이때 두 번째 요구 사항의 클래스가 가질 수 있는 최대 인스턴스 변수 중 하나로 카운트 해야 하는지 고민 했습니다. 미션을 진행하면서 내린 결론은 자식 클래스 코드 내부에는 직접 나타나진 않았지만, 필드를 상속 받을 때 자식 클래스의 인스턴스 마다 다른 값을 가질 수 있으므로 카운트 하는 것이 맞다고 생각하고 제한하였습니다. 이 부분에 대한 제이의 생각을 듣고 싶습니다.

2024-03-08 15:40 UTC, JunHoPark93 requested changes
안녕하세요 테드~
1단계 구현 깔끔하게 잘 해주셨네요!
크게 반영하실 부분은 없어보이고 간단한 피드백들만 확인주시면 될거같아요. 고생많으셨습니다~

2024-03-08 15:40 UTC, JunHoPark93 commented on src/main/java/blackjack/controller/BlackjackController.java
> +    }
메서드를 최대한 작게 유지해보면 어떨까요?
개인적으로 극단적인 연습이 도움이 많이 되는거같아요.

2024-03-08 15:40 UTC, JunHoPark93 commented on src/main/java/blackjack/model/deck/HandDeck.java
> +    }
외부에서 cards를 수정하면 어떻게 될까요?

2024-03-08 15:40 UTC, JunHoPark93 commented on src/main/java/blackjack/model/deck/HandDeck.java
> +            throw new IllegalArgumentException("[ERROR] 중복된 카드는 받을 수 없습니다.");
에러메세지에 어떤 card인지에 대한 값이 표시가 된다면 추후 트래킹에 유리할 수 있습니다

2024-03-08 15:40 UTC, JunHoPark93 commented on src/main/java/blackjack/model/gamer/Player.java
> +    private final Name playerName;
> 이번 미션에서는 추가된 요구사항 중 딜러와 플레이어에서 발생하는 중복 코드를 제거해야 한다. 와 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다. 와 같은 내용이 있습니다.
> 
> 중복 코드를 제거하기 위해서 상속을 사용하면서 두 번째 요구 사항을 지키기 위한 필드 개수에 대해 의문점이 생겼습니다.
> 부모 클래스에서 정의된 인스턴스 변수는 자식 클래스에서도 상속받아 사용할 수 있습니다. 이때 두 번째 요구 사항의 클래스가 가질 수 있는 최대 인스턴스 변수 중 하나로 카운트 해야 하는지 고민 했습니다. 미션을 진행하면서 내린 결론은 자식 클래스 코드 내부에는 직접 나타나진 않았지만, 필드를 상속 받을 때 자식 클래스의 인스턴스 마다 다른 값을 가질 수 있으므로 카운트 하는 것이 맞다고 생각하고 제한하였습니다. 이 부분에 대한 제이의 생각을 듣고 싶습니다.

저도 카운트가 되는게 맞다고 생각합니다. 의의자체가 중복을 제거하는데 있고 지금 구조는 요구사항을 만족하고있습니다. 마치 이중 반복문 내부를 함수로 추출해 1depth처럼 보이게 했지만 실제로는 O(n2)로 동작하는것과 유사한거같네요.

2024-03-08 15:40 UTC, JunHoPark93 commented on src/main/java/blackjack/model/result/PlayersResult.java
> +    private final Map<Player, Result> playerResult = new LinkedHashMap<>();
LinkedHashMap을 사용하셨네요~ 테스트코드에서 의도하신 자료구조의 특성이 검증되고있을까요?

2024-03-08 15:40 UTC, JunHoPark93 commented on src/main/java/blackjack/view/OutputView.java
> +    }
필요한 arguments만을 받고있는지 확인해보면 좋을거같아요~

2024-03-08 15:40 UTC, JunHoPark93 commented on src/main/java/blackjack/model/deck/PlayingDeck.java
> +    }
(이거는 진짜 그냥 참고만해주세요)
전체적으로 잘 해주셔서 재밌어보이는 주제하나 남깁니다..

poll을 했을시 비어있으면 null이라 isEmtpy연산을 한번 안할 수도있어보이는데요, 지금상황에서는 별차이없겠지만 queue자체가 빠르게 변화하고 있는 상황에서 isEmpty확인이후에 연산을 하고있는데 그사이에 queue가 차는 상황이 발생할수도있을거같아요. 나중에 프로젝트할때 특정 상황을 가정하고 자료구조에 대한 테스트도해보면 좋을거같아요.

남긴이유는 테드가 다양한 자료구조를 사용해보고 계셔서 남겼어요~

2024-03-08 15:40 UTC, JunHoPark93 commented on src/main/java/blackjack/model/gamer/Name.java
> +    }
지난 번 미션에서 경험하셨던 상수화 관련해서 10이라는 숫자도 추출해보면 좋을거같아요. 요구사항이 변경됐을때 수정해야하는 부분을 최소화 할 수 있습니다.

진짜 별거 아닌것처럼 보여도, 실제로 프로덕트에서 장애가 나거나 의도치 않은 결과가 나오는 경우에 이런 사소한 부분에서의 실수가 원인이 되는 경우가 많습니다.

2024-03-09 17:31 UTC, Kimprodp commented on src/main/java/blackjack/model/deck/HandDeck.java
> +    }
`getCards`를 통해 받아온 `Card`에서 특정 메서드를 통해 조건만 부합한다면 `score`값을 수정할 수 있을 것으로 확인했습니다. 위 메서드에서 반환 시, 값을 복사하여 반환해서 도메인의 데이터에 영향이 가지 않도록 수정했습니다.

2024-03-09 17:32 UTC, Kimprodp commented on src/main/java/blackjack/model/deck/HandDeck.java
> +            throw new IllegalArgumentException("[ERROR] 중복된 카드는 받을 수 없습니다.");
어떤 card가 중복되는지 확인 할 수 있게 card의 속정 정보를 포함하는 것으로 수정했습니다

2024-03-09 17:34 UTC, Kimprodp commented on src/main/java/blackjack/model/result/PlayersResult.java
> +    private final Map<Player, Result> playerResult = new LinkedHashMap<>();
순서가 보장되야 한다면 해당 내용도 테스트를 해야할 것 같습니다. 이번 피드백 주신 내용을 반영하면서 `PlayerResult `클래스에서 `getter`를 사용하지 않고 특정 `Player`의 결과값만을 반환하는 것으로 변경하여, 순서가 보장되지 않아도 될 것 같아 `HashMap`으로 변경하였습니다.

2024-03-09 17:45 UTC, Kimprodp commented on src/main/java/blackjack/model/deck/PlayingDeck.java
> +    }
멀티 스레드 환경이였다면, 다른 스레드에서 동시에 접근할 경우 `isEmpty`가 수행되는 동안이나 수행 직후 `queue`가 찰 수 있을 것 같네요. `ConcurrentLinkedQueue `와 같은 멀티 스레드 환경에서 안정성을 보장하는 자료구조를 사용할 수 있겠으나, 현재 단계 에서는 말씀 주신 것처럼 별 차이가 없을 것 같아 poll 시점에서 null 반환 여부를 검증하는 것으로 수정했습니다! 해당 자료 구조에 대해서는 아직 어려워서 더 공부해봐야겠네요. 감사합니다!

2024-03-09 17:46 UTC, Kimprodp commented on src/main/java/blackjack/controller/BlackjackController.java
> +    }
메서드 분리가 가능한 부분은 최대한 분리하여 단위를 최대한 작게 할 수 있도록 수정했습니다!

2024-03-09 17:48 UTC, Kimprodp commented on src/main/java/blackjack/model/gamer/Player.java
> +    private final Name playerName;
고민해서 결론 내렸지만 헷갈리는 부분이였는데 의견 감사합니다!😁

2024-03-09 17:49 UTC, Kimprodp commented on src/main/java/blackjack/model/gamer/Name.java
> +    }
상수화 처리 적용했습니다. 더 꼼꼼히 살펴야겠어요..👍

2024-03-10 11:03 UTC, JunHoPark93 approved these changes
안녕하세요 테드~
리뷰 반영 빠르게 잘 해주셨네요.
추가 코멘트 하나 남겼는데 다음 단계 진행하실때 참고부탁드립니다
다음 단계에서 뵐게요!

2024-03-10 11:03 UTC, JunHoPark93 commented on src/main/java/blackjack/controller/BlackjackController.java
> +    }
GameResult 라는 객체가 언제 가용상태로 되는지 알기가 힘든거같아요.
"결과"라는것을 계산할때 제일 바깥 호출부에서는 한번의 연산을 수행해서(내부적으로 여러과정이 있을수있겠지만) 결과를 만들곤하는데요, 현재구조는 gameResult라는 빈 객체를 만들어서 플레이어와 딜러계산을 모두 명시적으로 태워야 가용상태가 되는 구조입니다. 
불안정한 구조로 보이는데 테드 생각은 어떤가요?

2024-03-10 11:03 UTC, merged

2024-03-14 07:20 UTC, Kimprodp commented on src/main/java/blackjack/controller/BlackjackController.java
> +    }
controller에서 결과를 계산하는 구조가 다 노출되게 되니 말씀처럼 불안정해 보이는 것 같습니다. step2 에서는 게임 규칙을 관리하는 클래스로 보내 결과를 처리하도록 변경하였습니다.