[1단계 - 블랙잭 게임 실행] 켈리 미션 제출합니다.
woowacourse/java-blackjack pull request #615
Opened 2024-03-08 07:40 UTC by kelly6bf

만나서 반가워요 찰리! 블랙잭 리뷰 잘 부탁 드립니다!!! 🥰

## 설명이 필요한 도메인 정보
### 딜러 승리 조건
사실 블랙잭을 태어나서 처음 접하기도 했고 검색해도 규칙이 잘 와닿지 않아서 페어와 협의하에 다음과 같이 임의적으로 딜러 승리 규칙을 결정하였습니다.
- 딜러의 손패가 블랙잭일경우 무조건 딜러 승리
- 플레이서의 손패가 버스트일경우 무조건 딜러 승리
- 위 두 조건에 부합하지 않을시 딜러와 플레이어의 손패합을 비교해서 딜러가 크거나 같으면 무조건 딜러승리
- 위 세 조건에 하나라도 포함되지 않으면 플레이어 승리

## 리뷰어님께 여쭤보고 싶은 내용
### 에이스 숫자 변환 책임에 대한 결정
요구사항을 지키기 위해서는 상황에 따라 에이스의 숫자를 1 혹은 11로 변경하는 로직을 작성할 필요가 있었습니다. 페어와 논의하며 이 역할을 맡을 객체 후보를 선정하였고 각각의 장단점을 떠올리며 나름의 트레이드 오프를 진행하였습니다.

#### PlayingCard객체가 직접 맡는다.
해당 객체는 카드의 모양과 숫자를 멤버로 가진 객체이므로 변경이 필요한 정보를 가진 객체가 직접 변경하자는 의견으로 후보에 올랐습니다. 해당 객체가 역할을 수행할 경우 떠올릴 수 있는 장담점은 다음과 같습니다.
- 장점 : 게임에 굉장히 중요한 요소인 카드 번호를 변경시키는 작업이므로 해당 정보를 관리하는 객체가 직접 수행할 수 있게 함으로써 데이터의 잘못된 변경을 최대한 억제할 수 있다.
- 단점: (현재 저희가 선택한 방식에 따르면) 카드가 이 작업을 수행할 경우 버스터 기준(21을 넘는다.)을 알게된다. 카드가 알아도 괜찮은 정보가 맞을지 모르겠다.

#### Hand객체가 변경한다.
Hand는 참가자들의 손패를 표현한 객체이며 손패에 있는 카드들을 멤버로 가집니다. 따라서 손패합을 구하는 역할을 담당하며 손패합을 구할 때 상황에 따라 에이스의 값을 유동적으로 변경해서 더해주자는 의견이었습니다.
- 장점 : (사실 페어랑 대화하면서도 크게 와닿는 장점이 오지는 않았습니다.)
- 단점 : 카드의 정보가 1 혹은 11로 변경될 수 있다는 정보를 Hand가 알게되는데 타 도메인의 중요 정보를 지금 상황에서 굳이 손패가 알아야 하는가 싶은 의문이 들어 단점이라고 생각한다.

막상 글로 풀어보려고 하니 각 장단점의 대한 근거를 제대로 설명 못하고 있는거 같아 아쉽지만, 저희가 생각의 흐름이 리뷰어님이 보셨을 때 나름의 합리성을 가지는지 의견을 구하고 싶습니다.

2024-03-08 13:18 UTC, Gomding requested changes
안녕하세요 켈리!
블랙잭 미션을 함께하게된 찰리입니다 🙇 

질문에 대한 답변과 함께 몇가지 코멘트 남겼으니 확인 부탁드려요!

궁금한 점 있으면 언제든 코멘트나 DM 남겨주세요 🙏

2024-03-08 13:18 UTC, Gomding commented on src/main/java/Application.java
> +        blackJackGame.run();
딜러가 버스트임에도 딜러가 승리하는것으로 판단되고 있어요 😭 
수정 부탁드려요!

![image](https://github.com/woowacourse/java-blackjack/assets/57378410/1976107e-4a05-4437-9767-f6da2761d8e8)

2024-03-08 13:18 UTC, Gomding commented on src/main/java/domain/participant/Hand.java
> +    public int getCardsNumberSum() {
totalValue, totalScore 등의 이름은 어떠신가요! 😄 

+) 손패의 점수를 의미하는 객체도 만들어보는걸 켈리는 어떻게 생각하시나요?

```java
public Score getCardsNumberSum() {
```

2024-03-08 13:18 UTC, Gomding commented on src/main/java/domain/constant/GameOption.java
> +    public static final int BLACKJACK_CONDITION = 21;
해당 상수를 따로 관리하면 어떤 장점이 있을까요?

Hand에서 주로 사용될 값이라 생각해서요!

그럴일은 없겠지만 블랙잭 점수가 22점으로 변경된다면
다른 개발자는 어떤 객체가 변경될것을 예측할까요? 🤔

2024-03-08 13:18 UTC, Gomding commented on src/test/java/domain/participant/DealerTest.java
> +    void getGameResultsTest() {
딜러와 플레이어의 다양한 상황에 대한 게임 결과를 커버하는 테스트가 있으면 좋겠어요!

블랙잭에는 게임 결과에 대한 케이스가 다수 존재하니까요!
- 딜러가 버스트 플레이어가 버스트
- 딜러가 버스트 레이어가 21점 이하
- 딜러가 21점 이하 플레이어가 21점 이하

2024-03-09 04:29 UTC, kelly6bf commented on docs/README.md
> +# 기능 명세서
사실 조금만 더 서치한다면 충분히 찾아서 반영할 수 있는 정보일 텐데 스스로 빨리 완성해야 한다는 생각에 합리화를 한 게 아닐지 부끄럽네요..! 이번에는 승리 규칙을 조사해서 최대한 실제 블랙잭 규칙에 맞게 적용해 보겠습니다! 😂

2024-03-09 04:40 UTC, kelly6bf commented on src/main/java/domain/playingcard/Deck.java
> +        playingCards.remove(0);
제 부족한 자바기본기를 다시금 깨달아버렸네요..ㅎ remove를 호출하면 제거되는 대상 요소가 반환되니 바로 return문으로 넘기면 되겠군요..!
<img width="1690" alt="image" src="https://github.com/woowacourse/java-blackjack/assets/104609807/ebe2baf9-dd7c-4f48-916a-40ef5035941f">

2024-03-09 04:42 UTC, kelly6bf commented on src/main/java/domain/playingcard/Deck.java
> +        Collections.shuffle(playingCards);
규칙을 찾아보니 카드를 뽑고 바로 섞어야하는 규칙은 없네요..! (다른 크루들도 그러면 딜러 손모가지가 날아ㄱ..)

이 작업은 제거할 필요가 있어 보이네요!

2024-03-09 04:43 UTC, kelly6bf commented on docs/README.md
> +- [x] 참가자들의 게임 결과를 추출한다.
대략적인 메커니즘을 함께 적으면 문서를 읽는 입장에서 더 빠르게 파악할 수 있을거 같네요! 문서 내용을 추가해보겠습니다!! 😄

2024-03-10 05:17 UTC, kelly6bf commented on src/main/java/domain/playingcard/PlayingCard.java
> +    private int chooseAceValue(final int inputValue) {
리뷰어님 코멘트 참고해서 고민해보겠습니다!

2024-03-10 05:21 UTC, kelly6bf commented on src/main/java/domain/participant/Participant.java
> +public abstract class Participant {
중복되는 코드를 추상 클래스 메서드를 통해 줄일 수 있다는 점이었습니다! 플레이어와 딜러 모두 참가자의 역할인 `덱을 받아 카드를 한 장 뽑은 후 손 패에 추가한다'라는 같은 로직의 행위를 수행하는데 이를 추상 클래스 메서드로 정의하면 중복 코드를 줄일 수 있을 뿐 아니라 두 객체 모두 `참가자`의 관점에서 행위를 바라볼 수 있어 코드를 이해하기도 수월했습니다!

2024-03-10 05:22 UTC, kelly6bf commented on src/main/java/domain/participant/Player.java
> +        return new Player(playerName, Hand.init());
앗.. `딜러`는 시스템에 있어 중요한 표현이니까 플레이어가 지정할 수 없도록 해야겠네요...! 검증 로직을 추가해보겠습니다!

2024-03-10 05:22 UTC, kelly6bf commented on src/main/java/Application.java
> +        blackJackGame.run();
앗 수정하겠습니다!

2024-03-10 05:25 UTC, kelly6bf commented on src/main/java/domain/participant/Hand.java
> +    public int getCardsNumberSum() {
지금 사용한 이름보다는 찰리가 추천해 준 totalScore가 훨씬 와닿는 거 같아요..!

Score객체 역시 해당 메서드가 어떤 값을 넘겨주는 건지 좀 더 명확하게 코드를 작성할 수 있어 좋은 거 같아요..! 딜러와 플레이어의 점수를 비교하는 역할 역시 `Score`에 위임할 수 있겠네요!

2024-03-10 05:27 UTC, kelly6bf commented on src/main/java/domain/participant/Hand.java
> +import static java.util.Collections.unmodifiableList;
클래스명을 모두 적을 필요 없으니 코드 라인의 길이가 줄어든다는 장점이 생각나요! 다만 어떤 경우에서는 클래스명이 함께 있는게 해당 데이터 혹은 메서드가 어떤 역할인지 명확하게 파악하는 효과를 줄 수 있으니 import static이 모든 경우에서 장점을 가지지는 않는거 같네요..!

2024-03-10 05:29 UTC, kelly6bf commented on src/main/java/domain/constant/GameOption.java
> +    public static final int BLACKJACK_CONDITION = 21;
동의합니다..! 아무래도 저 값을 구하는 과정이 Hand에 있다 보니 자연스럽게 Hand 객체가 가지고 있으면서 다른 객체에서 사용해도 괜찮을 거 같네요..!

무엇보다 지금은 상수값이 하나뿐이라 굳이 별도 클래스로 분리할 이점도 없는 거 같아요.

2024-03-10 05:30 UTC, kelly6bf commented on src/test/java/domain/participant/DealerTest.java
> +    void getGameResultsTest() {
동의합니다..! 해당 테스트를 추가해보겠습니다!

2024-03-11 09:15 UTC, Gomding commented on src/main/java/domain/participant/Participant.java
> +public abstract class Participant {
> 참가자의 관점에서 행위를 바라볼 수 있어 코드를 이해하기도 수월했습니다!

좋은 관점이네요! 😄 

상속외에 [다른 방법](https://tecoble.techcourse.co.kr/post/2020-05-18-inheritance-vs-composition/)도 있으니 학습해보면 좋겠어요!

2024-03-11 09:17 UTC, Gomding commented on src/main/java/domain/participant/Hand.java
> +    public int getCardsNumberSum() {
원시값 포장을 하면 객체로써 의미를 부여하고 관련 책임을 부여할 수 있다는 장점이 있죠!
이로 인해 Hand의 책임이 줄어들겠네요 :)

2024-03-11 09:21 UTC, Gomding commented on src/main/java/domain/participant/Hand.java
> +import static java.util.Collections.unmodifiableList;
저는 import static이 코드를 읽는사람에게 자주 혼란을 준다고 생각해요!
해당 클래스에 없는 것이 마치 클래스 내에있는 상수나 static 메서드처럼 보이거든요 😢 

코드수가 줄어들어서 좋다는점에는 동의합니다!
그런데 코드 수를 줄인다는 건 가독성을 위해서인데
이것이 가독성에 악영향을 준다면 사용하는것을 다시 고민봐야겠어요 :)

2024-03-11 10:26 UTC, Gomding requested changes
안녕하세요 켈리!
지난 코멘트 잘 반영해주셨네요~

몇 가지 코멘트 추가로 남겼으니 확인해주세요!

궁금한 점 있으면 언제든 DM 남겨주세요~

2024-03-11 10:26 UTC, Gomding commented on src/main/java/BlackJackGame.java
> +        Deck deck = Deck.init();
BlackJackGame은 Controller 의 역할로 보이는데
Dealer 와 Player Deck 까지 많은 도메인을 의존하는 것으로 보여요

해당 도메인들을 관리하는 객체를 생성하여 BlackJackGame의 부담을 덜어주는것은 어떻게 생각하시나요?

2024-03-11 10:26 UTC, Gomding commented on src/test/java/domain/game/GameResultsTest.java
> +    void playerWinWhenPlayerTotalScoreIsBiggerThenDealersTotalScore() {
테스트 작성 시 매번 메서드 이름을 영어로 고민하고 지정할 때 피로감이 느껴진다면 아래와같이 하셔도 좋습니다 😄 

```java
@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)
class GameResultsTest {
    @Test
    void 플레이어의_손패합이_딜러의_손패합보다_크면_플레이어가_승리한다.() {
```

2024-03-11 10:26 UTC, Gomding commented on src/main/java/domain/participant/Hand.java
> +            result = playingCard.addValue(result);
현재 PlayingCards 의 순서가 Ace, Queen, King의 순서로 있다면 버그가 발생할 것 같아요!

Ace가 11 -> 1 로 바뀌는 상황을 테스트해보면 좋겠어요~

2024-03-11 10:26 UTC, Gomding commented on src/main/java/domain/participant/Hand.java
> +        int result = 0;
점수에 대한 객체로 Score를 만들어주셨으니
점수 계산에 대한 로직을 Score에게 부여해보면 어떨까요~

```java
Score result = Score.ZERO;
for (PlayingCard playingCard : playingCards) {
    result = result.sum(playingCard.getValue);
```

모든 카드의 점수를 구한 뒤 ACE의 점수 변경을 판단해보는건 어떻게 생각하시나요?

2024-03-11 10:26 UTC, Gomding commented on src/main/java/domain/playingcard/Deck.java
> +    private final List<PlayingCard> playingCards;
카드는 보통 제일 위에서 한 장씩 뽑는데요
이럴 때 사용할 수 있는 자료구조를 사용해보면 어떨까요 😄 

java의 Queue 인터페이스와 그 구현체들을 학습해보죠!

2024-03-11 10:26 UTC, Gomding commented on src/main/java/domain/playingcard/Deck.java
> +        return new Deck(playingCards);
생성할 때 한 번만 섞어주도록 변경하셨군요 👍 

한 단계 더 나아가서

카드는 매번 52장의 형태가 정해져있으니
캐싱해두는것이 어떨까요?

2024-03-11 10:38 UTC, Gomding commented on src/main/java/domain/participant/Participant.java
> +        return this instanceof Dealer;
instanceof 를 지양하는것이 좋아요!
여기서의 문제점은 Participant가 자식 타입인 Dealer를 알고있다는 것이 문제라고 생각해요!

해당 메서드를 추상 메서드로 변경하고
각각의 구현체에서 적당한 값을 반환하도록 하는것은 어떠신가요?

2024-03-12 04:59 UTC, kelly6bf commented on src/main/java/domain/participant/PlayerName.java
> +    private static final String DENIED_NAME = "딜러";
view에서 검사하는게 좀 더 좋을거 같습니다..! 말씀하신것처럼 지금은 `딜러`라는 형태로 입력을 받지만 기획에 따라서 `dealer`, `Dealer`라는 값으로 변할 수 있으니까요! (쓰고 보니까 영문 이름에 경우도 `dealer`라는 이름은 사용하지 못하도록 필터링이 필요하겠네요!)

피드백 참고해서 개선해보겠습니다.

2024-03-12 05:00 UTC, kelly6bf commented on src/main/java/domain/participant/PlayerName.java
> +            throw new IllegalArgumentException("설정할 수 없는 플레이어 이름 입니다.");
동의합니다! 지금 작성된 메시지로는 왜 안되는지 의문이 생길거 같아요..! 좀 더 명확한 메시지로 개선해보겠습니다!

2024-03-12 05:00 UTC, kelly6bf commented on src/main/java/domain/playingcard/PlayingCardValue.java
> +        return this == TEN || this == JACK || this == QUEEN || this == KING;
이 방법을 못떠올렸네요..ㅎㅎ.. 너무 좋습니다! 🥰

2024-03-12 05:02 UTC, kelly6bf commented on src/main/java/domain/game/GameResults.java
> +    private static boolean isDealerWin(Dealer dealer, Player player) {
딜러와 플레이어의 승/패를 조합해서 최종 결과를 추출하는건 `GameResults`의 책임으로,
각자의 승리 여부는 `Dealer`와 `Player`에게 맡긴다면 좀 더 명확하게 책임이 분리되는거 같네요! 개선해보겠습니다!

2024-03-12 05:08 UTC, kelly6bf commented on src/main/java/BlackJackGame.java
> +public class BlackJackGame {
이 코드를 작성할 당시에는 `Controller`는 왜 존재하는가? `Controller`의 기준은 무엇인가? 지금의 내 코드에 사용되는 코드는 `Controller`라고 부를 수 있는가라는 의문이 있어 당장은 `~Controller`라는 이름도 붙이지 않았고 별도로 `Controller`패키지도 사용하지 않았습니다!

하지만 이 의문에 대해 주말동안 많은 크루들과 논의를하였고 결론적으로는 지금의 제 코드에 존재하는 `BlackJackGame`은 Controller라고 부를 수 있을거같다는 판단을 내렸습니다.

제가 생각하는 `Controller`의 역할
- 도메인과 View를 중계
- 클라이언트에 요청을 적절한 모델에 위임 후 응답

(적다보니 글이 좀 난잡해졌지만.. 아무튼 Controller 패키지에 넣는것에 동의합니다! 개선해보겠습니다!)

2024-03-12 05:08 UTC, kelly6bf commented on src/main/java/BlackJackGame.java
> +    private void firstDraw(Deck deck, Dealer dealer, List<Player> players) {
동의합니다! 개선해보겠습니다!

2024-03-12 05:08 UTC, kelly6bf commented on src/main/java/BlackJackGame.java
> +//        GameResults gameResults = dealer.determineGameResults(players);
이런 실수를... 😵‍💫

2024-03-12 05:09 UTC, kelly6bf commented on src/main/java/BlackJackGame.java
> +        Deck deck = Deck.init();
안그래도 오늘 페어와 스몰토크를 하면서 나왔던 제안이었는데 매우 흥미로웠습니다! 한 번 적용해보겠습니다!

2024-03-12 05:10 UTC, kelly6bf commented on src/test/java/domain/game/GameResultsTest.java
> +    void playerWinWhenPlayerTotalScoreIsBiggerThenDealersTotalScore() {
엇 이런 방식도 있군요! 감사합니다!

2024-03-12 05:12 UTC, kelly6bf commented on src/main/java/domain/participant/Hand.java
> +            result = playingCard.addValue(result);
안그래도 지금 제 코드의 ACE 값을 결정하는 로직이 잘못 설정되어 있음을 깨달아서 대공사를 진행해보려고 합니다..! ACE의 상황을 테스트 할 수 있는 코드도 작성해보겠습니다!

2024-03-12 05:19 UTC, kelly6bf commented on src/main/java/domain/participant/Hand.java
> +        int result = 0;
동의합니다! 위 코멘트에도 남겼든 에이스 변환 로직이 잘못되어있을을 깨달아서.. 해당 역할을 어디에 위임할지 고민인데 Score가 제격이네요! 수정해보겠습니다!

2024-03-12 05:20 UTC, kelly6bf commented on src/main/java/domain/playingcard/Deck.java
> +    private final List<PlayingCard> playingCards;
Queue를 사용하기 딱 좋은 상황이네요..! 적용해보겠습니다!

2024-03-12 05:21 UTC, kelly6bf commented on src/main/java/domain/participant/Participant.java
> +        return this instanceof Dealer;
이러면 DIP위반이네요..! 수정해보겠습니다!

2024-03-12 05:21 UTC, kelly6bf commented on src/main/java/domain/playingcard/Deck.java
> +        return new Deck(playingCards);
캐싱 전략을 아직 사용해보지 못했는데 이번에 찾아봐야겠네요..! 적용해보겠습니다!

2024-03-13 12:08 UTC, merged

2024-03-14 01:57 UTC, kelly6bf commented on src/main/java/domain/participant/Score.java
> +    }
처음에는 `Score`에게 점수 계산의 책임을 위임하면 좋지 않을까 생각이들어 구현해봤는데 이를 위해서는 `Score`는 내부적으로 `PlayingCard`를 알게 되어 버리니까 무언가 과한 정보를 알게 된다는 생각이 들었습니다..!

리뷰어님이 말씀해주신 것 처럼 점수 계산은 `Hand`에 책임을 주고 `Score`는 점수에 관련된 책임만 수행하면 더 적절한 구조가 나올거 같네요! 반영해보겠습니다!

2024-03-14 01:59 UTC, kelly6bf commented on src/main/java/domain/participant/Participant.java
> +        return hand.getTotalScore().isBustValue();
위에 코멘트 드린 것 처럼 `Hand`가 점수를 계산하는 책임을 가지면 곧바로 버스트 여부를 확인해서 알려주는것도 좋겠네요! 반영해보겠습니다!

2024-03-14 02:00 UTC, kelly6bf commented on src/main/java/domain/participant/Player.java
> +                .isEqualOrLess(MAXIMUM_ENABLE_TOTAL_SCORE);
동의합니다! 개선해볼게요!

2024-03-14 02:01 UTC, kelly6bf commented on src/main/java/domain/game/BlackjackGameResults.java
> +        addGameResult(dealerGameResults, playerGameResults, player, DRAW, DRAW);
이 방식이 좀 더 코드의 중복을 줄일 수 있을거 같네요..! 반영해보겠습니다!

2024-03-14 02:06 UTC, kelly6bf commented on src/main/java/domain/playingcard/Deck.java
> +        Queue<PlayingCard> queue = new LinkedList<>();
사실 막연하게 'Queue를 자바에서 사용하려면 LinkedList를 사용해야해!'라는 생각만 가지고 구현했던거 같습니다..! 말씀해주신 `ArrayDeque`에 대해 찾아봤는데 다음과 같은 이유로 현 상황에서는 `ArrayDeque`를 사용해보는게 좋겠다고 생각이 들어요..!
- `ArrayDeque`는 양쪽 끝에서 추가,제거가 효율적임
- `LinkedList`보다 적은 메모리 소모

참고한 블로그입니다!
https://velog.io/@djawnstj/%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0-Java%EC%9D%98-LinkedList%EC%99%80-ArrayDeque