[1단계 - 블랙잭 게임 실행] 페드로(류형욱) 미션 제출합니다.
woowacourse/java-blackjack pull request #619
Opened 2024-03-08 07:47 UTC by hw0603

(추가예정)

2024-03-09 06:23 UTC, kimhodol requested changes
안녕하세요 페드로 👋 

1단계 구현 잘 해주셨어요 💯 
코드를 잘 짜주셔서 고칠 부분이 많이 보이진 않네요.

코멘트 확인 부탁드립니다 :)

2024-03-09 06:23 UTC, kimhodol commented on src/main/java/blackjack/controller/BlackJackController.java
> +        int extraDrawCount = dealerCardsCount - INITIAL_CARDS_COUNT;
[의견] 딜러에게 추가로 몇 장을 뽑았는지 물어보는게 자연스러울 것 같아요.

2024-03-09 06:23 UTC, kimhodol commented on src/main/java/blackjack/domain/Deck.java
> +    }
[질문] 이 메소드만 static일 이유가 있을까요?

2024-03-09 06:23 UTC, kimhodol commented on src/main/java/blackjack/domain/GameResultBoard.java
> +    public GameResultBoard(Dealer dealer, List<Player> players) {
[질문] Players 일급 콜렉션을 인자로 받아도 되지 않을까요?

2024-03-09 06:23 UTC, kimhodol commented on src/main/java/blackjack/domain/Player.java
> +    }
[의견] private으로 두어도 괜찮을 것 같아요.

2024-03-09 06:23 UTC, kimhodol commented on src/main/java/blackjack/domain/PlayerCards.java
> +        return (int) cards.stream().filter(Card::isAce).count();
[의견] 메서드 체이닝을 할 때는 다른 곳에서처럼 줄 바꿈을 해주세요 :)

2024-03-09 06:23 UTC, kimhodol commented on src/main/java/blackjack/domain/Players.java
> +    }
[질문] static하게 만든 이유가 있나요?

2024-03-09 06:23 UTC, kimhodol commented on src/main/java/blackjack/domain/dto/PlayerDto.java
> +}
[질문] DTO가 도메인 객체를 알고 있어도 될까요?

2024-03-09 06:23 UTC, kimhodol commented on src/main/java/blackjack/view/InputView.java
> +        }
[의견] 의미가 있는 문자열은 상수화해주세요 :)

2024-03-09 06:23 UTC, kimhodol commented on src/main/java/blackjack/view/description/GameResultDescription.java
> +    DRAW(GameResult.DRAW, "무");
[질문] XXXDescription enum 클래스를 별도로 생성한 이유가 궁금해요.

2024-03-09 06:23 UTC, kimhodol commented on src/test/java/blackjack/domain/DeckTest.java
> +        Deck deck = new Deck(cards);
[의견] Deck 생성자는 테스트코드에서만 쓰이지만 소스코드에서 public으로 노출되어있네요. 다른 방법을 찾아볼 수 있을까요?

2024-03-09 12:05 UTC, hw0603 commented on src/main/java/blackjack/controller/BlackJackController.java
> +        );
`Players`가 제일 마지막에 추가한 도메인 객체였는데, 추가 후 제대로 활용을 못 하고 있었네요! 반영했습니다👍

2024-03-09 12:21 UTC, hw0603 commented on src/main/java/blackjack/domain/Deck.java
> +    }
정적 팩토리 메서드인 `public static Deck createShuffledDeck()` 의 static context에서 참조해야 하는 메서드라 static으로 선언했습니다. 외부에서는 접근할 일이 없고, 팩토리 메서드 내부 로직에서 추출된 메서드로 봐 주시면 좋을 것 같아요!

2024-03-09 12:28 UTC, hw0603 commented on src/main/java/blackjack/domain/GameResultBoard.java
> +    public GameResultBoard(Dealer dealer, List<Player> players) {
수정했습니다!

2024-03-09 12:33 UTC, hw0603 commented on src/main/java/blackjack/domain/Players.java
> +    }
항상 정적 팩토리 메서드 내에서 검증 로직을 구현하다가 이번에 생각이 바뀌어 생성자 내부로 검증로직 위치를 이동시켰는데, 예전 습관이 남아서 `static`을 붙여 선언했었네요ㅎㅎ; 수정 완료했습니다!

2024-03-09 12:37 UTC, hw0603 commented on src/main/java/blackjack/domain/dto/PlayerDto.java
> +}
DTO <-> 도메인 객체 간 변환은 어디에서는 해 주어야 하는 것이고, 그 위치는 뷰와 모델을 연결해 주는 책임을 갖는 컨트롤러라고 생각합니다. 다만 컨트롤러에 변환로직 자체가 있어야 할 이유는 없다고 생각해요.

그렇다면 도메인 객체에서 DTO를 만들어주는 로직(domain.toDto()) 혹은 DTO에서 도메인 객체를 전달받아 DTO로 만들어주는 로직(Dto.from(domain)) 둘 중 하나를 선택해야 합니다.

결국 도메인이 DTO에 의존하냐, 아니면 DTO에 도메인이 의존하냐의 문제인데 상대적으로 변화의 가능성이 높은 DTO에 도메인이 의존하기보다는 그 반대로 구현하는 것이 유지보수의 측면에서 유리하다고 판단하여 위와 같이 구현했습니다.

2024-03-09 12:46 UTC, hw0603 commented on src/main/java/blackjack/view/description/GameResultDescription.java
> +    DRAW(GameResult.DRAW, "무");
질문사항에 적어 두었던 것 처럼, 차후 출력 요구사항이 변경되었을 때 변경이 도메인 패키지 안까지 전파되지 않도록 View 패키지 안에서 `XXXDescription` 으로 관리하여 출력에 사용되는 문자열들을 매핑해 주었습니다.

2024-03-09 12:57 UTC, hw0603 commented on src/test/java/blackjack/domain/DeckTest.java
> +        Deck deck = new Deck(cards);
사실 이것도 고민이 많았어서 질문으로 남겼었는데요,

> 개인적으로 테스트 코드에서만 쓰이는 코드는 소스코드 작성 시에 자동완성에 뜨는 것 자체가 위험하다고 생각해서 지양하자는 주의

호돌의 이 답변을 보고 무릎을 탁.. 쳤습니다ㅋㅋㅋ 자동완성 부분은 생각도 못 했었는데 듣고 보니 자동완성 때문에 다른 개발자가 헷갈릴 여지도 있을 수 있겠네요.

첫 번째 미션 때 부터 명확한 답을 찾지 못해서 계속 고민 중인데, 아직 '이거다' 할 만한 방법을 떠올리지는 못했어요. 전략패턴을 적용하여 인자로 인터페이스를 전달받는 방법도 있겠지만 전략패턴이 항상 장점만 가지는 것을 아니라고 생각해요. 지금까지 전략패턴을 사용하지 않았던 이유도 이 정도 규모에서 전략패턴의 적용은 오버헤드가 더 크다고 판단했기 때문이기도 하구요.

질문 받은 것을 그대로 다시 질문하는 것 같아서 머쓱하긴 하지만..ㅎㅎ 혹시 좋은 방법이 있을까요?

2024-03-09 14:05 UTC, merged

2024-03-11 07:08 UTC, hw0603 commented on src/main/java/blackjack/domain/Deck.java
> +
개인적으로 지역변수의 선언부와 사용부, 메서드의 반환문은 공백으로 분리되어 있는 게 읽기 편하다고 생각합니다! 지금은 각 줄이 그리 길지 않아 과한 개행으로 보일 수도 있을 것 같긴 한데, 저기서 지역변수 선언이 두 줄만 늘어나도 개행되어 있는 것이 편하지 않을까요? 그렇다고 선언부의 길이에 따라 개행 여부가 바뀌는 것도 조금 어색할 것 같구요.

2024-03-11 07:13 UTC, hw0603 commented on src/main/java/blackjack/domain/GameResult.java
> +    public static GameResult calculatePlayerResult(Score playerScore, Score dealerScore) {
고민했던 부분인데 역시 수정이 필요할 것 같아요. 다만, 2단계 구현에서는 `Score` 만으로 `GameResult`가 도출되지 않을 것 같아서 우선 TODO로 남겨두고 2단계를 구현하면서 리팩토링하겠습니다!

2024-03-11 07:21 UTC, hw0603 commented on src/main/java/blackjack/domain/dto/PlayerDto.java
> +}
감사합니다. 다른 미션 진행 시 참고할게요!

2024-03-11 07:50 UTC, hw0603 commented on src/test/java/blackjack/domain/DeckTest.java
> +        Deck deck = new Deck(cards);
아하 그렇다면 전략패턴을 활용할 때 크게 부담을 가질 이유는 없겠네요.
그런데 테스트 코드에서 셔플하지 않고 원하는 카드들을 순서대로 반환하는 덱을 만들기 위해서는

```java
public static Deck createShuffledDeck(CardShuffler shuffler, List<Card> cards)
```
이 형태로 팩토리 메서드에서 cards를 받아야 하는데, 이렇게 되면 프로덕션 코드에서도 항상 52개의 카드 리스트를 전달해 줘야 해서 불편해질 것 같아요

```java
public static Deck createShuffledDeck(CardShuffler shuffler)
public static Deck createCustomDeck(CardShuffler shuffler, List<Card> cards)
```
그렇다고 위와 같이 팩토리 메서드를 하나 더 만들어 버리면 결국 또 테스트 코드에서만 사용되는 팩토리 메서드가 되어 버리구요(이러면 굳이 전략패턴을 사용하는 의미가 없어진다는 문제도 있겠네요).


```java
public class Card(Shape shape, Value value) {
    ...

    public static List<Card> allPairs() {
        return 모든_트럼프쌍의_리스트;
    }
}

Deck.createShuffledDeck(new DefaultShuffler(), Card.allPairs());

```
프로덕션 코드에서는 이러한 형태로 사용해야 할까요? 정적 팩토리 메서드의 장점 중 하나가 객체를 생성하는 목적에 따라 이름을 부여하고, 해당 목적에 불필요한 값은 외부에서 전달받지 않아도 쉽게 객체를 생성할 수 있는 점이라고 생각하는데 저렇게 되면 팩토리 메서드를 제대로 활용하지 못하는 것 같아서 고민이 됩니다.