[1단계 - 블랙잭 게임 실행] 미아(이종미) 미션 제출합니다.
woowacourse/java-blackjack pull request #621
Opened 2024-03-08 07:48 UTC by jongmee

안녕하세요. 찰리! 반갑습니다 😊

블랙잭 미션은 여러 게임 규칙이 존재해 도메인 설계가 비교적 어렵다고 느꼈습니다. 
**"딜러와 플레이어에서 발생하는 중복 코드를 제거해야 한다."** 는 요구사항에 따라, Composition을 활용해 중복 로직을 `Cards`에서 관리하였습니다. 상속을 피한 이유는 
1. 딜러와 플레이어가 어떤 상위 도메인을 확장했다기 보다, 별개의 게임 요소로 보았습니다.
2. 현재 프로그램 구조에서 다형성을 활용할 수 없습니다.
아래는 딜러와 플레이어의 중복된 로직을 활용하여 게임 결과를 도출하는 메서드입니다. 예를 들어, 딜러와 플레이어의 상위 클래스 `A`로 `boolean isBlackJack = a.isBlackJack()`과 같이 다형성을 활용할 수 있습니다. 하지만 딜러와 플레이어의 `isBlackJack()` 결과(반환값)은 혼동되어서는 안됩니다. 상위 클래스 `A`에서 중복 로직을 관리하며 `boolean isBlackJack = dealer.isBlackJack()`와 같이 다형성을 활용하지 않는다면, 상속의 단점을 감당하면서 사용하는 것이 불필요하다고 판단했습니다.
```java
public class Referee {
    // 중략
    private MatchResult determineMatchResult(final Player player) {
        int playerTotalScore = player.calculateCardsTotalScore();
        int dealerTotalScore = dealer.calculateCardsTotalScore();

        if (dealer.isBlackJack() && player.isBlackJack()) {
            return MatchResult.TIE;
        }
        if (dealer.isBurst() || playerTotal >= dealerTotal) {
            return MatchResult.WIN;
        }
        return MatchResult.LOSE;
    }
}
```

따라서 중복된 코드를 피하고자하는 목적만으로 상속을 사용하기 보다, Composition을 활용하였습니다.
하지만 아래와 같은 코드들이 고민되었습니다.
```java
public class Dealer {
    private final Cards cards;
    // 중략
    public int calculateCardsTotalScore() {
        return cards.calculateCardsTotalScore();
    }

    public boolean isBurst() {
        return cards.isBurst();
    }

    public boolean isBlackJack() {
        return cards.isBlackJack();
    }
}

public class Player {
    private final String name;
    private final Cards cards;
    // 중략
    public int calculateCardsTotalScore() {
        return cards.calculateCardsTotalScore();
    }

    public boolean isBurst() {
        return cards.isBurst();
    }

    public boolean isBlackJack() {
        return cards.isBlackJack();
    }
}

```
같은 패턴으로 `Cards cards`의 메서드를 호출하고 있습니다. 
## 질문
1. 해당 메서드들의 책임을 `Cards`에게 주었지만, 이와 같은 같은 패턴이 발생했을 때 중복된 코드를 잘 관리한 것이라 볼 수 있을까요? 
2. 찰리는 이 상황에서 상속을 사용하는 것이 맞다고 보시나요?

2024-03-08 14:05 UTC, Gomding requested changes
안녕하세요 미아!
블랙잭 미션 함께하게된 찰리입니다 🙇 

전체적으로 꼼꼼하게 진행해주셨네요~!
몇가지 코멘트 남겼으니 확인해주세요 🙏 

궁금한 점 있으면 언제든 코멘트나 DM 남겨주세요

2024-03-08 14:05 UTC, Gomding commented on src/main/java/blackjack/model/dealer/Dealer.java
> +    public void doAction(final CardGenerator cardGenerator) {
doAction 이라는 이름은 어떤 의미를 전달하고 있을까요? 🤔

2024-03-11 02:29 UTC, jongmee commented on src/main/java/blackjack/model/player/Player.java
> +        this.name = name;
중복된 플레이어 이름도 허용하지 않는 만큼, `딜러` 역시 허용하지 않아야 겠군요..! 반영하였습니다!

2024-03-11 02:35 UTC, jongmee commented on src/main/java/blackjack/model/cardgenerator/RandomCardGenerator.java
> +        return new Card(suit, denomination);
실제 카지노에서는 카드 수로 결과를 예측하는 걸 방지하기 위해서 52개의 카드만 사용하지 않는 것으로 알고 있습니다!

찾아보니 최소 4벌 이상인 덱 여러 벌을 사용한다([나무위키](https://namu.wiki/w/%EB%B8%94%EB%9E%99%EC%9E%AD(%EC%B9%B4%EB%93%9C%EA%B2%8C%EC%9E%84)#fn-1))고 하네요..! 정확한 게임을 위해서 "중복된 카드가 5개 이상 나오지 않는" 로직을 추가하도록 하겠습니다.

2024-03-11 02:40 UTC, jongmee commented on src/main/java/blackjack/model/card/Cards.java
> +public class Cards {
> 해당 부분을 Cards의 역할로 분리해주신것이 아닐까요?

`Cards`에서 담당하는 기능을 메서드로 모아주었으니 역할 분리가 맞겠네요 ☺️

(처음에는 `Hand`였지만 해당 단어가 익숙하지 않아 `Cards`로 변경하였습니다..!)

2024-03-11 02:50 UTC, jongmee commented on src/main/java/blackjack/model/player/Player.java
> +        return cardsTotal <= HIT_CONDITION;
버스트가 아닐 때 hit을 할 수 있다는 상관관계를 놓쳤네요 😢 수정하였습니다 감사합니다!

2024-03-11 02:53 UTC, jongmee commented on src/main/java/blackjack/model/dealer/Dealer.java
> +        return cards.isBurst();
오타 수정하였습니다!

2024-03-11 03:01 UTC, jongmee commented on src/main/java/blackjack/model/card/Cards.java
> +    private static final int BURST_CONDITION = 21;
21이 사용되는 로직은 아래와 같습니다.

1. 카드 딜링에서 두 카드 합이 21이면 블랙잭이다.
2. 액션에서 카드의 총 합이 21이 넘으면 버스트다.

'블랙잭'이나 '버스트'는 `Cards`의 메서드명으로 충분히 표현되는 것 같아서 해당 상수 이름을 
```java
private static final int MAX_CARDS_TOTAL = 21;
```
로 바꾸어 보았습니다. 어떤 상황에서도 카드합의 최대 수를 의미하기 때문입니다.

2024-03-11 05:43 UTC, jongmee commented on src/main/java/blackjack/model/referee/Referee.java
> +    public List<PlayerMatchResult> determinePlayersMatchResult() {
`determineMatchResult` 메서드에서 `player `와 `dealer `의 `isBlackJack()`을 호출하고 있습니다. 다형성을 활용해서 
```java
public class Referee {
    private final List<Participant> players; // Participant는 Player와 Dealer의 상위 클래스라 가정
    private final Participant dealer;
}
```
와 같이 쓸 경우, 혹은 인자로 `Player player` 대신 `Participant player`와 같이 쓸 경우

딜러와 플레이어의 카드합을 비교해서 승패를 가리는 기능에서 Participant 타입의 변수에 원치 않은 객체가 할당되면
(Participant player에는 Dealer 객체가, Particpant dealer에는 Player 객체가)
안됩니다. 따라서 기존대로 타입을 자식 클래스로 유지해야 하는데 이렇다면 상속의 다형성을 활용하지 않습니다.

이 상황에서 상속의 단점 _( (1) 하위 클래스가 상위 클래스의 구현에 의존하기에 변경에 취약하다 (2) 캡슐화가 되지 않는다 )_ 
을 감당하면서 중복 코드를 줄일 필요성을 느끼지 못했습니다..! 

단어 선택이 분명하지 못했던 것 같네요 😢 이에 대한 찰리의 의견이 궁금합니다!

2024-03-11 05:51 UTC, jongmee commented on src/main/java/blackjack/controller/BlackJackController.java
> +            return;
`isBust()`로 수정하였습니다! 딜러가 버스트면 모든 플레이어가 즉시 승리합니다.

2024-03-11 06:24 UTC, jongmee commented on src/main/java/blackjack/controller/BlackJackController.java
> +        if (command) {
명령어 자체는 아니지만, `PlayerAction`여부를 결정하는 enum을 생성하여 객체로서 다루게 리팩토링 해보았습니다 😊

이해에 도움되는 리팩토링일까요?

2024-03-11 07:55 UTC, jongmee commented on src/main/java/blackjack/model/card/Cards.java
> +        int total = cards.stream()
Score가 블랙잭 게임에서 중요한 값이고, 연산이 중요한 도메인 로직인 것 같아 Score 불변 도메인 객체를 만들어보았습니다! 

자주 사용되는 1부터 21까지의 Score는 캐싱하였습니다.

2024-03-11 08:56 UTC, jongmee commented
안녕하세요 찰리!

리뷰에 코멘트로 수정된 사항들이나 질문, 질문에 대한 답변을 달아놓았습니다!
크게 변경된 내용은 아래와 같습니다.

1. `PlayerAction` 도메인 클래스(`enum`)를 생성하여 플레이어의 액션 지속 여부를 판단하는 역할을 맡게 하였습니다.
2. `Score` 불변 도메인 클래스를 생성하였고, 자주 사용되는 1부터 21까지의 점수는 캐싱하였습니다.
3. `RandomCardGenerator`에서 4개의 덱(208 개의 카드) 안에서 카드를 뽑도록 변경하였습니다.

추가적으로 공부하며 생긴 질문이 있습니다!
최근 static 객체와 JVM을 공부하던 중, Java8 부터 Hotspot JVM의 Metaspace가 도입되고 static 객체와 interned String이 Heap 영역에 저장된다는 것을 알았습니다. 이때 제가 이해한 static 객체는 
```java
static Map<Integer, Score> cache;
static Player player = new Player("mia");
```
와 같은 static이 붙은 객체(인스턴스)입니다. 출처는 https://openjdk.org/jeps/122 입니다.
Heap 영역에서 관리된다면 static 객체 역시 GC의 대상이 될 것입니다. 하지만 많은 블로그들을 참고하면 "static 객체는 GC의 대상이 아니다"라는 글들을 볼 수 있습니다. 저번 우테코 학습 강의에서도 캐시를 언급하며 
```
JVM의 경우 GC의 성능이 우리가 생각하는 것 보다 훨씬 더 좋기 때문에 캐싱을 하지 않는 것이 더 좋을 수도 있다
```
라고 언급해주셨습니다. 제가 올바르게 이해한 것이 맞은지 궁금합니다. static 객체들은 Heap에서 관리되고, GC의 대상이 되는 것이 맞을까요?

2024-03-11 10:29 UTC, Gomding commented on src/main/java/blackjack/model/cardgenerator/RandomCardGenerator.java
> +        return new Card(suit, denomination);
오 도메인 파악을 꼼꼼하게 해주셨네요 😮 👍👍👍 
저도 배워갑니다....

2024-03-11 10:46 UTC, Gomding commented on src/main/java/blackjack/controller/BlackJackController.java
> +            return;
게임을 시작하자마자 bust 인 경우가 있는지 궁금해요!
두 장의 최대 값을 21인 것으로 알고있어서요! (두 벌의 카드덱을 사용하더라도요!)

2024-03-11 10:46 UTC, Gomding commented on src/main/java/blackjack/model/referee/Referee.java
> +    public List<PlayerMatchResult> determinePlayersMatchResult() {
> Participant 타입의 변수에 원치 않은 객체가 할당되면 안됩니다. 
> (Participant player에는 Dealer 객체가, Particpant dealer에는 Player 객체가)

설득력 있는 문장이네요!

딜러와 참가자를 따로 필드로 가지지않고
참가자들(participants) 중에서 딜러를 직접 골라낸다면 해당 문제는 해결되지 않을까요? 🤔 
딜러가 없다면 애플리케이션이 오동작한 것이니 예외를 발생시키면 되겠구요!

```java
public class Referee {
    private final Participants partcipants;
    
    public void 멋진메서드() {
        final Participant dealer = partcipants.getDealer();
        ... 생략
    }
}
```

2024-03-11 10:58 UTC, Gomding commented on src/main/java/blackjack/model/card/Cards.java
> +        int total = cards.stream()
캐싱까지 완벽하군요 💯 💯 💯

2024-03-11 10:59 UTC, Gomding commented on src/main/java/blackjack/model/player/Player.java
> +        this.name = name;
사용자에게 혼란을 줄 수 있는 포인트라 생각해요!
물론 정책적인 부분이라 딜러를 허용하여 서비스에 문제가 없다면 상관없겠죠 😄

2024-03-11 11:01 UTC, Gomding commented on src/main/java/blackjack/controller/BlackJackController.java
> +        if (command) {
훌륭하다고 생각합니다 👍

2024-03-11 12:00 UTC, Gomding requested changes
안녕하세요 미아!

몇가지 코멘트 더 남겨봤어요 🙇 
다음 요청때 merge 할 예정입니다!

궁금한 점 있으면 언제든 DM 남겨주세요~!

2024-03-11 14:13 UTC, jongmee commented on src/main/java/blackjack/controller/BlackJackController.java
> +            return;
계산 로직을 생각해보니 에이스를 두 장 뽑더라도 11+1로 계산되어 버스트가 발생하지 않네요..! 해당 부분 수정하였습니다 😂

2024-03-11 14:15 UTC, jongmee commented on README.md
> +## 블랙잭 용어
감사합니다 추천해주신 레퍼런스를 더 읽어봐야겠어요 👍

2024-03-11 14:19 UTC, jongmee commented on src/main/java/blackjack/model/card/Score.java
> +        if (value >= ScoreCache.MIN_VALUE && value <= ScoreCache.MAX_VALUE) {
`MAX_VALUE `라는 용어 때문에 잘못 사용했네요 🥲

`MAX_VALUE`를 21로 하고 캐싱하는 숫자를 `IntStream.range(MIN_VALUE, MAX_VALUE + 1)`로 생성하도록 수정하였습니다!

2024-03-11 14:24 UTC, jongmee commented on src/main/java/blackjack/model/card/Cards.java
> +        Score totalScore = Score.from(scores);
정적 팩토리 메서드를 쓰는 것보다 더 직관적인 것 같네요! 👍 감사합니다 해당 부분 반영하였습니다!

2024-03-11 14:39 UTC, jongmee commented on src/main/java/blackjack/model/cardgenerator/RandomCardGenerator.java
> +    private final Iterator<Card> cards;
'뽑는다'라는 개념도 `Iterator`에는 적합하지 않네요! `Queue` 로 변경하였습니다 감사합니다 😊

2024-03-11 14:48 UTC, jongmee commented on src/main/java/blackjack/model/player/Player.java
> +    private static final String INVALID_PLAYER_NAME = "딜러";
입출력시에만 쓰이는 상수네요. inputView로 검사 위치를 변경하였습니다!

2024-03-11 14:50 UTC, jongmee commented on src/main/java/blackjack/model/referee/Referee.java
> +        if (dealer.isBlackJack() && player.isBlackJack()) {
딜러와 플레이어의 점수가 같으면 플레이어가 이기는 것으로 알고 있었는데, 무승부였군요..! 해당 로직 수정하였습니다.

2024-03-12 02:53 UTC, jongmee commented on src/test/java/blackjack/model/referee/RefereeTest.java
> +    @DisplayName("딜러와 플레이어의 카드 합을 비교하여 승패를 가린다")
`1) 버스트 여부`와 `2) 카드 합 비교`로 승패를 결정하는 테스트를 `ParameterizedTest`를 활용하여 추가하였습니다!

2024-03-12 03:17 UTC, jongmee commented on src/main/java/blackjack/model/dealer/Dealer.java
> +    public void doAction(final CardGenerator cardGenerator) {
플레이어의 `hit()`메서드처럼 hit의 의미를 담아 `hitUntilEnd`로 메서드 이름을 변경해보았습니다..!

2024-03-12 05:24 UTC, jongmee commented on src/main/java/blackjack/model/cardgenerator/RandomCardGenerator.java
> +        this.cards = generateDecks().iterator();
우선 피드백을 반영하여 큐 형태로 데이터를 저장하고 있는데요! 프로덕션 코드에 카드를 직접 생성하는 것은 없고 `private final Queue<Card> decks`에서 하나씩 뽑아서(`pick()`) 카드를 사용하고 있는데, 이 자체로 캐싱이라고 볼 수 있을까요? 

`decks`를 static 필드로 두고 생성 메서드들을 전부 static으로 바꾸려다 꼭 필요할까 싶어서 먼저 질문 드립니다!

2024-03-12 05:41 UTC, jongmee commented
안녕하세요 찰리! 다음엔 step2에서 뵙겠네요 ☺️

코멘트로 수정된 부분을 적어놓았습니다! 코멘트에도 나와있지만, 질문 하나가 있어서 여기에도 적어놓겠습니다!
> 우선 피드백을 반영하여 큐 형태로 데이터를 저장하고 있는데요! 프로덕션 코드에 카드를 직접 생성하는 것은 없고 private final Queue<Card> decks에서 하나씩 뽑아서(pick()) 카드를 사용하고 있는데, 이 자체로 캐싱이라고 볼 수 있을까요?
>
> decks를 static 필드로 두고 생성 메서드들을 전부 static으로 바꾸려다 꼭 필요할까 싶어서 먼저 질문 드립니다!

카드를 RandomCardGenerator에서 받아서 사용할 때 캐싱하는 것을 추천해주셔서 고민하다가 질문 남겨놓습니다!

2024-03-12 05:43 UTC, jongmee commented on src/main/java/blackjack/model/referee/Referee.java
> +    public List<PlayerMatchResult> determinePlayersMatchResult() {
찰리도 Composition에 동의해주셨고, participants 까지 고려하면 도메인 클래스가 너무 많아지는 것 같아서 step1에서는 이대로 마무리하겠습니다! 감사합니다 👍

2024-03-12 12:14 UTC, Gomding commented on src/main/java/blackjack/model/cardgenerator/RandomCardGenerator.java
> +        this.cards = generateDecks().iterator();
생각했던것은 카드덱 1벌은 52장이라는 것이 정해져있고 오랫동안 변경된적도 없으니
52장의 객체를 미리 만들어서 사용하자는 것이었습니다~

물론 지금처럼 게임을 한 번만 진행하면 전혀 필요없는 구현이라 YAGNI에 해당하겠지만요 😇

하지만 여러 게임이 진행되는 웹애플리케이션이라면 미리 52장의 카드 한벌 객체를 저장해두고
해당 객체만 계속 사용하면 되니 효율적이겠죠..!

말씀대로 꼭 필요할까? 라고 하면 반박 불가입니다 😄

2024-03-12 12:54 UTC, Gomding approved these changes
안녕하세요 미아!
전체적으로 요구사항을 만족하여 2단계에서 뵙겠습니다!
추가로 남긴 코멘트는 다음 단계 진행하면서 함께 고민해주세요~

2단계도 화이팅입니다 🔥

2024-03-12 12:54 UTC, Gomding commented on src/main/java/blackjack/model/card/Score.java
> +        static final Map<Integer, Score> cache = IntStream.range(MIN_VALUE, MAX_VALUE + 1)
적절하게 변경해주셨군요 👍 

IntStream.rangeClosed 라는 함수를 사용하면 두번째 인자까지 범위에 포함해줍니다 😄 
`for(int i = MIN_VALUE; i <= MAX_VALUE; i++)` 이것과 같아집니다~

2024-03-12 12:54 UTC, Gomding commented on src/main/java/blackjack/model/card/Cards.java
> +    private Score sumAllScores() {
위 메서드가 calculateCardsTotalScore 이니 totalScore로 해도 괜찮을거같아요!

물론 취향차이라서 무시하셔도 됩니다~! 😄

2024-03-12 12:54 UTC, Gomding commented on src/main/java/blackjack/model/cardgenerator/RandomCardGenerator.java
> +        return new LinkedList<>(decks);
Queue 의 구현체로 LinkedList와 ArrayDeque 가 있는데
LinkedList를 선택하신 이유가 궁금해요~ 🙋

2024-03-12 12:54 UTC, Gomding commented on src/main/java/blackjack/view/InputView.java
> +        if (input.contains("딜러")) {
view로 이동시켜 주셨군요! 💯

2024-03-12 12:54 UTC, Gomding commented on src/main/java/blackjack/model/card/Cards.java
> +        return calculateCardsTotalScore().equalTo(MAX_CARDS_TOTAL);
사실 블랙잭은 처음 받은 두 장의 카드가 21점일 때`Ace + 10점의 카드` 일 때만 블랙잭 상태입니다 😈 
(3장 이상으로 21점을 만들더라도 블랙잭이 아닌 총합이 21점일 뿐입니다~)
다음 단계 구현 시 고려해주세요!

출처 나무위키
![image](https://github.com/woowacourse/java-blackjack/assets/57378410/3274e429-ac2f-4d5d-8497-341a60b6a69c)

2024-03-12 12:54 UTC, Gomding commented on src/main/java/blackjack/model/card/Score.java
> +    public boolean equalToOrGreaterThan(final Score criterion) {
모든 비교를 메서드로 표현 👍

2024-03-12 12:54 UTC, Gomding commented on src/main/java/blackjack/model/player/PlayerAction.java
> +        return asked;
isHit 라는 이름이 블랙잭 도메인에 더 어울리지 않을까요!

```java
return this.equals(Hit);
```

2024-03-12 12:54 UTC, Gomding commented on src/main/java/blackjack/model/referee/Referee.java
> +            return MatchResult.WIN;
플레이어가 버스트라면 무조건 플레이어의 패배로 알고있어요!

출처 : 나무위키
> 하지만 카드 숫자의 합이 21을 초과하게 되는 순간 '버스트'라고 하며 딜러의 결과에 관계없이 플레이어가 패배한다.

2024-03-12 12:54 UTC, Gomding commented on src/main/java/blackjack/model/referee/Referee.java
> +        return MatchResult.decideByScore(playerTotalScore, dealerTotalScore);
딜러에게 플레이어의 결과를 판단해달라고 요청하는 것은 과한 책임일까요? 🤔

2024-03-12 12:54 UTC, Gomding commented on src/main/java/blackjack/model/card/Cards.java
> +        cards.add(cardGenerator.pick());
CardGenerator를 인자로 받는것과 Card를 인자로 받는것 둘을 비교해보면 좋겠어요!

deal 메서드도 마찬가지 입니다!

2024-03-12 12:54 UTC, merged

2024-03-13 04:28 UTC, jongmee commented on src/main/java/blackjack/model/cardgenerator/RandomCardGenerator.java
> +        return new LinkedList<>(decks);
연결리스트(LinkedList)와 배열(ArrayDeque)로 보고 삽입과 삭제가 연결리스트에서 더 유리할 거라고 생각했는데 ArrayDeque가 성능면에서 더 뛰어나군요..! 덕분에 공부할 수 있었습니다 감사합니다 🙇🏻‍♀️

2024-03-13 04:35 UTC, jongmee commented
나머지 리뷰들은 Step2에서 다루도록 하겠습니다!