[1단계 - 블랙잭 게임] 카고(정민호) 미션 제출합니다.
woowacourse/java-blackjack pull request #631
Opened 2024-03-08 08:10 UTC by devhoya97

안녕하세요 스티치! 저는 6기 카고라고 합니다 :)

우선 지금까지 제가 어떤 학습을 해왔고, 배경지식이 어떤 상태인지 말씀드리면 리뷰하는데 도움이 되실 것 같아서 아래 내용을 추가했어요!

***
전자과를 전공하여 이와 관련된 회사에서 1년간 일을 하다가, 프로그래밍이 너무 재밌어서 개발자가 되기 위해 작년 9월부터 자바 공부를 시작했어요. 대학시절 프로그래밍 수업은 몇개 들어봤지만 자바는 프리코스를 준비하면서 공부한 것이 처음이고, 백엔드 개발에 필요한 학습들은 우테코를 합격하고 나서부터 진행했기에 개발 경력이 매우 짧습니다..!
***

지난 미션들에 비해 이번 미션에서는 고민해야 할 문제들이 많아서, 리뷰 요청을 드리기 전에 만족스러운 코드를 완성하지 못했어요.

### 완성하지 못한 부분
#### 1. Player와 Dealer를 Gamer로 추상화하고, `List<Gamer>` 를 Gamers로 다루기
`3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.` 라는 요구사항을 지키기 위해 GameBoard가 Dealer와 Players를 각각 멤버변수로 가지지 않고, Gamers 라는 일급컬렉션을 멤버변수로 가짐으로써 GameBoard는 Deck과 Gamers만을 멤버변수로 갖도록 만들고 싶었습니다. 어떻게 구상해야 할지는 머릿속에 떠올랐지만, 여러 클래스에서의 변경이 필요해서 시간이 부족해 완성하지 못했어요. (완성하다가 롤백했습니다 ㅎㅎ..)

저는 이번 미션에서 `Player와 Dealer의 추상화`가 핵심 학습 주제라고 생각했는데요. 위와 같은 접근 방향이 적절한지 스티치의 생각이 궁금해요!

#### 2. 입력에 대한 다양한 예외처리
Player의 이름이 중복되지 않아야 한다거나, 공백은 이름이 될 수 없다거나, 너무 긴 이름을 가질 수 없다거나, y 또는 n 외의 문자가 들어오면 안된다거나 하는 입력 쪽에서의 예외처리를 구현하고 싶었지만, 이 내용들은 요구사항을 먼저 지키는 것이 우선이라 생각하여 TODO로 남겨두었고, 요구사항도 못 지킨 상황에서 이런 예외처리들은 구현하지 못하였습니다..! 

예외처리에 대한 리뷰 때문에 이번 미션에서 학습해야 하는 핵심 주제에 대한 리뷰를 받지 못하면 아쉬울 것 같아서 언급드리고 싶었어요..!

#### 3. 초반 TDD 적용 실패
초반의 커밋들을 보시면 테스트가 작성되지 않고 클래스들이 완성된 모습을 자주 보실 수 있을 텐데요. 자바의 기능을 테스트하는 꼴이 돼버리는 테스트 코드는 지양하고 싶었어요. 따라서 너무 간단한 메서드거나, 이 메서드를 활용해서 반복문을 도는 메서드 같은 경우는 테스트가 필요없다고 생각해서 이 부분은 TDD로 진행하지 않았어요.

그런데 다른 크루와 이에 대해 의견을 나누다보니, TDD를 하게 되면 객체의 협력 관점에서 구현을 모르는 채로 객체에게 메시지를 던질 수 있다는 사실을 알게 되었어요. 따라서 막상 구현했더니 아주 간단한 코드로 나오더라도, 객체가 책임을 잘 수행했는지를 보기 위해 TDD는 필요하다는 생각을 갖게 되었어요. 그리고 이렇게 구현해야만 자율성을 가진 객체들을 만들 수 있을 것 같아 TDD는 객체지향설계 관점에서도 도움을 줄 수 있지 않을까 생각했어요. 

제가 정리한 생각들이 올바른 방향인지 스티치의 생각이 궁금해요!

#### 4. 협력, 역할, 책임 관점에서의 객체 설계
`객체지향의 사실과 오해` 책을 읽고, 이 내용들을 미션에 적용해보고 싶었어요. 
docs.README.md에 구현할 기능 목록을 정리한 뒤, 위 기능들에 필요한 협력은 무엇이고, 해당 협력들을 구성하는 역할과 책임들은 무엇인지 정리해놓았어요. 그런데 커밋은 기능 단위로 추가하려다보니 막상 앞서 정리했던 협력과 책임 관점에서 객체가 잘 설계되었는지 확인하며 구현하기가 어려웠습니다. 그래서 일단 기능 목록만 보고 구현을 다 마치고, 협력, 역할, 책임 관점에서 객체 설계가 잘 이루어졌는지 검토하려 했는데 시간이 부족해 하질 못했네요..

README.md에 현재와 같이 정리했다면, 애초에 협력, 역할, 책임 관점에서 정리한 내용을 바탕으로 커밋을 하는게 더 좋았으려나요?!

***

### 추가로 질문드리고 싶은 내용
#### 1. 어떤 컨트롤러가 잘 설계된 컨트롤러일까?
https://techcourse.woowahan.com/s/IND5iItC/ls/m7oLA1fU
자동차 경주 리팩토링 피드백 문서에서 MVC 패턴 기반으로 리팩토링하라는 요구사항을 받았어요! 그 이후부터 미션을 진행할 때 MVC패턴을 적용할 수 있는 구조로 보이면 MVC패턴을 적용하기 위해 노력중이고, 이번 미션도 MVC 패턴을 충분히 적용할 수 있을 것 같아 적용했어요!

위 링크에서 보여준 예시 코드를 보시면 Main 메서드가 컨트롤러의 역할을 하고 있어요. 저는 MVC 패턴에 대해서도 우테코에 들어와 처음 사용해봤기 때문에 우선 예시 코드의 구조를 따라가려 노력했습니다.

따라서 Main 메서드를 도메인과 view를 연결해주는 컨트롤러와 같이 사용하며, GameBoard는 실제 도메인 로직을 활용해 게임을 진행해주는 역할을 하도록 설계했어요. 이러한 설계 구조가 적절해보이는지 궁금합니다..!
왜냐하면 GameBoard가 도메인 객체들을 활용하는 모습이 왠지 컨트롤러 역할을 하고 있는 것 같아서 찝찝했어요. Main 메서드를 컨트롤러로 활용하고 싶을 때, GameBoard와 같은 애매한 도메인 객체 없이도 게임을 잘 진행할 수 있을지, 아니면 더 합리적인 방법이 있는지 궁금합니다!

#### 2. DTO의 적절한 사용법
이번 미션에서 사용한 Player, Dealer 객체는 내부 상태를 변경시킬 수 있는 draw 라는 메서드를 갖고 있었기에 view에게 넘겨주고 싶지 않았어요. 따라서 처음에는 GameState 와 같은 VO를 만들어 넘겨주도록 설계했는데, 만들다보니 `이거 그냥 DTO 아닌가?` 라는 생각이 들어서, 차라리 다른 개발자들이 봤을 때 딱 봐도 데이터 전달용 객체로 보이도록 DTO를 만드는게 낫겠다는 생각이 들어 DTO들을 만들기 시작했어요. 그러다보니 DTO를 어디까지 만들어 사용해야할까? 궁금해졌어요.

예를 들어 A라는 객체에 one, two, three 라는 멤버 변수가 있는데, view에서는 one만 필요한 상황이 있고, one과 two만이 필요한 상황이 있고... 모든 경우의 수를 생각하면 3개의 멤버변수를 가진 클래스에 대해 최악의 경우 7종류의 DTO가 필요해 보였어요. 이렇게 view가 필요한 정보만을 제공하기 위해 DTO 종류를 잘게 나누는게 좋은지, 아니면 한 개의 멤버변수만을 필요로 하더라도 세 개의 멤버변수를 모두 갖는 DTO를 view에게 넘겨줌으로써 DTO의 종류를 하나로 유지하는게 좋을 지 아직도 잘 모르겠어요. DTO를 처음 사용해봐서 더 헷갈리는 것 같아요..!

스티치의 생각은 어떤가요? 

### 그 외에 지적해주실 만한 부분이 있다면 최대한 많이 지적해주시면 모두 반영하겠습니다!!!

2024-03-09 08:39 UTC, lxxjn0 requested changes
안녕하세요 카고, 이번에 블랙잭 게임 미션을 리뷰하게 된 스티치입니다.

말씀하신 카고의 이야기와는 다르게 작성하신 코드는 이미 훌륭하신 것 같아요!! 개발을 막 시작한 사람이라곤 믿기지 않습니다 👍🏼 너무 잘 짜주셨고 피드백이 많아서 테스트는 다음 리뷰에 피드백 드리도록 하고 우선 프로덕션 코드 위주로 피드백 작성하였습니다. 확인하시고 리팩토링 부탁드리겠습니다 :)

2024-03-09 08:39 UTC, lxxjn0 commented on docs/README.md
> +### 기능 요구 사항
기능 요구사항을 꼼꼼하게 작성해주었네요 👍🏼

2024-03-09 08:39 UTC, lxxjn0 commented on src/main/java/blackjack/domain/card/DeckFactory.java
> +}
Deck 팩토리라면 Deck을 생성해서 반환해주는 것이 어떨까요?

2024-03-09 08:39 UTC, lxxjn0 commented on src/main/java/blackjack/domain/card/DeckShuffleFactory.java
> +    }
deck을 파라미터로 받아와서 넣기보단 생성한 Card 들을 반환하고 호출한 메서드에서 넣어주는 것이 어떨까요? 그렇다면 굳이 deck을 파라미터로 받아오지 않고도 구현이 가능할 것 같습니다 :)

2024-03-09 08:39 UTC, lxxjn0 commented on src/main/java/blackjack/view/InputView.java
> +    private static final Scanner scanner = new Scanner(System.in);
상수 네이밍 규칙을 적용해주세요.

2024-03-09 08:39 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Players.java
> +            players.add(Player.from(new Name(name)));
Players의 정적 팩토리 메서드처럼 Player도 문자열을 받는 정적 팩토리 메서드를 구현한다면 Name을 여기서 생성하지 않아도 될 것 같습니다.

2024-03-09 08:39 UTC, lxxjn0 commented on src/main/java/blackjack/domain/dto/DealerDto.java
> +public class DealerDto {
DTO는 도메인 패키지에 위치하는 것은 적절하지 않아보입니다. DTO가 어떠한 역할을 하는 지와 패키지 레벨을 어디에 두는게 좋을지 한번 학습해보면 좋을 것 같습니다 :)

2024-03-09 08:39 UTC, lxxjn0 commented on src/main/java/blackjack/domain/GameBoard.java
> +    }
도메인 객체에서 DTO를 반환하게 된다면 도메인 객체가 DTO를 의존하는 상황이 됩니다. 의존의 방향을 바꿔서 코드를 작성해보면 좋을 것 같습니다!

2024-03-09 08:39 UTC, lxxjn0 commented on src/main/java/blackjack/Application.java
> +    }
GameBoard를 넘겨준다면 players는 안에서 가져와서 사용할 수 있을 것 같습니다.

2024-03-09 08:39 UTC, lxxjn0 commented on src/main/java/blackjack/domain/card/Card.java
> +public record Card(Number number, Suit suit) {
Card는 VO 객체로 사용되고 있는데 캐싱을 한번 적용해봐도 좋을 것 같습니다!! Integer 클래스의 구현을 참고하시면 좋을 것 같습니다 👍🏼

2024-03-09 08:39 UTC, lxxjn0 commented on src/main/java/blackjack/domain/card/Deck.java
> +    private final Stack<Card> deck;
적절한 자료구조 사용 👍🏼

2024-03-09 08:39 UTC, lxxjn0 commented on src/main/java/blackjack/domain/card/Number.java
> +    }
해당 메서드를 나눠두신 이유가 있을까요? 실제로 가지고 있는 Number의 값에 따라서 Ace의 스코어를 적절하게 적용할 수 있을 것 같습니다. 한번 해당 부분도 고민해봐주시면 좋을 것 같습니다 :)

2024-03-09 08:39 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Outcome.java
> +    }
해당 메서드는 Dto에서 가지고 있는 것은 어떨까요? 추가로 stream과 Collectors 라이브러리에서 제공하는 다양한 기능을 활용한다면 Map으로 만들어서 더 간단하게 처리가 가능할 것 같습니다!!

2024-03-09 08:39 UTC, lxxjn0 commented on src/main/java/blackjack/view/OutcomeTranslator.java
> +    PUSH(Outcome.PUSH, "무");
도메인 로직과 출력 로직을 적절히 분리하셨네요 👍🏼

2024-03-09 08:39 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Referee.java
> +public class Referee {
Referee가 게임의 결과를 계산하는 클래스로 보입니다. 그런데 실질적으로 반환하는 값이 다 Outcome 객체입니다. 그렇다면 Outcome 객체의 프로퍼티에 적절한 계산 로직을 둔다면 해당 클래스의 책임을 Outcome 클래스로 옮길 수 있지 않을까요?

2024-03-10 07:52 UTC, lxxjn0 commented
### 1

해당 부분은 코드의 구현에 따라 달라질 것 같습니다. 카고의 코드에서 List<Gamer>가 유의미하게 적용이 될 수 있을지는 아직 제가 파악을 하진 못했습니다. 그렇지만 주의해야 할 부분은 상위 타입인 Gamer로 사용하기에 적절하지 않은데 ‘상속을 사용했으니 어떻게든 이용해야지’ 하며 사용하는 것입니다. 가끔 코드를 보다보면 Gamer 타입으로 관리하면서, Dealer나 Player의 고유 기능을 사용해야 할 때는 하위 타입 캐스팅을 이용하는 경우가 있습니다. 이런 방법은 객체지향적인 설계도 아닐 뿐더러 상위 타입을 사용하는 적절한 방법이 아닐 가능성이 높습니다. 따라서 카고가 List<Gamer>로 Dealer와 Player를 관리할 때는 ‘해당 리스트의 객체들을 활용할 때 Gamer의 기능을 사용할 것인가?’라는 관점에서 고민해보면 좋을 것 같습니다 :)

### 2

제 개인적인 생각에서는 저런 예외 처리는 신경쓰지 않으셔도 될 것 같아요 :) 기능 요구사항도 아닌 내용이고 카고의 말씀대로 이번 미션에서 더 집중해야 하는 부분이 있으니 해당 부분은 없는 샘 치고 미션 진행하셔도 괜찮습니다!! 제가 개발했어도 예외에 대한 처리는 하나도 안하고 개발했을 것 같습니다 ㅎㅎㅎ

### 3

이 부분은 우테코의 교육 목적과 실제 코드 작성 시의 관점이 다르기에 정확한 정답을 말씀드리긴 어려울 것 같습니다. 먼저 저의 경우에는 테스트가 필요한 유의미한 비즈니스 로직에 대해서 테스트를 작성합니다. 카고의 말대로 실제 코드의 구현이 너무 단순하거나 테스트 코드를 작성하는 비용 대비 효율이 부족하다면 따로 작성하진 않습니다. 하지만 이게 올바른 방향이냐고 한다면 그렇진 않을 것 같아요.. 가능한 테스트는 작성되는 것이 좋다고 생각합니다. 단지 실제 코드를 작성하다보면 그런 테스트 코드 작성 비용이 부담스럽게 느껴지다보니 타협을 하는게 아닌가 싶습니다.

돌아와서 우테코에서는 다른 크루의 말씀대로 가능한 모든 상황에서 TDD를 하고 테스트 코드를 작성하면 좋을 것 같습니다. 허나 생성자와 같이 내부에 로직이 없다면 테스트 코드를 꼭 작성할 필요는 없겠지만 약간의 로직이 들어간 메서드라면 단순한 코드라도 테스트 코드 작성을 하는 방향으로 진행하시면 좋을 것 같아요!

### 4

이 부분은 사실 정답은 없다고 생각합니다.. 사실 우테코에서는 기능 구현 목록 단위로 커밋을 찍는 것으로 알고 있어요. 그렇지만 저의 경우에는 커밋의 단위를 꼭 기능 구현 목록 단위로 가져가진 않고 유의미한 개발 단위로 커밋을 찍습니다. 이게 기능 구현 일 수도 있고 특정 도메인의 구현 일 수도 있습니다. 아니면 기능을 구현하기 위해 필요한 도메인이나 클래스로 먼저 커밋을 찍고 구현된 도메인이나 클래스를 사용한 기능 구현에 대해 커밋을 다시 찍는 방법도 있을 것 같습니다!! 커밋은 말 그대로 코드의 기록하는 단위이니 카고가 생각하는 적절한 단위로 커밋을 찍으면 될 것 같아요!!

### 5

카고의 고민대로 지금 진행하는 미션 정도에서는 굳이 Controller 클래스를 만들 필요 없이 main 함수가 위치하는 Application 클래스를 컨트롤러로 사용해도 될 것 같아요. 컨트롤러는 도메인과 뷰를 연결해주는 역할을 담당하는데, 이때 비즈니스 로직은 도메인 객체가 가지고 있는게 맞다고 생각합니다. 지금 미션은 콘솔 미션이기에 뷰를 명확히 분리하기가 어렵고, 따라서 컨트롤러를 카고가 생각하는 이상적인 구조로 만들어 사용하기는 무리가 있을 수 있습니다. 너무 컨트롤러를 컨트롤러답게 써야지! 라는 관점보다는 최대한 도메인 로직과 뷰 로직의 의존성 방향과 의존 범위를 제한하는 관점에서 개발을 하시는 것이 더 좋을 것 같습니다!!

### 6

말씀대로 DTO는 특정 레이어 간의 의존성을 끊어낼 수 있는 도구 중 하나입니다. 카고는 작성해주신 고민대로 도메인 객체가 프레젠테이션 레이어(뷰)에서 조작이 되는 것을 피하고 싶기에 DTO를 사용하려고 했고, 이는 DTO의 적절한 사용 방법이라고 생각합니다. 그런데 이때 생기는 문제는 DTO의 관리가 늘어난다는 점입니다. 개발에서 흔히 말하는 트레이드 오프인데, DTO를 사용함으로써 얻는 레이어간의 의존성 분리와 그로 인해 생기는 DTO 객체들의 매핑과 관리 포인트의 증가가 트레이드 오프 관계가 될 것입니다. 이때 개발자는 적절한 범위에서 DTO를 사용하고 적절한 수준에서만 레이어 분리를 함으로써 합리적인 구조와 코드 관리 비용을 결정하게 됩니다. 

카고의 고민처럼 DTO를 상황에 맞게, 변수 값에 맞게 모두 나눠서 개발한다면 사용 범위는 제한되겠지만 너무 많은 DTO가 생기게 되면서 관리 포인트가 너무 커질 수 있습니다. 정작 구현해 둔 도메인 클래스는 하나인데 DTO만 7개 8개가 되는 이상한 상황이 연출 될 수도 있습니다. 저는 DTO는 특정 도메인 기준이나 레이어의 유형에 따라 하나 정도만 관리하여 최소한으로 유지하려고는 하는데 이 또한 정답은 아니기에 카고가 트레이드 오프를 생각해보고 적절한 범위로 사용하면 될 것 같습니다.

여기서 주의해야 할 점은 DTO와 도메인 객체 간의 의존성 방향이 적절한지, 모든 코드에서 DTO 생성 규칙이 일관되게 유지되고 있는지 입니다. 이 점들을 유의하면서 한번 개발해보시면 좋을 것 같습니다 :)

2024-03-10 13:47 UTC, devhoya97 commented on src/main/java/blackjack/domain/card/DeckFactory.java
> +}
동의합니다. 지금 보니 덱 만드는 공장에서 덱을 만들지 않는 모습은 어색하네요. 반영하였습니다 !!

2024-03-10 14:09 UTC, devhoya97 commented on src/main/java/blackjack/domain/card/DeckShuffleFactory.java
> +    }
스티치의 의견대로 수정하니 컬렉션을 생성한 메서드에서 컬렉션에 멤버를 추가하는 로직까지 한 번에 가질 수 있어서 가독성이 좋아졌어요! 

인덴트를 2->1로 줄이려는 이유는 결국 가독성 때문인데, 이유를 생각하지 않고 맹목적으로 메서드 분리만 하려했던 것 같아요. 좋은 지적 감사합니다 !

2024-03-10 14:33 UTC, devhoya97 commented on src/main/java/blackjack/view/InputView.java
> +    private static final Scanner scanner = new Scanner(System.in);
명사로 표기해야하는 부분 말씀하신 것 맞을까요?! 막판에 급하게 상수처리하느라 신경을 못 썼네요 ...! 아래와 같이 수정하였습니다!

```java
private static final String MORE_CARD = "y";
private static final String NOT_MORE_CARD = "n";
```

2024-03-10 14:41 UTC, devhoya97 commented on src/main/java/blackjack/domain/Players.java
> +            players.add(Player.from(new Name(name)));
Player의 정적 팩토리 메서드가 값 객체가 아닌 문자열을 받도록 수정하면, Player를 생성하는 객체 입장에서 편해지니 책임분리 관점에서 더 명확한 것 같네요! 반영하였습니다!!

2024-03-10 14:54 UTC, devhoya97 commented on src/main/java/blackjack/domain/dto/DealerDto.java
> +public class DealerDto {
컨트롤러 역할을 수행하는 Application 클래스와 view는 서로 다른 레이어에 속한다고 생각했고, `Application -> view` 방향으로 도메인 객체에 대한 정보를 안전하게 전달하기 위해 DTO를 사용했어요. 따라서 Application과 view가 DTO에 의존하는 구조를 만들기 위해선 blackjack 패키지 레벨에 dto 패키지를 두는 게 나아보여요! 

제 생각이 맞을까요 ...?!

2024-03-10 16:01 UTC, devhoya97 commented on src/main/java/blackjack/domain/GameBoard.java
> +    }
곰곰이 생각해보니 DTO를 생성하는 책임은 컨트롤러에 있는 것 같아요. 그리고 컨트롤러 단과 view 단에서 데이터를 전달하기 위해 쓰이는 DTO에 대한 유지보수를 도메인이 신경 쓸 필요는 없을 것 같네요!

해당 내용 반영하였습니다!! 그리고 PlayersDto는 과한 것 같아 삭제하고, PlayerDto 여러 개를 한 번에 전달하고 싶은 경우엔 `List<PlayerDto>`를 사용하도록 변경했어요.

2024-03-11 05:51 UTC, devhoya97 commented on src/main/java/blackjack/Application.java
> +    }
불필요한 파라미터는 제거하는 게 좋겠네요. 반영했습니다 !!

2024-03-11 08:40 UTC, devhoya97 commented on src/main/java/blackjack/domain/card/Card.java
> +public record Card(Number number, Suit suit) {
아래 코드와 같이 캐시를 적용해보았습니다!
```java
public class Card {

    private static final List<Card> CACHE;

    private final Number number;
    private final Suit suit;

    private Card(final Number number, final Suit suit) {
        this.number = number;
        this.suit = suit;
    }

    static {
        final List<Card> cache = new ArrayList<>();
        for (final Number number : Number.values()) {
            cache.addAll(createSuits(number));
        }
        CACHE = Collections.unmodifiableList(cache);
    }

    private static List<Card> createSuits(final Number number) {
        final List<Card> suits = new ArrayList<>();
        for (final Suit suit : Suit.values()) {
            suits.add(new Card(number, suit));
        }
        return suits;
    }

    public static Card of(final Number number, final Suit suit) {
        return CACHE.get((number.ordinal() * Suit.values().length) + suit.ordinal());
    }
}
```
처음엔 (number, suit) 쌍으로 적절한 값을 생성해 Map의 key로서 사용하고, 이에 대응되는 Card 객체를 저장해둔 뒤 사용자가 객체 생성을 원할 때마다 key 값으로 캐시에서 객체를 찾아 반환하도록 설계할까 고민해봤어요. 하지만 천천히 생각해보니 Card.of 메서드를 호출할 때 매개변수로 enum을 사용한 덕분에 존재하지 않는 카드에 대해서는 요청할 가능성이 없으므로 사용자가 원하는 카드는 항상 캐시에 존재할 것이고, 따라서 인덱스를 활용해서 캐시에 접근하는 것이 Map보다 성능상 이점을 가질 것 같아서 리스트를 사용했습니다! (Integer 클래스의 구현을 보니 성능을 최대로 끌어올리기 위해 배열을 사용한 것으로 보이는데, 저는 미션의 프로그래밍 요구사항을 맞추기 위해 컬렉션을 사용했어요.)

위와 같은 접근이 스티치가 의도한 방향이 맞을까요?!

***

그리고 캐싱을 처음 적용해보면서 생긴 질문들이 있습니다!

1. 현재 테스트코드를 제외하곤 Card를 만드는 객체는 DeckShuffleFactory 뿐입니다. 따라서 DeckShuffleFactory에서 중복된 카드를 생성하지 않도록 설계한다면, 캐싱을 사용하는 장점이 없지 않을까? 라는 생각이 들었어요. Card만을 독립적으로 바라본다면 불필요한 객체 생성을 미연에 방지할 수 있다는 장점이 보였지만, 애플리케이션 레벨에서 보면 중복된 카드를 만드는 과정이 없었기에 사실 캐싱을 하는 장점을 느끼기 힘들었어요. 
이에 대한 스티치의 생각이 궁금합니다 !!!

2. 캐싱 구조를 처음 설계해봐서 그런지 멤버변수, 메서드 순서가 올바르게 배치되어 있는지 잘 모르겠어요..! 구글코드컨벤션에는 위와 같은 상황에서 멤버변수와 메서드의 배치를 어떻게 하라는 조언을 찾지 못해서 제가 스스로 판단하기에 가독성이 좋도록 순서를 배치했는데, 스티치가 보기에 배치에 문제가 없는지 궁금합니다!!

2024-03-11 13:48 UTC, devhoya97 commented on src/main/java/blackjack/domain/Outcome.java
> +    }
Dto의 목적은 데이터 전달용 객체이기에  getter와 setter를 제외한 나머지 메서드는 가지고 있지 않게 만드려고 노력했습니다! Dto가 로직을 가지고 있어도 괜찮을까요 ??

Map으로 간단히 만들어 처리하는 리팩토링은 Collectors.groupingBy 메서드를 활용해 진행했습니다!! Collectos 라이브러리에 대해 제대로 공부해본 적이 없어서 아직 어색하지만, 이렇게 사용해보니 정말 유용하네요 !!

2024-03-11 14:44 UTC, devhoya97 commented on src/main/java/blackjack/domain/Referee.java
> +public class Referee {
심판은 게임 결과(승패)를 결정하는 책임이 있기에 심판의 행동이 게임 결과를 반환하는 것이 더 자연스럽다고 생각했는데, 다시 생각해보니 게임 결과를 `살아있는 객체`라고 생각하면 게임 결과가 카드들을 보고 게임 결과를 알려줄 책임을 갖는게 더 자연스럽게 느껴지네요!

해당 내용 반영하였습니다!

2024-03-13 06:30 UTC, lxxjn0 approved these changes
카고, 피드백 반영하시느라 수고하셨습니다 👍🏼 

리뷰를 진행하면서 세세한 부분들에 대해서도 카고가 많이 생각하고 고민하고 있다는 느낌을 많이 받을 수 있었습니다. 크게 리뷰를 남길만한 부분은 없을 것 같아 다음 단계 진행하시면서 피드백 더 진행하면 될 것 같습니다 :)

추가로 남겨주신 질문 중에서 상속을 잘 쓰지 못하고 있는 것 아닌가라는 말씀을 하셨는데 상속을 하면서 얻는 장점은 이미 충분히 있다고 생각합니다. 추상화를 함으로써 추상화의 100%를 얻겠다고 생각하시지 말고 기존의 로직에서 추상화를 하면서 어떤 점들에서 이점을 얻을 수 있었는지를 느끼셨다면 그걸로도 충분하지 않을까 생각합니다. 도메인을 조금씩 변경하면서 어떤 장점을 잃게되기도 하고 그로 인해 어떤 장점을 얻을 수도 있습니다. 이번에 딜러가 덱을 관리하면서 생긴 부분처럼요. 이런 부분은 본인이 생각하기에 도메인의 적절한 책임을 잘 규정지어서 관리한다면 크게 신경쓰지 않으셔도 될 부분이라 생각하기에 지금의 카고의 도메인 설계에 따라 코드를 계속 작성해가시면 될 것 같습니다 👍🏼

2024-03-13 06:30 UTC, lxxjn0 commented on src/main/java/blackjack/domain/Player.java
> +        final Hand hand = new Hand(new ArrayList<>());
Hand를 생성할 때 기본적으로 빈 리스트를 넣는다면 Hand의 기본 생성자를 활용해보는 것도 방법이 될 수 있을 것 같습니다.

2024-03-13 06:30 UTC, lxxjn0 commented on src/main/java/blackjack/domain/GameBoard.java
>      }
블랙잭 게임에서 처음에 2장의 카드를 뽑는 것이 비즈니스 로직인 만큼 2라는 숫자를 적절한 상수 값으로 관리하고 반복문으로 처리하면 어떨까요? 그렇다면 2장을 뽑는다는 행위에 비즈니스 적인 의미를 더 파악하기 쉬울 것 같습니다 :)

2024-03-13 07:11 UTC, merged

2024-03-13 09:00 UTC, devhoya97 commented on src/main/java/blackjack/domain/Outcome.java
> +    }
> DTO에서 비즈니스 로직을 처리하는 것이 아닌 로직들은 충분히 있어도 된다고 생각합니다. 결국 DTO도 객체인데 단순히 데이터만 감싸는 객체라면 그냥 Collection을 사용하는 게 더 낫다고 생각합니다.

그렇군요!! 이 부분에서도 객체의 역할과 책임을 생각해볼 수 있겠네요. 좋은 관점 감사합니다!

2024-03-13 09:07 UTC, devhoya97 commented on src/main/java/blackjack/domain/card/Card.java
> +public record Card(Number number, Suit suit) {
> 하나의 덱이 부족할만큼의 인원이 참가한다면 이때는 중복된 카드 생성이 발생할 수 있습니다.

그렇네요. 이런 케이스가 있겠군요! 프로그램을 더 견고하게 짜려면 덱을 다 소모했을 때, 새로운 덱을 받는 로직을 추가해야겠네요. 그리고 이 때는 말씀대로 캐시가 효과적일 것 같아요!

> 전체적인 맥락에서의 컨벤션만 잘 지킨다면 이러한 세부 사항은 너무 신경쓰지 않으셔도 괜찮을 것 같아요!

넵!! 컨벤션만 지킨다면 상황에 따라 가독성이 높아지는 방향으로 유연하게 선택해도 되겠네요!

2024-03-13 10:27 UTC, devhoya97 commented on src/main/java/blackjack/view/InputView.java
>      private static final Scanner scanner = new Scanner(System.in);
아아 그렇네요..! 항상 상수는 String, int 값만 처리해봤다보니 객체도 static final 이면 상수처리해야 한다는 것을 생각 못했네요 ..! 좋은 지적 감사합니다 :)

2024-03-14 04:08 UTC, devhoya97 commented on src/main/java/blackjack/domain/GameBoard.java
>      }
동의합니다! 2를 상수처리 해주면 dealer.draw() 가 두 번 수행되어야 하는 이유를 상수의 이름으로 표현할 수 있겠네요! 반영했습니다 :)