[1단계 - 블랙잭 게임 실행] 땡이(정지호) 미션 제출합니다.
woowacourse/java-blackjack pull request #639
Opened 2024-03-08 08:34 UTC by J-I-H-O

작성중...

2024-03-08 16:57 UTC, yxxnghwan requested changes
안녕하세요 땡이! 블랙잭 미션 리뷰하게 된 알렉스입니다!
미션 잘 구현해주셨네요! 생각해볼만한 부분들 코멘트 남겼으니 확인 부탁드립니다🙂

2024-03-08 16:57 UTC, yxxnghwan commented on src/main/java/blackjack/BlackjackController.java
> +    public static void main(String[] args) {
main 메소드가 Controller라고 네이밍된 클래스에 있네요..!
땡이가 생각하는 컨트롤러는 무엇인가요? 그리고 메인메소드의 책임을 갖는 클래스는 어떤 클래스가 좋을지 고민해보아요🤔

2024-03-08 16:57 UTC, yxxnghwan commented on src/main/java/blackjack/domain/player/Hand.java
> +                minimumSum += 10;
매직넘버가 상수화되면 좋을 것 같아요🙂

2024-03-08 16:57 UTC, yxxnghwan commented on src/main/java/blackjack/domain/cardgame/CardDeck.java
> +    private final Stack<Card> deck;
자료형을 Stack으로 해주셨네요..! 스택으로 구현해서 얻는 이점은 무엇이었나요?

2024-03-08 16:57 UTC, yxxnghwan commented on src/main/java/blackjack/domain/cardgame/CardGameJudge.java
> +        Map<Player, WinningStatus> result = new LinkedHashMap<>();
전체적으로 지역변수에 final 키워드를 붙이시는 것 같던데 여기는 빠져있네요..!
땡이가 생각하는 지역변수의 final을 붙였을 때의 이점은 무엇인가요?

2024-03-08 16:57 UTC, yxxnghwan commented on src/main/java/blackjack/domain/player/Dealer.java
> +public class Dealer extends Player {
딜러가 플레이어를 상속하는 구조로 구현해주셨네요..! 어떤 장단점이 느껴지셨나요?

2024-03-08 16:57 UTC, yxxnghwan commented on src/main/java/blackjack/domain/cardgame/CardGameResult.java
> +                .filter(playerWinningstatus -> playerWinningstatus.equals(LOSE))
```suggestion
                .filter(playerWinningStatus -> playerWinningStatus.equals(LOSE))
```

2024-03-08 16:57 UTC, yxxnghwan commented on src/main/java/blackjack/domain/cardgame/CardGameJudge.java
> +    public static final int BUST_THRESHOLD = 21;
좋은 네이밍이네요! 👍🏿

2024-03-08 16:57 UTC, yxxnghwan commented on src/main/java/blackjack/domain/cardgame/CardGameJudge.java
> +    }
플레이어와 딜러 모두 bust 되지 않았고 딜러가 점수가 더 높아서 플레이어가 패배하는 케이스는 테스트가 없는 것 같네요! 추가되면 좋을 것 같습니다!

2024-03-08 16:57 UTC, yxxnghwan commented on src/main/java/blackjack/domain/player/Dealer.java
> +    }
딜러가 16 이하면 카드를 더 받는다는 요구사항은 테스트가 없는 것 같네요! 테스트하지 않아도 괜찮은 부분일까요?

2024-03-08 16:57 UTC, yxxnghwan commented on src/test/java/blackjack/domain/player/HandTest.java
> +    }
Ace를 포함하는 케이스와 포함하지 않는 케이스 모두 테스트가 있으면 좋을 것 같아요 🙂

2024-03-08 16:57 UTC, yxxnghwan commented on src/test/java/blackjack/domain/player/NameTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
에러 메시지도 테스트해보면 어떨까요?

2024-03-08 16:57 UTC, yxxnghwan commented on src/test/java/blackjack/domain/player/NameTest.java
> +import blackjack.domain.player.Name;
불필요한 import인 것 같아요!

2024-03-13 08:48 UTC, J-I-H-O commented on src/main/java/blackjack/domain/cardgame/CardGameResult.java
> +                .filter(playerWinningstatus -> playerWinningstatus.equals(LOSE))
```
.filter(playerWinningStatus -> LOSE.equals(playerWinningStatus))
```
위 코드를 말씀하시는게 맞을까요? NPE를 방지하기 위한 좋은 습관인 것 같습니다 😊

2024-03-13 15:04 UTC, J-I-H-O commented on src/main/java/blackjack/domain/cardgame/CardDeck.java
> +    private final Stack<Card> deck;
### Stack의 사용
`CardDeck` 내부에서 카드를 섞기 위해 `Collections.shuffle()` 을 사용하기로 결정했고, 이를 사용하기 위해서 List 인터페이스를 구현한 클래스를 선택하기로 했어요.

처음에는 선택지 중 Stack이 실제 카드 뭉치의 특성을 가장 잘 나타낸다고 생각했어요. 현실에서도 카드 뭉치의 가장 위쪽에 있는 카드를 한장씩 뽑아서 사용하니까요!
삽입, 삭제 또한 O(1)에 해결할 수 있으니 성능상 문제 또한 없을 것이라고 생각했어요.

그러나 알렉스의 리뷰를 받고 Stack 클래스의 내부 구현 코드를 살펴보니 `push()`와 `pop()` 메서드 모두 `syncronized` 키워드를 사용하는 것을 확인할 수 있었고, 이는 Lock을 거는 작업으로 인해 오버헤드가 발생한다는 사실을 알게되었어요.

### Stack을 대체하기 위한 후보군
Stack을 대체할 수 있는 후보군으로 ArrayList와 LinkedList를 고려해보았습니다.
- **ArrayList**
  - 배열의 중간에 삽입, 삭제 연산을 수행하는 경우 시간 복잡도는 O(N) 이지만, 가장 마지막에 삽입 삭제를 수행하는 경우 O(1)
  - 그러나 `add()` 메서드의 내부 구현을 살펴보았을 때, 현재 할당된 최대 size를 넘어서서 `add()` 를 호출하는 경우, 더 큰 크기의 배열을 생성하고 값을 복사해 넣는 작업을 수행하는 것을 확인할 수 있었음 (오버헤드 발생)
- **LinkedList**
  - 가장 앞쪽에 삽입, 삭제를 수행하는 경우 시간 복잡도가 O(1)
  - 단, 노드 간 링크를 연결하고 끊어내는 과정에서의 오버헤드 발생

ArrayList와 LinkedList 모두 사용 방법에 따라 삽입, 삭제의 시간 복잡도를 O(1)로 줄일 수 있었지만, 각각 오버헤드를 가지는 포인트가 달랐기 때문에 둘 중 어느 것을 선택할지 고민했어요.
이에 직접 성능을 측정해보기로 생각했고, 결과는 다음과 같았습니다.

### 성능 측정
**테스트 코드**

<details>
<summary>접기/펼치기</summary>

```
public class ListTest {
    private static final int TRIALS = 10000000;
    public static final String LINE_SEPARATOR = System.lineSeparator();

    @Test
    void Stack_push_성능_측정() {
        System.out.println("Stack: push");
        Stack<Card> list = new Stack<>();
        long startTime = System.currentTimeMillis();

        for (int i = 0; i < TRIALS; i++) {
            list.push(new Card(ACE, CLOVER));
        }

        long estimatedTime = System.currentTimeMillis() - startTime;
        System.out.println(estimatedTime + "ms" + LINE_SEPARATOR);
    }

    @Test
    void ArrayList_add_성능_측정() {
        System.out.println("ArrayList: add");
        List<Card> list = new ArrayList<>();
        long startTime = System.currentTimeMillis();

        for (int i = 0; i < TRIALS; i++) {
            list.add(new Card(ACE, CLOVER));
        }

        long estimatedTime = System.currentTimeMillis() - startTime;
        System.out.println(estimatedTime + "ms" + LINE_SEPARATOR);
    }

	  @Test
    void ArrayList_add_처음부터_size를_할당하는_경우_성능_측정() {
        System.out.println("ArrayList: add - 처음부터 넉넉한 size를 할당");
        List<Card> list = new ArrayList<>(TRIALS);
        long startTime = System.currentTimeMillis();

        for (int i = 0; i < TRIALS; i++) {
            list.add(new Card(ACE, CLOVER));
        }

        long estimatedTime = System.currentTimeMillis() - startTime;
        System.out.println(estimatedTime + "ms" + LINE_SEPARATOR);
    }

    @Test
    void LinkedList_add_성능_측정() {
        System.out.println("LinkedList: add");
        List<Card> list = new LinkedList<>();
        long startTime = System.currentTimeMillis();

        for (int i = 0; i < TRIALS; i++) {
            list.add(new Card(ACE, CLOVER));
        }

        long estimatedTime = System.currentTimeMillis() - startTime;
        System.out.println(estimatedTime + "ms" + LINE_SEPARATOR);
    }

    @Test
    void Stack_pop_성능_측정() {
        System.out.println("Stack: pop");
        Stack<Card> list = new Stack<>();

        for (int i = 0; i < TRIALS; i++) {
            list.push(new Card(ACE, CLOVER));
        }

        long startTime = System.currentTimeMillis();

        while (!list.isEmpty()) {
            list.pop();
        }

        long estimatedTime = System.currentTimeMillis() - startTime;
        System.out.println(estimatedTime + "ms" + LINE_SEPARATOR);
    }

    @Test
    void ArrayList_뒤에서_remove_성능_측정() {
        System.out.println("ArrayList: remove - 뒤에서부터 삭제");
        List<Card> list = new ArrayList<>();

        for (int i = 0; i < TRIALS; i++) {
            list.add(new Card(ACE, CLOVER));
        }

        long startTime = System.currentTimeMillis();

        while (!list.isEmpty()) {
            list.remove(list.size() - 1);
        }

        long estimatedTime = System.currentTimeMillis() - startTime;
        System.out.println(estimatedTime + "ms" + LINE_SEPARATOR);
    }

    @Test
    void LinkedList_앞에서_remove_성능_측정() {
        System.out.println("LinkedList: remove - 앞에서부터 삭제");
        List<Card> list = new LinkedList<>();

        for (int i = 0; i < TRIALS; i++) {
            list.add(new Card(ACE, CLOVER));
        }

        long startTime = System.currentTimeMillis();

        while (!list.isEmpty()) {
            list.remove(0);
        }

        long estimatedTime = System.currentTimeMillis() - startTime;
        System.out.println(estimatedTime + "ms" + LINE_SEPARATOR);
    }
}
```
</details>

**출력**
```
Stack: push
429ms

ArrayList: add
308ms

ArrayList: add - 처음부터 넉넉한 size를 할당
208ms

LinkedList: add
2751ms

Stack: pop
81ms

ArrayList: remove - 뒤에서부터 삭제
24ms

LinkedList: remove - 앞에서부터 삭제
263ms
```

여러번의 실행 결과 ArrayList가 LinkedList보다 삽입 삭제 시 성능상 앞서는 모습을 볼 수 있었어요.
ArrayList가 배열을 복사할 때 발생하는 비용에 비해 LinkedList가 링크를 연결하고 끊어내는 과정에서 발생하는 비용이 크기 때문이라고 추정하고, 이에 ArrayList를 사용하기로 결정했습니다.

2024-03-13 15:12 UTC, J-I-H-O commented on src/main/java/blackjack/domain/player/Dealer.java
> +    }
테스트 코드 추가 완료했습니다! 😊

2024-03-13 15:12 UTC, J-I-H-O commented on src/main/java/blackjack/domain/cardgame/CardGameJudge.java
> +    }
테스트 코드 추가 완료했습니다! 😊

2024-03-13 15:13 UTC, J-I-H-O commented on src/test/java/blackjack/domain/player/NameTest.java
> +import blackjack.domain.player.Name;
아이고 제대로 정리가 안됐나보네요..! 제거 완료했습니다! 😊

2024-03-13 15:13 UTC, J-I-H-O commented on src/test/java/blackjack/domain/player/HandTest.java
> +    }
테스트 코드 추가 완료했습니다! 😊

2024-03-14 01:44 UTC, J-I-H-O commented on src/main/java/blackjack/domain/cardgame/CardGameJudge.java
> +        Map<Player, WinningStatus> result = new LinkedHashMap<>();
먼저 클래스의 필드와 메서드의 파라미터에는 습관적으로 final 키워드를 붙여주는데요, 외부로부터의 예측하지 못한 변경을 막기 위함입니다.

다만 지역변수에까지 final 키워드를 붙여야할까는 고민할 필요가 있어 보여요.
지역 변수는 클래스의 필드나 메서드 파라미터와는 다르게 해당 scope에서만 사용되는 값이기 때문에 변경이 일어나더라도 해당 scope에만 영향이 갈 뿐이고, 변경으로 인해 발생한 예상치 못한 동작의 원인을 추적하기 쉽습니다.
또, 지역 변수가 선언된 위치와 해당 변수를 사용하는 지점의 위치가 가깝기 때문에 오용할 가능성도 낮다고 생각이 듭니다.

그래도 최대한 방어적으로 코드를 작성해보자는 생각에 지역변수에도 final 키워드를 붙여주었는데요, 알렉스의 생각은 어떤지 궁금합니다! 😊

(참고로 해당 부분에 final 키워드가 빠져있는건 단순 실수입니다 ㅎㅎ;)

2024-03-14 02:09 UTC, J-I-H-O commented on src/main/java/blackjack/domain/player/Dealer.java
> +public class Dealer extends Player {
먼저, 딜러도 게임에 참여하는 플레이어라고 생각했고, 따라서 딜러와 플레이어 간 IS-A 관계가 성립한다고 생각했습니다. 
또, 딜러가 플레이어의 모든 행위를 필요로하는 동시에 딜러만의 행위가 추가로 정의되어야 합니다. 만약 플레이어의 메서드가 변경된다고 하더라도, 이는 딜러에게도 반영되어야 하는 변경사항일 것이기 때문에 상속을 사용하는 것이 적합한 상황이라고 생각했습니다.

딜러가 플레이어를 직접 상속하는 구조의 대안으로 추상 클래스 또는 인터페이스를 활용하는 방법과, 상속이 아닌 Composition을 사용하는 방법을 생각해보았는데요,

1. 추상 클래스 또는 인터페이스를 활용한 방법
    - 딜러와 플레이어가 공통으로 상속 및 구현하는 추상 클래스 또는 인터페이스를 정의하는 방법
    - 딜러와 플레이어가 공통적으로 사용하는 메서드를 중복해서 구현해야 함
    - 게임에 참여하면서, 또 다른 역할을 가진 사람이 추가될 가능성이 낮은 상황에 적합하지 않은 과도한 추상화라고 생각함
2. Composition을 사용하는 방법
    - Dealer의 내부에 Player가 필드로 포함되도록 구성하는 방법
    - Dealer가 Player에게 동작을 요청해야 하기 때문에 Dealer 내부에 위임을 위한 메서드가 많아짐
    - 딜러와 플레이어가 IS-A 관계임에도 HAS-A 관계에서 사용하는 Composition을 사용하는 것이 어색함

저는 이같은 생각에 상속을 사용했는데, 
상속을 사용함으로써 발생할 수 있는 문제점과, 더 좋은 방법이 있을지 궁금합니다!

2024-03-14 02:33 UTC, J-I-H-O commented on src/test/java/blackjack/domain/player/NameTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
에러 메세지를 테스트 했을 때의 장단점에 대해 생각해보았어요!
- **장점** : 테스트 시 예외 발생 원인을 정확하게 파악할 수 있음
- **단점** : 에러 메세지를 수정하는 경우, 테스트 코드도 수정해주어야 함

이처럼 에러 메세지를 테스트한다면 테스트의 정확성이 올라가겠지만, 테스트의 유지보수 비용 또한 함께 올라갈 것 같아요.

이번 미션에서는 세부 사항보다는 주요 기능 테스트에 집중하기 위해 에러 메세지 테스트를 고려하지 않고 일단 넘어갔습니다.

만약 두 방법 중 하나를 선택해야 한다면, 저는 우위를 정하기 힘들어서 팀 컨벤션을 따라갈 것 같은데요, 알렉스는 어떤 방법을 선호하시는지 궁금합니다! 😊

2024-03-14 04:47 UTC, J-I-H-O commented
안녕하세요 알렉스! 😊
정성어린 리뷰 감사드립니다! 작성해주신 리뷰 내용 반영 완료했구, 
 description에도 내용 추가해보았습니다. 
감사합니다!

2024-03-15 07:09 UTC, yxxnghwan commented on src/main/java/blackjack/BlackjackController.java
> +    public static void main(String[] args) {
MVC패턴에서 말하는 컨트롤러는 말씀주신 모델과 뷰를 연결해주는 역할이 맞습니다. 다만, 현재 자바 콘솔 게임에서 컨트롤러라는 네이밍이 적절한지 고민해보면 좋을 것 같아요. 컨트롤러가 현재 게임을 실행시키고 있는데, 컨트롤러라는 단어 뜻을 생각하면 어색한 느낌이 많이 듭니다. 무언가 인풋을 넣으면 그 동작을 수행하는게 컨트롤러라고 생각되어요. MVC 패턴에서도 같은 매커니즘으로 동작하기도 하구요. 현재 자바 콘솔 프로그램에서 컨트롤러의 역할은 무엇인가요?

2024-03-15 07:11 UTC, yxxnghwan commented on src/main/java/blackjack/domain/cardgame/CardDeck.java
> +    private final Stack<Card> deck;
직접 성능까지 테스트해보셨군요 👍🏿👍🏿

2024-03-15 07:13 UTC, yxxnghwan commented on src/main/java/blackjack/domain/cardgame/CardGameJudge.java
> +        Map<Player, WinningStatus> result = new LinkedHashMap<>();
개인적으론 final을 붙이는 것을 좀 더 선호하고 있어요. 땡이가 말했듯 예측할 수 없는 변경을 막기도 하고, 변수에 다른 값이 재할당 된다면 처음 선언한 변수에서 의미가 흐트러질 확률이 존재한다고 생각하거든요 :)
뭐가 되었든 정답은 없고 각자의 컨벤션에 맞게 일관되면 좋다는 생각이 가장 크긴 합니다 ㅎㅎ

2024-03-15 07:18 UTC, yxxnghwan commented on src/main/java/blackjack/domain/player/Dealer.java
> +public class Dealer extends Player {
조합을 사용하는 방법에서 딜러가 플레이어를 인스턴스 변수로 가지는게 아니라 공통된 동작과 상태 자체를 딜러와 플레이어가 각각 인스턴스 변수로 담아서 조합을 사용할 수 있을 것 같아요 :)

2024-03-15 07:18 UTC, yxxnghwan commented on src/main/java/blackjack/domain/cardgame/CardGameResult.java
> +                .filter(playerWinningstatus -> playerWinningstatus.equals(LOSE))
오 아뇨! 카멜케이스가 지켜지지 않는 것 같아서 코멘트 드렸습니다..!

2024-03-15 07:22 UTC, yxxnghwan commented on src/test/java/blackjack/domain/player/NameTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
TDD관점에서 보았을 때 요구사항의 변경으로 인해 에러메시지가 수정되어야하는 경우 다음과 같은 순서로 작업되어야할 것 같아요.

1. 테스트에서 에러 메시지 수정
2. 테스트 실패
3. 프로덕션 코드에서 에러 메시지 수정
4. 테스트 통과

메시지가 일치하는지 자체가 중요하진 않을 수 있지만, 1~10이라는 숫자는 중요할 수 있어보여요. 만약 20글자 제한으로 늘어났는데, 계속 1~10자 사이라는 에러 메시지를 던지고 있으면 사용하는 입장에서 소프트웨어를 신뢰할 수 없지 않을까요?

2024-03-15 07:25 UTC, yxxnghwan commented on src/main/java/blackjack/domain/player/Dealer.java
> +public class Dealer extends Player {
상속으로 구현했을 때 플레이어의 변경이 딜러까지 전파될 수 있을 것 같아요. 딱 공통으로 사용되는 부분만 같이 가져가는게 좋을 것 같은데, 그렇다고 공통된 부분만 플레이어에 남기기 위해 플레이어의 변경이 제한되는 문제도 생길 수 있겠네요.

2024-03-15 07:48 UTC, yxxnghwan approved these changes
안녕하세요 땡이! 코멘트 잘 반영해주셨네요!
추가로 몇몇 코멘트 남겨놓긴 했는데, 다음 단계 진행을 위해서 이 PR은 이만 머지하도록 하겠습니다!
다음 단계도 화이팅이에요!💪

2024-03-15 07:48 UTC, yxxnghwan commented on src/main/java/blackjack/view/PlayerChoice.java
> +public enum PlayerChoice {
뭐에 대한 초이스일까요? 클래스명만 보고 알 수 없을 것 같아요.

2024-03-15 07:48 UTC, yxxnghwan commented on src/main/java/blackjack/view/PlayerChoice.java
> +    }
이 메소드는 왜 여기에 있나요?

2024-03-15 07:48 UTC, yxxnghwan commented on src/main/java/blackjack/controller/BlackjackController.java
> +        while (!player.isBust() && InputView.askForMoreCard(playerName)) {
```suggestion
        while (player.isNotBust() && InputView.askForMoreCard(playerName)) {
```

위처럼 되는건 어떨까요?

2024-03-15 07:48 UTC, yxxnghwan commented on src/main/java/blackjack/domain/cardgame/CardGame.java
> +public class CardGame {
뭐를 추상화한 클래스인가요? 블랙잭 게임의 동작을 메소드로 가지고 있는데, 이름만 보면 어떤 카드게임인지 알 수 없는 것 같아요.
BlackjackController 클래스와 역할은 어떻게 나눠지는건가요?

2024-03-15 07:48 UTC, yxxnghwan commented on src/main/java/blackjack/view/CardShapeStrings.java
> +public enum CardShapeStrings {
클래스 뒤에 Strings가 붙는 이유는 무엇인가요?

2024-03-15 07:48 UTC, yxxnghwan commented on src/main/java/blackjack/view/CardShapeStrings.java
> +
다른 Enum값이 추가될 경우를 생각해서 다음처럼 쓰곤 합니다 :)
```suggestion
    DIAMOND("다이아몬드"),
    CLOVER("클로버"),
    ;
```

2024-03-15 07:48 UTC, yxxnghwan commented on src/main/java/blackjack/view/CardShapeStrings.java
> +    }
enum클래스가 기본적으로 가지는 values라는 메소드를 사용해서도 구현 가능할 것 같아요 :)

2024-03-15 07:48 UTC, merged