[1단계 - 블랙잭 게임 실행] 낙낙(이낙헌) 미션 제출합니다.
woowacourse/java-blackjack pull request #656
Opened 2024-03-08 08:48 UTC by nak-honest

안녕하세요! 웨지 :감자: !!
이번에 블랙잭 미션 리뷰이 낙낙이라고 합니다!!
<br>

이번 미션은 페어와 함께 TDD를 진행하면서 최대한 간결하게 코드를 작성하려고 노력했고, 
의식적으로 너무 복잡하게 생각하지 않으려 노력했습니다.
<br>
<br>

## 요청 :두_손을_들고_있는_사람:
웨지가 말씀해주실 문제에 대한 중요도를 수치로서 인지하고, 이를 통해 투자하는 시간을 적절히 분산하여
작은 시간동안 최고의 효율을 내는 리뷰 환경을 만들어보고 싶습니다!
때문에 **`Pn 리뷰 룰`** 적용을 요청드려도 괜찮을 지 궁금합니다!
```
* [P1] : 꼭 반영해 주세요 (Request Changes) - 이슈가 발생하거나 취약점이 발견되는 케이스 등
* [P2] : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 (Comment)
* [P3] : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 (Chore)
* [질문] : 이런 부분이 궁금합니다
```
절대 필수적으로 부탁드리는 부분이 아니며, 괜찮으시다면 부탁드리겠습니다 :) 시간내어 리뷰해주셔서 감사합니다:미소짓는_얼굴:
<br>

## 미션을 진행하며 들었던 고민
1.
페어와 함께 미션을 진행하며, 테스트 코드에서만 쓰이는 메소드가 프로덕션 코드를 침범해도 괜찮은지에 대해 논의를 했었는데요!
예를들어 `CardHand`와 같이 내부를 조회해야 하는 경우에는 `getter` 가 필요하기 때문에 이를 활용해서 테스트 코드를 작성할 수 있었습니다.
하지만 `Deck`은 내부 카드들에 대해 밖에서 조회할 필요가 없습니다. 즉 `getter`와 같은 조회 로직이 필요 없다는 것입니다.

하지만 덱에서 카드를 뽑았을 때 내부에서 해당 카드가 제거되는지를 테스트 함으로써 안정성을 확보하고 싶은데,
이때 저희가 생각해 볼 수 있는 방법은 총 2가지였습니다.

1. AssertJ 의 `extracting` 활용하기
2. `contains`와 같은 메소드를 `Deck`에 추가하기

1번의 방식은 테스트 코드에서만 쓰이는 메소드가 프로덕션을 침범하지는 않지만, 내부 필드 이름이 바뀌었을 때 컴파일이 아닌 런타임 에러가 발생한다는 부분에서 조금 꺼려졌습니다! 가독성도 조금 떨어진다고 느껴졌고, 가져온 필드에 대해 적용할 수 있는 assertJ 라이브러리도 적더라구요..!

2번의 방식은 테스트만을 위한 코드가 프로덕션에 있다는 부분이 꺼려졌지만, 가독성도 올라간다는 느낌이 들었고 위와같은 이유로 런타임 에러가 발생하지 않는다는 부분이 장점으로 여겨졌습니다.

웨지는 어떤 방식이 더 좋은 방식이라고 생각하시는지, 아니면 더 고민하면 좋을만한 포인트가 있는지 여쭈어봅니다!!
<br>
<br>

이외에도 리뷰하시면서 의문이 드는 코드나, 고민할만한 포인트가 있다면 가감없이 리뷰 남겨 주시면 감사하겠습니다!

2024-03-09 01:04 UTC, sihyung92 requested changes
안녕하세요 낙낙~ 리뷰어 웨지입니다! ㅎ

전반적으로 코드 품질이 높아서 리뷰가 아주 편했습니다! 

Pn 리뷰룰을 제안해주셨는데요, 
3개 정도 해보다가 생산자 입장에서 비효율적이라 제맘대로 문제정의하고 새로 구성했습니다 ㅎ
저는 리뷰 스타일이 각각의 코멘트가 말씀해주신 P1~질문 까지를 모두 포괄하는 경우가 많습니다
오히려 말씀해주신대로 구분하려다 애매해지는걸 발견해서요

어차피 모두 봐야하는 코멘트인데 왜 정량화를 요구하실지? 생각해봤고 
리뷰이 입장에서 꼭 반영해야되는 영역과 그렇지 않은 영역이 모호해서 혼란을 느끼셨을 거라고 제맘대로 정했습니다 ㅋㅎ
그래서 [필수] [의견] 두개 정도로 나누어서 코멘트 해두었어요 

[필수] - 제 입장에서 반드시 소명이 되어야 하는 부분
[의견] - 기타 모두

그런데 말씀드리고 싶은 건 리뷰어는 정답을 알고 있는 빨간펜 선생님은 아니고요 
함께 일하기 위해서 나도 이해할 수 있는 코드를 만들어달라는 제안자에 가까워요
(우테코는 어프로브를 못받으면 통과가 안 되니까 관계가 특수하지만요 ㅋ ㅋ)
그리고 현업(최소한 저희 팀)에서는 코드 리뷰는 일의 영역이기도 하지만요,
리뷰의 성실도는 개인에게 달려있습니다. 꼼꼼히 진행되는 리뷰는 본인의 바쁜 업무환경을 감수하고서라도 진행하는 감사의 영역에 가깝습니다.
바쁘면 대충 file changed 훑어보고 LGTM 👍 하고 어프로브 하는 경우도 허다합니다 (저도 절반 넘게 그러는듯 ㅋ ㅋ)

그래서 제안하신걸 보면서 묘한 기분을 느꼈는데요, 리뷰어의 입장은 고려하지 않은 제안이라고 느껴져 누군가에겐 불쾌감을 줄 수 있겠다 싶었어요 ㅎ

물론 제안 자체는 리뷰활동의 생산성을 높이기 위한 제안이란 걸 알고 있고, 요청주시는 태도도 아주 친절하셔서 기분이 나쁘진 않았습니다. 오히려 용기내어 제안해주셔서 감사합니다.

리뷰 활동 중 불편함을 느끼시는 부분을 말씀주신다면 함께 논의하여 리뷰어 리뷰이 모두 공감할 수 있는 리뷰 룰을 정하는데 도움이 될거 같습니다 ㅎ

Q&A
이런 경우 전 쿨하게 contains 추가합니다. 테스트를 위한 프로덕션 코드는 피하는 게 좋지만 extracting 보다는 나은거 같아요 ㅎ extracting은 코드 리팩토링 됐을 때 컴파일 오류로 감지가 안되니까요

2024-03-11 05:25 UTC, nak-honest commented on docs/README.md
> +## 블랙잭 기능 구현 문서 🔥
가장 보기 쉬운 곳에 있어야 한다는 의견에 저도 동의합니다!

2024-03-11 05:53 UTC, nak-honest commented on docs/README.md
> +## 블랙잭 기능 구현 문서 🔥
문서는 보기 쉬운 곳에 있어야 한다는 부분에 동의합니다!

2024-03-11 05:57 UTC, nak-honest commented on docs/README.md
> +## 블랙잭 기능 구현 문서 🔥
문서는 보기 쉬운 곳에 있어야 한다는 부분에 동의합니다!
프리코스 미션은 docs/README.md 에 기능 목록을 작성하라는 것이 요구사항이었는데,
그 이후 습관적으로 같은 곳에 기능 명세서를 작성했네요.

리팩토링시 반영하겠습니다 :)
감사합니다!!

2024-03-11 06:02 UTC, nak-honest commented on docs/README.md
> +- [ ] 모든 기능을 TDD로 구현해 단위 테스트가 존재해야 한다. 단, UI(System.out, System.in) 로직은 제외
단순 누락입니다..!

추가적인 기능까지 TDD로 다 구현한 뒤 체크하려 했지만, 마지막에 체크하지 못했네요😢

2024-03-11 06:13 UTC, nak-honest commented on src/main/java/blackjack/BlackjackController.java
> +		UnShuffledDeckGenerator deckGenerator = UnShuffledDeckGenerator.getInstance();
돌이켜보면 조금 과하게 유지보수성을 챙긴 것 같습니다.

당시에는 좀 더 다양한 방식으로 객체를 생성할 수 있으니 팩토리 객체로 빼서 나쁠게 없다는 생각이었습니다.
하지만 웨지의 의견을 듣고 고민해보니,
현재 소프트웨어에서는 Deck 객체가 한가지 방식으로만 생성되므로 팩토리 객체로 따로 빼는 것은 오히려 소프트웨어의 복잡성을 증가시킬 수 있겠다는 생각이 드네요.

"팩토리 객체로 따로 빼면 좋은 경우는 객체를 생성하는 방식이 다양하고 복잡할 때" 라는 것을 다시한번 인식하게 되었네요 :)
감사합니다!

2024-03-11 07:06 UTC, nak-honest commented on src/main/java/blackjack/domain/card/Deck.java
> +		validate(copyDeck);
먼저 위와 같이 복사를 먼저 한뒤 검증을 한 이유는 "이펙티브 자바 아이템 50 적시에 방어적 복사본을 만들라" 에 나와 있는 다음 내용 때문이었습니다.

> 매개변수의 유효성을 검사(아이템 49)하기 전에 방어적 복사본을 만들고, 이 복사본으로 유효성을 검사한 점에 주목하자. 순서가 부자연스러워 보이겠지만 반드시 이렇게 작성해야 한다. 멀티스레딩 환경이라면 원본 객체의 유효성을 검사한 후 복사본을 만드는 그 찰나의 취약한 순간에 다른 스레드가 원본 객체를 수정할 위험이 있기 때문이다. (304p)

<br>

물론 아래와 같이 필드에 바로 복사본을 할당하면, 추가적인 참조변수를 할당하지 않고 위의 순서를 만족할 수 있습니다.

```java
this.cards = new ArrayList<>(cards);
validate(this.cards);
```

하지만 `copyDeck`이라는 참조변수를 추가적으로 할당한 이유는 다른 도메인 객체와의 통일성 때문이었습니다.

예를들어 원시값을 필드로 가지는 `Name`과 같은 객체는 검증을 먼저하고 필드에 할당하도록 구현하였는데,
이러한 객체와 통일성을 부여하기 위해 스택 영역에 참조 변수 하나를 할당하는 것은 비싼 비용이 아니라고 판단하였습니다.

혹시 웨지의 생각은 다르신지 궁금합니다!

2024-03-11 07:07 UTC, nak-honest commented on src/main/java/blackjack/domain/gamer/Players.java
> +			.distinct().count();
감사합니다!

리팩토링 시 반영하겠습니다.

2024-03-11 07:07 UTC, nak-honest commented on src/main/java/blackjack/domain/gamer/Players.java
> +		if (players.size() < MIN_SIZE || players.size() > MAX_SIZE) {
세밀한 꿀팁 감사합니다 ㅎㅎ

확실히 웨지가 제시해 준대로 방향이 일치하는 것이 더 쉽게 읽히는 것 같네요!
앞으로 코드를 작성할때 도움이 될것 같습니다.

감사합니다!!

2024-03-11 07:12 UTC, nak-honest commented on src/main/java/blackjack/domain/card/Deck.java
> +			throw new IllegalArgumentException("카드는 중복될 수 없습니다.");
`Deck` 생성자에 대한 리뷰에서 제가 통일성에 대한 이야기를 했는데,
정작 여기서는 통일성을 제대로 지키지 못했네요 ㅠ

상수화에 대한 것도 하나로 통일해 보겠습니다!
감사합니다 :)

2024-03-11 07:37 UTC, nak-honest commented on src/main/java/blackjack/domain/card/Card.java
> +public class Card {
이펙티브 자바를 통해 "toString을 항상 재정의하라" 라는 내용은 이미 인식하고 있었지만,
아직 로깅이나 디버깅을 제대로 경험해본적이 없어서 나중에 필요성을 느끼면 재정의 하자라는 안일한 마음을 가지고 있었습니다..!

하지만 이를 미리 습관으로 만드는 것은 전혀 다른 문제겠네요!
뿐만아니라 리뷰어나 다른 팀원이 디버깅을 하고자 할 때 더 편한 환경을 제공해 줄 수 있겠네요!

가지면 좋을 습관을 알려주셔서 감사합니다!
앞으로 저의 습관으로 만들어 보도록 하겠습니다😀

2024-03-11 07:59 UTC, nak-honest commented on src/main/java/blackjack/view/OutputView.java
> +		Card dealerInitCard = dealer.getCardHand().get(0);
디미터 법칙에도 어긋나는 코드인 것 같네요!

리팩토링 하면서 직접 객체에게 물어보는 방식을 택해보겠습니다!
감사합니다!

2024-03-11 08:09 UTC, nak-honest commented on src/main/java/blackjack/view/OutputView.java
> +			String.format("딜러: %d승 %d패", dealerResult.get(GameResult.WIN), dealerResult.get(GameResult.LOSE)));
허걱 ㅠㅠ
다른 도메인 객체는 엣지 케이스에 대해 테스트 코드를 작성했지만,
딜러의 결과는 Map으로 관리했기 때문에 테스트 코드를 작성하지 않아서 캐치하기 어려웠던 부분인 것 같네요!

단순히 꼼꼼하지 못해서 발생한 버그라고 볼수도 있지만, 도메인 객체로 만들지 않아 더 꼼꼼한 테스트가 어려웠다로 받아들여도 좋을 것 같습니다 :)

좋은 리뷰 감사합니다!!

2024-03-11 08:31 UTC, nak-honest commented on src/main/java/blackjack/domain/GameResult.java
> +		if (this.equals(GameResult.WIN)) {
확실히 웨지가 제시해준 대로 `GameResult.`을 빼는 것이 더 쉽게 읽히는 것 같아요!

조금이라도 더 읽기 쉬운 코드를 만들어 보도록 계속 노력해보겠습니다 :)
감사합니다 웨지!!

2024-03-11 08:32 UTC, nak-honest commented on docs/README.md
> +## 블랙잭 기능 구현 문서 🔥
미션 마감 직전에 급하게 하다보니,,
컨벤션에도 없는 걸 썼네요 ㅠㅠ

앞으로 더 신경쓰도록 하겠습니다!
좋은 지적 감사합니다!

2024-03-11 08:33 UTC, nak-honest commented on docs/README.md
> +## 블랙잭 기능 구현 문서 🔥
미션 마감 직전에 급하게 하다보니,,
컨벤션에도 없는 걸 썼네요 ㅠㅠ

꼼꼼하게 봐주셔서 감사합니다!!

2024-03-11 08:34 UTC, nak-honest commented on docs/README.md
> +            - [x] 딜러만 버스트 되거나, 딜러보다 점수가 높으면 플레이어의 '승'
각각을 분리해주면 좀더 빠르게 기능을 파악하기 좋을 것 같네요!
문서 또한 읽기 좋게 만들기 위해 더 고민하고 노력해야겠습니다 ㅎㅎ

감사합니다!!!

2024-03-11 08:37 UTC, nak-honest commented on src/main/java/blackjack/BlackjackController.java
> +		dealer.receiveInitCards(dealer.dealInit());
N개의 컨트롤러가 존재할 수 있다는 관점을 한번도 생각해본적이 없는데,
앞으로 컨트롤러를 구현할때 좋은 기준이 될 수 있는 관점이 될 것 같습니다!!

컨트롤러가 도메인 로직을 수행하지 않도록 리팩토링 하겠습니다 :)

2024-03-11 08:42 UTC, nak-honest commented on src/main/java/blackjack/BlackjackController.java
> +		while (!player.isBust() && isPlayerInputHit(player)) {
동의하는 부분입니다!

말씀하신대로 컨트롤러가 도메인 로직을 수행하면 도메인 규칙의 변경이 컨트롤러에 그대로 전파가 되기 때문에,
도메인으로 옮기도록 리팩토링 하도록 하겠습니다.

2024-03-11 08:44 UTC, nak-honest commented on src/main/java/blackjack/BlackjackController.java
> +		return inputView.readHitOrStand(player).equals("y");
말씀하신대로 true에 해당되는 것이 "y" 인지, "yes"인지 등은 뷰 로직이겠네요!
뷰에서 직접 boolean을 반환하도록 리팩토링 하겠습니다.
감사합니다!!

2024-03-12 10:04 UTC, nak-honest commented on src/main/java/blackjack/BlackjackController.java
> +public class BlackjackController {
음.. 솔직하게 말씀드리면 이유를 잘 모르겠습니다 ㅠ

평소에는 컨트롤러도 패키지를 분리시키는데, 단순 누락이지 않을까... 싶어요.
리팩토링 시 반영하겠습니다!

2024-03-12 10:10 UTC, nak-honest commented on src/main/java/blackjack/domain/GameResult.java
> +public enum GameResult {
gamer는 게임에 참여하는 사람들에 대한 객체들을 모아 놓는 곳이라 생각했고
`GameResult`는 참여하는 사람들이 아닌, 그 사람들이 가지게 되는 결과라고 생각해서 따로 두어야 한다고 생각했습니다!

`GameResult`를 아예 따로 result 와 같은 패키지에 두는 것은 어떻게 생각하시는지 궁금합니다!

2024-03-13 00:16 UTC, her0807 commented on src/main/java/blackjack/domain/GameResult.java
> +public enum GameResult {
ㅋㅋㅋㅋㅋ ` 이친구 도메인 패키지에서 왕따 당하고 있나요?` 웨지 표현이 너무 웃겨요

2024-03-13 02:25 UTC, nak-honest commented
안녕하세요 웨지!!

먼저 말씀하신대로 Pn 리뷰룰은 리뷰어의 입장을 충분히 고려하지 못한 요청이었던 것 같아요..!
저는 전체적으로 보았을때 커뮤니케이션 비용이 줄어들어 저 뿐만 아니라 리뷰어도 더 적은 비용이 들지 않을까 생각했었는데,
리뷰 하나하나에 대해 Pn 리뷰룰을 적용하는 것이 더 비생산적일 것이라고 깊이 생각하지 못했습니다.

웨지는 괜찮다고 말씀하셨지만, 사과의 말씀 전해드리고 싶어요!

그리고 리뷰어의 입장 또한 알려주셔서 감사합니다!
말씀해주지 않으셨다면 이후 제가 다른 리뷰어 분께 불쾌감을 줄수도 있었을텐데,
웨지 덕분에 지금 단계에서 미리 알 수 있었습니다 :)
<br>

또한 상세한 피드백도 너무 감사드립니다!
많은 고민과 학습을 할 수 있었습니다 ㅎㅎ

감사합니다!!

2024-03-13 22:23 UTC, sihyung92 commented on src/main/java/blackjack/domain/card/Deck.java
> +		validate(copyDeck);
복사 뒤 검증의 유효성에 대해 공감합니다 ^_^ 배워가요

2024-03-13 22:25 UTC, sihyung92 commented on src/main/java/blackjack/BlackjackController.java
> +		dealer.receiveInitCards(dealer.dealInit());
MVC가 뷰가 플러그인으로 여러벌 들어올 수 있는 패턴임을 고려해보면, 뷰를 도메인으로 넘겨주는 컨트롤러도 N벌 생성될 개연성이 있다고 생각해요~~

2024-03-13 22:27 UTC, sihyung92 commented on src/main/java/blackjack/domain/card/Card.java
> +public class Card {
넵 느낄 일이 거의 없다가 한번씩 로그에 해쉬 찍혀있으면 머리를 짚습니다 ㅋ ㅋ
이거 때문에 핫픽스 운영배포 하기도 참 그렇고요

2024-03-13 23:03 UTC, sihyung92 commented on src/main/java/blackjack/domain/game/BlackjackGame.java
> +    }
코멘트 달아주신 부분 확인했습니다 🙆‍♂️ 요건 제가 리뷰를 잘못 드린거 같아요 ㅎ 읽어보시면서 생각 정리해보셔요

말씀해주신 것과 level 1 미션들은 유저의 입력을 처리하는 동안 blocking 해야 하는 문제가 있기 때문에, while / for 등의 핵심 제어로직들이 controller에서 수행하는 게 강요됩니다.

이것을 도메인에서 하는 방법도 있습니다. view에서 구현해야 할 인터페이스를 도메인 패키지에서 정의해주고, 구현체는 view에서 만들어 주입해주면 가능합니다 ㅎ 그럼 미래에 어떤 view가 들어와도 인터페이스만 지켜준다면 이 도메인 로직은 잘 동작할 것입니다.

지금처럼 Supplier를 받아보시는 게 그런 방향입니다. 이걸 단순히 hit 받는 것에만 적용하지 않고 모든 InputView에 대해 구현하면 (즉 inputView 메서드들을 interface화 하면) 반복문과 제어문을 모두 도메인으로 가져올 수 있습니다.

하지만 **권장드리지는 않는데요**, 
인터페이스화 자체가 복잡성을 증대시키는 일인데 저희 미션이 그정도로 보호받아야하는 도메인 모델을 추구할 필요가 없기 때문입니다. (이건 사람마다 의견이 다를겁니다)
그리고 미션에서 학습해야 될 내용들로 가득한데 아키텍처 적인 부분에 매몰되느라 다른 중요한 내용들을 놓칠 수 있어 권하지 않습니다. 
"도메인 모델은 순수해야한다"는 주장은 강력해서 반박하기 힘들고, "복잡하니까"는 "어려우니까"로 오해할 수 있어 개발토론에서 이기기 어렵습니다. 그러면 너도나도 도메인에 유저 I/O 인터페이스를 깔기 시작할텐데 이건 우테코에 독을 푸는 짓이라고 생각합니다 (좋대서 하는데 해보면서 왜 좋은지는 잘 모르겠는 나쁜 상황)

어쨌든.. 낙낙은 스스로의 고민 끝에 interface를 제공하는 방향으로 발전하셨으니, 리뷰를 드리자면 BooleanSupplier라는 타입핑이 가독성을 많이 떨어뜨립니다. 도메인 패키지에 이런 BooleanSupplier와 유사한 함수를 하나 추가합니다.

```java
    @FunctionalInterface
    public interface PlayerHitInput {

        boolean isHit();
    }
```
그리고 해당 코드에선 아래처럼 사용합니다.
```suggestion
    public boolean isHit(Player player, PlayerHitInput input) {
        return !player.isBust() && input.isHit();
    }
```
controller에선 람다로 처리하지만, 람다는 익명클래스 구현과 개념이 비슷합니다. 도메인 패키지에서 정의하고, controller에서 구현체를 만들어 주입한 경우가 됩니다. 
다른 컨트롤러에서도 비슷한 방식으로 쉽게 확장될 수 있습니다.

2024-03-13 23:12 UTC, sihyung92 commented on src/main/java/blackjack/domain/game/BlackjackGame.java
> +    }
직전 리뷰를 반영하면 이 메서드 분리도 필요없어질거라 예상합니다.

2024-03-13 23:16 UTC, sihyung92 commented on src/main/java/blackjack/domain/GameResult.java
> +public enum GameResult {
result 패키지도 괜찮은거 같아요 ㅎ root에 있으니까 동일한 depth에 있는 패키지를 포괄하는 개념으로 느껴져서요 (패키지들과 동일한 depth에 있는 객체가 다른 패키지들의 상위개념이라는 리뷰는 아닙니다 요번 케이스에 한해서 어색하게 느껴졌어요)

2024-03-13 23:27 UTC, merged

2024-03-14 02:06 UTC, nak-honest commented on src/main/java/blackjack/domain/result/GameResult.java
> +		if (player.isBust() || (!dealer.isBust() && player.getScore() <= dealer.getScore())) {
확실히 제시해주신 코드가 훨씬 가독성이 좋아보이네요!!
리팩토링 때 반영해보겠습니다 :)

2024-03-14 02:06 UTC, nak-honest commented on src/main/java/blackjack/domain/result/GameResult.java
> +	public static GameResult of(Dealer dealer, Player player) {
넵!!
메서드 이름을 통해 좀더 의도가 드러나도록 변경해보겠습니다!

2024-03-14 02:16 UTC, nak-honest commented on src/main/java/blackjack/domain/game/BlackjackGame.java
> +    }
확실히 표준 함수형 인터페이스 말고, 직접 정의를 해주는 것이 가독성 측면에서 훨씬 좋은 느낌이 드네요!!

하지만 말씀해 주신대로 저도 이로 인해 증가하는 복잡성에 비해 얻는 이득이 크지 않다고 판단되는 것 같아요 ㅎㅎ

리팩토링 시 다시 컨트롤러로 이동 시켜 보겠습니다!
상세한 답변, 그리고 다양한 관점에서 설명해 주셔서 감사합니다!!