[1단계 - 블랙잭 게임 실행] 리니(이예린) 미션 제출합니다.
woowacourse/java-blackjack pull request #665
Opened 2024-03-08 08:57 UTC by linirini

안녕하세요, 리니입니다.🖐️

이번 과제에서 어렵다고 느끼는 부분이 많았다 보니 아직은 리팩토링이 부족한 상태로 리뷰 요청을 하게 되었습니다. 리뷰하시는 와중에도 제가 리팩토링하느라 계속 커밋할 수도 있을 것 같아서 미리 말씀드려요!

앞으로 2주 간 리뷰 잘 부탁드립니다, 안돌:)

2024-03-08 14:00 UTC, andole98 requested changes
안녕하세요 리뷰어 안돌입니다.

도메인용어를 잘 사용하신 점, 설계의도를 잘 표현하신 점이 매우 좋습니다.

`handOut`(감동), `draw`, `hit`, `stay` 등 적절하게 잘 사용하셨어요 :+1:

코멘트 살펴봐주시고 궁금하거나 이해되지 않는다면 dm or 코멘트 남겨주세요.

2024-03-08 14:00 UTC, andole98 commented on src/main/java/domain/BlackJackGame.java
> +    private void drawTwoCardsForGamer(final Gamer gamer) {
메서드 순서도 컨벤션입니다. public > private 순으로 메서드를 기술하세요.

2024-03-08 14:00 UTC, andole98 commented on src/main/java/domain/BlackJackGame.java
> +    public boolean succeededGiving(final Gamer gamer) {
boolean을 리턴하는건 바깥의 while문 때문일것 같아요. 실제로 동작하는건 게이머의 턴을 진행하는것 같아요. 

succeededGiving은 실제 동작보다는 boolean에 집중한 듯한 느낌이 듭니다.
takeTurn 정도가 어떠한지..?

또는 제어구조를 바꿔볼수도 있겠네요.

2024-03-08 14:00 UTC, andole98 commented on src/main/java/domain/card/Rank.java
> +        return name().contains("ACE");
이렇게 하는게 낫겠네요

```java
return this == SMALL_ACE || this == BIG_ACE;
```

2024-03-08 14:00 UTC, andole98 commented on src/main/java/domain/gamer/Hand.java
> +    private static int accumulateScore(final Card card, final int sum) {
실제로 accumulate하는게 아닌것 같아요. ace카드에 대해서 가장 유리한 점수를 선택하고 더하고 있네요.

ace카드에 대해서 유리한 점수를 선택

더하기

를 분리해보면 더 좋은 이름이 나오고 가독성이 좋아질것 같아요.

2024-03-08 14:00 UTC, andole98 commented on src/main/java/domain/Decks.java
> +    public static Decks createByStrategy(final DecksGenerator decksGenerator) {
이건 상호참조인것 같아요. DecksGenerator가 Decks를 알고 있는데, Decks도 DecksGenerator에 의존하고 있네요

2024-03-08 14:00 UTC, andole98 commented on src/main/java/domain/Decks.java
> +    public Card draw() {
이름이 정말 맘에 듭니다

2024-03-08 14:00 UTC, andole98 commented on src/main/java/domain/strategy/ShuffledDecksGenerator.java
> +package domain.strategy;
`strategy` 패키지의 정체가 궁금합니다.

~Strategy가 생긴다면 이 패키지에 다 넣으실 건가요? 패키지는 종류별 묶음인가요?

2024-03-08 14:00 UTC, andole98 commented on src/main/java/view/InputView.java
> +
:+1:

2024-03-08 14:00 UTC, andole98 commented on src/main/java/domain/Decks.java
> +        return cards.pop();
혹시 cards가 비게 되면 어떻게 되나요? 딜러 / 참가자 1000명 인 경우?

2024-03-08 14:00 UTC, andole98 commented on src/main/java/domain/Gamers.java
> +        this.gamers = List.copyOf(gamers);
`copyOf`는 왜 필요한건가요?

2024-03-08 14:00 UTC, andole98 commented on src/main/java/domain/Gamers.java
> +    public static Gamers of(final Players players, final Dealer dealer) {
왜 static factory를 사용하셨나요? 이름이 필요한가요? 그렇다기엔 `of`라는 이름은 무엇을 설명하고 있나요?

2024-03-08 14:00 UTC, andole98 commented on src/main/java/domain/Gamers.java
> +                .filter(gamer -> gamer instanceof Player)
instanceOf 키워드 없이 만들려면 어떻게 해야 할까요?

이미 이 객체를 생성할 때는 Dealer와 Player가 구분되어 있지 않나요?

2024-03-08 14:00 UTC, andole98 commented on src/main/java/domain/Gamers.java
> +        return (Dealer) gamers.stream()
instanceOf와 같음

2024-03-08 14:00 UTC, andole98 commented on src/main/java/view/OutputView.java
> +        String message = String.format("딜러: %d승 %d패 %d무", loseCount, winCount, tieCount);
승패무를 출력하는데 lose win tie 를 넣어주네요.

findWin/Lose/Tie 에 뭔가 문제가 있는것 같아요. 

승패무를 알려면 두 대상이 필요한것 같아요. 누가 누구를 이겼는지, 누가 누구에게 졌는지.

PlayerResults는 플레이어들의 승패무를 미리 계산해서 넘겨주므로 딜러입장에선 반대가 되네요. 

만약 승패무가 아니라 score와 같은 비교대상이 필요 없는 정보가 있다면, 필요한 부분에서 적당히 가져다 쓸수 있을것 같아요.

또는 딜러를 위한 메서드 / 플레이어를 위한 메서드 

또는 딜러를 위한 객체 / 플레이어를 위한 객체

2024-03-08 14:00 UTC, andole98 commented on src/main/java/domain/gamer/Gamer.java
> +    public abstract boolean isStay();
```suggestion
    public abstract boolean shouldStay();
```

2024-03-10 08:02 UTC, linirini commented on src/main/java/controller/BlackJackController.java
> +
게임 전체 실행 흐름을 포함하고 있는 만큼 `start`이라는 네이밍은 좀 아쉬운 것 같아서, `play`라고 바꿔보았어요!

2024-03-10 09:50 UTC, linirini commented on src/main/java/domain/BlackJackGame.java
> +    private void drawTwoCardsForGamer(final Gamer gamer) {
`prepareCards` 내부에서 호출하는 private 메서드이기 때문에 해당 메서드 하위에 `drawTwoCardsForGamer`를 위치시켰는데요, 혹시 안돌은 어떤 방식을 선호하시나요?

+ 초기에 카드를 배분해주는 것은 hit이 의미하는 바와는 거리가 멀어서'receiveInitialCards'이라는 메서드로 분리해봤습니다!

2024-03-10 09:53 UTC, linirini commented on src/main/java/domain/BlackJackGame.java
> +    public boolean succeededGiving(final Gamer gamer) {
해당 메서드 내에서 `stay`가 아니라면 카드를 뽑고, `카드를 뽑는 것에 대한 성공 여부`를 반환하고 있다 보니, 페어와도 메서드명을 동작 혹은 boolean 중 어느 것에 집중해야 할지 많이 고민했던 것 같아요!

2024-03-10 10:13 UTC, linirini commented on src/main/java/domain/gamer/Gamer.java
> +        return hand.sum() == 21 && hand.getCards().size() == 2;
magic number를 또 놓쳤네요😭
isBust처럼 hand가 판단할 수 있도록 분리하는 게 좋아보이네요! 리팩토링 해보겠습니다:)

2024-03-10 10:17 UTC, linirini commented on src/main/java/domain/gamer/Gamer.java
> +    public abstract boolean isStay();
게이머의 선택으로 인한 stay가 아닌 더 이상 카드를 뽑을 수 없는 조건으로 인해 `stay` 당하는 것이기 때문에 `shouldStay`가 훨씬 가독성이 좋아보이네요! 좋은 네이밍 추천 감사합니다👍

2024-03-10 10:27 UTC, linirini commented on src/main/java/domain/gamer/Name.java
> +    public static final String INVALID_NAME_LENGTH = String.format("이름은 %d글자 이상, %d글자 이하 이어야 합니다.", MINIMUM_NAME_LENGTH,
현재는 최대/최소 이름 길이에 대한 상수는 `Name` 내에서만 사용하고 있기 때문에 접근 제어자를 private으로 막아두었는데요, `MINIMUM_NAME_LENGTH`와 `MAXIMUM_NAME_LENGTH`를 사용해서 메세지 내용을 구성하기 위해 이와 같은 순서로 작성했습니다!
예외 메세지를 직접 호출하는 곳이 test에서 밖에 없어서 그렇다면 private으로 접근 제어자를 변경해도 되겠다고 판단하여 예외 메세지의 접근 제어자를 private으로 수정해봤습니다.

2024-03-10 10:35 UTC, linirini commented on src/main/java/domain/gamer/Hand.java
> +    private static int accumulateScore(final Card card, final int sum) {
불필요한 `static` 제거하고, 메서드 순서도 컨벤션에 맞게 조정하겠습니다.
ace 카드에 유리한 점수를 선택하는 것은 Rank의 책임으로 분리하고 더하는 작업만 집중할 수 있도록 분리해보겠습니다!

2024-03-10 11:29 UTC, linirini commented on src/main/java/domain/Gamers.java
> +        this.gamers = List.copyOf(gamers);
방어적 복사와 불변 리스트로 생성하고자 `copyOf`를 사용했습니다.

2024-03-10 11:31 UTC, linirini commented on src/main/java/domain/Decks.java
> +        return cards.pop();
참가자의 제한을 2명에서 8명으로 제한하고, 더 이상 카드를 뽑을 수 없는 조건에 도달하면 카드를 뽑지 못하도록 했기 때문에 cards가 비는 경우를 처리할 필요가 없다고 생각했습니다.
하지만, 모든 개발자가 제 의도대로 사용해주길 기대할 수는 없으니 이에 대한 예외 처리도 필요할 것 같네요!

2024-03-10 12:05 UTC, linirini commented on src/main/java/domain/Gamers.java
> +    public static Gamers of(final Players players, final Dealer dealer) {
`gamers`는 `players`와 `dealers`로 이루어져 있음을 명시적으로 나타내고 싶었습니다. 그래서 정적 팩터리 메서드 형태로 생성하였습니다.


하지만 아래 질문들
- instanceOf 키워드 없이 만들려면 어떻게 해야 할까요?
- 이미 이 객체를 생성할 때는 Dealer와 Player가 구분되어 있지 않나요?
을 읽고 `players와 dealers를 하나의 일급 컬렉션으로 관리해야 하는 이유가 있을까` 고민하게 되었습니다.

실제로 `Gamers`에서는 players와 dealer를 하나의 컬렉션으로 만들고, 둘을 구분해서 찾아오는 메서드만 존재한다면 Gamers로 묶어서 관리할 필요는 없다는 결론을 내렸습니다.

2024-03-10 12:05 UTC, linirini commented on src/main/java/domain/Gamers.java
> +                .filter(gamer -> gamer instanceof Player)
위의 질문에서 함께 답을 달았습니다:)

2024-03-10 12:05 UTC, linirini commented on src/main/java/domain/Gamers.java
> +        return (Dealer) gamers.stream()
위의 질문에서 함께 답변 드렸어요!

2024-03-10 12:24 UTC, linirini commented on src/main/java/domain/strategy/ShuffledDecksGenerator.java
> +package domain.strategy;
strategy 패키지는 전략을 관리하기 위해 생성했는데요, Strategy가 더 생긴다면 같은 패키지 내에서 관리할 예정입니다, 만약 현재는`Decks` 관련된 전략만 존재하지만, 다른 도메인 관련 전략이 생긴다면 `strategy > domain명` 방식으로 관리할 것 같습니다.

이 부분에 대해서는 안돌에게 질문이 있는데요!
지금까지는 MVC 형식의 패키지로만 분리를 해왔었습니다! 
이번 과제에서는 도메인의 개수가 많아져서 관련 도메인들끼리 패키지를 분리하여 `card`, `gamer` 패키지를 만들었는데요!
저도 제가 `패키지를 분리하는 기준`에 대해 모호함을 느꼈습니다. `strategy`도 마찬가지로, `strategy`를 분리하긴 했지만, strategy의 인터페이스도 이 안에서 함께 관리해야 하는지 모르겠더라고요!
안돌은 패키지를 분리할 때 어떤 기준을 가지고 분리하시나요?

2024-03-10 13:05 UTC, linirini commented on src/main/java/view/OutputView.java
> +        String message = String.format("딜러: %d승 %d패 %d무", loseCount, winCount, tieCount);
Players의 결과를 관리하고 있으니, Dealer의 결과는 따로 관리할 필요가 없다고 생각했는데, 생각이 짧았던 것 같아요!
딜러와 플레이어 모두 결과를 객체로 관리하는 방향으로 리팩토링 해보겠습니다.

2024-03-10 13:47 UTC, andole98 commented on src/main/java/domain/BlackJackGame.java
> +    private void drawTwoCardsForGamer(final Gamer gamer) {
> 초기에 카드를 배분해주는 것은 hit이 의미하는 바와는 거리가 멀어서 receive이라는 메서드로 분리해봤습니다!

이건 무슨뜻인지(왜 이 말이 여기에서 나오는지) 모르겠어요.

제 선호는 `객체에는 public method 단 하나` 만 둡니다. 그리고 private 메서드가 2개 이상이면 문제가 있다고 느낍니다.

2024-03-10 13:49 UTC, andole98 commented on src/main/java/domain/Gamers.java
> +    public static Gamers of(final Players players, final Dealer dealer) {
> gamers는 players와 dealers로 이루어져 있음을 명시적으로 나타내고 싶었습니다

생성자로는 안되나요?

2024-03-10 13:51 UTC, andole98 commented on src/main/java/domain/gamer/Name.java
> +    public static final String INVALID_NAME_LENGTH = String.format("이름은 %d글자 이상, %d글자 이하 이어야 합니다.", MINIMUM_NAME_LENGTH,
전 컨벤션에 대한 얘기를 했어요. public x private o 가 아니라 public 변수를 가장 위로 올려주세요.

2024-03-10 13:54 UTC, andole98 commented on src/main/java/domain/strategy/ShuffledDecksGenerator.java
> +package domain.strategy;
패키지에 관해 스스로 좀더 고민하고 깨달았으면 합니다.

얘기한대로 간단한 시나리오 (~~가 생긴다면/~~변경된다면)에 관한 객체 이름과 패키지를 만들고(메서드구현x) `import` 문 을 관찰해 보세요.

2024-03-11 07:18 UTC, linirini commented on src/main/java/domain/Deck.java
> +public class Deck {
> Deck 과 Decks는 무슨 차이가 있을까요? Deck은 어떻게 사용되고 있나요?

2024-03-11 07:32 UTC, linirini commented on src/main/java/domain/Deck.java
> +public class Deck {
> Deck 과 Decks는 무슨 차이가 있을까요? Deck은 어떻게 사용되고 있나요?
 의도한 바는 52장의 카드 한 세트를 `Deck`이라고 할 때, 6벌의 덱을 섞어서 312장을 기준으로 게임을 플레이한다는 의미에서 `Decks`라고 명명했습니다. 
> Decks generator인데 Stack<Card> 를 만드는군요?
위의 답변에 이어서 말씀드리자면, 다른 크루들에게도 물어봤는데 `Decks`는 `Deck`을 타입으로 가지는 컬렉션을 관리하는 일급 컬렉션처럼 보인다고 답했고, 의도한 바를 설명하는데 불필요한 비용이 발생함을 느꼈습니다.
적절하지 못한 네이밍과 타입을 사용하고 있다고 판단했고 `312장(6벌의 카드팩)을 Deck`으로 사용하는 방향으로 리팩토링 했습니다.

2024-03-11 07:34 UTC, linirini commented on src/main/java/domain/DecksGenerator.java
> +    Stack<Card> generate();
[아래의 코멘트](https://github.com/woowacourse/java-blackjack/pull/665#discussion_r1519254514)에서 함께 답변 드렸습니다:)

2024-03-11 07:34 UTC, linirini commented on src/main/java/domain/Decks.java
> +    public static Decks createByStrategy(final DecksGenerator decksGenerator) {
- 상호참조는 왜 문제가 될까요?
  - 상호 참조는 변경이 전파된다는 문제점을 가집니다. 이는 개발과 유지보수에 불필요한 비용 소모를 유발하고, 예상치 못한 문제점을 만들어 내기 쉽습니다. 따라서 상호참조가 발생하지 않도록 의존성을 역전시키거나 우회시켜서 연결을 끊어줘야 합니다.
다만, 위의 코드에서는 `DecksGenerator`는 `Deck`을 알고, `Decks`가 `DecksGenerator`를 알고 있기 때문에 어떤 부분이 상호참조인지 잘 모르겠습니다. 안돌이 말한 상호참조가 어떤 부분인지 설명 부탁드려도 될까요?

- 리팩토링 방향은 [위 코멘트](https://github.com/woowacourse/java-blackjack/pull/665#discussion_r1519254514)에서 말씀드렸습니다.

2024-03-11 07:49 UTC, linirini commented on src/main/java/domain/strategy/ShuffledDecksGenerator.java
> +package domain.strategy;
`import 문 을 관찰해 보세요.`
-> 좋은 인사이트 감사합니다 👍👍

이전 코멘트에서 `다른 도메인 관련 전략이 생긴다면 strategy > domain명 방식으로 관리할 것 같습니다.`와 같이 말씀 드렸었는데요, 
import문을 관찰해보면서 제가 말한 시나리오대로면 `domain.strategy.deck`인데, 부자연스러움을 느꼈습니다. 
또한, 변경이 발생했을 때, deck 패키지와 strategy 패키지에 분산되어 있게 되기 때문에 적합하지 않다고 판단했습니다.

이보다는 어떤 `domain명`의 `strategy`이다라고 읽히는 것이 자연스럽고, 변경이 발생했을 때에도 한 패키지에 모여있기 때문에 `domain > deck > strategy`와 같은 방식으로 패키지를 분리했습니다.

2024-03-12 02:42 UTC, linirini commented on src/main/java/view/OutputView.java
> +        String message = String.format("딜러: %d승 %d패 %d무", loseCount, winCount, tieCount);
딜러의 승패무를 저장하는 `DealerResult`와, 플레이어의 결과를 저장하는 `PlayerResults`가 존재하고, `Judement`에서 정적 팩토리 메서드로 `Players`와 `Dealers`를 이용하여 결과를 판별해서 저장하도록 구현했습니다.

`Judement`에서는 `DealerResult`와 `PlayerResults`를 필드로 가지며, 딜러를 기준으로 승패무를 판단하여 결과를 저장하고 있습니다.

2024-03-12 02:43 UTC, linirini commented on src/main/java/domain/BlackJackGame.java
> +    private Result isPlayerWin(final Dealer dealer, final Player player) {
최종 판단 결과를 저장하는 `Judement` 도메인을 생성하여 이 도메인이 결과 판단 책임을 가지도록 구현했습니다.
내부 로직에 대한 설명은 [아래 코멘트](https://github.com/woowacourse/java-blackjack/pull/665#discussion_r1520761190)에 작성하였습니다!

2024-03-12 04:27 UTC, linirini commented on src/main/java/domain/Gamers.java
> +    public static Gamers of(final Players players, final Dealer dealer) {
players와 dealers를 생성자의 필드로 받는다면 해당 도메인은 필드로 `players`와 `dealers`를 들고 있다고 받아들일 수도 있다고 생각했습니다. 그래서 정적 팩터리 메서드로 필드로 해당 값들을 들고 있는 것이 아니라는 것을 드러내고자 했었습니다!

2024-03-12 11:47 UTC, andole98 commented on src/main/java/domain/Gamers.java
> +    public static Gamers of(final Players players, final Dealer dealer) {
> players와 dealers를 생성자의 필드로 받는다면 해당 도메인은 필드로 players와 dealers를 들고 있다고 받아들일 수도 있다

리니는 필드 접근제어자를 무엇으로 설정하고 있나요? `private final` 아닌가요? 왜 그렇게 하나요? 필드를 알려주고 싶으면 public으로 하면 안되나요? 객체는 자신의 필드와 구현을 드러내고 싶어하나요?

2024-03-12 12:02 UTC, andole98 commented on src/main/java/domain/Deck.java
> +public class Deck {
리니의 대답을 듣고도 여전히 이게 궁금하네요

> Deck~~s~~ generator인데 Stack 를 만드는군요?

2024-03-12 12:13 UTC, andole98 commented on src/main/java/domain/strategy/ShuffledDecksGenerator.java
> +package domain.strategy;
제가 기대한 것과는 많이 다릅니다. 앞으로 미션 등 코딩할때 한번쯤 `패키지는 어떻게 나누면 좋을까?` 를 생각해보면 될것 같아요.

2024-03-12 15:10 UTC, andole98 reviewed
변경분에 대해서는 크게 이야기할 내용이 없네요.

제가 남긴 코멘트에 대한 방향이 결정되지 않아서 그런것 같아요.

저도 답글 남겨두었으니 살펴봐주세요. 반영할 필요 없다 느끼신다면 머지하도록 하겠습니다. 댓글남겨주세요.

2024-03-12 15:10 UTC, andole98 commented on src/main/java/view/RankView.java
> +    public static String findName(final Rank rank) {
이게 잘 동작하려면 Rank의 element name과 반드시 동일해야 하겠네요. 중요한 제약조건인데 테스트가 가능한가요?

(이런일은 거의 없겠지만..) 카드(rank)에 조커가 추가되었어요. Rank에만 추가하고 RankView에 추가하지 않으면 어떻게 되나요?

2024-03-12 15:10 UTC, andole98 commented on src/main/java/view/RankView.java
> +public enum RankView {
주요 도메인에 대한 view mapping을 분리하셨군요. 좋은 시도인것 같아요.

그렇지만 직접적인 in/out을 담당하는건 아니고 또 중요한 로직이므로 테스트가 있으면 좋겠네요

2024-03-12 15:10 UTC, andole98 commented on src/main/java/domain/Judgement.java
> +public class Judgement {
이 클래스에 대한 리니의 생각이 궁금해요.

결과계산 등을 담당하는걸로 보이는데, getter를 제외하고는 모두 static이네요.

이친구는 `객체` 인가요?

2024-03-12 15:33 UTC, andole98 commented on src/main/java/domain/Gamers.java
> +    public static Gamers of(final Players players, final Dealer dealer) {
static factory를 쓰지 말라는 코멘트를 레벨1부터 계속해서 남기는 이유는 그 폐해를 너무나 고통스럽게 받았기 때문입니다.

static factory에서 로직을 작성할 수 있으니깐 객체와 필드는 잊어버립니다. 역할분리가 필요한데도 static factory 는 그것을 감춰버립니다. static factory만의 문제는 아닐겁니다. 하지만 static factory는 객체, 필드, 생성자를 잊어버리게 하기 너무 쉽습니다.

지금 수준의 프로젝트에서는 1도 상관없을지 몰라요. 그러나 static factory를 왜 쓰는건지, 쓰라고 하니까 쓰는건지, 어떨때 좋은지, 다른 방법보다 더 좋은지, 정확하고 근거있는 그리고 실용성 있는 답을 제시할 수 없다면, 쓰지 않는걸 권장합니다.

static factory를 쓰고 싶은 욕구가 생긴다면 객체 역할과 필드를 살펴보세요. 타입이 달라져야 하는게 아닌지 검토해보세요.

2024-03-13 00:31 UTC, linirini commented on src/main/java/domain/BlackJackGame.java
> +    private void drawTwoCardsForGamer(final Gamer gamer) {
초기에 카드를 배분해주는 것은 hit이 의미하는 바와는 거리가 멀어서 receive이라는 메서드로 분리해봤습니다!
-> 페어의 리뷰를 보면서 리팩터링 한 부분인데, 혼란을 드린 것 같네요, 죄송합니다.😭

2024-03-13 04:51 UTC, linirini commented on src/main/java/domain/Deck.java
> +public class Deck {
질문의 의도를 제대로 파악하지 못했던 것 같아요🙊
`Deck`을 생성한다는 의미에서 `DeckGenerator`라 명명하고 반환형이 Stack인 점은 사용하는 개발자 입장에서 혼란을 준다는 부분을 놓쳤습니다. 앞으로, 해당 클래스를 사용하고자 하는 입장에서 무엇을 하는 객체인지 예측 가능한 이름을 짓도록 유의하겠습니다.

2024-03-14 01:50 UTC, linirini commented on src/main/java/domain/Judgement.java
> +public class Judgement {
playerResult와 dealerResult는 dto로서 사용된다고 판단했습니다. 따라서, Judgement의 필드로도 어울리지 않는다고 생각합니다.

따라서, Judgement 대신 `Referee`로 리팩터링 하여 승패무를 판단하는 유틸 클래스로서 변경하였고, playerResult와 dealerResult를 묶은 `totalResult`를 생성하여 view에서 사용할 수 있도록 리팩토링 하였습니다.

2024-03-14 06:46 UTC, andole98 commented on src/main/java/domain/Decks.java
> +    public static Decks createByStrategy(final DecksGenerator decksGenerator) {
오..... 하나만 말했는데 여럿을 깨달으신것 같아요 💯 

> 디자인 패턴을 적용할 때 그 목적을 분명히 하고 신중하게 사용

배우는 단계에서는 많이 시도해보고 적용해야 좋은것 같아요! 무엇이든 잘해야만 사용할수 있는건 아니니깐요.

저나 다른 사람이 이에 대해서 말하는건 "하지말라" 가 아니라 "이런이런점은 고려해보았니?" 정도로 이해하시면 좋을것 같아요.

2024-03-14 07:02 UTC, andole98 commented on src/main/java/domain/Gamers.java
> +    public static Gamers of(final Players players, final Dealer dealer) {
눈물없이 들을수 없는데 😢 간략히 얘기해드릴게요.

저는 결제회사 다녀요. 코드에 이런게 있었어요. `Payment.of()`. 아직까진 모두가 행복했어요.

온라인커머스가 급격히 성장하면서 이런저런 결제수단 / 방법들이 만들어졌어요. 토스페이(써주세요), 네이버페이, 해외결제, 페이팔, 보쿠, Grab ... 수십개의 방법들이 생겨났어요.

모두 payment로 분류하고 싶었나봐요. `Payment.fromTossPay()` 이런것들이 생기기 시작했어요. `of` 시절엔 금액만 있어도 되었는데, `fromTossPay`를 위해선 포인트도 필요해졌네요. Payment에 point 필드가 생기고, nullable이 되었습니다. `of`에서는 안 쓰이는 필드거든요.

이런 케이스가 30개 정도 된다고 생각해보세요. 🙈 결제수단이 추가될수록 Payment의 부담은 커지고 살펴봐야할 코드의 범위는 기하급수적으로 늘어납니다. 생산성이 떨어지고 버그날까 두렵고 extream한 성장을 포기하게 됩니다.

처음에 `of`나 `fromTossPay`같은게 없었다면, `TosspayPayment`, `NaverayPayment`, `PaypalPayment` 로 객체가 분리되었을지 몰라요. 생성자를 만들면서 필드가 이상함 or 기존 맥락에 맞지 않음이 정확히 보였을테니까요.

static factory로 생성을 제어할수 있다고 착각하기 시작하면서 Payment는 쓰레기통 / 짬통이 되었습니다. 결제회사에서 Payment는 어떤 존재인가요? 매~우 중요한데도 필드가 100여개.... 테스트가 있을리 없죠. (필드 100개짜리를 어떻게 만들어요)

다음에 기회되면 더 재밌는 얘기도 해드릴게요

2024-03-14 07:18 UTC, andole98 approved these changes
이번에도 잘 구현해 주셨네요 :+1:

시스템/객체 설계 경험이 조금은 있는것 같아 여러 코멘트들을 남겼었는데요, 어려웠을지... 무슨 이야기인지 의도가 전달되었는지 궁금하네요 :joy: 

어려울수도 있는 피드백 잘 이해하려 노력해주시고, 고민하고 생각을 말해주셔서 즐거웠던 것 같아요.

소소한 코멘트 남겼으나 다음 미션 진행하면서 참고만 해 주세요~

2024-03-14 07:18 UTC, andole98 commented on src/main/java/domain/Referee.java
> +    private Referee() {
private로 객체생성을 막아두셨군요. :+1:

2024-03-14 07:18 UTC, andole98 commented on src/main/java/domain/deck/Deck.java
> +import strategy.ShuffleStrategy;
이 import문 한번 관찰해 보세요.

2024-03-14 07:18 UTC, andole98 commented on src/main/java/domain/gamer/Dealer.java
> +public class Dealer extends Gamer {
더 심플해졌네요?? :+1:

2024-03-14 07:18 UTC, andole98 commented on src/main/java/strategy/ShuffleStrategy.java
> +    Stack<Card> shuffle(List<Card> cards);
이 시그니처는 이름과도 매우 잘 어울리네요. shuffle이면 순서가 있을것 같은데... 정렬은 어떻게 하지? 라는 의문이 바로 해결되네요.

2024-03-14 07:18 UTC, andole98 commented on src/test/java/view/RankViewTest.java
> +class RankViewTest {
:+1:

2024-03-14 07:18 UTC, merged