[2단계 - 블랙잭 베팅] 무빈(김현중) 미션 제출합니다.
woowacourse/java-blackjack pull request #678
Opened 2024-03-12 07:36 UTC by hjk0761

안녕하세요, 알렉스!
1단계를 마치고 2단계까지 구현해 본 무빈입니다!

1단계에서 추가로 주신 피드백을 반영하는 것을 우선으로 두고 2단계를 진행했습니다. 먼저 컨트롤러의 의미에 대해 생각해보면서, BlackJackGame 이라는, 블랙잭 게임을 주관하는 도메인을 분리하여 보았습니다(https://github.com/woowacourse/java-blackjack/pull/618#discussion_r1519325422 등). 또한 전체적으로 상수 관리에 미흡한 부분이 있어 전체적으로 수정하였습니다(https://github.com/woowacourse/java-blackjack/pull/618#discussion_r1518835809, https://github.com/woowacourse/java-blackjack/pull/618#discussion_r1518840644 등).

먼저, 1단계 추가 피드백 관련해서 궁금한 점이 생겨 질문 드립니다!
에러 메시지에 상수화된 부분을 출력해야 하는가, 그렇다면 어떻게 검증하는가(https://github.com/woowacourse/java-blackjack/pull/618#discussion_r1519174563)

스트림으로의 변환에 대한 궁금증(https://github.com/woowacourse/java-blackjack/pull/618#discussion_r1519176563)

또한 2단계를 진행하면서 생긴 질문이 있어 정리해보았습니다!

**1. 에이스 값 결정에 대한 질문**
 - 실제 블랙잭에선 11로 처리한 에이스를 가진 상태에서 버스트가 난 경우 11로 처리한 에이스를 1로 두고 다시 힛(카드를 뽑기) 할 수 있습니다. 지금 구현된 프로그램은 에이스의 값이 결정되면 이후에 바뀌지 않는데, 실제 존재하는 도메인이기에 이를 따라 구현하는 것이 맞을지 아니면 지금의 상태도 작은 블랙잭 게임으로 보고 추후에 확장하는 것이 옳을지 입니다.

**2. 딜러의 배팅 결과를 계산하는 로직에 대한 책임**
 - 현재 BettingResult 라는 플레이어에 따른 배팅 결과(int) 를 가지는 Map을 래핑한 클래스에서 이를 계산합니다. ' 플레이어의 총 수입의 합 + 딜러의 수익 = 0 ' 이라는 기준에서 이 계산에 대한 책임이 BettingResult에 있다고 생각했지만, 무언가 마음에 들지 않는데 이유를 모르겠습니다. 이를 포함해 배팅 관련 기능들에 대한 책임들이 적절히 분배되지 않았다는 기분이 드는데, 어떻게 생각하시는지 궁금합니다!

**3. 상태 패턴의 적용에 대한 고민**
 - 현재 플레이어의 승리 / 플레이어의 블랙잭으로 인한 승리 / 플레이어 패배 이렇게 세 상태를 enum으로 관리하고 있습니다. 오늘 블랙잭 피드백 첫 번째 수업에서 네오께서 state 패턴을 사용하셨는데, 이와 같은 부분에 해당 패턴을 적용하는게 옳은 선택인지 궁금합니다.

이외에도 부족한 부분이 많이 있을 것 같습니다. 부족한 코드 봐주셔서 감사드립니다!

2024-03-13 13:07 UTC, yxxnghwan requested changes
안녕하세요 무빈 2단계 빠르게 구현해주셨네요.🙂
코멘트 남겼으니 확인 부탁드려요.

## 질문 답변

> 1. 에이스 값 결정에 대한 질문
> 실제 블랙잭에선 11로 처리한 에이스를 가진 상태에서 버스트가 난 경우 11로 처리한 에이스를 1로 두고 다시 힛(카드를 뽑기) 할 수 있습니다. 지금 구현된 프로그램은 에이스의 값이 결정되면 이후에 바뀌지 않는데, 실제 존재하는 도메인이기에 이를 따라 구현하는 것이 맞을지 아니면 지금의 상태도 작은 블랙잭 게임으로 보고 추후에 확장하는 것이 옳을지 입니다.

이 부분 코멘트 남겨두었습니다..! 1단계에 저도 놓치고 리뷰하지 못한 부분인 것 같아요.

딜러의 배팅 결과를 계산하는 로직에 대한 책임

> 현재 BettingResult 라는 플레이어에 따른 배팅 결과(int) 를 가지는 Map을 래핑한 클래스에서 이를 계산합니다. ' 플레이어의 총 수입의 합 + 딜러의 수익 = 0 ' 이라는 기준에서 이 계산에 대한 책임이 BettingResult에 있다고 생각했지만, 무언가 마음에 들지 않는데 이유를 모르겠습니다. 이를 포함해 배팅 관련 기능들에 대한 책임들이 적절히 분배되지 않았다는 기분이 드는데, 어떻게 생각하시는지 궁금합니다!

이 부분도 코멘트 남겨두었으니 확인 부탁드립니다!

> 3. 상태 패턴의 적용에 대한 고민
현재 플레이어의 승리 / 플레이어의 블랙잭으로 인한 승리 / 플레이어 패배 이렇게 세 상태를 enum으로 관리하고 있습니다. 오늘 블랙잭 피드백 첫 번째 수업에서 네오께서 state 패턴을 사용하셨는데, 이와 같은 부분에 해당 패턴을 적용하는게 옳은 선택인지 궁금합니다.

어떤 것이 옳다 그르다는 정의하기 어렵습니다🙂 다만, 현재 구조상 복잡하게 얽혀있는 분기문들은 상태 패턴을 도입할 시 많이 해소될 수 있겠다는 생각이 들긴 하네요. 무빈의 판단 하에 도입할지 말지 결정해주시면 좋을 것 같습니다!
도입하게 된다면, 상태패턴을 도입하면서 느껴지는 장단점들도 생각해보시면 좋을 것 같아요

2024-03-13 13:07 UTC, yxxnghwan commented on src/test/java/domain/participant/HandTest.java
> +        Assertions.assertThat(isMaximum).isTrue();
어디는 정적임포트를 사용해서 Assertions가 빠져있고 어디는 붙어있는데 일관되면 좋을 것 같아요..!

2024-03-13 13:07 UTC, yxxnghwan commented on src/main/java/domain/dto/BettingResult.java
> +}
dto인데 딜러의 베팅에 의한 결과를 계산하여 반환하는 로직을 가지네요🤔

2024-03-13 15:00 UTC, hjk0761 commented on src/test/java/domain/participant/PlayerNamesTest.java
>      }
이와 같은 부분 모두에서 1단계 마무리 때에 주셨던 리뷰를 통해 해당 상수를 public 으로 전환하고, 이를 테스트에서도 확인할 수 있게 바꾸었습니다.

2024-03-13 15:00 UTC, hjk0761 commented on src/main/java/domain/Amount.java
> +public class Amount {
BettingAmount 라는 이름으로 좀 더 의미를 전달할 수 있게 바꾸어 보았습니다!

2024-03-13 15:12 UTC, hjk0761 commented on src/main/java/controller/BlackJackController.java
> +        List<PlayerHandStatusDto> playerHandStatusDtos = players.stream().map(PlayerHandStatusDto::of).toList();
전체적으로 스타일과 관련된 리뷰가 많은 것 같아 스스로 너무 서두르고 부주의한 2단계 구현이었다는 생각이 들었습니다. 앞으로 빠른 리뷰 요청보다 양질의 리뷰 요청을 보낼 수 있도록 노력해보겠습니다. 놓친 부분 없이 잘 짚어주셔서 감사드립니다!

2024-03-13 15:12 UTC, hjk0761 commented on src/main/java/controller/BlackJackController.java
> +    private static void playOneTurnForPlayer(final BlackJackGame blackJackGame, final Player player) {
불필요한 static 의 사용이었기에 제거했습니다.

2024-03-13 15:13 UTC, hjk0761 commented on src/main/java/domain/constant/GameResult.java
> +    WIN(1), LOSE(-1), WIN_BY_BLACKJACK(1.5);
트럼프 카드와 관련된 Enum 은 추가될 여지가 없기에 한 줄로 붙였지만 게임 결과는 해석이나 요구사항 변경에 따라 더욱 추가될 수 있을 것 같습니다! 말씀 주신 대로 개행을 추가해보았습니다.

2024-03-14 02:33 UTC, hjk0761 commented on src/main/java/domain/Betting.java
> +
구현할 당시에 Betting 인스턴스가 오직 하나만 존재해야 한다는 생각에 싱글톤 패턴으로 구현했었습니다.
하지만 리뷰를 받고 생각해보니 이와 같은 논리로 싱글톤 패턴을 적용하였다면 BlackJackGame 이나 Deck 등의 도메인들도 오직 하나의 인스턴스만을 사용할 것을 가정하고 만들었기 때문에 싱글톤을 적용해야 한다는 생각이 들었습니다.
하지만 프로그램의 규모에서 보았을 때에 싱글톤을 적용하였을 때의 이점을 느끼기 어렵다고 느껴 해당 패턴을 사용하지 않도록 변경하였습니다.

2024-03-14 06:18 UTC, hjk0761 commented on src/main/java/domain/PlayingCardValue.java
>      }
Ace의 초기값이 1인지 11인지를 물어봐주셨던 1단계 리뷰와도 이어지는 부분인 것 같아 많은 고민을 해보았습니다!

먼저 말씀 주신 부분처럼 Ace가 11인 경우는 최대 1회이기 때문에 Ace의 초기값을 1로 설정하였고, Ace 의 값이 차후에도 변할 수 있다는 문제를 해결하기 위해서 계산하는 구조를 바꾸어 보았습니다.
에이스를 모두 1로 가정할 때의 합인 primitiveSum을 구하고, 이를 기반으로 10을 더할 수 있다면 더해서 OptimizedSum을 구해보았습니다.

크루들과 이 구조에 대해 이야기하면서, 지금 제 구조처럼 PlayingCardValue가 Hand에서 primitiveSum을 받아 자신의 최적화된 값을 뱉어내는 구조와 Hand에서 아래의 PlayingCardValue를 결정짓는 구조 중 어느 것이 책임을 잘 배분한 것인지 궁금해 졌습니다.
저는 PlayingCardValue가 카드의 값을 결정하는 책임을 가진다고 생각해 이런 구조로 만들었지만 단점으로 Hand와 PrimitiveSum값을 주고받아야 하는 단점이 있었습니다.
후자의 Hand가 Ace의 값을 결정하는 구조는 PlayingCardValue가 그 자체로만 존재하고 값만 뱉어내도 되지만 Hand가 본인이 가진 카드들 중 Ace를 찾아서 값을 정하는 과정이 필요하다는 단점이 있었습니다.

알렉스께서는 두 가지 구조 중 어떤 구조가 카드의 값을 결정하는 구조를 잘 나타낸 것이라고 생각하시는지 궁금합니다!

2024-03-14 06:56 UTC, hjk0761 commented on src/main/java/domain/dto/BettingResult.java
> +}
간단한 계산이어서 처음엔 DTO에 둬도 괜찮다고 생각했었지만 DTO는 말 그대로 Date Transfer의 역할만 하도록 해당 로직은 GameResults로 옮겨 보았습니다.

2024-03-15 10:48 UTC, yxxnghwan commented on src/main/java/controller/BlackJackController.java
> +public class BlackJackController {
컨트롤러라는 네이밍을 해주셨네요..! 무빈이 생각하는 컨트롤러는 무엇인가요?

2024-03-15 10:48 UTC, yxxnghwan commented on src/main/java/domain/participant/PlayerNames.java
> +    public static final int MAX_PLAYER_NUMBER = 10;
테스트 때문에 public이 된 것 같은데 테스트를 위해 접근제어자를 변경하는게 괜찮을까요?
굳이 테스트에서 해당 상수를 사용해서 테스트해야하나요?

2024-03-15 10:48 UTC, yxxnghwan commented on src/main/java/domain/dto/BettingResult.java
> +public record BettingResult(Map<PlayerName, Integer> result, int DealerResult) {
다른 DTO클래스들은 Dto라는 접미사가 붙는데 이 클래스는 그냥 BettingResult네요! 어떠한 구분짓는 규칙이 있는걸까요?

2024-03-15 10:48 UTC, yxxnghwan commented on src/main/java/domain/PlayingCardValue.java
> +    ACE(1), TWO(2), THREE(3), FOUR(4), FIVE(5), SIX(6), SEVEN(7), EIGHT(8), NINE(9), TEN(10), JACK(10), QUEEN(10), KING(10);
옆으로 길게 뻗어있는 것보다 개행되어있으면 보기 편할 것 같아요 :)

2024-03-15 10:48 UTC, yxxnghwan commented on src/main/java/domain/constant/GameResult.java
> +
새로운 enum이 추가될 때를 생각해서 아래처럼 쓰기도 합니다!
```suggestion
    LOSE(-1),
    WIN_BY_BLACKJACK(1.5),
    ;
```

2024-03-15 10:48 UTC, yxxnghwan commented on src/main/java/domain/PlayingCardValue.java
>      }
저도 처음에는 카드가 자신의 점수를 계산한다는게 역할에 맞다고 생각이 들었으나, 블랙잭의 룰상 여러 카드를 조합했을 때마다 점수계산이 달라진다는 점에선 Hand가 계산 공식을 갖는게 역할에 맞는 것 같다는 생각입니다 :)

2024-03-15 10:53 UTC, yxxnghwan requested changes
안녕하세요 무빈! 코멘트 잘 반영해주셨네요!
추가로 생각해볼만한 코멘트 몇개 남겼습니다! 확인 부탁드려요! :)

2024-03-15 10:53 UTC, yxxnghwan commented on src/main/java/domain/GameResults.java
> +        return -1 * result.values().stream().reduce(0, Integer::sum);
뒤에 스트림 구문은 변수로 따로 추출하는게 가독성이 좋을 것 같은데 어떻게 생각하시나요?!

2024-03-15 10:53 UTC, yxxnghwan commented on src/main/java/domain/participant/Hand.java
>      }
2는 어떤 숫자일까요?!

2024-03-15 14:27 UTC, hjk0761 commented on src/main/java/domain/participant/PlayerNames.java
> +    public static final int MAX_PLAYER_NUMBER = 10;
이전 단계 리뷰(https://github.com/woowacourse/java-blackjack/pull/618#discussion_r1519174563)에서 요구사항에 바뀔 때에 에러 메시지도 정상적으로 출력하기 위해서 상수화를 진행했었습니다.
이에 따라서 테스트 메서드에서도 요구사항이 바뀌면 메시지도 반영되도록 상수를 사용하고자 생각했고, 이를 위해 상수이기에 변경의 여지가 없다고 생각해서 public으로 열어두게 되었습니다.

다만, 요구사항이 바뀌었을 때 당연히 테스트 코드도 수정이 되어야 함을 생각한다면 해당 도메인 내에서만 사용하는 상수까지 가져다 쓸 필요는 없을 것 같다는 생각이 들었습니다.

2024-03-15 14:31 UTC, hjk0761 commented on src/main/java/domain/constant/GameResult.java
> +
추가를 감안해서 뒤에 ','를 붙여서 사용하는 방법이 되는 줄 몰랐었습니다!
새로운 방법 알려주셔서 감사합니다 😊

2024-03-15 14:46 UTC, hjk0761 commented on src/main/java/domain/GameResults.java
> +        return -1 * result.values().stream().reduce(0, Integer::sum);
해당 구문을 메서드로 둔 이유가 결과를 계산할 때에 딱 한 번 사용되고, 이 변수를 계산하는 로직이 Map 에서 Value 들의 합을 구하고 -1을 곱한 단순한 계산이라 Map 에 종속된다고 생각하여 변수로 두지 않고 메서드로 분리해둔 것 이었습니다.
변수로 분리하게 된다면 네이밍이 get을 가지긴 했지만 계산하여 값을 뱉어내는 현 상태에서, 변수로 분리하면 계산된 필드를 보내주는 getter의 역할로 바뀌게 됩니다.
다만 차후 재사용이 고려된다면 메서드로 계속 계산을 수행하는 것 보다 변수로 계산 결과를 저장해 두는 것이 코스트가 적게 들 것이라는 장점이 보여 변수로 분리해보겠습니다!

2024-03-15 14:49 UTC, hjk0761 commented on src/main/java/domain/participant/Hand.java
>      }
여기서 2는 초기에 가지고 있을 손패의 수를 정하는 숫자입니다. 이는 블랙잭 게임의 룰인 초기에 뽑는 카드 수와 연관된 부분입니다.

바로 옆 BLACKJACK_CONDITION 또한 룰에 관련된 부분이기에 BlackJackGame에서 관리되는 만큼, 같은 이유로 2를 상수화하고 이를 BlackJackGame에서 관리하도록 수정했습니다!

2024-03-15 15:01 UTC, hjk0761 commented on src/main/java/domain/dto/BettingResult.java
> +public record BettingResult(Map<PlayerName, Integer> result, int DealerResult) {
이전 리뷰에서 수정된 부분이지만, BettingResult 가 Map 의 Value 들의 합을 계산하는 로직을 가지고 있어서 Dto 라고 이름짓지 않았습니다. 하지만 해당 로직이 다른 곳으로 옮겨간 현 상황에서 Dto 라는 이름이 붙는 것이 객체의 의미를 잘 드러내는 방법인 것 같습니다!

2024-03-15 15:05 UTC, hjk0761 commented on src/main/java/controller/BlackJackController.java
> +public class BlackJackController {
1단계 리뷰에서도 같은 질문을 해주셨던 것으로 기억합니다!(https://github.com/woowacourse/java-blackjack/pull/618#discussion_r1519325422)
다만 컨트롤러의 역할이 서로 분리된 뷰와 모델들을 이어주면서 프로그램을 동작하게 해주는 중계자의 역할을 수행한다고 말씀 드렸었는데, 혹시 지금의 BlackJackController 가 해당 역할을 벗어나는 일을 하고 있다고 생각하신 것이라면 어느 부분이 그러한지 말씀 주시면 감사하겠습니다!

2024-03-15 15:24 UTC, hjk0761 commented on src/main/java/domain/PlayingCardValue.java
>      }
그럼 알렉스께서는 점수를 계산하는 책임이 손패에 있기 때문에 카드가 자신의 값을 계산하기 위해 상위 객체인 손패에서의 합을 알아야 하는 부분이 책임 분배에 적절하지 않다고 보신 거겠군요! 카드가 값을 스스로 정하기 위해선 외부의 도움(지금까지의 손패의 합, 지금 구현에서 primitiveSum)이 꼭 필요하다는 점에서 카드 스스로 값을 정하는 건 블랙잭의 룰 아래에선 적절한 책임 분배가 아니라는 생각 또한 들었습니다. 점수 계산에 대한 책임은 Hand로 옮겨 구현해 보겠습니다! 객체가 가지는 책임이 적절한 지에 대해 깊게 고민해 볼 수 있어서 좋았습니다, 감사합니다!

2024-03-16 16:46 UTC, yxxnghwan commented on src/main/java/controller/BlackJackController.java
> +public class BlackJackController {
MVC패턴에서 말하는 컨트롤러는 말씀주신 모델과 뷰를 연결해주는 역할이 맞습니다. 다만, 현재 자바 콘솔 게임에서 컨트롤러라는 네이밍이 적절한지 고민해보면 좋을 것 같아요. 컨트롤러가 현재 게임을 실행시키고 있는데, 컨트롤러라는 단어 뜻을 생각하면 어색한 느낌이 많이 듭니다. 무언가 인풋을 넣으면 그 동작을 수행하는게 컨트롤러라고 생각되어요. MVC 패턴에서도 같은 매커니즘으로 동작하기도 하구요. 현재 자바 콘솔 프로그램에서 컨트롤러의 역할은 무엇인가요?

2024-03-16 16:48 UTC, yxxnghwan commented on src/main/java/domain/participant/PlayerNames.java
> +    public static final int MAX_PLAYER_NUMBER = 10;
무빈의 생각에 공감합니다. TDD관점에서 요구사항이 변경된다면,

1. 테스트 코드에서 에러 메시지 변경
2. 테스트 실패
3. 프로덕션 코드에서 상수값 변경
4. 테스트 성공

순서로 진행되는게 맞는 것 같기도 하구요. 잘 고민해주신 것 같아요👍🏿

2024-03-16 16:50 UTC, yxxnghwan commented on src/main/java/domain/GameResults.java
> +        return -1 * result.values().stream().reduce(0, Integer::sum);
에고 오해의 소지가 있었던 것 같네요! 이 메소드 안에서 변수추출이 어떨까 싶었습니다! 메소드라인이 하나인데 너무 많은 행위가 담겨있어서요!

2024-03-16 16:57 UTC, yxxnghwan approved these changes
안녕하세요 무빈! 리뷰 잘 반영해주셨네요. 질문주신 부분들에 대한 제 생각 코멘트로 남겨두었습니다!
추가적으로 생각해볼만한 코멘트들 몇개 남겨놨는데, 사소한 부분들 남은 것 같아 다음 미션에서 고민해서 반영해주시면 될 것 같아요! 이번 미션은 이만 마치도록 하겠습니다. 수고많으셨어요! 👍🏿

2024-03-16 16:57 UTC, yxxnghwan commented on src/main/java/domain/GameResults.java
> +        return (int) (betting.getBetting(playerName).getAmount() * gameResult.getProfitRatio());
```suggestion
        return (int) (betting.getBettingAmount(playerName) * gameResult.getProfitRatio());
```
이렇게 코드가 되도록 수정되면 어떨까요?

2024-03-16 16:57 UTC, yxxnghwan commented on src/main/java/domain/GameResults.java
> +        int dealerBettingResult = -1 * result.values().stream().reduce(0, Integer::sum);
한 라인에서 하는 동작이 되게 많은 것 같아요!

2024-03-16 16:57 UTC, merged