[2단계 - 블랙잭 베팅] 콜리(김건우) 미션 제출합니다.
woowacourse/java-blackjack pull request #680
Opened 2024-03-12 11:07 UTC by coli-geonwoo

2024-03-12 11:31 UTC, coli-geonwoo commented
안녕하세요 미르 🙌 

먼저 1단계 미션을 늦게 제출한 사안에 대해 죄송하다는 말씀을 올립니다. 당시 상황에 대해 말씀드리자면 17:30분경에 pull request를 올려놓고 리뷰요청을 클릭한 상태였으나, 페어 리뷰가 완료되어있지 않아 LMS에 신청이 되지 않았다는 것을 18 : 10이 되어서야 알게되었습니다. 온전히 제 불찰이지만 가벼운 마음으로 미르와의 리뷰를 대하고 있지는 않는다는 사실을 전하고 싶습니다.

1-2단계 미션 과정에서 고민했던 사안들에 대해 질문 드립니다.

**1. 패를 확정하는 과정을 도메인 객체로 분담할 수 없을까?**
블랙잭 게임에서 참여자들의 패를 확정하는 과정은 domain과 view로직이 반복되어 있습니다.
```
1) view - hit을 할 것인지 물어본다
2) domain - 승낙하면 패를 더 준다
3) view - hit or stay 이후의 참여자들의 패를 보여준다
```
그렇기에 Players라는 일급컬렉션에 참여자들의 패를 확정하는 책임을 캡슐화할 수 없었습니다. 물론 view 로직을 함수형 인터페이스를 통해 받아줄 수 있었으나 이는 도메인 객체가 뷰로직을 의식한 결과이기에 책임이 혼재되어 있다고 생각했습니다

되도록 Controller가 아닌 도메인 객체가 패를 확정하는 로직을 가지게 하고 싶은데 view와 domain간의 상호작용이 필수적인 흐름에서는 도메인으로의 책임 이전이 가능할까요? 🤔 

**2. has-a 관계로의 상속 관점**
게임 참여자인 Participant 추상 클래스를 Player와 Dealer에게 상속시켜주었고, 각자 Hit의 필수조건인 canAddCard 추상메서드를 오버라이드하여 다형성을 추구했습니다. 그러나, 2단계로 넘어와서 Batting 멤버변수를 Player가 가지게 되면서 고민이 생겼습니다.

상위 클래스인 Participant의 멤버변수 Name, Hands까지 포함한다면 Player는 Name, Hands, Batting이라는 세가지 멤버변수를 가지게 되고 이는 `인스턴스 변수는 최대 2가지로 한다`는 요구사항 위반입니다.

그래서 생각해낸 아이디어는 Participant가 제공하는 메서드를 참여자라면 가지는 공통 책임이라는 뜻의 GamerCommonFeature로 생각하여 상속의 관점을 has-a 관계로 바꾸는 것입니다. 그러나, 이 리팩터링을 진행하지 않은 이유는 has-a 관계로 전환시 Participant가 외부에 제공하는 인터페이스를 Dealer와 Player가 그대로 구현해야 하였기 때문입니다. .

```java
ex)

public addCard(Card card){
    return Participant.addCard(card);
}
```

그리고 이는 추가적인 요구사안-Player와 Dealer의 중복코드를 없앤다-의 위반이라 생각되었습니다. 추가적으로 요구사안을 제외한 제 주관으로는 참여자와 딜러-플레이어의 관계가 is-a가 더 합리적으로 받아들여진다는 이유도 있었습니다.

그래서 고민 끝에 미르에게 다음 2가지 질문을 드리고자 생각했습니다.
- 미르는 is-a와 has-a 상속관계를 주로 어떤 기준으로 구분하시나요? 
- has-a 상속관계에서 멤버객체가 가지는 인터페이스를 그대로 노출해야 한다면 그 객체를 멤버로 넣어주는 의의가 있을까요? 😂 

**3. 번외질문**
피드백 강의에서 캐싱이라는 개념을 접하고 여기저기 정보를 찾아보고 있습니다. 아직 작은 규모의 프로그램이다보니 캐싱의 중요성이나 효율성에 대해 잘 와닿지 않는데, 현업에서도 캐싱이 정말 중요한 개념으로 사용되는지 궁금합니다 😄

2024-03-12 13:43 UTC, ddu0422 requested changes
안녕하세요 콜리! 미르입니다 :)
2단계 미션까지 잘 구현해주셨네요.
몇 가지 코멘트 남겼습니다!
궁금한 점 있으면 코멘트 남겨주시거나 DM 남겨주세요!

## 답변
1. Controller/Domain은 어떤 역할을 해야할까요?
2. 상속과 조합에 대한 질문일까요? is-a/has-a의 차이는 무엇일까요?
 > Participant가 외부에 제공하는 인터페이스를 Dealer와 Player가 그대로 외부에 공개해야 했고,

 &nbsp;&nbsp;&nbsp; 이 부분은 잘 이해가 가지 않는데 샘플 코드를 작성해서 전달해주실 수 있을까요?
3. 캐싱은 어떨때 활용해야할까요? 언제 활용해야하는지 고민해보면 어떨까요?

2024-03-12 13:43 UTC, ddu0422 commented on src/main/java/blackjack/view/OutputView.java
> +                , handsScore.toInt());
[배열 Convention](https://google.github.io/styleguide/javaguide.html#s4.8.3-arrays)과 유사하게 Comma를 Line 마지막에 작성하는건 어떨까요?

2024-03-12 13:43 UTC, ddu0422 commented on src/main/java/blackjack/view/OutputView.java
> +        Double dealerProfit = -1 * gameResult.getSumOfProfit();
-1을 view에서 해준 이유가 있을까요?

2024-03-12 13:43 UTC, ddu0422 commented on src/test/java/blackjack/domain/card/CardTest.java
>      }
assertAll을 사용하지 않고 하나의 데이터로 하나의 테스트만 진행하는건 어떨까요?
Dummy를 여러개 만들어 동일한 테스트를 진행하려면 어떤 방식으로 해야할까요?

2024-03-12 13:43 UTC, ddu0422 commented on src/test/java/blackjack/domain/gameresult/BattingTest.java
> +}
테스트 이름은 "가능"인데 에러가 발생하는 테스트군요!
배팅 가능과 배팅 불가능을 나누어 테스트하는건 어떨까요?

2024-03-14 01:53 UTC, coli-geonwoo commented on src/main/java/blackjack/controller/GameController.java
> +        return game;
사실 반환값이 없다는 오류를 해결하려고 넣은 코드라 찜찜했습니다. 이때까지만 해도 null 반환에 대해 큰 위화감을 가지지 않은 것도 사실입니다. 그러나, 책 <좋은 코드, 나쁜 코드>를 읽으면서 null객체를 반환하는 행위는 개발자간 코드 소통에 혼동을 주고 또, NPE에 대한 위험성이 커진다는 점에서 지양해야 한다는 사실을  최근 알게되었습니다.

미르의 말대로 재귀호출을 하거나, exception을 내면 makeGame() 메서드가 맡은 책임인 "정상적인 Game객체를 만들어줘"라는 요청에 더 알맞은 동작을 할 수 있으리라 생각하여 반영해주었습니다.

>> 질문 : 메서드에서 null반환은 언제나 지양되어야 하는 것일까?

다만 미르가 주신 `Game은 언제나 null인데 의미가 있는걸까요?`에 대해서 이 로직에 해당하는 일은 아니지만 `null을 반환하는 행위가 언제나 지양되어야 할까`로 확장하여 고민을 해보았는데요. 제 생각에는 empty source와 null source가 분명한 차이를 지니는 경우가 있기 때문입니다. 예를 들어 빈 문자열에 대한 메시지 반환은 사용자 입력에 대한 메시지 임을 인지할 수 있고, null 메시지 반환은 코드 내부에서의 메시지 반환이라는 점을 인지할 수 있는 경우를 들고 싶습니다. 이 차이가 유의하게 작요앟는 순간이 있을 것 같은데, 미르는 메서드의 null값 반환이 되도록 지양되어야 한다고 생각하시나요?

2024-03-14 01:57 UTC, coli-geonwoo commented on src/main/java/blackjack/controller/GameController.java
> +            return Game.of(InputView.readPlayerNamesAndBattings());
각 도메인 객체에 필요한 정보만을 넣어줄 수 있도록 리팩터링 하였습니다.

> 배운 점 : 도메인 객체 생성에는 필요한 정보만을 넣어주기
> 배운 점 : input 로직을 생각하여 도메인 객체의 생성자 인수를 결정하지 말기

InputView에서 이름을 입력받고, 그 이름에 대한 안내메시지대로 베팅을 입력받는 다는 점에서 이름-베팅 입력을 하나의 로직으로 생각하고 Map으로 도메인 객체를 생성했습니다. 그러나, 미르의 말대로 Map은 1:1 대응이기에 확장적인 코드가 아니었고, 플레이어 이름에 해당하는 요소들을 리스트나 튜플로 Map으로 묶어준다해도, 다른 객체들에게 불필요한 데이터가 들어갈 수 있다는 점을 캐치했습니다.

2024-03-14 01:58 UTC, coli-geonwoo commented on src/main/java/blackjack/domain/card/Card.java
> +// TODO 성격에 따라 패키지 나누어보기
미르에게는 전달되지 않아야할 불필요한 주석이 지워지지 않았군요! 남아있는 주석도 오도되지 않도록 신경쓰겠습니다 😄

2024-03-14 02:03 UTC, coli-geonwoo commented on src/main/java/blackjack/domain/card/Card.java
> +    }
eq & hc와 같은 스탠다드 메서드를 맨 아래 작성하는군요!  getter/setter보다는 위에 위치해야한다고 생각했습니다. 반영해주었습니다.

2024-03-14 02:06 UTC, coli-geonwoo commented on src/main/java/blackjack/domain/gameresult/Profit.java
> +    private static final int MAX_PROFIT = 10_000_000;
스스로 Profit에 대한 책임을 충분히 고려하지 못한 설계였던 것 같아요.

다음과 같이 리팩터링 해주었습니다.
- Profit 객체는 최소/최대 수익비율만을 책임진다 => 최소(-1배) / 최대(1.5배)
- 최소/최대 수익량은 최대 베팅 금액을 Batting 객체로부터 전달받아 산출한다. => ex) double maxProfit = Batting.maxBat() * MAX_PROFIT_RATE

2024-03-14 02:12 UTC, coli-geonwoo commented on src/main/java/blackjack/domain/gameresult/ResultJudge.java
> +    }
승패를 판단하고 / 승패에 따른 수익을 구한다. 라는 두 가지 책임을 각각의 enum class를 구현하여 분담했습니다.
-Result : 승패를 판단
-ResultProfit : 승패에 따른 수익 산출

다음과 같이 책임을 분담한 이유는
- Result enum이 결과(승패)의 조건을 가지고 판단하는 게 알맞은 책임이라 판단
- 결과를 '판단'해주는 로직과 결과에 따른 '수익 산출식'은 따로 관리하는 것이 단일책임원칙에 알맞다 판단

그러나, 다음과 같은 질문이 생겼습니다.
- Result enum class가 결과 각각의 판단로직과 수익산출로직을 모두 가진다면 응집성면에서 더 좋은 클래스가 되지 않을까?
- Result Class에서 가독성을 위해 승패판단 로직을 static 메서드로 분리하였는데 이것이 미르에게 가독성 있는 코드로 와닿을까?
- ResultProfit이라는 클래스가 `결과에 따른 수익반환로직`을 가진 enum Class라고 미르에게 직관적으로 읽혀질까? (이에 ProfitCalc로 이름을 지어보았다가 피드백을 받고 개선하고자 롤백했습니다.)

2024-03-14 02:12 UTC, coli-geonwoo commented on src/main/java/blackjack/domain/hands/Hands.java
> +                .map(Card::getValue)
말씀해주신 방안이 더 객체지향적인 코드인 것 같습니다

2024-03-14 02:13 UTC, coli-geonwoo commented on src/main/java/blackjack/domain/hands/Hands.java
> +    private static final HandsScore BLACK_JACK = new HandsScore(21);
정수형 21이라는 숫자는 HandsScore에만 반환하게 해주고, HandsScore는 카드패의 값을 관리하기에 정적 팩터리 메서드로 HandsScore.blackJack()을 통해 블랙잭 score를 반환하게 리팩터링해주었습니다.

2024-03-14 02:14 UTC, coli-geonwoo commented on src/main/java/blackjack/domain/participant/Name.java
> +    }
딜러가 책임져야 맞는 것 같습니다. Name은 순수한 값 객체이기 때문입니다

2024-03-14 02:14 UTC, coli-geonwoo commented on src/main/java/blackjack/view/KindView.java
> +        throw new IllegalStateException("존재하지 않는 카드 종류를 조회하였습니다.");
스트림을 통해 탐색하고 예외를 발생시켜주는 전반적인 코드에 모두 반영해주었습니다. 더 깔끔해진 코드가 된 것 같아요!

2024-03-14 02:17 UTC, coli-geonwoo commented on src/main/java/blackjack/view/OutputView.java
> +        Double dealerProfit = -1 * gameResult.getSumOfProfit();
GameResult는 Player와 각 플레이어의 수익(Profit)에 대한 정보만을 담당하는 객체로 설계했습니다. 딜러의 수익은 모든 플레이어의 수익을 더한 값의 -1을 곱한 값입니다. 딜러의 수익률을 보여주고자 하는 것은 View의 의도이지 도메인 객체가 담당해야 하는 책임이 아니라 생각했습니다.

GameReuslt 객체는 자신이 가진 플레이어별 수익의 합산을 반환해주는 것에 그치는 것이 view를 의식하지 않은 메서드 로직이라 생각했습니다.

2024-03-14 02:18 UTC, coli-geonwoo commented on src/test/java/blackjack/domain/card/CardTest.java
>      }
MethodSource를 통해 Dummy를 넣어주어 동일한 로직으로 테스트를 진행해보았습니다.
다만, 이 테스트에서 assertAll은 Kind와 Value값 확인을 동시에 테스트하고 있기에 넣어주었습니다.

2024-03-14 04:52 UTC, coli-geonwoo commented
안녕하세요 미르 🙌 

답변해주신 사안에 대한 제 의견과 추가 질문을 남깁니다. 

> 의견

**1. Controller/Domain은 어떤 역할을 해야할까요?**

사실 컨트롤러의 역할에 대해 `도메인과 뷰를 연결`, `전체 로직의 흐름 제어`와 같이 추상적으로 인식하고 있습니다. 

제가 질문을 드린 의도는 
- Controller에 드러나 있는 [참여자들이 각자의 패를 확정하는 과정]이 GameParticipants와 Deck을 가진 Game 도메인의 책임이라 생각합니다.
- Players는 view(player의 승낙 여부 질문) - domain(addcCard) - view(player 패 출력) 와 같은 연관성으로 인해 Game이 가진 Players를 getter로 꺼내어 컨트롤러에서 로직을 제어하고 있습니다.
- 그렇다면 Players와 Dealer만 존재해도 되는 것인지 아닌지 의문이 들었고 Game 객체는 왜 존재해야 하는지에 대한 이유가 불분명해짐과 동시에, getter의 반복적인 사용으로 캡슐화를 해치고 있다는 느낌이 들었습니다.

패를 확정하는 흐름이 질문 - 카드추가 -카드패 출력이기 때문에 controller의 역할에 알맞다 생각합니다. 그러나, 이 로직을 객체 안으로 넣을 수 있다면 더 깔끔한 코드가 될 것 같아 뷰로직을 함수형 인터페이스 인수로 받아 메서드를 구현해보았는데 이것은 뷰를 의식한 도메인 메서드가 생기는 것 같아 롤백해주었습니다.

뷰 로직으로 인해 도메인이 맡아야할 책임이 컨트롤러로 올라온 상황에서 이게 어쩔 수 없는 상황인 것인지 혹은 적절한 절충안이 있는지 미르의 의견이 궁금하여 질문드렸습니다.

**2. 상속과 조합에 대한 질문일까요? is-a/has-a의 차이는 무엇일까요?**

상속과 조합에 대한 질문이 맞습니다. 

- **is-a**
-  상위 객체와의 강한 의존관계를 지님
-  공유되는 멤버변수와 메서드에 대한 변동가능성이 크지 않을 때,
-  확장 가능성이 큰 경우

-**has-a**
- 객체의 `공통된 구성요소와 기능` 으로 소유적인 의미
-  is -a 보다는 더 느슨한 결합관계를 지님

=> 그래서 되도록 has-a관계로 바라보고 싶은 것이 지금의 생각입니다. 그런데 has-a관계로의 전환에 대해 생각하다가 고민이 생겼습니다.

이 고민에 대한 질문의 의도와 명세가 명확하지 않았던 것 같아요 😢  조금 더 상세히 적어 전달드립니다!

`Participant가 외부에 제공하는 인터페이스를 Dealer와 Player가 그대로 외부에 공개해야 했고,`
현재 is-a 관계에서 Participant는 isBust, hasLowerScore, getName(), getHandsCard(), addCard()와 같은 메서드가 외부로 공개되어 있습니다. 만약 has-a관계로 전환하여 Participant가 담당하는 공통기능을 Dealer와 Player가 멤버변수로 소유하게 된다면 Participant에서 상속받은 public 인터페이스를 그대로 구현해주어야 한다는 중복의 문제가 생겼습니다.

샘플 코드는 다음과 같습니다. 

```java

public Dealer{
     private GamerCommon; // Participant를 참여자의 공통 기능으로 보고 has-a 관계로 전환한 객체이름
     private Batting;
 
    public void addCard(Card card) {
          GamerCommonFeature.addCard(card);
     }

    public List<Card> getHandsCards() {
        return GamerCommonFeature.getHandsCards();
    }

    public HandsScore getHandsScore() {
        return GamerCommonFeature.getHandsScore();
    }
}

public Player{
     private GamerCommon // Participant를 참여자의 공통 기능으로 보고 has-a 관계로 전환한 객체이름

     public void addCard(Card card) {
          GamerCommonFeature.addCard(card);
     }

    public List<Card> getHandsCards() {
        return GamerCommonFeature.getHandsCards();
    }

    public HandsScore getHandsScore() {
        return GamerCommonFeature.getHandsScore();
    }
}
```
그렇게 해서 나온 질문이 다음 질문입니다.
- has-a 상속관계에서 멤버객체가 가지는 인터페이스를 그대로 노출해야 한다면 그 객체를 멤버로 넣어주는 의의가 있을까요?


**3. 캐싱은 어떨때 활용해야할까요? 언제 활용해야하는지 고민해보면 어떨까요?**

캐싱은 `인스턴스 생성비용이 클 때`, `반복적으로 활용하는 인스턴스가 있을 때`, 필요할 때마다 인스턴스 생성을 하는 것이 아닌 미리 생성된 인스턴스를 반환하는 식으로 효율을 챙기는 것으로 인식하고 있습니다. 최근 책 <이펙티브 자바>를 보며 캐싱의 중요성이 제가 생각한 것보다 더 크다는 사실을 체감하고 있습니다.

그러나, 질문을 구체화해보면 `생성비용이 크지 않아도 반복적으로 활용하는 인스턴스가 있을 때 ` 캐싱의 필요성에 대한 의문이 들었던 것 같습니다. 이번 리팩토링을 통해 카드패의 점수 값 객체인 HandsScore를 캐싱한 것이 그 사례인데요. 
카드패 점수가 될 수 있는 0점부터 31점까지 모두 객체를 생성해놓고 객체를 호출하면 미리 생성해놓은 HandsScore 인스턴스를 반환해주었습니다.  분명 캐싱을 통해 범위가 한정되어 있고 반복적으로 호출되는 HandsScore의 생성비용을 줄일 수 있음은 맞습니다. 

그러나
1. 최대 플레이어 수를 8명으로 제한하였기에 딜러를 포함해도 실제로 사용되는 카드패 점수는 9개에 그친다.
2. HandsScore은 단순한 값 객체인만큼 생성비용이 크지 않다

이러한 요소로 인해 캐싱이 유리한 상황과 선호되지 않아도 되는 상황에 대한 구분점을 알고 싶었습니다.

---

## 질문

이외에 리팩터링 과정에서 생각한 질문들입니다

- Result 객체에서 승패 판단 로직을 static 메서드로 분리하는 것이 괜찮은지?
    - 가독성을 위해 승패 판단 로직을 static 메서드로 각각 분리하고 Enum class의 멤버로 넣어주었습니다.
    - static 메서드는 OOP적인 코드가 아니라는 의견을 본 적이 있어 망설여졌습니다. 그러나 그것은 타 객체와의 상호작용의 이야기이고 자기 자신 클래스와의 소통에 있어 가독성을 위해 static 메서드로 분리하는 과정은 객체와의 메시지를 주고받는 OOP 개념을 해친다고 생각하지 않았습니다. 

- Result enum 객체가 승패 판단로직과 수익 산출 로직을 한번에 들고 있는 것이 더 응집성 있지 않을까?
- private static 멤버를 반환하는 행위 
     - Profit 객체에서 최대 수익금액을 산출하기 위해 Batting의 정적 멤버변수인 최대 배팅금액을 반환하는 static 메서드(Batting.maxBat())를 사용했습니다. 

    - 그 이유는 Batting의 최대값(만원)과 Profit의 최대값(만 오천원)을 각각 정의하면, 이후의 batting의 최대값이 2만원으로 달라진다면 Profit의 최대값도 2만원의 1.5배인 3만원으로 수정해주어야 하는 등 수정포인트가 이원화 되어 있기 때문입니다. 그래서  Profit에서는 최소 수익 비율(-1배)와 최대 수익 비율(1.5배)만을 가지고 있게 하였고, maxProfit을 MAX_PROFIT_RATE * Batting.maxBat()을 통해 산출하여 조금 더 각자의 책임만을 가지도록 리팩터링하였습니다.
    그러나, Batting의 private static 변수인 MAX_BAT을 밖으로 반환하는게 조금 찜찜했습니다.
   
  -  static 메서드를 외부로 노출하는 행위는 객체의 접근 제어자 private의 의미를 퇴색시킨다는 생각이었으며, Profit과 Batting의 의존성을 만든다는 생각이기도 했습니다. 
 -> 만약 필요에 의해 private static 변수를 전달하는 메시지를 보내는 메서드가 정의되었다면 이는 getter 처럼 지양되어야 하는 행위일까요?

---

이외에 1차 개선사안에 대해 정리한 리팩터링 사안을 전달드립니다.(README.md에도 적혀있습니다.)

## 1차 리뷰 개선사안

- controller/GameController : Game 생성 로직에서 예외처리


- domain : Map 생성자 인수 개선 
  - 확장성을 고려하여 각자에게 필요한 인수만으로 리팩터링
- gameResult/Profit : 최대/최소 수익이 아닌 수익률을 가지고 있도록 수정
- gameResult/Profit : Batting 객체를 통한 최대/최소 수익 계산
- gameResult : 승패 판정 책임과 결과에 따른 수익 반환 책임 분리
  - Result(enum) : 승패 판정
  - ResultProfit(enum) : 승패에 따른 수익 반환
- card/Card : 해당 카드 번호를 가졌는지 메시지를 반환하는 메서드 추가
- hands/HandsScore : BLACK_JACK 점수 객체를 반환하는 정적 팩토리 메서드 추가
- hands/HandsScore : 자주 사용되는 스코어 인스턴스 캐싱
- participant : 딜러 이름 관리 책임 이전 (Name > Dealer)
- 스트림 orElseThrow를 통한 Optional 타입 값 예외처리
- eq & hc 컨벤션 준수를 통한 코드 가독성 개선
- 불필요한 TODO 및 주석 삭제

- view: 컨벤션 준수를 통한 코드 가독성 개선
- test/BattingTest : 성공/실패 각각의 테스트 케이스 추가
- test/ProfitTest : 성공/실패 각각의 테스트 케이스 추가

2024-03-14 13:15 UTC, ddu0422 commented on src/main/java/blackjack/controller/GameController.java
> +        return game;
null 값 반환이 되어야 하는 상황이라면 null이 반환되어야 한다고 생각해요 :)
`하지만 위 코드에선 null을 반환해야 하는 상황일까?`에 대한 의견이었습니다.

2024-03-14 13:44 UTC, ddu0422 commented on src/main/java/blackjack/domain/gameresult/Result.java
> +    }
깔끔하게 리팩토링 하셨네요 👍🏻 👍🏻 

추가 리뷰) Result는 결과의 책임만 지고 Result의 Condition은 다른 책임으로 넘길 수 없을까요?

2024-03-14 13:44 UTC, ddu0422 commented on src/main/java/blackjack/view/OutputView.java
> +        Double dealerProfit = -1 * gameResult.getSumOfProfit();
네 크루들과 비슷하다고 생각해요.
딜러가 수익을 얻고, 잃은 것 또한 중요한 규칙이지 않을까요?

2024-03-14 14:18 UTC, ddu0422 requested changes
안녕하세요 콜리! 미르입니다 :)
피드백 잘 반영해주셨네요.
코멘트 남겼으니 확인 부탁드려요~

## 의견 답변

1. 저는 의도에 맞게 잘 구현되었다고 생각해요.
controller는 승낙 여부 질문으로 흐름을 제어한 것이고, domain은 그에 따라 카드를 뽑았습니다.
y, n이 아닌 true, false 등으로 변경되면 domain에서 카드를 뽑느냐 뽑지 않느냐정도는 결정할 수 있을 것 같습니다.

2. > has-a 상속관계에서 멤버객체가 가지는 인터페이스를 그대로 노출해야 한다면 그 객체를 멤버로 넣어주는 의의가 있을까요?

다형성을 이용하려면 어떤 방식을 활용해야할까요?

3. 네 현재는 그렇지만 나중을 위해 연습한다고 생각해보면 어떨까요?

## 질문 답변

각 질문은 리뷰와 코멘트에 남긴 것 같아요.
놓친 부분이 있으면 다시 이야기주세요!

2024-03-14 14:18 UTC, ddu0422 commented on src/main/java/blackjack/domain/gameresult/Profit.java
> +    }
수익은 수익이고 배팅은 배팅일텐데, 수익을 제한하는 편이 올바른지 고민이 되네요.

2024-03-15 06:25 UTC, coli-geonwoo commented on src/main/java/blackjack/view/OutputView.java
> +        Double dealerProfit = -1 * gameResult.getSumOfProfit();
저도 미르와 크루들의 의견이 합리적이라 생각되네요! GameResult에서 getDealerProfit을 통해 책임을 도메인 객체로 넘겨주었습니다.

2024-03-15 06:31 UTC, coli-geonwoo commented on src/main/java/blackjack/domain/participant/Participant.java
> +    }
무언가 개발자 입장에서는 추상 클래스의 abstract가 구현체에서 중요하게 다루어질것 같아 위에 배치해놓았습니다. 아무래도 다형성을 추가하는 메서드인만큼 이 메서드의 내부 구현방식이 각 구현체의 정체성을 결정지을 수 있다고 생각했거든요! 

business method > getter 까지는 저도 합리적이라 생각하는데, 미르는 abstract을 하단에 놓으시는 이유가 있으실까요?  🤔

2024-03-15 06:31 UTC, coli-geonwoo commented on src/main/java/blackjack/domain/card/Value.java
> +public enum Value {
저도 매우매우 동의합니다!! 리팩터링 해주었습니다.
Kind > CardKind
Value > CardNumber

2024-03-15 06:33 UTC, coli-geonwoo commented on src/main/java/blackjack/domain/gameresult/Profit.java
> +    }
옳지 않은 것 같습니다. Profit은 게임룰을 모르는 단순 값 객체여야 하는데 게임 결과에 따른 Profit_Rate라는 룰을 의식함으로써 검증을 해주려 했던 것 같아요. 

Profit_Rate라는 enum을 통해 각 승패결과에 따른 rate를 분리해주었고 Profit은 VO로서의 순수함만 가지도록 노력했습니다.

2024-03-15 11:26 UTC, coli-geonwoo commented
안녕하세요 미르 🙌  2차 개선사안 말씀드립니다.

큰 리팩터링 사안은 2가지입니다.

**1. is-a관계를 has-a 관계로 전환**
이전에 게임참여자의 공통특성을 추상화하였던 Participant와 (Dealer,Player) 간의 is-a관계의 의존성을 없애주었습니다. 그 이유는 다음과 같습니다.

- Dealer와 Player간에는 상속을 통해 다형성을 추구하는 기능이 필요하지 않습니다.
- Dealer와 Player는 게임 내에서 서로 다른 책임을 지고 있습니다. 딜러는 게임 결과를 플레이어와 비교하는 책임을 지니며, 이름을 가지지 않아도 되고 hit 여부를 결정하는 과정 또한 다릅니다.
- 객체간의 불필요한 의존성을 최대한 지우고 싶었습니다.

**2. 배팅을 관리하는 GameBettings 객체**
플레이어가 베팅을 가지는 것은 "블랙잭 게임의 룰"이 플레이어의 상태에 영향을 주는 것이라 생각했습니다.  플레이어는 이름과 카드패만 가지는 것이 정체성을 잘 대변한다 생각하였습니다. `인스턴스 변수는 최대 2가지로 한다`라는 요구사안에도 더 적절한 설계라 생각했습니다.

대신 Player-Betting을 매핑시킨 GameBettings 객체를 만들어 플레이어가 건 베팅 금액을 관리해주도록 하고, 이를 Game 객체가 가지고 있도록 하였습니다.

## 2차 리뷰 개선사안
- 상속관계 Participants 삭제
- 베팅을 관리하는 GameBattings 객체 추가
- 게임 결과 판단에 대한 책임을 Game으로 이전하여 Map<Player, Profit>을 GameResult에게 넘겨줌
- 결과와 결과조건에 대한 책임 분리
  - Result : 승패 결과만을 대변
  - ResultJudge : 승패 판단 
- GameResult : 딜러 수익 결과 반환 로직 추가
- Profit : 범위 검증 과정 삭제
- rename: Value > CardNumber 

## 질문

> Result enum 객체가 승패 판단로직과 수익 산출 로직을 한번에 들고 있는 것이 더 응집성 있지 않을지 고민이 되었습니다. Result 하나에 대한 관리포인트가 많아진 느낌이 듭니다 🤔 
<br>

> GameResult는 단순 게임 결과만 저장하는 책임으로 바라보아 ,Game 객체에서 플레이어와 수익결과를 Mapping을 하여 GameResult에게 넘겨주었습니다. 이 책임 분배가 자연스럽다고 느껴지는지 궁금합니다!

2024-03-16 03:44 UTC, ddu0422 commented on src/main/java/blackjack/domain/gameresult/Result.java
> +    }
저는 더 작은 단위의 개념을 생각했어요.
`ResultJudge` 결과 판단이 변경되어야 하는 경우 책임지녀야할 객체라고 생각해요.

아래와 같은 요구사항이 있다고 생각해볼게요.

1. 무승부가 더 이상 필요없으니 제거해주세요.
2. 무승부의 조건이 변경되었으니 변경해주세요.

1번의 요구사항은 `결과 자체를 변경`해달라는 의미입니다.
2번의 요구사항은 `결과의 조건을 변경`해달라는 의미입니다.

`결과 자체를 변경하는 것`과 `결과 조건을 변경`할 때, 동일한 객체`(Result)`가 변경되어야해요.
그렇다면, `단일 책임 원칙에 위배되지 않을까?`하는 생각이었습니다 :)

2024-03-16 03:44 UTC, ddu0422 commented on src/main/java/blackjack/domain/participant/Participant.java
> +    }
죄송합니다. 제가 정신이 없었네요.
`business method > abstract > getter` 가 적절하겠네요 :)

2024-03-16 03:52 UTC, ddu0422 commented on src/main/java/blackjack/domain/participant/Participant.java
> +    }
합리적이지 않다고 생각하시면 반영 안해주셔도 괜찮습니다! :)

2024-03-16 04:17 UTC, ddu0422 requested changes
안녕하세요 콜리! 미르입니다 :)
2단계 미션 잘 구현해주셨네요!
몇 가지 의견을 주고 받고 싶은 부분이 있어 코멘트 남겼습니다~
궁금한 점이 있으시면 언제든지 코멘트 남겨주시거나 DM주세요 😄

2024-03-16 04:17 UTC, ddu0422 commented on src/main/java/blackjack/domain/participant/Dealer.java
> +    }
> hit 여부를 결정하는 과정 또한 다릅니다.

네 충분히 다르다고 생각해요. 

하지만 Controller는 흐름을 제어하는 역할을 하죠.
단순히 `참가자가 뽑을 수 있는지 확인하는 것`이지 않을까요?

`딜러일 때 뽑을 수 있는지 확인한다.`와 `플레이어일 때 뽑을 수 있는지 확인한다.`를 구분해야할까요?

2024-03-16 04:17 UTC, ddu0422 commented on src/main/java/blackjack/domain/participant/Dealer.java
> +    }
> 다형성을 추구하는 기능이 필요하지 않습니다.

플레이어와 딜러가 동일한 기능을 수행하는 것이지 않을까요?
`딜러와 플레이어에서 발생하는 중복 코드를 제거해야 한다.`의 요구사항을 위반한게 아닐까요?

2024-03-16 04:17 UTC, ddu0422 commented on src/main/java/blackjack/domain/gameresult/GameResult.java
> +        return -1 * profitResult.values()
-1은 어떤 의미를 지닐까요?

2024-03-16 04:17 UTC, ddu0422 commented on src/main/java/blackjack/domain/game/Game.java
> +    }
makeGameResult인데 GameResult를 반환하는건 어떨까요?

2024-03-17 06:57 UTC, coli-geonwoo commented on src/main/java/blackjack/domain/gameresult/Result.java
> +    }
예시를 들어주시니 어떤 의도로 리뷰를 주셨는지 확실히 이해했습니다. 저는 결과 자체를 변경하는 것과 결과 조건의 변경이 항상 함께 이루어진다고 생각했는데, 미르의 말처럼 요구사안에 따라 책임을 지닌 클래스를 확인하면 되니 훨씬 직관적이라는 생각도 드네요!

> 배운점1 : 특정 상태에 대한 변경과 상태의 조건에 대한 변경 요구사안은 구분에서 바라볼 필요가 있다
> 배운점2 : 책임의 분할은 단일책임원칙 준수는 물론, 객체간이 협력관계를 구축하는 더 OOP스러운 코드가 된다.

2024-03-17 06:59 UTC, coli-geonwoo commented on src/main/java/blackjack/domain/gameresult/GameResult.java
> +        return -1 * profitResult.values()
매직 넘버네요... 저는 의도를 담아 사용했지만, 그 의도가 전달되지 않을 수 있음을 캐치하지 못했습니다.
상수화를 통해 의미를 담아주겠습니다!

2024-03-17 07:43 UTC, coli-geonwoo commented on src/main/java/blackjack/domain/game/Game.java
> +    }
makeGameResult의 메서드명 자체가 GameResult를 반환해야 더 예측가능한 코드라 부를 수 있을 것 같아요! 반영해주었습니다.

2024-03-17 08:00 UTC, coli-geonwoo commented on src/main/java/blackjack/domain/participant/Dealer.java
> +    }
Controller가 Dealer와 Player를 '참여자'라는 추상대상으로 바라볼 수 있다면 상속관계를 유지하는 게 좋다는 미르의 생각에 동의합니다. 또, canDraw() 처럼 `뽑을 수 있는지 확인`하는 기능은 Dealer와 Player가 동일한 책임을 지니고 있는 것이 맞습니다. 이러한 의견에 동의하기에 다시 상속관계를 롤백해주었습니다.

그러나, **어떠한 이유로 제가 상속관계를 끊어도 된다고 생각했는지** 전달드리고 싶습니다.

> 첫째로, Controller가 Dealer와 Player를 추상화된 대상으로 바라보기가 힘들었습니다.   

 Player는 view를 통해 hit 동의를 얻어야 하기에 view와 Controller 로직에서 두 객체를 추상화된 대상으로 바라보지 못하고, Player는 player라는 사실을, Dealer는 dealer라는 사실을 명확하게 인지한 상태로 로직이 구성되어 있었습니다.

```java
 private static void confirmDealerHands(Dealer dealer, Deck deck) {
        while (dealer.canAddCard()) {
            dealer.addCard(deck.draw());
            OutputView.printDealerDrawMessage();
        }
    }

 private static void askDrawToPlayer(Player player, Deck deck) {
        while (player.canAddCard() && InputView.askDraw(player.getName())) {
            player.addCard(deck.draw());
            OutputView.printParticipantHands(player.getName(), player.getHandsCards());
        }
    }

``` 
이에 `어? 그럼 지금 코드에서 추상화가 크게 필요한가? 불필요한 추상화는 아닌가?`라는 생각이 들었습니다.

> 두번째로 딜러와 플레이어의 드로우 로직은 조금 다른 맥락이라 생각했습니다. 

플레이어의 hit 결정은 'y'라는 동의를 받음으로써 결정되고, 이 동의를 수행할 수 있는 상황을 확인하는 과정에 `버스트가 아님을 확인하는` canDraw() 메서드를 사용했습니다. 이와 달리 딜러는 hit 여부가 강제되어 있고 `16이하라 hit을 해야함을 확인하는` shouldDraw()를 사용했습니다. 

이 두가지 맥락을 canAddCard라는 메서드로 `뽑을 수 있는지 확인한다`라는 기능으로 축약하기에는 딜러는 hit의 가능여부를 확인하는 것이 아닌, **hit을 해야하는지 확인한다**는 미묘한 차이를 담기가 힘들다고 생각했습니다.

2024-03-17 08:11 UTC, coli-geonwoo commented on src/main/java/blackjack/domain/participant/Dealer.java
> +    }
이 부분에 정말 많은 고민이 있었고, 이전 질문에서 미르에게 관련 질문들을 남기기도 하였습니다.

고민끝에 내린 결론은 **addCard / isBust와 같은 메서드는 중복코드라 판단하지 않았습니다.**

그 이유는 다음과 같습니다.
- `중복된 코드`란 같은 기능을 하는 코드가 두개 이상 존재하는 것으로 해석했습니다.
- addCard/isBust는 Participant에게 전해진 메시지를 hands에게 그대로 전달할 뿐, 작성된 로직이 없습니다. 이는  isBust/ addCard등의 기능은 Participant가 담당하는 기능이 아닌 hands가 담당하는 기능이라 생각했습니다.

이 부분이 중복인지 너무 궁금하여 구구 코치와의 데일리 미팅 때에도 관련 주제를 논의한 적이 있습니다. 구구는 멤버변수에게 메시지를 전해주는 코드는 중복코드로 바라보지 않는다는 의견을 주셨고, 리뷰어마다 생각이 다를 수 있다는 의견을 남겨주시기도 하셨습니다.

다시 상속관계로 롤백을 하고보니 단순 메시지를 전달하는 메서드가 Participant 한 곳에 모여 더 깔끔하게 보인다는 장점이 있었으나, hands를 가진 모든 객체가 Participant는 아니듯, hands에게 메시지를 전해주는 기능이 있다고 그것을 재사용하기위한 목적으로 상속관계의 정당성을 이야기하기가 조금 망설여졌습니다.

그렇기에 미르에게 질문드리고 싶습니다.
- 미르는 멤버변수에게 메시지를 전달하는 메서드가 중복이라고 생각하시나요?
- 만약 중복이라 생각하신면, 저는 그것이 Participant로 추상화된 상위 클래스를 만드는 정당한 이유라 생각합니다. 그러나, 중복이 아니라고 생각하신다면, 미르가 생각하시는 is-a 관계로의 상속이 필요하다고 생각하신 이유가 궁금합니다! 🤔

2024-03-17 08:15 UTC, coli-geonwoo commented
안녕하세요 미르! 🙌 

말씀해주신 사안들에 대한 리팩터링 이후, 리뷰요청드립니다.

3차 리팩터링은 큰 변동사안이 많지 않았으나, **다시금 is-a 관계로 Participant 상위 클래스**를 만들어주었습니다. 그러나, 제가 왜 상속관계를 없애려 했는지에 대한 이유를 말씀드리는 것이 좋겠다 판단하였고, 남겨주신 코멘트들에 제 생각을 잘 녹이려 애썼습니다. 

매번 진심어린 리뷰 남겨주심에 감사합니다! 열린질문으로 생각할 여지를 남겨주실 때마다 개인적으로 생각해보지 못했던 부분들까지 더 깊게 고민하게 미르의 질문에 답변을 드리기 위해 노력하고 있어요 😄 

그럼 3차 리뷰 개선사안 전달드립니다.

### 3차 리뷰 개선사안

- 상속관계인 Participant 추상 클래스 롤백
- Game: makeGameResult 메서드에서 GameResult를 생성
- GameResult : getDelaerProfit 메서드를 Profit.reverse()와의 협력으로 구현

2024-03-17 12:08 UTC, ddu0422 commented on src/main/java/blackjack/domain/participant/Dealer.java
> +    }
저는 멤버 변수를 바라보는 관점이 아닌, 행동을 관점으로 바라봅니다.

1. 외부에서 바라볼 때, 단순히 멤버 변수에게 전달하는지 하지 않는지 알 필요가 없다고 생각해요.
2. 행동 관점에서 딜러, 플레이어 둘 다 `draw를 할 수 있다`는 행동을 할 수 있고, `손 패를 공개한다`는 행동도 할 수 있다고 생각해요.

그렇기 때문에 is-a 관계로 바라봐야한다고 생각해요.
저 또한 상속을 선호하지는 않습니다만(상속보단 조합을 사용) 상속이 필요할 때는 상속을 진행해야한다고 생각합니다.

2024-03-17 14:10 UTC, coli-geonwoo commented on src/main/java/blackjack/domain/participant/Dealer.java
> +    }
최근 책 <객체지향의 사실과 오해>를 읽으며, 구현과 인터페이스를 분리하라! 라는 문장이 기억에 남았는데 미르의 코멘트가 그 문장을 기억나게 했어요!

블랙잭 게임에 대한 객체 협력 공동체에서 딜러와 플레이어의 내부구현이 아닌 역할과 책임에 있어서 ,  draw, 손패 공개와 같은 **역할**은 같은 메시지를 각자의 방식으로 처리할 책임을 의미하네요!

무의식적으로 의존관계 = 나쁜것 이라는 생각이 자리잡혔고,우리가 추구해야할 건 무결합이 아닌 가능한 느슨한 결합이라는 사실을 되뇌입니다!

추가로, 저도 미르의 코멘트가 합리적이라 판단되어 is-a 관계로 다시 롤백 해주었습니다!😀

2024-03-18 09:01 UTC, ddu0422 approved these changes
안녕하세요 콜리! 미르입니다 :)
블랙잭 미션 하시느라 고생 많으셨어요!
즐거운 의논을 주고 받았네요 ㅎ_ㅎ
다음 미션도 화이팅이예요 😄

2024-03-18 09:03 UTC, merged