[2단계 - 블랙잭 베팅] 아루(이동훈) 미션 제출합니다.
woowacourse/java-blackjack pull request #682
Opened 2024-03-12 12:09 UTC by donghoony

안녕하세요 조앤! 2단계로 돌아왔습니다 😎

주말동안 도메인을 어떻게 하면 좋을지... 고민을 많이 했습니다. 필드 두 개라는 제한사항을 지키려다 보니 꽤나 깊게 생각한 것 같기도 하고요. 돈을 어떻게 처리할지를 생각하다 보니 금방 주말이 지나갔습니다 🏃‍♀️

사용자의 베팅 정보가 추가됐을 뿐이었지만, 전체적인 구조가 바뀌었습니다. 간단하게 설명드릴게요!

### 사소한 변화
초반 커밋들은 오타와 리팩터링 중심으로 이루어져 있습니다. `isBust`라고 써야 할 것을 `isBurst`라고 썼다던가... 도메인 용어가 생소해서 그랬던 것 같네요 😅

이후에 점수를 `Score`로 뽑으면서 +10점 해주는 로직도 이쪽으로 옮겨왔습니다.

### 플레이어의 현재 상태를 추상화
오토마타의 DFA처럼, 현재 상태를 추상화하고 행동에 따라 상태가 전이되는 것을 표현하고자 했습니다. 이렇게 표현하니 말단 상태 (더 이상 뽑을 수 없는 상태)에서 상대방의 상태와 비교해 `if-else`를 줄일 수 있는 파격적인 효과를 볼 수 있었어요. 기존 `MatchResult` enum에서 계산하던 것이 각 말단 상태로 이동했습니다.

이렇게 하니 딜러와 플레이어의 상태를 나눌 수 있을 것이라고 판단했고, 그렇게 되니 상속 관계가 무의미해져 딜러와 플레이어를 더이상 나누지 않게 되었어요. 그래서 중간에 `Player`를 `Participant`로 변경했지만, 뭔가 와닿지 않아 다시 `Player`로 돌려 두었습니다. 혹시라도 혼동이 오셨다면 미리 사과드립니다 😶

나아가 이번 요구사항에서 추가된 BetMoney와 유기적인가..? 라고 보기에는 어렵다고 느껴집니다. 따로 게임 흐름에서 돈을 관리하고, 매번 플레이어에게 물어보는 게 조금 어색해 보였어요. 응집도가 조금 떨어지는 것 같았습니다.

테스트를 먼저 짜내면서 코드를 옮겨나가는 게 참 어려웠습니다... 😭 그만큼 허점도 많이 보일 것 같지만, 여러 질문들을 통해서 개선해나가보고 싶네요.

"이 작업은 이쪽 클래스에서 하는 것이 적당한지"에 대한 코멘트가 필요합니다. 메서드나 행동의 응집도를 위주로 봐주시면 감사하겠습니다, 이번에도 잘 부탁드립니다 😊

2024-03-12 14:11 UTC, seovalue requested changes
안녕하세요, 아루! 2단계 미션 빠르게 진행해주셨네요.
몇가지 코멘트 남겨뒀는데 확인 후 다시 리뷰 요청 주세요~

2024-03-12 14:11 UTC, seovalue commented on src/main/java/blackjack/game/BlackJackGame.java
>          }
<img width="609" alt="Screenshot 2024-03-12 at 23 03 45" src="https://github.com/woowacourse/java-blackjack/assets/48412963/18f823b8-3d6f-430b-9343-06d19d9f82b7">

dealer는 16이하라 한 장의 카드를 더 받았습니다 는 한번만 출력되어야할 것 같아요.

2024-03-12 14:11 UTC, seovalue commented on src/main/java/blackjack/player/Score.java
> +    public static Score zero() {
👍

2024-03-12 14:11 UTC, seovalue commented on src/main/java/blackjack/player/Score.java
> +    public Score add(int other) {
이 메서드는 private으로 바꾸고 외부에서 Score와 합산을 원할 땐 항상 아래 Score를 받는 add를 호출하도록 해도 될 것 같아요.

2024-03-12 14:11 UTC, seovalue commented on src/test/java/blackjack/player/ScoreTest.java
> +    @DisplayName("에이스 추가 점수를 받아 21점이 초과된다면, 추가 점수를 반영하지 않는다.")
👍

2024-03-12 14:11 UTC, seovalue commented on src/main/java/blackjack/player/state/GameState.java
> +public abstract class GameState {
GameState에는 블랙잭의 룰과 관련이 있는 BlackJackState.. 등과 아예 유저와 관련있는 Dealer/PlayerState가 공존하는 것 같아요. 그래서 추가로 코멘트도 남겨뒀지만 GameState의 정확한 의미를 어떤 것으로 생각하셨는지가 궁금하네요~

2024-03-13 01:44 UTC, donghoony commented on src/main/java/blackjack/game/BlackJackGame.java
>          }
딜러는 16 이하인 동안 계속해서 카드를 받습니다! `문서에도 17 이상이 되어야 스탠드로 전이한다`라고 적어 뒀는데, 조금 비약했을까요 😶

2024-03-13 01:51 UTC, donghoony commented on src/main/java/blackjack/game/MatchResults.java
> +        int betAmount = playerBet.betMoney().getAmount();
어차피 불변이니 내부를 이런 식으로 공개해도 되겠네요. 어떻게 보면 메시지를 던져서 가져오는 게 되겠습니다 🤩

2024-03-13 02:08 UTC, donghoony commented on src/main/java/blackjack/player/Hand.java
> +    public boolean isBlackJack() {
`Hand`가 `State` 아래로 옮겨가면서, `State`에서 `Hand`에게 블랙잭 여부를 묻습니다. 여전히 책임은 `Hand`에게 있다고 생각하는데, 처음 요청을 받게 되는 객체가 책임을 가지는 것은 아니라고 생각했습니다.

2024-03-13 02:10 UTC, donghoony commented on src/main/java/blackjack/game/BlackJackGame.java
> +    private MatchResults createMatchResults(Player dealer, Players players) {
놓친 부분이네요..! 👀

2024-03-13 02:21 UTC, donghoony commented on src/main/java/blackjack/player/state/GameState.java
> +    }
플레이어의 상태가 들어옴에 따라, 자신의 현재 상태에 따른 드로우 여부를 결정하게 됩니다. `State`가 직접 패에 카드를 추가해주면서 플레이어의 상태를 다음 상태로 바꿔 주고, 드로우할 수 없다면 드로우할 수 없는 상태로 만들어 줍니다 (Stand를 했다면 PlayerState -> StandState, 버스트라면 BustedState로요!)

물론 카드를 뽑는 것 자체는 직관적으로 플레이어의 영역이라고 생각되지만, 아래에 플레이어의 상태를 가지도록 하는 객체를 추가해 이쪽으로 책임을 위임하게 되었어요. `State`가 많은 일을 하고 있는 것처럼 보이는 것일까요?

2024-03-13 02:24 UTC, donghoony commented on src/main/java/blackjack/player/Hand.java
> +    public boolean isBlackJack() {
블랙잭과 버스트 여부는 손패의 개수와 총 점수에도 영향을 미치므로 `Hand`가 가져갑니다. `GameState`는 이를 가져다가 다음 상태로 전이하는 데 사용됩니다.
위에서도 말씀드렸지만 직관과는 거리가 조금 있어 보이지만, 개인적으로 책임을 아래로 내려 상태를 바꿔나가는 것이 어색하다고 느껴지지는 않았어요.

사실 이런 방식으로 리팩터링을 진행하면서 상태를 넣지 않고 돈만 넣는 방식으로 진행했다면..? 이라는 생각도 하는데... 그러는 편이 나았을까요? 🤔 다양한 고민을 할 수 있어 좋았지만 결국 PR로 보여지는 것은 리뷰어분들에게 부담이라 고민이네요..!

2024-03-13 02:27 UTC, donghoony commented on src/main/java/blackjack/game/BlackJackGame.java
> +        int dealerProfit = playersProfit * -1;
`MatchResults`라는 일급 컬렉션을 넘겨서 내부에서 계산하도록 하면 응집도가 떨어지는 것 같아 고민을 했던 부분입니다. 우선적으로는 게임 흐름에 이런 로직이 있는 게 더 어색해 보이네요. 안으로 넣어두겠습니다 🙂

`MatchResults`를 받아서 이를 활용하도록 하는 것이 자연스러워 보이나요?
```java
public int calculateDealerProfit(MatchResults matchResults) {
    int playersProfit = playerBets.values()
            .stream()
            .mapToInt(matchResults::calculateProfitByBet)
            .sum();
    return playersProfit * -1;
}
```

2024-03-13 02:41 UTC, donghoony commented on src/main/java/blackjack/player/Score.java
> +    public Score add(int other) {
생성하는 방식을 `new`가 아닌 `of`로 생성하도록 합니다. 해당 메서드를 삭제하고 아래와 같이 작성하니 깔끔하네요!
```java
    public Score addAceScoreOnNotBust() {
        if (value + ADDITIONAL_ACE_SCORE <= BLACKJACK_SCORE) {
            return this.add(Score.of(ADDITIONAL_ACE_SCORE));
        }
        return this;
    }
```

2024-03-13 02:50 UTC, donghoony commented on src/main/java/blackjack/player/state/GameState.java
> +public abstract class GameState {
위에서 조금 설명했는데, 이해가 어렵거나 함께 이야기하고 싶으면 추가적으로 코멘트나 DM 부탁드립니다..! 고맙습니다 😊

2024-03-13 03:06 UTC, donghoony commented
안녕하세요 조앤! 꼼꼼하게 봐 주셔서 고맙습니다 😎

아직도 메서드가 필요한 파라미터만 받는 것인지에 대해서 고민이 많아요. 예를 들어, 매치 결과를 추가하는 과정에서
```java
    public void addResult(String playerName, Player player, Player dealer) {
        MatchResult result = player.matchResultVersus(dealer);
        results.put(playerName, result);
    }
```
와 같이 플레이어 자체를 받아서, 플레이어의 매치 정보를 넣어주는 식인데 이게 너무 과한 의존인 것 같고, 응집도도 떨어지는 느낌을 받습니다. 그래서 아래와 같이 변경하게 되었어요. 이는 좋은 리팩터링이라고 생각합니다.
```java
    public void addResult(String playerName, MatchResult result) {
        results.put(playerName, result);
    }
```
같은 느낌으로, 딜러의 수익을 계산하는 과정에서도 아래와 같이 전체 `MatchResults`를 받아오는데, 이를 객체를 받아오는 느낌이라고 봐야 할지, 일종의 컬렉션을 넘기는 느낌이라고 봐야 할지 고민이 되네요. 아래와 같은 코드는 테스트도 어려워지는 느낌이라 망설여집니다. 사실 하나의 일급 컬렉션을 넘기는 거라 괜찮다고 생각이 들면서도, 너무 큰 단위를 넘기는 것 같아 동시에 어색하네요 😮

```java
// PlayerBets.java
    public int calculateDealerProfit(MatchResults matchResults) {
        int playersProfit = playerBets.values()
                .stream()
                .mapToInt(matchResults::calculateProfitByBet)
                .sum();
        return playersProfit * -1;
    }
```

`State`와 관련된 이야기도 답글로 달아 두었습니다. 위에 레이어가 추가됐다고 해서 자신의 책임이 희석(?)되는 것인지 궁금해요. 아직 시간이 많아 추가적으로 리뷰를 받아보면서 나눠보고 싶습니다. 고맙습니다 😁

2024-03-13 13:47 UTC, seovalue commented on src/main/java/blackjack/player/state/terminated/BlackJackState.java
> +package blackjack.player.state.terminated;
넵 근데 정확히 아루가 패키지를 나누는 일관된 기준이 궁금했어요. 어떤 경우는 도메인 단위, 어떤 경우는 행위 단위인 것 같아서요.

2024-03-13 13:59 UTC, seovalue commented on src/main/java/blackjack/game/BlackJackGame.java
>          }
아 넵넵! 근데 출력을 굳이 세번할 필요가 있을까 생각이 들었는데, 어차피 실제 게임을 한다고 했을 때에도 3번을 받는 게 보여지겠죠..?(실제로 안해봐서 모르겠네요..ㅎㅎ) 그럼 문제없을 것 같아요!!

2024-03-13 14:02 UTC, seovalue commented on src/main/java/blackjack/player/state/GameState.java
> +    }
넵넵 State가 서로 다른 두 가지의 일을 하고 있다고 느껴져요. 게임의 실제 상태(블랙잭, 버스트 등등)와 플레이어의 역할 두 가지요!!

2024-03-13 14:03 UTC, seovalue commented on src/main/java/blackjack/player/Hand.java
> +    public boolean isBlackJack() {
위에도 비슷한데 제가 아루의 코드를 읽으면서 헷갈리는 부분은 GameState를 정확히 한 마디로 설명할 수 없기 때문에 헷갈리는 것 같아요ㅎㅎ 역할만 명확해진다면 책임을 아래로 내리는 것이랑은 무관하게 해결될 것 같아요.

2024-03-13 14:03 UTC, seovalue requested changes
아루~ 남겨주신 질문에 대해 코멘트 남겼어요!
조금 더 수정해주신다고 하셔서 이야기 나눈 내용대로 Request Changes 남길게요ㅎㅎ 
리팩터링 후 다시 리뷰 요청 주세요!

2024-03-14 07:05 UTC, donghoony commented
안녕하세요 조앤! 과감한 부탁이었지만 선뜻 받아주셔서 고맙습니다 🏃‍♂️
확실히 이전 리뷰를 읽으면서 플레이어 자체가 상태에 들어간 것 같은 느낌을 지우지 못해 상태를 밖으로 뽑아내려고 했고, `Hand`가 없는 상태는 무엇일까? 를 고민한 끝에, 게임을 끝낸 최종 상태를 각각 클래스화해 모든 경우의 수를 따져보기로 했습니다.

다시 구현하며 들었던 생각은 각 코드 코멘트로 추가하겠습니다. 잘 부탁드립니다 😊

2024-03-14 07:30 UTC, donghoony commented on src/main/java/blackjack/player/Player.java
> +public abstract class Player {
`Player`는 이제 추상 클래스입니다. 지금까지 고려 가능한 선택지가 네 가지 있었는데요.
1. 추상 클래스
2. 상속
3. 별도의 클래스
4. 인터페이스를 통한 구현입니다. 

3은 코드 중복을 피할 수 없어 요구사항에 맞추기 어려웠어요.
상속에서 추상 클래스로 옮겨온 데에는, `Player`가 가지고 있었던 고유의 메서드를 상속받으면서 오버라이딩을 하게 되면 상속을 하게 되는 의미가 없게 된다고 보았어요. 이를 확실하게 명시하려면 추상 클래스를 사용해야겠다 싶었습니다!

2024-03-14 07:30 UTC, donghoony commented on src/main/java/blackjack/money/BetMoney.java
> +public class BetMoney extends Money {
사용자의 입력을 검증하기 위해서 상속을 사용해 구현했습니다. 입력받을 때에는 `BetMoney`를 통해 진행하지만, 이후 수익을 계산할 때에는 `Money`를 활용합니다.

2024-03-14 07:30 UTC, donghoony commented on src/main/java/blackjack/resultstate/ResultState.java
> +public interface ResultState {
상태를 가볍게 하면 상태를 사용하는 의미가 없고, 상태를 사용하지 않으면 승리 판정 시에 `if`가 상당히 많아져 인지적 부담이 꽤 되었습니다.

이제 `Hand`를 가지지 않고, **게임이 종료되었을 때, 플레이어와 딜러의 상태**를 정의합니다. 각 상태는 `Stand`, `Bust`, `BlackJack` 세 가지이고 각 세 가지의 조합을 따져 승패를 가리게 됩니다.

`ResultState`의 `isCapableWith`는 두 플레이어가 현재 이 상태인지를 알아냅니다. 이는 심판 역할인 `Referee`에서 진행합니다.

2024-03-14 07:30 UTC, donghoony commented on src/main/java/blackjack/player/Player.java
> +public abstract class Player {
하지만 이후에 `Game`에서 사용할 때, `Player`로 명시해야 할지, `Participant`으로 사용해야 할지 고민이 되었습니다. 결국 같은 행동을 하니 `Player`로 사용해야 할 것 같지만, 일관성과 가독성을 위해 `Participant`, `Dealer`로 구체적으로 적었습니다.

2024-03-14 12:38 UTC, seovalue approved these changes
안녕하세요, 아루! 
리팩터링 잘 수행해주셨네요ㅎㅎ 전체적으로 가독성도 좋아지고 책임도 명확해진 것 같아요.
요구사항은 진작 만족해주셨어서 이번엔 바로 머지할게요!
몇가지 소소한 코멘트 남겼는데 천천히 확인해주세요~

2024-03-14 12:38 UTC, seovalue commented on README.md
> +- [ ] 두 장만으로 21점을 만들면 블랙잭이며, 배팅 금액의 1.5배를 가져간다.
완료한 내역 체크해주세요~

2024-03-14 12:38 UTC, seovalue commented on src/main/java/blackjack/game/BlackJackGame.java
> +        Participants participants = createParticipants();
전체적으로 코드가 직관적으로 읽기 좋아졌다는 생각이 들어요. 많은 고민을 하시고 그것을 코드에 반영하신 것 같아요 👍

2024-03-14 12:38 UTC, seovalue commented on src/main/java/blackjack/player/Dealer.java
> +        super(DEALER_NAME);
👍

2024-03-14 12:38 UTC, seovalue commented on src/main/java/blackjack/player/Hand.java
> +        if (hasAceInCards) {
👍

2024-03-14 12:38 UTC, seovalue commented on src/main/java/blackjack/player/Player.java
> +public abstract class Player {
저는 Participant로 명명한 것도 말씀주신 것처럼 가독성 측면에 있어서 잘 이해되는 것 같아요.

2024-03-14 12:38 UTC, merged