[2단계 - 블랙잭] 초코칩(권기호) 미션 제출합니다.
woowacourse/java-blackjack pull request #685
Opened 2024-03-13 06:24 UTC by Chocochip101

# 블랙잭
안녕하세요, 아서. 6기 백엔드 초코칩입니다. Step1에 이어서 배팅 기능이 더해진 블랙잭을 구현했습니다. 

## 부탁
### [커뮤니케이션 비용을 줄이기 위한 Pn 룰](https://blog.banksalad.com/tech/banksalad-code-review-culture/)
PR 내용을 보시기 전에 저와 리뷰어님의 커뮤니케이션 비용을 줄이기 위해 Pn 룰을 부탁드리고 싶습니다. Pn룰을 통해 리뷰어님이 저에게 꼭 고쳤으면 하는 리뷰와 그렇지 않은 리뷰를 범위로 나누어 더욱 전달이 효과적으로 이루어질 것 같습니다. 

- [P1]: 꼭 반영해주세요 (Request changes)
- [P2]: 적극적으로 고려해주세요 (Request changes)
- [P3]: 웬만하면 반영해 주세요 (Comment)
- [P4]: 반영해도 좋고 넘어가도 좋습니다 (Approve)
- [P5]: 그냥 사소한 의견입니다 (Approve)
- [질문]: 의견에 대한 질문입니다. (Question)

## 기능 목록 (step2)

### 입출력

- [x] 사용자의 배팅 금액을 입력받는다.
- [x] 사용자의 최종 수익을 출력한다.

### 배팅

- [x] 플레이어는 게임을 시작할 때 배팅 금액을 정해야 한다.
- [x] 배팅 금액에 대해 예외처리한다.
- [x] 카드를 추가로 뽑아 21을 초과할 경우 배팅 금액을 모두 잃게 된다.
- [x] 플레이어가 이길 경우 **배팅한 금액의 2배**를 받는다
- [x] 두 장의 카드 합이 21일 경우 블랙잭이 되면 **승리 금액과 베팅 금액의 1.5 배**를 딜러에게 받는다.
- [x] 딜러와 플레이어가 모두 동시에 블랙잭인 경우 플레이어는 베팅한 금액을 돌려받는다.
- [x] `BlackJackGame`에서 객체한테 역할을 전달하는 방식으로 구현한다.
- [x] 무승부일 경우, 그대로 돌려받는다.
- [x] 배팅 최소 금액을 설정한다.

### 수익

- [x] 딜러의 수익을 출력한다.
- [x] 플레이어의 수익을 출력한다.
- [x] 수익은 배팅 금액에서 제외한다.

## 이전 리뷰
> 게임 로직 관리 중에서 Player가 카드를 계속 받을지 말지 결정하는 로직 을 제외하고는 별도의 객체 안에서 관리되어지는게 어떨까 싶습니다.

`BlackjackGame` 클래스의 생성 로직을 분리하기 위해 다른 클래스가 아닌 `Dealer`와 `Player` 클래스로 옮겼습니다. 이로 인해 `BlackjackGame` 클래스의 책임이 줄어들고 `Dealer`, `Player` 클래스의 응집도가 높아진 것 같습니다. 게다가 아래 코드와 같이 함수형 인터페이스를 이용해 표현하니 행위에 더 집중할 수 있었던 것 같습니다.

```java
players.initialDeal(dealer::draw); 

public void initialDeal(final Supplier<Card> supplier) {  
    IntStream.range(0, BLACKJACK_INIT_CARD_AMOUNT)  
            .forEach(i -> players  
                    .forEach(player -> player.draw(supplier.get())));  
}
```

## 질문
- 페어프로그래밍 중에는 몰랐는데, 메서드의 인자를 넘겨주는 순서가 제각각인 것을 확인해서 수정했습니다. 혹시 자바로 이러한 컨벤션을 맞추시는지 궁금합니다.

```java
private void initializeGame(final Dealer dealer, final Players players) {};
private void printCardDistribute( final Players players, final Dealer dealer) {};
```
- 메서드 순서 컨벤션에 대해서 저는 아래와 같이 작성하는데, 아서의 생각이 궁금합니다.

1. 클래스 정적 상수
2. 인스턴스 변수 
3. 생성자 
4. (필요할 경우) 정적 팩터리 메서드
5. 일반 메서드 (호출 순서대로)
6. (필요할 경우) 오버라이드 메서드
7. getter, setter
8. equals, hashcode, toString 메서드

감사합니다.

2024-03-14 12:13 UTC, Hyunta requested changes
안녕하세요 초코칩,
1단계 미션을 잘 구현해주셔서 코드의 큰 변화 없이 2단계 요구사항도 잘 반영해주셨네요.
몇가지 커멘트 남겼는데 확인 부탁드립니다!
고생하셨습니다👍🏻

2024-03-14 12:13 UTC, Hyunta commented on src/main/java/blackjack/dto/PlayerProfit.java
> +}
[P2]
DTO로 사용하기엔 네이밍이 도메인인 Profit과 너무 유사하네요 충분히 착각할 수 있겠어요.

2024-03-14 12:13 UTC, Hyunta commented on src/main/java/blackjack/domain/participant/Profit.java
> +public class Profit {
[P5]
Judge는 승패 계산 + Result 반환,
Profit은 수익 계산 하는 역할로 쪼개신 것 같은데
Judge에서 PlayerProfit을 반환을 해야해서 Profit 로직까지 영향을 주다보니 Judge의 역할이 커진 것 같네요.
Judge에서는 승패 계산만 하도록 바꾸면 어떨까 싶은데 어떻게 생각하시나요?

2024-03-14 12:20 UTC, Hyunta commented
> 페어프로그래밍 중에는 몰랐는데, 메서드의 인자를 넘겨주는 순서가 제각각인 것을 확인해서 수정했습니다. 혹시 자바로 이러한 컨벤션을 맞추시는지 궁금합니다.

저는 최대한 맞추려고 합니다. 그런데 팀 내에서 컨벤션이 따로 있지는 않아요.
정말 중요한 부분은 아니라고 생각하는데, 가독성이 조금이라도 나아지는 것 같아서 하나의 PR에서 공통된 인자를 받으면 순서를 유지하려고 노력합니다. 그런데 코드 리뷰할 때 그 부분이 다르다고 커멘트를 남기지는 않을 것 같아요ㅋㅋ 딱 그정도 수준만 지키는 것 같습니다.

> 메서드 순서 컨벤션에 대해서 저는 아래와 같이 작성하는데, 아서의 생각이 궁금합니다.
클래스 정적 상수
인스턴스 변수
생성자
(필요할 경우) 정적 팩터리 메서드
일반 메서드 (호출 순서대로)
(필요할 경우) 오버라이드 메서드
getter, setter
equals, hashcode, toString 메서드

저도 초코칩이 작성해주신 순서대로 사용하는 것 같네요ㅎㅎ
추가로 이런 고민도 해보세요
만약에 생성자가 여러개 있으면 어떤 순서로 배치하실 건가요?
인자가 많은 것부터 나열해서 적은 순으로 내려갈 것 인지,
인자가 적은 것부터 나열해서 많은 순으로 올라갈 것인지?

```java
public class Person {
    private String name;
    private Integer age;

    public Person(String name, Integer age) {
        this.name = name;
        this.age = age;
    }

    public Person(String name) {
        this.name = name;
    }

    public Person(Integer age) {
        this.age = age;
    }

    public Person() {
    }
}
```

```java
public class Person {
    private String name;
    private Integer age;

    public Person() {
    }
    
    public Person(String name) {
        this.name = name;
    }

    public Person(Integer age) {
        this.age = age;
    }

    public Person(String name, Integer age) {
        this.name = name;
        this.age = age;
    }
}

```

2024-03-15 02:55 UTC, Chocochip101 commented on src/main/java/blackjack/dto/PlayerProfit.java
> +}
PlayerProfit을 구분하기 위해 PlayerProfitResult로 변경했습니다.

2024-03-15 05:24 UTC, Chocochip101 commented on README.md
> +## 기능 목록 (step2)
> a,aa의 수익이 합 11,000원이면 딜러의 수익은 -11,000이 되어야 하지 않나요?

저의 수학 계산 미스로 잘못 계산했습니다... 🫠

> 이름이 문제였다면 베팅 금액 받기전에 알려주면 안되나요?
중복인 이름도 미리 알려주면 안되나요?

이름에 문제가 있을 경우, 배팅 금액을 입력하기 전에 예외를 던지게 했습니다. 이름의 예외를 `Player`에서, 중복 처리를 `InputView`에서 처리하려 했습니다. 하지만 `Player` 클래스의 책임이 커진다고 생각해 `Name` 클래스에 구현했습니다. 또한 중복 처리 게임 로직과 가깝다고 판단하여 `NamesInput` dto 클래스에서 검증하게 했습니다.

2024-03-15 05:29 UTC, Chocochip101 commented on src/main/java/blackjack/BlackjackGame.java
> +        Players players = createPlayers();
> Dealer는 create, Players는 of 로 정적 팩토리 메서드 이름을 다르게 지어준 이유가 있을까요?

정적 팩터리 메서드의 의미를 부여하고자 했습니다. 하지만 [이팩티브 자바]에서 정적 팩터리의 관습적인 명명 방식이 있는 것을 확인하여 create를 from으로 수정했습니다.

[정리 Link](https://velog.io/@chocochip/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C-%EC%9E%90%EB%B0%94-1.-%EC%83%9D%EC%84%B1%EC%9E%90-%EB%8C%80%EC%8B%A0-%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%84%B0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C%EB%A5%BC-%EA%B3%A0%EB%A0%A4%ED%95%98%EB%9D%BC-ojonzwfn#%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%84%B0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C%EB%A5%BC-%EC%9E%91%EC%84%B1%ED%95%98%EB%8A%94-%EC%8B%9C%EC%A0%90%EC%97%90%EB%8A%94-%EB%B0%98%ED%99%98%ED%95%A0-%EA%B0%9D%EC%B2%B4%EC%9D%98-%ED%81%B4%EB%9E%98%EC%8A%A4%EA%B0%80-%EC%A1%B4%EC%9E%AC%ED%95%98%EC%A7%80-%EC%95%8A%EC%95%84%EB%8F%84-%EB%90%9C%EB%8B%A4)

2024-03-15 10:01 UTC, Chocochip101 commented on src/main/java/blackjack/domain/Judge.java
>      }
`Judge` 클래스를 util 클래스의 느낌으로 사용하기 위해 인스턴스화를 막았습니다.

아래 세 가지 방식 중 하나를 골라야 합니다.

```java
// #1
Judge.judge(dealer, player);

// #2
new Judge(dealer, player).judge();

// #3
new Judge( ).judge(dealer, player);
```
2번의 경우에는 `Judge` 클래스가 굳이 인스턴스 변수로 dealer와 player를 알아야 할까 라는 생각이 들었고, 불필요하다고 생각했습니다. 또한 3번의 경우에는 1번의 방식과 비교해서 new 연산자만 추가될 형태이니 굳이 붙여야하나라는 생각이 들었고, util 클래스로 분리했습니다.

하지만 막상 사용해보니 여러 메서드의 집합도 아닐뿐더러, util로서의 재사용성이 많이 떨어져보입니다. 또한 static으로의 처리가 전역함수를 사용하는 효과처럼 보이기도 했습니다. 따라서 인스턴스로 생성하여 사용하는 것으로 변경했으며, 굳이 인스턴스 변수를 가질 필요가 없어 3번 방법을 선택했습니다.

2024-03-15 10:08 UTC, Chocochip101 commented on src/main/java/blackjack/domain/participant/Profit.java
> +public class Profit {
말씀해주신걸 들어보니 Judge에 많은 역할이 있는 것 같아 분리했습니다.

2024-03-15 10:21 UTC, Chocochip101 commented on src/main/java/blackjack/domain/Judge.java
> +    public static BlackjackResult judge(final Dealer dealer, final Players players) {
Judge의 '판단하다'라는 의미로는 파악하기 힘들어, 클래스명과 메서드명을 수정해 `Referee().determinePlayersResult`로 수정했습니다.

2024-03-15 10:22 UTC, Chocochip101 commented on src/main/java/blackjack/domain/Judge.java
> +    private static PlayerProfit judge(final Dealer dealer, final Player player) {
각 사용자에 대한 게임 결과를 판단하는 함수이기에 `determinePlayerResult()`로 변경했습니다.

2024-03-17 03:47 UTC, Chocochip101 commented
> 만약에 생성자가 여러개 있으면 어떤 순서로 배치하실 건가요?
인자가 많은 것부터 나열해서 적은 순으로 내려갈 것 인지,
인자가 적은 것부터 나열해서 많은 순으로 올라갈 것인지?

보기가 두 개만 존재한다면, **인자가 적은 순**으로 배치할 것 같습니다. 코드를 읽는 사람이 왼쪽부터 인자가 적은 생성자부터 읽게 되므로, 이해하기 쉬울 것 같습니다. 

하지만 `Person` 클래스와 같이 여러 형태의 생성자를 호출해야 된다면, Boilerplate 코드 때문에 양이 많아질 수 있다고 생각합니다. 매개변수(필드)의 개수에 따라 Builder를 고려할 것 같습니다.

2024-03-17 13:27 UTC, Hyunta commented on README.md
> +## 기능 목록 (step2)
DTO의 역할이 무엇인가요? DTO에서 중복 검증을 하는 것이 적절한가요?
기획이 수정되어 `중복된 이름도 허용해주세요` 라고 했을때,
다른 개발자가 초코칩의 코드를 읽고 DTO에 중복 검증 로직이 있구나 파악하는데 시간이 오래걸릴 것 같아요.

_미션을 진행하면서 DTO를 데이터 전달의 목적 이외의 용도로는 일절 사용하지 말아주세요._

---

> 하지만 Player 클래스의 책임이 커진다고 생각해 Name 클래스에 구현했습니다. 

Player에서 Name의 예외을 아는게 책임이 커진다고 판단하셔서 분리했다고 이해했습니다, 타당한 이유라고 생각됩니다.
개인적으로 Player의 클래스는 현재 규모에서 책임을 많이 가진다고 생각들지는 않아서, 이름에 대한 검증까지 이뤄져도 유지보수에 큰 문제는 없을 것 같습니다.

2024-03-17 13:28 UTC, Hyunta commented on src/main/java/blackjack/BlackjackGame.java
> +        Players players = createPlayers();
정리까지 아주 좋습니다👍🏻

2024-03-17 13:33 UTC, Hyunta commented on src/main/java/blackjack/domain/Judge.java
>      }
초코칩이 정리해주신 것처럼 해당 문제는 약간 취향의 영역인가 싶기도 합니다.
정답은 없지만, 왜 선택했는지에 대한 근거만 있으면 충분히 합리적으로 보여집니다.
개인적으로 3번처럼 해결할 수 있는 문제라면 웬만하면 인스턴스화해서 해결하는 것을 선호하는 것 같습니다.
누가봐도 너무 Util스러운 것들은 제외하구요(eg. StringUtils, DateTimeUtils 등)

2024-03-17 13:43 UTC, Hyunta approved these changes
안녕하세요 초코칩,
2단계 피드백 반영도 잘 해주셨네요ㅎㅎ
객체의 역할을 적절히 분리하고, 네이밍도 잘 바꿔주셔서 이전보다 읽기 쉬워진 것 같습니다.
DTO 관련해서 커멘트 남겼는데 확인해주시고, 더 이야기를 하고 싶으시면 언제든지 DM 주세요!
저와 나눴던 대화들이 도움이 됐으면 좋겠네요.
 남은 미션도 응원하겠습니다!

2024-03-17 13:43 UTC, merged