[2단계 - 블랙잭 베팅] 테니(나아연) 미션 제출합니다.
woowacourse/java-blackjack pull request #686
Opened 2024-03-13 08:44 UTC by ay-eonii

안녕하세요 조앤!☺️ 테니입니다
2단계 미션을 진행하면서 고민한 부분을 아래에 정리했습니다. 2단계 리뷰 잘 부탁드립니다!

### 1. 예외처리
```java
public String getFirstCard() {
    if (cards.isEmpty()) {
        throw new UnsupportedOperationException("카드가 없습니다.");
    }
    return cards.get(0).toString();
}
```
이전 리뷰에서 cards가 empty인 경우를 짚어주셨는데, cards 생성자에서 사이즈가 2인지 유효성검사를 진행하고 있습니다. 추가적으로 List<Card>의 원소를 감소시키는 하는 메서드는 존재하지 않습니다. 즉, List<Card>는 항상 2이상으로 유지하는 것을 보장한다고 생각합니다. 
하지만 위 내용은 내부 사정이라 외부에서는 알지 못하고 `getFirstCard()`를 호출할 수 있다는 점은 이해했습니다. 그렇다면 예외처리를 어디까지 해야할까요? 현재로서는 카드가 없다면 예외를 던지기만 합니다.
```java
try {
    outputView.printInitialCards(dealerCards, playerCardsBundle);
} catch (UnsupportedOperationException e) {
    outputView.printError(e.getMessage());
    return;
}
```
Casino에서 위 처럼 예외메시지를 출력하고 정상종료하도록 하는 로직이 필수일까요? 이 외에도 도메인에서 발생할 수 있는 모든 예외가 Controller 역할을 하는 Casino를 거쳐 Casino가 너무 무거워지는 게 아닌지 걱정됩니다. 조앤의 의견이 궁금합니다!🥺

---

### 2 comparable 사용
```java
public Status decidePlayerStatus(int dealerSum, PlayerCards playerCards) {
    if (dealerSum < playerCards.bestSum()) {
        return Status.WIN;
    }
    if (dealerSum > playerCards.bestSum()) {
        return Status.LOSE;
    }
    return Status.TIE;
}
```
위는 Rule 도메인의 decidePlayerStatus 메서드입니다. 위 로직에서 카드의 합을 비교해서 승,무,패를 결정하는데 각자의 합을 비교하는 것은 Cards에서도 가능하다고 생각합니다. 
그래서 Cards에 Comparable을 아래와 같은 방식을 고민했습니다. Override하는 것은 해당 메서드의 내용과 적합하게 구현을 하는 것이 중요하다고 알고 있습니다. 그리고 보통 정렬에 사용하는 경우는 많이 봤는데, 제가 생각한 로직은 정렬에는 사용하지 않고 양수, 음수, 0을 따져 상태를 판단하는 로직이었습니다. 만약 이렇게 구현한다면 다른 개발자가 보았을 때 의도를 잘 파악하기 어렵진 않을지 걱정이 되었습니다. 조앤이 보기엔 어떤지 궁금합니다!
```java
@Override
public int compareTo(Cards other) {
    return this.bestSum() - other.bestSum();
}
```
```java
public Status decidePlayerStatus(PlayerCards playerCards, DealerCards dealerCards) {
    int compared = playerCards.compareTo(dealerCards);
    if (compared > 0) {
        return Status.WIN;
    }
    if (compared < 0) {
        return Status.LOSE;
    }
    return Status.TIE;
}
```

읽어주셔서 감사합니다😄

2024-03-13 14:51 UTC, seovalue requested changes
안녕하세요, 테니! 조앤이에요ㅎㅎ
코멘트 몇가지 남겨두었는데 확인해보시고 다시 리뷰 요청 주세요!

2024-03-13 14:51 UTC, seovalue commented on src/main/java/manager/Casino.java
>      public void run() {
> 함수(또는 메서드)의 길이가 10라인을 넘어가지 않도록 구현한다

지켜볼까요~

2024-03-13 14:51 UTC, seovalue commented on src/main/java/manager/Casino.java
> +        List<PlayerCards> playerCardsBundle = makePlayerCards(names, deck);
굉장히 사소한건데..ㅎㅎㅎ make라는 의미가 와닿지 않는 것 같아요!

2024-03-13 14:51 UTC, seovalue commented on src/main/java/manager/Casino.java
> +        if (opinion) {
if (opinionToDraw) 이런식으로 draw 한다는 의견임이 담기는 것은 어떨까요?

2024-03-13 14:51 UTC, seovalue commented on src/main/java/manager/Casino.java
> +        if (!playerCards.canDraw() || !opinion) {
여기도 not이 두번 붙어있는데 메서드를 분리하거나 내부에서 not 메서드를 만들어볼까요?

2024-03-13 14:51 UTC, seovalue commented on src/main/java/domain/game/Referee.java
> +public class Referee {
ㅎㅎReferee라는 객체 뭔가 귀엽네요

2024-03-13 14:51 UTC, seovalue commented on src/main/java/domain/score/Status.java
> +    private final Function<Bet, Revenue> function;
function에도 적절한 이름을 줘볼까요?

2024-03-13 14:51 UTC, seovalue commented on src/main/java/domain/score/Status.java
>  public enum Status {
Status도 좀 더 세부적인 이름을 줘볼까요?

2024-03-13 14:51 UTC, seovalue commented on src/main/java/domain/game/Rule.java
> +        if (dealerStatus == BLACKJACK) {
dealerStatus.isBlackjack()

2024-03-13 14:51 UTC, seovalue commented on src/main/java/domain/game/Referee.java
> +        checkRemainPlayers(dealer, players, dealerStatus);
(꼭 하지 않으셔도 돼요!) 지금은 3가지밖에 없지만, 만약 10가지라면 10번을 모두 나눠서 해야할 것 같아요. 한번에 players의 결과를 얻을 수 있도록 리팩터링해볼까요?

2024-03-13 14:51 UTC, seovalue commented on src/main/java/domain/game/Referee.java
> +                .filter(player -> !rule.isBlackJack(player) && !rule.isBust(player))
조건문은 메서드 분리를 하면 가독성이 좋아죠요! (위에도 남겼지만요ㅎㅎ)

2024-03-13 14:51 UTC, seovalue commented on src/main/java/domain/score/ScoreBoard.java
> +        Revenue revenue = status.calculateRevenue(bet);
status가 수익을 계산하는 것에 대해서 어떻게 생각하시나요

2024-03-13 14:51 UTC, seovalue commented on src/main/java/domain/game/Referee.java
> +        checkRemainPlayers(dealer, players, dealerStatus);
check라는 네이밍에서 ScoreBoard를 업데이트할 거라는 예상이 되지 않는 것 같아요.

2024-03-13 14:51 UTC, seovalue commented on src/test/java/domain/game/RefereeTest.java
> +class RefereeTest {
Referee의 decideResult를 수행한 결과에 대한 ScoreBoard 테스트 같다는 느낌이 들어요. Referee의 정확한 역할이 뭘까요? Referee에서 하는 역할을 ScoreBoard에서 할 순 없을까요?

2024-03-13 14:51 UTC, seovalue commented on src/test/java/domain/card/CardsTest.java
> +    @DisplayName("처음 뽑은 두 개 카드의 합을 구한다.")
Card에 A가 들어있을 경우 케이스별로 어떤 결과가 나오는지에 대한 테스트를 추가해보는 것이 어떨까요?

2024-03-13 14:51 UTC, seovalue commented on README.md
> +- [ ] 게임을 완료한 후 각 플레이어별로 최종 수익 출력
완료한 것은 체크해주세요!

2024-03-13 14:51 UTC, seovalue commented on README.md
> +### 베팅
질답 여기서 해볼게요!! 그나저나 본명이 엄청 예쁘시네요

1. 예외처리
getFirstCard를 했을 때 없다면 예외를 던지는 정도만 추가해도 좋을 것 같아요. 
그리고 카지노에서 예외처리의 경우 우선 비즈니스 로직상(요구사항 상) 발생가능한 예외케이스에 대해서는 임의의 예외 및 메시지를 담아서 던지도록 하고, 나머지 예외에 대해서는 일단은 처리하지 않아도 저는 괜찮다고 생각해요! 

2. comparable
저는 지금 구현해주신 것도 괜찮다고 생각해요. compareTo가 좀 더 명확해지려면 차라리 Cards를 넘기는 것이 아닌 bestSum을 넘기게 되면 명확해지는 것 같고요ㅎㅎ

2024-03-14 00:45 UTC, ay-eonii commented on src/main/java/manager/Casino.java
> +        if (opinion) {
무엇에 대한 opinion인지 의미를 담아 네이밍해주는 게 확실히 명확해보이네요!
 readHitOpinion 메서드의 리턴값이니 opinionToHit을 사용했습니다! 감사합니다 😊

2024-03-14 00:55 UTC, ay-eonii commented on src/main/java/manager/Casino.java
> +        if (!playerCards.canDraw() || !opinion) {
확인했습니다!

2024-03-14 01:52 UTC, ay-eonii commented on src/main/java/domain/game/Rule.java
> +        if (dealerStatus == BLACKJACK) {
enum과 비교하는 메서드를 만들어 두는 이유가 무엇인가요?

제가 생각한 isBlackjack 메서드의 장점에는 enum을 equals가 아닌 ==로 비교하게끔 **유도**할 수 있다는 것입니다. 하지만 강제는 아니기에 (해당 메서드를 사용하지 않고 여전히 밖에서 equals 또는 == 로 비교할 수 있습니다), 메서드로 만들어 사용하는 장점이 더 있는지 궁금합니다!

2024-03-15 05:27 UTC, ay-eonii commented on src/main/java/domain/score/Status.java
>  public enum Status {
결과를 의미하는 Outcome으로 변경했습니다!

2024-03-15 07:32 UTC, ay-eonii commented on src/main/java/domain/game/Referee.java
> +        checkRemainPlayers(dealer, players, dealerStatus);
조앤! **한번에** 라는 의미를 잘 이해하지 못했어요🥺

**한번에** 라는 것은 List<PlayerCards>를 한번만 돌린다는 의미일까요? 혹은 조건이 추가되어도 메서드의 호출이 늘어나지 않게끔 하라는 의미일까요?

전자라면 리팩토링 후 players를 세 번 돌리는 문제를 해결했다고 생각합니다!
후자라면 조건들(isBlackjack, isBust 등)을 List 같은 콜렉션으로 만들어 각 조건을 순회하는 방법도 생각했는데 구현이 쉽지 않네요😢

2024-03-15 07:36 UTC, ay-eonii commented on src/main/java/domain/score/ScoreBoard.java
> +        Revenue revenue = status.calculateRevenue(bet);
상태(결과)가 수익 계산과 연관이 있다고 느껴지다가도 상태가 수익을 직접 계산하는 `status.calculateRevenue(bet)` 라는 코드를 보면 어색하게 느껴지기도 하네요. Outcome(구 Status) 가 수익 계산기를 알고, 이를 반환하는 로직으로 수정했습니다 :)

2024-03-15 07:36 UTC, ay-eonii commented on src/main/java/domain/game/Referee.java
> +        checkRemainPlayers(dealer, players, dealerStatus);
수정하겠습니다 :) 👍

2024-03-15 08:11 UTC, ay-eonii commented on src/test/java/domain/game/RefereeTest.java
> +class RefereeTest {
Rule : 기준에 따라 승,무,패 반환
ScoreBoard : 이름과 결과로 수익 계산 및 저장
Referee : Rule 및 ScoreBoard 호출

> Referee에서 하는 역할을 ScoreBoard에서 할 순 없을까요?

Referee에서 하는 역할을 ScoreBoard에서 처리하기 위해서는 Rule이 ScoreBoard를 호출해야 하는데,
기존에 Rule이 ScoreBoard를 알고 있는 게 어색하다고 생각해 만든 게 Rule과 ScoreBoard 둘 다 아는 Referee 였습니다 😂
> Referee의 decideResult를 수행한 결과에 대한 ScoreBoard 테스트 같다는 느낌이 들어요.

위와 같은 느낌이 드는 게 Rule과 ScoreBoard를 호출하는 역할만 해서 그런 것 같아요.

---

현재는 Rule이 하는 역할을 Referee가 할 수 있고 어색하지 않다고 생각해서 현재는 Rule의 역할을 Referee에게 넘겼습니다.

즉, 현재는 아래와 같은 역할을 가지고 있어요.
Referee : 기준에 따라 승,무,패 결정 및 ScoreBoard 업데이트
ScoreBoard : 이름과 결과로 수익 계산 및 저장

그런데 승, 무, 패 결과는 큰 의미를 가지고 있지 않고 ScoreBoard를 업데이트 하는 용도로만 사용되고 있어요. 그래서 ScoreBoard에 바로 업데이트를 하니 반환값이 없어 또 같은 테스트가 나왔네요 😢 

이전보다는 각 클래스의 역할은 뚜렷해졌다고 생각하는데, 반환값이 없는 메서드는 어떤 테스트를 해야할지 막막합니다 🤯

2024-03-15 08:25 UTC, ay-eonii commented on src/test/java/domain/card/CardsTest.java
> +    @DisplayName("처음 뽑은 두 개 카드의 합을 구한다.")
추가하겠습니다! 감사합니다 😊

2024-03-15 08:26 UTC, ay-eonii commented on README.md
> +- [ ] 게임을 완료한 후 각 플레이어별로 최종 수익 출력
감사합니다 ☺️

2024-03-15 08:35 UTC, ay-eonii commented on README.md
> +### 베팅
답변 감사합니다 조앤! 기분이 너무 좋아지는 칭찬이네요 😊

> compareTo가 좀 더 명확해지려면 차라리 Cards를 넘기는 것이 아닌 bestSum을 넘기게 되면 명확해지는 것 같고요ㅎㅎ

bestSum을 넘기는 것이 Comparable<Integer>을 구현해 bestSum을 넘기라는 말씀이실까요? 

제가 생각하기에는 이렇게 구현을 한다면 의도와 다르게 사용될 가능성이 높은 것 같아요! 내부에서는 자신의 bestSum과 비교할텐데 외부에서는 이를 모르니 bestSum이 아닌 다른 값을 넘겨줄 수 있다고 생각해요. 
조앤은 이 부분에 대해 어떻게 생각하는지 궁금해요!💭

2024-03-15 08:38 UTC, ay-eonii commented on src/main/java/manager/Casino.java
> +        List<PlayerCards> playerCardsBundle = makePlayerCards(names, deck);
사소한 리뷰 좋아요!! ㅎㅎㅎ 감사합니다 ☺️

카드를 갖는 건 게임을 준비하는 것이라 생각해서 readyPlayerCards라고 변경해보았는데 어떤가요?!

2024-03-16 01:58 UTC, seovalue commented on src/main/java/domain/game/Rule.java
> +        if (dealerStatus == BLACKJACK) {
@ay-eonii 저는 객체가 알고 있는 정보에 대해서는 최대한 내부로 숨기는 것을 좋아해요. 그리고 dealerStatus == BLACKJACK과 같은 부분이 반복될 경우 중복을 줄일 수도 있고요.

2024-03-16 02:13 UTC, seovalue commented on README.md
> +### 베팅
넵넵 동의해요! 이런 경우에는 메서드명으로 의도를 표현해주어야한다고 생각해요. 
즉 compareTo라는 메서드는 기존에 제공되는 메서드이니 bestSum을 계산한다는 의미를 외부에서 알기 어렵고, 그렇다고 Cards를 넘기자니 내부적으로 bestSum을 호출하는 구조가 되어 외부에서 모르는 것은 동일하고요.
이런 경우에는 메서드명으로 의도를 담아주는게 가장 낫다고 생각해요! bestSum을 비교한다는 것 자체가 의도가 담긴 행위이기도 하고요!

2024-03-16 02:42 UTC, seovalue commented on src/main/java/domain/game/BlackjackGame.java
> +public class BlackjackGame {
블랙잭게임과 카지노의 차이가 무엇인가요?

2024-03-16 02:42 UTC, seovalue commented on src/main/java/domain/game/BlackjackGame.java
> +    private final Map<Name, PlayerCards> players;
해당 변수도 일급컬렉션화해서 객체로 만들어줄 수 있을 것 같아요.

2024-03-16 02:42 UTC, seovalue commented on src/test/java/domain/card/CardsTest.java
> +    @DisplayName("Ace가 있을 때의 최선 합을 구한다.")
👍 리뷰 반영해주셨네요ㅎㅎ

2024-03-16 02:42 UTC, seovalue commented on src/test/java/domain/game/RefereeTest.java
> +class RefereeTest {
referee가 결정만 하는 것이 아니라 scoreBoard의 업데이트 책임까지 갖고 있어서 테스트하기가 애매한 것 같아요.
referee는 judgeOutcome만 수행하여 그 결과를 반환하는 1가지의 책임만 갖는다면 referee에서는 outcome 결과를 제대로 판별하는지에 대한 테스트를 수행할 수 있을 것 같아요.

또한 ScoreBoard도 계산된 수익을 갖고 있는 값과 같은 역할이 아닌 수익 계산까지 수행하고 있어서 테스트하기가 애매한 것 같다고 느껴지고요.

결과적으로 리팩터링 전이나 후 모두 Referee와 ScoreBoard가 1가지 이상의 역할을 하고 있기 때문에 발생하는 것 같아요~

2024-03-16 02:45 UTC, seovalue approved these changes
안녕하세요, 테니!ㅎㅎ 리팩터링 잘 수행해주셨네요.
우선 요구사항은 만족해서 이번 단계는 이만 머지하도록 할게요!
다만 지난번에 나눴던 코멘트들에 대해 제 코멘트 추가로 남겨두었는데요, 
확인해보시고 추가로 질문이 있으시다면 편하게 말씀주세요~!

2024-03-16 02:45 UTC, merged

2024-03-16 11:08 UTC, ay-eonii commented on src/main/java/domain/game/BlackjackGame.java
> +    private final Map<Name, PlayerCards> players;
적용해보겠습니다!

2024-03-17 05:09 UTC, ay-eonii commented on src/main/java/domain/game/BlackjackGame.java
> +public class BlackjackGame {
가장 큰 차이점은 View를 아는지 모르는지 입니다.

Blackjack 도메인을 따로 둔 이유는 View를 알고있는 Casino에서 무분별하게 접근하던 데이터 (DealerCards, List<PlayerCards> 등)을 캡슐화하여 메서드로 접근하도록 하기 위함입니다!

2024-03-17 05:16 UTC, ay-eonii commented on README.md
> +### 베팅
의도를 잘 나타낼 수 있는 메서드를 만드는 것도 방법이네요! 비교라고 하면 compareTo를 오버라이딩 해야겠다 생각했는데 꼭 그렇게 해야 하는 건 아닌 것 같네요😅👍

2024-03-17 05:21 UTC, ay-eonii commented
@seovalue 

안녕하세요 조앤! 날이 많이 따듯해졌네요. 주말 잘 보내고 계신가요?☺️

리뷰에서 좀 벗어난 질문이 하나 있는데요,
Casino에서 run()이라는 메서드가 역할이 크고 의미가 모호하다는 생각을 했어요.

2024-03-17 05:32 UTC, ay-eonii commented
@seovalue 

안녕하세요 조앤! 날이 많이 따듯해졌네요. 주말 잘 보내고 계신가요?☺️

리뷰에서 좀 벗어난 질문이 하나 있는데요,
Casino에서 run()이라는 메서드가 역할이 크고 의미가 모호하다는 생각을 했어요.
```java
public class BlackjackApplication {
    public static void main(String[] args) {
        final Casino casino = new Casino();
        final BlackjackGame game = casino.prepare();
        casino.start(game);
    }
}
```

그래서 위 처럼 메서드를 preparer과 start로 분리하였는데, BlackjackGame이라는 도메인이 Application까지 노출되게 되었네요. 변경되지 않을 거라는 의미로 final을 붙였는데, 외부에 도메인이 노출되었을 때 의도와 다르게 메서드를 호출할 가능성이 있지 않을까 걱정이 돼요.

이렇게 변경하였을 때의 장점은 Casino의 메서드를 더 작은 역할로 분리할 수 있다는 점이고,
단점은 Application에 도메인이 노출된다는 점입니다.

조앤은 이 단점에 대해 어떻게 생각하시나요?

2024-03-17 05:36 UTC, seovalue commented
@ay-eonii 말씀해주신 문제도 있기도 하고 저는 카지노가 준비를 끝냈을 때 블랙잭 게임을 반환하는 것도 어색하게 느껴지는 것 같아요!(아마 인스턴스 변수 세개 제한 때문에 그러셨을 것 같긴 한데ㅎㅎ)

어차피 반환한 블랙잭을 카지노 내부에서만 사용한다면 카지노의 생성자 안에서 prepare의 역할을 수행하고 start만 외부로 노출하는 게 가장 낫다구 생각해요

2024-03-17 05:39 UTC, ay-eonii commented
@seovalue 

인스턴스 변수 개수 제한이 조금 가혹하네요 ㅎㅎ 🫠
답변 감사합니다 조앤 ! 좋은 주말 보내세요 🍀☺️