[블랙잭 Step2] 명오 미션 제출합니다
woowacourse/java-blackjack pull request #689
Opened 2024-03-13 08:53 UTC by HyungHoKim00

안녕하세요 오리!

저번에는 저저번 리뷰에 말씀해주셨던 수정사항을 수정하지 못해 죄송합니다.

이번 미션에는 큰 의문은 없었고, 제가 진행한 방식에 대한 의문점이 하나 있습니다.
---
검증만을 위한 객체

처음에는 금액을 1000 이상으로 받기 위해 단순히 Money 객체에서 검증을 진행하려 했습니다.

하지만, Money 객체는 플레이어가 패배할 시 값이 음수로 변형되었고, 그 과정에서 에러가 발생했습니다.

그렇기 때문에, '플레이어의 베팅 금액'과 '게임 중의 돈'을 다른 객체로 나누어 생성했는데요,

이 과정에서 BetAmount 객체는 값을 받아 값이 1000 이상인지만 판별하였고,

Money 객체는 new Money(BetAmount.value()) 와 같은 방식으로 생성했습니다.

나쁜 방법은 아닌 것 같지만, 이 과정에서 불필요하게 객체가 생성되었다 제거된다고 생각했습니다. 

static한 BetAmountValidator 클래스를 만들어, 입력을 int로 받고 값만 판별하는 메서드를 입력 단계에서 지나치게 하는 방법이 나았을까요?

어떤 방법이 좋다고 생각하는 지 궁금합니다.
---
항상 감사합니다!!

2024-03-14 03:26 UTC, jinyoungchoi95 requested changes
안녕하세요 명오 😄

2단계 잘 진행해주셨네요. 몇가지 코멘트남겨두었으니 확인부탁드려요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-03-14 03:26 UTC, jinyoungchoi95 commented on src/main/java/domain/money/PlayersMoney.java
> +public class PlayersMoney {
`Players`와 분리해야하는 이유가 있을까요? `Players`가 그냥 `Map<Player, Money>`를 가지게 하면 되지 않을까요?

2024-03-14 03:26 UTC, jinyoungchoi95 commented on src/main/java/domain/money/PlayersMoney.java
> +    }
blackjack인 경우 돈을 1.5배로 돌려주는 메소드인데요. 따로 호출하도록 하는것이 아닌 이율계산시에 blackjack도 함께 계산되도록 바꾸어주세요. 현재처럼 구현하면 `changeIfBlackjack()`이 호출될 수 있도록 보장할 수 있을까요?

2024-03-14 03:26 UTC, jinyoungchoi95 commented on src/main/java/domain/money/PlayersMoney.java
> +        return playersMoney.values().stream().mapToInt(Money::value).sum() * DEALER_MULTIPLIER;
```suggestion
        int playersMoney = playersMoney.values()
            .stream()
            .mapToInt(Money::value)
            .sum()
        return playersMoney * DEALER_MULTIPLIER;
```
stream을 포현할때 한줄에 점을 여러개 찍지 않아요.

2024-03-14 03:26 UTC, jinyoungchoi95 commented on src/main/java/domain/money/PlayersMoney.java
> +    }
replace하기보다는 새로운 `Map<Player, GameResult>`를 반환하여야하지 않을까요?

Collection을 파라미터로 받아서 값을 변환해주는 로직은 편하기는 하지만 어디서 변경점이 일어나는지 확인할 수 없어요. 불변을 지키는 것은 final로 참조값만 불변을 지키는 것이 아닌 컬랙션에서 어떻게하면 불변성을 유지할 수 있을지도 중요합니다.

2024-03-14 03:26 UTC, jinyoungchoi95 commented on src/main/java/domain/user/GameUsers.java
> +    }
1. `isDealerBlackjackOnly`가 더 적절하지 않을까요?
2. (반영하지 않으셔도 됩니다.) 개인적으로 && 혹은 ||로 매칭하는 것보다 더 가독성이 높은 것은 아닌경우로 if 조건절을 타는 것이 더 눈에 잘 보일 수 있다 생각해요.
```java
if (player.isBlackjck() {
    return false;
}
return dealer.isBlackjack();
```
3. Blackjack에서 `J`를 대문자, 소문자로 혼용해서 사용되고 있는데 Blackjack 하나로 통일해주세요.

2024-03-14 03:26 UTC, jinyoungchoi95 commented on src/main/java/controller/BlackjackRunner.java
> +        }
블랙잭이면 실수로 hit을 더안해도 자동으로 플레이어가 게임을 종료할 수 있는 친절한 규칙이네요 👍

2024-03-14 03:26 UTC, jinyoungchoi95 commented on src/test/java/domain/money/PlayersMoneyTest.java
> +        assertThat(playersMoney.getPlayersMoney()).containsExactly(Map.entry(player, money.change(gameResult)));
현재 테스트의 가독성이 좋은지 한번 고민해보세요. bdd의 주석을 사용해도 가독성은 올라갈 것 같지만, 근본적으로 테스트에서 세팅해야하는 값(given)이 add를 해야하거나 하는 등 로직이 들어가면 들어갈 수록 테스트 가독성이 떨어집니다.

2024-03-14 03:26 UTC, jinyoungchoi95 commented on src/main/java/domain/user/GameUsers.java
<img width="684" alt="스크린샷 2024-03-14 오후 12 23 55" src="https://github.com/woowacourse/java-blackjack/assets/69106910/ea59737a-240d-485e-ac25-96b0c846e979">

커버리지가 채워지지 않은 비즈니스 로직이 보이네요.

2024-03-14 03:53 UTC, HyungHoKim00 commented on src/main/java/domain/user/Hand.java
> +    private final List<Card> cards;
validation을 활용하는 방법이 더 좋은 방법이겠네요!! 감사합니다.

2024-03-14 03:55 UTC, HyungHoKim00 commented on src/test/java/view/BetAmountTest.java
> +    @DisplayName("베팅 금액은 최소 1000이다")
정확하게 테스트명을 작성하도록 하겠습니다!!

2024-03-14 04:21 UTC, HyungHoKim00 commented on src/main/java/domain/money/PlayersMoney.java
> +public class PlayersMoney {
처음에 이름을 입력받고 그 후에 Money를 입력받기 때문에, Players를 생성하고 Money를 입력받아야 한다고 생각했습니다.

이번에 다른 분들의 리뷰를 보며 방법을 알아내어 Map으로 생성했는데요, 이때 문제가 하나 생겼습니다.

toMap()을 실행하니, 이름의 중복을 검사할 수 없었습니다.

중복을 검사하기 위해선, 위의 BetAmount같은 클래스를 새로 생성하는 방법이 떠올랐는데요, 그렇다면 굳이 Players를 제거할 필요가 있을까하는 의문이 들었습니다.

출력에서도 List 꼴로 player를 받는 경우가 많기 때문에 순서를 보장받기에도 용이하다고 생각하여 수정하지 않았습니다.

2024-03-14 04:24 UTC, HyungHoKim00 commented on src/main/java/domain/money/PlayersMoney.java
> +    }
동의합니다!!

2024-03-14 04:24 UTC, HyungHoKim00 commented on src/main/java/domain/money/PlayersMoney.java
> +        return playersMoney.values().stream().mapToInt(Money::value).sum() * DEALER_MULTIPLIER;
더 꼼꼼하게 확인하겠습니다!!

2024-03-14 04:49 UTC, HyungHoKim00 commented on src/main/java/domain/user/GameUsers.java
> +    }
J를 혼용하지 않고 소문자로 쓰려 했는데, 제 스스로가 대문자라고 생각해서 실수가 있었던 것 같네요.

메서드명도 is를 사용하는 것이 boolean을 반환하는 것을 잘 나타내는것 같아 좋은 것 같아요.

추가적으로, 제 스스로는 && 으로 매칭하는 것이 익숙해져서인지, 아직은 그쪽이 더 잘 읽히네요 ㅎㅎ . 좋은 의견 감사합니다.

2024-03-14 06:11 UTC, HyungHoKim00 commented on src/main/java/domain/money/Money.java
> +    private static final double LOSE_MULTIPLIER = -1;
맞네요!! GameResult가 가져가는 것이 적절한 역할분배라 느껴지고, 코드도 깔끔해진 것 같습니다.

2024-03-14 06:23 UTC, HyungHoKim00 commented on src/test/java/domain/money/PlayersMoneyTest.java
> +        assertThat(playersMoney.getPlayersMoney()).containsExactly(Map.entry(player, money.change(gameResult)));
기본적으로 불필요한 개행들도 존재하는 것 같아 수정했습니다.

테스트에서 given에 add 등의 로직이 들어갈 수 밖에 없는 상황이 존재한다고 생각하는데, 그런 경우에는 어떻게 가독성 문제를 해결하시나요?

2024-03-14 06:38 UTC, HyungHoKim00 commented
안녕하세요 오리! 주신 리뷰 바탕으로 수정했습니다.

이번에 따로 질문은 없고, Players와 PlayersMoney 분리 관련하여 질문 하나를 대댓글로 남겨두었습니다.

항상 감사합니다!

2024-03-14 08:26 UTC, jinyoungchoi95 commented on src/main/java/domain/user/GameUsers.java
커버리지를 확인하는 것도 중요하지만 TDD가 습관화된다면 좋을 것 같아요. 꼭 테스트를 먼저 짜는 것을 고려하지 않더라도 중요한 것은 실패케이스를 먼저 설계를 하고 이를 테스트코드로 추가하는 것입니다.

2024-03-14 08:50 UTC, jinyoungchoi95 commented on src/test/java/domain/money/PlayersMoneyTest.java
> +        assertThat(playersMoney.getPlayersMoney()).containsExactly(Map.entry(player, money.change(gameResult)));
단적으로 예를들면 
```java
    @Test
    @DisplayName("플레이어가 블랙잭으로 승리한 경우 금액의 1.5배를 받는다.")
    void earn150PercentMoneyWhenBlackjackAndWin() {
        Player player = new Player(new Name("aa"));
        player.receiveCard(new Card(Shape.SPADE, Number.ACE));
        player.receiveCard(new Card(Shape.SPADE, Number.TEN));
```
에서 receiveCard를 하는 것과 똑같을 것 같은데요. 생성자에서 두카드를 들고있는 Hand를 가지게하면 되지 않나요? `Hand`의 생성자가 무조건 기본 생성자여야하는지 고민해보시면 좋을 것 같아요. 생성자는 과연 필요한것만 있어야할까요?

2024-03-14 09:02 UTC, jinyoungchoi95 requested changes
안녕하세요 명오 😄

블랙잭에서 충분히 미션의 요구사항과 학습을 진행하신 것 같아 머지하려하는데요. 내일 수업을 들으신 이후 수업에 나온 내용을 적용하고 싶으시다면 먼저 dm 주신 이후 수업내용을 미션에 반영해주시면 될 것 같아요. 추가적인 구현없이 머지하고싶으시다면 리뷰요청주시면 머지하겠습니다. (남은 시간을 학습에 투자해도 좋다고 생각해요.)

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-03-15 08:10 UTC, HyungHoKim00 commented
안녕하세요 오리! 이번에 생각보다 많은 변화가 일어났습니다.

get 메서드를 사용하지 않고 로직을 작성하는 연습을 했는데요, 제가 하고 있는 것이 맞나 하는 생각을 좀 했던 것 같습니다.

많이 바뀌었지만 다시 잘 부탁드립니다!!

2024-03-16 04:53 UTC, jinyoungchoi95 requested changes
안녕하세요 명오 😄

미션 잘 마무리해주셨네요. 블랙잭 미션에서의 요구사항과 학습을 충분히 만족하신 것 같아 이만 머지하려고하는데 혹시 추가로 궁금하신 것이 있으실까 하여 request change드려요. 다시 리뷰 요청주시면 머지하겠습니다.

감사합니다 🙇‍♂️

2024-03-16 04:53 UTC, jinyoungchoi95 commented on src/main/java/domain/money/PlayerProfits.java
> +        playersMoney.keySet().forEach(consumer);
> 하지만, forEachPlayer() 메서드가 올바른 것인지는 잘 모르겠습니다. 결국 PlayerProfits 에서 Players를 꺼내와 연산을 수행하는 것 처럼 느껴졌습니다.

`PlayerProfits`는 Player Map를 관리하는 것이기 때문에 `PlayerProfits`이 Map안에 있는 Player를 호출하는 것은 큰 문제가 없어보여요.

다만 `Consumer`를 활용하신다면 무슨 역할을 하는지 좀 더 명확하게 전달할 필요가 있는 것 같아요. `forEachPlayer`가 무엇을 하는지 명확하게 드러나는 메소드명일까요? `Consumer`라는 표준 인터페이스를 사용하는 것은 괜찮다고 생각하지만 현재 이 `Consumer`는 무슨 일을 하는 consumer인지 드러나있나요?

2024-03-16 04:53 UTC, jinyoungchoi95 commented on src/main/java/domain/money/BetAmount.java
> +    public static final int MIN_BET_AMOUNT = 1000;
```suggestion
    private static final int MIN_BET_AMOUNT = 1000;
```

2024-03-16 04:53 UTC, jinyoungchoi95 commented on src/test/java/domain/money/BetAmountTest.java
> +    @DisplayName("베팅 금액이 1000 미만이면 예외가 발생한다.")
정상 생성에 대한 테스트도 중요할 것 같아요 :)

2024-03-16 04:53 UTC, jinyoungchoi95 commented on src/main/java/domain/money/GameResult.java
> +    }
(반영하지 않으셔도 됩니다.) `GameResult`가 게임의 승패와 관련된 결과를 가지고 있고 그에 따른 이율도 가지고 있어요. 그럼 `getCondition()`을 내보내지 않고 `GameResult`가 금액을 받아서 benefitRatio를 계산한 금액을 반환하도록 해주어도 좋을 것 같아요.

2024-03-16 04:53 UTC, jinyoungchoi95 commented on src/main/java/domain/money/PlayerProfits.java
> +    }
여기의 `forEach`도 무엇을 위한 forEach인지 이름이 명확하지 않은 것 같아요. 명확하지 않은 이름이라면 너무 포괄적인 메소드를 제공하는 것은 아닌지, 추상화된 메소드를 제공했을때의 문제는 무엇인지 고려해보시면 좋을 것 같아요.

https://github.com/woowacourse/java-blackjack/pull/689#discussion_r1524480475 에서 말씀드렸듯 출력을 위한 getter는 괜찮다고 생각하고, getter로 출력해도 되는 로직을 `BiConsumer`로 단순 출력되는 로직으로 변경하는 것은 오히려 복잡성만 높일수도있어요.

2024-03-16 04:53 UTC, jinyoungchoi95 commented on src/main/java/domain/user/Player.java
> +    public static final int RECEIVABLE_THRESHOLD = 21;
```suggestion
    private static final int RECEIVABLE_THRESHOLD = 21;
```

2024-03-16 04:53 UTC, jinyoungchoi95 commented on src/main/java/domain/user/Player.java
> +                .findFirst()
`findFirst()`와 `findAny()`의 차이는 무엇일까요?

2024-03-16 04:53 UTC, jinyoungchoi95 commented on src/main/java/domain/user/PlayerNames.java
> +        }
`Set`을 통한 중복체크를 하거나해서 따로 중복에 대한 validation을 하는건 어떨까요?

개인적으로 `new ArrayList<>();`를 통해서 add하면서 가변적으로 상황이 바뀌는 validation은 직관적이지 않아 무엇을 뜻하는지 코드를 파악하기 힘들고 에러발생 시에 원인 파악이 힘들 수 있다고 생각해요.

2024-03-17 00:52 UTC, HyungHoKim00 commented on src/main/java/domain/user/Player.java
> +    public static final int RECEIVABLE_THRESHOLD = 21;
단축키로 상수를 생성하면 public으로 생성되는데, 확인을 못한 부분이 있네요.. 신경쓰겠습니다!!

2024-03-17 01:30 UTC, HyungHoKim00 commented on src/main/java/domain/user/Player.java
> +                .findFirst()
findFirst()는 첫번째 요소를 반환하고, findAny()는 순서와 상관없이 반환합니다.

그냥 stream에서는 작동이 비슷하지만, 병렬 stream에서는 순서 상관없이 찾는다면 findAny()가 더 효율이 좋습니다!

순서가 상관없다는 것을 명시할 수 있기에, findAny()를 사용하도록 변경했습니다.

2024-03-17 01:49 UTC, HyungHoKim00 commented on src/main/java/domain/user/PlayerNames.java
> +        }
처음엔 중복된 이름을 출력하려면 최선이라고 생각했지만, 지적해주신 덕분에 더 좋은 코드로 발전시킬 수 있었습니다.

Set을 활용한 코드로 변경하여 중복된 이름을 모두 출력하는 것도 가능하도록 변경했습니다.

2024-03-17 02:12 UTC, HyungHoKim00 commented on src/main/java/domain/money/PlayerProfits.java
> +    }
forEcah, forEachPlayer가 오히려 forEach() 구문이 무엇을 하는지 아는 개발자 입장에서는 더 이해하기 쉽다고 생각했습니다.

하지만, forEach() 라는 이름의 메서드를 보고 '내부의 Map에서 forEach연산을 수행하는구나' 라는 것을 생각하기 어렵다는 것을 느꼈습니다.

getter를 사용하는 것이 개발자 입장에서도 더 이해하기 쉽다 판단하여, 다시 바꾸었습니다.

2024-03-17 02:14 UTC, HyungHoKim00 commented on src/main/java/domain/money/PlayerProfits.java
> +        playersMoney.keySet().forEach(consumer);
forEachPlayer 라는 메서드명은, 앞에 동사가 없기 때문에 무엇을 하는 지 파악하기 어렵다고 느꼈습니다.

consumer도, 변수명만 봤을 때 소비자라고 오해할 수 있는 여지도 있기 때문에 수정했습니다!

2024-03-17 02:17 UTC, HyungHoKim00 commented
안녕하세요 오리!

덕분에 여러 번 수정하면서, 많이 배워갔습니다.

월요일에는 추천해주신 모던 자바 인 액션을 공부해보려고 생각중입니다 ㅎㅎ

지금까지 감사했습니다!

2024-03-17 07:02 UTC, jinyoungchoi95 approved these changes
안녕하세요 명오 😄

블랙잭 미션 기간동안 주고받았던 피드백이 앞으로 미션, 학습하는데 많은 도움이 되셨으면 좋겠습니다. 수고하셨어요 :)

감사합니다 🙇‍♂️

2024-03-17 07:02 UTC, merged