[2단계 - 블랙잭 게임] 잉크 미션 제출합니다.
woowacourse/java-blackjack pull request #691
Opened 2024-03-13 10:30 UTC by yechop

2024-03-15 04:09 UTC, lxxjn0 requested changes
잉크, 2단계 미션 진행하시느라 수고 많으셨습니다!

코드를 보니 특별히 피드백을 드릴만한 부분이 많이 보이질 않네요.. 그래서 일단 간단한 부분에 대해서 피드백 드려봤어요! 해당 부분들 수정하면서 추가로 더 피드백 드릴만한 부분을 찾아보도록 해보면 좋을 것 같습니다 :)

2024-03-16 10:18 UTC, yechop commented on src/main/java/domain/cards/Deck.java
> +    }
카드에 정의되어 있는 캐싱은 카드(단일 카드)를 생성하는 비용을 줄이는 역할을 한다고 생각합니다.

Card의 캐시에서 카드 한장씩 가져와서 Deck에서 카드 뭉치를 생성하는게 더 자연스럽지 않나요??

2024-03-17 09:14 UTC, lxxjn0 requested changes
잉크, 코드 변경사항이 없어보이는데 리뷰 요청이 왔더라고요. 혹시 추가로 반영할 사항이 없다거나 혹은 푸쉬를 안했다면 다시 리뷰 요청 부탁드릴게요 :)

2024-03-17 11:36 UTC, yechop commented
> 잉크, 코드 변경사항이 없어보이는데 리뷰 요청이 왔더라고요. 혹시 추가로 반영할 사항이 없다거나 혹은 푸쉬를 안했다면 다시 리뷰 요청 부탁드릴게요 :)

에고 푸쉬를 안했네요 😭
다시 요청 보냈습니다!

2024-03-18 10:50 UTC, lxxjn0 requested changes
잉크, 피드백 반영하시느라 수고하셨습니다.

반영하신 코드에서 책임과 역할이 보이지 않는 객체들이 많았던 것 같습니다. 혹시나 미션의 요구사항들로 인한 오해 때문에 생긴 객체가 아닐까 싶은 생각도 들었습니다. 예를 들어 원시값을 감싼다거나 혹은 3개 이상의 필드를 가지지 말라는 요구사항이요. 이러한 요구사항을 무조건 지키면서 코드를 작성하실 필요는 없을 것 같습니다. 그것보다 우테코에서 제공하는 요구사항은 '왜 이러한 요구사항이 주어졌을까'에 대해 고민하고 그에 맞는 방법으로 코드를 작성하는 것이 중요합니다. 단순히 'getter를 쓰지 마라'라고 해서 getter를 아예 쓰면 안되는 것이 아니라 왜 getter를 쓰지 말라고 했는지 의도를 파악하게 된 것처럼요! 이번 피드백을 드린 부분 뿐만이 아니라 전체적인 코드에서 객체의 설계와 어떤 도메인을 표현하고 있는지에 대해서 한번 더 고민해보고 수정해보면 좋을 것 같습니다 :)

2024-03-18 10:50 UTC, lxxjn0 commented on src/main/java/domain/BlackJackGame.java
> +    Deck deck;
해당 두 필드의 접근 지정자를 두지 않은 이유가 있을까요?

2024-03-18 10:50 UTC, lxxjn0 commented on src/main/java/domain/gamer/Gamers.java
> +public class Gamers {
해당 클래스는 players와 dealer를 감싸는 것 말고는 별다른 역할을 하지 않는 것 같습니다. 해당 객체를 만드신 이유가 있을까요?

2024-03-18 10:50 UTC, lxxjn0 commented on src/main/java/domain/gamer/bet/GamerWallet.java
> +public class GamerWallet {
해당 객체도 마찬가지로 어떠한 목적응로 설계된 도메인 객체인지 모르겠어요. 혹시 필드를 3개 이상 가지지 말라는 제약조건으로 인해 생긴 도메인 객체라면 이 요구사항을 신경쓰지 마시고 작성해보시면 좋겠어요. 해당 요구조건은 객체가 의도하지 않게 커지는 상황에 대한 경계의 의미로의 요구사항으로 생각해주시면 될 것 같습니다. 필요한 상황에는 필요한 개수 만큼의 필드는 있어야 한다고 생각합니다.

2024-03-18 10:50 UTC, lxxjn0 commented on src/main/java/domain/gamer/bet/Money.java
> +public class Money {
해당 객체도 가지는 역할이 없어보입니다. 도메인 객체에 맞는 적절한 역할을 부여해보면 어떨까요?

2024-03-18 10:50 UTC, lxxjn0 commented on src/main/java/domain/gamer/bet/GamersWallet.java
> +                .filter(gamerWallet -> gamerWallet.getPlayer().equals(player))
getter를 사용하지 말고 메시지를 전달하는 방향으로 변경해보면 어떨까요?

2024-03-21 09:56 UTC, yechop commented
> 잉크, 피드백 반영하시느라 수고하셨습니다.
> 
> 반영하신 코드에서 책임과 역할이 보이지 않는 객체들이 많았던 것 같습니다. 혹시나 미션의 요구사항들로 인한 오해 때문에 생긴 객체가 아닐까 싶은 생각도 들었습니다. 예를 들어 원시값을 감싼다거나 혹은 3개 이상의 필드를 가지지 말라는 요구사항이요. 이러한 요구사항을 무조건 지키면서 코드를 작성하실 필요는 없을 것 같습니다. 그것보다 우테코에서 제공하는 요구사항은 '왜 이러한 요구사항이 주어졌을까'에 대해 고민하고 그에 맞는 방법으로 코드를 작성하는 것이 중요합니다. 단순히 'getter를 쓰지 마라'라고 해서 getter를 아예 쓰면 안되는 것이 아니라 왜 getter를 쓰지 말라고 했는지 의도를 파악하게 된 것처럼요! 이번 피드백을 드린 부분 뿐만이 아니라 전체적인 코드에서 객체의 설계와 어떤 도메인을 표현하고 있는지에 대해서 한번 더 고민해보고 수정해보면 좋을 것 같습니다 :)

객체가 꼭 책임과 역할을 가져야 한다고 생각을 못했습니다. 원시값을 포장하는데 집중하다보니 필요 없는 객체가 많아졌던 것 같아요. 체스 미션과 동시에 진행하느라 많이 시간을 쏟지 못했지만 피드백 반영 해보았습니다!

2024-03-22 08:48 UTC, lxxjn0 approved these changes
잉크, 미션 진행하시느라 수고 많으셨습니다. 제가 말씀드린 부분에 대한 반영은 전반적으로 다 적용된 것으로 보여서 미션 종료하도록 하겠습니다.

미션 진행하시느라 수고 많으셨습니다 👍🏼

2024-03-22 08:48 UTC, merged