[2단계 - 블랙잭 베팅] 로빈(임수빈) 미션 제출합니다!
woowacourse/java-blackjack pull request #699
Opened 2024-03-14 03:34 UTC by robinjoon

# 기능 변경 사항
## 승부 판단 규칙 변경
- 플레이어와 딜러가 모두 bust(21점이 넘는 경우) 플레이어의 승리
## 베팅 기능
1. 플레이어는 양의 정수 만큼의 배팅을 할 수 있다.
2. 게임의 결과에 따라 상금이 달라진다.
    - 블랙잭(처음 뽑은 두개의 카드로 21점)인 경우 : 베팅 금액의 1.5배
    - 블랙잭이 아닌 상태로 승리한 경우 : 베팅 금액의 1배
    - 패배한 경우 : 베팅 금액을 잃는다.
    - 비긴 경우 : 베팅 금액을 그대로 돌려 받는다

# 고민과 선택

## 정말 컨트롤러에는 도메인 로직 vs 도메인에 간접적인 뷰의 로직 주입
1단계 머지된 시점에서의 BlackJackController의 일부 코드 입니다.
```Java
private boolean playerTryDrawOnce(Deck deck, Player player) {
      boolean needToDraw = YesOrNoInputView.getYNAsBoolean(player.getRawName());
      DrawResult drawResult = null;
      if (needToDraw) {
          drawResult = playerDraw(deck, player);
      }
      printPlayer(player);
      if (drawResult == null) {
          return false;
      }
      return drawResult.hasNextChance();
}
```
**컨트롤러**에 플레이어가 카드를 뽑기 원하는지 입력을 받고, 이를 이용해 카드를 뽑는 **비즈니스 로직이 포함**되어 있습니다.

저는 **컨트롤러의 역할이 단순히 모델과 뷰 사이의 통신을 대리하는 것이라 생각**합니다. 따라서, **컨트롤러에는 비즈니스 로직이 포함되면 안된다(도메인 로직은 모델에서 수행하므로)고 결론** 내렸습니다. 그 결과 다음과 같은 코드가 작성되었습니다.

```Java
public class BlackJackGame {
// 생략
    public void playersDraw(Deck deck, Consumer<Player> doAfterEachPlayerDraw,
                            Function<String, Boolean> playerWantDraw) {
        players.draw(deck, doAfterEachPlayerDraw, playerWantDraw);
    }
}
```
```Java
public class BlackJackController {
// 생략
    private void playersTryDraw(Deck deck, BlackJackGame blackJackGame) {
        blackJackGame.playersDraw(deck, this::printPlayer, YesOrNoInputView::getYNAsBoolean); 
    }
}
```

위와 같이 **도메인에 함수형 인터페이스를 통해 뷰의 로직이 전달되는 구조**가 되었습니다. 코**드상에서 도메인이 뷰를 의존하지 않지만 결국 런타임에 도메인이 뷰의 로직을 주입받아 수행**한다는 점에서 여전히 의존성이 남아있다고 생각됩니다. **덤으로 매개변수의 개수가 늘어나는 단점**도 함께 가지게  되었습니다.

지금 시점에는 도메인 객체의 매개변수 개수가 아직은 감당 가능하고, 잘 동작하며, 코드상에 명시적인 의존성은 사라지기 때문에 도메인에 함수형 인터페이스를 통해 뷰의 로직을 간접적으로 주입받는 것을 선택했습니다.
# 질문
## 클래스 설계를 하지 않고 TDD를 하는게 맞나??

이번 미션에서도 네오 강의에서 배운대로 TDD로 미션을 수행했습니다. 네오 강의에서는 별도의 클래스 설계(어떤 클래스가 있고, 어떤 클래스와 어떤 클래스가 어떤 메세지를 주고 받는지) 없이 **생각의 흐름대로 진행**했습니다.

저번 사다리 타기 미션에서는 이 방식으로 잘 했는데, 이번 **블랙잭 미션에서는 이 방식대로 했더니 코드를 리팩토링하는 것이 힘들 정도로 이상한 코드가 작성**되었습니다.

코드를 리팩토링하는 것이 힘들 정도로 이상한 코드가 작성된 것이 **제 리팩토링 능력 부족이라 그런건지, 애초에 리팩토링이 어렵게 될 수 밖에 없는 방식인건지** 궁금합니다.

2024-03-14 12:56 UTC, ddu0422 requested changes
안녕하세요 로빈! 미르예요 :)
2단계 미션도 잘 구현해주셨네요.
몇 가지 코멘트 남겼으니 확인 부탁드립니다~

## 답변

> 클래스 설계를 하지 않고 TDD를 하는게 맞나??

TDD의 원칙이 무엇일까요?
리팩토링을 진행할 때는 전체적인 관점에서 바라보며 연습해보면 어떨까요?

2024-03-14 12:56 UTC, ddu0422 commented on src/main/java/domain/blackjack/BlackJackGame.java
> +            dealer.drawRandom(deck);
랜덤은 테스트하기 어렵습니다. 테스트하기 쉬운 구조로 변경하는건 어떨까요?

2024-03-14 12:56 UTC, ddu0422 commented on src/main/java/controller/BlackJackController.java
> +        List<Card> rawHoldingCards = dealer.getRawHoldingCardsWithoutFirstCard();
56번째와 62번째 `getRawHoldingCards / getRawHoldingCardsWithoutFirstCard`도 동일한 행동 아닐까요?
Gamer를 활용해보는건 어떨까요?

2024-03-14 12:56 UTC, ddu0422 commented on src/main/java/domain/blackjack/BlackJackGame.java
> +    }
테스트 코드에서만 사용하는걸까요?
사용하지 않으면 제거하는건 어떨까요?

2024-03-14 12:56 UTC, ddu0422 commented on src/main/java/domain/blackjack/BlackJackGameMachine.java
>      List<Card> getRawHoldingCards() {
보통 메서드 순서는 `생성자 -> business logic -> getter -> equals & hashcode`로 선언합니다.

2024-03-14 12:56 UTC, ddu0422 commented on src/main/java/domain/blackjack/EarnMoneyCalculator.java
> +    }
if 문을 없애보는건 어떨까요?

2024-03-14 12:56 UTC, ddu0422 commented on src/main/java/domain/blackjack/GameResult.java
> +        if (this == WIN || this == WIN_BLACK_JACK) {
enum을 활용하여 if문을 제거해보는건 어떨까요?

2024-03-14 12:56 UTC, ddu0422 commented on src/main/java/domain/blackjack/Gamer.java
> +        this.bettingMoney = bettingMoney;
BettingMoney에게 책임을 부여하는건 어떨까요?

2024-03-14 12:56 UTC, ddu0422 commented on src/main/java/domain/blackjack/Players.java
> +    void draw(Deck deck, Consumer<Player> doAfterEachPlayerDraw, Function<String, Boolean> playerWantDraw) {
functional interface를 그대로 활용하면 어떤 의미인지 파악하는데 시간이 듭니다.
코드를 해석하기보단 이해하기 쉽게 작성하면 어떨까요?

2024-03-14 14:59 UTC, robinjoon commented on src/main/java/controller/BlackJackController.java
> +        List<Card> rawHoldingCards = dealer.getRawHoldingCardsWithoutFirstCard();
> 56번째와 62번째 `getRawHoldingCards / getRawHoldingCardsWithoutFirstCard`도 동일한 행동 아닐까요? Gamer를 활용해보는건 어떨까요?

**플레이어와 딜러 모두**에게 **자신이 가진 모든 카드를 보여주는 행동**(`getRawHoldingCards`)이 필요합니다. 따라서 이는 **Gamer에 정의**했습니다. 

반면, **딜러**에게는 **첫번째 카드를 제외하고 가진 카드를 보여주는 행동**(`getRawHoldingCardsWithoutFirstCard`)이 필요합니다. 따라서 이는 **Dealer에 정의**했습니다.

혹시 
```Java
abstract class Gamer {
//생략
    abstract DrawResult draw(Deck deck, CardSelectStrategy cardSelectStrategy);
}
```
처럼 전략 패턴을 이용해 메서드 하나로 묶어보라는 말씀이신가요?

2024-03-15 01:03 UTC, robinjoon commented on src/main/java/view/BattingMoneyInputView.java
> +                    Console.printf("%s의 배팅 금액은?%n", playerName);
> map은 어떤 역할을 할까요? 출력문을 따로 뺄 수 없을까요? 🤔

map 은 변환하는 역할을 수행하니, 중간에 출력문이 포함되는 것은 어색하다는 말씀이시죠?
peek 을 이용해 처리하도록 하갰습니다!

2024-03-15 02:09 UTC, ddu0422 commented on src/main/java/domain/blackjack/BlackJackGame.java
> +            dealer.drawRandom(deck);
네 맞습니다~

2024-03-15 02:10 UTC, ddu0422 commented on src/main/java/controller/BlackJackController.java
> +        List<Card> rawHoldingCards = dealer.getRawHoldingCardsWithoutFirstCard();
네 맞습니다~ 어떤 행동을 보여줄지 결정하면 자유롭게 사용할 수 있지 않을까요?

2024-03-16 04:29 UTC, ddu0422 commented on src/main/java/view/BattingMoneyInputView.java
> +                    Console.printf("%s의 배팅 금액은?%n", playerName);
peek() 메서드 내부 설명입니다.
```
This method exists mainly to support debugging, where you want to see the elements as they flow past a certain point in a pipeline

papago
이 방법은 주로 디버깅을 지원하기 위해 존재하며, 여기서 요소들이 파이프라인의 특정 지점을 지나 흐를 때 이 요소들을 확인하고자 합니다
```
peek말고 다른 방식으로 변경해볼 수는 없을까요?
반드시 stream을 사용해야할까요?

2024-03-16 04:30 UTC, ddu0422 commented on src/main/java/view/BattingMoneyInputView.java
> +        }
```java
private static void validateInput(String input) {
    try {
        int rawNumber = Integer.parseInt(input);
        checkNegative(rawNumber);
    } catch (NumberFormatException e) {
        throw new IllegalArgumentException("입력 형식이 올바르지 않습니다.");
    }
}
```
위와 같이 변경할 수 있지 않을까요?

2024-03-16 05:23 UTC, ddu0422 requested changes
안녕하세요 로빈! 미르입니다 :)
전체적으로 잘 구현해주셨네요.
몇 가지 궁금한 사항이 있어 코멘트 남겨드립니다~
궁금한 점 있으시면 언제든지 코멘트 남겨주시거나 DM주세요 😄

2024-03-16 05:23 UTC, ddu0422 commented on src/main/java/domain/blackjack/BlackJackGame.java
> +    }
플레이어 드로우 이후, 출력문을 수행하기 위함이네요.
Domain이 지녀야할 책임일까요?
Draw 이후 아무것도 출력하지 않는 형태로 변경되면 그건 Domain의 책임일까요? View의 책임일까요?

2024-03-16 05:23 UTC, ddu0422 commented on src/main/java/domain/blackjack/CardShowStrategy.java
> +    List<Card> show(List<Card> allCards);
`all`이라는 내용을 CardShowStrategy가 알아야할 책임일까요?

2024-03-16 05:23 UTC, ddu0422 commented on src/main/java/domain/blackjack/Players.java
> +    Players(List<String> playerNames) {
사용하지 않으면 제거하는건 어떨까요?

2024-03-16 05:23 UTC, ddu0422 commented on src/main/java/domain/card/CardPool.java
> +    static final Map<CardType, Map<CardName, Card>> pool = new ConcurrentHashMap<>();
`List<Card>`를 선언할 수는 없는걸까요?

2024-03-16 05:23 UTC, ddu0422 commented on src/main/java/domain/blackjack/BlackJackGame.java
> +        int dealerRawEarningMoney = -players.calculatePlayersEarningMoney(dealer).stream()
`-`가 눈에 띄지 않네요.
어떤 방식으로 변경해야 의미 전달을 적절히 할 수 있을까요?

2024-03-16 09:25 UTC, robinjoon commented on src/main/java/domain/blackjack/CardShowStrategy.java
> +    List<Card> show(List<Card> allCards);
> `all`이라는 내용을 CardShowStrategy가 알아야할 책임일까요?

allCards 라는 변수명은 처음 입력으로 주어지는 카드들 중 일부만 선택해서 보여줄 수 있다는 것을 암시하기 위한 변수명이었습니다. 지금 보니, 가능한 모든 Card 라는 의미로 해석될 수 있군요! 적절한 변수명으로 변경하겠습니다!

2024-03-16 11:06 UTC, robinjoon commented on src/main/java/domain/blackjack/BlackJackGame.java
> +    }
> 플레이어 드로우 이후, 출력문을 수행하기 위함이네요. Domain이 지녀야할 책임일까요? Draw 이후 아무것도 출력하지 않는 형태로 변경되면 그건 Domain의 책임일까요? View의 책임일까요?

말씀하신 변경은 Controller 에서 playerDrawAfterCallBack에 아무것도 수행하지 않는 구현체를 넘겨주는 것으로 구현할 수 있습니다. 하지만, 질문의 의도는 View 의 로직이 Domain 내부로 주입되는 것이 문제가 있다는 취지로 하신 것 같습니다. 앞서 처음 코드 리뷰를 요청했을 때 PR에 적은 고민의 연장선이 되겠군요.

이런 선택을 내리게 한 근원적인 이유는 Controller에 대한 부족한 이해때문이었던 것 같습니다. 입출력과 관련된 로직은 도메인 외부에서 처리하게 하고, 기존과 비슷하게 도메인 로직과 입출력 로직이 엉켜있는 부분을 도메인 외부에서 작성해 보겠습니다!

2024-03-16 11:07 UTC, robinjoon commented on src/main/java/controller/BlackJackController.java
> +        players.forEach(this::printPlayer);
> players가 forEach를 책임져야할까요? 어떤 의도를 지닌걸까요?

너무 포괄적인 동작을 할 수 있기 때문에, 의도를 파악하기 어렵고 오용의 여지가 있겠네요. 이를 사용하는 코드에 맞게 특화된 메서드로 분리하겠습니다!

2024-03-16 11:26 UTC, robinjoon commented on src/main/java/domain/card/CardPool.java
> +    static final Map<CardType, Map<CardName, Card>> pool = new ConcurrentHashMap<>();
> `List<Card>`를 선언할 수는 없는걸까요?

조회 성능을 위해 Map 을 활용하려 했는데, 생각해 보니 어차피 Card 의 개수가 52개기 때문에 단순 순회와 속도 차이가 없겠군요! 수정하겠습니다!

2024-03-16 12:31 UTC, robinjoon commented
https://github.com/woowacourse/java-blackjack/pull/699#discussion_r1527086683 이 코멘트를 반영하는 과정에서, 기존의 forEach 메서드를 사용한 코드가 모두 DTO로 변환하는 과정에서 사용했던 것을 확인했습니다. Player에는 public 메서드가 없기 때문에 Players에 getter를 추가해 List<Player> 를 가져오는 방향으로 변경했습니다.

그런데, https://github.com/woowacourse/java-blackjack/pull/699#discussion_r1527095558 이 코멘트를 반영하는 과정에서 Player의 draw 메서드가 public으로 전환되게 되었습니다. 기존에 입출력 관련 로직을 메서드 참조를 통해 도메인 패키지 내부로 주입했기 때문에 default로 유지될 수 있었던 메서드기 때문입니다.

결론적으로 두 코멘트를 반영한 결과 Player에 오용할 수 있는 여지가 열린 것 같다는 생각이 들었습니다.

도메인 내부로 뷰의 로직을 간접적으로 주입함으로써 도메인의 캡슐화를 단단히 유지할 수 있었는데, 도메인 내부로 뷰의 로직을 주입하지 않으니 도메인의 캡슐화가 약해졌습니다. 이게 어쩔 수 없는 트레이드 오프인건지, 제가 방법을 못 찾은 건지 확신이 없습니다.

2024-03-16 23:34 UTC, ddu0422 requested changes
안녕하세요 로빈! 미르입니다 :) 
블랙잭 미션 잘 구현해주셨어요~
로빈의 생각을 듣고 싶은 부분이 생겨서 코멘트 남겨드립니다~

2024-03-16 23:34 UTC, ddu0422 commented on src/main/java/domain/card/CardPool.java
> +    }
조회 성능에 대한 이야기를 주셨는데, 현재 조회 메서드는 테스트코드에서만 사용하고 있는 내용이 아닐까요?

2024-03-16 23:34 UTC, ddu0422 commented on src/main/java/controller/BlackJackApplication.java
> +        return drawResult.hasNextChance();
> 도메인 내부로 뷰의 로직을 간접적으로 주입함으로써 도메인의 캡슐화를 단단히 유지할 수 있었는데, 도메인 내부로 뷰의 로직을 주입하지 않으니 도메인의 캡슐화가 약해졌습니다. 이게 어쩔 수 없는 트레이드 오프인건지, 제가 방법을 못 찾은 건지 확신이 없습니다.

## 질문

1. 캡슐화란 무엇일까요?
`getter로 데이터를 가져온 방식` 때문에 캡슐화가 약해졌다고 이야기하는걸까요?
아니면, `카드 선택을 View`에서 진행하기 때문에 캡슐화가 약해졌다고 이야기하는걸까요?

2. 카드 선택 여부를 도메인 규칙으로 보신걸까요?

2024-03-17 01:24 UTC, robinjoon commented on src/main/java/domain/card/CardPool.java
> +    }
> 조회 성능에 대한 이야기를 주셨는데, 현재 조회 메서드는 테스트코드에서만 사용하고 있는 내용이 아닐까요?

네 맞습니다. 하지만, 테스트 코드 역시 자주 실행되어야하는 코드기 때문에 성능을 고려하는 것은 타당하다고 생각합니다.

2024-03-17 01:42 UTC, robinjoon commented on src/main/java/controller/BlackJackApplication.java
> +        return drawResult.hasNextChance();
> ## 질문
> 1. 캡슐화란 무엇일까요?
>    `getter로 데이터를 가져온 방식` 때문에 캡슐화가 약해졌다고 이야기하는걸까요?
>    아니면, `카드 선택을 View`에서 진행하기 때문에 캡슐화가 약해졌다고 이야기하는걸까요?
> 2. 카드 선택 여부를 도메인 규칙으로 보신걸까요?

1. 저는 `객체 관점의 캡슐화`를 **객체의 상태를 숨기**고, **객체를 조작할 수 있는 메서드 일부만 외부에 공개**해 **객체를 안전하게 보호하는 것**이라 이해하고 있습니다. `패키지 관점의 캡슐화`는 클래스 역시 외부 클래스 입장에선 일종의 인터페이스(자바의 인터페이스가 아닌, 보다 일반적인 의미의)기 때문에, **같은 기능을 수행한다면 적은 클래스가 공개되는 것이 캡슐화가 강한 것이고, 공개된 클래스라도 공개된 메서드가 적은 것이 더 캡슐화가 강한 것**이라 이해하고 있습니다. 
    - 그런데, 미르의 코멘트를 적용하면서 기존의 **Gamer 의 default 메서드가 public**이 되어야 했고, **DrawResult가 public 클래스**가 되어야 했습니다. 이런 관점에서 캡슐화가 약해졌다고 생각했습니다. 
    - Players에 getter를 추가했던 시점에는 Player에 도메인 로직을 수행하는 public 메서드가 없었기 때문에 캡슐화가 약해졌다고 볼 수 없었습니다. 그런데, 이제는 생겼기 때문에 **허용되지 않는 시점에 Player의 도메인 로직이 수행될 수 있게 되었습니다.** 이 부분도 캡슐화가 약해진 것이라 생각합니다.
2. 카드의 선택 여부를 도메인 규칙으로 바라봤다기보단 **카드를 추가로 뽑을 수 있는 조건을 판단해 카드를 추가로 뽑을지 물어보는 것이 도메인 로직**이라 생각했습니다. **카드를 언제 추가로 뽑을 수 있는지 결정하는 것은 블랙잭 게임의 규칙**이기 때문에 도메인 로직으로 바라보는 것이 합당하다고 생각합니다.

2024-03-17 01:55 UTC, ddu0422 commented on src/main/java/domain/card/CardPool.java
> +    }
현재 테스트하는 부분은 CardPool과 상관없이 테스트 되어야하는 상황이 아닐까요?
Parameter로 CardPool을 받는 상황이 아니라면 Card를 직접 생성해서 테스트를 진행하는 방법은 어떨까요?

2024-03-17 01:56 UTC, ddu0422 commented on src/main/java/controller/BlackJackApplication.java
> +        return drawResult.hasNextChance();
1. 캡슐화가 깨지지만 않으면 괜찮지 않을까요?
2. 그렇다면 허용 여부를 Parameter로 받으면 되는게 아닐까요?

2024-03-17 03:50 UTC, robinjoon commented on src/main/java/domain/card/CardPool.java
> +    }
> 현재 테스트하는 부분은 CardPool과 상관없이 테스트 되어야하는 상황이 아닐까요?
> Parameter로 CardPool을 받는 상황이 아니라면 Card를 직접 생성해서 테스트를 진행하는 방법은 어떨까요?

pool 을 만든 이유가 Card 객체를 매번 새로 생성하지 않기 위해서였어서 설령 테스트 코드에서도 Card를 따로 생성하는 것은 고려하지 않았습니다.

그러나 CardPool을 사용했던 안했던 동일한 결과가 나와야 하니까 직접 Card를 생성하는 것도 괜찮을 것 같습니다. 다음에 비슷한 상황이 생기면 미르의 방법도 적용해보겠습니다!!

2024-03-17 03:57 UTC, robinjoon commented on src/main/java/controller/BlackJackApplication.java
> +        return drawResult.hasNextChance();
> 1. 캡슐화가 깨지지만 않으면 괜찮지 않을까요?
> 2. 그렇다면 허용 여부를 Parameter로 받으면 되는게 아닐까요?

> 1. 캡슐화가 깨지지만 않으면 괜찮지 않을까요?
> 2. 그렇다면 허용 여부를 Parameter로 받으면 되는게 아닐까요?

1. 괜찮은 것도 같습니다. 이번에 두 상황 모두 경험해봤으니 좋은 학습이었던 것 같습니다!!

2. 허용 여부를 파라미터로 받는 것이 무슨 말인지 잘 이해가 가지 않습니다..

2024-03-17 04:58 UTC, ddu0422 commented on src/main/java/controller/BlackJackApplication.java
> +        return drawResult.hasNextChance();
> 카드를 추가로 뽑을 수 있는 조건을 판단
> 카드를 추가로 뽑을지 물어보는 것

2024-03-17 05:17 UTC, robinjoon commented on src/main/java/controller/BlackJackApplication.java
> +        return drawResult.hasNextChance();
물어본 결과를 매개변수로 받아보라는 말씀이셨군요! 이해했습니다!

2024-03-18 09:28 UTC, ddu0422 approved these changes
안녕하세요 로빈! 미르입니다 :)
블랙잭 미션 하시느라 고생 많으셨어요!
새로운 관점에서 많은 내용을 주고 받을 수 있었어요!
다음 미션도 화이팅이예요 😄

2024-03-18 09:28 UTC, merged