[2단계 - 블랙잭 베팅] 리비(이근희) 미션 제출합니다.
woowacourse/java-blackjack pull request #709
Opened 2024-03-14 08:20 UTC by Libienz

안녕하세요 썬 ☀️
2단계 PR 요청 드립니다.

2단계에서는 어떤 객체가 어떤 속성을 가지고 있고 어떤 기능을 제공해야 하는지를 중점적으로 고민해봤습니다.
제가 제일 약한 부분이더군요... 쉽사리 답을 찾지 못하고 여기저기 책임을 퍼뜨린 것 같습니다.

2단계도 잘 살펴봐주시면 열심히 학습해보겠습니다 
감사합니다 😊

2024-03-14 16:13 UTC, syoun602 requested changes
안녕하세요 리비 ☀️

깔끔하게 구현해주셔서 리뷰할게 별로 없네요 💯
조금 과도한 분리가 있었던 것 같아서 관련해서 리뷰 드렸는데,
확인해주시고 재요청주세요 😊

2024-03-14 16:13 UTC, syoun602 commented on src/main/java/blackjack/domain/result/BetResult.java
> +public class BetResult {
비슷한 리뷰가 있는데, 이 부분도 객체가 조금 과도하게 분리된 느낌이 있는 것 같아요.
BetResult, PlayerResult, PlayerResults가 정말 도메인이 맞는지 궁금합니다. 단순 DTO 아닌가요?

2024-03-14 16:13 UTC, syoun602 commented on src/test/java/blackjack/domain/bet/MoneyTest.java
> +
👀

2024-03-15 08:44 UTC, Libienz commented on src/main/java/blackjack/domain/bet/Bets.java
> +public class Bets {
방금 진행해보았습니다. 신세계네요 🙌
전반적으로 객체의 depth가 많이 줄었고 관련있는 기능끼리 응집하게 되어 객체의 책임까지 선명해진 것 같습니다.

개선된 부분 잘 개선했는지 한번 살펴봐주시면 감사하겠습니다 🙇🏻‍♂️

2024-03-15 08:46 UTC, Libienz commented on src/main/java/blackjack/domain/bet/Money.java
> +    public void validateRange(int amount) {
놓친 부분... 감사합니다 😊

2024-03-15 08:56 UTC, Libienz commented on src/main/java/blackjack/domain/result/BetResult.java
> +public class BetResult {
Map으로 응집하니 관련 책임이 눈에 띄게 되었습니다.

개선 해보았는데 리뷰 요청드리면 한 번 봐주시면 감사하겠습니다 🙇🏻‍♂️

2024-03-15 08:57 UTC, Libienz commented on src/test/java/blackjack/domain/bet/MoneyTest.java
> +
앗 ... 🫠

2024-03-15 11:19 UTC, Libienz commented on src/test/java/blackjack/domain/JudgeTest.java
> +    void testPlayerBlackJackWin() {
이전의 관례였군요.. 애노테이션이 등장하면서 서서히 사라진 모습 확인할 수 있었습니다.

개인적으로 이런 배경에 대해서 알아보는 것을 좋아하는데 짚어서 글 추천해주시니 너무 좋습니다 😀
흥미로운 글  추천 감사합니다 👍

2024-03-15 17:33 UTC, Libienz commented
안녕하세요 썬 ☀️

2단계 리팩토링 진행해보았습니다.
과한 분리를 줄이고 도메인에 역할들을 할당함으로써 명세를 자세히 드러내보고자 노력했어요 🤔
그래도 잘 진행했는지는 확신이 없네요 🫠

여러 질문 주세요 썬!
나름(?) 깊게 고민하고 작성한 코드라 썬이랑 여러 의견 나눠보고 싶어요 🙌

이번에도 잘 부탁드립니다 🙇🏻‍♂️

2024-03-16 02:18 UTC, syoun602 requested changes
안녕하세요 리비~

리팩토링 이후에 훨씬 깔끔한 코드를 작성하셨네요! 💯
코멘트 남겨두었으니 확인 부탁드려요.
또한, 중점적으로 살펴봤으면 하는 부분이 있다면 해당 코드에 PR 코멘트를 남겨주시면 됩니다.
어느 부분에서 어떤 고민을 하셨는지 말씀해주세요 😊

2024-03-16 02:18 UTC, syoun602 commented on src/main/java/blackjack/domain/result/GameResult.java
> +    GameResult(double profitLeverage, BiPredicate<Dealer, Player> biPredicate) {
이렇게 두면 접근 제어자가 어떻게 될까요?

2024-03-16 02:18 UTC, syoun602 commented on src/main/java/blackjack/domain/result/GameResult.java
> +    public static GameResult of(Dealer dealer, Player player) {
이 메서드는 생성자인가요?

2024-03-16 02:18 UTC, syoun602 commented on src/test/java/blackjack/domain/bet/PlayerBetsTest.java
> +        assertThat(GameResult.of(dealer, player2)).isEqualTo(GameResult.PLAYER_LOSE);
assertAll에 포함되지 않은 이유가 있나요?

2024-03-16 02:18 UTC, syoun602 commented on src/test/java/blackjack/domain/result/PlayerProfitsTest.java
> +        Player player1 = TestPlayerCreator.of("썬", 1, 2, 3, 4);
엇 저도 있었군여 🙇‍♂️

2024-03-16 02:18 UTC, syoun602 commented on src/test/java/blackjack/domain/result/PlayerProfitsTest.java
> +        Map<Player, Profit> playerProfitMap = new HashMap<>();
기본적으로 변수명에는 자료구조를 사용하지 않습니다~
클린코드의 의미 있는 이름에 대해 학습해보아요
```suggestion
        Map<Player, Profit> playerProfits = new HashMap<>();
```

2024-03-16 08:32 UTC, Libienz commented on src/main/java/blackjack/domain/result/GameResult.java
> +
가독성 측면에서는 비슷하다고 판단합니다! 조건식이 거의 동일한 것 같아서요 🤔

제가 위의 코드처럼 바꾼 이유는 채점 로직 분리를 통해 Judge 클래스를  파생되게 만드는 것보다 어떤 결과가 나올지 판정 로직을 GameResult 도메인 안에 응집시키고 싶었기 때문입니다.

다만 다음과 같은 고민이 있기는 합니다.
`플레이어가 승리하는 판정 로직을 변경해주세요`라는 변경 요구사항이 들어오면 다른 개발자들이  위화감없이 GameResult라는 enum을 찾아올 수 있을지가 고민이에요!

관련해서  썬의 의견도 들어보고 싶습니다 🙌

2024-03-16 08:34 UTC, Libienz commented on src/main/java/blackjack/domain/result/GameResult.java
> +                .orElseThrow(() -> new IllegalArgumentException("[INTERNAL ERROR] 게임 결과를 판정할 수 없습니다"));
파라미터가 적절하지 않다는 의미에서 `IllegalArgumentException`을 생각하기는 했어요 🤔
다만 NoSuchElement등 다른 예외도 생각이 나기는 하네요 

표준 예외를 사용한다고 했을 때 어떤 예외를 고르는지 팁이 있을까요!? 
골라본 경험이 많지 않다보니 이것도 될 것 같고 저것도 될 것 같고 많이 헷갈립니다 🤔

2024-03-16 08:37 UTC, Libienz commented on src/main/java/blackjack/domain/result/GameResult.java
> +                .findFirst()
스트림 요소들을 직렬로 처리할 때는 문제가 없지만 병렬로 처리하는 경우에 차이가 있을 수 있다는 것을 학습할 수 있었습니다 👊

2024-03-16 08:38 UTC, Libienz commented on src/test/java/blackjack/domain/bet/BetAmoutTest.java
> +    void testCreateMoneyWithInvalidRange(int amount) {
앗 .. 테스트 명 바꾸는 실습도 진행해보겠습니다!

2024-03-16 08:39 UTC, Libienz commented on src/main/java/blackjack/BlackJackGame.java
>          CardDeck cardDeck = CardDeck.createShuffledDeck();
실습의 의미로 자료구조 변경해보겠습니다 💪🏻

제가 만든 클래스가 특정 자료형에 종속적인지도 확인해 볼 수 있을 것 같아요 👍

2024-03-16 08:43 UTC, Libienz commented on src/main/java/blackjack/domain/result/GameResult.java
> +    public static GameResult of(Dealer dealer, Player player) {
생성자가 아닙니다. 다만 `GameResult.of(dealer, player)`와 같은 코드가 `딜러와 플레이어의 게임 결과`처럼 평문적으로 읽힌다고 생각해서 네이밍을 위처럼 진행해보았어요.

썬의 말씀 듣고 추가적인 생각해보았습니다 🤔
그 결과 다른 개발자가 본다면 정적 팩토리 메서드의 네이밍 패턴을 사용하고 있기에 헷갈릴 수도 있겠다는 생각을 하게 되었어요.

고쳐보는게 낫다고 판단하게 되었습니다. 반영해볼게요 💪🏻

2024-03-16 08:44 UTC, Libienz commented on src/test/java/blackjack/domain/bet/PlayerBetsTest.java
> +        assertThat(GameResult.of(dealer, player2)).isEqualTo(GameResult.PLAYER_LOSE);
앗.. 테스트가 통과하지 않아서 디버깅 용도로 제가 작성한 테스트인데 삭제하지 않았네요 😓

2024-03-16 08:47 UTC, Libienz commented on src/test/java/blackjack/domain/result/PlayerProfitsTest.java
> +        Map<Player, Profit> playerProfitMap = new HashMap<>();
특정 자료형에 종속적인 변수명은 의미를 드러내지 못하고 확장사항에 잘 견디지 못하는 것을 학습할 수 있었습니다 
반영해보겠습니다 💪🏻

2024-03-17 07:39 UTC, Libienz commented on src/main/java/blackjack/domain/card/Hand.java
> +        if (hasAce() && (sum + ACE_WEIGHT) <= BUST_THRESHOLD) {
새로운 시각 알게 되었습니다 💪🏻

2024-03-17 08:17 UTC, Libienz commented on src/main/java/blackjack/domain/result/GameResult.java
> +    GameResult(double profitLeverage, BiPredicate<Dealer, Player> biPredicate) {
열거형 생성자는 기본적으로 접근제어자가 private인걸로 학습했습니다! 
public, protected로 설정해보았는데 not allowed here라고 하면서 빨간줄이 뜨더라고요 🤔

불필요한 생성을 막기 위한 맥락으로 이해했습니다 👍

2024-03-17 10:00 UTC, Libienz commented
안녕하세요 썬 ☀️ 
코멘트 반영 위주의 리팩토링 진행해보았습니다.

미션 진행에 대해서 다음의 것들에 대해서 썬과 의견 나눠보고 싶어요 🙌
썬께서 생각 들려주신다면 매우 큰 도움이 될 것 같습니다 😃

### 🙋🏻‍♂️ 연관관계 방향에 대해서 고민해보았습니다 

저는 플레이어가 베팅금액을 가지지 않도록 설계했어요 🤔 

처음에는 플레이어 도메인에 추가하려고 했는데 이렇게 한두개씩 플레이어에 추가하다가는 후에 Player가 가지게 되는 속성이 굉장히 많아질수도 있다고 생각하게 되었습니다. 
그래서 플레이어가 베팅금액을 가지지 않도록 구현하기로 하였고 결과적으로 매핑하는 클래스를 추가로 정의해야 했죠 🤔

현업의 경우를 저 혼자 멋대로 상상해보았는데요 현업의 도메인들은 지금의 미션과는 비교도 안될 정도로 많은 연관관계를 가지고 있을 것 같아요.
보통의 경우 도메인 연관관계를 어떤 방향으로 관리하는지 알려주실 수 있을까요? (플레이어가 Bet을 가지고 있는지, Bet이 플레이어를 알고 있는지, 매퍼가 있는지)

학습할만한 키워드 짧게 던져만주셔도 도움 많이 될 것 같습니다 💪🏻

### 🙋🏻‍♂️ 도메인은 어떤 속성을 가지고 어떤 속성을 외부로 덜어내야 하는가 
위 질문과 비슷한 맥락입니다.

플레이어가 플레이어 이름을 속성으로 가지고 있는 것은 제게는 매우 합리적입니다.
플레이어가 자신의 손패를 속성으로 가지고 있는 것 또한 그렇고요 .
사실 플레이어가 자신의 베팅을 속성으로 가지고 있는 것 또한 제게 위화감이 없습니다.

이렇게 치면 플레이어 관련된  모든 속성이 플레이어에 엮여야 하는데 이는 결국 클래스를 비대하게 만들고 시스템 유지보수의 취약점이 될 수 있을 것 같다는 생각입니다.

어디까지를 플레이어가 알고 어디까지가 외부로 덜어내져야 하는 것일까요 .. 절대적 기준이 없음을 알지만 썬의 의견이 도움이 될 수 있을 것 같습니다 🙇🏻‍♂️

### 🙋🏻‍♂️ 검증 책임에 대해 크루들과 토의하고 결론을 내려보았습니다
크루들끼리 토의하고 스스로 결론 내려보았습니다. 사고 과정과 도출한 결론이 합리적인지 썬께서 봐주시면 너무 좋을 것 같아요 😃

시작은 이렇습니다. 
`블랙잭 게임에 참여하는 플레이어는 3명 이하여야 한다`와 같은 검증로직을 저는 Players 도메인에 위치시켰습니다. 

그런데 문득 이런 생각이 들었어요 
- 플레이어가 3명이하이어야 하는 것을 검증하는 책임은 Players의 책임이 아니라 BlackJackGame의 책임이 아닐까
- `Players` 도메인은 사실 자신이 관리하고 있는 플레이어들만 알고 있으면 되지 3명 이하여야 한다는 게임의 룰까지 알아야 될까

도메인이 순수해보이지 않았습니다. (자신의 역할이외의 룰까지 알고 있어서 순수하지 않다라는 생각..)

간단히 넘어갈 수도 있는 문제였지만 저는 그때부터 모든 것이 의심스러웠습니다. 아래와 같이요..
- 21이라는 숫자는 Hand도메인이 알아도 되나? 핸드는 카드리스트만 관리하면 되는 것 아닌가?
- 플레이어는 자신이 히트할 수 있는 숫자를 알아도 되나? 룰과 너무 강한 결합을 맺는 것 아닌가?
- 도메인을 여러 룰들, 전략에서 멀리 하여 순수하게 두는 것이 재사용성에 더 좋지 않을까? 

관련해서 크루들과 [이런 얘기](https://github.com/woowacourse-6th-code-review-study/java-blackjack/pull/11#discussion_r1527232561)를 나눈 후에는 스스로 결론을 내보았습니다.

- 블랙잭 게임 프로젝트에 존재하는 도메인들은 블랙잭 게임 구현이라는 같은 목표를 가진다.
- 같은 목표, 같은 기능을 바라보고 있기에 도메인들에게서 규칙을 완전히 덜어낼 필요 없다.
- 각자와 관련된 요구사항을 알고 있는 것은 합리적. 이들이 협력하도록 하는 것이 중요
- 룰을 덜어내고 BlackJackGame에만 추가하면 오히려 BlackJackGame클래스가 뚱뚱해진다.

### 기능의 위치를 정하는 요령을 생각해보았습니다.

여러 도메인들 중 기능을 어느 도메인의 책임으로 둘 지 스스로 판단하기 힘들었습니다.

1,2단계 모두 `합리적인듯`,`위화감 없는듯`과 같이 느낌에 의존한 설계를 많이했었어요.
특히 이 과정에서 자꾸 행위를 추상화하려고 하다가 객체지향의 특성을 많이 놓친 경험도 있습니다.
(ex. 점수 계산시 Player에게 Hand를 게터로 꺼내와서 ScoreCalculator에 전달)

그러던 와중에 크루들과의 얘기를 통해 다음과 같은 결론을 내리게 되었어요

- TDA 원칙을 생각해보자
- 어떤 기능이 필요로 하는 속성을 가지는 클래스에 물어보도록 하자

어떤 클래스가 어떤 속성을 가지게 할 지 위의 질문처럼 어려움이 있기는 하지만 기능과 같은 경우는 앞으로 위 기준을 가지고 진행해보려고 하는데 썬의 생각은 어떤가요 🤔

2024-03-17 11:54 UTC, syoun602 commented
1. 도메인 및 연관관계
객체지향 설계에 있어서 절대적으로 정답이 있지는 않은 것 같아요. 따라서 제 얘기가 정답이 아님을 우선 상기시켜드립니다.
저 또한 플레이어에 대한 베팅이라면 충분히 플레이어가 가지고 있어도 합리적이라고 생각합니다. 다만, 이때 딜러는 베팅 금액을 필요로 하지 않기 때문에 상속이 아닌 조합을 활용했을 것 같구요. 이렇게하면 3개 이상의 인스턴스 변수에 대한 요구사항도 만족할 것 같네요 😄
설계를 위해서 객체들을 떠올리기 이전에 어떤 메시지가 있을까?를 먼저 고민해보면 좋을 것 같아요. 예를 들어 `베팅하기`라는 메시지를 정의해보고 이 기능은 누구의 책임일까?를 생각해보는거죠. 그리고 이때 해당 객체가 스스로 처리할 수 없는 정보 또는 기능이 있다면 (win, lose에 따른 변화) 적절한 객체를 찾아 해당 작업을 위임 하는거죠. 이걸 책임주도설계(RDD)라고 부르는데 더 궁금하시다면 책 `오브젝트`를 추천드립니다 :)

2. 검증 책임, 책임 위치
객체지향에 한없이 빠지다보면 갑자기 주화입마가 오는데, 잘 정리하신 것 같습니다 👍
결국 객체지향도 하나의 어플리케이션을 완성시키기 위한 수단임으로 도메인/룰에 대한 책임을 각각에게 부여해도 문제가되지 않을 것 같아요.

2024-03-17 11:54 UTC, syoun602 approved these changes
안녕하세요 리비 !

블랙잭 미션 잘 구현해주셨습니다 💯
이전에도 충분히 코드를 잘 작성해주셔서 이만 머지하겠습니다 :)
이제 레벨 1은 악명높은 체스 미션만 남았는데, 푹 쉬시고 다음 미션도 화이팅입니다 😊

2024-03-17 11:55 UTC, merged