[2단계 - 블랙잭 베팅] 포케(이무송) 미션 제출합니다.
woowacourse/java-blackjack pull request #717
Opened 2024-03-14 10:02 UTC by fromitive

안녕하세요 파랑 🐳 포케입니다.

2단계 미션도 잘 부탁드립니다 ㅎㅎ

1단계 미션의 [코멘트](https://github.com/woowacourse/java-blackjack/pull/663#discussion_r1522979395)도 달아놓았으니 확인하시면 될 것 같습니다..!

미션을 하면서 아래와 같이 궁금한 점이 생겨 코멘트 남깁니다

## 궁금한 점

### 구현 객체가 추상 메서드 이외의 메서드를 가지는 건 자연스러운 현상이다 vs 리팩터링의 징조이다.

1단계에선 중복 메서드를 제거하기 위해 `Gamer` 클래스를 **추상 클래스**로 변경했고  `Dealer`와 `Player`에서 추상메서드인 `canHit`을 만든 것 까진 OCP원칙을 위배하진 않았는데,

이번 2단계 부터 **승패 기능이 배팅 기능으로 변경**되면서 플레이어가 배팅 금액인 `Money`를  가지게 되는 구조로 변경되었습니다. 이에 따라 딜러도 `Name`을 가질 필요성을 못느껴, 아래와 같이 각 객체별 필드를 가지게 되었습니다 🥲

| 객체명   | 갖고 있는 필드    |
| ------ | ----------- |
| Game   | Hand        |
| Player | Money, Name |
| Dealer | 없음          |

요구사항이 추가될 수록 딜러와 플레이어의 성격이 달라지는게 자연스러운 현상인지 아니면 리펙터링의 징조인지 판단이 서지 않는데, 파랑의 생각은 어떤지 궁금합니다~ 

PS : 사실 리펙터링 하기 위해선 어디서 부터 나눠야 할지 감이 안잡히긴 합니다 😂

--- 

꼼꼼하게 봐주셔서 감사합니다! 이번 리뷰도 잘 부탁드립니다..! 🙏

2024-03-14 12:31 UTC, summerlunaa commented on src/main/java/domain/BettingResult.java
> +                        player -> player.bet(dealer)));
불필요한 줄바꿈으로 보이네요.

2024-03-14 12:34 UTC, summerlunaa commented on src/main/java/domain/Gamer.java
> -        this.name = name;
이름은 왜 삭제되었나요? 딜러의 이름은 반드시 "딜러"여야 하나요? 콘솔 view가 아닌 곳에서도 해당 제한이 적용될까요?
딜러의 이름이 반드시 딜러여야 한다 하더라도 DEALER_NAME이 `Players`에 있어야 할까요?

2024-03-14 12:34 UTC, summerlunaa commented on src/main/java/domain/Gamer.java
> +    public boolean isBlackJack() { return hand.isBlackJack(); }
```suggestion
    public boolean isBlackJack() { 
        return hand.isBlackJack(); 
    }
```

2024-03-14 12:39 UTC, summerlunaa commented on src/main/java/domain/Hand.java
- `Hand` 클래스의 역할이 무엇인가요?
- 상대가 Bust면 반드시 LOSE 인가요?

2024-03-14 12:55 UTC, summerlunaa commented on src/main/java/domain/Player.java
> +    }
> 구현 객체가 추상 메서드 이외의 메서드를 가지는 건 자연스러운 현상이다 vs 리팩터링의 징조이다.

추상 메서드 이외의 메서드를 가지는 것만으로 리팩터링의 징조인지 아닌지 판단할 수는 없습니다. 메서드 추가 여부보다는 리스코프 치환 원칙을 공부해보세요.

2024-03-15 00:13 UTC, fromitive commented on src/main/java/domain/BettingResult.java
> +                .filter(player -> !GamerResult.DRAW.equals(dealer.judge(player)))
헉 처음 알았습니다..! 관련자료 더 찾아보고 공부하겠습니다! 감사합니다~

2024-03-15 05:38 UTC, fromitive commented on src/main/java/domain/Gamer.java
> -        this.name = name;
처음에 1단계 구현하면서 딜러와 플레이어가 구별할 수 있는 부분이 많지 않았기 때문에 이름을 추가하였습니다! 따라서 `Players`에서 구분을 위해서 "딜러"라는 이름을 검증하는 것이 자연스러운 것 같아 추가하게 되었습니다!

이번 2단계 미션을 진행하면서, `배팅 결과를 반환`하는 기능이 `Player`가 가지고 있게 되면서 `Dealer`와 `Player`는 비슷하지만 다른 객체가 되었습니다. 

따라서 딜러와 플레이어는 굳이 `Name`으로 구분할 필요 없이 객체로 구분이 될 수 있다고 생각하여 `Gamer`에서. `Name`을 제거하는 편이 자연스러운 것 같아서 제거하게 되었습니다!

이렇게 되면 `Players` 내에서 "딜러"라는 이름을 추가로 검증할 필요가 없게 될 것 같은데, 딜러의 알고 모르고 떠나서 다른 기능을 제공하기 때문에, 제거하는편이 좋다고 생각합니다 파랑의 입장도 같은 생각이신가요? 🥲

2024-03-15 05:53 UTC, fromitive commented on src/main/java/domain/Hand.java
딜러의 judge의 결과와 player의 judge의 결과가 다르게 나와야 하네요..!

딜러 입장에선 자신이 bust가 나와도 상대(Player)가 bust이면 이기는데,
플레이어 입장에선 자신이 bust가 나오면 무조건 지도록 작성해야 하는데 그렇제 않네요 🫠

이부분 어떻게 해결할지 고민해보겠습니다..!

2024-03-15 07:13 UTC, fromitive commented on src/main/java/domain/Money.java
> +    }
처음 `Money`를 만들었을 때, 배팅 금액이 1.5배 증가해야 하는 요구사항이 있었기 때문에 `double`을 생각했습니다. 그러나, `double`은 부동소수점 자료형이고, 연산을 할 때 소수점이 부정확 하기 때문에 돈계산을 하기에는 부적합하다고 생각했습니다.

그래서 채용한게 `BigDecimal`인데요, 처음에 `BigDecimal`을 테스트하기 위해서 long을 넘겼으나, 테스트 결과가 연산에 따라 BigDecimal.valueOf(100.0) 또는  BigDecimal.valueOf(100)가 나오게 되면서 정확한 비교가 불가능 했습니다. 그래서 아예 문자열로 받도록 시도했습니다. 

결과적으로 문자열로 `BigDecimal` 초기화를 떠나서  `equals`로 값을 판단하기는 부적합했고 대신 `compareTo` 를 사용해서 비교하라는 [글](https://stackoverflow.com/questions/6787142/bigdecimal-equals-versus-compareto) 을 보면서 해결하게 되었습니다.

문자열 파라미터로 사용하는 것은 해결하려고 했던 기존 잔재가 남아있어서 그렇습니다.. view에서 별도의 처리하지 않아도 될 것 같아 그대로 남게 되었습니다.

그러나, 생성자를 문자열로 받는 것은 동료 개발자로 하여금 오해 받을 소지가 있을 것 같으니, double을 받도록 변경하겠습니다!

2024-03-15 08:13 UTC, fromitive commented on src/main/java/domain/Player.java
> +    }
파랑, 리스코프 치환 원칙에 대해 알게되었는데요!

간단하게 정리하자면, 하위 객체의 메서드는 상위 객체의 기능을 보장해야 한다고 이해했습니다.

현재  공통 기능을 `Gamer` 추상 클래스로 묶었고, `Dealer`와 `Player`는 `Gamer`가 하는 기능을 재정의(추상 메서드 제외)하지 않고 사용하고 있으니 리팩터링 대상은 아닌 것 같다고 생각합니다~

2024-03-15 08:33 UTC, fromitive commented
안녕하세요 파랑 🐳 포케입니다.

포멧팅과 컨밴션 때문에 구조를 이해하기 어렵게 만들어 죄송합니다.. 

포맷팅 부분은, 인텔리제이 설정을 건드려서 해결하고자 노력했고, 제출하기 전에 확인했으나, 컨벤션에 위배되는 부분이 있을 수 있으니 미리 양해를 구합니다 🙇‍♂️

대부분의 코맨트는 답변을 달았으니, 확인 부탁드립니다..! 감사합니다!

2024-03-15 10:43 UTC, summerlunaa commented on src/main/java/domain/Money.java
> +    }
ㅎㅎ 생각보다 복잡한 사정이 있었군요. 고생하셨습니다 👏

2024-03-15 10:45 UTC, summerlunaa commented on src/main/java/domain/Gamer.java
> -        this.name = name;
"딜러"라는 이름을 딜러가 갖는다, 플레이어의 이름은 "딜러"가 될 수 없다는 조건은 콘솔 view 에서의 조건이지 도메인 자체의 제약사항은 아니라고 보았습니다. 만약 해당 검증이 필요하다면 저는 view에서 진행했을 것 같습니다 😀

2024-03-15 11:17 UTC, summerlunaa requested changes
포케 안녕하세요~

코드가 훨씬 정돈되어서 읽기 좋습니다 💯 
지금도 충분히 좋지만 리뷰 조금 더 남겨드렸으니 확인부탁드릴게요!

2024-03-15 11:17 UTC, summerlunaa commented on src/main/java/view/OutputView.java
> +        System.out.printf("%s - %s%n", buildNameCards(playerName.name(), cards), buildTotalScore(playerScore));
이왕이면 Gamer 클래스를 잘 활용해서 `xxxDealerXXX`, `xxxPlayerXXX`와 같은 메서드를 최소화해볼까요? 같은 부모를 가진 자식 클래스들마다 개별 메서드를 나눠주는 건 비효율적인 방식입니다. 공통점을 최대한 활용해봅시다!

2024-03-15 11:17 UTC, summerlunaa commented on src/main/java/view/InputView.java
> +    }
음수 배팅금액도 가능하게 만든 건 의도하신 부분인가요?

2024-03-15 11:17 UTC, summerlunaa commented on src/main/java/domain/card/Card.java
>  public class Card {
블랙잭의 카드는 몇가지로 제한되어 있나요? 매번 같은 인스턴스를 생성할 필요가 있을까요?

2024-03-15 11:17 UTC, summerlunaa commented on src/main/java/BlackJackGame.java
>  public class BlackJackGame {
- 모든 엔티티를 작게 유지한다.

BlackJackGame은 어떤 역할을 하는 클래스인가요? 
BlackJackGame과 view <> domain을 연결하며 적절한 순서대로 프로그램을 진행시키는 역할을 분리해보면 해당 클래스를 조금 더 가볍게 유지할 수 있을 것 같습니다 :-)

2024-03-16 10:07 UTC, fromitive commented
안녕하세요 파랑 🐳 포케입니다~ 

## Gamer

딜러와 플레이어의 공통 부분을 최대한 활용하고자 Gamer에 Name 필드를 다시 추가했습니다..! 
Players에서 "딜러" 이름을 검증하지 안해도 구별이 되기 때문에 이부분은 다시 살리지 않았습니다.

## Deck

static 변수로 카드를 미리 생성하도록 변경하였고, ArrayList<>()를 활용하여 방어적 복사를 하도록 변경하였습니다!
파랑의 의도대로 Deck 생성 시 매 번 카드를 불필요하게 생성하는 것을 제대로 방지한 건지 확인 부탁드립니다..!  🙇‍♂️

## InputView

최소 금액을 음수로 받을 수 있는 부분은 의도하지 않은 동작이라, 입력값 부분에서 처음에 음수가 나오지 않도록 변경했습니다..!

## BlackJackGame

블랙젝 게임이 컨트롤러 역할을 하고 있었는데요 소스코드에서 쉽게 확인할 수 있게 `Application`으로 변경하였고 기존에 메서드로 나뉘어저 있는 게임 순서를, **상태 패턴**을 적용해서 객체만 봐도 순서를 알 수 있도록 수정하였습니다!

`상태 패턴은 도메인에서만 적용해야 한다` 라는 고정관념이 있었고 이를 컨트롤러에서도 적용해보는 것도 괜찮은 시도인 것 같아 적용해봤습니다.
혹시 이렇게 역할을 나눠도 괜찮은 선택인지 파랑의 의견이 궁금합니다~

2024-03-16 12:42 UTC, summerlunaa commented on src/main/java/domain/card/Card.java
>  public class Card {
카드 자체를 캐싱할 수도 있습니다. ([참고](https://kth990303.tistory.com/287))

2024-03-17 05:55 UTC, summerlunaa approved these changes
포케 안녕하세요~

DM으로 드린 리뷰까지 잘 반영해주셨네요! 처음보다 훨씬 좋아진 것 같아요ㅎㅎ

블랙잭 미션은 여기서 머지하겠습니다. 이번 미션도 수고하셨습니다 👏👏 👍

2024-03-17 05:55 UTC, summerlunaa commented on src/main/java/domain/card/Card.java
> +    }
Card 캐싱 좋습니다 👍 

```suggestion
    private static final List<Card> CARDS;
    
    static {
        CARDS = Arrays.stream(CardType.values())
                .flatMap(cardType -> Arrays.stream(CardNumber.values())
                        .map(cardNumber -> new Card(cardType, cardNumber)))
                .toList();
    }
```
이렇게 변경해도 unmodifiableList가 반환됩니다. 줄바꿈도 신경써주시구요~

코딩 컨벤션은 글로 따지면 맞춤법, 띄어쓰기, 문단 나누기 등으로 볼 수 있어요. 맞춤법이나 띄어쓰기를 좀 안 지킨다고 글 읽는 데 문제는 없지만 가독성이 떨어지죠. 일반적으로 통용되는 코딩 컨벤션을 공부해보고 작성할 때부터 의식적으로 적용해보려 노력해보면 좋을 것 같아요!! 처음엔 저도 많이 틀리고 신경도 별로 안 썼는데 하다 보니 익숙해지더라구요ㅎㅎ 점점 좋아질 거예요 👍

2024-03-17 05:59 UTC, merged