[2단계 - 블랙잭 베팅] 짱수(장혁수) 미션 제출합니다.
woowacourse/java-blackjack pull request #719
Opened 2024-03-14 11:24 UTC by zangsu

안녕하세요, 범블비!
꽤나 많은 부분이 수정되면서 구현에 시간이 많이 들었네요...!
요구사항을 만족하지 못했거나, 마음에 들지 않는 부분들도 일부 존재하지만 고민 끝에 답을 찾지 못해 리뷰를 요청하게 되었어요.

주요 변경 사항과 질문들을 차례로 설명드리겠습니다!

## 주요 변경사항 (추가된 요구사항과 관련된 내용은 제외)

### Controller 와 BlackjackGame 의 분리

Step2를 시작하기 전에, `BlackjackGame`을 `Controller`와 분리하게 되었습니다.
범블비가 이전 리뷰에서 언급 주셨던 부분이기도 한데요.
자세한 게임의 흐름을 모두 관리하는 대신, 비즈니스 로직과 관련된 부분들을 `BlackjackGame`으로 최대한 감싸보았습니다.

### `Dealer`, `Player` 의 추가 카드를 뽑는 방법 변경

앞선 Step1 에서는 `Controller` 에서 `Player`가 추가카드를 뽑는 로직을 구현해 두고, 이 자체를 함수형 인터페이스로 넘겨주었습니다. 그리고 이 이유로 실제로 사용되는 `Player` 인스턴스를 `Controller`로 넘기고 싶지 않다고 말씀드렸었죠.
더불어, 이 방법 역시 도메인 로직이 `Controller`에 노출된다는 단점을 가지고 있는 것 같다고 말씀드렸었는데요.

코드를 구현하며 다른 크루들과 이야기를 하다 보니, 이 경우 카드를 뽑는 방법, 즉 도메인 로직이 변경될 때 `Controller`의 코드가 변경되어야 한다는 큰 단점이 있다는 것을 깨달았습니다.
그래서 추가 카드를 뽑는 방법 전체를 하나의 인터페이스로 두는 방법을 사용해 보았습니다.

### `Dealer`와 `Player`를 감싸는 `Participants` 생성

해당 객체를 구현하게 된 이유는 솔직히 말씀 드리면 "3개 이상의 인스턴스 필드를 가지는 클래스를 사용하지 말라" 는 제약조건 때문이었습니다.
다만, `Dealer` 역시 카드를 뽑고, 상금을 분배받는 등 `Player`와 비슷한 역할을 가지고 있기에 일급컬렉션에 함께 관리되는 것이 자연스러울 수 있겠다는 생각도 들었습니다.
동일한 추상클래스를 상속하고 있지만, 다형성을 위함이기 보단 중복된 로직의 중복 제거를 위함이기에 두 객체를 동일한 `List<Participant>`에서 관리하고 있지는 않습니다.

### `Player.getName()`의 반환값 타입 변경

플레이어의 이름이 다양한 곳에서 사용되면서 이제는 `Name` 자체도 의미있는 엔티티가 되었습니다. 이에 따라 `String`을 반환하던 `Player.getName()`을 `Name`을 반환하도록 변경하였습니다.

## 공유드릴 고민점

### 카드 뽑는 책임 `DrawRule`

앞서 말씀드렸듯, 참가자들의 카드를 뽑는 방법을 인터페이스로 묶어내게 되었는데요.
이 과정에서 `InputView`, `OutputView`와의 협력은 꼭 필요하기 때문에 `PlayerRule`, `DealerRule`은 view 패키지의 객체들을 필드로 가지게 됩니다.
그런데, 이렇게 작성하고 나니 도메인 클래스에 view가 너무 깊이 침범한 기분이 들기도 합니다.
게다가, `Player`, `Dealer` 에서도 각 클래스가 사용할 `DrawRule` 구현 클래스를 직접 상수로 가지고 있기도 하고요.

중복되는 흐름은 꽤나 적당히 제거를 한 것 같고, `Controller`에서는 이제 도메인과 관련된 정보를 가지지 않는다는 점 역시 마음에 들지만 위의 단점들이 방금 말씀드린 장점과 트레이드 오프가 될 수 있을 정도인지 판단이 서지 않습니다.

`Controller` 에서 도메인과 관련된 정보를 제거하기 위해 새로 도입한 `DrawRule`과 구현 클래스들을 범블비는 어떻게 보시나요?

### 객체 지향과 현실 모사

이전에 "객체지향의 사실과 오해"라는 책을 가볍게 읽어본 적이 있습니다. 객체지향은 현실을 모사하는 방법론이 아니라는 것을 알게 되었는데요. 그럼에도 저 스스로 느끼기엔 자꾸 불필요하게 현실을 모사하거나, 현실과 차이가 큰 설계에 대해 어색한 느낌이 드는 것 같았습니다.

다만, 저 스스로 제 코드를 보다 보면 자연스러운 흐름을 위한 설계인지, 정말로 불필요하게 현실을 모사하고 있는 것인지 잘 보이지가 않는데요.

혹시나 범블비가 느끼시기에도 과하게 현실을 반영하려는 것 같은 부분이 있다면 코멘트 부탁 드리고 싶습니다!

(제가 그렸던 메시지의 흐름과 같은 설계가 존재한다면 훨씬 답변에 도움이 될 것 같지만 제대로 칠판에 메시지의 흐름을 그려 보면서 클래스를 설계해 본 적은 없다는 점이 아쉽네요..ㅠㅠ)

### 기타...

코드 관련된 질문은 코드 아래에 질문을 추가해 두겠습니다!

2024-03-14 11:29 UTC, zangsu reviewed
이번에도 잘 부탁드립니다!!

2024-03-15 08:44 UTC, ddaaac requested changes
안녕하세요 짱수 👋 

2단계 구현 잘 해주셨습니다.

몇 가지 코멘트 남겼으니 확인해주세요

2024-03-16 07:23 UTC, zangsu commented on src/main/java/blackjack/domain/game/result/GameResult.java
> +public interface GameResult {
리뷰를 받고 생각을 해 보니 특히나 블랙잭의 경우, 각각의 결과들이 특정 절차에 따라 판단되어야 하는데 이 결과들을 모두 분리를 시키려고 했던 것 같네요. 저 역시 각 결과들이 되기 위한 상황을 작성하는 것이 많이 헷갈렸던 만큼 모든 결과를 한 곳에서 판단해 주는 방법으로 변경했습니다.

다만, `Player`와 `Dealer` 모두 게임에 참여하는 플레이어로 카드를 뽑거나 점수를 계산하는 등의 책임만을 부여하고 싶었기에 결과를 enum으로 변경을 해 보았습니다.

2024-03-16 08:39 UTC, zangsu commented on src/main/java/blackjack/domain/game/PlayerResult.java
> +    private final GameResult gameResult;
이전 코멘트와 이번 코멘트를 하나로 아우르는 무언가를 고민해 보았지만, 아직 찾지 못해 우선 개별적으로 생각을 남겨봅니다!

기존의 `Name`을 가지고 있던 방법은 비유하자면 Player 라는 객체의 id인 Name을 외래키로 가지는 다른 객체의 느낌이었던 것 같습니다.
이 방법은 "중복된 이름을 사용할 수 없다" 라는 제약 조건이 있는 현재에는 나름 괜찮은 구현인 것 같기는 합니다. 이름을 식별자처럼 사용할 수 있는 현재에는 굳이 손패 정보와 다양한 로직들을 가지는 `Player`를 식별자와 같이 사용해야 할 이유도 잘 떠오르지는 않습니다. 

하지만, 언젠가 요구사항의 변경에 따라 이름이 아닌 다른 값을 식별자로 구분할 수 있게 되고, 중복된 이름을 사용할 수 있게 된다면 위에서 언급했던 모든 장점이 흔들릴 것 같아요. 

반대로 `Player`를 식별자로 가지고 있게 된다면 `Player`의 `equals()`를 다시 재정의 하는 것 만으로도 `OwnedMoney`, `PlayerResult`와 같은 값들이 이전과 동일하게 동작할 수 있을 것 같습니다. 또, "이름이 결과와 금액을 소유" 하는 것보단 "플레이어가 결과와 금액을 소유" 하는 것이 코드를 읽는 입장에서도 훨씬 자연스럽게 느껴질 것 같아요.
조금 더 확실하게 코드로 확인을 해 보고 싶어 소유권이 명시되어야 할 객체들에서 `Name` 대신 `Player`를 사용하도록 변경을 해 두었습니다.

2024-03-16 08:49 UTC, zangsu commented on src/main/java/blackjack/domain/betting/Bets.java
> +    private final List<OwnedMoney> bets;
범블비의 질문을 다음과 같이 정리해볼 수 있을 것 같아요.
"플레이어가 소유권을 가지게 될 객체들은 플레이어의 인스턴스 변수로 두는 것이 자연스러울 수 있다."
예시로 `OwnedMoney`와 `PlayerResult`가 있을 것 같습니다.

이번 미션의 요구사항에서는 "3개 이상의 인스턴스 변수를 가지는 클래스를 사용하지 않는다" 라는 제약조건이 있었습니다. 그리고, 저는 이를 "모든 클래스는 가능한 최소한의 책임만을 갖도록 설계해 보라"는 의도로 이해했습니다.

`Player`는 게임에 참여하는 책임을 지니고 있습니다. 손패를 관리하고 점수를 계산하기 위해 `Hand` 인스턴스를 멤버로 가지고 있어야 하며,  콘솔에서 자신을 식별시키기 위해 이름을 가지고 있어야 하죠. 이 순간 `Player`는 가질 수 있는 최대한의 인스턴스를 가지게 됩니다. 때문에 "플레이어의 승부 결과", "플레이어의 배팅금액 / 상금" 은 플레이어의 책임에서 분리시키게 되었습니다. 

현실 모사를 조금 해 보자면, 돈을 거는 베팅게임에서 플레이어가 걸었던 돈은 플레이어가 가지고 있는 것이 아닌 테이블 중앙에 두는 것으로 비유해 볼 수도 있을 것 같아요...ㅎㅎ

제가 제대로 질문을 이해하고, 답변을 드린 것이 맞을까요? 답변이 나름 합리적이더라도 범블비가 생각하시기에 더 좋게 느껴지는 방법이 있다면, 새롭게 RC를 주시면서 키워드를 주실 수 있으실지도 부탁드려봅니다! 🙇

2024-03-16 08:56 UTC, zangsu commented on src/main/java/blackjack/domain/betting/Bets.java
> +        Money money = result.calculatePrize(bet.getMoney());
TDA! `PlayerResult`의 내부 구현을 숨기기 위해 `PlayerResult`에게 `calculatePrize()` 메서드를 구현했습니다!

2024-03-16 09:00 UTC, zangsu commented on src/main/java/blackjack/domain/participant/Player.java
> +        return name;
제가 의도했던 "엔티티를 반환해 외부에서 사용하도록 변경" 이 "값에서 책임을 벗겨내지 않는다" 라는 말로 설명될 수 있군요!! 감사합니다 :D

2024-03-16 11:11 UTC, zangsu commented on src/main/java/blackjack/domain/participant/rule/DealerRule.java
> +    private final OutputView outputView = new OutputView();
Controller에서 도메인 관련 정보를 모르게 하고 싶다는 욕심 때문에 너무 많은 시간을 낭비한 것 같네요.

프레젠테이션을 모델에서 분리해 내는 것이 왜 중요한지 다시 공부했습니다. 객체지향의 관점에서 생각하면 "변하기 쉬운 것보단 변화가 없는 것에 의존하라" 는 DIP 와도 관련이 있을 것 같고요. 
표현이 변경된다고 해서 동작을 담당하는 도메인이 변경되지 않도록, 도메인이 view에 의존하면 안된다는 원칙을 다시 한번 새기고 가겠습니다.

추가적으로, 다양한 시도를 통해 블랙잭 미션에서 Controller와 도메인을 완벽하게 분리해 내는 것은 꽤나 까다롭다는 것을 느꼈습니다. 가장 처음에 범블비가 말씀하셨던 대로 Controller 에서 직관적으로 흐름을 볼 수 있도록 Controller에서 Player의 인스턴스를 사용했습니다.

2024-03-16 11:14 UTC, zangsu commented on src/main/java/blackjack/domain/participant/rule/DrawRule.java
> +public interface DrawRule<P extends Participant> {
`DrawRule`은 카드를 뽑는 전략만을 추상화하기 위한 인터페이스이기에 추가적인 메서드를 선언하지 않을 것을 강제하기 위해 붙여주었었는데요.
함수형으로 사용한다는 것은 말 그대로 입력과 출력이라는 개념으로 인터페이스를 사용한다는 뜻이 맞을까요?
이 때의 구현으로는 입력과 출력이 아닌, 구현 클래스를 사용해 주었으니 `@FunctionalInterface`를 붙이지 않는 것이 옳은 것인가요??

2024-03-16 12:07 UTC, zangsu commented on src/main/java/blackjack/BlackJackGameController.java
> +    }
이 부분 Bets 내부로 이동하였습니다!

2024-03-16 12:09 UTC, zangsu commented on src/main/java/blackjack/domain/game/result/PlayerLose.java
> +    public boolean isSatisfy(Dealer dealer, Player player) {
항상 리뷰어 또한 사람이며, 현직자라는 점을 고려하려고 노력하지만 리뷰어의 입장이 되어 본 적이 없어 리뷰를 요청드릴 때 마다 고민이 많았어요!
범블비가 말해주신 부분들 꾸준히 신경써보도록 하겠습니다!! 감사합니다 🙇‍♂️

2024-03-17 06:45 UTC, ddaaac requested changes
안녕하세요 짱수 👋 

몇 가지 코멘트 남겼으니 확인해주세요.

2024-03-17 06:45 UTC, ddaaac commented on src/main/java/blackjack/domain/Ownable.java
> +    default boolean ownedSameOwner(Ownable<O> object) {
OwnedMony#ownedSameOwner을 해도 될 것 같은데 Ownable에 기본 메서드로 만든 이유가 있을까요?

2024-03-17 06:45 UTC, ddaaac commented on src/main/java/blackjack/domain/Ownable.java
> +public interface Ownable<O> {
Ownable이 무슨 책임을 갖고 있는지 잘 이해가 되지 않습니다.
PlayerResult와 OwnedMoney가 어떤 같은 책임을 가져야하는지 모르겠네요.

2024-03-17 06:45 UTC, ddaaac commented on src/main/java/blackjack/domain/betting/Bets.java
> +    private final List<OwnedMoney> bets;
> 3개 이상의 인스턴스 변수를 가지는 클래스를 사용하지 않는다

이 요구사항을 놓쳤었네요. 인스턴스 변수 숫자를 줄이려면 Player와 Money를 묶는 객체가 필요할 거고, 지금의 OwnedMoney 같은 객체를 만들었을 것 같네요.
고민해볼만한 부분은 Players에서 List<Player> 대신 List<PlayerWithBet>을 가질 수 있다는 점입니다. 지금은 컨트롤러에서 Reulst <-> Bet 매칭을 해주고 있는데, List<PlayerWithBet>을 갖는다면 도메인에서 Bet까지 모두 구해줄 수 있겠죠.

2024-03-17 06:45 UTC, ddaaac commented on src/main/java/blackjack/domain/game/BlackJackGame.java
> +    public boolean isDealerDrawable() {
사용하지 않는 메서드들은 정리해주세요.

2024-03-17 06:45 UTC, ddaaac commented on src/main/java/blackjack/domain/Ownable.java
> +public interface Ownable<O> {
인터페이스에 불필요한 제네릭의 사용은 지양해주세요.

2024-03-17 06:45 UTC, ddaaac commented on src/main/java/blackjack/domain/game/GameResult.java
> +    PLAYER_LOSE((OwnedMoney bet) -> bet.multiply(-1)),
미래의 요구사항이 어떻게 될지 모르니 함수를 쓸 수도 있긴 하지만, 눈에 보이는 요구사항이 없다면 직관적으로 배수만 double로 갖고 있는 편이 보기 좋습니다.
요구사항에 유연한 코드를 만들어야하는 것은 맞지만 보이지도 않는 요구사항에 맞춰서 코드를 만드는 건 오버 엔지니어링입니다.

2024-03-17 06:45 UTC, ddaaac commented on src/main/java/blackjack/domain/participant/rule/DrawRule.java
> +public interface DrawRule<P extends Participant> {
> DrawRule은 카드를 뽑는 전략만을 추상화하기 위한 인터페이스이기에 추가적인 메서드를 선언하지 않을 것을 강제하기 위해 붙여주었었는데요. 

이런 의도를 나타내고 싶었다면 붙여도 좋을 것 같네요.

2024-03-17 06:45 UTC, ddaaac commented on src/main/java/blackjack/domain/game/PlayerResult.java
> +    private final GameResult gameResult;
앞서 여러번 코멘트 드렸듯이 인스턴스 변수를 줄이기 위해서는 내부에 필드를 추가하는 대신 외부에 객체를 하나 더 둬서 감싸는 방식을 사용하면 됩니다.
Bet, Result 모두 감싸다보면 자연스럽게 Player + 특정 필드들을 갖는 객체들이 나오겠죠. 외래키라는 개념까지 도입할 필요가 없을 것 같아요.

2024-03-17 07:43 UTC, zangsu commented on src/main/java/blackjack/domain/Ownable.java
> +public interface Ownable<O> {
`Ownable` 인터페이스는 `Player`에게 소유될 수 있다는 것을 나타내기 위한 인터페이스였습니다.
상금을 구하는 과정은 
1. 결과가 누구의 결과인지 확인 후
2. 결과의 주인이 베팅한 금액을 찾고
3. 베팅 금액과 결과를 통해 상금을 계산한다.

로 진행되었습니다. 
때문에 서로 다른 책임을 갖는 두 클래스가 모두 `Player`에게 소속될 수 있다는 공통된 특성을 가져야 했어요.

제네릭은 이미 `Name`을 통해 소속되던 코드가 `Player`로 변경된 적이 있으니 변경에 대해 확장성을 열어두어야 하나 라는 생각으로 사용해 주었었는데요, 확실한 오버엔지니어링이라 느껴지네요 ㅎㅎ;;;

2024-03-17 07:46 UTC, zangsu commented on src/main/java/blackjack/domain/game/PlayerResult.java
> +    private final GameResult gameResult;
사실, 외래키는 설명을 위해 비유적으로 가져온 표현이기는 합니다...ㅎㅎ
한번 `Player`를 감싸는 객체를 새로 만들어 보겠습니다!!

2024-03-17 07:47 UTC, zangsu commented on src/main/java/blackjack/domain/Ownable.java
> +    default boolean ownedSameOwner(Ownable<O> object) {
다른 코멘트에서 언급했던 것 처럼, 해당 메서드는 `OwnedMoney`와 `PlayerResult`를 비교하며 동일한 소유주인지 확인하기 위한 메서드였습니다!

2024-03-17 12:16 UTC, zangsu commented on src/main/java/blackjack/domain/game/GameResult.java
> +    PLAYER_LOSE((OwnedMoney bet) -> bet.multiply(-1)),
오버엔지니어링 이었다는 것에 동의합니다...!
리팩토링 완료하였습니다!

2024-03-18 03:35 UTC, ddaaac approved these changes
안녕하세요 짱수 👋 

블랙잭 미션 고생 많으셨습니다.

다음 미션도 화이팅하세요!

2024-03-18 03:35 UTC, ddaaac commented on src/main/java/blackjack/domain/participant/BettingPlayer.java
> +    }
https://github.com/woowacourse/java-blackjack/pull/723#discussion_r1526004943

2024-03-18 03:35 UTC, ddaaac commented on src/main/java/blackjack/domain/participant/BettingPlayer.java
> +    }
여러 개의 생성자가 있다면 [생성자 체이닝](https://developer-talk.tistory.com/227)에 대해 고려해볼만 할 것 같아요.

2024-03-18 03:35 UTC, ddaaac commented on src/main/java/blackjack/domain/Ownable.java
> +    default boolean ownedSameOwner(Ownable<O> object) {
말씀해주신 그대로라면 OwnedMoney.ownedSameOwner(PlayerResult)로 만들어도 되지 않았었나는 코멘트였습니다.

2024-03-18 03:35 UTC, ddaaac commented on src/main/java/blackjack/domain/participant/Players.java
> +        for (int index = 0; index < names.size(); index++) {
둘 사이즈가 같다는 검증 정도 넣어주면 좋겠네요.

2024-03-18 03:35 UTC, ddaaac commented on src/main/java/blackjack/domain/participant/Players.java
> +    public static Players from(List<String> names, List<Integer> bets) {
값 객체의 포장은 입력을 받은 시점에 바로 해도 좋아보이네요.
https://github.com/woowacourse/java-blackjack/pull/745#discussion_r1527434483 이 코멘트를 참고해도 좋을 것 같아요.

2024-03-18 03:35 UTC, ddaaac commented on src/main/java/blackjack/domain/game/BlackJackGame.java
> +    public BlackJackGame(List<String> names, List<Integer> bets) {
값 객체의 생성 시점과 비슷하게 Players는 컨트롤러에서 만들어줘도 될 것 같아요. Game은 생성자로 Players를 받아도 되구요.
names + bets -> Players로의 변환 책임을 꼭 Game이 가져갈 필요는 없어보이네요.

2024-03-18 03:36 UTC, merged

2024-03-18 05:45 UTC, zangsu commented on src/main/java/blackjack/domain/Ownable.java
> +    default boolean ownedSameOwner(Ownable<O> object) {
아하...! 충분히 추상화 없이도 해결할 수 있는 문제가 복잡해 진 것 같네요!
처음 구현을 할 때는 `Comparator`와 비슷하게 구현할 수 있겠다 라는 생각을 한 것 같아요.

2024-03-18 05:56 UTC, zangsu commented on src/main/java/blackjack/domain/participant/BettingPlayer.java
> +    }
범블비가 Step1에서 해 주셨던 "디폴트 접근 제어자는 큰 의미가 없습니다." 라는 리뷰의 연장선이라고 느껴집니다.
[#616 (comment)](https://github.com/woowacourse/java-blackjack/pull/616#discussion_r1519564323)

테스트에서만 사용할 생성자이기에 default 접근제어자를 사용하는 것이 습관이 되었던 것 같네요!
다만, 프로덕션에서 사용할 목적으로 생성된 것이 아니기에 `new BettingPlayer()`를 입력했을 때 해당 메서드 시그니처가 자동완성으로 보여지는 것이 프로그래머의 편의성을 저해하지 않을까 라는 고민도 드는 것 같아요. 
생성자는 많이 제공해 줄 수록 유연성이 높아진다는 말을 이번 미션동안 정말 많이 접할 수 있었으니 긍정적으로 수용해보겠습니다!

2024-03-18 06:44 UTC, zangsu commented on src/main/java/blackjack/domain/participant/BettingPlayer.java
> +    }
주생성자 / 부생성자와 같은 개념이군요!
`Value`에서 적용한 것 처럼 이곳에서도 도입해 보겠습니다.

2024-03-18 06:44 UTC, zangsu commented on src/main/java/blackjack/domain/participant/Players.java
> +        for (int index = 0; index < names.size(); index++) {
확인했습니다!

2024-03-18 06:57 UTC, zangsu commented on src/main/java/blackjack/domain/participant/Players.java
> +    public static Players from(List<String> names, List<Integer> bets) {
지금까지 항상 래퍼 클래스를 포함한 모든 클래스 생성을 최대한 `Controller`와 분리를 시키려고 했던 것 같아요.
왜그랬는지는 잘 모르겠네요....ㅎㅎ
이번에 범블비의 리뷰를 받고 나서 MVC를 다시 공부해 보면서 `Controller`의 책임에 `view`와 `Model` 사이에서의 데이터 변환이 존재한다는 것을 알게 되었습니다. `Controller`에서 객체를 생성해서 넘겨줘 보겠습니다.

2024-03-18 08:05 UTC, zangsu commented on src/main/java/blackjack/domain/participant/BettingPlayer.java
> +    }
코드를 아래와 같이 바꾸어 보았습니다.
```java
public BettingPlayer(Player player, Money bet) { //새로 추가된 생성자
        this.player = player;
        this.bet = bet;
    }

    public BettingPlayer(Name name, Money bet) {
        this(Player.from(name), bet);
    }

    public BettingPlayer(List<Card> cards, Money bet) {
        this(new Player(cards, new Name("name")), bet);
    }
```

모든 생성자를 `public`으로 제공해 줌과 동시에, 모든 부생성자가 주생성자를 체이닝하도록 구현해 보았습니다. 괜찮아 보이는데, 주생성자가 모든 필드를 전부 파라미터로 받는 것이 지금까지의 제 코드와는 조금 달라져서 어색한 것 같아요. 이런 주생성자가 "캡슐화를 깨뜨린다."고 보지는 않아도 괜찮겠죠??

2024-03-18 11:44 UTC, ddaaac commented on src/main/java/blackjack/domain/participant/BettingPlayer.java
> +    }
- 이전에도 코멘트 드린것처럼 생성자는 객체 입장에서 바라봐야합니다. "name"이란 디폴트로 이름을 넣어주는 생성자는 객체 입장에서 너무 어색합니다. 외부에서도 어떻게 동작할지 모를 확률이 높구요. 테스트 관련해서 사용할거라면 테스트에 유틸쪽으로 빼는 게 좋아보이네요.
- 생성자를 노출한다고 내부 구현이 외부에 노출되지는 않습니다. 클라이언트 입장에서 생각해보면 Player와 Money를 넣으면 이 객체가 생성되는구나 정도로 이해하겠죠.