[2단계 - 블랙잭 배팅] 켬미(김경미) 미션 제출합니다.
woowacourse/java-blackjack pull request #729
Opened 2024-03-15 09:03 UTC by kyum-q

안녕하세요 🤠비밥🤠 이번에 2단계 리뷰도 받게 된 켬미라고 합니다!
저번 리뷰들로 인해 많은 고민을 하였고, 그만큼 코드가 많이 변화된 것 같아요😊
비밥의 피드백으로 한 층 성장하였고, 이번 단계에서도 많이 성장하고 싶어요! 그러니 거침없는 피드백 해주시면 감사하겠습니다 !

<br>

## 궁금합니다 !

코드를 작성하면서 몇 가지 궁금한 점이 있었습니다.

<br>

### view에게 필요한 인자를 전달할 때, 객체 자체를 전달하는 것과 (최대한) 원시 값 전달 중에 뭐가 좋을까요?

이번에 view로 최소한의 데이터만 전달하려고 하였습니다. 그렇다보니 인자에 데이터만 보고 해당 데이터가 무엇을 의미하는지 파악하기가 저 또한 어렵다는 생각이 들었습니다.
 
제가 최소한의 데이터만 전달하려고 하는 이유는 그럴리는 없짐나 혹시나 view에서 도매인의 변경을 시도하지 못하게 하기 위해서 입니다.

예를 들어, `Map<String, List<Card>> usersNameAndCards`를 봤을 때 `String`이 의미하는 것이 무엇인지 헷갈리더라고요.. 또한 `List<Card>`라고 작성해놓으니 너무 복잡한 데이터처럼 보이더라고요..! 

그래서 고민 끝에 `Map<Name, Cards> usersNameAndCards` 로 래핑된 객체를 전달하도록 변경하였습니다.

이렇게 하니까 제가 생각하기에 view에서 봤을 때도 무엇을 위해 받은 인자인지 명확해졌다고 생각해요! 😊

이렇게 가독성의 문제가 될 수 없는 정도로만 객체를 최소화해서 전달하는 것이 좋다고 생각하는데, 이에 대해 비밥의 의견이 궁금합니다 !

비밥은 view에게 정보를 전달할 때 최소한의 객체로 전달하는지, 아니면 그냥 해당 정보를 가지고 있는 객체 자체 전달하는지 궁금합니다 🤔

### 필요한 인자만 인스턴스로 전달, 및 클래스 전달
딜러에 정보를 통해 참가자의 승패 여부를 결정하는 메서드가 있습니다.  `public Outcome findOutcome(Dealer dealer)`

위에 내용과 비슷한 내용이지만,  이부분도 처음에는 Dealer 자체를 넘겨주었다가 그냥 필요한 정보만 넘기는게 어떨까라는 생각이 들어 `public Outcome findOutcome(boolean isOtherNotHit, int otherDifference)` 로 변경하였습니다.

근데 이러고 보니 인자가 하나 더 추가되기도하고, dealer와만 비교하여 승패를 알아내야하는데 참가자와도 비교할 수도 있고 사실상 그냥 아무 boolean, int 값을 전달하여 가상의 객체와 비교할 수 도 있게 되더라고요..🤔

그래서 이런 단점보다 딜러의 변화가 일어나더라도 딜러자체를 넘겨주는 것이 좋다고 판단하여 최종적으로는 
`public Outcome findOutcome(Dealer dealer)`로 구현하였습니다!

이것도 단순히 비밥의 의견이 궁금합니다 !
비밥이라면 이런 상황에 어떤 방식을 선호하시는지, 이유가 있다면 무엇인지 궁금합니다 😊

<br>

### List<Name>과 이익 값을 래핑하는 게 좋을까요?
List<Name>을 래핑하지 않은 이유는 List<Name>이 사용되는 부분은 입력 받고 participant 제작 전, 다른 말로는 배팅 금액을 입력받기 위해서만 존재한다고 생각하기 때문입니다. 
즉, 따로 도매인의 역할을 하지 않는다고 생각해서 래핑하지 않았습니다.
또한 이익 값은 출력시에만 사용되기 때문에 래핑하지 않았습니다.

즉 이렇게 view를 위해 잠시동안 생성되고 사용되는 것들에 대해서도 래핑을 해야하는지 비밥의 의견이 궁금합니다 !

<br>

---

2024-03-16 06:17 UTC, pci2676 commented
> ### view에게 필요한 인자를 전달할 때, 객체 자체를 전달하는 것과 (최대한) 원시 값 전달 중에 뭐가 좋을까요?
> 이번에 view로 최소한의 데이터만 전달하려고 하였습니다. 그렇다보니 인자에 데이터만 보고 해당 데이터가 무엇을 의미하는지 파악하기가 저 또한 어렵다는 생각이 들었습니다.
> 
> 제가 최소한의 데이터만 전달하려고 하는 이유는 그럴리는 없짐나 혹시나 view에서 도매인의 변경을 시도하지 못하게 하기 위해서 입니다.
> 
> 예를 들어, `Map<String, List<Card>> usersNameAndCards`를 봤을 때 `String`이 의미하는 것이 무엇인지 헷갈리더라고요.. 또한 `List<Card>`라고 작성해놓으니 너무 복잡한 데이터처럼 보이더라고요..!
> 
> 그래서 고민 끝에 `Map<Name, Cards> usersNameAndCards` 로 래핑된 객체를 전달하도록 변경하였습니다.
> 
> 이렇게 하니까 제가 생각하기에 view에서 봤을 때도 무엇을 위해 받은 인자인지 명확해졌다고 생각해요! 😊
> 
> 이렇게 가독성의 문제가 될 수 없는 정도로만 객체를 최소화해서 전달하는 것이 좋다고 생각하는데, 이에 대해 비밥의 의견이 궁금합니다 !
> 
> 비밥은 view에게 정보를 전달할 때 최소한의 객체로 전달하는지, 아니면 그냥 해당 정보를 가지고 있는 객체 자체 전달하는지 궁금합니다 🤔

가능한 필요한 객체를 전달하는 편입니다.

다만 말씀하신것 처럼 변경이 가해질 수 있는 객체는 전달하지 않고 불변한 객체를 위주로 전달합니다. 일종의 불변한 값 객체들이 전달되는 편 입니다.

2024-03-16 06:19 UTC, pci2676 commented
> ### 필요한 인자만 인스턴스로 전달, 및 클래스 전달
> 딜러에 정보를 통해 참가자의 승패 여부를 결정하는 메서드가 있습니다. `public Outcome findOutcome(Dealer dealer)`
> 
> 위에 내용과 비슷한 내용이지만, 이부분도 처음에는 Dealer 자체를 넘겨주었다가 그냥 필요한 정보만 넘기는게 어떨까라는 생각이 들어 `public Outcome findOutcome(boolean isOtherNotHit, int otherDifference)` 로 변경하였습니다.
> 
> 근데 이러고 보니 인자가 하나 더 추가되기도하고, dealer와만 비교하여 승패를 알아내야하는데 참가자와도 비교할 수도 있고 사실상 그냥 아무 boolean, int 값을 전달하여 가상의 객체와 비교할 수 도 있게 되더라고요..🤔
> 
> 그래서 이런 단점보다 딜러의 변화가 일어나더라도 딜러자체를 넘겨주는 것이 좋다고 판단하여 최종적으로는 `public Outcome findOutcome(Dealer dealer)`로 구현하였습니다!
> 
> 이것도 단순히 비밥의 의견이 궁금합니다 ! 비밥이라면 이런 상황에 어떤 방식을 선호하시는지, 이유가 있다면 무엇인지 궁금합니다 😊

메서드를 설계할때는 메서드를 다른 사람이 사용할때 잘못된 사용을 방어하는 것이 굉장히 중요하다고 생각합니다.

> 근데 이러고 보니 인자가 하나 더 추가되기도하고, dealer와만 비교하여 승패를 알아내야하는데 참가자와도 비교할 수도 있고 사실상 그냥 아무 boolean, int 값을 전달하여 가상의 객체와 비교할 수 도 있게 되더라고요..🤔

위 처럼 적어주셨는데 이러한 부분을 방어하는게 중요하다고 생각합니다.

그러한 이유에서 소통에 직접적으로 참여하는 객체를 가능한 매개변수로 전달하는 편입니다.

2024-03-16 06:46 UTC, pci2676 commented
> ### `List<Name>`과 `이익 값`을 래핑하는 게 좋을까요?
> `List<Name>`을 래핑하지 않은 이유는 `List<Name>`이 사용되는 부분은 입력 받고 participant 제작 전, 다른 말로는 배팅 금액을 입력받기 위해서만 존재한다고 생각하기 때문입니다. 즉, 따로 도매인의 역할을 하지 않는다고 생각해서 래핑하지 않았습니다. 또한 `이익 값`은 출력시에만 사용되기 때문에 래핑하지 않았습니다.
> 
> 즉 이렇게 view를 위해 잠시동안 생성되고 사용되는 것들에 대해서도 래핑을 해야하는지 비밥의 의견이 궁금합니다 !

`matchNameAndRevenues`를 말씀하시는 것 일까요?

별도의 도메인으로써 역할을 수행하지 않는다면 저도 객체로 랩핑하지 않습니다. 😄

2024-03-16 06:57 UTC, pci2676 requested changes
전체적으로 코드가 깔끔한것 같습니다.

질문 주신 부분에 대한 답변과 리뷰를 조금 남겨두었으니 확인해주세요.

2024-03-16 06:57 UTC, pci2676 commented on src/test/java/model/card/CardDeckTest.java
> +            cardDeck.selectRandomCard();
테스트에서 반복문은 없는것이 좋습니다.

일련의 로직이 테스트에 포함되면 테스트를 파악하기 힘든 요소가 됩니다.

2024-03-16 06:57 UTC, pci2676 commented on src/test/java/model/player/DealerTest.java
> +                Card.of(Suit.SPACE, Denomination.TWO))));
테스트에서 상태를 가지는 객체는 가능한 공유하지 않는것이 좋습니다.

새로운 테스트 코드에서 dealer를 이용한 테스트 코드를 작성하려면

기존 dealer의 상태를 파악하는 작업이 선행됩니다.

이러한 상태는 새로운 테스트 코드를 짜는 입장과 테스트 코드를 읽는 입장 모두에게 좋지 않게 작용할 수 있습니다.

2024-03-16 06:57 UTC, pci2676 commented on src/test/java/model/player/NameTest.java
> +        }).isInstanceOf(IllegalArgumentException.class);
테스트에서 exception을 검사할 때 exception 타입만 검사하는 것은 조금 위험할 수 있습니다.

제가 이전에 말씀드렸는지 모르겠는데 거짓양성과 거짓음성에 대해 알아보시면 좋을것 같습니다.

2024-03-16 06:57 UTC, pci2676 commented on src/main/java/model/player/Participant.java
> +        this.gameMoney = gameMoney;
Participant가 3개의 멤버변수를 가지고 있는것으로 볼 수 있을것 같습니다.

2024-03-17 05:23 UTC, kyum-q commented on src/test/java/model/card/CardDeckTest.java
> +            cardDeck.selectRandomCard();
테스트에서 반복문을 제거하고 stream을 사용하도록 코드를 수정하였습니다. 😊

혹시 stream을 사용하는 것도 일련의 로직이 테스트에 포함되는 것일까요? 또 다른 좋은 방법이 있는지 궁금합니다. 😁

2024-03-17 05:33 UTC, kyum-q commented on src/test/java/model/player/DealerTest.java
> +                Card.of(Suit.SPACE, Denomination.TWO))));
도매인의 변경이 발생했을 때 수정하기 쉽고 테스트 코드의 중복된 코드를 배제하고자 BeforeEach를 쓰는 버릇이 생겼었나봐요..! 어쩌면 개발자(저)의 편의를 위해 사용하지 않았나라는 생각이 드네요.

비밥의 의견처럼 이 방식의 가져올 단점에 대해 생각해보지 않았던 것 같아요. 
해당 코드는 상태를 가지는 객체들이 공유되지 않도록 각 테스트에서 해당 객체를 생성하도록 수정 하였습니다 😊

2024-03-17 08:16 UTC, kyum-q commented on src/main/java/model/player/Participant.java
> +        this.gameMoney = gameMoney;
ParticipantProfile 클래스를 통해 name과 gameMoney를 가지도록 구현하였습니다😊

2024-03-17 08:52 UTC, kyum-q commented on src/test/java/model/player/NameTest.java
> +        }).isInstanceOf(IllegalArgumentException.class);
`hasMessage`를 사용해서 예외가 제대로 발생하였는지 확인하도록 수정하였습니다. 😊

2024-03-17 08:54 UTC, kyum-q commented
비밥이 남겨주신 리뷰 보고 테스트를 수정하면서 ㅇ다른 테스트들도 경계값을 확인하도록 하여 정확성을 올렸습니다.  😊
이 외에도 몇가지 출력 오류와 필요없는 public 메서드들이 있어 변경하였습니다. 😁

2024-03-17 23:50 UTC, pci2676 commented on src/test/java/model/card/CardDeckTest.java
> +            cardDeck.selectRandomCard();
stream을 사용해도 동일한 문제가 있어 보입니다.

반복문을 사용해야하는 이유가 무엇인지, 그렇다면 이유가 되는 부분에 대한 제어가 온전히 이루어지는지를 생각해보면 좋을것 같습니다.

2024-03-18 00:05 UTC, pci2676 requested changes
이번 미션은 마무리지어도 큰 문제가 없을것 같습니다.

리뷰를 조금 남겨두었는데 (꼭 반영하실 필요는 없습니다.)   
확인해주시고 다시 PR주시면 머지하도록 하겠습니다.

2024-03-18 00:05 UTC, pci2676 commented on src/main/java/model/player/ParticipantsBuilder.java
> +public class ParticipantsBuilder {
개선을 바라는 리뷰가 아니니 그냥 읽고 넘기셔도 좋습니다.

빌더를 사용하셨는데 여기서 검증하고 있는 부분이 Participants에도 동일하게 있는것 같아보입니다.

두 코드가 약간이라도 서로 다른 검증을 한다면 문제가 발생할수도 있을것 같습니다.

빌더 패턴을 반드시 사용해야하는 이유가있었는지 고민해보시면 좋을것 같습니다.

2024-03-18 00:05 UTC, pci2676 commented on src/main/java/model/BlackJack.java
> +public class BlackJack {
블랙잭도 3개의 인스턴스 변수를 가지고 있네요

2024-03-18 00:05 UTC, pci2676 commented on src/main/java/model/BlackJack.java
> +                .sum() * -1;
저는 일급컬렉션을 너무 많이 만드는것을 별로 좋아하지는 않지만 이 부분도 누군가의 책임으로 추출할수도 있을것 같습니다.

2024-03-18 00:05 UTC, pci2676 commented on src/main/java/model/BlackJack.java
> +public class BlackJack {
한번 쯤 고민해보시면 좋을것 같은 부분은

인스턴스 변수의 상호간 응집도가 높은지에 대해 고민해보시면 좋을것 같습니다.

2024-03-18 05:32 UTC, kyum-q commented on src/main/java/model/player/ParticipantProfile.java
> +    }
비밥의 의견은 해당 Map을 그대로 view에 전달하지 말고, 컨트롤러에서 해당 Map을 dto로 한번 더 묶어서 전달하는 것인가요?

제가 생각했을 때, Dto의 장점은 뷰에서 객체의 변화를 막기 위해 도와주는 것이라고 생각합니다. 😊
그런데 현재 Map으로 전달하고 있는 객체들도 Name, Integer로 불변한 객체 혹은 원시 값이라고 생각합니다. (Name에 setter가 존재하지 않아 수정될 수가 없다.)  그렇다면 굳이 왜 dto로 감싸야할까? 라는 생각이 드는 것 같아요!
혹시 제가 모르는 dto의 장점이 또 있을까요? 해당 코드를 dto로 수정했을 때 좋은 점은 무엇일지 모르겠습니다 🤔

2024-03-18 05:43 UTC, kyum-q commented on src/main/java/model/player/ParticipantsBuilder.java
> +public class ParticipantsBuilder {
맞아요 저도 해당 부분에 대해 고민을 많이 했던 것 같아요 !
하지만 필요하다면 중복 검증은 나쁘지 않다고 생각합니다. 해당 부분의 검증은 사용자 입력을 받자마자 검증하기 위한 검증, Participants의 검증은 개발자의 잘못으로 객체가 잘못 생성될 수 있기 때문에 중복 검증하였습니다 !

그리고 빌더 패턴을 사용한 이유는 객체 생성 인자가 많다고 판단하여 생성의 편리함을 위해 구현하였습니다 😊

2024-03-18 07:08 UTC, kyum-q commented on src/main/java/model/BlackJack.java
> +                .sum() * -1;
Participants와 Dealer를 가지고 있는 Users를 제작하여 해당 로직을 Users의 담당으로 변경하였습니다 !

2024-03-18 07:09 UTC, kyum-q commented on src/main/java/model/BlackJack.java
> +public class BlackJack {
현재 participants와 dealer와의 응집도는 높은 편에 속한다고 생각합니다 ! 하지만 클래스 내에 응집도가 높은 것은 안좋은 것이 아니라고 생각해서 Users로 그들을 묶기만 하고 추가적인 코드 변경은 하지 않았습니다 😊

2024-03-18 07:20 UTC, kyum-q commented on src/test/java/model/card/CardDeckTest.java
> +            cardDeck.selectRandomCard();
해당 부분에 대해 곰곰이 고민해본 결과 그냥 `생성 시에 카드가 꼭 52장이어야할까?` 라는 생각을 하였습니다.
생각해보니 굳이 그럴 필요 없다고 판단하였고 CardDeck에서 52장임을 확인하는 로직을 제거하였습니다. 
그렇게 하니 테스트 코드가 
```java
    @DisplayName("덱이 비어있을 때 카드를 뽑으면 예외가 발생한다.")
    @Test
    void validateNotEmpty() {
        CardDeck cardDeck = new CardDeck(List.of());

        assertThatThrownBy(cardDeck::selectRandomCard)
                .isInstanceOf(IllegalStateException.class)
                .hasMessage("더 뽑을 카드가 없습니다.");

    }
```
로 더 간단하게 변경되었습니다 ! 감사합니다 비밥😊

2024-03-18 07:22 UTC, kyum-q commented
비밥 친절한 리뷰 감사했습니다 ! 정말 비밥 덕분에 새로운 시야를 알게 되었고, 색다른 방법들을 많이 사용해본 것 같아요 (함수형 인터페이스, 정적 팩토리 메서드 등) 😊

2024-03-18 22:49 UTC, merged