[2단계 - 블랙잭 베팅] 카고(정민호) 미션 제출합니다.
woowacourse/java-blackjack pull request #740
Opened 2024-03-16 04:14 UTC by devhoya97

스티치 안녕하세요 !!

기능 구현은 목요일에 마쳤는데, 객체마다 책임을 적절하게 분리시키기 위해서 리팩토링하다보니 시간이 많이 늦어졌습니다...!

이번에도 리뷰 잘 부탁드립니다 :) 좋은 주말 되세요 !!!!

2024-03-16 15:35 UTC, lxxjn0 requested changes
카고, 2단계 미션 진행하시느라 수고하셨습니다!

코드는 기존의 로직에서 크게 변경된 부분은 없어보여서 간단한 부분들에 대해 피드백 남겨보았습니다. 추가로 최근에 상태패턴에 대해서 수업을 들었다고 하던데 혹시 관심이 있다면 한번 적용해보는 것도 좋을 것 같습니다 :)

2024-03-16 15:35 UTC, lxxjn0 commented on src/test/java/blackjack/domain/GamersTest.java
> +}
테스트가 없는 테스트 코드인데 사용하지 않는다면 지워주세요 :)

2024-03-16 15:35 UTC, lxxjn0 commented on src/main/java/blackjack/domain/gamers/Gamers.java
> +public class Gamers {
해당 클래스를 보면 결국 dealer 또는 Players의 메서드를 호출만 해주는 역할을 하는 것 같아 보입니다. 메서드를 보면 Player 또는 Dealer를 특정지어 수행시키는 메서드가 많은 만큼 두 프로퍼티를 하나로 묶지 않고 관리하는 것이 더 좋아보이는데 어떻게 생각하시나요?

2024-03-16 15:35 UTC, lxxjn0 commented on src/main/java/blackjack/domain/result/Bettings.java
> +                ));
stream을 사용하는 것도 좋지만 key와 value가 잘 드러나지 않다보니 가독성이 약간 떨어지는 것 같아요. forEach를 활용해서 한번 바꿔보는 것은 어떨까요?(사실 어떤 방향이 더 나은 가독성을 제공할 지는 모르겠지만 한번 시도해보시고 카고가 보시기에 더 나은 방향으로 결정해봐도 좋을 것 같습니다)

2024-03-16 15:35 UTC, lxxjn0 commented on src/main/java/blackjack/domain/result/Bettings.java
> +    private static final int PUSH_PROFIT_MULTIPLIER = 0;
해당 값들을 PlayerOutcome에서 관리해보는 것은 어떨까요?

2024-03-16 15:35 UTC, lxxjn0 commented on src/main/java/blackjack/domain/result/Judge.java
> +    private final Dealer dealer;
판단을 하는 객체가 딜러를 가지고 있는 것이 어색해보입니다. 적절한 판단 로직만 가지고 있으면서 필요에 따라 dealer를 전달받거나 하는 식으로 풀어보는 것은 어떨까요?

2024-03-16 15:35 UTC, lxxjn0 commented on src/main/java/blackjack/domain/result/Money.java
> +    }
아니면 int로 파라미터를 받고 생성 시점에 에러 등으로 int가 아닌 값을 처리하는 것은 어떨까요?

2024-03-17 02:20 UTC, devhoya97 commented on src/test/java/blackjack/domain/GamersTest.java
> +}
넵 반영했습니다 !!

2024-03-17 03:42 UTC, devhoya97 commented on src/main/java/blackjack/domain/gamers/Gamers.java
> +public class Gamers {
동의합니다. 사실 Step1에서의 GameBoard의 이름을 Gamers로 바꾸다보니 이렇게 됐어요. 

Step1에서는 Main(컨트롤러)이 모든 domain 객체에 대해서 잘 알 필요는 없고, 오직 GameBoard라는 domain 객체와 상호작용함으로써 애플리케이션의 목적을 달성할 수 있도록 설계하고 싶었고, 실제로 GameBoard 객체를 생성할 때를 제외하곤 다른 domain 객체에 대해선 알 필요가 없도록 설계했어요.

그런데 Step2에서 `플레이어의 수익 계산` 기능을 GameBoard에게 추가하려다보니 GameBoard 객체에 너무 과중한 책임이 들어가게 됐어요. 그래서 기본적인 게임 진행(초기카드 뽑기, 추가카드 뽑기, 카드 보여주기)에 필요한 기능만을 남기다 보니 Gamer들을 관리하는 객체의 모습이 되어서 이름을 GameBoard -> Gamers로 바꾸게 되었습니다.

그런데 스티치의 말대로 그냥 Main에서 Player와 Dealer에 대해 각각 관리하는게 더 좋아보이네요 ^^;;

이렇게 장황하게 제 생각을 말씀드린 이유는, 애초에 Step1에서 GameBoard를 설계하려 했던 의도가 잘못된 방향이었나? 생각이 들어서입니다. `Main(컨트롤러)이 최소한의 domain 객체와 소통하도록 만들자` 라는 방향성에 대해 어떻게 생각하시나요?

2024-03-17 04:36 UTC, devhoya97 commented on src/main/java/blackjack/domain/gamers/Gamers.java
> +public class Gamers {
> 그런데 스티치의 말대로 그냥 Main에서 Player와 Dealer에 대해 각각 관리하는게 더 좋아보이네요 ^^;;

우선 이 부분은 코드로 반영하였습니다 !

2024-03-17 07:00 UTC, devhoya97 commented on src/main/java/blackjack/domain/result/Bettings.java
> +                ));
forEach를 사용해본 경험이 거의 없어서, Map에 대해 forEach를 쓸 생각을 못했네요..! 그래서 당시 Collectors.toMap을 이용했어요.

아래와 같이 forEach를 사용하니 bettings가 가진 key, value가 드러나 가독성이 좋아진 것 같아요. 근데 첫 줄에 빈 Map을 생성하지 않는 방법은 없겠죠 ??

```java
public Map<Name, Money> calculatePlayerProfits(final Judge judge) {
    final Map<Name, Money> playerProfits = new LinkedHashMap<>();
    bettings.forEach((player, betting) ->
        playerProfits.put(player.getName(), calculateProfit(betting, judge.calculatePlayerOutcome(player))));

    return playerProfits;
}
```

2024-03-17 07:09 UTC, devhoya97 commented on src/main/java/blackjack/domain/result/Bettings.java
> +    private static final int PUSH_PROFIT_MULTIPLIER = 0;
헐 그렇네요. 왜 이 생각을 못했을까요. 좋은 포인트 지적 감사드립니다!!

2024-03-17 07:20 UTC, devhoya97 commented on src/main/java/blackjack/domain/result/Money.java
> +    }
배팅금액 또는 블랙잭으로 1.5배가 된 상금을 소수점 단위까지 가능하게 만들고 싶어서 Money는 double로 관리하고 있는데요. 위 기능은 사실 소수점 아래 값이 없을 때, 콘솔 출력시 `10000.0` 과 같이 뒤에 붙는 `.0`을 제거하기 위해 필요한 로직입니다.

말씀드리고 보니, 이는 명백히 view를 위한 로직이기에 OutputView에게 위 기능을 위임하도록 변경했습니다 !

2024-03-17 07:22 UTC, devhoya97 commented
세심한 피드백 감사드립니다 스티치!! DM 드린 내용과 관련해 고민이 해결되면 상태패턴으로 리팩토링을 다시 해보겠습니다 !! :)

2024-03-18 00:51 UTC, devhoya97 commented on src/main/java/blackjack/domain/result/Judge.java
> +    private final Dealer dealer;
DM드린 내용을 바탕으로 Judge가 static 메서드만을 갖게끔 리팩토링 완료했습니다! 

사실 static 메서드만을 갖는 클래스는 어디서든 객체를 생성할 필요 없이 접근할 수 있다는 측면에서, 여기저기 개입할 여지가 있어 보이고 마치 Util 클래스처럼 사용될 수 있어 꺼렸는데요. 클래스를 public 으로 열어주지 않고 default로 열어줌으로써 같은 result 패키지에 속한 클래스들만 Judge를 Util처럼 사용할 수 있도록 제한해보았습니다!

2024-03-18 00:58 UTC, devhoya97 commented
리팩토링 작업중 간단한 질문 하나가 더 생겼는데요 ..! ㅎㅎ

`List<Player>`를 관리하는 일급컬렉션 Players가 기존에 하는 역할이 너무 모호해보였습니다. 따라서 Players가 갖는 `getPlayers` 메서드를 Dto를 생성할 때 외에는 사용하지 않도록 변경하고, Main에서 Player와 관련된 메시지를 보내고 싶다면, 항상 `Name`을 가지고 Players에게 접근하도록 변경해보았습니다.

너무 돌아가는 느낌이 들기도 하는데.. 이에 대해 어떻게 생각하시나요 ?!

2024-03-19 04:47 UTC, lxxjn0 approved these changes
카고, 피드백 반영하시느라 수고하셨습니다! 

코드는 전체적으로 잘 정리된 것 같고 추가로 드릴만한 피드백은 없어보입니다 👍🏼 그리고 여쭤보신 질문에 대해서는 일급 컬렉션을 쓰려고 하면 어쩔 수 없는 부분일 것 같기도 합니다. 도메인을 컬렉션 단위로 수행할 행위가 많다면 일급 컬렉션을 사용하는 것이고, 개별로 수행할 행위가 많다면 그냥 리스트를 필드로 가지고 수행할 것 같아요. 결국 코드 상에서 어떻게 관리하는 것이 더 이득일지 생각해서 고르면 될 것 같습니다!

미션 진행하시느라 수고 많으셨습니다 :)

2024-03-19 04:47 UTC, merged

2024-03-20 00:54 UTC, devhoya97 commented on src/main/java/blackjack/domain/gamers/Gamers.java
> +public class Gamers {
넵!! 이번 미션에서는 도메인 객체 설계보다 오히려 컨트롤러와 도메인 간 소통을 고민한 시간이 길었던 것 같네요..! 현 시점에서는 말씀해주신대로 도메인 객체 설계에 더 집중하는게 맞는 것 같아요!