[2단계 - 블랙잭 베팅] 폰드(권규택) 미션 제출합니다.
woowacourse/java-blackjack pull request #749
Opened 2024-03-17 06:48 UTC by tackyu

안녕하세요 영이, 6기 BE 폰드 입니다.
 
제출이 늦어 죄송합니다.
이번 미션에서는 Result에 게임 결과 판별을 하는 책임을 더 주게 되었고, 
새로 추가된 베팅 정보와 수익 계산등은 MoneyManager라는 클래스를 통해서 관리하도록 설계하였습니다.

Result Enum의 역할이 더 커짐에 따라 코드가 좀 조악해진 것 같습니다.
Result에 대한 영이의 의견을 여쭙고 싶습니다.

감사합니다!

2024-03-17 09:36 UTC, choijy1705 requested changes
폰드 2단계 잘 진행해주셨네요!
전체적으로 깔끔한 코드인것 같습니다👍
몇가지 코멘트 남겼으니 확인해봐주세요!

2024-03-17 09:36 UTC, choijy1705 commented on src/main/java/controller/GameController.java
>      }
user를 생성할때 이름과 배팅금액을 함께 받아서 생성하면 map을 만드는 과정이 필요없지 않을까요??

2024-03-17 09:36 UTC, choijy1705 commented on src/main/java/controller/GameController.java
> +    private void hitOrStayOnce(Game game, Player player) {
메서드명에 once는 어떤걸 의미하나요?
hitOrStay로 표현해도 될것 같아서 질문드립니다!

2024-03-17 09:36 UTC, choijy1705 commented on src/main/java/controller/GameController.java
> +    private void notifyBust(State state, UserDto userDto) {
출력하는 동작에 메서드명이 두가지를 혼용하고 있는것 같네요!
show 와 notify 중 하나만 일관적으로 사용하도록 하는게 어떨까요?

2024-03-17 09:36 UTC, choijy1705 commented on src/main/java/domain/game/Result.java
> +    public static Result blackjackCompare(boolean current, boolean opponent) {
dealer와 player일 것 같은데 
current, opponent로 표현하면 헷갈릴것 같아요
좀 더 구체적으로 하면 isDealerBlackjack, isPlayerBlackjack 으로 명명해야 혼동을 안줄것 같네요

2024-03-17 09:36 UTC, choijy1705 commented on src/main/java/domain/money/Money.java
> +            throw new NumberFormatException("양의 정수만 입력하세요.");
NumberFormatException으로 throw하는게 적절할지는 모르겠네요
-1000이 numberFormat 에러는 아닌것 같아서요

2024-03-17 09:36 UTC, choijy1705 commented on src/main/java/domain/money/Money.java
> +        validate();
```suggestion
        try {
            int value = Integer.parseInt(rawValue);
            validate(value);
            this.value = value;
        } catch (NumberFormatException ne) {
            throw new NumberFormatException("양의 정수만 입력하세요.");
        }
```
validate가 try-catch 밖에 있어서 놓치기 쉬울것 같네요

2024-03-17 09:36 UTC, choijy1705 commented on src/main/java/domain/money/MoneyManager.java
> +    private final Map<Player, Money> bettingManager;
player가 money를 필드로 가지고 있으면 안될지 
체크해봐주세요!

2024-03-17 09:36 UTC, choijy1705 commented on src/main/java/domain/money/Money.java
> +    private final int value;
돈과 관련된거라면 BigDecimal을 사용하는게 어떨까요?
BigDecimal 학습해보시고 적용해보면 좋을것 같습니다!

2024-03-17 09:36 UTC, choijy1705 commented on src/main/java/domain/money/Profit.java
> +    private final double value;
여기도 BigDecimal!

2024-03-17 09:36 UTC, choijy1705 commented on src/main/java/domain/user/Users.java
>                  .count();
1단계에서 리뷰를 안드렸군요!
set자료구조를 활용하여 중복된 이름이 없는지 체크해보는건 어떤가요??

2024-03-17 09:36 UTC, choijy1705 commented on src/main/java/domain/game/Result.java
> +    public static Result bustCompare(boolean current, boolean opponent) {
여기도 파리미터 명 고민해봐주세요!

2024-03-17 09:36 UTC, choijy1705 commented on src/main/java/domain/game/Result.java
>  public enum Result {
Result 클래스가 비대하거나 엄청 이상한 느낌은 없습니다
어떤 부분에서 조악하다고 느끼셨나요??

2024-03-17 09:36 UTC, choijy1705 commented on src/main/java/domain/game/Result.java
> +    private final double profitRate;
얘도 BigDecimal이어야 겠네요

2024-03-17 11:26 UTC, tackyu commented on src/main/java/controller/GameController.java
>      }
맞습니다! 그런데 미션 요구 사항에 인스턴스 변수가 3개 이상이면 안된다는 제약 조건이 있어서
Map으로 만들게끔 설계하였습니다.
또 만약 User의 Money필드가 있다면, setter메서드를 통해서 Money를 받아와야 되지 않을까하는 고민이 있었습니다.
user에 Money필드가 있는게 더 나을까요??

2024-03-17 11:28 UTC, tackyu commented on src/main/java/controller/GameController.java
> +    private void hitOrStayOnce(Game game, Player player) {
player가 한번씩 hitOrStay과정을 거친다고 once를 표기하였는데,
메서드 오버로딩을 하는 것이 더 직관적인 것 같습니다.
감사합니다!

2024-03-17 11:46 UTC, tackyu commented on src/main/java/domain/money/Money.java
> +            throw new NumberFormatException("양의 정수만 입력하세요.");
parseInt에서 throw해야 했던 것인데, 혼동이 있었습니다.
IllegalArgumentException으로 변경하였습니다.
감사합니다!

2024-03-17 12:04 UTC, tackyu commented on src/main/java/domain/money/Money.java
> +        validate();
감사합니다. 모든 검증 이후에 값을 넣어 주는게 더 자연스러운 것 같습니다!

2024-03-17 12:05 UTC, tackyu commented on src/main/java/domain/money/MoneyManager.java
> +    private final Map<Player, Money> bettingManager;
제약조건과 setter 사용에 대한 고민이 있었습니다
필드에 money를 갖는게 더 나을지 궁금합니다!

2024-03-17 12:28 UTC, tackyu commented on src/main/java/domain/user/Users.java
>                  .count();
Set<String> distinctName = new HashSet<>();
        for (Player player : players) {
            distinctName.add(player.getName());
        }
와 같이 변경하였습니다.
stream을 사용했을 때와 비교해서 어떤 이점이 있는건가요??

2024-03-17 12:28 UTC, tackyu commented on src/main/java/domain/game/Result.java
>  public enum Result {
이번 수업에서 상태패턴에 대한 내용이 있었는데, 저는 바로 적용하기에 엄두가 안나서 조건을 하나 하나 검증하도록 하였습니다.
이런 방법이 너무 억지스럽지 않을까에 대한 고민이 있어서 조악스럽다고 느꼈던 것 같습니다

2024-03-17 13:25 UTC, tackyu commented on src/main/java/domain/money/Money.java
> +    private final int value;
양의 실수를 입력값으로 받도록 변경하였고, 돈 관련 타입은 BigDecimal로 변경하였습니다.
새로 알게 되었습니다 감사합니다!

2024-03-17 15:09 UTC, choijy1705 requested changes
빠르게 반영해주셨네요!
질문 남겨주신부분 답변 드렸어요
확인해보시고 반영할지 말지 판단하셔서 다시 요청주세요!

2024-03-17 15:09 UTC, choijy1705 commented on src/main/java/domain/money/Money.java
> +    }
BigDecimal의 메서드를 통해서 굳이 double로 바꾸지 않아도 체크해볼 수 있을것 같습니다!

2024-03-17 15:09 UTC, choijy1705 commented on src/main/java/domain/user/Users.java
>                  .count();
아 지금은 player로 객체를 생성한후 getName을 통해서 이름 중복을 체크하고 있군요...
그렇다면 둘다 반복문을 사용해야해서 큰 차이가 없을것 같네요!
이름을 입력받고 List<String> names 를 사용한다면 바로 new HashSet(names) 로 set을 만들수있어서
시간복잡도를 줄일 수 있을거라 생각했습니다...
지금 구조에서는 크게 개선이 될것 같지는 않네요!

2024-03-18 05:42 UTC, tackyu commented on src/main/java/controller/GameController.java
>      }
name과 money를 따로 받아서 User를 생성하는 방법에 고민이 있었습니다.
User가 money필드를 갖도록 수정하였는데 확인해주실 수 있나요??
감사합니다!

2024-03-18 13:36 UTC, choijy1705 approved these changes
폰드 블랙잭 미션하시느라 고생하셨어요!
잘 구현해주신것 같습니다👍
마이너한 추가 리뷰 남겼는데 확인해주시고
다음 미션도 화이팅입니다!

2024-03-18 13:36 UTC, choijy1705 commented on src/main/java/controller/GameController.java
> +        }
```suggestion
       private Users createUsers(Names names) {
          List<Player> players = new ArrayList<>();
          for (Name name : names.value()) {
              Money money = ExceptionHandler.handle(() -> new Money(InputView.inputBetting(name.value())));
              Player player = new Player(name, money);
              players.add(player);
          }
          return new Users(Collections.unmodifiableList(players));
    }
```
비어있는 players를 파라미터로 받아서 update 하는 로직이 어색한것 같네요
메서드 내에서 완전한 객체를 반환하도록 처리하면 좋을것 같네요

2024-03-18 13:36 UTC, choijy1705 commented on src/main/java/domain/user/User.java
> +    protected final UserDeck userDeck = new UserDeck();
생성자가 아닌 왜 필드에서 초기화하나요?

2024-03-18 13:36 UTC, choijy1705 commented on src/main/java/domain/user/Player.java
> +    private final Money money;
betting 금액인데 Money보다는 다른 네이밍이 더 의미를 잘 전달할것 같네요!

2024-03-18 13:36 UTC, choijy1705 commented on src/main/java/domain/money/MoneyManager.java
> +        Profit profit = new Profit(new BigDecimal("0"));
```suggestion
        Profit profit = new Profit(BigDecimal.ZERO);
```
상수가 있어요!

2024-03-18 13:36 UTC, merged

2024-03-22 04:50 UTC, tackyu commented on src/main/java/controller/GameController.java
> +        }
감사합니다!

2024-03-22 04:52 UTC, tackyu commented on src/main/java/domain/user/User.java
> +    protected final UserDeck userDeck = new UserDeck();
특별히 이유가 있지 않았습니다🥲
생성자에서 초기화하는 것이 더 자연스러운 것 같습니다.

2024-03-22 05:04 UTC, tackyu commented on src/main/java/domain/money/MoneyManager.java
> +        Profit profit = new Profit(new BigDecimal("0"));
새로 알게 되었습니다. 감사합니다!