[2단계 - 블랙잭 베팅] 테바(김성겸) 미션 제출합니다.
woowacourse/java-blackjack pull request #756
Opened 2024-03-17 14:40 UTC by ksk0605

2024-03-18 11:01 UTC, Hyunta requested changes
안녕하세요 테바,
상태패턴을 적용하시느라 고민도 많이하시고 노력하신게 너무 느껴지네요👍🏻
상태들의 구조를 잘 설계해주셔서 흐름 파악하기가 좋았습니다.
관련해서 몇가지 커멘트 남겨놨는데 확인 부탁드립니다!

2024-03-19 15:48 UTC, ksk0605 commented on src/main/java/domain/Players.java
> +                .toList();
수정했습니다! 저도 걸리는 부분이었는데 짚어주셔서 감사합니다 😀
적절한 자료구조를 활용하는 것을 고려하는 연습을 해보겠습니다!

2024-03-19 16:10 UTC, ksk0605 commented on src/main/java/domain/Names.java
> +    private final List<Name> names;
각각의 클래스들의 역할에 따라 적절하게 코드를 배치할 수 있다는 기본적인 장점이 있었습니다. 이때 검증 로직들이 적절하게 분배되었다는 것이 가장 큰 이점이라고 생각합니다. 

플레이어에는 연관된 객체들이 많고 (Name, BetAmount) 등 각각의 객체들이 검증해야하는 데이터의 종류와 검증로직이 달랐습니다. 이것을 특정한 객체에게 모두 위임하게 된다면 가독성, 과도한 책임 등 다양한 문제가 있다고 생각합니다. 

또 Name, Names, BetAmount, Player, Players 순서대로 검증이 진행되기 때문에 비교적 생성 비용이 적은 값 객체들 부터 리스트 순서대로 검증이 이루어지게 됩니다. 때문에 중간에 예외가 발생하더라도 성능적으로 손해를 덜 감수해도 되지 않을까 생각합니다. 

단점이 있다면 생성 자체에 많은 클래스들이 연관되어있어 다른 사람이 한 눈에 생성과정을 파악하기 어려울 수 있겠다는 생각이 듭니다. 

아서는 어떻게 생각하시나요?

2024-03-19 16:10 UTC, ksk0605 commented on src/main/java/domain/BlackjackGame.java
> +    }
감사합니다! 😀

2024-03-19 16:10 UTC, ksk0605 commented on src/main/java/domain/Participant.java
> +    // TODO: protected 는 왜 테스트에서 .으로 접근가능하지? 그래도 되나?
에고 지우고 리뷰요청한다는 것을 그만..🥲 지워놓았습니다!

2024-03-19 16:14 UTC, ksk0605 commented on src/main/java/domain/Player.java
> +        return state instanceof Hit;
객체의 타입 그 자체가 중요한 로직은 아니기에 객체가 스스로 검증하도록 수정하는 것이 좋겠다는 생각이 듭니다! 상태에게 직접 물어볼 수 있도록 수정하였습니다 😀

2024-03-19 16:14 UTC, ksk0605 commented on src/main/java/domain/state/Ready.java
> +        return new Hit(hand);
의견 주신대로 수정해보았습니다!

2024-03-19 16:21 UTC, ksk0605 commented on src/main/java/domain/state/Finished.java
> +public class Finished implements State {
공통된 로직을 가진 상태들을 추상화하는 과정에서 만든 클래스였음에도 추상 클래스를 사용할 생각을 하지 못했군요 🥲

```java
@Override
public boolean isBlackjack() {
    return nulll;
}
```

추상 클래스로 변환하는 과정에서 위와 같이 하위 클래스가 구현해줄 것을 믿고 남겨둔 null 반환하는 안티패턴들 또한 없앨 수 있었습니다. 
따로 인스턴스화 되지 않는 클래스를 적절히 추상화 할 때의 장점을 배울 수 있었습니다! 👍

2024-03-19 16:23 UTC, ksk0605 commented on src/main/java/domain/state/Finished.java
> +    public static final int DEFAULT_RATE = 1;
위와 마찬가지로 추상클래스가 아닌 일반 클래스로 만들어서 생긴 문제입니다 🥲
실제로 작동하지는 않지만 숫자 1로 남겨두는 것보다는 나을 것이라 생각하여 분리한 상수였네요.. 추상 클래스로 변경하며 처리해주었습니다!

2024-03-19 16:44 UTC, ksk0605 commented on src/main/java/domain/state/State.java
> +    State draw(Card card);
저는 State 라는 인터페이스를 활용하여 상태별로 다른 행동을 실행하도록 추상화 함으로써 많은 조건 분기와 중복 코드들을 줄일 수 있다는 것이 가장 큰 매력으로 다가왔네요! 

자칫 Player 가 상황에 따른 각각의 행동들을 일일히 구현하여 가지고 있었다면 Player 가 지나치게 비대해 질 수 있었을 것 같아요. 각각의 분기들을 상태에게 적절히 분배함으로 전체적인 구조가 간결하게 유지되어서 오히려 기존 구조의 수정을 덜 할 수 있었다는 생각이 듭니다 😀

실제 느낀 단점이라면 아무래도 관리할 객체들이 많아진다는 것이었습니다. 상태들이 적절하게 작동하고 변화하고 있는지 확인하기 위해 다양한 상황을 가정하여 많은 테스트 코드들을 작성해야했고 이때 가장 큰 시간적 비용이 들어갔습니다.  

인터페이스, 추상 클래스를 제외하고 5개의 상태들의 작동에도 다양한 조합이 있었고 검증해야하는 것들이 적지 않았으나 이보다 많은 숫자의 상태클래스들이 있다면(혹은 생길 가능성이 있다면) 흐름을 이해하는데 어려워질 수 있겠다는 생각이 듭니다. 

그럼에도 불구하고 이번 미션에는 단점보다는 장점을 더 많이 느꼈고 미션이 해결하고자 하는 문제를 푸는 적절한 디자인 패턴이라는 결론을 내리게 되었습니다. 상태패턴을 직접 써보며 어떤 상황이 상태패턴에 적합할지 생각해볼 수 있는 기회였습니다! 👍

2024-03-20 11:47 UTC, Hyunta commented on src/main/java/domain/Names.java
> +        validate(names);
값을 미리 주입하고 검증하게되면 검증되지 않은 값이 들어갈 수도 있어서,

2024-03-20 12:02 UTC, Hyunta commented on src/main/java/domain/Names.java
> +    private final List<Name> names;
정답이 있는 문제는 아니라고 생각해요ㅎㅎ
오히려 처음에는 테바가 나눠주신 것처럼 모든 것을 객체로 만들어서 책임을 잘게 나누는 연습이 도움이 될 수 있습니다.
그런데 객체지향적인 코드는 항상 장점만 있는 것은 아닙니다. 모든 선택에는 트레이드 오프가 따릅니다.
로직이 단순하다면 객체로 나누는 것보다는 절차지향적으로 짜놓는편이 오히려 가독성이 좋은 코드를 만들 수도 있죠.

제 생각에 Player, Players는 객체로 나누기에 적절한 역할이 필요해요.
Name까지는 고려해볼만하다고 생각합니다. 그런데 Names는 정말 필요할까 생각해봤을 때 저는 개인적으로 만들지 않았을 것 같아요. List<Name> 중복 검증은 Players에서 이뤄져도 충분히 납득이 가거든요.

가독성은 코드가 추상화되어 숨겨져있는 것만을 의미하지 않아요.
만약 플레이어 중복을 허락한다고 요구사항이 변경되면 Name,Names,Player,Players 4가지 객체 중 어떤 객체를 가장 많이 볼까요?
저도 Names를 먼저 볼 것 같고, 확률도 높을 것 같은데, Players를 먼저보는 사람들도 꽤 있을 것 같습니다.
애초에 후보군을 Name, Player, Players로 놓았으면 어땠을까요? 아마 두 비율을 합친 사람들이 확인하지 않을까요?
그렇기 때문에 네이밍이 중요하고 응집도 높은 코드를 작성하라는 가이드라인을 제시합니다.
만약 비슷한 역할의 객체가 많아지게 되면 문제가 발생했을 때 어떤 코드를 봐야할지 파악하기가 어려워집니다.

위에서 말한 것처럼 지금은 객체를 나누는 연습을 하는 과정이기 때문에 당연히 안나누는 것보다는 나눠보는게 낫다고 생각합니다.
그런데 그런 고민은 한번 해보세요, 이게 정말 필요한 클래스인지? 판단하기가 어렵다면 요구사항이 변경됐다고 가정해보고 내 코드를 모르는 사람이 봤을때 여기에 로직이 있다는 것을 빠르게 확인할 수 있을까? 이런 고민을 하다보면 점점 더 객체 설계에 대한 인사이트가 늘어날 수 있을 것 같습니다ㅎㅎ

절대 지금 잘못하셨다는 의미는 아니었습니다,
한번 다른 관점에서도 고민해보셨으면 하는 바람에 드린 피드백이었습니다!
지금처럼 객체를 나눠보는 연습을 우테코 과정에서 많이 경험하면서 성장하시길 바랍니다💪🏻

2024-03-20 12:05 UTC, Hyunta commented on src/main/java/domain/state/State.java
> +    State draw(Card card);
구조를 바꾼다는게 정말 공수가 많이 드는 작업인데 훌륭하게 진행해주신 것 같습니다!
느끼신 장단점도 많이 공감이 되네요ㅎㅎ
체스 미션하시면서 해당 경험이 도움이 되셨으면 좋겠습니다!

2024-03-20 12:09 UTC, Hyunta approved these changes
안녕하세요 테바,
상태 패턴을 배우고 바로 적용하는 시도가 인상적이었습니다!
더 좋은 코드를 위해서 고민을 하시는 점도 많이 느껴졌어요ㅎㅎ
남겨주신 질문에 답변 드렸는데 혹시 더 궁금하신점이 있으면 DM 주세요!
남은 미션들도 잘 수행해내시길 응원하겠습니다💪🏻

2024-03-20 12:09 UTC, merged